Add ICorDebug documentation for framework interfaces
dotnet/docs pull request #10006
Opened 2019-01-16 01:29 UTC by hoyosjs

## Summary

Add documentation @cshung wrote on several methods and interfaces in the CLRs Debugger APIs

/cc: @tommcdon @noahfalk

2019-01-16 22:52 UTC, rpetrusha requested changes
Thanks for documenting these, @hoyosjs.  I've added several comments and made a number of suggestions. In addition, the following should be added to the documentation:
- The toc (<https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/toc.md>) should be updated to reflect the new types and members.
- The Debugging Interfaces (<https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/debugging-interfaces.md>) and Debugging Structures (<https://github.com/dotnet/docs/blob/master/docs/framework/unmanaged-api/debugging/debugging-structures.md>) topics should be updated to list the new interfaces and structures documented in this PR.
- Each member should have a **System Requirements** section.  This has the following form:
   ```
   # Requirements  
    **Platforms:** See [System Requirements](../../../../docs/framework/get-started/system-requirements.md).  
  
    **Header:** CorPub.idl, CorPub.h  
  
     **Library:** CorGuids.lib  
  
     **.NET Framework Versions:** [!INCLUDE[net_current_v10plus](../../../../includes/net-current-v10plus-md.md)]  
   ```
   Assuming that these APIs are all new to .NET Framework 4.8, this also requires adding a token to the github.com/dotnet/docs/includes directory named net_current_v48plus whose text is "Available since 4.8"

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-enuminstance-method.md
> +Enumerate instances of this definition.
```suggestion
Enumerates instances of this definition.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-interface.md
> +Provide methods for querying information about a method definition.
```suggestion
Provides methods for querying information about a method definition.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-interface.md
> +|------------------|---------------------------------------------|
Each of the method names should link to the documentation for that method.

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-interface.md
> +|StartEnumInstances|Start enumerate instances of this definition.|
Starts enumerating instances of this definition -- ?

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-interface.md
> +|EnumInstance      |Enumerate instances of this definition.      |
```suggestion
|EnumInstance      |Enumerates instances of this definition.      |
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-interface.md
> +|EndEnumInstances  |End enumerate instances of this definition.  |
Ends enumerating instances of this definition -- ?

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethoddefinition-startenuminstances-method.md
> +Start enumerate instances of this definition.
Starts enumerating instances of this definition -- ?

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethodinstance-getiladdressmap-method.md
> +Get the IL to address mapping information.
```suggestion
Gets the IL to address mapping information.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethodinstance-interface.md
> +Provide methods for querying information about a method instance.
```suggestion
Provides methods for querying information about a method instance.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamethodinstance-interface.md
> +|GetILAddressMap|Get the IL to address mapping information.   |
```suggestion
|[GetILAddressMap](ixclrdatamethodinstance-getiladdressmap-method.md)|Gets the IL to address mapping information.   |
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamodule-getmethoddefinitionbytoken-method.md
> +Get a method definition by metadata token.
```suggestion
Gets the method definition for a specified metadata token.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamodule-getversionid-method.md
> +Get the module's version ID.
```suggestion
Gets the module's version identifier.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamodule-getversionid-method.md
> +[out] The module's version ID.
```suggestion
[out] The module's version identifier.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamodule-interface.md
> +Provide methods for querying information about a loaded module.
```suggestion
Provides methods for querying information about a loaded module.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamodule-interface.md
> +|--------------------------|------------------------------------------|
The members should link to the member documentation. The "Get" in each member definition should be "Gets".

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdatamodule-interface.md
> +|GetMethodDefinitionByToken|Get a method definition by metadata token.|
by --> for a

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-endenummethodinstancesbyaddress-method.md
> +End enumerate method instances of this process by an address.
Ends enumerating method instances of this process by address -- ?
The definition is unclear.

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-endenummodules-method.md
> +End enumerate modules of this process.
The definition is unclear. Ends enumerating the modules...?

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-enummodule-method.md
> +Enumerate modules of this process.
```suggestion
Enumerates the modules of this process.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-getappdomainbyuniqueid-method.md
> +Get the AppDomain by its unique id.
```suggestion
Gets an AppDomain based on its unique identifier.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-interface.md
> +Provide methods for querying information about a process.
```suggestion
Provides methods for querying information about a process.
```

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-interface.md
> +|---------------------------------|--------------------------------------------------------------------|
The member names should link to the member documentation.
The member descriptions should correspond to those in the member documentation.

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-startenummethodinstancesbyaddress-method.md
> +Start enumerate method instances of this process by an address.
Starts enumerating the method instances of this process by address. -- ?

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-startenummethodinstancesbyaddress-method.md
> +### Parameters
"instances" rather than "instance" in the parameter descriptions?

2019-01-16 22:52 UTC, rpetrusha commented on docs/framework/unmanaged-api/debugging/ixclrdataprocess-startenummodules-method.md
> +Start enumerate modules of this process.
Starts enumerating the modules of this process -- ?

2019-01-17 00:00 UTC, hoyosjs commented
Hey @rpetrusha, I've added some metadata and footers as well as some other fixes. Will add the data to the TOC and other indices now.

2019-01-17 01:41 UTC, noahfalk commented
Just fyi @rpetrusha, this documentation is a bit atypical.
1) The APIs have existed in previously shipped .NET Framework versions, but they were considered internal and undocumented. We are now documenting them so that 3rd parties can retroactively make use of them.
2) We are not documenting all the APIs/types in the relevant interfaces, only the subset that we'd like to support. If we were writing the APIs from scratch we would factor the interfaces appropriately but since the APIs already exist this means we have some internal APIs and some public APIs intermingled on the same interface. Its awkward, but unavoidable.
3) These APIs are not defined in any public SDK header.

2019-01-17 02:15 UTC, rpetrusha commented
Thanks for the context, @noahfalk. And thanks for adding the additional sections, @hoyosjs. I've also corrected some broken links from the last commit, @hoyosjs.

2019-01-19 02:22 UTC, rpetrusha approved these changes

2019-01-19 03:25 UTC, merged