Better explain managed assembly names in .NET Core hosting docs
dotnet/docs pull request #10024
Opened 2019-01-17 04:17 UTC by mjrousos

## Summary

.NET Core hosting APIs (`CreateDelegate`) take a managed assembly name as a parameter. Along with dotnet/samples#576, this updates .NET Core hosting docs to briefly explain and link to information on what a managed assembly name is.

Fixes dotnet/docs#7536

2019-01-17 16:33 UTC, rpetrusha commented
Closing and reopening to begin new build.

2019-01-17 16:38 UTC, rpetrusha requested changes
The link to the assembly names topic needs to be a relative file path rather than an URL, @mjrousos. Once you make that correction, I'll merge.

2019-01-17 16:38 UTC, rpetrusha commented on docs/core/tutorials/netcore-hosting.md
> +With the runtime started, the host can call managed code. This can be done in a couple of different ways. The sample code linked to this tutorial uses the `coreclr_create_delegate` function to create
This and the link on line 191 should be relative links rather than an URL: ../../framework/app-domains/assembly-names.md

2019-01-17 23:07 UTC, mjrousos commented
I've fixed the links to be relative.

2019-01-18 16:15 UTC, rpetrusha commented
Thanks for making the additional changes, @mjrousos. I'll merge now.

2019-01-18 16:15 UTC, rpetrusha approved these changes

2019-01-18 16:15 UTC, merged