Update references-and-the-imports-statement.md
dotnet/docs pull request #10125
Opened 2019-01-24 06:07 UTC by imba-tjd

2019-01-24 18:14 UTC, rpetrusha requested changes
Thanks for correcting all of the formatting issues, @imba-tjd. I've left a number of suggested changes.

2019-01-24 18:14 UTC, rpetrusha commented on docs/standard/data/xml/xslt-compiler-xsltc-exe.md
> + The xsltc.exe tool does not validate the class (`/class:` `name`) or assembly (`/out:` `assemblyName`) names. Errors are thrown by the common language runtime if the names are not valid.
```suggestion
 The xsltc.exe tool does not validate the class (`/class:`*name*) or assembly (`/out:`*assemblyName*) names. Errors are thrown by the common language runtime if the names are not valid.  
```

2019-01-24 18:14 UTC, rpetrusha commented on docs/visual-basic/language-reference/objects/my-resources-object.md
> + The properties of the `My.Resources` object provide read-only access to your application's resources. To add or remove resources, use the **Project Designer**. You can access resources added through
```suggestion
 The properties of the `My.Resources` object provide read-only access to your application's resources. To add or remove resources, use the **Project Designer**. You can access resources added through the **Project Designer** by using `My.Resources.`*resourceName*.  
```

2019-01-24 18:14 UTC, rpetrusha commented on docs/visual-basic/language-reference/objects/my-resources-object.md
> + You can also add or remove resource files by selecting your project in **Solution Explorer** and clicking **Add New Item** or **Add Existing Item** from the **Project** menu. You can access resource
```suggestion
 You can also add or remove resource files by selecting your project in **Solution Explorer** and clicking **Add New Item** or **Add Existing Item** from the **Project** menu. You can access resources added in this manner by using `My.Resources.`*resourceFileName*`.`*resourceName*.  
```

2019-01-24 18:14 UTC, rpetrusha commented on docs/visual-basic/language-reference/xml-axis/xml-child-axis-property.md
> +|`child`|Required. Name of the child nodes to access, of the form [`prefix:`]`name`.<br /><br /> -   `Prefix` - Optional. XML namespace prefix for the child node. Must be a global XML namespace defin
```suggestion
|`child`|Required. Name of the child nodes to access, of the form [`prefix:]name`.<br /><br /> -   `Prefix` - Optional. XML namespace prefix for the child node. Must be a global XML namespace defined with an `Imports` statement.<br />-   `Name` - Required. Local child node name. See [Names of Declared XML Elements and Attributes](../../../visual-basic/programming-guide/language-features/xml/names-of-declared-xml-elements-and-attributes.md).|  
```

2019-01-24 18:14 UTC, rpetrusha commented on docs/visual-basic/language-reference/xml-axis/xml-descendant-axis-property.md
> + Required. Name of the descendant nodes to access, of the form [`prefix:`]`name`.
```suggestion
 Required. Name of the descendant nodes to access, of the form [`prefix:]name`.  
```

2019-01-24 18:14 UTC, rpetrusha commented on docs/visual-basic/programming-guide/program-structure/references-and-the-imports-statement.md
> + `Imports` [`Aliasname` =] `Namespace`
```suggestion
 `Imports [Aliasname =] Namespace`  
```

2019-01-25 07:12 UTC, imba-tjd commented
I have accepted all of these changes, although in the middle I changed target branch and force-pushed once:joy:

2019-01-25 20:12 UTC, rpetrusha approved these changes

2019-01-25 20:12 UTC, rpetrusha commented
Thanks for making the additional changes, @imba-tjd. I'll merge your PR now.

2019-01-25 20:12 UTC, merged