Task 1409923: Content refresh for windows services install
dotnet/docs pull request #10214
Opened 2019-01-29 03:10 UTC by dksimpson

## Summary

Part of .NET content refresh for 20 high traffic items.

Task: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1409923/

2019-02-05 01:24 UTC, rpetrusha requested changes
Thanks for revising this article, @dksimpson. I've left some suggestions for additional changes.

2019-02-06 02:57 UTC, dksimpson commented
Thanks for your comments, @rpetrusha. I've made all the changes that you suggested.

2019-02-06 18:11 UTC, rpetrusha approved these changes

2019-02-06 18:11 UTC, rpetrusha commented
Thanks for making the additional set of changes, @dksimpson. I'll merge your PR now.

2019-02-06 18:11 UTC, merged