1436790/1438462: Part 6: 30 files with MSDN link fixes.
dotnet/docs pull request #10261
Opened 2019-02-01 03:12 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

2019-02-01 20:04 UTC, mairaw requested changes
Looks good @DennisLee-DennisLee. Left some comments for you though. Thanks!

2019-02-01 20:04 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/collections.md
> + You can define a collection by implementing the <xref:System.Collections.Generic.IEnumerable%601> or <xref:System.Collections.IEnumerable> interface. For additional information, see [Enumerating a C
```suggestion
 You can define a collection by implementing the <xref:System.Collections.Generic.IEnumerable%601> or <xref:System.Collections.IEnumerable> interface. For additional information, see [Enumerating a Collection](https://docs.microsoft.com/previous-versions/dotnet/netframework-4.0/hwyysy67(v=vs.100)).
```

2019-02-01 20:04 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/object-lifetime-how-objects-are-created-and-destroyed.md
> +- [Initialization and Termination of Components](https://docs.microsoft.com/previous-versions/ws9dc6t6(v=vs.140))
```suggestion
- [Initialization and Termination of Components](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2013/ws9dc6t6(v=vs.120))
```

2019-02-01 20:04 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/operators-and-expressions/index.md
> + For more information and examples, see [Operator Overloading in Visual Basic 2005](https://docs.microsoft.com/previous-versions/ms379613(v=vs.80)).
remove this sentence

```suggestion
```

2019-02-01 20:04 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/procedures/how-to-define-an-operator.md
> + For more information and examples, see [Operator Overloading in Visual Basic 2005](https://docs.microsoft.com/previous-versions/ms379613(v=vs.80)).
```suggestion
```

2019-02-01 20:04 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/procedures/operator-procedures.md
> + For more information and examples, see [Operator Overloading in Visual Basic 2005](https://docs.microsoft.com/previous-versions/ms379613(v=vs.80)).
```suggestion
```

2019-02-01 22:18 UTC, DennisLee-DennisLee commented on docs/visual-basic/misc/source-name-specified-in-eventlogsource-is-registered-to-another-log.md
> +- [Administering Event Logs](https://docs.microsoft.com/previous-versions/4f69axw4(v=vs.100))
Sorry, the trick had been working for me before, so I was curious why it was failing so often in this PR. I don't have a sense of how often that trick should be successful. (To be sure, we don't need to bother with version numbers higher than what the redirect shows?)

I think I forgot to add the period between the "vs" and the version number here. That's probably why the trick wasn't working for me.

2019-02-02 00:33 UTC, DennisLee-DennisLee commented
#sign-off

2019-02-04 23:50 UTC, mairaw approved these changes
Thank you @DennisLee-DennisLee! 🚀

2019-02-04 23:50 UTC, merged