Improve debugging interfaces documentation for .NET Framework
dotnet/docs pull request #10284
Opened 2019-02-02 02:58 UTC by hoyosjs

## Summary

Adds further documentation for .NET Framework's debugging API. 

cc: @tommcdon @noahfalk @cshung

2019-02-03 07:50 UTC, tommcdon commented on docs/framework/unmanaged-api/debugging/dacpmethoddescdata-structure.md
> +| `cJittedRejitVersions`       | Number of                                                                                       |
Incomplete sentence

2019-02-06 00:00 UTC, rpetrusha requested changes
This looks really good, @hoyosjs. I've left some comments and suggestions.

2019-02-06 03:01 UTC, hoyosjs reviewed
@rpetrusha Thanks for the review. I think I addressed most of your comments, unless what was in said documents was as intended.

2019-02-06 03:40 UTC, tommcdon approved these changes

2019-02-06 23:45 UTC, rpetrusha approved these changes

2019-02-06 23:46 UTC, rpetrusha commented
Thanks both for creating this documentation and addressing my comments, @hoyosjs. I'll merge your PR now. It should be live on docs.microsoft.com in the next day or two.

2019-02-06 23:46 UTC, merged