Byte can be simplified to byte
dotnet/docs pull request #10294
Opened 2019-02-02 22:35 UTC by hassanhabib

## Simplify Byte

Using ``` byte ``` instead of ``` Byte ```.

2019-02-03 21:10 UTC, rpetrusha requested changes
Thanks for contributing to the dotnet/docs repo, @hassanhabib. If Byte is changed to byte in the variable declaration, it should also be changed in the comment.

2019-02-03 21:10 UTC, rpetrusha commented on docs/csharp/programming-guide/types/index.md
>  // Static method on type Byte.
```suggestion
// Static method on type byte.  
```

2019-02-04 04:57 UTC, hassanhabib commented on docs/csharp/programming-guide/types/index.md
>  // Static method on type Byte.
Good catch! thanks. fixed.

2019-02-04 17:23 UTC, rpetrusha approved these changes

2019-02-04 17:24 UTC, rpetrusha commented
Thank you for making the additional change, @hassanhabib. We'll merge your PR now.

2019-02-04 17:24 UTC, merged