Visual Studio Tools for Docker How-To
dotnet/docs pull request #1035
Opened 2016-09-19 16:30 UTC by spboyer

# Title
Using Visual Studio Tools for Docker 

## Summary
Introduction to Visual Studio Tools for Docker 

Developing and debugging your application in a Docker container can be a ceremony of tasks to get setup with various tools. [Visual Studio Tools for Docker](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4) helps you get past the hurdles and find the bugs using F5 to debug your application directly in a locally hosted Docker Container. 

More content for #806 

## Suggested Reviewers

@stevelasker @glennc @BillWagner

2016-09-19 16:30 UTC, dnfclas commented
Hi __@spboyer__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by .NET Foundation and real humans are currently evaluating your PR.</p>

TTYL, DNFBOT;

2016-09-19 16:44 UTC, dnfclas commented
Hi __@spboyer__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by .NET Foundation and real humans are currently evaluating your PR.</p>

TTYL, DNFBOT;

2016-09-19 16:58 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1035](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1035)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C19%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609191644541542-1035%5Cworkflow_report.html).

2016-09-19 17:38 UTC, mairaw commented on docs/core/docker/visual-studio-tools-for-docker.md
> +- [Microsoft .NET Core 1.0.1 RTM VS 2015 Tooling Preview 2, with the 1.0.1 updates](https://go.microsoft.com/fwlink/?LinkID=827546)
do you need to say this "with the 1.0.1 updates"?

2016-09-19 17:41 UTC, mairaw commented on docs/core/docker/visual-studio-tools-for-docker.md
> +title: Visual Studio Tools for Docker
there's something odd with this topic. You restart the topic several times with metadata sections in the middle of the text.

2016-09-19 17:43 UTC, mairaw requested changes
The new topic is broken. Please fix that and then we can proceed with the review of this topic.

2016-09-19 18:01 UTC, spboyer commented
@mairaw sorry about that, local merge must have gotten screwy. Fixed.

2016-09-19 18:04 UTC, mairaw commented
No worries @spboyer. It was just hard to read like that. :smile:

2016-09-19 18:12 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1035](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1035)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C19%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609191759470990-1035%5Cworkflow_report.html).

2016-09-19 18:36 UTC, spboyer commented on docs/core/docker/visual-studio-tools-for-docker.md
> +- [Microsoft .NET Core 1.0.1 RTM VS 2015 Tooling Preview 2, with the 1.0.1 updates](https://go.microsoft.com/fwlink/?LinkID=827546)
I dont think that's overly important, but up to @stevelasker to comment

2016-09-19 22:36 UTC, mairaw commented on docs/core/docker/visual-studio-tools-for-docker.md
> +- [Microsoft .NET Core 1.0.1 RTM VS 2015 Tooling Preview 2, with the 1.0.1 updates](https://go.microsoft.com/fwlink/?LinkID=827546)
I was mostly thinking about the right branding which would be ".NET Core 1.0.1 - VS 2015 Tooling Preview 2".

2016-09-19 22:41 UTC, mairaw commented on docs/core/docker/visual-studio-tools-for-docker.md
> +Using Visual Studio, create a new ASP.NET Core Web Application. When the application is loaded, either select **Add Docker Support** from the **Project Menu** or right click the project from the Solu
nit: Add and Docker Support in the end should also be bold.

2016-09-20 02:01 UTC, BillWagner commented on docs/core/docker/visual-studio-tools-for-docker.md
> +Download and install the [Visual Studio Tools for Docker](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4) from the [Visual Studio Gallery](http://visualstudiogall
You can also search for it in the Extensions window in VS, right?

2016-09-20 02:02 UTC, BillWagner commented on docs/core/docker/visual-studio-tools-for-docker.md
> +The following files are added the to the project.
typo: "added the to the" -> "added to the"

2016-09-20 02:09 UTC, BillWagner commented on docs/core/docker/visual-studio-tools-for-docker.md
> +- **Dockerfile**: the Docker file for ASP.NET Core applications is based on the [microsoft/aspnetcore](https://hub.docker.com/r/microsoft/aspnetcore) image. This image includes the ASP.NET Core NuGet
Would it be better to say that the FROM will reference the most recent version? That would make it more resilient to nwe .NET Core versions.

2016-09-20 02:10 UTC, BillWagner requested changes
Overall, this is great. I commented on a typo or two to fix, and a couple content suggestions.

2016-09-20 12:12 UTC, spboyer commented on docs/core/docker/visual-studio-tools-for-docker.md
> +Download and install the [Visual Studio Tools for Docker](https://visualstudiogallery.msdn.microsoft.com/0f5b2caa-ea00-41c8-b8a2-058c7da0b3e4) from the [Visual Studio Gallery](http://visualstudiogall
Added

2016-09-20 12:12 UTC, spboyer commented on .gitignore
> +.vscode/
ok, will remove this

2016-09-20 12:13 UTC, spboyer commented on docs/core/docker/visual-studio-tools-for-docker.md
> +The following files are added the to the project.
fixed

2016-09-20 12:14 UTC, spboyer commented on docs/core/docker/visual-studio-tools-for-docker.md
> +- **Dockerfile**: the Docker file for ASP.NET Core applications is based on the [microsoft/aspnetcore](https://hub.docker.com/r/microsoft/aspnetcore) image. This image includes the ASP.NET Core NuGet
sure, makes sense.

2016-09-20 12:17 UTC, spboyer commented on docs/core/docker/visual-studio-tools-for-docker.md
> +- [Microsoft .NET Core 1.0.1 RTM VS 2015 Tooling Preview 2, with the 1.0.1 updates](https://go.microsoft.com/fwlink/?LinkID=827546)
Made the change.

2016-09-20 12:21 UTC, spboyer commented on docs/core/docker/visual-studio-tools-for-docker.md
> +Using Visual Studio, create a new ASP.NET Core Web Application. When the application is loaded, either select **Add Docker Support** from the **Project Menu** or right click the project from the Solu
fixed

2016-09-20 12:21 UTC, spboyer commented
@mairaw @BillWagner - fixed nits

2016-09-20 12:29 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1035](https://review.docs.microsoft.com/en-us/dotnet/articles/core/docker/visual-studio-tools-for-docker?branch=pr-en-us-1035)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609201217511028-1035%5Cworkflow_report.html).

2016-09-20 13:45 UTC, BillWagner approved these changes

2016-09-20 16:59 UTC, mairaw approved these changes

2016-09-20 17:01 UTC, merged