1436790/1438462: Part 16: 20 files with MSDN link fixes.
dotnet/docs pull request #10376
Opened 2019-02-08 03:58 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

2019-02-08 23:47 UTC, mairaw requested changes
Thanks @DennisLee-DennisLee. A few comments before we can merge.

2019-02-08 23:47 UTC, mairaw commented on docs/framework/data/wcf/data-service-versioning-wcf-data-services.md
> + By default, WCF Data Services uses version 1.1 of CSDL to represent a data model. This is always the case for data models that are based on either a reflection provider or a custom data service prov
```suggestion
 By default, WCF Data Services uses version 1.1 of CSDL to represent a data model. This is always the case for data models that are based on either a reflection provider or a custom data service provider. However, when the data model is defined by using the [!INCLUDE[adonet_ef](../../../../includes/adonet-ef-md.md)], the version of CSDL returned is the same as the version that is used by the [!INCLUDE[adonet_ef](../../../../includes/adonet-ef-md.md)]. The version of the CSDL is determined by the namespace of the [Schema element (CSDL)](/ef/ef6/modeling/designer/advanced/edmx/csdl-spec#schema-element-csdl).
```

2019-02-09 00:47 UTC, DennisLee-DennisLee commented
#sign-off

2019-02-09 00:58 UTC, mairaw approved these changes
Looks good! Thanks @DennisLee-DennisLee ❄️

2019-02-09 00:58 UTC, merged