Task 1409890: Refresh of .NET article, View certificates with MMC
dotnet/docs pull request #10394
Opened 2019-02-08 23:26 UTC by dksimpson

## Summary

Task 1409890: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1409890/

Verify content freshness and update procedures.

2019-02-09 02:06 UTC, dksimpson commented
Hi @rpetrusha, I've finished my updates - ready for your review.

2019-02-21 00:29 UTC, rpetrusha requested changes
Thanks for updating this article, @dksimpson. I've left a number of suggested changes.

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +When you create a secure client or service, you can use a [certificate](working-with-certificates.md) as the credential. For example, a common type of credential is the X.509 certificate, which you c
```suggestion
When you create a secure client or service, you can use a [certificate](working-with-certificates.md) as the credential. For example, a common type of credential is the X.509 certificate, which you create with the <xref:System.ServiceModel.Security.X509CertificateInitiatorClientCredential.SetCertificate%2A?displayProperty=nameWithType> method. 
```

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +There are three different types of certificate stores that you can examine with the Microsoft Management Console (MMC):
```suggestion
There are three different types of certificate stores that you can examine with the Microsoft Management Console (MMC) on Windows systems:
```

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +- Local computer: Store is local to the device and global to all users on the device.
```suggestion
- Local computer: The store is local to the device and global to all users on the device.
```

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +- Current user: Store is local to the current user account on the device.
```suggestion
- Current user: The store is local to the current user account on the device.
```

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +- Service account: Store is local to a particular service on the device.
```suggestion
- Service account: The store is local to a particular service on the device.
```

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +## To view certificates in the MMC snap-in
```suggestion
## View certificates in the MMC snap-in 
```

2019-02-21 00:29 UTC, rpetrusha commented on docs/framework/wcf/feature-details/how-to-view-certificates-with-the-mmc-snap-in.md
> +2. To view your certificates, under **Certificates - Current User** in the left pane, expand the directory for the type of certificate you want to view.
```suggestion
2. To view your certificates, under **Certificates - Current User** in the left pane, and expand the directory for the type of certificate you want to view.
```

2019-02-21 17:17 UTC, Lxiamail approved these changes
With Ron's suggestion, I have no additional feedback.

2019-02-26 03:11 UTC, dksimpson commented
Hi @rpetrusha, I've incorporated your review comments - ready to merge.

2019-02-28 16:52 UTC, rpetrusha approved these changes

2019-02-28 16:53 UTC, rpetrusha commented
Thanks for the additional changes, @dksimpson. I'll merge your PR now.

2019-02-28 16:53 UTC, merged