1436790/1438462: Part 24: 20 files with MSDN link fixes.
dotnet/docs pull request #10442
Opened 2019-02-12 23:09 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

2019-02-12 23:09 UTC, DennisLee-DennisLee commented
Again this PR mostly contains changes to the same recurring paragraph.

2019-02-13 18:31 UTC, rpetrusha requested changes
This looks good, @DennisLee-DennisLee I've left one suggested change, and thought two of the cross-references could be eliminated.

2019-02-13 18:31 UTC, rpetrusha commented on docs/framework/winforms/controls/how-to-design-a-windows-forms-layout-that-responds-well-to-localization.md
>  1.  [How to: Align and Stretch a Control in a TableLayoutPanel Control](how-to-align-and-stretch-a-control-in-a-tablelayoutpanel-control.md)
```suggestion
## Additional resources
1.  [How to: Align and Stretch a Control in a TableLayoutPanel Control](how-to-align-and-stretch-a-control-in-a-tablelayoutpanel-control.md)  
```
A nit unrelated to your PR: it's unclear why the code is immediately followed by a list of articles, so I thought adding a header would be a good idea.

2019-02-13 18:31 UTC, rpetrusha commented on docs/framework/winforms/controls/how-to-display-an-insertion-mark-in-a-windows-forms-listview-control.md
> +- [Windows XP Features and Windows Forms Controls](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/06da8ztk(v=vs.100))
This item can be deleted.

2019-02-13 18:31 UTC, rpetrusha commented on docs/framework/winforms/controls/how-to-enable-tile-view-in-a-windows-forms-listview-control.md
> +- [Windows XP Features and Windows Forms Controls](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/06da8ztk(v=vs.100))
This item can be deleted.

2019-02-13 19:41 UTC, rpetrusha approved these changes

2019-02-13 19:41 UTC, rpetrusha commented
Thanks for making the additional changes, @DennisLee-DennisLee. I'll merge your PR now.

2019-02-13 19:41 UTC, merged