1436790/1438462: Part 23: 20 files with MSDN link fixes.
dotnet/docs pull request #10441
Opened 2019-02-12 22:04 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

2019-02-12 22:07 UTC, DennisLee-DennisLee commented
There are basically just 2 changes here, repeated over several files:
* Splitting the **Walkthrough: Embedding Type Information from Microsoft Office Assemblies** link into separate C# and VB article links.
* Replacing the paragraph I mentioned in part 19 (PR #10421) with the new version, which deleted the last paragraph and converted the two tilde links into the regular-style relative links.

2019-02-12 23:56 UTC, mairaw requested changes
Looks great @DennisLee-DennisLee. One little thing and we can merge.

2019-02-12 23:56 UTC, mairaw commented on docs/csharp/programming-guide/interop/walkthrough-office-programming.md
> +- [Walkthrough: Embedding Type Information from Microsoft Office Assemblies in Visual Studio (Visual Basic)](../../../visual-basic/programming-guide/concepts/assemblies-gac/walkthrough-embedding-type
Let's keep this one out since we're in the C# guide here 

```suggestion
```

2019-02-13 01:01 UTC, mairaw approved these changes

2019-02-13 01:02 UTC, merged