Use ICLRRuntimeHost4
dotnet/docs pull request #10466
Opened 2019-02-14 05:28 UTC by NextTurn

Related to dotnet/samples#635 

Uses space alignment to prevent the code block from being rendered differently.

/cc @mjrousos

2019-02-16 01:31 UTC, rpetrusha requested changes
Thanks, @NextTurn, for making this update. I've left two suggestions for changes; we've been trying to replace gerunds ("Creating...") with imperatives ("Create...") in titles and headers.

2019-02-16 01:31 UTC, rpetrusha commented on docs/core/tutorials/netcore-hosting.md
> +## Creating a host using CoreClrHost.h
```suggestion
## Create a host using CoreClrHost.h
```
Our current style guide calls for using an imperative rather than a gerund.

2019-02-16 01:31 UTC, rpetrusha commented on docs/core/tutorials/netcore-hosting.md
>  ### Step 4 - Setting startup flags and starting the runtime
```suggestion
### Step 4 - Set startup flags and starting the runtime
```

2019-02-20 05:10 UTC, NextTurn commented
@rpetrusha Is this style guide contained in `microsoft-style-guide` repo? I can't find it there.

2019-02-20 20:58 UTC, rpetrusha commented
It's in the [template](https://github.com/dotnet/docs/blob/master/styleguide/template.md), @NextTurn.

2019-02-20 21:18 UTC, rpetrusha approved these changes

2019-02-20 21:19 UTC, rpetrusha commented
Thanks, @NextTurn, both for the PR and the additional changes. I'll merge now.

2019-02-20 21:19 UTC, merged

2019-02-21 05:54 UTC, NextTurn commented
Is it the one in the [File name](https://github.com/dotnet/docs/blob/master/styleguide/template.md#file-name) section? Does the rule below about small words also apply to titles?

https://github.com/dotnet/docs/blob/481c63c7a3f411aca1a73d8c1ba98a7df0e95518/styleguide/template.md#L63-L64

2019-02-21 21:07 UTC, rpetrusha commented
I think it depends on the title and whether it makes sense without the small word, @NextTurn.