Update the dotnet vstest doc
dotnet/docs pull request #10491
Opened 2019-02-15 08:22 UTC by singhsarab

Removed the reference to coded ui.
Fixed the message for parallel.
Removed Framework35 from the supported frameworks.

2019-02-15 08:23 UTC, singhsarab commented
@PBoraMSFT

2019-02-15 08:44 UTC, PBoraMSFT commented
Looks good to me, @singhsarab

2019-02-21 00:19 UTC, rpetrusha requested changes
Thanks, @singhsarab. I've suggested some minor changes. You can submit them as a batch by reviewing them from the Files tab.

2019-02-21 00:19 UTC, rpetrusha commented on docs/core/tools/dotnet-vstest.md
> +Execute tests in parallel. By default, all available cores on the machine are available for use. Specify explicit number of cores by setting MaxCpuCount property under the RunConfiguration node in th
```suggestion
Execute tests in parallel. By default, all available cores on the machine are available for use. Specify an explicit number of cores by setting the MaxCpuCount property under the RunConfiguration node in the runsettings file.
```

2019-02-21 00:19 UTC, rpetrusha commented on docs/core/tools/dotnet-vstest.md
> +Execute tests in parallel. By default, all available cores on the machine are available for use. Specify explicit number of cores by setting MaxCpuCount property under the RunConfiguration node in th
```suggestion
Execute tests in parallel. By default, all available cores on the machine are available for use. Specify an explicit number of cores by setting the MaxCpuCount property under the RunConfiguration node in the runsettings file.
```

2019-02-21 00:19 UTC, rpetrusha commented on docs/core/tools/dotnet-vstest.md
> +Execute tests in parallel. By default, all available cores on the machine are available for use. Specify explicit number of cores by setting MaxCpuCount property under the RunConfiguration node in th
```suggestion
Execute tests in parallel. By default, all available cores on the machine are available for use. Specify an explicit number of cores by setting the MaxCpuCount property under the RunConfiguration node in the runsettings file.
```

2019-02-22 08:41 UTC, singhsarab commented
@rpetrusha Can you please review and approve. Thanks.

2019-02-22 20:57 UTC, rpetrusha approved these changes

2019-02-22 20:58 UTC, rpetrusha commented
Thanks for making the additional changes, @singhsarab. I'll merge your PR now. The changes should be live on docs.microsoft.com in the next day or two.

2019-02-22 20:58 UTC, merged

2019-02-25 09:00 UTC, singhsarab commented
@rpetrusha Thanks Ron.