Noting what members it returns
dotnet/docs pull request #10535
Opened 2019-02-18 01:36 UTC by JackTrapper

EnumMembers only returns fields and methods, and does not return properties or events.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-02-22 03:52 UTC, noahfalk approved these changes

2019-02-22 04:17 UTC, mairaw requested changes
Thanks for your PR @JackTrapper and for the review again @noahfalk. I have just a small suggestion.

2019-02-22 04:17 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-enummembers-method.md
> + Properties and events are not enumerated by **EnumMembers**. In order to enumerate those use **EnumProperties** or **EnumEvents**.
```suggestion
 Properties and events are not enumerated by **EnumMembers**. To enumerate those, use **EnumProperties** or **EnumEvents**.
```

2019-02-25 19:48 UTC, mairaw approved these changes
Thanks @JackTrapper. I've applied the feedback and also made some minor changes. I'll merge once build finishes successfully. Thanks for your contributions!

2019-02-25 19:57 UTC, merged