Noting that it returns mdInterfaceImpl tokens
dotnet/docs pull request #10547
Opened 2019-02-18 20:19 UTC by JackTrapper

- it returns mdInterfaceImpl tokens
- properties of the interface implementations can be queries with GetInterfaceImplProps

2019-02-22 03:53 UTC, noahfalk approved these changes

2019-02-22 04:22 UTC, mairaw requested changes
Thanks @JackTrapper for one more contribution and @noahfalk for the review. I've left some suggestions. We use backticks to lock the words from being translated (although I'd prefer to have more styling options). We also avoid using future tense when possible.

2019-02-22 04:22 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-enuminterfaceimpls-method.md
> +Enumerates all interfaces implemented by the specified TypeDef.
```suggestion
Enumerates all interfaces implemented by the specified `TypeDef`. 
```

2019-02-22 04:22 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-enuminterfaceimpls-method.md
> +The enumeration returns a collection of `mdInterfaceImpl` tokens for each interface implemented by the specified **TypeDef**. Interface tokens will be returned in the order the interfaces were specif
```suggestion
The enumeration returns a collection of `mdInterfaceImpl` tokens for each interface implemented by the specified `TypeDef`. Interface tokens are returned in the order the interfaces were specified (through `DefineTypeDef` or `SetTypeDefProps`). Properties of the returned `mdInterfaceImpl` tokens can be queried using `GetInterfaceImplProps`.
```

2019-02-25 19:50 UTC, mairaw approved these changes
Thanks @JackTrapper! I've applied the feedback I've left last week and made some other minor fixes. Once the build finishes successfully, I'll merge the PR.

2019-02-25 19:50 UTC, merged