Noting where the tokens come from
dotnet/docs pull request #10548
Opened 2019-02-18 20:36 UTC by JackTrapper

The mdInterfaceImpl tokens come from EnumInterfaceImpls

## Summary

Added note that the mdInterfaceImpl tokens from the EnumInterfaceImpls, and describe what you're getting (i.e. you're not getting the Interface propertie)

2019-02-18 20:36 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=10548) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=10548) before we can accept your contribution.<br/><br/>:x: JackTrapper [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=10548)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=10548) it.</sub>

2019-02-22 03:57 UTC, noahfalk approved these changes

2019-02-22 04:37 UTC, mairaw requested changes
Thanks @JackTrapper for this change and @noahfalk for the review again! Left a few suggestions.

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
> + You obtain the value for *iImpl* by calling the **EnumInterfaceImpls** method.
```suggestion
 You obtain the value for `iImpl` by calling the [EnumInterfaceImpls](imetadataimport-enuminterfaceimpls-method) method.
```

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
> + For example, suppose a class has an mdTypeDef token value of 0x02000007. And suppose it implements three
```suggestion
 For example, suppose that a class has an `mdTypeDef` token value of 0x02000007 and that it implements three
```

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
> +| Row Number | Class Token | Interface Token |
```suggestion
| Row number | Class token | Interface token |
```

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
> +- the lower 3 bytes hold the row number, or RID
```suggestion
- The lower 3 bytes hold the row number, or RID.
```

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
> +- the upper byte holds the token type – 0x09 for `mdtInterfaceImpl`
```suggestion
- The upper byte holds the token type – 0x09 for `mdtInterfaceImpl`.
```

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
> +**GetInterfaceImplProps** will return the information held in the row whose token you provide in the *iImpl* argument.
```suggestion
`GetInterfaceImplProps` returns the information held in the row whose token you provide in the `iImpl` argument. 
```

2019-02-22 04:37 UTC, mairaw commented on docs/framework/unmanaged-api/metadata/imetadataimport-getinterfaceimplprops-method.md
>  ms.author: "mairaw"
given how thoroughoully this was changed, it would be good to update the ms.date value to today's date on line 3

2019-02-25 19:53 UTC, mairaw approved these changes
Thank you @JackTrapper for your contribution and for applying the suggestions (you can also apply them in bulk at once via the Files tab). I've just changed the date and I'll merge once the build finishes.

2019-02-25 21:24 UTC, merged