Remove broken link
dotnet/docs pull request #10555
Opened 2019-02-19 14:15 UTC by manolis82

Remove 'Configuration, Administration, And Management' link.

Fixes #10531

2019-02-19 16:31 UTC, rpetrusha requested changes
Thanks for addressing #10531, @manolis82. Rather than simply removing the link, though, a better option is to remove the entire section.

2019-02-19 16:38 UTC, manolis82 commented
Thank you @rpetrusha.

I removed the section completely as indicated.

2019-02-20 00:04 UTC, rpetrusha commented
Thanks for responding so quickly, @manolis82. I'll merge your PR now.

2019-02-20 00:04 UTC, rpetrusha approved these changes

2019-02-20 00:04 UTC, merged