C67701: Should the link be clickable?
dotnet/docs pull request #10602
Opened 2019-02-21 08:18 UTC by v-makoud

Hello @yishengjin1413,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description of the source issue:
The link is not being rendered as clickable on LOC pages, while on EN it is. The link is not working though. Should the link be clickable? If link should be clickable then it should be written like this, so it works on LOC pages too.
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-02-21 08:44 UTC, mairaw requested changes
Thanks @v-makoud. Please check the suggestion I left for you.

2019-02-21 08:44 UTC, mairaw commented on includes/tlasharptla-mcxmlnsv1-md.md
> +[http://schemas.openxmlformats.org/markup-compatibility/2006](http://schemas.openxmlformats.org/markup-compatibility/2006)
This link doesn't work so I'd put backticks around instead

```suggestion
`http://schemas.openxmlformats.org/markup-compatibility/2006`
```

2019-02-22 07:49 UTC, v-makoud commented
thanks @mairaw I committed the change

2019-02-22 08:23 UTC, mairaw approved these changes

2019-02-22 08:23 UTC, merged