Fixed broken links
dotnet/docs pull request #10681
Opened 2019-02-25 19:50 UTC by OronDF343

I have fixed 3 completely broken links (and also converted 2 relative links to absolute for consistency)

2019-02-25 22:49 UTC, jzeferino approved these changes

2019-02-26 01:37 UTC, nxtn requested changes
Thanks for fixing the broken links. However, we prefer relative links because they also work on GitHub. #9968

2019-02-26 14:11 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=10681) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=10681) before we can accept your contribution.<br/><br/>:x: OronDF343 [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=10681)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=10681) it.</sub>

2019-02-26 14:13 UTC, OronDF343 commented
Done, all links in AppContextSwitchOverrides docs page are now relative

2019-02-26 14:23 UTC, BillWagner approved these changes
Thanks for making these changes @OronDF343 and for responding to the comments by @NextTurn 

This is ready to :shipit:

Thanks for making your first contribution to our docs repo! 🎆

2019-02-26 14:24 UTC, merged