Whats new in csharp 6
dotnet/docs pull request #1068
Opened 2016-09-22 19:42 UTC by BillWagner

Fixes #680.

Ready for review.

This is longer than I would like. I welcome any ideas to break it up.

2016-09-22 19:55 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6?branch=pr-en-us-1068](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6?branch=pr-en-us-1068)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C22%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609221942287276-1068%5Cworkflow_report.html).

2016-09-22 21:06 UTC, stevehoag commented on docs/csharp/csharp-6.md
> +returns `false`. That always false exception filte means that you can
filte -> filter

2016-09-22 21:08 UTC, stevehoag commented on docs/csharp/csharp-6.md
> +way to get tools working with you whenever you need the name of a variable,
"great way to get tools working with you" - I don't understand what you are trying to convey here.

2016-09-22 21:10 UTC, stevehoag commented on docs/csharp/csharp-6.md
> +Rename a variable, and any nameof expressions will update as well.
Rename -> rename

2016-09-22 21:12 UTC, stevehoag commented on docs/csharp/csharp-6.md
> +lost. The same happens with `await`ed expressions in `catch` and `finally`
`await`ed looks strange in the published output - maybe skip the keyword formatting here?

2016-09-22 21:13 UTC, stevehoag commented on docs/csharp/csharp-6.md
> +This features means that associative containers can be initialized using
features -> feature

2016-09-22 21:14 UTC, stevehoag commented on docs/csharp/csharp-6.md
> +added for parity with Visual Basic.
Does a C# programmer even care about VB parity? ;-)

2016-09-22 21:21 UTC, stevehoag requested changes
Other than a few nits, LGTM. If you really want to make the article shorter you could eliminate some of the background details (i.e. this was implemented because...), but I think it's useful in this type of article. And I learned something :sm

2016-09-22 22:26 UTC, mairaw commented on docs/csharp/csharp-6.md
> +lost. The same happens with `await`ed expressions in `catch` and `finally`
and this would probably be an issue for loc later

2016-09-22 22:29 UTC, mairaw commented on docs/csharp/csharp-6.md
> +* [Readonly Auto properties](#readonly-auto-properties)
according to our lovely MSFT style guide, read-only is always hyphenated.

2016-09-22 22:30 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The compiler generates code for for the `?.` operator that ensures
for for

2016-09-22 22:32 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The remainder of this topic provides details on each these features.
on each these -> on each of these

2016-09-22 22:33 UTC, mairaw commented on docs/csharp/csharp-6.md
> +## Auto Property enhancements
should auto-property be hyphenated? sometimes you hyphenated, sometimes you didn't.

2016-09-22 22:37 UTC, mairaw commented on docs/csharp/csharp-6.md
> +them in more scenarios. You'll fall back on the more verbose syntax of declaring
This last sentence reads a bit backward to me. Perhaps write it as 
"You won't need to fall back on the more verbose syntax of declaring and manipulating the backing field by hand so often."
Noticed I shortened a bit as well.

2016-09-22 22:39 UTC, mairaw commented on docs/csharp/csharp-6.md
> +code outisde the class.
typo: outisde

2016-09-22 22:41 UTC, mairaw commented on docs/csharp/csharp-6.md
> +This features enables true language support for creating immutable types and using
This features -> This feature

2016-09-22 22:42 UTC, mairaw commented on docs/csharp/csharp-6.md
> +### Auto Property Initializers
This is still under the same section.

2016-09-22 22:43 UTC, mairaw commented on docs/csharp/csharp-6.md
> +these properties would need to have setters and a class author would need
a class author or you?

2016-09-22 22:45 UTC, mairaw commented on docs/csharp/csharp-6.md
> +Property Initializers can be used with read / write properties as well
read / write -> read/write

2016-09-22 23:04 UTC, mairaw commented on docs/csharp/csharp-6.md
> +Many of the members that we write consist of single return statements.
I understood the concept by seeing the examples but somehow I feel this needs to be explained a bit better. 
Wouldn't this be easier to understand if we said something like "The body of a lot of members that we write consist of only one return statement that can be represented as an expression. You can reduce that syntax by writing an **expression bodied member** instead. It works for methods and read-only properties."

2016-09-22 23:05 UTC, mairaw commented on docs/csharp/csharp-6.md
> +## Using static
should this using be lowercase?

2016-09-22 23:07 UTC, mairaw commented on docs/csharp/csharp-6.md
> +Your code will be littered with `Math.Sin`, `Math.Sqrt` and other calls
should we link to the apis when possible?

2016-09-22 23:07 UTC, mairaw commented on docs/csharp/csharp-6.md
> +`System.String`:
missing the verb: is `System.String`

2016-09-22 23:10 UTC, mairaw commented on docs/csharp/csharp-6.md
> +> You can't use the `string` keyword instead.
can't -> cannot (I think it reads better)

2016-09-22 23:11 UTC, mairaw commented on docs/csharp/csharp-6.md
> +the specifically address those interactions. The goal is to
the specifically  -> that specifically ?

2016-09-22 23:12 UTC, mairaw commented on docs/csharp/csharp-6.md
> +methods. They are not in scope if they are called as though they are static
as though -> even though?

2016-09-22 23:15 UTC, mairaw commented on docs/csharp/csharp-6.md
> +the `person` variable is null. Instead, it short-circuits and produces null.
make sure all the instances where null should not be localized are styled as inline code.

2016-09-22 23:20 UTC, mairaw commented on docs/csharp/csharp-6.md
> +[delegate patterns](delegates-patterns.md#Handling-Null-Delegates).
anchor needs to be lowercase: handling-null-delegates or it doesn't work.

I also think that the expression "where we discuss" seems a bit strange. Maybe change this to:
You can see an example on [delegate patterns](delegates-patterns.md#handling-null-delegates) topic.

2016-09-22 23:21 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The rules of the `?.` operator ensure that the left hand side of the operator is
left hand -> left-hand

2016-09-22 23:22 UTC, mairaw commented on docs/csharp/csharp-6.md
> +// Not recommended
this will not get localized. so you might want to add important notes in the text itself.

2016-09-22 23:26 UTC, mairaw commented on docs/csharp/csharp-6.md
> +the left side (`this.SomethingHappened`) below is evaluated once, and the result
style guide: don't use below.

also just a side comment here that we might want to file a bug:
I find it weird that the parentheses and the text inside get separated in the rendered view as this:
![image](https://cloud.githubusercontent.com/assets/12971179/18769313/ffa67cac-80e0-11e6-8fca-75fbc1be40c0.png)

2016-09-22 23:27 UTC, mairaw commented on docs/csharp/csharp-6.md
> +on [events](events-overview.md#Language-Support-for-Events).
correct anchor is language-support-for-events

2016-09-22 23:29 UTC, mairaw commented on docs/csharp/csharp-6.md
> +a floating point number with 2 decimal places.
floating-point is hyphened

2016-09-22 23:30 UTC, mairaw commented on docs/csharp/csharp-6.md
> +a floating point number with 2 decimal places.
and spell out two

2016-09-22 23:34 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The above line of code will format the value for `Grades.Average()` as
style guide: don't use above.  use previous, preceding, or earlier.

2016-09-22 23:36 UTC, mairaw commented on docs/csharp/csharp-6.md
> +### String Interpolation and Specific Cultures
let's try to make the new topics with the right section casing so it's less work to fix those in the future :-)

2016-09-22 23:37 UTC, mairaw commented on docs/csharp/csharp-6.md
> +may want need to format the string produced using a specific culture.
typo: may want need

2016-09-22 23:49 UTC, mairaw commented on docs/csharp/csharp-6.md
> +using German as the language and culture. (It will use the ',' character
wouldn't it be simpler to say decimal separator for example?

2016-09-22 23:49 UTC, mairaw commented on docs/csharp/csharp-6.md
> +> only supported in the full .NET Framework.
remove full.

2016-09-22 23:51 UTC, mairaw commented on docs/csharp/csharp-6.md
> +are clauses that determine when a given catch clause should be applied.
style catch as inline code?

2016-09-22 23:51 UTC, mairaw commented on docs/csharp/csharp-6.md
> +to enable easy formating with specific cultures.
typo: formating

2016-09-22 23:52 UTC, mairaw commented on docs/csharp/csharp-6.md
> +catch clause performs its normal procesing on an exception. If the
typo: procesing

2016-09-22 23:54 UTC, mairaw commented on docs/csharp/csharp-6.md
> +were added to the language you would need to create code like the following:
nit: missing comma after language

2016-09-22 23:55 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The exception filter expression evaluates to `false`. Execution never
lowercase the

2016-09-22 23:56 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The exception filter expression evaluates to `false`. Execution never
should this be a list instead?

2016-09-22 23:57 UTC, mairaw commented on docs/csharp/csharp-6.md
> +of relying on solely on the exception type, use an exception filter to
relying on solely on -> relying solely on

2016-09-23 00:02 UTC, mairaw commented on samples/snippets/csharp/new-in-6/Program.cs
> +                // perform recovery here
Should this be "Perform recovery here."?

2016-09-23 00:03 UTC, mairaw commented on docs/csharp/csharp-6.md
> +catch clause may appear before a more specific one. It's also possible
this probably means we have to revisit our exception topic and exception filters there too

2016-09-23 00:04 UTC, mairaw commented on docs/csharp/csharp-6.md
> +In the code, add an exception filter so that any recovery code executes
In the code -> In your code?

2016-09-23 00:07 UTC, mairaw commented on docs/csharp/csharp-6.md
> +way to get tools working with you whenever you need the name of a variable,
Probably just remove the with you and it's good

2016-09-23 00:09 UTC, mairaw commented on docs/csharp/csharp-6.md
> +Rename a variable, and any nameof expressions will update as well.
also style nameof as inline code

2016-09-23 00:12 UTC, mairaw commented on docs/csharp/csharp-6.md
> +(`LastName` in the examples above) even if you use the fully qualified
examples above -> previous example (because the first example used nameof(lastName) and not LastName

2016-09-23 00:13 UTC, mairaw commented on samples/snippets/csharp/new-in-6/viewmodel.cs
> +                        new PropertyChangedEventArgs(nameof(UXComponents.ViewModel.FastName)));
FastName or FirstName?

2016-09-23 00:17 UTC, mairaw commented on docs/csharp/csharp-6.md
> +has a method with a different name to semantically add new items:
should : be a period here?

2016-09-23 00:27 UTC, mairaw commented on samples/snippets/csharp/new-in-6/classList.cs
> +                new Student("Richard", "Feynman"),
we can't use real people's names in examples. we have a database of fictitious names. let me know if you need help finding it.

2016-09-23 00:29 UTC, mairaw commented on docs/csharp/csharp-6.md
> +### Extension `Add` methods in collection initializers
wondering if this scenario would benefit from having the full sample for people to see?

2016-09-23 01:00 UTC, mairaw requested changes
Awesome article but left a bunch of comments to be fixed.

2016-09-23 14:26 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +The 6.0 release of C# contained many features that improves
Fixed

2016-09-23 14:30 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +***Readonly auto-properties*** provide a more concise syntax to create
I was following what was in the C# spec. that's a paper doc, so let's go with **italic**.

2016-09-23 14:33 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +### Auto Property Initializers
I checked the Roslyn site, and the C# spec. The full name for the feature is "automatically implemented properties". The shortened form is typically hyphenated.  

I made updates to fix both.

2016-09-23 14:47 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +lost. The same happens with `await`ed expressions in `catch` and `finally`
Done.

2016-09-23 14:48 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +This features means that associative containers can be initialized using
fixed.

2016-09-23 14:50 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +added for parity with Visual Basic.
The teams do. 😄

2016-09-23 14:52 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +* [Readonly Auto properties](#readonly-auto-properties)
Changed everywhere that `readonly` was not used as the C# keyword.

2016-09-23 14:53 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +The remainder of this topic provides details on each these features.
fixed.

2016-09-23 14:58 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +## Auto Property enhancements
I checked the C# spec, and the Roslyn site. It should be hyphenated. I made the global change.

2016-09-23 14:58 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +them in more scenarios. You'll fall back on the more verbose syntax of declaring
Great suggestion. Updated.

2016-09-23 14:59 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +code outisde the class.
fixed.

2016-09-23 14:59 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +This features enables true language support for creating immutable types and using
fixed.

2016-09-23 15:00 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +Property Initializers can be used with read / write properties as well
fixed.

2016-09-23 15:04 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +Instead of all that ceremony, write an ***expression bodied member***
Incorporating your suggestion below, I think this gets better.

2016-09-23 15:04 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +Many of the members that we write consist of single return statements.
I like that.

2016-09-23 15:07 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +## Using static
Changed. (I wasn't sure, but you know the guidelines better.

2016-09-23 15:07 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +Your code will be littered with `Math.Sin`, `Math.Sqrt` and other calls
Yes. Thanks for reminding me.

2016-09-23 15:16 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +`System.String`:
Fixed.

2016-09-23 15:16 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +> You can't use the `string` keyword instead.
Fixed.

2016-09-23 15:16 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +the specifically address those interactions. The goal is to
yes.

2016-09-23 15:20 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +methods. They are not in scope if they are called as though they are static
See rewrite. 'even though' would be misleading.

2016-09-23 15:20 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +the `person` variable is null. Instead, it short-circuits and produces null.
Done.

2016-09-23 15:23 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +The rules of the `?.` operator ensure that the left hand side of the operator is
fixed.

2016-09-23 15:25 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +// Not recommended
fixed. I turned it into an **important** note to highlight it.

2016-09-23 15:28 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +the left side (`this.SomethingHappened`) below is evaluated once, and the result
Fixed, and I'll file that bug.

2016-09-23 15:29 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +a floating point number with 2 decimal places.
fixed both.

2016-09-23 15:43 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +### String Interpolation and Specific Cultures
Right!

2016-09-23 15:44 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +using German as the language and culture. (It will use the ',' character
yes

2016-09-23 15:45 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +are clauses that determine when a given catch clause should be applied.
yes

2016-09-23 15:45 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +to enable easy formating with specific cultures.
fixed.

2016-09-23 15:46 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +catch clause performs its normal procesing on an exception. If the
fixed.

2016-09-23 15:46 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +were added to the language you would need to create code like the following:
fixed.

2016-09-23 15:51 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +The exception filter expression evaluates to `false`. Execution never
It shouldn't be a list. It's a series of cause and effect statements. See if the rewrite is more clear.

2016-09-23 15:51 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +of relying on solely on the exception type, use an exception filter to
fixed.

2016-09-23 15:54 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +catch clause may appear before a more specific one. It's also possible
Yes. That's mentioned in issue #274

Is there another topic that should be updated as well?

2016-09-23 15:54 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +In the code, add an exception filter so that any recovery code executes
fixed.

2016-09-23 15:54 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +(`LastName` in the examples above) even if you use the fully qualified
fixed.

2016-09-23 15:55 UTC, BillWagner commented on samples/snippets/csharp/new-in-6/viewmodel.cs
> +                        new PropertyChangedEventArgs(nameof(UXComponents.ViewModel.FastName)));
Fixed.

2016-09-23 15:55 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +has a method with a different name to semantically add new items:
yes.

2016-09-23 15:57 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +### Extension `Add` methods in collection initializers
I think so. I'll add that

2016-09-23 16:14 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6?branch=pr-en-us-1068](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6?branch=pr-en-us-1068)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C23%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609231602226895-1068%5Cworkflow_report.html).

2016-09-23 16:29 UTC, stevehoag approved these changes

2016-09-23 16:41 UTC, mairaw commented on docs/csharp/csharp-6.md
> +catch clause may appear before a more specific one. It's also possible
No, that's the one.

2016-09-23 17:33 UTC, mairaw commented on docs/csharp/csharp-6.md
> +methods. They are not in scope if they are called as though they are static
yep, I wasn't sure. rewrite looks better.

2016-09-23 17:34 UTC, mairaw commented on docs/csharp/csharp-6.md
> +The exception filter expression evaluates to `false`. Execution never
Yep, it's more clear indeed!

2016-09-23 17:36 UTC, mairaw commented on docs/csharp/csharp-6.md
> +the exception filter expression evaluates to `false`.Therefore, execution never
missing a space before therefore

2016-09-23 17:37 UTC, mairaw commented on docs/csharp/csharp-6.md
> +calls involving lambda expressions ambiguious. Consider this method:
typo: ambiguious

2016-09-23 17:38 UTC, mairaw commented on docs/csharp/csharp-6.md
> +## Using static
Not so sure about that. But this is about the keyword right?

2016-09-23 17:40 UTC, mairaw approved these changes
Still a few things to be fixed but the topic LGTM. Although it's long, it's easy to read.

2016-09-23 17:45 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +## Using static
Yes, so I think it's right.

2016-09-23 17:46 UTC, BillWagner commented on docs/csharp/csharp-6.md
> +may want need to format the string produced using a specific culture.
Fixed.

2016-09-23 18:24 UTC, badersur commented on docs/csharp/csharp-6.md
> +The 6.0 release of C# contained many features that improves
Maybe it is improve instead of improves?

2016-09-23 18:47 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6?branch=pr-en-us-1068](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/csharp-6?branch=pr-en-us-1068)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C23%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609231833467955-1068%5Cworkflow_report.html).

2016-09-23 18:55 UTC, merged