Fix formatting console-teleprompter.md
dotnet/docs pull request #1073
Opened 2016-09-24 20:33 UTC by badersur

Some tutorials add inline code for file names, but this file does not. so which one is correct?!

There is "Hello World application" and "hello world program", is it fine?!

In **Reading and Echoing the File** section, there is:
> The first feature to add is to read a text file, and display all that text to the console. First, let’s add a text file. Copy the sampleQuotes.txt file from the GitHub repository for this sample into your project directory. **This will serve as the script for your application**.

Is it a script?!

And:
> The compiler generates that **call** when execution reaches the closing brace of the using statement. The compiler-generated **code** ensures that the resource is released even if an exception is thrown from the code in the block defined by the using statement.

Maybe **code** is a **call**?

And:
```cs
{ # maybe this brace should be removed!
    Console.Write(line);
    if (!string.IsNullOrWhiteSpace(line))
    {
        var pause = Task.Delay(200);
        // Synchronously waiting on a task is an
        // anti-pattern. This will get fixed in later
        // steps.
        pause.Wait();
    }
} # maybe should be removed
```

cc: @BillWagner

2016-09-24 20:33 UTC, dnfclas commented
Hi __@badersur__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, DNFBOT;

2016-09-24 20:46 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C24%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609242033417149-1073%5Cworkflow_report.html).

2016-09-24 21:07 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C24%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609242055483621-1073%5Cworkflow_report.html).

2016-09-24 22:26 UTC, badersur commented on docs/csharp/tutorials/console-teleprompter.md
> +enclosing class or namespace names. A `static using` statement imports the
Or maybe: static `using`!

2016-09-25 07:44 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C25%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609250732559293-1073%5Cworkflow_report.html).

2016-09-26 18:33 UTC, mairaw commented on docs/csharp/tutorials/console-teleprompter.md
> +enclosing class or namespace names. A `static using` statement imports the
If you're going to style the whole thing as inline code then it should be `using static`. Or probably you could also called this static `using` statement.

2016-09-26 18:40 UTC, badersur commented on docs/csharp/tutorials/console-teleprompter.md
> +enclosing class or namespace names. A `static using` statement imports the
I've wanted to change it to `using static` but I'm waiting your approval :)

2016-09-26 18:43 UTC, mairaw commented
Thanks for the changes @badersur.

I think this topic was written when we didn't have a style guide yet. 

> Some tutorials use inline code for file names, but this file does not. In the template file you ask us to "Use Italics for files, folders, paths.." but is not inline code or bold better for these?

We can check. We don't have much of those yet. This was the same style used by the ASP.NET and we're trying to achieve some consistency across teams. @Rick-Anderson, any thoughts on that?

> When talking about methods, some have parentheses while others don't!

On MSDN, our build system would only add the parentheses if we wanted to talk about a specific overload or show the parameters, otherwise the link doesn't show the parentheses. Maybe we should do the same if we're talking about custom methods in our articles too.

 > APIs should be linked but I can't do it now.

It's ok. We have a tracking bug for that so eventually we'll get those linked throughout our content.

I'll let @BillWagner answer the other questions you had.

2016-09-26 18:45 UTC, mairaw commented on docs/csharp/tutorials/console-teleprompter.md
> +enclosing class or namespace names. A `static using` statement imports the
Sounds good then.  😄

2016-09-26 19:15 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/tutorials/console-teleprompter?branch=pr-en-us-1073)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C26%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609261903073512-1073%5Cworkflow_report.html).

2016-09-26 21:38 UTC, Rick-Anderson commented
File paths should **always** be *itallic*, never ``code``.

Only include () in methods when you are explaining an overload (which is very rare). Method names should **not** include ().

2016-09-26 23:58 UTC, mairaw commented
Thanks @Rick-Anderson!

2016-10-03 14:53 UTC, BillWagner approved these changes

2016-10-03 14:55 UTC, BillWagner commented
> The first feature to add is to read a text file, and display all that text to the console. First, let’s add a text  file. Copy the sampleQuotes.txt file from the GitHub repository for this sample into your project directory. This will serve as the script for your application.

> Is it a script?!

Probably better to say "This will be the text displayed by the application.

2016-10-05 17:58 UTC, BillWagner requested changes
Two sets of changes to make:
Removing the curly braces as you suggested earlier.
Removing the parens from method calls in text when not needed to disambiguate overloads.

2016-11-03 19:09 UTC, BillWagner commented
@badersur Were you planning to make the last few requested changes?  After that, this would be ready to merge.

2016-11-04 17:07 UTC, badersur commented
Unfortunately I'm busy these days and can't do these changes @BillWagner

2016-11-04 17:09 UTC, BillWagner commented
@badersur We understand. I will make those last change on this and your other open PRs so we can merge them.

2016-11-06 19:51 UTC, BillWagner commented
I've addressed the remaining feedback by cloning this branch, and creating PR #1210.  

Closing this PR.

2016-11-06 19:51 UTC, closed without merging