1436790/1438462: Part 48: 20 files with MSDN link fixes.
dotnet/docs pull request #10759
Opened 2019-02-27 00:55 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

2019-02-27 00:56 UTC, DennisLee-DennisLee commented
The `git reset` trick didn't work - still lots of commits. :(

2019-02-27 00:59 UTC, mairaw commented
Ping me offline via teams and I can work with you to get that working. You might be missing a few extra steps.

2019-02-28 01:19 UTC, mairaw requested changes
Thank you @DennisLee-DennisLee. A few comments before we merge.

2019-02-28 01:19 UTC, mairaw commented on docs/visual-basic/misc/bc33028.md
> +- [Object as the Universal Data Type (Visual Basic)](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/3cf69sdx(v=vs.100))
```suggestion
- [Object Data Type (Visual Basic)](../language-reference/data-types/object-data-type.md)
```

2019-02-28 01:19 UTC, mairaw commented on docs/visual-basic/misc/bc33032.md
> +- [Object as the Universal Data Type (Visual Basic)](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/3cf69sdx(v=vs.100))
```suggestion
- [Object Data Type (Visual Basic)](../language-reference/data-types/object-data-type.md)
```

2019-02-28 01:19 UTC, mairaw commented on docs/visual-basic/misc/bc36553.md
> +- [How to: Define Optional Parameters for a Procedure (Visual Basic)](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/ssaskzyc(v=vs.100))
```suggestion
```

2019-02-28 01:19 UTC, mairaw commented on docs/visual-basic/misc/bc36577.md
> +- [Closer Look: What If... Testing Code in the Immediate Window](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2008/ms172593(v=vs.90))
```suggestion
- [Immediate Window - Visual Studio](/visualstudio/ide/reference/immediate-window)
```

2019-02-28 01:19 UTC, mairaw commented on docs/visual-basic/misc/bc36595.md
> +- [Introduction to Exception Handling (Visual Basic)](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/c68xfk56(v=vs.100))
```suggestion
- [Handling and throwing exceptions in .NET](../../dotnet/standard/exceptions/index.md)
```

2019-02-28 01:19 UTC, mairaw commented on docs/visual-basic/misc/bc36627.md
> +- [Closer Look: What If... Testing Code in the Immediate Window](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2008/ms172593(v=vs.90))
```suggestion
- [Immediate Window - Visual Studio](/visualstudio/ide/reference/immediate-window)
```

2019-02-28 02:56 UTC, mairaw approved these changes

2019-02-28 03:09 UTC, merged