1436790/1438462: Part 49: 7 files with MSDN link fixes.
dotnet/docs pull request #10760
Opened 2019-02-27 01:59 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

2019-02-27 04:04 UTC, DennisLee-DennisLee commented
No more extraneous commits, @mairaw! Looks like your trick worked. :)

2019-02-28 00:43 UTC, mairaw commented
Yay 🎆 I'll get that reviewed!

2019-02-28 01:40 UTC, mairaw requested changes
LGTM. Just two suggestions and we're good to merge.

2019-02-28 01:40 UTC, mairaw commented on docs/visual-basic/misc/could-not-complete-operation-since-target-directory-is-under-source-directory.md
> +- [Debugging Basics: Breakpoints](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/4607yxb0(v=vs.100))
```suggestion
- [Use breakpoints in the Visual Studio debugger](/visualstudio/debugger/using-breakpoints)
```

2019-02-28 01:40 UTC, mairaw commented on docs/visual-basic/misc/key-cannot-be-deleted-because-it-has-subkeys.md
> +- [Troubleshooting: Manipulating the Registry (Visual Basic)](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2010/zs7t1t16(v=vs.100))
```suggestion
```

2019-02-28 02:56 UTC, mairaw approved these changes

2019-02-28 02:56 UTC, merged