1436790/1438462: Part 50: Final 9 files with MSDN link changes.
dotnet/docs pull request #10790
Opened 2019-02-28 04:58 UTC by DennisLee-DennisLee

Contributes to PR #[2037](https://github.com/dotnet/docs/issues/2037) and applies to the following work items:
- [User Story 1436790: Content Update: update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1436790)
- [Task 1438462: Update MSDN links for .NET content](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1438462)

These are changes to instances I missed or needed to reconsider. There are a few more MSDN links, but most of them are to MSDN magazine articles that aren't on docs.microsoft.com.

2019-02-28 17:28 UTC, rpetrusha requested changes
Thanks for all of the work you've put into making these link changes, @DennisLee-DennisLee. I've left some suggestions, almost all unrelated to your PR.

2019-02-28 17:28 UTC, rpetrusha commented on docs/framework/wcf/feature-details/serializing-in-json-with-message-level-programming.md
> + The <xref:System.Runtime.Serialization.Json.DataContractJsonSerializer> is used when the <xref:System.ServiceModel.Web.WebGetAttribute> or the <xref:System.ServiceModel.Web.WebInvokeAttribute> is ap
```suggestion
 The <xref:System.Runtime.Serialization.Json.DataContractJsonSerializer> is used when the <xref:System.ServiceModel.Web.WebGetAttribute> or the <xref:System.ServiceModel.Web.WebInvokeAttribute> is applied to a service operation. Both of these attributes allow you to specify the `RequestFormat` and `ResponseFormat`. To use JSON for requests and responses. set both of these to `WebMessageFormat.Json`.  In order to use JSON, you must use the <xref:System.ServiceModel.WebHttpBinding>, which automatically configures the <xref:System.ServiceModel.Description.WebHttpBehavior>. For more information about WCF serialization, see [Serialization and Deserialization](../../../../docs/framework/wcf/feature-details/serialization-and-deserialization.md). For more information about JSON and WCF, see [Service Station - An Introduction To RESTful Services With WCF](https://msdn.microsoft.com/magazine/dd315413.aspx).  
```
The second link appears to be broken.

2019-02-28 17:28 UTC, rpetrusha commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md
>    [*https://github.com/StackExchange/dapper-dot-net*](https://github.com/StackExchange/dapper-dot-net)
```suggestion
 <https://github.com/StackExchange/dapper-dot-net>
```

2019-02-28 17:28 UTC, rpetrusha commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md
>    [*https://docs.microsoft.com/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio*](https://docs.microsoft.com/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visua
```suggestion
  <https://docs.microsoft.com/aspnet/core/tutorials/web-api-help-pages-using-swagger?tabs=visual-studio>
```

2019-02-28 17:28 UTC, rpetrusha commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md
>    [*http://udidahan.com/2008/02/29/how-to-create-fully-encapsulated-domain-models/*](http://udidahan.com/2008/02/29/how-to-create-fully-encapsulated-domain-models/)
```suggestion
  <http://udidahan.com/2008/02/29/how-to-create-fully-encapsulated-domain-models/>
```

2019-02-28 17:31 UTC, rpetrusha commented
//cc @mvelosop for visibility

2019-02-28 23:31 UTC, mairaw requested changes
Looks good @DennisLee-DennisLee. Left a few comments to be addressed.

2019-02-28 23:31 UTC, mairaw commented on docs/framework/performance/index.md
> +|Windows Forms|[Winning Forms: Practical Tips for Boosting the Performance of Windows Forms Apps](https://web.archive.org/web/20060411224813/https://msdn.microsoft.com/msdnmag/issues/06/03/WindowsFor
I'd just remove this 

```suggestion
```

2019-02-28 23:31 UTC, mairaw commented on docs/framework/winforms/windows-forms-overview.md
> +|Using the Data Sources window|[Walkthrough: Displaying Data on a Windows Form](https://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2013/wwh8ka92(v=vs.120))|
Let's change this to go to https://docs.microsoft.com/visualstudio/data-tools/bind-windows-forms-controls-to-data-in-visual-studio instead

2019-03-01 22:24 UTC, mairaw approved these changes
Thanks @DennisLee-DennisLee! Last one - woo hoo!

2019-03-04 16:34 UTC, rpetrusha commented
Thank you for making the additional changes, @DennisLee-DennisLee. I'll merge your PR now.

2019-03-04 16:34 UTC, rpetrusha approved these changes

2019-03-04 16:34 UTC, merged

2019-03-07 11:28 UTC, mvelosop commented
Thank you @rpetrusha!