Fix broken links
dotnet/docs pull request #10844
Opened 2019-03-01 15:19 UTC by NextTurn

2019-03-01 17:19 UTC, rpetrusha requested changes
Thanks for fixing the broken link, @NextTurn. I thought that the link title might also be changed, since the content of the section doesn't reflect what most developers think of as a shim.

2019-03-01 17:19 UTC, rpetrusha commented on docs/standard/microservices-architecture/net-core-net-framework-containers/net-framework-container-scenarios.md
> +Third-party libraries are quickly embracing the [.NET Standard](../../net-standard.md), which enables code sharing across all .NET flavors, including .NET Core. With the .NET Standard Library 2.0 and
```suggestion
Third-party libraries are quickly embracing the [.NET Standard](../../net-standard.md), which enables code sharing across all .NET flavors, including .NET Core. With the .NET Standard Library 2.0 and beyond the API surface compatibility across different frameworks has become significantly larger and in .NET Core 2.x applications can also directly reference existing .NET Framework libraries (see [.NET Framework 4.6.1 supporting .NET Standard 2.0](https://github.com/dotnet/standard/blob/master/docs/planning/netstandard-2.0/README.md#net-framework-461-supporting-net-standard-20)).
```

2019-03-01 22:22 UTC, mairaw commented
@mvelosop FYI on a broken link from the e-book

2019-03-02 00:02 UTC, rpetrusha approved these changes

2019-03-02 00:02 UTC, rpetrusha commented
Thank you, @NextTurn, for making the additional change. I'll merge your PR now.

2019-03-02 00:02 UTC, merged

2019-03-07 11:27 UTC, mvelosop commented
Thank you @mairaw