Update TOC for Docker
dotnet/docs pull request #1088
Opened 2016-09-28 18:39 UTC by BillWagner

This includes placeholders for this week’s deliverables.

2016-09-28 18:40 UTC, BillWagner commented
TOC Updates for Docker on windows content.  /cc @staceyhaffner @spboyer @shirhatti @richlander @mairaw

2016-09-28 18:46 UTC, mairaw commented on docs/framework/docker/aspnetmvc.md
> +description: Running ASP.NET MVC applications in Docker
let's try to apply the right metadata to new topics. It's ok for now since they're still placeholders.

2016-09-28 18:50 UTC, mairaw commented on docs/framework/index.md
> +on Windows.
do we need to say on Windows here?

2016-09-28 18:52 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609281839517080-1088%5Cworkflow_report.html).

2016-09-28 18:53 UTC, BillWagner commented on docs/framework/docker/aspnetmvc.md
> +description: Running ASP.NET MVC applications in Docker
I agree. I'll update in my next push.

2016-09-28 18:53 UTC, BillWagner commented on docs/framework/index.md
> +on Windows.
Well, this is framework that only runs on Windows. How do we want to best distinguish this from .NET Core and .NET Standard?

2016-09-28 19:06 UTC, mairaw requested changes
Left a few comments. There's an issue with the TOC that needs to be fixed before merging this.

2016-09-28 19:06 UTC, mairaw commented on docs/toc.md
> +### [🔧 Running Console Applications in Containers](framework/docker/aspnetmvc.md)
MVC apps?

2016-09-28 20:39 UTC, mairaw commented on docs/framework/index.md
> +on Windows.
We could expand this paragraph a bit to explain what the framework is and say it runs on Windows. To say .NET Framework on Windows seems strange.

2016-09-29 01:36 UTC, BillWagner commented on docs/framework/docker/aspnetmvc.md
> +description: Running ASP.NET MVC applications in Docker
Updated, except for the descriptions on the placeholders. Let's add those as we fill in the documents.

2016-09-29 01:37 UTC, BillWagner commented on docs/framework/index.md
> +on Windows.
Done. Let me know what you think of the update.

2016-09-29 01:37 UTC, BillWagner commented on docs/toc.md
> +### [🔧 Running Console Applications in Containers](framework/docker/aspnetmvc.md)
fixed.

2016-09-29 01:43 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C29%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609290130334558-1088%5Cworkflow_report.html).

2016-09-29 14:01 UTC, BillWagner commented
@mairaw I addressed all your comments. Let me know what you think.

2016-09-29 21:03 UTC, mairaw approved these changes
LGTM but I found some minor nitpicks

2016-09-29 21:03 UTC, mairaw commented on docs/framework/index.md
> +author: dotnet-bot
put your name here

2016-09-29 21:03 UTC, mairaw commented on docs/framework/index.md
> +to create mobile, desktop, and web applications that run on Windowws PCs,
Typo: Windowws

2016-09-29 21:06 UTC, BillWagner commented on docs/framework/index.md
> +author: dotnet-bot
updated.

2016-09-29 21:06 UTC, BillWagner commented on docs/framework/index.md
> +to create mobile, desktop, and web applications that run on Windowws PCs,
updated.

2016-09-29 21:28 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C29%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609292107262845-1088%5Cworkflow_report.html).

2016-09-30 02:47 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609300235328492-1088%5Cworkflow_report.html).

2016-09-30 17:45 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609301732257687-1088%5Cworkflow_report.html).

2016-09-30 20:32 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609302018153185-1088%5Cworkflow_report.html).

2016-09-30 20:56 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/aspnetmvc?branch=pr-en-us-1088)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1088)  
  Please see 1 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609302042514665-1088%5Cworkflow_report.html).

2016-09-30 21:42 UTC, merged