word-smith
dotnet/docs pull request #1095
Opened 2016-09-30 02:26 UTC by Rick-Anderson

# word-smith

## Summary

edit clean up,, kill dead wood, put 3 commands on 3 lines.

Fixes 
## Suggested Reviewers

@mairaw

2016-09-30 02:26 UTC, dnfclas commented
Hi __@Rick-Anderson__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by .NET Foundation and real humans are currently evaluating your PR.</p>

TTYL, DNFBOT;

2016-09-30 02:39 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609300226411876-1095%5Cworkflow_report.html).

2016-09-30 02:51 UTC, mairaw requested changes
LGTM but I found a few minor issues

2016-09-30 02:51 UTC, mairaw commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +The example provides a service that indicates whether a number prime.
a number is prime?

2016-09-30 02:51 UTC, mairaw commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +```dotnet restore
new line before dotnet restore

2016-09-30 03:20 UTC, Rick-Anderson commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +The example provides a service that indicates whether a number prime.
Isn't that what it does? True if a number is prime, else false?

2016-09-30 03:32 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609300318557751-1095%5Cworkflow_report.html).

2016-09-30 06:50 UTC, svick commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +`dotnet test` runs all the configure tests.
What does "configure" mean here? Should it be just:

> `dotnet test` runs all the tests.

2016-09-30 17:33 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C9%5C30%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201609301717417571-1095%5Cworkflow_report.html).

2016-09-30 21:44 UTC, mairaw commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +`dotnet test` runs all the configure tests.
@BillWagner what did you intend to say here initially? configured tests perhaps?

2016-09-30 22:11 UTC, BillWagner commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +`dotnet test` runs all the configure tests.
"configured tests" is correct.

2016-10-01 00:12 UTC, mairaw commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +`dotnet test` runs all the configure tests.
@Rick-Anderson can you also please fix this and the other feedback I gave you and then we can merge this. Thanks!

2016-10-01 00:44 UTC, Rick-Anderson commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +The example provides a service that indicates whether a number prime.
depends on what your definition of is is.

2016-10-01 00:46 UTC, Rick-Anderson commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +`dotnet test` runs all the configure tests.
configured was all I fixed, did I miss something?

2016-10-01 00:50 UTC, mairaw approved these changes
LGTM. Thanks @Rick-Anderson!

2016-10-01 00:50 UTC, mairaw commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +`dotnet test` runs all the configure tests.
I missed your earlier fix. My bad!

2016-10-01 00:59 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C1%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610010045183835-1095%5Cworkflow_report.html).

2016-10-03 21:21 UTC, merged