a few edits for the docker console topic
dotnet/docs pull request #1100
Opened 2016-10-01 00:35 UTC by mairaw

I didn't have a chance to review the topic earlier today and I had a few suggestions, so created a PR to address them.

/cc @BillWagner @spboyer

2016-10-01 00:36 UTC, mairaw commented on docs/framework/docker/console.md
> +Adding the following code to the *build.ps1* script, when run the Docker image called `console-random-answer-generator` is created once the compilation is complete.
@spboyer can you clarify what this sentence means? it's a bit confusing

2016-10-01 00:49 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1100](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1100)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C1%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610010035084485-1100%5Cworkflow_report.html).

2016-10-01 00:57 UTC, spboyer commented on docs/framework/docker/console.md
> +Adding the following code to the *build.ps1* script, when run the Docker image called `console-random-answer-generator` is created once the compilation is complete.
above when build.ps1 was introduced, it was to show how to use MSBuild to compile the application and produce the assets. This is the second portion of the script that is related to building the Docker image.

2016-10-01 00:57 UTC, spboyer approved these changes

2016-10-01 00:57 UTC, spboyer commented
:shipit:

2016-10-03 14:36 UTC, BillWagner requested changes

2016-10-03 14:36 UTC, BillWagner commented on docs/framework/docker/console.md
> +In *build.ps1*, the script uses [MSBuild](https://msdn.microsoft.com/en-us/library/dd393574.aspx) to compile the application to complete the task of building the assets. There are a few parameters pa
Should this be "to be compiled" instead of "to be compile"?

2016-10-03 14:36 UTC, BillWagner commented
One typo remains, but everything else looks great.

2016-10-04 06:42 UTC, mairaw commented on docs/framework/docker/console.md
> +In *build.ps1*, the script uses [MSBuild](https://msdn.microsoft.com/en-us/library/dd393574.aspx) to compile the application to complete the task of building the assets. There are a few parameters pa
I think so. I'll fix it.

2016-10-04 06:43 UTC, mairaw commented on docs/framework/docker/console.md
> +Adding the following code to the *build.ps1* script, when run the Docker image called `console-random-answer-generator` is created once the compilation is complete.
Sure, but how can we improve the sentence? The flow is a bit weird after the comma.

2016-10-04 06:57 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1100](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/docker/console?branch=pr-en-us-1100)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Unable to resolve cross-reference "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptKeyHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptKeyHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptProviderHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptProviderHandle</a>", "<a href="xref:Microsoft.Win32.SafeHandles.SafeNCryptSecretHandle" sourcefile="docs/standard/garbagecollection/implementing-dispose.md" sourcestartlinenumber="413" sourceendlinenumber="413">SafeNCryptSecretHandle</a>"..  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C4%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610040645007297-1100%5Cworkflow_report.html).

2016-10-05 05:57 UTC, mairaw commented
@BillWagner does it look ok to you now? @spboyer please look at my last question.

2016-10-05 14:20 UTC, BillWagner commented on docs/framework/docker/console.md
> +In *build.ps1*, the script uses [MSBuild](https://msdn.microsoft.com/en-us/library/dd393574.aspx) to compile the application to complete the task of building the assets. There are a few parameters pa
Still missing the 'd' on compiled:  "or solution to be compile, the location"

2016-10-05 16:56 UTC, spboyer commented on docs/framework/docker/console.md
> +Adding the following code to the *build.ps1* script, when run the Docker image called `console-random-answer-generator` is created once the compilation is complete.
>Adding the following code to the *build.ps1* script, when run the Docker image called console-random-answer-generator` is created once the compilation is complete.

In order to create the Docker image, the following code is added to the *build.ps1* script. When run, the `console-random-answer-generator` image is created using the assets compiled from MSBuild previously defined in [Building the application](#building-the-application).

2016-10-05 16:56 UTC, spboyer commented
@mairaw see inline comment

2016-10-05 18:04 UTC, BillWagner approved these changes

2016-10-05 18:05 UTC, BillWagner commented
:shipit:

2016-10-05 18:05 UTC, merged

2016-10-06 18:20 UTC, mairaw commented on docs/framework/docker/console.md
> +Adding the following code to the *build.ps1* script, when run the Docker image called `console-random-answer-generator` is created once the compilation is complete.
Much better @spboyer! I'll add this in a new PR. Thanks!