SEOImages: User Story 1463880, Part 3
dotnet/docs pull request #11033
Opened 2019-03-05 06:02 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-06 22:26 UTC, damabe commented
@mairaw Please review this PR. There are no warnings, all extensions are lowercase, and there are fewer files (26) than the previous PR :-).

2019-03-09 06:10 UTC, mairaw commented
Resolved some merge conflicts

2019-03-09 07:09 UTC, mairaw requested changes
Thank you @damabe. Left some comments regarding the changes. I'd focus more on adding the text to the alt text vs. title. I'm also suggesting a few unrelated changes if you don't mind.

2019-03-09 07:09 UTC, mairaw commented on docs/framework/windows-workflow-foundation/performance.md
> +![Workflow Performance Test Environment](./media/performance/performance-test-environment.gif "Performance test environment workflow")
```suggestion
![Environment setup for workflow performance test](./media/performance/performance-test-environment.gif)
```

2019-03-09 07:09 UTC, mairaw commented on docs/framework/windows-workflow-foundation/performance.md
> + ![Persistence Workflows](./media/performance/persist-workflow-in-wf3-and-wf4.gif "Persistence workflow in WF3 on left and WF4 on right")
```suggestion
 ![Persistence workflow in WF3 on left and WF4 on right](./media/performance/persist-workflow-in-wf3-and-wf4.gif "Persistence workflows")
```

2019-03-09 07:09 UTC, mairaw commented on docs/framework/windows-workflow-foundation/performance.md
> + ![Throughput Persistence](./media/performance/throughput-persistence-graph.gif "Throughput Persistence graph")
```suggestion
 ![Column chart showing throughput persistence](./media/performance/throughput-persistence-graph.gif "Throughput Persistence")
```

2019-03-09 07:09 UTC, mairaw commented on docs/framework/windows-workflow-foundation/performance.md
> + ![Workflow Performance Test Environment](./media/performance/performance-test-environment.gif "Performance test environment workflow")
```suggestion
 ![Environment setup for workflow performance test](./media/performance/performance-test-environment.gif)
```

2019-03-09 07:09 UTC, mairaw commented on docs/framework/windows-workflow-foundation/performance.md
> + ![Workflow Tracing Cost](./media/performance/workflow-tracking-costs.gif "Shows workflow tracking costs")
```suggestion

 ![Column chart showing workflow tracking costs](./media/performance/workflow-tracking-costs.gif "Workflow tracking cost")
```

2019-03-09 07:09 UTC, mairaw commented on docs/framework/windows-workflow-foundation/performance.md
> + ![Workflow Performance Test Environment](./media/performance/performance-test-environment.gif "Performance test environment workflow")
```suggestion
 ![Environment setup for workflow performance test](./media/performance/performance-test-environment.gif)
```

2019-03-12 05:07 UTC, damabe commented
@mairaw The feedback has been incorporated. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031200050/Report/. There are three failures in alt text length. Do you want that criteria included in this user story or fixed at a later time?

2019-03-12 05:59 UTC, mairaw commented
What does work best for you and your team @damabe? I'm fine either way.

2019-03-12 06:02 UTC, mairaw approved these changes
I'm approving and merging as-is. Changes look great @damabe. Let me know how you prefer to handle these so I know what to review in the following PRs.

2019-03-12 06:02 UTC, merged