FixBlogLinks: updates to 10 articles
dotnet/docs pull request #11107
Opened 2019-03-06 15:08 UTC by craigcaseyMSFT

Updated or removed blog links in 10 articles per mseng User Story 1443043.

2019-03-06 15:09 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=11107) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=11107) before we can accept your contribution.<br/><br/>:x: craigcaseyMSFT [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=11107)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=11107) it.</sub>

2019-03-06 15:19 UTC, craigcaseyMSFT commented
@mairaw  - Hi, Maira. Please review these first 10 articles and let me know if anything should be changed before we can merge. Thanks for your help!

2019-03-06 19:51 UTC, mairaw requested changes
Thank you @craigcaseyMSFT! Changes look good. I left a couple of suggestions to simplify some links and also I'd revert the change to remove that 404 link until I can get confirmation that's by design.

2019-03-06 19:51 UTC, mairaw commented on docs/core/docker/building-net-docker-images.md
> -* [Getting hands on with Visual Studio for Mac, containers, and serverless code in the cloud](https://blogs.msdn.microsoft.com/visualstudio/2017/08/31/hands-on-with-visual-studio-for-mac-containers-s
hmm, this one is interesting. Let me follow up with the PM driving the migration to see if this is expected.

2019-03-06 19:51 UTC, mairaw commented on docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md
> +  [*https://devblogs.microsoft.com/dotnet/staying-up-to-date-with-net-container-images/*](https://devblogs.microsoft.com/dotnet/staying-up-to-date-with-net-container-images/)
Let's change this link format to this:

```suggestion
  *<https://devblogs.microsoft.com/dotnet/staying-up-to-date-with-net-container-images/>*
```

2019-03-06 19:51 UTC, mairaw commented on docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md
> +  [*https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2018-update/*](https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2018-update/)
```suggestion
  *<https://devblogs.microsoft.com/dotnet/using-net-and-docker-together-dockercon-2018-update/>*
```

2019-03-06 20:03 UTC, mairaw commented
I also added to the description a link to our GitHub issue tracking this work. Can you do the same when you open the new PRs?

2019-03-06 23:36 UTC, mairaw commented
@craigcaseyMSFT can you also undo the change done for building-net-docker-images.md as requested? Then we can merge this.

2019-03-07 14:34 UTC, craigcaseyMSFT commented
Change undone for building-net-docker-images.md as requested. Ready to merge.

#sign-off

2019-03-07 22:09 UTC, mairaw approved these changes
Thank you @craigcaseyMSFT!

2019-03-07 22:09 UTC, merged