Refresh .NET article: Create windows service app
dotnet/docs pull request #11110
Opened 2019-03-06 20:02 UTC by dksimpson

## Summary
Task 1409933: https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1409933/

2019-03-09 00:02 UTC, rpetrusha requested changes
I've left a large number of comments and suggestions, @dksimpson, but this is a good revision of a very stale article. Thanks for doing it.

2019-03-13 22:35 UTC, dksimpson commented on docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md
> +3. Select the **Service1.cs [Design]** (or **Service1.vb [Design]**) tab and select **Properties** from the shortcut menu. From the **Properties** window, change the **ServiceName** value to *MyNewSe
You're correct - if the user renames the file first, VS will then prompt to rename the default Service1 references.

2019-03-13 23:32 UTC, dksimpson commented on docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md
> +4. Edit the `MyNewService()` constructor to define a custom event log:
VS adds these System.Diagnostics by default in Service1.cs when you create a C# Windows service project.  However VS doesn't add any includes for a VB project.

2019-03-14 23:18 UTC, dksimpson commented
Hello @rpetrusha, I've incorporated your updates. Let me know if there's anything else you'd like me to change.

2019-03-19 17:28 UTC, rpetrusha approved these changes

2019-03-19 17:29 UTC, rpetrusha commented
Thank you for making the additional changes, @dksimpson. I'll merge your PR now.

2019-03-19 17:29 UTC, merged