1463880 8
dotnet/docs pull request #11249
Opened 2019-03-11 04:36 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-12 04:55 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031200048/Report/.

2019-03-12 07:38 UTC, mairaw requested changes
Changes look great @damabe. Left a few suggestions that can be batched in a single via the [Files changed](https://github.com/dotnet/docs/pull/11249/files) tab, Some changes will have to be manual since they require to rename the image name.

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
>   The first document example contains a document that has a number of network share names; for example `\\server1\folder\file.ext`. Whether you have this network link in an Arabic or English document,
```suggestion
 The first document example contains a document that has a number of network share names; for example `\\server1\folder\file.ext`. Whether you have this network link in an Arabic or English document, you always want it to appear in the same way. The following graphic illustrates using the Span element and shows the link in an Arabic <xref:System.Windows.FlowDirection.RightToLeft> document:
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
> + The following graphic illustrates this.
```suggestion
 The following graphic illustrates this by using the Run element embedded in a Span element:
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
> + ![Graphic illustrates the Run element embedded in a Span element.](./media/bidirectional-features-in-wpf-overview/embedded-span-element.png)
```suggestion
 ![Graphic that illustrates the Run element embedded in a Span element.](./media/bidirectional-features-in-wpf-overview/embedded-span-element.png)  
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
>   <xref:System.Windows.FlowDirection> defines not only how text flows in a textual element but also the flow direction of almost every other [!INCLUDE[TLA2#tla_ui](../../../../includes/tla2sharptla-ui
```suggestion

 <xref:System.Windows.FlowDirection> defines not only how text flows in a textual element but also the flow direction of almost every other [!INCLUDE[TLA2#tla_ui](../../../../includes/tla2sharptla-ui-md.md)] element. The following graphic shows a <xref:System.Windows.Controls.ToolBar> that uses a horizontal <xref:System.Windows.Media.LinearGradientBrush> to draw its background with a left to right gradient.  
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
>   The following graphic shows the output of the previous example.
```suggestion
 The following graphic shows the output of the previous example with arrows drawn using the `Path` element:
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
> + ![Graphic that illustrates arrows drawn using the path element.](./media/bidirectional-features-in-wpf-overview/arrows-drawn-path-element.png)
```suggestion
 ![Graphic that illustrates arrows drawn using the Path element.](./media/bidirectional-features-in-wpf-overview/arrows-drawn-path-element.png)  
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
>   The following graphic shows the output of the previous sample if you are running in an Arabic version of [!INCLUDE[TLA#tla_mswin](../../../../includes/tlasharptla-mswin-md.md)].
```suggestion
 The following graphic shows the output of the previous sample if you're running in an Arabic version of Windows with Arabic and English numbers displayed:
```

2019-03-12 07:38 UTC, mairaw commented on docs/framework/wpf/advanced/bidirectional-features-in-wpf-overview.md
>   The following graphic shows what the window looks like for either programming language.
```suggestion
 The following graphic shows what the window looks like for either programming language, displaying Arabic numbers:
```

2019-03-13 02:24 UTC, damabe commented
@mairaw Fixes have been made. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031300037/Report/

2019-03-13 18:41 UTC, mairaw approved these changes
Thank you @damabe!

2019-03-13 18:42 UTC, merged