Updates to the CLI commands reference
dotnet/docs pull request #1129
Opened 2016-10-07 23:26 UTC by mairaw

Since I was going to respond to a customer feedback given on LiveFyre who noticed an example using `dotnet compile` in our docs, I took the opportunity to address also the following issues for this set of topics which I've been wanting to do for a while now:
- #1083 
- #808 
- formatting issues
- changed the order of the example explanation
- added missing options (such as --help for all commands, dotnet-publish was missing a bunch, and so forth)

/cc @blackdwarf @piotrpMSFT can one of you please help review this?

2016-10-07 23:39 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129)  
  Please see 7 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/core/tools/project-json,md). Referenced by file: docs/core/tools/dotnet-build.md at line: 73...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C7%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610072326167551-1129%5Cworkflow_report.html).

2016-10-07 23:52 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129)  
  Please see 7 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/core/tools/project-json,md). Referenced by file: docs/core/tools/dotnet-build.md at line: 73...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C7%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610072332013536-1129%5Cworkflow_report.html).

2016-10-08 01:05 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129)  
  Please see 7 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C8%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610080051232835-1129%5Cworkflow_report.html).

2016-10-08 12:24 UTC, svick commented on docs/core/tools/dotnet-new.md
> +Language of the project. Defaults to `C#`. Valid values are `csharp`, `fsharp`, `cs` and `fs`.
I think the "also" in the previous version was important. Either this should say something like "additional valid values", or it should list all valid values, including `C#` and `F#`.

2016-10-08 12:24 UTC, svick commented on docs/core/tools/dotnet-new.md
> +`dotnet new -t web`
Should these descriptions be more explicit about the defaults? I.e. say that the first two examples create a console application and the the third example creates a C# application.

2016-10-08 12:24 UTC, svick commented on docs/core/tools/dotnet-pack.md
> +`-c`, `--configuration <Debug|Release>`
The new format with `|` here too.

2016-10-08 12:24 UTC, svick commented on docs/core/tools/dotnet-new.md
>  `-t`, `--type`
I think this option should use the new format that other options use, with `|`.

2016-10-13 01:43 UTC, mairaw commented on docs/core/tools/dotnet-build.md
> +Defines what `*` should be replaced with in the version field in the [project.json](project-json.md#version) file. The format follows NuGet's version guidelines.
It would, I just need to find it 😄 
I'll check with the team if there is any.

2016-10-13 01:45 UTC, mairaw commented on docs/core/tools/dotnet-install-script.md
> +Which version of CLI to install; you need to specify the version as 3-part version (that is, 1.0.0-13232). If omitted, it will default to the first [global.json](global-json.md) that contains the [sd
you're right. I just translated the i.e. automatically. Fixed.

2016-10-13 01:45 UTC, mairaw commented on docs/core/tools/dotnet-install-script.md
> +Which version of CLI to install; you need to specify the version as 3-part version (that is, 1.0.0-13232). If omitted, it will default to the first [global.json](global-json.md) that contains the [sd
Fixed.

2016-10-13 01:46 UTC, mairaw commented on docs/core/tools/dotnet-install-script.md
>  OS X/Linux:
Fixed

2016-10-13 01:46 UTC, mairaw commented on docs/core/tools/dotnet-install-script.md
>  OS X/Linux:
Fixed

2016-10-13 01:47 UTC, mairaw commented on docs/core/tools/dotnet-new.md
> +Language of the project. Defaults to `C#`. Valid values are `csharp`, `fsharp`, `cs` and `fs`.
I agree. Added Other in front of the sentence.

2016-10-13 01:48 UTC, mairaw commented on docs/core/tools/dotnet-new.md
>  `-t`, `--type`
Yes, missed this one.  Fixed.

2016-10-13 01:50 UTC, mairaw commented on docs/core/tools/dotnet-new.md
> +`dotnet new -t web`
I like that. Fixed.

2016-10-13 01:51 UTC, mairaw commented on docs/core/tools/dotnet-pack.md
> +`-c`, `--configuration <Debug|Release>`
Fixed.

2016-10-13 01:54 UTC, mairaw commented
Thanks @svick. I appreciate the feedback. I believe I took care of all your comments except the link to NuGet version guidelines which I don't know yet if we have such a topic.

2016-10-13 02:08 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129)  
  Please see 7 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C13%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610130152139986-1129%5Cworkflow_report.html).

2016-10-13 02:22 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129)  
  Please see 7 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C13%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610130158246577-1129%5Cworkflow_report.html).

2016-10-13 14:43 UTC, BillWagner requested changes
Everything looks great, but I found one typo fix. After that's done, let's merge it.

2016-10-13 14:43 UTC, BillWagner commented on docs/core/tools/dotnet-build.md
> +Build a project and its dependencies for a specific runtime (in this excample, Ubuntu 16.04):
typo "excample"

2016-10-13 18:05 UTC, mairaw commented on docs/core/tools/dotnet-build.md
> +Build a project and its dependencies for a specific runtime (in this excample, Ubuntu 16.04):
Good catch! Fixed,

2016-10-13 18:17 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-build?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-install-script?branch=pr-en-us-1129)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-new?branch=pr-en-us-1129)  
  Please see 7 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C13%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610131805173838-1129%5Cworkflow_report.html).

2016-10-14 21:57 UTC, mairaw commented
@BillWagner good to go?

2016-10-14 22:02 UTC, BillWagner commented
Good to go.  :shipit: now.

2016-10-14 22:03 UTC, merged