SEOImages: User Story 1463880, Part 12
dotnet/docs pull request #11319
Opened 2019-03-15 06:16 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-15 06:35 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031500050/Report/

2019-03-17 22:43 UTC, mairaw requested changes
Looks really good. Just had a question re. one of the file names.

2019-03-17 22:43 UTC, mairaw commented on docs/framework/wcf/feature-details/flowing-transactions-into-and-out-of-workflow-services.md
> +     ![Adding a TransactedReceiveScope activity](./media/flowing-transactions-into-and-out-of-workflow-services/transreceivescope-activity.jpg)
Should we use the full name here? 
```suggestion
     ![Adding a TransactedReceiveScope activity](./media/flowing-transactions-into-and-out-of-workflow-services/transactedreceivescope-activity.jpg)  
```

2019-03-17 23:19 UTC, damabe commented
@mairaw Yes. Good catch. I've updated the file name and related link. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031700048/Report/.

2019-03-18 00:24 UTC, mairaw approved these changes

2019-03-18 00:24 UTC, merged