SEOImages: User Story 1463880, Part 13
dotnet/docs pull request #11320
Opened 2019-03-15 06:57 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-16 00:25 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031600009/Report/

2019-03-17 22:57 UTC, mairaw requested changes
Looks great @damabe. A few suggestions...

2019-03-17 22:57 UTC, mairaw commented on docs/core/porting/project-structure.md
> +![Create an csproj that targets multiple frameworks](./media/project-structure/project-csproj-frameworks.png)
Image name suggestion:
```suggestion
![Create an csproj that targets multiple frameworks](./media/project-structure/multi-targeted-project.png)
```

2019-03-17 22:57 UTC, mairaw commented on docs/core/porting/project-structure.md
> +![.NET Core project with existing project in different folder](./media/project-structure/project-csproj-different.png)
```suggestion
![.NET Core project with an existing project in a different folder](./media/project-structure/separate-projects-same-source.png)
```

2019-03-17 22:57 UTC, mairaw commented on docs/framework/wpf/controls/gridview-overview.md
>   The following illustration shows the table that the previous example creates.
```suggestion
 The following illustration shows the table that the previous example creates. The GridView control displays data from an ItemsSource object:
```

2019-03-17 23:55 UTC, damabe commented
@mairaw Thanks! Changes incorporated. Updated CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031700052/Report/

2019-03-18 00:22 UTC, mairaw approved these changes

2019-03-18 00:23 UTC, merged