SEOImages: User Story 1463880, Part 15
dotnet/docs pull request #11335
Opened 2019-03-16 05:58 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-16 19:36 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: 
https://contentqacats.azurewebsites.net/CheckResults/2019031600054/Report/

There are two image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-18 20:50 UTC, mairaw requested changes
Looks great. Have comments for one of the articles.

2019-03-18 20:50 UTC, mairaw commented on docs/framework/wcf/feature-details/routing-introduction.md
> +|One-Way||![Check mark](./media/routing-introduction/checkmark-indicates-compatibility.gif)||No|An exception is thrown and the transaction is rolled back.|
Let's remove this image and replace it with this character instead
```suggestion
|One-Way||✓||No|An exception is thrown and the transaction is rolled back.|  
```

2019-03-19 01:51 UTC, damabe commented
@mairaw The changes are made. New CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031900041/Report/

There are two image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-19 04:36 UTC, damabe commented
@mairaw I got wires crossed while going between branches. I added three files to this PR. Sorry about that. It is this markdown file: https://review.docs.microsoft.com/en-us/dotnet/framework/wpf/graphics-multimedia/extend-glass-frame-into-a-wpf-application?branch=pr-en-us-11335 and the associated images.

The updated CATS report is here: https://contentqacats.azurewebsites.net/CheckResults/2019031900057/Report/

2019-03-19 22:10 UTC, mairaw commented
No worries @damabe.

2019-03-22 22:07 UTC, mairaw approved these changes
LGTM 🆒

2019-03-22 22:07 UTC, merged