SEOImages: User Story 1463880, Part 19
dotnet/docs pull request #11345
Opened 2019-03-17 04:36 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-17 06:11 UTC, damabe commented
@mairaw This PR is ready for review. CATS report:
https://contentqacats.azurewebsites.net/CheckResults/2019031700011/Report/

There is one image name identified by CATS as being too short. It should be handled at a later time as it is not part of the SEO image without hyphen work.

2019-03-18 23:02 UTC, mairaw requested changes
Thank you @damabe. A few comments before we merge.

2019-03-18 23:02 UTC, mairaw commented on docs/framework/wpf/advanced/how-to-use-automatic-layout-to-create-a-button.md
>   The following graphic shows the output of the code samples.
```suggestion
 The following graphic shows the output of the code samples with auto-resizable buttons:
```

2019-03-18 23:02 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/serialization/index.md
> +![Serialization graphic](./media/index/serialization-graphic.gif)
```suggestion
![Serialization graphic](./media/index/serialization-process.gif)
```

2019-03-19 00:18 UTC, damabe commented
@mairaw Thanks for the feedback! Changes are made. New CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031900004/Report/

There is one image name identified by CATS as being too short. It should be handled at a later time as it is not part of the SEO image without hyphen work.

2019-03-22 22:52 UTC, mairaw approved these changes
LGTM ✌️

2019-03-22 22:52 UTC, merged