SEOImages: User Story 1463880, Part 18
dotnet/docs pull request #11344
Opened 2019-03-17 00:42 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-17 04:07 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031700007/Report/

There are three image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-18 22:51 UTC, mairaw requested changes
Looks good @damabe. A few comments to be addressed before we merge.

2019-03-18 22:51 UTC, mairaw commented on docs/framework/interop/default-marshaling-for-objects.md
> + ![Diagram that showsvVariant passed on the stack.](./media/default-marshaling-for-objects/interop-variant-passed-value-reference.gif)
```suggestion
 ![Diagram that shows variant passed on the stack.](./media/default-marshaling-for-objects/interop-variant-passed-value-reference.gif)  
```

2019-03-18 22:51 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-draw-a-line-with-line-caps.md
> + ![Illustration that shows a line with a round cap.](./media/how-to-draw-a-line-with-line-caps/line-cap-arrowhead-example.gif "pens4")
```suggestion
 ![Illustration that shows a line with a round cap.](./media/how-to-draw-a-line-with-line-caps/line-cap-arrowhead-example.gif)  
```

2019-03-19 00:37 UTC, damabe commented
@mairaw Feedback incorporated. Thanks for the feedback. New CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031900024/Report/

There are three image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-22 22:41 UTC, mairaw approved these changes
Thanks for applying my suggestions @damabe 👍

2019-03-22 22:42 UTC, merged