SEOImages: User Story 1463880, Part 17
dotnet/docs pull request #11343
Opened 2019-03-16 23:01 UTC by damabe

## Summary
Updating image file names and references to improve SEO.

Files #1463880

2019-03-17 00:13 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: 
https://contentqacats.azurewebsites.net/CheckResults/2019031700001/Report/

There is one image name identified by CATS as being too short. It should be handled at a later time as it is art of the SEO image without hyphen work.

2019-03-18 21:25 UTC, mairaw requested changes
Thank you. Have just one suggestion to not use ing on the image file name.

2019-03-18 21:25 UTC, mairaw commented on docs/framework/windows-workflow-foundation/pick-activity.md
> + ![Pick Activity](./media/pick-activity/using-pick-activity-two-branches.jpg)
```suggestion
 ![Pick Activity](./media/pick-activity/pick-activity-two-branches.jpg)  
```

2019-03-19 01:05 UTC, damabe commented
@mairaw Thanks for your help. The change is made. Updated CATS report:

https://contentqacats.azurewebsites.net/CheckResults/2019031900032/Report/

There is one image name identified by CATS as being too short. It should be handled at a later time as it is art of the SEO image without hyphen work.

2019-03-22 22:40 UTC, mairaw approved these changes
Thanks @damabe 🚀

2019-03-22 22:40 UTC, merged