Basic types, classes and structs
dotnet/docs pull request #1134
Opened 2016-10-11 20:15 UTC by stevehoag

Split Types topic and added C# 7 literals features

2016-10-11 20:17 UTC, BillWagner commented
Cool! I'll give this a review this evening.

2016-10-11 20:19 UTC, stevehoag commented
I'm going to need to do another merge - I still had the Structs topic open so the latest changes didn't get in.

2016-10-11 21:30 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C11%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610112116310438-1134%5Cworkflow_report.html).

2016-10-12 01:54 UTC, BillWagner requested changes
Looks good. I made a few comments.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/basic-types.md
>  author:  dotnet-bot
You should change this to you.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/classes.md
>  author:  dotnet-bot
you should change this to you.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/classes.md
> +The **class** keyword is preceded by the access level. Because [public](https://msdn.microsoft.com/en-us/library/yzh058ae.aspx) is used in this case, anyone can create objects from this class. The na
access level should be "access modifier".

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/classes.md
> +Although they are sometimes used interchangeably, a class and an object are different things. A class defines a type of object, but it is not an object itself. An object is a concrete entity based on
I would drop this first clause. class and object should not be used interchangeably.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/structs.md
> +A struct is a value type. When a struct is created, the variable to which the struct is assigned holds the struct's actual data. When the struct is assigned to a new variable, it is copied. The new v
Should `struct` be in inline style?

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/structs.md
>  ms.assetid: a7094b8c-7229-4b6f-82fc-824d0ea0ec40
author and date should change.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/structs.md
> +Value types derive from @System.ValueType, which derives from @System.Object. Types that derive from @System.ValueType have special behavior in the CLR. Value type variables directly contain their va
This is misleading, in a way. It reads like you must define structs by deriving from System.ValueType. That's all implicit.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/structs.md
> +-   A struct can be used as a nullable type and can be assigned a null value.
A nullable corresponding type can be built from any struct type. A struct can't b used as a nullable type.

2016-10-12 01:54 UTC, BillWagner commented on docs/csharp/structs.md
> +In C#, literal values receive a type from the compiler. You can specify how a numeric literal should be typed by appending a letter to the end of the number. For example, to specify that the value 4.
We should probably say "the compiler will infer the `double` type for the literal."

2016-10-12 01:54 UTC, BillWagner commented on samples/snippets/csharp/concepts/structs/literals.cs
> +// Outputs: "I can specify bit patterns:
we should add the value here.

2016-10-12 18:00 UTC, stevehoag commented on docs/csharp/basic-types.md
> +
Good suggestion - done.

2016-10-12 18:00 UTC, stevehoag commented on docs/csharp/classes.md
>  author:  dotnet-bot
Done

2016-10-12 18:19 UTC, stevehoag commented on docs/csharp/classes.md
> +Although they are sometimes used interchangeably, a class and an object are different things. A class defines a type of object, but it is not an object itself. An object is a concrete entity based on
Agreed - I removed it.

2016-10-12 18:23 UTC, stevehoag commented on docs/csharp/structs.md
> +A struct is a value type. When a struct is created, the variable to which the struct is assigned holds the struct's actual data. When the struct is assigned to a new variable, it is copied. The new v
Fixed.

2016-10-12 18:23 UTC, stevehoag commented on docs/csharp/structs.md
>  ms.assetid: a7094b8c-7229-4b6f-82fc-824d0ea0ec40
Done.

2016-10-12 18:24 UTC, stevehoag commented on docs/csharp/structs.md
> +Value types derive from @System.ValueType, which derives from @System.Object. Types that derive from @System.ValueType have special behavior in the CLR. Value type variables directly contain their va
Fixed.

2016-10-12 18:25 UTC, stevehoag commented on docs/csharp/structs.md
> +-   A struct can be used as a nullable type and can be assigned a null value.
Fixed.

2016-10-12 18:47 UTC, mairaw reviewed
Left a few comments for you to address

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/basic-types.md
> +For more information, see [Casting and type conversions](https://msdn.microsoft.com/en-us/library/ms173105.aspx)
nit: missing punctuation in the end

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/basic-types.md
> +-   Each type in the CTS is defined as either a *value type* or a *reference type*. This includes all custom types in the .NET Framework class library and also your own user-defined types. Types that
nit: Missing space before the sentence "Types that you define"

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/classes.md
> +When the object is created, the memory is allocated on the managed heap, and the variable holds only a reference to the location of the object. Types on the managed heap require overhead both when th
nit: missing comma in most scenarios

also: lowercase link (../standard/....)

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/classes.md
> +A class can be declared [abstract](https://msdn.microsoft.com/en-us/library/sf985hc5.aspx). An abstract class contains abstract methods that have a signature definition but no implementation. Abstrac
typo: constrast

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/structs.md
> +Value types are *sealed*, which means, for example, that you cannot derive a type from @System.Int32, and you cannot define a struct to inherit from any user-defined class or struct because a struct
a Object -> an Object

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/structs.md
> +-   Within a struct declaration, fields cannot be initialized unless they are declared as const or static.
should const and static be formatted as inline code?

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/structs.md
> +-   Unlike classes, structs can be instantiated without using a **new** operator.
keywords should be styled as inline code, not bold

2016-10-12 18:47 UTC, mairaw commented on docs/csharp/structs.md
> +-   A struct cannot inherit from another struct or class, and it cannot be the base of a class. All structs inherit directly from **System.ValueType**, which inherits from **System.Object**.
same here. either link to the API in this case or style as inline code.

2016-10-12 18:47 UTC, mairaw commented on samples/snippets/csharp/concepts/classes/class-example.cs
> +        person1.SetName("John Smith");
there's a process to use names in content. are you aware of the process?

2016-10-12 19:09 UTC, stevehoag commented on samples/snippets/csharp/concepts/structs/literals.cs
> +// Outputs: "I can specify bit patterns:
Fixed

2016-10-12 19:14 UTC, stevehoag commented on docs/csharp/basic-types.md
> +-   Each type in the CTS is defined as either a *value type* or a *reference type*. This includes all custom types in the .NET Framework class library and also your own user-defined types. Types that
Fixed.

2016-10-12 19:21 UTC, stevehoag commented on docs/csharp/structs.md
> +-   Within a struct declaration, fields cannot be initialized unless they are declared as const or static.
Fixed.

2016-10-12 19:21 UTC, stevehoag commented on docs/csharp/structs.md
> +Value types are *sealed*, which means, for example, that you cannot derive a type from @System.Int32, and you cannot define a struct to inherit from any user-defined class or struct because a struct
Fixed.

2016-10-12 19:21 UTC, stevehoag commented on docs/csharp/classes.md
> +A class can be declared [abstract](https://msdn.microsoft.com/en-us/library/sf985hc5.aspx). An abstract class contains abstract methods that have a signature definition but no implementation. Abstrac
Fixed.

2016-10-12 19:21 UTC, stevehoag commented on docs/csharp/classes.md
> +When the object is created, the memory is allocated on the managed heap, and the variable holds only a reference to the location of the object. Types on the managed heap require overhead both when th
Fixed.

2016-10-12 19:25 UTC, stevehoag commented on docs/csharp/structs.md
> +-   Unlike classes, structs can be instantiated without using a **new** operator.
Fixed. Btw, this and the next one are artifacts from the CAPS markdown conversion - they were styled as bold in the MSDN source.

2016-10-12 19:26 UTC, stevehoag commented on samples/snippets/csharp/concepts/classes/class-example.cs
> +        person1.SetName("John Smith");
Yes. This snippet came directly from the MSDN docs.

2016-10-12 19:26 UTC, stevehoag commented on docs/csharp/structs.md
> +-   A struct cannot inherit from another struct or class, and it cannot be the base of a class. All structs inherit directly from **System.ValueType**, which inherits from **System.Object**.
Fixed.

2016-10-12 19:42 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C12%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610121928084208-1134%5Cworkflow_report.html).

2016-10-12 20:31 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C12%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610122017085588-1134%5Cworkflow_report.html).

2016-10-12 20:48 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1134)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1134)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C12%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610122034438333-1134%5Cworkflow_report.html).

2016-10-12 20:51 UTC, stevehoag commented
@BillWagner @mairaw  I've addressed all comments and updated the TOC - should be good to go now.

2016-10-13 01:31 UTC, BillWagner approved these changes

2016-10-13 01:32 UTC, BillWagner commented
LGTM.  :shipit:

2016-10-13 01:45 UTC, merged