SEOImages: User Story 1463880, Part 16
dotnet/docs pull request #11342
Opened 2019-03-16 20:23 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-16 22:34 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031600060/Report/

2019-03-18 21:16 UTC, mairaw requested changes
Great changes. Left just a few comments.

2019-03-18 21:16 UTC, mairaw commented on docs/framework/wpf/advanced/optimizing-performance-text.md
> -Hyperlink appearing on MouseEnter
consider moving this as an intro to the image

2019-03-18 21:16 UTC, mairaw commented on docs/framework/wpf/advanced/how-to-specify-whether-a-hyperlink-is-underlined.md
>   In the following example, the underline for the "My MSN" link is dynamic—it only appears when the <xref:System.Windows.ContentElement.MouseEnter> event is triggered.
```suggestion
 In the following example, the underline for the "My MSN" link is dynamic, that is, it only appears when the <xref:System.Windows.ContentElement.MouseEnter> event is triggered. 
```

2019-03-19 01:12 UTC, damabe commented
@mairaw Thanks! The changes are made. New CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031900035/Report/

2019-03-22 22:21 UTC, mairaw approved these changes
Looks great @damabe! Thanks! :shipit:

2019-03-22 22:21 UTC, merged