SEOImages: User Story 1463880, Part 24
dotnet/docs pull request #11357
Opened 2019-03-18 03:58 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-18 05:20 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031800010/Report/

There are seven image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-26 04:36 UTC, damabe commented
Updated based on other PR review feedback. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032600053/Report/

2019-03-29 02:09 UTC, mairaw requested changes
Looks good @damabe. A few suggestions.

2019-03-29 02:09 UTC, mairaw commented on docs/framework/wpf/advanced/cleartype-registry-settings.md
> + ![Screenshot that shows ClearType settings in the Registry Editor.](./media/cleartype-registry-settings/cleartype-settings-registry-editor.png)
```suggestion
 ![ClearType settings in the Registry Editor.](./media/cleartype-registry-settings/cleartype-settings-registry-editor.png)  
```

2019-03-29 03:11 UTC, damabe commented
@mairaw Updated the PR. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019032900052/Report/

2019-03-29 23:24 UTC, mairaw approved these changes
Thank you @damabe!

2019-03-29 23:24 UTC, merged