SEOImages: User Story 1463880, Part 23
dotnet/docs pull request #11356
Opened 2019-03-18 02:34 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-18 03:49 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031800008/Report/

2019-03-26 03:59 UTC, damabe commented
Updated with feedback from other PR reviews. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019032600045/Report/

2019-03-27 08:40 UTC, mairaw requested changes
Changes look good @damabe. Left some comments for you re. expanding a bit more on the alt text.

2019-03-27 08:40 UTC, mairaw commented on docs/framework/wpf/app-development/dialog-boxes-overview.md
> + ![Screenshot that shows a Word Processor dialog box.](./media/dialog-boxes-overview/word-processor-dialog.png)
```suggestion
 ![A Word Processor dialog box asking if you want to save the changes to the document before the application closes.](./media/dialog-boxes-overview/word-processor-dialog.png)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/framework/wpf/app-development/dialog-boxes-overview.md
> + ![Screenshot that shows an Open dialog box.](./media/dialog-boxes-overview/open-file-dialog-box.png)
```suggestion
 ![An Open dialog box showing the location to retrieve the file.](./media/dialog-boxes-overview/open-file-dialog-box.png)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/framework/wpf/app-development/dialog-boxes-overview.md
> + ![Screenshot that shows a Save As dialog box.](./media/dialog-boxes-overview/save-file-dialog-box.png)
```suggestion
 ![A Save As dialog box showing the location to save the file.](./media/dialog-boxes-overview/save-file-dialog-box.png)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/framework/wpf/app-development/dialog-boxes-overview.md
> + ![Screenshot that shows a Margins dialog box.](./media/dialog-boxes-overview/margin-size-dialog-box.png)
```suggestion
 ![A Margins dialog box with fields to define left margin, top margin, right margin, and bottom margin.](./media/dialog-boxes-overview/margin-size-dialog-box.png)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/framework/wpf/app-development/dialog-boxes-overview.md
> + ![Screenshot that shows an invalid left margin.](./media/dialog-boxes-overview/invalid-left-margin-dialog.png)
```suggestion
 ![A Margins dialog box with a red border around the invalid left margin value.](./media/dialog-boxes-overview/invalid-left-margin-dialog.png)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/arrays/array-dimensions.md
> + ![Diagram that shows a one&#45;dimensional array.](./media/array-dimensions/one-dimensional-array.gif)
```suggestion
 ![Diagram that shows a one-dimensional array.](./media/array-dimensions/one-dimensional-array.gif)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/arrays/array-dimensions.md
> + ![Diagram that shows a two&#45;dimensional array.](./media/array-dimensions/two-dimensional-array.gif)
```suggestion
 ![Diagram that shows a two-dimensional array.](./media/array-dimensions/two-dimensional-array.gif)  
```

2019-03-27 08:40 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/arrays/array-dimensions.md
> + ![Diagram that shows a three&#45;dimensional array.](./media/array-dimensions/three-dimensional-array.gif)
```suggestion
 ![Diagram that shows a three-dimensional array.](./media/array-dimensions/three-dimensional-array.gif)  
```

2019-03-28 00:37 UTC, damabe commented
@mairaw Made the requested updates. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032800007/Report/

A couple of the alt text changes you requested are over 70 characters so will end up throwing an error on max alt length. I made the changes so please let me know if you want me to change to something else.

2019-03-28 17:20 UTC, mairaw approved these changes
Changes look good @damabe. Thank you!

2019-03-28 17:20 UTC, merged