SEOImages: User Story 1463880, Part 25
dotnet/docs pull request #11358
Opened 2019-03-18 05:40 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-19 05:08 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031900059/Report/

2019-03-26 04:55 UTC, damabe commented
Updated based on other PR review feedback. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032600057/Report/

2019-03-30 00:34 UTC, mairaw commented
Closed and reopened since one of the images was missing:
![image](https://user-images.githubusercontent.com/12971179/55268637-ef742500-5248-11e9-833a-29100fceb5d6.png)

2019-03-30 04:58 UTC, damabe commented
@mairaw fixed the path to the image. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019033000033/Report/

2019-04-01 01:24 UTC, mairaw requested changes
Thanks @damabe. A few suggestions left.

2019-04-01 01:24 UTC, mairaw commented on docs/visual-basic/developing-apps/customizing-extending-my/extending-the-visual-basic-application-model.md
> + ![Diagram showing the Application Model next instance.](./media/extending-the-visual-basic-application-model/application-model-next-instance.gif)
```suggestion
 ![Diagram showing the OnStartupNextInstance method raising the StartupNextInstance event.](./media/extending-the-visual-basic-application-model/raise-startupnextinstance-event.gif)  
```

2019-04-01 01:24 UTC, mairaw commented on docs/visual-basic/developing-apps/customizing-extending-my/extending-the-visual-basic-application-model.md
> + ![Diagram showing the Application Model unhandled exception.](./media/extending-the-visual-basic-application-model/application-model-unhandled-exception.gif)
```suggestion
 ![Diagram showing the OnUnhandledException method raising the UnhandledException event.](./media/extending-the-visual-basic-application-model/raise-unhandledexception-event.gif)  
```

2019-04-02 04:10 UTC, damabe commented
@mairaw These changes have been made. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019040200062/Report/

2019-04-02 05:35 UTC, mairaw approved these changes
Thanks!

2019-04-02 05:35 UTC, merged