SEOImages: User Story 1463880, Part 21
dotnet/docs pull request #11353
Opened 2019-03-17 20:35 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Files #1463880

2019-03-17 21:51 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019031700036/Report/
There are five image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-19 00:55 UTC, mairaw requested changes
Thanks @damabe. A few comments before we merge,

2019-03-19 00:55 UTC, mairaw commented on docs/core/tutorials/debugging-with-visual-studio.md
> +   ![Screenshot that shows an example of a breakpoint.](./media/debugging-with-visual-studio/breakpoint-console-window.png)
```suggestion
   ![Screenshot of a breakpoint in Visual Studio.](./media/debugging-with-visual-studio/breakpoint-console-window.png)
```

2019-03-19 00:55 UTC, mairaw commented on docs/framework/security/wif-claims-programming-model.md
> + ![Diagram that shows the WIF Claims Programming Model.](./media/wif-claims-programming-model/wif-claims-programming-model.png)
```suggestion
 ![Diagram that shows the WIF Claims programming model.](./media/wif-claims-programming-model/wif-claims-programming-model.png)
```

2019-03-19 00:55 UTC, mairaw commented on docs/framework/wcf/feature-details/message-security-with-a-certificate-client.md
> + ![Screenshot that shows a client with certificate.](./media/message-security-with-a-certificate-client/client-with-certificate.gif)
Can you move this before the sentence in line 12?

2019-03-19 00:55 UTC, mairaw commented on docs/framework/windows-workflow-foundation/how-to-create-a-sequential-workflow.md
> +     ![Screenshot that shows a completed sequential workflow.](./media/how-to-create-a-sequential-workflow/complete-sequential-workflow.jpg)
```suggestion
     ![Screenshot that shows the completed sequential workflow.](./media/how-to-create-a-sequential-workflow/complete-sequential-workflow.jpg)  
```

2019-03-19 00:55 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-draw-opaque-and-semitransparent-lines.md
> + The following illustration shows the output of the following code:
can you move this to after the sample code?

2019-03-19 00:55 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-draw-with-opaque-and-semitransparent-brushes.md
> + The following illustration shows the output of the following code:
same here. can you move this to after the code?

2019-03-19 00:55 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-draw-with-opaque-and-semitransparent-brushes.md
> + ![Illustration that shows opaque and semitransparent output.](./media/how-to-draw-with-opaque-and-semitransparent-brushes/comp-qual-ellipse-semitransparent.png)
maybe use the full name of the property?

```suggestion
 ![Illustration that shows opaque and semitransparent output.](./media/how-to-draw-with-opaque-and-semitransparent-brushes/compositingquality-ellipse-semitransparent.png)  
```

2019-03-19 00:55 UTC, mairaw commented on docs/framework/winforms/advanced/media/how-to-draw-with-opaque-and-semitransparent-brushes/desktop.ini
> +[LocalizedFileNames]
we shouldn't be adding this file, right?

2019-03-19 00:55 UTC, mairaw commented on docs/standard/data/xml/xslt-transformations-with-the-xsltransform-class.md
> +![Diagram that shows the XSLT Transformation Architecture.](./media/xslt-transformations-with-the-xsltransform-class/xslt-transformation-architecture.gif)
```suggestion
![Diagram that shows the XSLT transformation architecture.](./media/xslt-transformations-with-the-xsltransform-class/xslt-transformation-architecture.gif) 
```

2019-03-22 23:22 UTC, mairaw commented
@damabe can you address my suggestions here?

2019-03-23 05:21 UTC, damabe commented
@mairaw I've addressed your requested changes. Please have a look. Updated CATS: https://contentqacats.azurewebsites.net/CheckResults/2019032300033/Report/

There are five image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-03-25 22:49 UTC, mairaw approved these changes
Thanks @damabe!

2019-03-25 22:49 UTC, merged