SEOImages: User Story 1463880, Part 27
dotnet/docs pull request #11384
Opened 2019-03-19 07:03 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880)

2019-03-20 01:58 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032000018/Report/

2019-04-01 01:36 UTC, mairaw requested changes
Thanks @damabe. A few comments.

2019-04-01 01:36 UTC, mairaw commented on docs/framework/winforms/controls/bindingnavigator-control-overview-windows-forms.md
>   The <xref:System.Windows.Forms.BindingNavigator> control is composed of a <xref:System.Windows.Forms.ToolStrip> with a series of <xref:System.Windows.Forms.ToolStripItem> objects for most of the com
```suggestion

 The <xref:System.Windows.Forms.BindingNavigator> control is composed of a <xref:System.Windows.Forms.ToolStrip> with a series of <xref:System.Windows.Forms.ToolStripItem> objects for most of the common data-related actions: adding data, deleting data, and navigating through data. By default, the <xref:System.Windows.Forms.BindingNavigator> control contains these standard buttons. The following screenshot shows the <xref:System.Windows.Forms.BindingNavigator> control on a form:
```

2019-04-01 01:36 UTC, mairaw commented on docs/framework/winforms/controls/bindingnavigator-control-overview-windows-forms.md
> + ![Screenshot showing the BindingNavigator Control.](./media/bindingnavigator-control-overview-windows-forms/bindingnavigator-control-form.gif)
```suggestion
 ![Screenshot showing the BindingNavigator control.](./media/bindingnavigator-control-overview-windows-forms/bindingnavigator-control-form.gif)  
```

2019-04-01 01:36 UTC, mairaw commented on docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md
> + ![Screenshot showing an Arabic Homepage.](./media/wpf-globalization-and-localization-overview/arabic-homepage-sample.jpg)
home page - two words (https://docs.microsoft.com/en-us/style-guide/a-z-word-list-term-collections/h/home-home-page)

```suggestion
 ![Screenshot showing an Arabic home page.](./media/wpf-globalization-and-localization-overview/arabic-home-page-sample.jpg)  
```

2019-04-01 01:36 UTC, mairaw commented on docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md
> + ![Screenshot showing an English Homepage.](./media/wpf-globalization-and-localization-overview/english-homepage-sample.jpg)
```suggestion
 ![Screenshot showing an English home page.](./media/wpf-globalization-and-localization-overview/english-home-page-sample.jpg)  
```

2019-04-01 01:36 UTC, mairaw commented on docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md
>  ### Designing a Global Microsoft Homepage
```suggestion
### Designing a global Microsoft home page  
```

2019-04-02 03:34 UTC, damabe commented
@mairaw Changes are incorporated. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019040200056/Report/

2019-04-02 05:36 UTC, mairaw approved these changes
Thanks! :shipit:

2019-04-02 05:36 UTC, merged