SEOImages: User Story 1463880, Part 29
dotnet/docs pull request #11409
Opened 2019-03-20 04:06 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-20 05:16 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032000036/Report/

2019-03-27 03:49 UTC, damabe commented
Updated based on other PR reviews. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032700051/Report/

2019-04-03 23:34 UTC, mairaw requested changes
Thanks @damabe. A few comments before merging this one.

2019-04-03 23:34 UTC, mairaw commented on docs/framework/resources/creating-satellite-assemblies-for-desktop-apps.md
> + ![Diagram that shows a satellite assembly directory.](./media/creating-satellite-assemblies-for-desktop-apps/satellite-assembly-directory.gif
```suggestion
 ![A satellite assembly directory with localized cultures subdirectories.](./media/creating-satellite-assemblies-for-desktop-apps/satellite-assembly-directory.gif)
```

2019-04-03 23:34 UTC, mairaw commented on docs/framework/winforms/controls/datagrid-control-overview-windows-forms.md
> + The following screen shot shows a DataGrid bound to data with multiple tables:
```suggestion
 The following screenshot shows a DataGrid bound to data with multiple tables:  
```

2019-04-03 23:34 UTC, mairaw commented on docs/framework/winforms/controls/datagrid-control-overview-windows-forms.md
> + ![Diagram that shows a DataGrid bound to data with multiple tables.](./media/datagrid-control-overview-windows-forms/datagrid-bound-multiple-tables.gif)
```suggestion
 ![A WinForms app showing a DataGrid bound to data with multiple tables.](./media/datagrid-control-overview-windows-forms/datagrid-bound-multiple-tables.gif)  
```

2019-04-03 23:34 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/control-flow/decision-structures.md
> + ![Diagram that shows an If...Then...Else construction.](./media/decision-structures/if-then-else-construction.gif)
```suggestion
 ![A flow chart of an If...Then...Else construction.](./media/decision-structures/if-then-else-construction.gif)  
```

2019-04-03 23:34 UTC, mairaw commented on docs/visual-basic/programming-guide/program-structure/comments-in-code.md
> + You can add or remove comment symbols for a block of code by selecting one or more lines of code and choosing the **Comment** (![Graphic shows the Visual Basic Comment button.](./media/comments-in-c
```suggestion
 You can add or remove comment symbols for a block of code by selecting one or more lines of code and choosing the **Comment** (![The Visual Basic Comment button in Visual Studio.](./media/comments-in-code/visual-basic-comment-button.gif)) and **Uncomment** (![The Visual Basic Uncomment button in Visual Studio.](./media/comments-in-code/visual-basic-uncomment-button.gif)) buttons on the **Edit** toolbar.  
```

2019-04-04 02:47 UTC, damabe commented
@mairaw I've made these changes. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019040400032/Report/

2019-04-08 16:41 UTC, mairaw approved these changes
Thanks @damabe!

2019-04-08 16:41 UTC, merged