SEOImages: User Story 1463880, Part 28
dotnet/docs pull request #11408
Opened 2019-03-20 02:15 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880)

2019-03-20 03:37 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032000027/Report/

2019-03-26 06:00 UTC, damabe commented
Updated based on other PR reviews. CATS: https://contentqacats.azurewebsites.net/CheckResults/2019032600058/Report/

2019-03-28 03:55 UTC, damabe commented
Updated an altText with a property name. CATS: https://contentqacats.azurewebsites.net/CheckResults/2019032800047/Report/

2019-04-01 04:23 UTC, mairaw requested changes
Looks good @damabe. A few suggestions.

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-rotate-reflect-and-skew-images.md
> + ![Skewed, reflected, translated, and rotated illustration.](./media/how-to-rotate-reflect-and-skew-images/reflected-skewed-rotated-illustration.gif)
```suggestion
 ![The original image and the image mapped to the parallelogram.](./media/how-to-rotate-reflect-and-skew-images/reflected-skewed-rotated-illustration.gif)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-rotate-reflect-and-skew-images.md
> + ![Skewed, reflected, translated, and rotated photo.](./media/how-to-rotate-reflect-and-skew-images/reflected-skewed-rotated-photo.png)
```suggestion
 ![The picture of a climber and the picture mapped to the parallelogram.](./media/how-to-rotate-reflect-and-skew-images/reflected-skewed-rotated-photo.png)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-rotate-reflect-and-skew-images.md
> + ![Skewed, reflected, translated, and rotated metafile.](./media/how-to-rotate-reflect-and-skew-images/reflected-skewed-rotated-metafile.png)
```suggestion
 ![Illustration of shapes and text and that mapped to the parallelogram.](./media/how-to-rotate-reflect-and-skew-images/reflected-skewed-rotated-metafile.png)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-set-pen-width-and-alignment.md
> +     ![Illustration showing green pixels centered on line.](./media/how-to-set-pen-width-and-alignment/green-pixels-centered-line.gif)
```suggestion
     ![A black thin line with green highlight.](./media/how-to-set-pen-width-and-alignment/green-pixels-centered-line.gif)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-set-pen-width-and-alignment.md
>       The following illustration shows the resulting rectangle.
```suggestion
     The following illustration shows the resulting rectangle:
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-set-pen-width-and-alignment.md
> +     ![Illustration showing green pixels centered on a rectangle.](./media/how-to-set-pen-width-and-alignment/green-pixels-centered-rectangle.gif)
```suggestion
     ![A rectangle drawn with black thin lines with green highlight.](./media/how-to-set-pen-width-and-alignment/green-pixels-centered-rectangle.gif)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-set-pen-width-and-alignment.md
> +     ![Illustration showing green pixels inside a rectangle.](./media/how-to-set-pen-width-and-alignment/green-pixels-inside-rectangle.gif)
```suggestion
     ![A rectangle drawn with black lines with the wide green line inside.](./media/how-to-set-pen-width-and-alignment/green-pixels-inside-rectangle.gif)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-set-pen-width-and-alignment.md
>       Now the pixels in the wide green line appear on the inside of the rectangle as shown in the following illustration.
```suggestion
     Now the pixels in the wide green line appear on the inside of the rectangle as shown in the following illustration:
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/wpf/controls/bulletdecorator.md
> + ![Screenshot showing three bullet decorators.](./media/bulletdecorator/three-bullet-decorators.png)
```suggestion
 ![Example of a Checkbox, a RadioButton, and a TextBox bullet decorator.](./media/bulletdecorator/three-bullet-decorators.png)  
```

2019-04-01 04:23 UTC, mairaw commented on docs/framework/wpf/controls/how-to-position-a-tooltip.md
> + ![ToolTip placement by using the Offset property.](./media/how-to-position-a-tooltip/tooltip-placement-offset-property.png)
```suggestion
 ![Diagram showing ToolTip placement by using the Offset property.](./media/how-to-position-a-tooltip/tooltip-placement-offset-property.png)
```

2019-04-02 03:02 UTC, damabe commented
@mairaw Updates have been made. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019040200050/Report/

2019-04-02 05:42 UTC, mairaw approved these changes
Thanks!

2019-04-02 05:42 UTC, merged