SEOImages: User Story 1463880, Part 32
dotnet/docs pull request #11417
Opened 2019-03-20 17:07 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-20 18:29 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032000165/Report/

There are 2 image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-04-09 07:29 UTC, mairaw requested changes
Thank you @damabe. I've left some feedback for you before we can merge this.

2019-04-09 07:29 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-apply-gamma-correction-to-a-gradient.md
> + ![Diagram that shows two gradient-filled rectangles.](./media/how-to-apply-gamma-correction-to-a-gradient/two-rectangles-gamma-gradient.png)
```suggestion
 ![Two gradient-filled rectangles, with and without gamma correction.](./media/how-to-apply-gamma-correction-to-a-gradient/two-rectangles-gamma-gradient.png)  
```

2019-04-09 07:29 UTC, mairaw commented on docs/framework/wpf/advanced/hosting-win32-content-in-wpf.md
> +![Windows Presentation Foundation application dialog screenshot](./media/hosting-win32-content-in-wpf/windows-presentation-foundation-application.png)
```suggestion
![Screenshot of the WPF app running.](./media/hosting-win32-content-in-wpf/windows-presentation-foundation-application.png)
```

2019-04-09 07:29 UTC, mairaw commented on docs/framework/wpf/advanced/walkthrough-hosting-a-wpf-clock-in-win32.md
>  You can recreate this dialog by creating C++ [!INCLUDE[TLA2#tla_win32](../../../../includes/tla2sharptla-win32-md.md)] project in [!INCLUDE[TLA#tla_visualstu](../../../../includes/tlasharptla-visuals
```suggestion
You can recreate this dialog by creating a C++ Win32 project in Visual Studio, and using the dialog editor to create the following:
```

2019-04-09 07:29 UTC, mairaw commented on docs/framework/wpf/data/how-to-bind-the-properties-of-two-controls.md
> + ![Screenshot showing a canvas with a green background.](./media/how-to-bind-the-properties-of-two-controls/data-binding-bind-background-canvas.png)
```suggestion
![Screenshot showing a combo box with the value green selected and a green square.](./media/how-to-bind-the-properties-of-two-controls/data-binding-bind-background-canvas.png)

```

2019-04-09 07:29 UTC, mairaw commented on docs/framework/wpf/data/how-to-bind-the-properties-of-two-controls.md
>   **Note** The binding target property (in this example, the <xref:System.Windows.Controls.Panel.Background%2A> property) must be a dependency property. For more information, see [Data Binding Overvie
```suggestion
> [!NOTE]
> The binding target property (in this example, the <xref:System.Windows.Controls.Panel.Background%2A> property) must be a dependency property. For more information, see [Data Binding Overview](data-binding-overview.md).  
```

2019-04-09 07:29 UTC, mairaw commented on docs/framework/wpf/data/how-to-bind-to-xml-data-using-an-xmldataprovider-and-xpath-queries.md
> + ![Screenshow that shows an XPath example.](./media/how-to-bind-to-xml-data-using-an-xmldataprovider-and-xpath-queries/xpath-example-listbox-details.png)
```suggestion
 ![Screenshot of the XPath example showing the title of four books.](./media/how-to-bind-to-xml-data-using-an-xmldataprovider-and-xpath-queries/xpath-example-listbox-details.png)  
```

2019-04-09 07:29 UTC, mairaw commented on docs/visual-basic/developing-apps/development-with-my/how-my-depends-on-project-type.md
> + ![Diagram that shows the shape of My in a Windows Forms application.](./media/how-my-depends-on-project-type/my-shape-windows-forms-application.png)
```suggestion
 ![Diagram that shows the My object model in a Windows Forms application.](./media/how-my-depends-on-project-type/my-object-model-windows-forms.png)  
```

2019-04-09 07:29 UTC, mairaw commented on docs/visual-basic/developing-apps/development-with-my/how-my-depends-on-project-type.md
> + ![Diagram that shows the shape of My in a Web application.](./media/how-my-depends-on-project-type/my-shape-web-application.png)
```suggestion
 ![Diagram that shows the My object model in a Web application.](./media/how-my-depends-on-project-type/my-object-model-web.png)  
```

2019-04-10 02:49 UTC, damabe commented
@mairaw These changes have been made. Here's the new CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019041000041/Report/

2019-04-22 23:54 UTC, mairaw approved these changes
Thank you @damabe!

2019-04-22 23:54 UTC, merged