SEOImages: User Story 1463880, Part 30
dotnet/docs pull request #11410
Opened 2019-03-20 05:41 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-20 06:51 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032000040/Report/

2019-03-27 04:08 UTC, damabe commented
Updated based on other PR reviews. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032700053/Report/

2019-04-01 23:30 UTC, mairaw requested changes
Thanks @damabe. Left you some comments before merging.

2019-04-01 23:30 UTC, mairaw commented on docs/framework/wcf/feature-details/workflow-service-host-internals.md
> + The <xref:System.ServiceModel.WorkflowServiceHost> class is used to host workflow services. It listens for incoming messages and routes them to the appropriate service instance, creating new instanc
```suggestion

The <xref:System.ServiceModel.WorkflowServiceHost> class is used to host workflow services. It listens for incoming messages and routes them to the appropriate service instance, creating new instances or loading existing instances from durable storage as needed. The following diagram illustrates on a high level how <xref:System.ServiceModel.WorkflowServiceHost> works: 
```

2019-04-01 23:30 UTC, mairaw commented on docs/framework/wcf/feature-details/workflow-service-host-internals.md
> + ![Diagram that shows a Workflow Service Host overview.](./media/workflow-service-host-internals/workflow-service-host-high-level-overview.gif)
```suggestion
 ![Diagram that shows an overview of the Workflow Service Host.](./media/workflow-service-host-internals/workflow-service-host-high-level-overview.gif)  
```

2019-04-01 23:30 UTC, mairaw commented on docs/framework/wcf/feature-details/workflow-service-host-internals.md
> + ![Image showing when WFS Host receives a message and CanCreateInstance is true.](./media/workflow-service-host-internals/workflow-service-host-receive-message-cancreateinstance.gif)
```suggestion
 ![Decision tree used by the WFS Host when it receives a message and CanCreateInstance is true.](./media/workflow-service-host-internals/workflow-service-host-receive-message-cancreateinstance.gif)  
```

2019-04-01 23:30 UTC, mairaw commented on docs/framework/wcf/feature-details/workflow-service-host-internals.md
> + ![Image showing when WFS Host receives a message and CanCreateInstance is false.](./media/workflow-service-host-internals/workflow-service-host-receive-message.gif)
```suggestion
 ![Decision tree used by the WFS Host when it receives a message and CanCreateInstance is false.](./media/workflow-service-host-internals/workflow-service-host-receive-message.gif)  
```

2019-04-01 23:30 UTC, mairaw commented on docs/framework/wpf/app-development/navigation-topologies-overview.md
> + ![Screenshot that shows task pages with data items.](./media/navigation-topologies-overview/navigation-topology-data-items.png)
```suggestion
 ![Task pages with data items and navigation buttons.](./media/navigation-topologies-overview/navigation-topology-data-items.png)  
```

2019-04-01 23:30 UTC, mairaw commented on docs/framework/wpf/controls/wpf-content-model.md
> + ![Screenshot that shows a control from each content model.](./media/wpf-content-model/control-content-model-image-text.png)
```suggestion
 ![Screenshot that shows four different controls, one from each content model.](./media/wpf-content-model/control-content-model-image-text.png)  
```

2019-04-02 02:25 UTC, damabe commented
@mairaw Changes have been made. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019040200034/Report/

2019-04-02 05:46 UTC, mairaw approved these changes

2019-04-02 05:47 UTC, merged