SEOImages: User Story 1463880, Part 31
dotnet/docs pull request #11412
Opened 2019-03-20 15:07 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-20 15:52 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032000095/Report/

There are 9 image names identified by CATS as being too short. They should be handled at a later time as they are not part of the SEO image without hyphen work.

2019-04-01 23:50 UTC, mairaw requested changes
Thanks @damabe. A few comments before merging.

2019-04-01 23:50 UTC, mairaw commented on docs/csharp/programming-guide/concepts/linq/filtering-data.md
> + ![Diagram that shows a LINQ Filtering Operation](./media/filtering-data/linq-filter-operation.png)
```suggestion
 ![Diagram that shows a LINQ filtering operation](./media/filtering-data/linq-filter-operation.png)  
```

2019-04-01 23:50 UTC, mairaw commented on docs/framework/data/adonet/entity-data-model-inheritance.md
> + ![Diagram that shows a model with four entity types.](./media/entity-data-model-inheritance/entity-type-inheritance.gif)
```suggestion
 ![Diagram that shows a conceptual model with four entity types.](./media/entity-data-model-inheritance/entity-type-inheritance.gif)  
```

2019-04-01 23:50 UTC, mairaw commented on docs/framework/data/adonet/entity-data-model-inheritance.md
>   The diagram below shows a conceptual model with four entity types: `Book`, `FictionBook`, `Publisher`, and `Author`. The `FictionBook` entity type is a derived type, inheriting from the `Book` entit
```suggestion

The following diagram shows a conceptual model with four entity types: `Book`, `FictionBook`, `Publisher`, and `Author`. The `FictionBook` entity type is a derived type, inheriting from the `Book` entity type. The `FictionBook` type inherits the `ISBN (Key)`, `Title`, and `Revision` properties, and defines an additional property called `Genre`.  
```

2019-04-01 23:50 UTC, mairaw commented on docs/framework/wcf/diagnostics/tracing/emitting-user-code-traces.md
> -Errors across endpoints for a given request appear in the same activity if the request activity id was propagated
can you move this before the image?

2019-04-01 23:50 UTC, mairaw commented on docs/framework/wcf/diagnostics/tracing/emitting-user-code-traces.md
>   If the service code throws an exception that causes the client to throw as well (for example, when the client did not get the response to its request), both the service and client warning or error m
```suggestion
 If the service code throws an exception that causes the client to throw as well (for example, when the client did not get the response to its request), both the service and client warning or error messages occur in the same activity for direct correlation. In the following image, the service throws an exception that states "The service refuses to process this request in user code." The client also throws an exception that states "The server was unable to process the request due to an internal error."  
```

2019-04-01 23:50 UTC, mairaw commented on docs/framework/wcf/diagnostics/tracing/emitting-user-code-traces.md
> + ![Screenshot that shows errors across endpoints for a given request.](./media/emmiting-user-code-traces/trace-viewer-endpoint-errors.gif)
The folder where the images are has a typo as well

```suggestion
 ![Screenshot of Trace Viewer showing errors across endpoints for a given request.](./media/emitting-user-code-traces/trace-viewer-endpoint-errors.gif)  
```

2019-04-01 23:50 UTC, mairaw commented on docs/framework/wcf/diagnostics/tracing/emitting-user-code-traces.md
> -Graph view of error correlation
can you move this before the image?

2019-04-01 23:50 UTC, mairaw commented on docs/framework/wcf/diagnostics/tracing/emitting-user-code-traces.md
> + ![Screenshot that shows the graph view of error correlation.](./media/emmiting-user-code-traces/trace-viewer-error-correlation.gif)
```suggestion
 ![Screenshot of Trace Viewer showing the graph view of error correlation.](./media/emitting-user-code-traces/trace-viewer-error-correlation.gif)  
```

2019-04-01 23:50 UTC, mairaw commented on docs/standard/garbage-collection/fundamentals.md
>   The following illustration shows background garbage collection performed on a separate dedicated thread on a workstation.
```suggestion
The following illustration shows background garbage collection performed on a separate dedicated thread on a workstation:
```

2019-04-01 23:50 UTC, mairaw commented on docs/visual-basic/developing-apps/development-with-my/index.md
> + ![Diagram shows the Object Model for My.](./media/index/my-object-model-relationships.gif)
```suggestion
 ![Diagram shows the object model for My.](./media/index/my-object-model-relationships.gif)  
```

2019-04-01 23:50 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/filtering-data.md
> + ![Diagram that shows a LINQ Filtering Operation](./media/filtering-data/linq-filter-operation.png)
```suggestion
 ![Diagram that shows a LINQ filtering operation](./media/filtering-data/linq-filter-operation.png)  
```

2019-04-01 23:50 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/data-types/generic-types.md
> + ![Diagram of a screwdriver set.](./media/generic-types/generic-screwdriver-set.gif)
```suggestion
 ![Diagram of a screwdriver set with different heads.](./media/generic-types/generic-screwdriver-set.gif)  
```

2019-04-02 01:58 UTC, damabe commented
@mairaw I've made the changes. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019040200028/Report/

2019-04-02 05:43 UTC, mairaw approved these changes

2019-04-02 05:43 UTC, merged