SEOImages: User Story 1463880, Part 34
dotnet/docs pull request #11426
Opened 2019-03-20 22:31 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-21 06:37 UTC, damabe commented
@mairaw I've updated the identified issues (file names without hyphens) in these files. The index.md file in this PR has a good deal of links that are not close to the 20 character minimum. Also, they don't have alt text for any of them so they are causing a lot of errors in the CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032100062/Report/.

Please let me know if you have a suggestion for the short links. For example, the visual basic icon/logo is named vb.svg. I updated it to visual-basic.svg but that still is not close to the minimum.

2019-04-30 05:39 UTC, mairaw requested changes
Thanks @damabe. Changes look good but left some feedback. Sorry for the delay!

2019-04-30 05:39 UTC, mairaw commented on docs/framework/windows-workflow-foundation/how-to-create-a-flowchart-workflow.md
> +     ![Diagram that shows a completed Windows Workflow flowchart.](./media/how-to-create-a-flowchart-workflow/completed-windows-workflow-flowchart.png)
```suggestion
     ![Diagram that shows a completed Windows Workflow Foundation flowchart.](./media/how-to-create-a-flowchart-workflow/completed-windows-workflow-flowchart.png)  
```

2019-04-30 05:39 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-tile-a-shape-with-an-image.md
> + ![Screenshot that shows a tile image.](./media/how-to-tile-a-shape-with-an-image/rectangle-tile-200x200.gif)
```suggestion
 ![The tile image that shows a red house and a tree.](./media/how-to-tile-a-shape-with-an-image/rectangle-tile-200x200.gif)  
```

2019-04-30 05:39 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-tile-a-shape-with-an-image.md
> + ![Screenshot of a rectangle tiled with an image.](./media/how-to-tile-a-shape-with-an-image/rectangle-tiled-image-no-flip.gif)
```suggestion
 ![A rectangle tiled with the image using the same orientation for all tiles.](./media/how-to-tile-a-shape-with-an-image/rectangle-tiled-image-no-flip.gif)  
```

2019-04-30 05:39 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-tile-a-shape-with-an-image.md
> + ![Screenshot that shows a tile flipped horizontally.](./media/how-to-tile-a-shape-with-an-image/rectangle-tiled-image-horizontal-flip.gif)
```suggestion
 ![A rectangle tiled with the image flipped horizontally.](./media/how-to-tile-a-shape-with-an-image/rectangle-tiled-image-horizontal-flip.gif)  
```

2019-04-30 05:39 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-tile-a-shape-with-an-image.md
> + ![Screenshot that shows a tile flipped horizontally and vertically.](./media/how-to-tile-a-shape-with-an-image/rectangle-tiled-image-horizontal-vertical-flip.gif)
```suggestion
 ![A rectangle tiled with the image flipped horizontally and vertically.](./media/how-to-tile-a-shape-with-an-image/rectangle-tiled-image-horizontal-vertical-flip.gif)  
```

2019-04-30 05:39 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-use-a-color-matrix-to-transform-a-single-color.md
> + ![Screenshot that shows the color transformation of an image.](./media/how-to-use-a-color-matrix-to-transform-a-single-color/color-transformation.png)
```suggestion
 ![A purple square on the left and a fuchsia square on the right.](./media/how-to-use-a-color-matrix-to-transform-a-single-color/color-transformation.png)  
```

2019-04-30 05:54 UTC, damabe commented
@mairaw Thanks for the feedback. The updates have been made.

2019-04-30 06:39 UTC, mairaw approved these changes
Thank you @damabe!

2019-04-30 06:39 UTC, merged