SEOImages: User Story 1463880, Part 36
dotnet/docs pull request #11451
Opened 2019-03-22 04:48 UTC by damabe

## Summary

Updating image file names and references to improve SEO.

Fixes #1463880

2019-03-22 05:44 UTC, damabe commented
@mairaw This PR is ready for review. CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019032200061/Report/

2019-03-29 17:39 UTC, Thraka requested changes
Looks good, just needs one fix.

2019-03-29 17:39 UTC, Thraka commented on docs/framework/winforms/advanced/walkthrough-creating-an-accessible-windows-based-application.md
> +  Your form will look something like the following image:
This needs to be indented otherwise the screenshot below renders as a code block

2019-03-30 19:35 UTC, damabe commented
@Thraka I've made the update. New CATS report: https://contentqacats.azurewebsites.net/CheckResults/2019033000069/Report/

2019-03-30 23:37 UTC, mairaw approved these changes
Looks great @damabe. A couple of additional alt text suggestions.

2019-03-30 23:37 UTC, mairaw commented on docs/csharp/tutorials/working-with-linq.md
> +![Screenshot that shows a Console window.](./media/working-with-linq/console-52-card-application.png)
I think the original alt text was more descriptive

```suggestion
![A console window showing the app writing out 52 cards.](./media/working-with-linq/console-52-card-application.png)
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/wcf/feature-details/wcf-web-http-service-help-page.md
> + ![Screenshot that shows the WCF REST Help page.](./media/wcf-web-http-service-help-page/windows-communication-foundation-rest-help-page.gif)
```suggestion
 ![A browser with the WCF REST Help page open.](./media/wcf-web-http-service-help-page/windows-communication-foundation-rest-help-page.gif)  
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/wcf/feature-details/wcf-web-http-service-help-page.md
> + ![Screenshot showing WCF REST Help Page details.](./media/wcf-web-http-service-help-page/windows-communication-foundation-rest-help-page-detail.gif)
```suggestion
 ![A browser with the WCF REST Help page details for the GetCustomers method open.](./media/wcf-web-http-service-help-page/windows-communication-foundation-rest-help-page-detail.gif)  
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-shear-colors.md
> + ![Screenshot that shows an original image and a sheared image.](./media/how-to-shear-colors/original-image-sheared-image.png)
```suggestion
 ![Two squares with colored stripes side-by-side illustrating the original image and the sheared image.](./media/how-to-shear-colors/original-image-sheared-image.png)  
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/winforms/advanced/walkthrough-creating-an-accessible-windows-based-application.md
> +      ![Screenshot that shows the pizza order form.](./media/walkthrough-creating-an-accessible-windows-based-application/visual-basic-pizza-order-form.gif)
```suggestion
      ![The pizza order form with a name textbox, and size and toppings selection.](./media/walkthrough-creating-an-accessible-windows-based-application/visual-basic-pizza-order-form.gif)  
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/wpf/graphics-multimedia/how-to-set-the-tile-size-for-a-tilebrush.md
> +![Screenshot that shows tiling with an image brush.](./media/how-to-set-the-tile-size-for-a-tilebrush/rectangle-tile-image-brush.png)
```suggestion
![A rectangle with four cherries demonstrating tiling with an image brush.](./media/how-to-set-the-tile-size-for-a-tilebrush/rectangle-tile-image-brush.png)
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/wpf/graphics-multimedia/how-to-set-the-tile-size-for-a-tilebrush.md
>  The following example uses an <xref:System.Windows.Media.ImageBrush>, a type of <xref:System.Windows.Media.TileBrush>, to paint a rectangle with tiles. The example sets each tile to  50 percent by 50
```suggestion
The following example uses an <xref:System.Windows.Media.ImageBrush>, a type of <xref:System.Windows.Media.TileBrush>, to paint a rectangle with tiles. The example sets each tile to 50 percent by 50 percent of the output area (the rectangle). As a result, the rectangle is painted with four projections of the image.
```

2019-03-30 23:37 UTC, mairaw commented on docs/framework/wpf/graphics-multimedia/how-to-set-the-tile-size-for-a-tilebrush.md
> +![Screenshot that shows a tiled TileBrush with a Viewport.](./media/how-to-set-the-tile-size-for-a-tilebrush/25-x-25-viewport-tilebrush.png)
```suggestion
![A rectangle with forty-eight cherries demonstrating a tiled TileBrush with a Viewport.](./media/how-to-set-the-tile-size-for-a-tilebrush/25-x-25-viewport-tilebrush.png)
```

2019-03-30 23:37 UTC, mairaw requested changes
Mistakenly hit the approve button.

2019-03-31 20:21 UTC, damabe commented
Updates made. New CATS: https://contentqacats.azurewebsites.net/CheckResults/2019033100034/Report/

2019-04-01 19:14 UTC, Thraka approved these changes

2019-04-01 19:30 UTC, mairaw approved these changes
Thank you @damabe!

2019-04-01 19:30 UTC, merged