fix: MD033/no-inline-html
dotnet/docs pull request #11463
Opened 2019-03-22 20:09 UTC by nschonni

- Escape inline elements that didn't render
- Ignore elements currently used by Markdown tables
- Encode elements inside pre/code blocks

2019-03-22 20:44 UTC, Lxiamail reviewed
Didn't see any technical concern with WCF related doc updates. Thanks

2019-03-22 23:03 UTC, rpetrusha requested changes
Thanks, @nschonni. In the toc.md files, however, the backslash is rendering in the output TOC. And one change was unrelated to the original paragraph.

2019-03-22 23:27 UTC, mairaw commented
Unfortunately, the proper Markdown syntax never worked for the TOC files. 

Also, with PR #11443, you'd get a lot of merge conflicts.

2019-03-22 23:36 UTC, nschonni commented
I'll fix @rpetrusha's catch, and I'll just rebase to remove all the TOC changes once that other PR lands

2019-03-22 23:43 UTC, nschonni commented on docs/framework/wcf/troubleshooting-the-getting-started-tutorial.md
> + Visual Studio saves project files in c:\users\\<user name\>\Documents\\<Visual Studio version\>\Projects.
Not sure where that came from, but I undid the change

2019-03-23 00:00 UTC, nschonni commented
Actually, just removed the TOC changes since it was simple while reverting the other change

2019-03-25 15:28 UTC, rpetrusha approved these changes

2019-03-25 15:28 UTC, rpetrusha commented
Thanks, @nschonni. I'll merge your PR now.

2019-03-25 15:28 UTC, merged