Adding more values to messageVersion
dotnet/docs pull request #11544
Opened 2019-03-28 16:11 UTC by CarlosACepeda

## Summary

<textMessageEncoding> messageVersion attribute also supports Soap11 and Soap12 
as defined in: [MessageVersion](https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.messageversion?view=netframework-4.7.2)

Fixes #Issue_Number (if available)

2019-03-29 17:12 UTC, Thraka commented
@Lxiamail Need your review on this one. Thanks!

2019-03-29 17:20 UTC, CarlosACepeda commented
I would like to mention that the messageVersion depends algo on the Binding used, this is never said in the docs.
for example:
<customBinding> does not seem to recognize values such as:
Soap11WSAddressing10

2019-03-29 17:20 UTC, rpetrusha requested changes
Thanks, @CarlosACepeda, for contributing to the dotnet/docs repo and enhancing the documentation for the \<textMessageEncoding> element. I've suggested one change.

2019-03-29 17:20 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/textmessageencoding.md
> +|messageVersion|Specifies the SOAP version of the messages sent using the binding. Valid values are<br /><br /> -   Soap11Addressing10<br />-   Soap12Addressing10<br />-   Soap11<br />-  Soap12<br />
```suggestion
|messageVersion|Specifies the SOAP version of the messages sent using the binding. Valid values are<br /><br /> -   Soap11Addressing10<br />-   Soap12Addressing10<br />-   Soap11<br />-  Soap12<br /><br />The default is Soap12Addressing10. This attribute is of type <xref:System.ServiceModel.Channels.MessageVersion>.|  
```

2019-03-29 18:57 UTC, rpetrusha commented
You can add that information in this PR with a new commit, @CarlosACepeda.

2019-04-09 07:03 UTC, mairaw commented
@CarlosACepeda can you hit the Commit suggestion button in Ron's comment so we can merge this PR?

![image](https://user-images.githubusercontent.com/12971179/55779628-c9296300-5a5a-11e9-95a0-a0c893b0b79a.png)

2019-04-15 20:57 UTC, rpetrusha approved these changes

2019-04-15 20:57 UTC, rpetrusha commented
Thanks, @CarlosACepeda. We'll merge your PR now. The update should appear live on docs.microsoft.com in the next day or two.

2019-04-15 20:57 UTC, merged