November changes
dotnet/docs pull request #1157
Opened 2016-10-17 18:05 UTC by cartermp

This changes the layout of things quite a bit to align with our November release and upcoming changes to the .NET Docs hub page.  Here are the changes:

* "About .NET" section with have a simple, small article at its index.  It will now also have three articles underneath it:
    - Getting Started
    - Tour of .NET
    - .NET Products (potential rename, but this is a simple, small article which gives an overview of the .NET Standard Library, runtimes, and tooling)

* .NET Fundamentals Guide replaces .NET Standard Guide, with a new index article that will have a small amount of content giving a short overview of fundamental .NET Content and provide a suggested pathway through the docs.

Note that much of the content is still yet to be written.  This is intentional.  We want to get stubs in so that the developers of the redesigned Docs hub page can link to the correct articles.  We'll be filling in content in the coming weeks.

2016-10-17 18:19 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  
  Please see 27 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/index.md). Referenced by file: docs/welcome.md at line: 47...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610171805572938-1157%5Cworkflow_report.html).

2016-10-17 20:08 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157)  
  Please see 14 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/standard/index.md). Referenced by file: docs/welcome.md at line: 47...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610171954242989-1157%5Cworkflow_report.html).

2016-10-17 20:26 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157)  
  Please see 14 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/fundamentals/index.md). Referenced by file: docs/welcome.md at line: 46...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610172012227091-1157%5Cworkflow_report.html).

2016-10-17 20:51 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157)  
  Please see 14 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/fundamentals/index.md). Referenced by file: docs/welcome.md at line: 46...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610172034239650-1157%5Cworkflow_report.html).

2016-10-17 21:19 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157)  
  Please see 14 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610172106023284-1157%5Cworkflow_report.html).

2016-10-17 21:35 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/about/products?branch=pr-en-us-1157)  
  Please see 14 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610172121383788-1157%5Cworkflow_report.html).

2016-10-17 21:50 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  Please see 14 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C17%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610172123036788-1157%5Cworkflow_report.html).

2016-10-20 15:45 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  Please see 10 more published files of this docset in report.  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/about/products.md). Referenced by file: docs/platform/tour.md at line: 23...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610201533532682-1157%5Cworkflow_report.html).

2016-10-20 16:01 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  Please see 10 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610201549510679-1157%5Cworkflow_report.html).

2016-10-20 16:42 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  Please see 10 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610201629463041-1157%5Cworkflow_report.html).

2016-10-20 18:04 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  Please see 10 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610201751357365-1157%5Cworkflow_report.html).

2016-10-20 18:18 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  Please see 10 more published files of this docset in report.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610201806576498-1157%5Cworkflow_report.html).

2016-10-25 22:04 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/platform/products.md)...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C25%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610252148260572-1157%5Cworkflow_report.html).

2016-10-25 22:22 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/platform/products.md). Referenced by file: docs/platform/index.md at line: 29...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C25%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610252206053327-1157%5Cworkflow_report.html).

2016-10-26 00:00 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/platform/concept.md). Referenced by file: docs/platform/tour.md at line: 21...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C26%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610252343341436-1157%5Cworkflow_report.html).

2016-10-26 00:18 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C26%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610260002093072-1157%5Cworkflow_report.html).

2016-10-26 03:07 UTC, mairaw commented
Are you going to rename the folder too? How are you going to deal with redirects? I'd wait to rename the folder until we have a better redirect solution.

2016-10-26 15:25 UTC, cartermp commented
I've already renamed the folder - redirects can't handle those changes?  We want to get this in ASAP so that we have the structure to make these changes and have links for the .NET hub page.

2016-10-26 15:53 UTC, mairaw commented
The only way to do redirects today is to keep a copy of the file and apply the redirect metadata to it. So you'd have to keep a copy of the entire structure to be able to do the redirect. There's a feature request to do this on a smarter way and by folder too, but we don't have that yet. I'll send you the documentation on this.

2016-10-28 22:26 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157)  

**Status**: SucceededWithWarning. **Message**: Warning occurred: Invalid file link:(~/docs/platform/index.md). Referenced by file: docs/welcome.md at line: 46...  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201610282213587863-1157%5Cworkflow_report.html).

2016-10-28 22:42 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/structs?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/packages?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/deploying/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/third-party-deps?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-publish?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tools/dotnet-test?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/tutorials/libraries?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/versions/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/async?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/basic-types?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/classes?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201610282231286492-1157%5Cworkflow_report.html).

2016-10-28 22:44 UTC, cartermp commented
@mairaw Look good?  I want to merge this ASAP so that we can have proper links to give folks who are building the hub page.

2016-10-31 20:59 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.keycollection.enumerator?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.keycollection.enumerator?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.keycollection?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.keycollection?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.valuecollection.enumerator?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.valuecollection.enumerator?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.valuecollection?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2.valuecollection?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sorteddictionary-2?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sortedlist-2?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sortedlist-2?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sortedset-1.enumerator?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sortedset-1.enumerator?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sortedset-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.sortedset-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1.enumerator?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1.enumerator?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic.stack-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.generic?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.hashtable?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.hashtable?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.icollection?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.icollection?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.icomparer?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.icomparer?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.idictionary?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.idictionary?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.idictionaryenumerator?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.collections.idictionaryenumerator?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.variantwrapper?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.variantwrapper?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.asyncinfo?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.asyncinfo?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.defaultinterfaceattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.defaultinterfaceattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.eventregistrationtoken?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.eventregistrationtoken?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.eventregistrationtokentable-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.eventregistrationtokentable-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.iactivationfactory?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.iactivationfactory?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.interfaceimplementedinversionattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.interfaceimplementedinversionattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.readonlyarrayattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.readonlyarrayattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.returnvaluenameattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.returnvaluenameattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.windowsruntimebuffer?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.windowsruntimebuffer?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.windowsruntimebufferextensions?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.windowsruntimebufferextensions?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.windowsruntimemarshal?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.windowsruntimemarshal?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.writeonlyarrayattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.windowsruntime.writeonlyarrayattribu [...]

2016-10-31 21:31 UTC, mairaw requested changes
need to review more carefully but found some things to be fixed

2016-10-31 21:31 UTC, mairaw commented on docs/standard/frameworks.md
> +# Frameworks and Tarets
typo: tarets

2016-10-31 21:31 UTC, mairaw commented on docs/standard/index.md
> +ms.date: 06/23/2016
shouldn't this be a more recent date?

2016-10-31 21:31 UTC, mairaw commented on docs/standard/index.md
> +ms.assetid: 2e38e9d9-8284-46ee-a15f-199adc4f26f4
why change the GUID?

2016-10-31 21:31 UTC, mairaw commented on docs/standard/tour.md
> +description: .NET Primer
add description

2016-10-31 21:31 UTC, mairaw commented on docs/core/testing/index.md
> +and using [Dependency Injection](https://docs.asp.net/en/latest/standard/dependency-injection.html)
this link shouldn't be changed

2016-10-31 21:38 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.custombinding?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.custombinding?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.faultconverter?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.faultconverter?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httprequestmessageproperty?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httprequestmessageproperty?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httpresponsemessageproperty?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httpresponsemessageproperty?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httpstransportbindingelement?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httpstransportbindingelement?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httptransportbindingelement?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.httptransportbindingelement?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ichannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ichannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ichannelfactory-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ichannelfactory-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ichannelfactory?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ichannelfactory?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsession?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsession?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsessionchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsessionchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ihttpcookiecontainermanager?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ihttpcookiecontainermanager?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsession?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsession?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsessionchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsessionchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.enumerableexecutor?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.enumerableexecutor?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.enumerablequery-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.enumerablequery-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.enumerablequery?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.enumerablequery?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.binaryexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.binaryexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.blockexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.blockexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.catchblock?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.catchblock?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.conditionalexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.conditionalexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.constantexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.constantexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.debuginfoexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.debuginfoexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.defaultexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.defaultexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.dynamicexpression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.dynamicexpression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.dynamicexpressionvisitor?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.dynamicexpressionvisitor?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.elementinit?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.elementinit?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.expression-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.expression-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.expression?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.expression?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.linq.expressions.expressiontype?branch=pr-en-us-1157](https://review.docs.m [...]

2016-10-31 21:51 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsession?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsession?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsessionchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iduplexsessionchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ihttpcookiecontainermanager?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ihttpcookiecontainermanager?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsession?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsession?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsessionchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.iinputsessionchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.imessageproperty?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.imessageproperty?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ioutputchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ioutputchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ioutputsession?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ioutputsession?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ioutputsessionchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.ioutputsessionchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.irequestchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.irequestchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.irequestsessionchannel?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.irequestsessionchannel?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.isession?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.isession?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.isessionchannel-1?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.isessionchannel-1?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.localclientsecuritysettings?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.servicemodel.channels.localclientsecuritysettings?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.foundation?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.foundation?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.color?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.color?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation.elementnotavailableexception?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation.elementnotavailableexception?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation.elementnotenabledexception?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation.elementnotenabledexception?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.automation?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.controls.primitives.generatorposition?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.controls.primitives.generatorposition?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.controls.primitives?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.controls.primitives?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.cornerradius?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.cornerradius?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.duration?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.duration?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.durationtype?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.durationtype?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.gridlength?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.gridlength?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.gridunittype?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.gridunittype?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.layoutcycleexception?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.layoutcycleexception?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.markup.xamlparseexception?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.markup.xamlparseexception?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.markup?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.markup?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.media.animation.keytime?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/windows.ui.xaml.media.animation.keytime?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.co [...]

2016-10-31 22:12 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comeventshelper?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comeventshelper?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comexception?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comexception?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comimportattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comimportattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.cominterfacetype?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.cominterfacetype?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.commembertype?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.commembertype?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comsourceinterfacesattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comsourceinterfacesattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.advf?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.advf?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.bindptr?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.bindptr?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.bind_opts?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.bind_opts?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.callconv?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.callconv?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.connectdata?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.connectdata?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.datadir?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.datadir?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.desckind?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.runtime.interopservices.comtypes.desckind?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.assemblyversionattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.assemblyversionattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.bindingflags?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.bindingflags?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.callingconventions?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.callingconventions?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.constructorinfo?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.constructorinfo?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.context.customreflectioncontext?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.context.customreflectioncontext?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.context?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.context?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributedata?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributedata?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributeextensions?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributeextensions?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributenamedargument?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributenamedargument?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributetypedargument?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.customattributetypedargument?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.defaultmemberattribute?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.defaultmemberattribute?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.dispatchproxy?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.dispatchproxy?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.assemblybuilder?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.assemblybuilder?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.assemblybuilderaccess?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.assemblybuilderaccess?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.constructorbuilder?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.constructorbuilder?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.customattributebuilder?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.customattributebuilder?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.dynamicmethod?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.dynamicmethod?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.enumbuilder?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.enumbuilder?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/core/api/system.reflection.emit.eventbuilder?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-u [...]

2016-11-04 23:17 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/about?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/about?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157)  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C4%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611042302037318-1157%5Cworkflow_report.html).

2016-11-08 17:10 UTC, cartermp commented
@mairaw I addressed your changes.  Is this good to merge?

2016-11-09 19:30 UTC, mairaw reviewed
there's still a broken link. fix that and you can merge

2016-11-09 19:30 UTC, mairaw commented on docs/core/testing/index.md
> +and using [Dependency Injection](https://docs.asp.net/en/latest/platform/dependency-injection.html)
this new link doesn't work. maybe you should link between repos like this: /aspnet/core/fundamentals/dependency-injection

2016-11-09 19:30 UTC, mairaw commented on docs/standard/index.md
> +==========
nit: that's not the header style we use but I wouldn't prevent you from merging 😄

2016-11-11 17:53 UTC, mairaw approved these changes

2016-11-11 17:53 UTC, mairaw commented
just don't forget to fix the link before merging

2016-11-11 18:21 UTC, saldana commented
### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[docs/core/testing/index.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/core/testing/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/core/testing/index?branch=pr-en-us-1157) | [Details](#user-content-docs/core/testing/index.md)
[docs/framework/index.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/framework/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/framework/index?branch=pr-en-us-1157) | [Details](#user-content-docs/framework/index.md)
[docs/standard/about.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/standard/about.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/about?branch=pr-en-us-1157) | [Details](#user-content-docs/standard/about.md)
[docs/standard/concepts.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/standard/concepts.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/concepts?branch=pr-en-us-1157) | [Details](#user-content-docs/standard/concepts.md)
[docs/standard/frameworks.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/standard/frameworks.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/frameworks?branch=pr-en-us-1157) | [Details](#user-content-docs/standard/frameworks.md)
[docs/standard/getting-started.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/standard/getting-started.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/getting-started?branch=pr-en-us-1157) | [Details](#user-content-docs/standard/getting-started.md)
[docs/standard/index.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/standard/index.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/index?branch=pr-en-us-1157) | [Details](#user-content-docs/standard/index.md)
[docs/standard/tour.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/standard/tour.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/standard/tour?branch=pr-en-us-1157) | [Details](#user-content-docs/standard/tour.md)
[docs/toc.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/toc.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/toc.json?branch=pr-en-us-1157) | [Details](#user-content-docs/toc.md)
[docs/welcome.md](https://github.com/cartermp/core-docs/blob/november-changes/docs/welcome.md) | :white_check_mark:Succeeded | [View](https://review.docs.microsoft.com/en-us/dotnet/articles/welcome?branch=pr-en-us-1157) | [Details](#user-content-docs/welcome.md)











For more details, please refer to the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C11%5C11%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201611111808260592-1157%5Cworkflow_report.html).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

2016-11-11 18:22 UTC, merged