Update index.md
dotnet/docs pull request #1163
Opened 2016-10-20 04:25 UTC by zwcloud

Fix links for dotnet-apiport.

2016-10-20 04:25 UTC, dnfclas commented
Hi __@zwcloud__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, DNFBOT;

2016-10-20 04:38 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/index?branch=pr-en-us-1163](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/index?branch=pr-en-us-1163)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C20%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610200425405778-1163%5Cworkflow_report.html).

2016-10-21 23:04 UTC, mairaw requested changes
HI @zwcloud, thanks for your contribution! From what I can see in one of their [commits](https://github.com/Microsoft/dotnet-apiport/commit/678f6c0ad9c19096fdc806d09c263ee08a10110d), the content from that file was moved over to the readme file. So can you please just update the links to point to https://github.com/Microsoft/dotnet-apiport/blob/master/docs/HowTo/ instead of the repo homepage? Thanks!

2016-10-21 23:12 UTC, mairaw commented on docs/core/porting/index.md
> +3. Use the [API Portability Analyzer tool](https://github.com/Microsoft/dotnet-apiport/) to analyze your assemblies and develop a plan to port based on its results.
I think this one is fine as-is. No need to change this one.

2016-10-21 23:12 UTC, mairaw commented on docs/core/porting/index.md
> +* Api Portability Analyzer - [command line tool](https://github.com/Microsoft/dotnet-apiport/releases) or [Visual Studio Extension](https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a
Let's change this one to 
```markdown
[.NET Portability Analyzer Tools](https://github.com/Microsoft/dotnet-apiport/blob/master/docs/HowTo/)
```

2016-10-22 13:11 UTC, zwcloud commented on docs/core/porting/index.md
> +* Api Portability Analyzer - [command line tool](https://github.com/Microsoft/dotnet-apiport/releases) or [Visual Studio Extension](https://visualstudiogallery.msdn.microsoft.com/1177943e-cfb7-4822-a
Yes, that's more approprate. Updated.

2016-10-22 13:21 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  [https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/index?branch=pr-en-us-1163](https://review.docs.microsoft.com/en-us/dotnet/articles/core/porting/index?branch=pr-en-us-1163)  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C22%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610221310181217-1163%5Cworkflow_report.html).

2016-10-24 21:06 UTC, mairaw approved these changes

2016-10-24 21:06 UTC, mairaw commented on docs/core/porting/index.md
> +3. Use the [API Portability Analyzer tool](https://github.com/Microsoft/dotnet-apiport/) to analyze your assemblies and develop a plan to port based on its results.
I didn't express myself correctly. Yes, the change is fine as is.

2016-10-24 21:06 UTC, merged