Update duplex.md to use the latest string contact.
dotnet/docs pull request #11644
Opened 2019-04-03 12:02 UTC by Anduin2017

Update duplex.md to use the latest string contact method.

## Summary

Describe your changes here.

Update duplex.md to use the latest string contact method.

2019-04-03 16:39 UTC, rpetrusha requested changes
Thanks, @Anduin2017, for modernizing the code in this example. I've suggested some changes, since the ToString method is called automatically for interpolated expressions that are not of type **string**.

2019-04-03 16:39 UTC, rpetrusha commented on docs/framework/wcf/samples/duplex.md
> +        Callback.Equation($"{equation} = {result.ToString()}");
```suggestion
        Callback.Equation($"{equation} = {result}");  
```

2019-04-03 16:39 UTC, rpetrusha commented on docs/framework/wcf/samples/duplex.md
> +        equation += $" + {n.ToString()}";
```suggestion
        equation += $" + {n}";  
```

2019-04-03 16:44 UTC, Anduin2017 commented
@rpetrusha Wow! Thanks for your suggestion! That makes it really simple now!

2019-04-04 05:05 UTC, EdiWang approved these changes

2019-04-04 15:49 UTC, rpetrusha commented
Thanks, @Anduin2017, for making the additional changes. This looks good. I'll merge your PR, and your changes should be live on docs.microsoft.com in the next day or two.

2019-04-04 15:49 UTC, rpetrusha approved these changes

2019-04-04 15:49 UTC, merged