make caller info sample work with C#
dotnet/docs pull request #11716
Opened 2019-04-07 15:31 UTC by CaringDev

## Summary
Make this sample work when called from C#

### TL;DR;
As it is, C# (respectively the C# compiler) does not understand how to handle e.g. parameters of type `option<string>` decorated with some `[CallerInfoX]` attribute. Instead we would need to supply some `FSharpOption<string>`. Marking the `option`al parameter `[<Optional>]` leads to an optional option, which is OK from C# perspective<sup>1</sup> but always `null`, i.e. `None`. I believe, we should have examples that work for F# and C# out-of-the-box. I'm happy to provide two samples including an explanation, if you think different.

<sup>1</sup> maybe the compiler should emit a warning if it encounters a [CallerInfo] attribute on a type it cannot supply?

2019-04-07 15:31 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=11716) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=11716) before we can accept your contribution.<br/><br/>:x: CaringDev [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=11716)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=11716) it.</sub>

2019-04-08 00:49 UTC, cartermp requested changes
Looks good modulo these changes (this would make the sample equivalent to the C# docs)

2019-04-08 00:49 UTC, cartermp commented on docs/fsharp/language-reference/caller-information.md
> +                      [<CallerMemberName; Optional>] memberName: string,
```suggestion
                      [<CallerMemberName; Optional; DefaultParameterValue("")>] memberName: string,
```

2019-04-08 00:49 UTC, cartermp commented on docs/fsharp/language-reference/caller-information.md
> +                      [<CallerFilePath; Optional>] path: string,
```suggestion
                      [<CallerFilePath; Optional; DefaultParameterValue("")>] path: string,
```

2019-04-08 00:49 UTC, cartermp commented on docs/fsharp/language-reference/caller-information.md
> +                      [<CallerLineNumber; Optional>] line: int) =
```suggestion
                      [<CallerLineNumber; Optional; DefaultParameterValue(0)>] line: int) =
```

2019-04-08 06:27 UTC, CaringDev commented
@cartermp ah, sorry, I should have batch-merged your suggestions instead of fixing them locally... now Github does not recognise them as resolved. Could you check again? Thank you.

2019-04-08 14:54 UTC, cartermp approved these changes
Thanks @CaringDev

2019-04-08 14:54 UTC, merged