Add mnemonic device to C# conditional operator docs
dotnet/docs pull request #11815
Opened 2019-04-12 19:34 UTC by akmadian

## Summary

Added a mnemonic device to help retention of how the C# ?: operator evaluates. The language could use some refining as it is quite informal, but I figured it would be best to get input from others on this instead of trying to struggle through it myself.

Fixes #11802, Here's the PR @BillWagner

2019-04-15 15:23 UTC, Thraka commented on docs/csharp/language-reference/operators/conditional-operator.md
> +A handy [mnemonic device](https://www.google.com/search?q=mnemonic+device&rlz=1C1CHBF_enUS811US811&oq=mnemonic+device&aqs=chrome..69i57j69i61j0l4.2439j0j7&sourceid=chrome&ie=UTF-8) you can use to rem
```suggestion
A handy mnemonic device you can use to remember how this operator evaluates is by asking: `is this cond true ? yes : no`, with the ? part of the operator acting as a question mark for the previous statement, and the consequent acting as the logical response to this question.
```

We wouldn't want to put in search queries directly into the documentation.

2019-04-15 15:28 UTC, Thraka requested changes
@akmadian This looks good! We don't want to have any search queries embedded in the text though. Someone can easily just do their own search if they don't know what a mnemonic device is.

Also, we shouldn't have the mnemonic device in a `code block` as the code blocks aren't translated to other languages. I would use something like.

```markdown
A handy mnemonic device you can use to remember how this operator evaluates is by asking: 

> Is this condition true ? yes : no

The `?` part of the operator acting as a question mark for the previous statement, and the consequent acting as the logical response to this question.
```

2019-04-15 16:07 UTC, akmadian commented
All makes good sense, will make changes when I get back home :)

2019-04-16 16:16 UTC, BillWagner commented
@akmadian It looks like you accepted @Thraka 's suggestion. (Thanks for reviewing while I was OOF).

If you're done, let me know and I'll :shipit:.

2019-04-16 17:21 UTC, Thraka commented
@akmadian The wording is still off though because of the code block. I think you should also spell out condition.

CC @BillWagner

2019-04-16 18:46 UTC, akmadian commented
@Thraka Code block has been added, and I've spelled out conditional. Great suggestions, thanks!

Let's :shipit:!

2019-04-16 20:21 UTC, BillWagner commented
I like it! @Thraka do you want to approve it?

2019-04-16 20:26 UTC, Thraka approved these changes

2019-04-16 20:26 UTC, Thraka commented
@akmadian Thanks again 😄

2019-04-16 20:27 UTC, merged

2019-04-16 21:10 UTC, akmadian commented
Happy to help!