[WIP] Update SentimentAnalysis tutorial
dotnet/docs pull request #11816
Opened 2019-04-12 20:30 UTC by JRAlexander

2019-04-16 17:09 UTC, natke requested changes
Some general comments:
- the Build and Train Model section doesn't actually build and train the model - it more sets up skeleton functions
- In the closing para, you mentioned hyper-parameters but we've not defined these yet
- There is some confusion between the machine learning task and the algorithm to choose for that task. (And I know we don't provide good guidance on that rn). It would be good to clarify this, even if we remain a little vague about why we chose the Scda algorithm.
- I'm not sure we need to save and re-load the model in every single tutorial. This seems like an operational feature that developers could learn about from our How-to on the topic.

2019-04-16 17:12 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +There are three major concepts in ML.NET: [Data](../basic-concepts-model-training-in-mldotnet.md#data), [Transformers](../basic-concepts-model-training-in-mldotnet.md#transformer), and [Estimators](.
We need to define them somewhere.

2019-04-16 17:13 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
>  >[!WARNING]
Nope!

2019-04-16 17:14 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +![classification machine learning algorithm](./media/sentiment-analysis/classification.png)
Sure. Can we leave it for now in the meantime and replace later?

2019-04-16 17:15 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +The [Fit()](xref:Microsoft.ML.Trainers.MatrixFactorizationTrainer.Fit%28Microsoft.ML.IDataView,Microsoft.ML.IDataView%29) method trains your model with the provided training dataset. It executes the
Not sure that is clearer

2019-04-16 17:15 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +## Save model as .zip file
agreed.

2019-04-17 14:09 UTC, luisquintanilla requested changes
Look good. Minor changes.

2019-04-17 14:09 UTC, luisquintanilla commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +`SentimentPrediction` is the prediction class used after the model training. It has a single boolean (`Sentiment`) and a `PredictedLabel` `ColumnName` attribute. The `Label` is used to create and tra
Suggestion: Add xref to `ColumnName`.

2019-04-17 14:09 UTC, luisquintanilla commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +Fit the model to the `Train` data and return the trained model by adding the following as the next line of code in the `BuildAndTrainModel()` method:
Not sure if Train needs to be inlined.

2019-04-17 15:59 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +There are three major concepts in ML.NET: [Data](../basic-concepts-model-training-in-mldotnet.md#data), [Transformers](../basic-concepts-model-training-in-mldotnet.md#transformer), and [Estimators](.
Just defined them at first usage.

2019-04-17 16:04 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +`SentimentPrediction` is the prediction class used after the model training. It has a single boolean (`Sentiment`) and a `PredictedLabel` `ColumnName` attribute. The `Label` is used to create and tra
Its xreffed in the previous paragraph.

2019-04-17 19:50 UTC, JRAlexander commented on docs/machine-learning/tutorials/sentiment-analysis.md
They should be gone. Not needed. Gone now!

2019-04-17 21:02 UTC, luisquintanilla approved these changes

2019-04-18 20:35 UTC, natke approved these changes
One minor comment. Other than that LGTM!

2019-04-18 20:35 UTC, natke commented on docs/machine-learning/tutorials/sentiment-analysis.md
> +The [Predict()](xref:Microsoft.ML.PredictionEngine%602.Predict%2A) function makes a prediction on a single column of data.
column -> row

2019-04-18 20:39 UTC, JRAlexander commented
Thanks, @luisquintanilla and @natke!!

2019-04-18 20:46 UTC, merged