Fix formatting of code samples
dotnet/docs pull request #11822
Opened 2019-04-13 02:56 UTC by dksimpson

Story [1510854](https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1510854/)
Content Update - Localization fix: CC122748: Updated bad code formatting and trailing whitespace

2019-04-13 04:17 UTC, NextTurn commented on docs/framework/wcf/feature-details/interoperable-object-references.md
> +```
```suggestion
```csharp
```

2019-04-13 04:18 UTC, NextTurn commented on docs/framework/wcf/feature-details/interoperable-object-references.md
> +[DataContract(IsReference=true)] public class X`
```suggestion
[DataContract(IsReference=true)]
public class X  
```

2019-04-13 04:18 UTC, NextTurn commented on docs/framework/wcf/feature-details/interoperable-object-references.md
> +```
```suggestion
```xml
```

2019-04-15 15:22 UTC, Thraka commented
@dksimpson The suggestions from @NextTurn are good. Please accept them. Thanks!

2019-04-15 15:25 UTC, rpetrusha requested changes
Thanks for correcting this badly formatted code, @dksimpson. Both @NextTurn and I have left some suggested changes.

2019-04-15 15:25 UTC, rpetrusha commented on docs/framework/wcf/feature-details/interoperable-object-references.md
> +    <B ref="1">
```suggestion
    <B ref="1"></B>
```

2019-04-15 15:25 UTC, rpetrusha commented on docs/framework/wcf/feature-details/interoperable-object-references.md
> +    </B>
```suggestion
 ```

2019-04-15 18:56 UTC, dksimpson commented
@NextTurn @rpetrusha @Thraka  Thanks everyone for your review comments - I've updated the article.

2019-04-15 19:02 UTC, rpetrusha approved these changes

2019-04-15 19:03 UTC, rpetrusha commented
Thanks, @dksimpson, for making the additional changes. I'll merge your PR now.

2019-04-15 19:03 UTC, merged