kill dead wood
dotnet/docs pull request #1184
Opened 2016-10-28 00:41 UTC by Rick-Anderson

I was hoping to make this generic so we could use it, but I don't think that's possible. It was too painful to copy so I did some cleanup. We should consider making this generic. If we do, I can help clean it up and maintain it.

2016-10-28 00:48 UTC, mairaw requested changes
Changes look good to me but I have a few comments that I left for you to address. Thanks!

2016-10-28 00:48 UTC, mairaw commented on CONTRIBUTING.md
> +**Step 6:** Terspond to the PR feedback.
Terspond -> Respond

2016-10-28 00:48 UTC, mairaw commented on CONTRIBUTING.md
> +We typically push all commits from master branch into the live branch. You'll be able to see your contribution live at https://docs.microsoft.com/dotnet/ within an hour of the contribution being merg
I wouldn't add any expectations around when changes show up live and it's not that we typically push, we do have to push always.

2016-10-28 00:48 UTC, mairaw commented on CONTRIBUTING.md
> +Install [DocFX](https://dotnet.github.io/docfx/) to build the docs.
to build the docs locally

2016-10-28 00:52 UTC, Rick-Anderson commented on CONTRIBUTING.md
> +We typically push all commits from master branch into the live branch. You'll be able to see your contribution live at https://docs.microsoft.com/dotnet/ within an hour of the contribution being merg
got it. But the original doesn't make much sense and seems to imply quick viewing .

2016-10-28 00:54 UTC, Rick-Anderson commented on CONTRIBUTING.md
> +Install [DocFX](https://dotnet.github.io/docfx/) to build the docs.
Why do you need locally? That's just confusing to me. How else would you build it? I guess it doesn't hurt to leave in locally. I'll add it.

2016-10-28 01:01 UTC, mairaw commented on CONTRIBUTING.md
> +Install [DocFX](https://dotnet.github.io/docfx/) to build the docs.
there are two types of builds: local and automatically triggered OPS builds. not sure how locally can be confusing.

2016-10-28 01:04 UTC, mairaw commented on CONTRIBUTING.md
> +**Step 6:** Rerspond to the PR feedback.
still doesn't say Respond 😄

2016-10-28 01:08 UTC, mairaw commented on CONTRIBUTING.md
> +We periodically push all commits from master branch into the live branch. You'll be able to see your contribution at https://docs.microsoft.com/dotnet/, typically within a few hours of the merge.
which merge are you referring to in the last sentence? the merge to master or the merge to live? we don't always merge to live the same day, so I'm just trying to not create false expectations here.

2016-10-28 01:08 UTC, mairaw commented on CONTRIBUTING.md
> +- **DO** blog, tweet and use other social media to annouce your contribution.
annouce -> announce

2016-10-28 01:11 UTC, Rick-Anderson commented on CONTRIBUTING.md
> +We periodically push all commits from master branch into the live branch. You'll be able to see your contribution at https://docs.microsoft.com/dotnet/, typically within a few hours of the merge.
I'll add merge to live.

2016-10-28 01:34 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610280041176494-1184%5Cworkflow_report.html).

2016-10-28 01:46 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610280102252882-1184%5Cworkflow_report.html).

2016-10-28 02:00 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610280058373571-1184%5Cworkflow_report.html).

2016-10-28 02:14 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610280059381615-1184%5Cworkflow_report.html).

2016-10-28 02:29 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610280118160019-1184%5Cworkflow_report.html).

2016-10-28 02:45 UTC, qinezh commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5C2a032abb-a76c-bfc8-4231-71ab612989a2%5CPullRequest%5C201610280225244961-1184%5Cworkflow_report.html).

2016-10-28 19:41 UTC, saldana commented
Open Publishing Build Service: The pull request content has been published and here are some changed files links of this time:
- Docset 1 - **core-docs**  
  No file of this docset changes.  

**Status**: Succeeded.  
[Open Publishing Report](https://opbuildstorageprod.blob.core.windows.net/report/2016%5C10%5C28%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201610281928497909-1184%5Cworkflow_report.html).

2017-02-14 06:54 UTC, mairaw commented
I'm going through our old PRs. I'll take a look at the current contrib guide for ASP.NET, these changes and merge them into my existing PR for the contributing guide on PR #1081. Thanks @Rick-Anderson!

2017-02-14 06:54 UTC, closed without merging