Replace marshalling/marshalled with marshaling/marshaled
dotnet/docs pull request #12005
Opened 2019-04-24 15:11 UTC by NextTurn

Contributes to #11396 
Fixes #11986

2019-04-24 15:52 UTC, pkulikov commented on docs/standard/native-interop/customize-parameter-marshaling.md
> -title: Customizing parameter marshalling - .NET
A file rename results into the link change. That should be "registered" in the redirection file:
https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json

2019-04-24 18:05 UTC, pkulikov commented on docs/standard/native-interop/customize-parameter-marshaling.md
> -title: Customizing parameter marshalling - .NET
>put the entries somewhere in the middle of the file, don't append to the end.

Entries are sorted alphabetically by the `source_path` field.

2019-04-25 05:42 UTC, mairaw requested changes
Thanks @NextTurn. This looks great. As @pkulikov mentioned, for the file renames, we need to add the entries to the redirect file at https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json, where we sort the entries alphabetically by the `source_path` field. "redirect_document_id" should be true in this case as well.

2019-04-27 01:03 UTC, mairaw commented
@NextTurn apologies, but it seems we have some merge conflicts here. Can you check?

2019-04-28 05:15 UTC, NextTurn commented
What does "redirect_document_id" mean?

2019-04-29 21:19 UTC, mairaw commented
It's for internal purposes. It tells our BI system to flow the data from the old article to the new one. We don't always want to do that.

2019-04-29 21:23 UTC, mairaw approved these changes
Thank you for making the changes @NextTurn. These changes will be going live next week.

2019-04-29 21:23 UTC, merged