Update Taxi Fare tutorial to v 1.0.0-preview
dotnet/docs pull request #12035
Opened 2019-04-25 20:35 UTC by JRAlexander

2019-04-25 22:07 UTC, luisquintanilla requested changes
Looks good @JRAlexander . Minor changes

2019-04-25 22:07 UTC, luisquintanilla commented on docs/machine-learning/tutorials/taxi-fare.md
> +Replace the `Console.WriteLine("Hello World!")` line in the `Main` method with the following code to declare and initialize the mlContext variable:
code fence `mlContext`

2019-04-25 22:07 UTC, luisquintanilla commented on docs/machine-learning/tutorials/taxi-fare.md
> +The [Predict()](xref:Microsoft.ML.PredictionEngine%602.Predict%2A) function makes a prediction on a single column of data.
Suggestion: change column to instance or sample

2019-04-26 21:33 UTC, luisquintanilla approved these changes

2019-04-26 21:46 UTC, JRAlexander commented
Thanks, @luisquintanilla!

2019-04-26 21:50 UTC, merged