Add one more example of reducing null checks.
dotnet/docs pull request #12077
Opened 2019-04-28 22:07 UTC by ericmutta

Added an example of using the null-conditional operator to avoid checking for null when referencing a possibly-null object in an `If` statement (see discussion on #9208).

I wasn't sure where to slot in the extra example, hopefully the current position flows well with the rest of the page. 

PS: since this is the first doc change I have made that isn't a simple typo/grammar fix, I am very much open to the submission being further edited for "flow" or "tone". Much respect to the docs team, it's surprising how difficult it can be to write docs that are both thorough and easy to understand!

Fixes #9208

2019-04-29 23:38 UTC, rpetrusha requested changes
Thanks for adding the additional example to the documentation, @ericmutta. Your additions looks good; I've left some minor suggestions.

2019-04-29 23:38 UTC, rpetrusha commented on docs/visual-basic/language-reference/operators/null-conditional-operators.md
> +Sometimes you need to take an action on an object that may be null, based on the value of a boolean member on that object (like the boolean property `IsAllowedFreeShipping` in the code below):
```suggestion
Sometimes you need to take an action on an object that may be null, based on the value of a Boolean member on that object (like the Boolean property `IsAllowedFreeShipping` in the following example):
```

2019-04-30 08:47 UTC, ericmutta commented
@rpetrusha thanks for the suggested edit, I have applied it :+1:

2019-04-30 15:42 UTC, rpetrusha approved these changes

2019-04-30 15:43 UTC, rpetrusha commented
Thanks for making the additional changes, @ericmutta. I'll merge your PR now. The changes will appear live on docs.microsoft.com next Monday.

2019-04-30 15:43 UTC, merged

2019-04-30 19:06 UTC, ericmutta commented
@rpetrusha many thanks, it's really fun to be able to contribute and see one's changes go live in a matter of days. Looking forward to doing more!