proposing additions for type annotation
dotnet/docs pull request #12076
Opened 2019-04-28 05:30 UTC by smoothdeveloper

Proposing few examples on how to use whitespace for type annotations.

2019-04-28 05:30 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=12076) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=12076) before we can accept your contribution.<br/><br/>:x: smoothdeveloper [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=12076)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=12076) it.</sub>

2019-04-28 20:27 UTC, cartermp requested changes
Some minor changes, but otherwise this is great. Thanks @smoothdeveloper

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +### type annotation
```suggestion
### Type annotations
```

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +#### Right-pad function argument type annotation with white space
```suggestion
#### Right-pad function argument type annotations
```

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +When defining arguments with type annotation, use white space after the `:` symbol:
```suggestion
When defining arguments with type annotations, use white space after the `:` symbol:
```

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +#### Surround definition type annotations with white space
```suggestion
#### Surround return type annotations with white space
```

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +In a let binding with type annotation, use white space after the `:` symbol:
```suggestion
In a let-bound function or value type annotation (return type in the case of a function), use white space before and after the `:` symbol:
```

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +let expensiveToCompute : int = 0
```suggestion
let expensiveToCompute : int = 0 // Type annotation for let-bound value
```

2019-04-28 20:27 UTC, cartermp commented on docs/fsharp/style-guide/formatting.md
> +let myFun (a: decimal) b c : decimal = a + b + c
```suggestion
let myFun (a: decimal) b c : decimal = a + b + c // Type annotation for the return type of a function
```

2019-05-02 03:43 UTC, cartermp approved these changes

2019-05-02 03:43 UTC, merged

2021-06-10 07:29 UTC, auduchinok commented
I've seen a lot of code with no space before colon in both values and function annotations, like this:
```fsharp
// values:

let x: SomeType = y

let f () =
    let y: AnotherType = g x


// functions:

let f (arg: _): unit =
    ()

let f x: unit =
    ()
```

Perhaps, I've seen more code formatted like this than with space like `let a : int = 1`.

@cartermp @dsyme I think we should explicitly allow this style, since Fantomas uses these rules to enforce arguably less popular code style without any option to keep no-space style. What do you think?

2021-06-11 17:44 UTC, dsyme commented
I personally regard the former style (no space) as standard with the exception of having a whitespace here, partly so `):` doesn't look like a weird sad backward smilely

```fsharp
let f (arg: _) : unit =
    ()
```

We should document this here, yes

2021-06-11 17:56 UTC, dsyme commented
@auduchinok I made a proposed adjustment here: https://github.com/dotnet/docs/pull/24643