WIP Cross validation how to
dotnet/docs pull request #12159
Opened 2019-05-02 18:21 UTC by natke

Cross validation how-to

Re-open #11792, with changes

AB#1463694

2019-05-02 20:03 UTC, JRAlexander requested changes
One clarfication, otherwise LGTM.

2019-05-02 20:03 UTC, JRAlexander commented on docs/machine-learning/how-to-guides/train-machine-learning-model-cross-validation-ml-net.md
> +Load the data in into an [`IDataView`](xref:Microsoft.ML.IDataView).
Is code missing for this?

2019-05-02 20:19 UTC, luisquintanilla commented on docs/machine-learning/how-to-guides/train-machine-learning-model-cross-validation-ml-net.md
> +Load the data in into an [`IDataView`](xref:Microsoft.ML.IDataView).
No. Just an instruction to do so.

2019-05-02 20:20 UTC, luisquintanilla commented on docs/machine-learning/how-to-guides/train-machine-learning-model-cross-validation-ml-net.md
> +# How-To: Learn how to train and evaluate a machine learning model using cross validation in ML.NET
```suggestion
Learn how to train and evaluate a machine learning model using cross validation in ML.NET
```

2019-05-02 20:20 UTC, luisquintanilla commented on docs/machine-learning/how-to-guides/train-machine-learning-model-cross-validation-ml-net.md
> +title: "How-To: Learn how to train and evaluate a machine learning model using cross validation in ML.NET"
```suggestion
title: Learn how to train and evaluate a machine learning model using cross validation in ML.NET
```

2019-05-02 20:21 UTC, luisquintanilla approved these changes
Looks good. Minor suggestions

2019-05-03 18:07 UTC, JRAlexander approved these changes

2019-05-03 18:13 UTC, luisquintanilla approved these changes

2019-05-03 18:13 UTC, luisquintanilla commented on docs/machine-learning/how-to-guides/train-machine-learning-model-cross-validation-ml-net.md
> +Learn how to train and evaluate a machine learning model using cross validation in ML.NET
```suggestion
# Learn how to train and evaluate a machine learning model using cross validation in ML.NET
```

2019-05-03 21:42 UTC, merged