SEOImageUpdates: User Story 1463880, Small PR 3
dotnet/docs pull request #12339
Opened 2019-05-14 05:37 UTC by damabe

## Summary

Make a smaller PR.

Fixes #1463880

2019-05-15 06:23 UTC, mairaw requested changes
Thanks @damabe. A few things to address before merging.

2019-05-15 06:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-obtain-font-metrics.md
>   The following illustration shows the various metrics.
```suggestion
 The following illustration shows the various metrics:
```

2019-05-15 06:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-obtain-font-metrics.md
>   The following illustration shows the output of the example code.
```suggestion
 The following illustration shows the output of the example code:
```

2019-05-15 06:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-obtain-font-metrics.md
> + ![Example code output of Arial font](./media/how-to-obtain-font-metrics/example-output-code-arial-font.png "Example code output of Arial font")
```suggestion
 ![Example code output of Arial font metrics.](./media/how-to-obtain-font-metrics/example-output-code-arial-font.png)  
```

2019-05-15 06:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-obtain-font-metrics.md
> + ![Illustration of various font metrics](./media/how-to-obtain-font-metrics/various-font-metrics.png "Illustration of various font metrics")
```suggestion
 ![Illustration of font metrics: ascent, descent, and line spacing.](./media/how-to-obtain-font-metrics/various-font-metrics.png)  
```

2019-05-15 06:23 UTC, mairaw commented on docs/framework/winforms/advanced/how-to-obtain-font-metrics.md
> + ![Example of converting from design units to pixels](./media/how-to-obtain-font-metrics/convert-font-units-example.png "Example of converting from design units to pixels")
```suggestion
 ![Formula showing the conversion from design units to pixels](./media/how-to-obtain-font-metrics/convert-font-units-example.png)  
```

2019-05-16 02:42 UTC, damabe commented
@maira Feedback incorporated. Updated CATS report:

https://contentqacats.azurewebsites.net/CheckResults/2019051600045/Report/

2019-05-17 20:03 UTC, mairaw approved these changes

2019-05-17 20:06 UTC, merged