SEOImageUpdates: User Story 1463880, Small PR 1
dotnet/docs pull request #12337
Opened 2019-05-14 03:38 UTC by damabe

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-05-14 19:08 UTC, mairaw commented
Do these smaller PRs replace #10947 @damabe?

2019-05-14 19:20 UTC, mairaw requested changes
Thank you @damabe. A few comments before merging this one.

2019-05-14 19:20 UTC, mairaw commented on docs/framework/deployment/reducing-system-restarts.md
> + ![Screenshot that shows the Close Application dialog.](./media/reducing-system-restarts/close-application-dialog.png)
```suggestion
 ![The Close Application dialog listing the programs currently running.](./media/reducing-system-restarts/close-application-dialog.png)  
```

2019-05-14 19:20 UTC, mairaw commented on docs/framework/wcf/feature-details/managing-claims-and-authorization-with-the-identity-model.md
>   Multiple sets of claims may have the same issuing claim set, as illustrated in the following figure.
```suggestion
 Multiple sets of claims may have the same issuing claim set, as illustrated in the following figure:
 
```

2019-05-14 23:22 UTC, damabe commented
These do replace the large PR. I've got one more to create to cover all the updated file. I'll do that one in a bit and @ mention you when I'm done.

2019-05-15 02:40 UTC, damabe commented
@mairaw Feedback incorporated. Updated CATS report:

https://contentqacats.azurewebsites.net/CheckResults/2019051500056/Report/

2019-05-15 04:59 UTC, mairaw commented
Breaking it down helps a lot @damabe. Thanks!

2019-05-15 04:59 UTC, mairaw approved these changes

2019-05-15 04:59 UTC, merged