SEOImageUpdates: User Story 1463880, Small PR 2
dotnet/docs pull request #12338
Opened 2019-05-14 04:58 UTC by damabe

## Summary

Making a smaller PR.

Fixes #1463880

2019-05-14 19:53 UTC, mairaw requested changes
Thanks @damabe. A few changes before we merge this one.

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/how-to-create-a-state-machine-workflow.md
> +     ![Completed state machine workflow from the Getting Started Tutorial](./media/how-to-create-a-state-machine-workflow/getting-started-tutorial-complete-state-machine-workflow.jpg)
```suggestion
     ![Illustration that shows the completed state machine workflow.](./media/how-to-create-a-state-machine-workflow/complete-state-machine-workflow.jpg)  
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/state-machine-workflows.md
> + ![Completed state machine workflow from the Getting Started Tutorial](./media/state-machine-workflows/getting-started-tutorial-complete-state-machine-workflow.jpg)
```suggestion
 ![Illustration that shows the completed state machine workflow.](./media/state-machine-workflows/complete-state-machine-workflow.jpg)  
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/state-machine-workflows.md
> + ![WF4 State Machine Activities](./media/state-machine-workflows/net-framework-platform-update-state-machine-activities.jpg)
```suggestion
 ![Screenshot of the State Machine section of the Toolbox](./media/state-machine-workflows/state-machine-section-toolbox.jpg)  
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/wf-features-in-the-rehosted-workflow-designer.md
> + ![Auto-surround with WriteLine activity](./media/wf-features-in-the-rehosted-workflow-designer/auto-surround-write-line-activity.png)
```suggestion
 ![A WriteLine activity in the Body of a NoPersistScope activity.](./media/wf-features-in-the-rehosted-workflow-designer/auto-surround-write-line-activity.png)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/wf-features-in-the-rehosted-workflow-designer.md
> + ![Auto-surround with Sequence activity](./media/wf-features-in-the-rehosted-workflow-designer/auto-surround-sequence-activity.png)
```suggestion
 ![An automatically created Sequence in the Body of a NoPersistScope.](./media/wf-features-in-the-rehosted-workflow-designer/auto-surround-sequence-activity.png)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/wf-features-in-the-rehosted-workflow-designer.md
> + ![Use the pan button to move the visible portion of the workflow.](./media/wf-features-in-the-rehosted-workflow-designer/pan-button-visible-workflow.png)
```suggestion
 ![The pan button highlighted in the workflow designer.](./media/wf-features-in-the-rehosted-workflow-designer/pan-button-workflow-designer.png)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/wf-features-in-the-rehosted-workflow-designer.md
> + ![Outline View with a sequential workflow](./media/wf-features-in-the-rehosted-workflow-designer/outline-view-in-workflow-designer.jpg)
```suggestion
 ![Screenshot of outline view with a sequential workflow in Visual Studio](./media/wf-features-in-the-rehosted-workflow-designer/outline-view-in-workflow-designer.jpg)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/wf-features-in-the-rehosted-workflow-designer.md
> + ![Completed state machine workflow from the Getting Started Tutorial](./media/wf-features-in-the-rehosted-workflow-designer/getting-started-tutorial-complete-state-machine-workflow.jpg)
```suggestion
 ![Illustration that shows the completed state machine workflow.](./media/wf-features-in-the-rehosted-workflow-designer/complete-state-machine-workflow.jpg)  
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/whats-new-in-wf-in-dotnet.md
> +![Auto-surround with WriteLine activity](./media/whats-new-in-wf-in-dotnet/auto-surround-write-line-activity.png)
```suggestion
![A WriteLine activity in the Body of a NoPersistScope activity.](./media/whats-new-in-wf-in-dotnet/auto-surround-write-line-activity.png)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/whats-new-in-wf-in-dotnet.md
> +![Auto-surround with Sequence activity](./media/whats-new-in-wf-in-dotnet/auto-surround-sequence-activity.png)
```suggestion
![An automatically created Sequence in the Body of a NoPersistScope.](./media/whats-new-in-wf-in-dotnet/auto-surround-sequence-activity.png)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/whats-new-in-wf-in-dotnet.md
> +![Use the pan button to move the visible portion of the workflow.](./media/whats-new-in-wf-in-dotnet/pan-button-visible-workflow.png)
```suggestion
![The pan button highlighted in the workflow designer.](./media/whats-new-in-wf-in-dotnet/pan-button-workflow-designer.png)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/whats-new-in-wf-in-dotnet.md
> +![Outline view with a sequential workflow.](./media/whats-new-in-wf-in-dotnet/outline-view-in-workflow-designer.jpg)
```suggestion
![Screenshot of outline view with a sequential workflow in Visual Studio.](./media/whats-new-in-wf-in-dotnet/outline-view-in-workflow-designer.jpg)
```

2019-05-14 19:53 UTC, mairaw commented on docs/framework/windows-workflow-foundation/whats-new-in-wf-in-dotnet.md
> +![Completed state machine workflow from the Getting Started Tutorial](./media/whats-new-in-wf-in-dotnet/getting-started-tutorial-complete-state-machine-workflow.jpg)
```suggestion
![Illustration that shows the completed state machine workflow.](./media/whats-new-in-wf-in-dotnet/complete-state-machine-workflow.jpg)
```

2019-05-15 03:47 UTC, damabe commented
@mairaw Feedback incorporated. Updated CATS report:

https://contentqacats.azurewebsites.net/CheckResults/2019051500065/Report/

2019-05-15 05:00 UTC, mairaw approved these changes

2019-05-15 05:01 UTC, merged