Add a note about the point-in-time concern with VS and the CLI
dotnet/docs pull request #12503
Opened 2019-05-23 15:35 UTC by BillWagner

The .NET SDK CLI does not yet include the rename from NullableContextOptions to Nullable.

See https://github.com/dotnet/docs/pull/12497#issuecomment-495242895

/cc @rainersigwald

2019-05-23 15:40 UTC, rainersigwald approved these changes
LGTM but I've been talking offline with @jaredpar about this so he should weigh in.

2019-05-23 15:46 UTC, rpetrusha approved these changes
LGTM, @BillWagner. Left one comment for you to consider that applies to all three of your changes. You can merge when you're ready.

2019-05-23 15:46 UTC, rpetrusha commented on docs/csharp/nullable-references.md
> +> [!NOTE]
I think I'd label this Important rather than Note for greater visibility.

2019-05-23 21:42 UTC, Thraka approved these changes
LGTM too 😄

2019-05-23 21:43 UTC, Thraka requested changes
~Actually can we hold off for a second? I want to test something.~

2019-05-23 22:01 UTC, Thraka approved these changes

2019-05-24 01:17 UTC, drewnoakes approved these changes

2019-05-24 01:19 UTC, merged