Make code snippet colorful
dotnet/docs pull request #12712
Opened 2019-06-06 22:25 UTC by Youssef1313

Specifying the code snippet language (vb) to make reserved words blue and comments green

( Compare the two snippets in the picture )
![image](https://user-images.githubusercontent.com/31348972/59070347-b72d3a80-88ba-11e9-990d-e120d62f8a7a.png)

2019-06-06 22:44 UTC, rpetrusha approved these changes
This looks good, @Youssef1313. Thank you for making the additional changes to improve the formatting of the entire article. I'll merge your PR as soon as our internal build completes successfully.

2019-06-07 00:08 UTC, mairaw requested changes
Changes look great @Youssef1313 but there should be an empty line between the text and the code blocks. I left a few suggestions to fix that throughout the text. Thanks!

2019-06-07 00:08 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/how-to-infer-property-names-and-types-in-anonymous-type-declarations.md
> +  ```vb
```suggestion

  ```vb
```

2019-06-07 00:08 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/how-to-infer-property-names-and-types-in-anonymous-type-declarations.md
> +    ```vb
```suggestion

    ```vb
```

2019-06-07 00:08 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/how-to-infer-property-names-and-types-in-anonymous-type-declarations.md
> +    ```vb
```suggestion

    ```vb
```

2019-06-07 00:08 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/how-to-infer-property-names-and-types-in-anonymous-type-declarations.md
> +     ```vb
```suggestion

     ```vb
```

2019-06-07 00:08 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/how-to-infer-property-names-and-types-in-anonymous-type-declarations.md
> +     ```vb
```suggestion

     ```vb
```

2019-06-07 00:08 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/objects-and-classes/how-to-infer-property-names-and-types-in-anonymous-type-declarations.md
> +     ```vb
```suggestion

     ```vb
```

2019-06-08 12:12 UTC, Youssef1313 commented
> 
> 
> Changes look great @Youssef1313 but there should be an empty line between the text and the code blocks. I left a few suggestions to fix that throughout the text. Thanks!

@mairaw, Thanks for the suggesstions. I've committed them.

2019-06-27 15:58 UTC, KathleenDollard reviewed
Looks good. Thank you!

2019-07-03 08:26 UTC, mairaw approved these changes
Thanks @Youssef1313 for applying the suggested changes. Merging now.

2019-07-03 08:26 UTC, merged