Fixing links to wiki articles
dotnet/docs pull request #12725
Opened 2019-06-07 15:53 UTC by ardalis

## Summary

Fixing links to wiki articles

2019-06-07 16:21 UTC, nishanil requested changes

2019-06-07 16:21 UTC, nishanil commented on docs/standard/modernize-with-azure-and-containers/walkthroughs-technical-get-started-overview.md
>  ## Walkthrough 5: Deploy your Windows Containers-based apps to Kubernetes in Azure Container Service
The link is broken here.

2019-06-07 16:21 UTC, nishanil commented on docs/standard/modernize-with-azure-and-containers/walkthroughs-technical-get-started-overview.md
> +## Walkthrough 6: Deploy your Windows Containers-based apps to Azure App Service for Containers
Add Scenario with diagram? Every other walkthrough has it. This is our most recommended path for Windows Containers and we should have that explicitly called out :)

2019-06-07 16:21 UTC, nishanil commented on docs/standard/modernize-with-azure-and-containers/walkthroughs-technical-get-started-overview.md
>  ## Walkthrough 5: Deploy your Windows Containers-based apps to Kubernetes in Azure Container Service
In Walkthrough 5. I couldn't comment there..

2019-06-07 17:20 UTC, ardalis commented
Hopefully all set now @nishanil

2019-06-07 19:51 UTC, rpetrusha requested changes
This looks good, @ardalis. I've made two minor suggestions about formatting and capitalization.

2019-06-07 19:51 UTC, rpetrusha commented on docs/standard/modernize-with-azure-and-containers/conclusions.md
> +- For production environments, you should use an orchestrator (like Kubernetes) to host scalable Containers­­–based applications.
```suggestion
- For production environments, you should use an orchestrator (like Kubernetes) to host scalable containers­­–based applications.
```

2019-06-07 19:51 UTC, rpetrusha commented on docs/standard/modernize-with-azure-and-containers/index.md
>  During this initial modernization, you can also add assets from the cloud, such as monitoring with tools like [Azure Application Insights](https://docs.microsoft.com/azure/application-insights/app-in
```suggestion

During this initial modernization, you can also add assets from the cloud, such as monitoring with tools like [Azure Application Insights](https://docs.microsoft.com/azure/application-insights/app-insights-overview); CI/CD pipelines for your app lifecycles with [Azure DevOps Services](https://azure.microsoft.com/services/devops/); and many more data resource services that are available in Azure. For instance, you can modify a monolithic web app that was originally developed by using traditional [ASP.NET Web Forms](https://www.asp.net/web-forms) or [ASP.NET MVC](https://www.asp.net/mvc), but now you deploy it by using Windows Containers. When you use Windows Containers, you should also migrate your data to a database in [Azure SQL Database Managed Instance](https://docs.microsoft.com/azure/sql-database/), all without changing the core architecture of your application.
```

2019-06-07 20:03 UTC, ardalis commented
:shipit:

2019-06-07 22:46 UTC, rpetrusha commented
Thanks, @ardalis. I'll merge your PR now.

2019-06-07 22:46 UTC, rpetrusha approved these changes

2019-06-07 22:47 UTC, rpetrusha commented
Sorry, @ardalis., @nishanil still has to approve.

2019-06-08 13:38 UTC, nishanil approved these changes
Looks good. Thanks, @ardalis !!

2019-06-10 02:01 UTC, merged