WIP - ONNX Object Detection Tutorial
dotnet/docs pull request #12755
Opened 2019-06-10 15:35 UTC by luisquintanilla

Object Detection Tutorial using ONNX

2019-07-16 20:27 UTC, JRAlexander requested changes
Looks good. Just a few minor changes.

2019-07-17 19:13 UTC, JRAlexander approved these changes

2019-07-18 17:18 UTC, natke reviewed
Looks good! I've done an initial review, by just reading. I want to run through it again, and actually do the tutorial, and will probably add more comments then.

Oh, have we run acrolinx over this?

2019-07-18 17:18 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +The expected output generated by the pre-trained ONNX model is a tensor of shape `125 x 13 x 13` that is returned as a one-dimensional `float[]` of 21125 elements. In order to extract the predictions
Should we define what a tensor is?

2019-07-18 17:18 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +![](./media/object-detection-onnx/onnx-frameworks.png)
A diagram with the network inputs and outputs would be very useful here. If you draft it, we can ask Deborah in art to make it professional

2019-07-18 17:18 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +The expected output generated by the pre-trained ONNX model is a tensor of shape `125 x 13 x 13` that is returned as a one-dimensional `float[]` of 21125 elements. In order to extract the predictions
A diagram showing the mapping would be useful here

2019-07-18 17:18 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +> * Understand the problem
I think we could expand this list to make it a little less generic. They learn a lot in this tutorial!

2019-07-18 17:18 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +## Create console application
Is this the best title for this section? Can we make it more specific?

2019-07-18 20:48 UTC, luisquintanilla commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +    - `PredictedLabel` contains the dimensions, objectness score and class probabilities for each of the bounding boxes detected in an image.
That's what it's referred to as in the paper.

https://arxiv.org/pdf/1612.08242.pdf

2019-07-30 18:38 UTC, natke reviewed
Overall, looking good! I have a few more suggestions.

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +Learn how to use a pre-trained ONNX model in ML.NET to detect objects. The pre-trained model was trained to find and classify objects in an image.
Suggest simplifying this to: 
```
Learn how to use a pre-trained ONNX model in ML.NET to detect objects in images
```

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +Object detection is a computer vision problem. While closely related to image classification, object detection performs image classification at a more granular scale. When an image is processed, ther
Suggest simplifying to:
`Object detection both locates _and_ categorizes entities within images. Use object detection when images contain multiple objects of different types.`

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +## Select the appropriate machine learning task
I'm still of the opinion that this title doesn't describe the content of this section

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +There are different types of neural networks, each more suitable than the other for certain tasks. The most common types of neural networks are Multi-Layered Perceptron (MLP), Convolutional Neural Ne
```suggestion
There are different types of neural networks, the most common being Multi-Layered Perceptron (MLP), Convolutional Neural Network (CNN) and Recurrent Neural Network (RNN). The most basic is the MLP, which maps a set of inputs to a set of outputs. This neural network is good when the data does not have a spatial or time component. The CNN makes use of convolutional layers to process spatial information contained in the data. A good use case for CNNs is image processing to detect the presence of a feature in a region of an image (for example, is there a nose in the center of an image?). Finally, RNNs allow for the persistence of state or memory to be used as input. RNNs are used for time-series analysis, where the sequential ordering and context of events is important. 
```

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +![](./media/object-detection-onnx/netron-model-map.png)
The netron part of this image is too small. I can help rework this image

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +The input expected by the YOLO model is an image that is `416px x 416px`, where each pixel contains 3 data elements corresponding to the RGB values of the respective pixel. The model takes this input
```suggestion
The YOLO model takes an image `416px x 416px x 3 (RGB)`. The model takes this input and passes it through the different layers to produce an output. The output divides the input image into a `13 x 13` grid, with each box in the grid consisting of `125` values. 
```

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +![](./media/object-detection-onnx/model-output-description.png)
Image looks good! Would the yellow bounding box be where the centroid of the object is though?

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +The model segments an image into a `13 x 13` grid, where each grid cell is `32px x 32px`. Each grid cell contains 125 elements within it that correspond to 5 areas in an image which are believed to c
```suggestion
The model segments an image into a `13 x 13` grid, where each grid cell is `32px x 32px`. Each grid cell contains 5 potential object bounding boxes. A bounding box has  25 elements:
```

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +    `ImageNetPrediction` is the prediction data class and has the following `float[]` field:
I suggest moving the grid image into this section, to break up the code a bit, and also to illustrate how the ImagePrediction data is encoded.

We could talk about the expected dimensions of the ImagePrediction float[] array too

2019-07-30 18:38 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +Object localization is a core component of object detection. As such, much of the data output by the model contains coordinates and dimensions of the bounding boxes of objects within the image. Creat
```suggestion
The data output by the model contains coordinates and dimensions of the bounding boxes of objects within the image. Create a base class for dimensions.
```

2019-07-30 21:53 UTC, natke reviewed
One small comment, which was actually my bad from the last review: box --> cell

2019-07-30 21:53 UTC, natke commented on docs/machine-learning/tutorials/object-detection-onnx.md
> +The YOLO model takes an image `3(RGB) x 416px x 416px`. The model takes this input and passes it through the different layers to produce an output. The output divides the input image into a `13 x 13`
```suggestion
The YOLO model takes an image `3(RGB) x 416px x 416px`. The model takes this input and passes it through the different layers to produce an output. The output divides the input image into a `13 x 13` grid, with each cell in the grid consisting of `125` values. 
```

2019-07-30 21:59 UTC, natke approved these changes

2019-07-30 22:01 UTC, merged