Added explanation for the --s <SETTINGS> flag
dotnet/docs pull request #12820
Opened 2019-06-13 14:42 UTC by roel4ez

## Summary

Added an explanation for the `--s <SETTINGS>` flag, and clarified with a link to the usage of such a file.

Fixes #11589 (if available)

2019-06-24 15:14 UTC, Thraka requested changes
Thanks a bunch for doing this! It helps a lot. 

Some minor suggestions for you to approve. I added a period at the end of the sentence-links and I also code-blocked the file reference in the link so it matches the style of the normal text to the left of it.

Thanks again!

2019-06-24 15:14 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runset
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-24 15:14 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runset
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-24 15:14 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a .runsettings file](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runset
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-24 18:41 UTC, roel4ez commented
Approved the edits, thanks!

2019-06-25 14:36 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-run
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-25 14:37 UTC, Thraka requested changes
@roel4ez I totally missed this the first visual pass, sorry. The links to visual studio have a locale in them, the en-us. I'll edit those and I think we can link directly to the file instead of the published link. 

I *think* this is how it should be formatted. Once you commit these it will kick off a build and we can test. Sorry about that.

2019-06-25 14:37 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-run
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-25 14:37 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-run
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-25 14:37 UTC, Thraka commented on docs/core/tools/dotnet-test.md
> +The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](https://docs.microsoft.com/en-us/visualstudio/test/configure-unit-tests-by-using-a-dot-run
```suggestion
The `.runsettings` file to use for running the tests. [Configure unit tests by using a `.runsettings` file.](/visualstudio/test/configure-unit-tests-by-using-a-dot-runsettings-file?view=vs-2019)
```

2019-06-26 10:54 UTC, roel4ez commented
ok thanks for noticing. The build says it's ok!

2019-06-26 15:14 UTC, Thraka commented
Awesome! Thanks again 👍

2019-06-26 15:14 UTC, Thraka approved these changes

2019-06-26 15:15 UTC, merged