WIP - Added overview of C# type-testing and assignment operators
dotnet/docs pull request #12828
Opened 2019-06-14 06:11 UTC by pkulikov

Fixes #10739
Supported by dotnet/samples#990

2019-06-14 06:16 UTC, pkulikov commented
@BillWagner maybe, this PR would be easier to review, if that's done in stages. Should we try?

What is now ready for review:
- *Order* and *titles* of the sections
- Cast and assignment operator sections (I'm fine if you merge the samples PR to have the review site version with code examples in)

2019-06-14 14:47 UTC, BillWagner commented
@pkulikov 

I gave this a read today, along with dotnet/samples#990

I like the direction so far.  

If you want me to merge the samples that exist now, just remove the work-in-progress note, and I'll approve it and merge it.

I'll watch for further updates here.

2019-06-14 14:57 UTC, pkulikov commented
@BillWagner let's merge the samples, I've removed the WIP mark

2019-06-18 06:11 UTC, pkulikov commented
@BillWagner could you please take a look at the latest commit that adds the `is` operator section. Is that a fine separation of content? My thoughts on it are below.

As far as I understand, a number of patterns is supported by both `switch` and `is`. Thus, to reduce duplication, those patterns deserve their own article. Now there is some duplication in the `switch` and `is` articles. I didn't want to disturb the pattern content, so it should be simpler to consolidate it later. That's why, in a new article I only briefly mention the type pattern and give an example. And then link the "main" section on patterns.

As for TOC, can we move the "is" entry out of the "Operator keywords" section? What about the new "Pattern matching" section (which can be under "Keywords" node or on the same level with it)?

2019-06-18 14:21 UTC, BillWagner commented
@pkulikov I like the breakdown so far.

It's in keeping with the goal that the **Language Reference** is a reference that explains the syntax, although not with the depth of the specification. Pattern Matching will continue to get more coverage in tutorials and other conceptual articles. That will be a great location for a single explanation of patterns in both `is`, `switch` and any other future syntax elements.

> As for TOC, can we move the "is" entry out of the "Operator keywords" section? What about the new "Pattern matching" section (which can be under "Keywords" node or on the same level with it)?

Good questions. Yes, we can move the `is` entry out of the "Operator keywords" section.  Ultimately, I think a pattern matching section is the best location. In the short term, the "type testing" is a good solution.

2019-06-19 06:23 UTC, pkulikov commented
@BillWagner because of the `as` and `()` operators, I would like to rename the overview into *Type-testing, conversion, and assignment operators*. It appears to be long. I suggest to bring the `=` operator back into its own page.

So, to have a new *Type-testing and conversion operators* article and existing *= operator* article.

What do you think? Do I miss anything that suggest including the `=` operator into the group of type-testing and conversion operators? (I assume implicit conversion on assignment is a weak link.)

2019-06-19 13:45 UTC, BillWagner commented
@pkulikov 

> ...
> What do you think? Do I miss anything that suggest including the = operator into the group of type-testing and conversion operators? (I assume implicit conversion on assignment is a weak link.)

I like your analysis, and I agree.  

In truth, I often make these kinds of changes to outlines and the TOC as I'm writing. Weaknesses in a planned presentation become more clear. We find a better organization of the material.

2019-06-20 06:14 UTC, pkulikov commented
@BillWagner thanks for the interim checks and reviews!

This is ready for the final review. Additional snippets are in dotnet/samples#1005

I've not included the `!`/`?` operators in this edition, as I think that would be for the C# 8 related set of changes. Something for later.

2019-06-20 14:36 UTC, BillWagner commented
closing and reopening to start a new build.

2019-06-20 14:49 UTC, BillWagner commented
Closing and reopening again for a fresh build. Several snippets not found in the last build.

2019-06-20 15:02 UTC, BillWagner requested changes
Thanks for all the work @pkulikov 

I'll keep working to track down why the build is failing.  I did have one other nit to fix.

Overall, this is great work again. Thank you so much!

2019-06-20 15:02 UTC, BillWagner commented on docs/csharp/language-reference/operators/assignment-operator.md
> +[!code-csharp-interactive[simple assignment](~/samples/csharp/language-reference/operators/AssignmentOperator.cs#Simple)]
This file isn't found. I'm not seeing why after dotnet/samples#1005 was merged.

2019-06-20 15:02 UTC, BillWagner commented on docs/csharp/language-reference/operators/type-testing-and-conversion-operators.md
> +[!code-csharp[is with reference conversion](~/samples/csharp/language-reference/operators/TypeTestingAndConversionOperators.cs#IsWithReferenceConversion)]
Hmm. These are also all generating warnings. Not sure why either.

2019-06-20 15:05 UTC, pkulikov commented on docs/csharp/language-reference/operators/assignment-operator.md
> +In the case of the ref assignment operator, the type of its both operands must be the same.
Thanks!

2019-06-20 15:18 UTC, pkulikov commented
@BillWagner the build looks green now

2019-06-20 15:22 UTC, BillWagner commented
Thanks @pkulikov 

I've approved the changes, and I'll :shipit: now.

2019-06-20 15:22 UTC, BillWagner approved these changes

2019-06-20 15:22 UTC, merged