Styling syntax as a code block
dotnet/docs pull request #12822
Opened 2019-06-13 18:03 UTC by Youssef1313

2019-06-13 18:31 UTC, mairaw requested changes
I like this change @Youssef1313! I just left a suggestion for an improvement on the formatting due to the change from text to code block. Please take a look!

2019-06-13 18:31 UTC, mairaw commented on docs/visual-basic/programming-guide/language-features/procedures/operator-procedures.md
> + Public Shared [Widening | Narrowing] Operator *operatorsymbol* ( *operand1* [,  *operand2* ]) As *datatype*
The \* here were used to make the names italic. By using a code block, we should probably remove those:

```suggestion
 Public Shared [Widening | Narrowing] Operator operatorsymbol ( operand1 [,  operand2 ]) As datatype  
```

This is how the change renders right now:
![image](https://user-images.githubusercontent.com/12971179/59458101-9f7c1780-8dce-11e9-8c14-7270e19f1e7f.png)

2019-06-14 04:40 UTC, Youssef1313 commented
> 
> 
> I like this change @Youssef1313! I just left a suggestion for an improvement on the formatting due to the change from text to code block. Please take a look!

@mairaw , Yes, it seems a lot better. I've committed your change.

2019-06-14 21:56 UTC, mairaw approved these changes
Looks great! Thanks @Youssef1313!

2019-06-14 21:56 UTC, merged