Revisions to lambda expressions topic.
dotnet/docs pull request #1285
Opened 2016-11-22 23:21 UTC by rpetrusha

# Revisions to lambda expressions topic

## Summary

Extensively revised with new examples and a section on tuples and lambda expressions.

## Suggested Reviewers
@BillWagner @stevehoag @mairaw

2016-11-23 03:21 UTC, mairaw commented
There are some build errors. It would be good to fix those first, otherwise we can't even see it on staging.

2016-11-23 19:12 UTC, rpetrusha commented
@mairaw I think I've fixed all the build errors.  A new build should run shortly.

2016-11-23 21:26 UTC, stevehoag reviewed
Looks good - add a few minor comments.

2016-11-23 21:26 UTC, stevehoag commented on docs/csharp/lambda-expressions.md
> -ms.date: 06/20/2016
Update the date; also needs a ms.author.

2016-11-23 21:26 UTC, stevehoag commented on docs/csharp/lambda-expressions.md
> +Starting with C# 7.0, the C# language provides built-in support for tuples. You can provide a tuple as an argument to a lambda expression, and your lambda expression can also return a tuple. In some
Link to the Tuples topic?

2016-11-23 21:26 UTC, stevehoag commented on docs/csharp/lambda-expressions.md
> +You can also supply a lambda expression when the argument type is an @System.Linq.Expressions.Expression%601, for example in the standard query operators that are defined in the @System.Linq.Queryabl
The last link (@System.Linq.Enumerable.Count) isn't resolving.

2016-11-23 21:26 UTC, stevehoag commented on docs/csharp/lambda-expressions.md
> +[LINQ (Language-Integrated Query)](../standard/using-linq.md)
These three links are all showing up on a single line - was that intentional?

2016-11-23 21:26 UTC, stevehoag commented on docs/csharp/lambda-expressions.md
> +## Featured Book Chapter ##
Should we still be linking to this? The book was published in 2007.

2016-11-25 19:31 UTC, rpetrusha commented on docs/csharp/lambda-expressions.md
> -ms.date: 06/20/2016
@stevehoag Thanks. I completely forgot to copy the header from the original topic.

2016-11-28 19:37 UTC, mairaw commented on docs/csharp/lambda-expressions.md
> +The general rules for type inteference for lambdas are:
typo: inteference

2016-11-28 19:37 UTC, mairaw commented on docs/csharp/lambda-expressions.md
> +Lambdas can refer to *outer variables* (see [Anonymous methods](programming-guide/statements-expressions-operators/anonymous-methods.md)) that are in scope in the method that defines the lambda funct
must be definitely -> must be (I think the must is enough)

2016-11-28 19:37 UTC, mairaw commented on docs/csharp/lambda-expressions.md
> +When writing lambdas, you often do not have to specify a type for the input parameters because the compiler can infer the type based on the lambda body, the parameter’s delegate type, and other facto
nit: missing comma after So

2016-11-29 17:25 UTC, BillWagner requested changes
Ron, I like the way you've explained all the concepts here.

I had a few locations where the language is technically incorrect based on the terms used in the spec.  once those are handled, this looks great.

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +-keywords: .NET, .NET Core, lambda epxressions, lambdas, delegates
typo: epxressions

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +Lambda expressions are delegates. The specific delegate type of a lambda expressions depends on its parameters and return value. Lambda expressions that don't return a value correspond to a specific
Lambda expressions are delegates, except when they are expression trees. 

Maybe "Lambda expressions are code that can be represented either as a delegate, or an expression tree that would compile to a delegate".  (I'm not sure I like that wording, improve at will.)

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +Note in the previous example that the body of an expression lambda can consist of a method call. However, if you are creating expression trees that are evaluated outside of the .NET Framework, such a
We should add some weasel words here. Entity Framework does translate some known methods (especially on the string class. The guidance is correct in the general case.

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +Statement lambdas, like anonymous methods, cannot be used to create expression trees.
I'd recommend deleting "like anonymous methods".  The C# spec defines lambda expressions as a syntax for anonymous methods, so in that sense all lambda expressions are anonymous methods.

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +Many standard query operators have an input parameter whose type is one of the @System.Func%601 family of generic delegates. These delegates use type parameters to define the number and type of input
I would start this by saying "LINQ to Objects, among other implementations" have an input parameter..

That way this is distinguished from the IQueryable discussion later.

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +When writing lambdas, you often do not have to specify a type for the input parameters because the compiler can infer the type based on the lambda body, the parameter’s delegate type, and other facto
I'd just remove "So".

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +When writing lambdas, you often do not have to specify a type for the input parameters because the compiler can infer the type based on the lambda body, the parameter’s delegate type, and other facto
I think you should delete "delegate" in the phrase "the parameter's delegate type". Or am I misunderstanding this sentence?

2016-11-29 17:25 UTC, BillWagner commented on docs/csharp/lambda-expressions.md
> +Lambdas can refer to *outer variables* (see [Anonymous methods](programming-guide/statements-expressions-operators/anonymous-methods.md)) that are in scope in the method that defines the lambda funct
No, this should stay "definitely assigned". That's the phrase the spec always uses for the analysis of assignment to a variable before it is used.

2016-11-29 21:37 UTC, rpetrusha commented on docs/csharp/lambda-expressions.md
> +The general rules for type inteference for lambdas are:
@mairaw And I didn't even spell the wrong word (interference) correctly. Fixed.

2016-11-29 22:01 UTC, rpetrusha commented
@BillWagner I've addressed all of your comments and will update the topic.

2016-11-29 22:47 UTC, mairaw commented on docs/csharp/lambda-expressions.md
> +Lambdas can refer to *outer variables* (see [Anonymous methods](programming-guide/statements-expressions-operators/anonymous-methods.md)) that are in scope in the method that defines the lambda funct
Good to know @BillWagner 😄

2016-11-29 22:50 UTC, BillWagner approved these changes

2016-11-29 22:51 UTC, BillWagner commented
@rpetrusha LGTM.  :shipit:

2016-11-29 23:43 UTC, merged