Update custom .NET Core host tutorial for hosting with hostfxr
dotnet/docs pull request #12872
Opened 2019-06-17 22:34 UTC by elinor-fung

## Summary

Update custom .NET Core host tutorial for hosting with hostfxr

See dotnet/samples#995 for snippet tags.

2019-06-17 22:56 UTC, rpetrusha commented
Closing and reopening to begin new build.

2019-06-17 23:39 UTC, elinor-fung commented
Hm, I must be missing / misunderstanding something with how to use the snippet tags and code blocks. The ones I tried to add are blank in https://review.docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting?branch=pr-en-us-12872

2019-06-17 23:46 UTC, elinor-fung commented
Actually, from the logs, it looks like the build was still using the samples repo at commit 8eda260763f8f7441bfcdff89f3daf1f810f5f33 which is from before the change for adding the snippet tags got merged?

2019-06-17 23:51 UTC, rpetrusha commented
I can't see anything wrong, @elinor-fung. The previous build (before I closed and reopened this PR) reported no warnings, although it should have. But I'll close and reopen once again, and we can see if that accomplishes anything.

2019-06-18 00:26 UTC, rpetrusha commented
The code is still not included in the build, but there are no build warnings. @mairaw, I may well be missing something completely obvious, but could you take a look, please? The samples repo contains the code, and the code references and snippet tags are correct, AFAIK.

2019-06-18 16:56 UTC, rpetrusha commented
Closing and reopening again...

2019-06-18 17:52 UTC, elinor-fung commented
Thanks, @rpetrusha. It seems like it picked up the changes from the samples repo this time.

2019-06-18 18:09 UTC, rpetrusha commented
Yes, it finally did, @elinor-fung. I have no idea of what the problem was earlier. I'll review your PR shortly.

2019-06-18 18:18 UTC, rpetrusha requested changes
This looks really good, @elinor-fung. I've just suggested one very minor change and this will be ready to merge.

2019-06-18 18:18 UTC, rpetrusha commented on docs/core/tutorials/netcore-hosting.md
> +The `nethost` library provides the `get_hostfxr_path` function for locating the `hostfxr` library. The `hostfxr` library exposes functions for hosting the .NET Core runtime. The full list can be foun
```suggestion
The `nethost` library provides the `get_hostfxr_path` function for locating the `hostfxr` library. The `hostfxr` library exposes functions for hosting the .NET Core runtime. The full list of functions can be found in [`hostfxr.h`](https://github.com/dotnet/core-setup/blob/master/src/corehost/cli/hostfxr.h) and the [native hosting design document](https://github.com/dotnet/core-setup/blob/master/Documentation/design-docs/native-hosting.md). The sample and this tutorial use the following:
```

2019-06-18 18:18 UTC, elinor-fung commented
cc @sdmaclea @vitek-karas @lpereira

2019-06-18 19:34 UTC, sdmaclea reviewed
LGTM.

For the sample code itself, I would consider renaming the `load_and_get` variable name to be more verbose. When I first saw it wasn't immediately clear what it was doing.

2019-06-19 16:28 UTC, rpetrusha approved these changes

2019-06-19 16:28 UTC, rpetrusha commented
Thanks, @elinor-fung. I'll merge your PR now.

2019-06-19 16:28 UTC, merged