Cloudnative ch1
dotnet/docs pull request #12885
Opened 2019-06-18 14:42 UTC by ardalis

## Summary

- Added architecture folder
- Added architecture/cloud-native folder
- Added index.md placeholder in /architecture
- Added all book figures in /architecture/cloud-native/images
- Added full toc.yml in /architecture/cloud-native
- Added chapter 1 .md files

Additional chapters will come in separate PRs.

2019-06-18 14:43 UTC, ardalis commented
Per discussion with @mairaw

2019-06-19 06:37 UTC, mairaw requested changes
Thanks @ardalis. Left a few comments based on Acrolinx suggestions and SEO guidance.

Remember your Oxford commas 😉

2019-06-19 06:46 UTC, mairaw commented
Also, not sure if you've used the suggestions feature before, but you can apply my suggestions in bulk via the Files changed tab.

2019-06-19 06:46 UTC, mairaw commented on docs/architecture/cloud-native/index.md
> +ms.author: wiwagn
```suggestion
```

2019-06-19 14:47 UTC, ardalis commented
> Thanks @ardalis. Left a few comments based on Acrolinx suggestions and SEO guidance.
> 
> Remember your Oxford commas 😉

My co-author wrote this chapter. My review caught a bunch of Oxford comma omissions already :)

2019-06-19 14:57 UTC, ardalis commented on docs/architecture/cloud-native/azure-cloud-native-development-stack.md
> +Even further clouding operating system concerns is the explosive growth of containers. Containers allow applications to run independently of the operating system. "If you take a look at the way that
@robvet

2019-06-19 14:58 UTC, ardalis commented on docs/architecture/index.md
> +---
should I delete it from my branch, then?

2019-06-19 15:15 UTC, mairaw commented on docs/architecture/index.md
> +---
Yes @ardalis

2019-06-19 18:19 UTC, ardalis commented
Can we merge this one ASAP (remember it's not going to a production branch) so I can make the ch2 PR against the updated branch?

2019-06-19 19:38 UTC, ardalis commented
@mairaw can we merge?

2019-06-20 21:45 UTC, mairaw approved these changes
There are just a few comments still left. Think about those before we go live with this e-book.

2019-06-20 22:20 UTC, merged