Cloud Native Chapter 5
dotnet/docs pull request #12932
Opened 2019-06-20 21:34 UTC by ardalis

## Summary

Chapter 5 files. TOC and images are in ch1 PR.

2019-06-20 21:42 UTC, mairaw commented on docs/architecture/cloud-native/data-patterns.md
> +-   *Key/Value Store* (redis, riak, memcached) � Data is stored in simple key-value pairs with system operations performed against a unique access key that is mapped to a value of user data
can you fix these characters @ardalis?

2019-06-22 00:38 UTC, mairaw commented
There's still some left apparently

2019-06-23 02:48 UTC, ardalis commented
looks good now

2019-06-23 23:16 UTC, mairaw commented
Ok, thanks @ardalis. @rpetrusha volunteered to review this chapter.

2019-06-24 16:39 UTC, rpetrusha requested changes
I've made some editorial and formatting corrections for you to review, @ardalis. In addition, the Cosmos DB and Azure Storage Services sections in the data storage article need to be completed.

2019-06-24 17:29 UTC, ardalis commented
@robvet do you want to complete Cosmos and Azure Storage Services in this PR or as a follow-on?

2019-06-24 17:30 UTC, robvet commented
It’s been done. I’m updating that md right now.


Thanks!

Rob Vettor | Principal Cloud System Architect
                      | ASD IP Architect
                      | Developer Advisory Services for Azure

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image003.jpg@01D52A88.9FF8CFE0]  www.thinkingincloudnative.com<http://www.thinkingincloudnative.com/>

From: Steve Smith <notifications@github.com>
Sent: Monday, June 24, 2019 12:30 PM
To: dotnet/docs <docs@noreply.github.com>
Cc: Robert Vettor <robvet@microsoft.com>; Mention <mention@noreply.github.com>
Subject: Re: [dotnet/docs] Cloud Native Chapter 5 (#12932)


@robvet<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobvet&data=02%7C01%7Crobvet%40microsoft.com%7C5356cfef92c146745f3608d6f8c983f3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636969941726112793&sdata=ubWf6o6dnAucrLn48BQVebKErc1eAYOvd1ZZQHZzU3g%3D&reserved=0> do you want to complete Cosmos and Azure Storage Services in this PR or as a follow-on?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fpull%2F12932%3Femail_source%3Dnotifications%26email_token%3DABFIQYBESIAHOKQQWYMBUK3P4D77VA5CNFSM4HZ7MCR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYNUUOY%23issuecomment-505104955&data=02%7C01%7Crobvet%40microsoft.com%7C5356cfef92c146745f3608d6f8c983f3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636969941726122791&sdata=rMa8YIP5HtPb%2BtFTeiMYBKql7CzE29uJl7KHOJGX90s%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABFIQYCTAAJUIRUUQEPK3D3P4D77VANCNFSM4HZ7MCRQ&data=02%7C01%7Crobvet%40microsoft.com%7C5356cfef92c146745f3608d6f8c983f3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636969941726122791&sdata=bUb283wyL5thRUitqqxVbRNWTVX08iVrC5Wcf1PX%2BFo%3D&reserved=0>.

2019-06-24 17:33 UTC, robvet commented
Give me an hour to finish updating it and I’ll do a PR.

Thanks!

Rob Vettor | Principal Cloud System Architect
                      | ASD IP Architect
                      | Developer Advisory Services for Azure

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image004.jpg@01D52A88.EFC67FE0]  www.thinkingincloudnative.com<http://www.thinkingincloudnative.com/>

From: Robert Vettor
Sent: Monday, June 24, 2019 12:31 PM
To: dotnet/docs <reply@reply.github.com>; dotnet/docs <docs@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [dotnet/docs] Cloud Native Chapter 5 (#12932)

It’s been done. I’m updating that md right now.


Thanks!

Rob Vettor | Principal Cloud System Architect
                      | ASD IP Architect
                      | Developer Advisory Services for Azure

[Description: cid:image001.gif@01CC9CCD.D94B9620]  214-707-0584
[Description: cid:image003.gif@01CC9CCD.D94B9620]   robvet@microsoft.com<mailto:robvet@microsoft.com>
[cid:image005.jpg@01D52A88.EFC67FE0]  www.thinkingincloudnative.com<http://www.thinkingincloudnative.com/>

From: Steve Smith <notifications@github.com<mailto:notifications@github.com>>
Sent: Monday, June 24, 2019 12:30 PM
To: dotnet/docs <docs@noreply.github.com<mailto:docs@noreply.github.com>>
Cc: Robert Vettor <robvet@microsoft.com<mailto:robvet@microsoft.com>>; Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: Re: [dotnet/docs] Cloud Native Chapter 5 (#12932)


@robvet<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Frobvet&data=02%7C01%7Crobvet%40microsoft.com%7C5356cfef92c146745f3608d6f8c983f3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636969941726112793&sdata=ubWf6o6dnAucrLn48BQVebKErc1eAYOvd1ZZQHZzU3g%3D&reserved=0> do you want to complete Cosmos and Azure Storage Services in this PR or as a follow-on?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fdocs%2Fpull%2F12932%3Femail_source%3Dnotifications%26email_token%3DABFIQYBESIAHOKQQWYMBUK3P4D77VA5CNFSM4HZ7MCR2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGODYNUUOY%23issuecomment-505104955&data=02%7C01%7Crobvet%40microsoft.com%7C5356cfef92c146745f3608d6f8c983f3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636969941726122791&sdata=rMa8YIP5HtPb%2BtFTeiMYBKql7CzE29uJl7KHOJGX90s%3D&reserved=0>, or mute the thread<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FABFIQYCTAAJUIRUUQEPK3D3P4D77VANCNFSM4HZ7MCRQ&data=02%7C01%7Crobvet%40microsoft.com%7C5356cfef92c146745f3608d6f8c983f3%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636969941726122791&sdata=bUb283wyL5thRUitqqxVbRNWTVX08iVrC5Wcf1PX%2BFo%3D&reserved=0>.

2019-06-25 12:57 UTC, ardalis commented
@rpetrusha Are we good to merge now?

2019-06-25 18:01 UTC, rpetrusha approved these changes

2019-06-25 18:09 UTC, rpetrusha commented
I've approved and I'll merge now, @ardalis.

2019-06-25 18:09 UTC, merged