Cloud Native Chapter 6
dotnet/docs pull request #12951
Opened 2019-06-21 10:46 UTC by ardalis

## Summary

Chapter 6 md files and images

2019-06-21 13:34 UTC, EugeneKramer commented on docs/architecture/cloud-native/resilient-communications.md
> +- *Out-of-process network communication* Each service communicates over a network protocol which introduces network congestion, latency and transient faults
```suggestion
- *Out-of-process network communication* - Each service communicates over a network protocol which introduces network congestion, latency and transient faults.
```

2019-06-21 13:35 UTC, EugeneKramer commented on docs/architecture/cloud-native/resilient-communications.md
> +- *Resiliency and failover* How do we manage short-lived failures and keep the system stable?
```suggestion
- *Resiliency and failover* - How do we manage short-lived failures and keep the system stable?
```

2019-06-21 13:35 UTC, EugeneKramer commented on docs/architecture/cloud-native/resilient-communications.md
> +- *Load balancing* How does inbound traffic get distributed across multiple instances of a service?
```suggestion
- *Load balancing* - How does inbound traffic get distributed across multiple instances of a service?
```

2019-06-21 13:36 UTC, EugeneKramer commented on docs/architecture/cloud-native/resilient-communications.md
> +- *Security* How are security concerns such as transport-level encryption and certificate management enforced?
```suggestion
- *Security* - How are security concerns such as transport-level encryption and certificate management enforced?
```

2019-06-21 13:36 UTC, EugeneKramer commented on docs/architecture/cloud-native/resilient-communications.md
> +- *Distributed Monitoring* How do you correlate and capture traceability and monitoring for a single request across multiple consuming services?
```suggestion
- *Distributed Monitoring* - How do you correlate and capture traceability and monitoring for a single request across multiple consuming services?
```

2019-06-21 16:20 UTC, robvet approved these changes

2019-06-21 22:44 UTC, mairaw commented on docs/architecture/cloud-native/application-resiliency-patterns.md
> +Note in the figure above how the various resiliency policies apply to operation requests, whether coming from an external client or another backend service. The goal is to correctly compensate the re
for a that -> not sure what word you wanted to use here

2019-06-21 22:55 UTC, mairaw commented on docs/architecture/cloud-native/application-resiliency-patterns.md
> +As recommended in Chapter 1, Microsoft developers targeting cloud native applications should be building on the .NET Core framework. At the time of this writing, version 2.2 is the current release. V
as a for sending -> as a way for sending?

2019-06-21 23:14 UTC, mairaw commented on docs/architecture/cloud-native/infrastructure-resiliency-azure.md
> +- *Scale proportionally.* When scaling a service, think in terms of *resource sets*. If you were to dramatically scale out a specific service, what impact would that have on backend data stores, cach
will to a -> will what?

2019-06-21 23:15 UTC, mairaw commented on docs/architecture/cloud-native/infrastructure-resiliency-azure.md
> +- *Scale-up aggressively.* A final practice would be to scale up aggressively so that you can quickly meet immediate spikes in traffic without losing business. And, then scale down (remove unneeded r
conservatory -> conservatively?

2019-06-21 23:42 UTC, mairaw commented on docs/architecture/cloud-native/infrastructure-resiliency-azure.md
> +- *Take advantage of platform autoscaling features.* Use built-in autoscaling features whenever possible, rather than custom or third-party mechanisms. Use scheduled scaling rules, where possible, to
missing link

2019-06-21 23:57 UTC, mairaw commented on docs/architecture/cloud-native/infrastructure-resiliency-azure.md
> +- *Azure Service Bus.* The Service Bus client exposes a RetryPolicy property that can be configured with a back-off interval, retry count and TerminationTimeBuffer which specifies the maximum time an
RetryPolicy property or class (https://docs.microsoft.com/en-us/dotnet/api/microsoft.servicebus.retrypolicy?view=azure-dotnet)?

2019-06-22 00:13 UTC, mairaw commented on docs/architecture/cloud-native/resiliency.md
> +- Unexpected [Network Latency](https://www.techopedia.com/definition/8553/network-latency) network latency
this is repeated. not sure which one you wanna keep.

2019-06-22 00:35 UTC, mairaw commented
Review is done @ardalis. But there are some pending comments that we should resolve before merging.

2019-06-22 00:37 UTC, mairaw requested changes
Please look at my questions before we can merge

2019-06-24 15:16 UTC, ardalis commented
Should be good to merge, @mairaw

2019-06-24 21:14 UTC, ardalis commented
This one says there's 1 change requested but I don't see what it is.

2019-06-25 01:16 UTC, mairaw commented
We were having some build issues earlier today. Trying again.

2019-06-25 01:22 UTC, mairaw commented on docs/architecture/cloud-native/infrastructure-resiliency-azure.md
> +- *Azure Service Bus.* The Service Bus client exposes a [RetryPolicy property](https://docs.microsoft.com/dotnet/api/microsoft.servicebus.retrypolicy?view=azure-dotnet) that can be configured with a
If that's really the API you were talking about, this is a class

```suggestion
- *Azure Service Bus.* The Service Bus client exposes a [RetryPolicy class](xref:Microsoft.ServiceBus.RetryPolicy) that can be configured with a back-off interval, retry count, and <xref:Microsoft.ServiceBus.RetryExponential.TerminationTimeBuffer>, which specifies the maximum time an operation can take. The default policy is nine maximum retry attempts with a 30-second backoff period between attempts.
```

2019-06-25 01:27 UTC, mairaw commented
Edited the last one that had major issues before. One comment left.

2019-06-25 03:01 UTC, ardalis commented
Hopefully good to go now.

2019-06-25 05:28 UTC, mairaw approved these changes

2019-06-25 05:29 UTC, merged