Fixing links and adding missing content
dotnet/docs pull request #13017
Opened 2019-06-25 19:17 UTC by ardalis

## Summary

Added 2 missing sections to Chapter 2.
Fixed a bunch of internal links required by the PDF generator.

2019-06-26 14:59 UTC, rpetrusha requested changes
I've left some suggestions and comments, @ardalis. The figures also need to be numbered appropriately.

2019-06-26 14:59 UTC, rpetrusha commented on docs/architecture/cloud-native/other-deployment-options.md
> +**Note**: Do we need to cover deployment to App Service for Containers here or is that covered elsewhere?
Can this be removed?

2019-06-26 14:59 UTC, rpetrusha commented on docs/architecture/cloud-native/other-deployment-options.md
> +To deploy to [Azure Container Instances (ACI)](https://docs.microsoft.com/azure/container-instances/), you need to have configured an Azure Container Registry (ACR) and credentials for accessing it.
```suggestion
To deploy to [Azure Container Instances (ACI)](/azure/container-instances/), you need to have configured an Azure Container Registry (ACR) and credentials for accessing it. You must also have previously pushed your container image to the registry, so it's available to pull into ACI. You can work with ACI using the Azure CLI or through the portal. Azure Container Registries make it easy to deploy individual container instances to ACI directly from within the registry, as shown in Figure 2-x.
```

2019-06-26 14:59 UTC, rpetrusha commented on docs/architecture/cloud-native/other-deployment-options.md
> +Once the deployment completes, you can find the newly-deployed container's IP address and communicate with it over the port you specified.
```suggestion
Once the deployment completes, you can find the newly deployed container's IP address and communicate with it over the port you specified.
```

2019-06-26 17:21 UTC, ardalis commented on docs/architecture/cloud-native/deploy-containers-azure.md
> +**Figure 2-x**. Create container registry
Will do a separate PR with that.

2019-06-26 17:23 UTC, ardalis commented on docs/architecture/cloud-native/other-deployment-options.md
> +**Note**: Do we need to cover deployment to App Service for Containers here or is that covered elsewhere?
Yes, thanks.

2019-06-27 15:41 UTC, rpetrusha commented
@ardalis, can you address the merge conflict?

2019-07-01 14:33 UTC, ardalis commented
Can we merge this and I'll do a pass to fix all the figure numbers? Thanks.

2019-07-01 20:24 UTC, rpetrusha commented
Yes, I'll approve and merge now, @dotnet/nsboard-xamarin

2019-07-01 20:24 UTC, rpetrusha approved these changes

2019-07-01 20:24 UTC, merged