#275 string interpolation tutorial for C#
dotnet/docs pull request #1317
Opened 2016-12-09 19:44 UTC by mgroves

# C# tutorial for string interpolation

## Summary

This is for #275 via up-for-grabs.

## Details

This tutorial covers the basics of string interpolation with the $ symbol. It does not dive deep into string formatting, other than referencing that it is syntactic sugar for String.Format and that interpolated strings can be assigned to IFormattable.

## Suggested Reviewers

Would love a review from anyone, maybe @BillWagner would be best?

2016-12-09 19:44 UTC, dnfclas commented
Hi __@mgroves__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla2.dotnetfoundation.org.
    </span>

TTYL, DNFBOT;

2016-12-09 19:48 UTC, dnfclas commented
__@mgroves__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, DNFBOT;

2016-12-09 20:04 UTC, BillWagner commented
@mgroves I'll give this a thorough review by the end of the day Monday.

One meta-item I found is how you are including the code. We've got CI builds in place to verify that all the samples build and run correctly. The DocFx engine can pull that code into the markdown files. See this section in our contributing guide: https://github.com/dotnet/docs/blob/master/styleguide/template.md#code

Another advantage is that users can download the final sample. It will be great if you have questions adding the sample.

2016-12-09 20:29 UTC, mgroves commented
Okay, I will check that out. I have a sample project, just didn't commit it anywhere yet.

2016-12-12 16:04 UTC, mgroves commented
@BillWagner based on the guide, I just committed snippets. Hopefully I did it correctly. If so, it's pretty similar to how I write blogs and include source code with AsciiDoctorFX (minus the automated part).

2016-12-12 18:51 UTC, mgroves commented
@BillWagner looks like I did something wrong with the `code-csharp` snippets. The path looks correct to me, so is there some other syntax I'm missing?

2016-12-12 19:00 UTC, BillWagner commented
@mgroves I was just reviewing this. The snippet includes "concepts", whereas the path to the file does not:

```
[!code-csharp[String.Format example](../../../samples/snippets/csharp/concepts/new-in-6/string-interpolation.cs#StringFormatExample)]   
```
vs.

samples/snippets/csharp/new-in-6/string-interpolation.cs

2016-12-12 19:20 UTC, BillWagner requested changes
Matt,

Overall, this looks good. There's a few items to fix, and then it should be ready to go.

2016-12-12 19:20 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +## Introduction
It looks like you haven't filled this bit in yet.

2016-12-12 19:20 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +With `String.Format`, you would specify "placeholders" in a string that would be replaced by the parameters following the string. For instance:
If you use '@System.String.Format' this will become a link to the API reference. (It will display 'String.Format')

2016-12-12 19:20 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +For localization, keep in mind that instead of `{0}` style placeholders, you are now storing variable names, which means they must match up with variable names at runtime. If a variable name is not f
These are checked at compile time, not runtime.

2016-12-12 19:20 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +If you run this, you'll get exceptions:
You'll get compiler errors, not runtime exceptions

2016-12-12 19:20 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +For localization, keep in mind that instead of `{0}` style placeholders, you are now storing variable names, which means they must match up with variable names at runtime. If a variable name is not f
The errors you describe are for any interpolated string, not just those that are cast as IFormattableStrings.

I'd move this section above the section on localization.

2016-12-12 19:20 UTC, BillWagner commented on samples/snippets/csharp/new-in-6/string-interpolation.cs
> +            var str = String.Format("My name is {FirstName} {LastName}", firstName, lastName);
This will throw an exception. You want:

```csharp
String.Format("My name is {0} {1}", firstName, lastName);

2016-12-12 19:20 UTC, BillWagner commented on samples/snippets/csharp/new-in-6/string-interpolation.cs
> +            var localizeMe = $"The {adj} brown {animal} jumped over the lazy {otheranimal}";
Because these won't compile, you should put them inline in the markdown file, using the ``` syntax. Otherwise, the CI build will fail.

2016-12-12 19:20 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +For instance, you can add padding and numeric formatting:
Let's add a link to the format strings doc [https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx](https://msdn.microsoft.com/en-us/library/dwhawy9k(v=vs.110).aspx) here to explain how that works.

(We'll catch and update those links when that section in MSDN is migrated).

2016-12-12 19:20 UTC, BillWagner commented on samples/snippets/csharp/new-in-6/string-interpolation.cs
> +            var str = $"My name is {firstName} {lastName}");
There's a trailing ')' that will cause a build error here.

2016-12-12 20:48 UTC, mgroves commented on docs/csharp/tutorials/string-interpolation.md
> +## Introduction
goodness how did I forget to finish that

2016-12-13 20:52 UTC, mgroves commented
@BillWagner I'm not sure what's wrong now: I corrected the code and I even found one more issue with a missing namespace.

2016-12-13 20:54 UTC, BillWagner commented
@mgroves We are having some issues with our build system at the moment.  I'll kick off a new build once I hear that those are addressed. 

Thanks for your patience.

2016-12-14 18:39 UTC, dnfclas commented
Hi __@mgroves__, I'm your friendly neighborhood .NET Foundation Pull Request Bot (You can call me DNFBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by .NET Foundation and real humans are currently evaluating your PR.</p>

TTYL, DNFBOT;

2016-12-14 23:08 UTC, mairaw commented
The builds are working again.

2016-12-15 16:42 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +String Interpolation is the way that placeholders in a string are replaced by the value of a string variable. Before C# 6, the way to do this is with `System.String.Format`. This works okay, but sinc
typo: 'an' => 'and'

2016-12-15 16:43 UTC, BillWagner commented on docs/csharp/tutorials/string-interpolation.md
> +## Introduction
nit: I'd remove the "Introduction" header.

2016-12-15 16:43 UTC, BillWagner approved these changes

2016-12-15 16:44 UTC, BillWagner commented
@mgroves I found one typo, and I'd recommend removing the "Introduction" header (it's usually assumed).

After you fix the typo, I'll merge it.

Thanks again for your contributions.  We really appreciate it.

2016-12-15 16:45 UTC, mgroves commented
Glad to be of service, I might pick up some more of these when I get some time (if that's okay with you)

2016-12-15 18:18 UTC, BillWagner commented
@mgroves Thanks for your question on this issue that relates to this PR.  I'd forgotten to mention two quick changes that you'll need to make on this PR so this shows up in the doc set.

- [ ] Update docs/toc.md to include a link to this file in the C# Guide / Tutorials section.
- [ ] Update docs/csharp/tutorials/index.md to include a short description of this tutorial, with a link to the topic.

I'm sorry I forgot to mention that earlier. 😞

2016-12-15 18:19 UTC, mairaw commented
There is some metadata that needs to be updated to use our new values as well. We can do after you merge @BillWagner!

2016-12-15 18:47 UTC, BillWagner commented
@mairaw I like that idea.  

@mgroves I'll merge this now, and I'll handle the TOC updates, the metadata updates and the intro. This will be live some time tomorrow.

2016-12-15 18:47 UTC, merged