Update ApiAnalyzer section
dotnet/docs pull request #13235
Opened 2019-07-03 21:53 UTC by Lxiamail

## Summary

to clarify the ApiAnalyzer tool's unique value and avoid including the duplicate content as in ApiAnalyzer doc.

Fixes #Issue_Number (if available)

2019-07-03 21:59 UTC, mairaw requested changes
Looks good @Lxiamail. Just a few quick comments to be addressed.

2019-07-03 21:59 UTC, mairaw commented on docs/core/porting/index.md
> +ms.date: 7/03/2019
```suggestion
ms.date: 07/03/2019
```

2019-07-03 21:59 UTC, mairaw commented on docs/core/porting/index.md
> +* .NET API Analyzer - A Roslyn analyzer that discovers .NET Standard API that throws [PlatformNotSupportedException](https://docs.microsoft.com/en-us/dotnet/api/system.platformnotsupportedexception)
```suggestion
* .NET API Analyzer - A Roslyn analyzer that discovers .NET Standard API that throws <xref:System.PlatformNotSupportedException> on some platforms, detects calls to deprecated APIs, and discovers some other potential compatibility risks for C# APIs on different platforms. For more information, see [.NET API analyzer](../../standard/analyzers/api-analyzer.md). This analyzer is helpful after you already created your .NET Core project to identify runtime behavior differences on different platforms. 
```

2019-07-03 22:16 UTC, Lxiamail commented
> Looks good @Lxiamail. Just a few quick comments to be addressed.

Fixed all per feedback

2019-07-04 00:17 UTC, mairaw approved these changes
Looks good. Thanks!

2019-07-04 00:18 UTC, merged