Explain boolean conversion to numeric type.
dotnet/docs pull request #13304
Opened 2019-07-09 14:50 UTC by Youssef1313

The article says
> If you assign the result to a numeric type, Visual Basic converts it from Boolean to that type. This could produce unexpected behavior. For example, 5 AndAlso 12 results in –1 when converted to Integer.

I don't think calling that as `unexpected behavior` is correct. It's expected and the [Boolean Data Type](https://docs.microsoft.com/en-us/dotnet/visual-basic/language-reference/data-types/boolean-data-type#type-conversions) article speaks about it.

2019-07-10 18:54 UTC, rpetrusha requested changes
Thank you for adding this clarification and the other changes you've made, @Youssef1313. I've suggested a number of changes. I also found the original "performs the entire operation in Boolean" to be completely unclear, so I suggested an alternative.

2019-07-10 18:54 UTC, rpetrusha commented on docs/visual-basic/language-reference/operators/orelse-operator.md
> + The `OrElse` operator is defined only for the [Boolean Data Type](../../../visual-basic/language-reference/data-types/boolean-data-type.md). Visual Basic converts each operand as necessary to `Boole
```suggestion
 The `OrElse` operator is defined only for the [Boolean Data Type](../../../visual-basic/language-reference/data-types/boolean-data-type.md). Visual Basic converts each operand as necessary to `Boolean` before evaluating the expression. If you assign the result to a numeric type, Visual Basic converts it from `Boolean` to that type such that `False` becomes `0` and `True` becomes `-1`.
```

2019-07-10 18:54 UTC, rpetrusha commented on docs/visual-basic/language-reference/operators/andalso-operator.md
> + [See Boolean Type Conversions](../../../visual-basic/language-reference/data-types/boolean-data-type#type-conversions)
```suggestion
For more information, see [Boolean Type Conversions](../data-types/boolean-data-type.md#type-conversions)
```

2019-07-10 18:54 UTC, rpetrusha commented on docs/visual-basic/language-reference/operators/orelse-operator.md
> + [See Boolean Type Conversions](../../../visual-basic/language-reference/data-types/boolean-data-type#type-conversions)
```suggestion
For more information, see [Boolean Type Conversions](../data-types/boolean-data-type.md#type-conversions)
```

2019-07-10 19:03 UTC, Youssef1313 commented
I've applied your changes, One of them was suggested only for one article, I've added a commit for the same suggestion to the other article as well.

2019-07-11 16:30 UTC, rpetrusha commented
Thanks, @Youssef1313, for making the additional changes. I'll merge your PR now. The changes should be live by tomorrow.

2019-07-11 16:30 UTC, rpetrusha approved these changes

2019-07-11 16:30 UTC, merged