Add vb sample
dotnet/docs pull request #13303
Opened 2019-07-09 11:31 UTC by Youssef1313

Added vb samples and fixed code that was contradicting

> Each sentence in the string assigned to the Exception.Message property should end in a period.

2019-07-10 18:19 UTC, rpetrusha requested changes
Thank you for adding the missing Visual Basic examples, @Youssef1313. I've suggested a number of changes so that the code compiles.

2019-07-10 18:19 UTC, rpetrusha commented on docs/standard/exceptions/best-practices-for-exceptions.md
> +Catch ex As Exception ex
```suggestion
Catch ex As Exception
```

2019-07-10 18:19 UTC, rpetrusha commented on docs/standard/exceptions/best-practices-for-exceptions.md
> +        .To = to,
```suggestion
        .[To] = [to],
```

2019-07-10 18:24 UTC, Youssef1313 commented
I've committed one suggestion. For the others, I didn't check, but I think it should be `[to]` because visual basic has a reserved word `to` ?

2019-07-10 23:08 UTC, rpetrusha commented
Yes, to is a reserved word, @Youssef1313. I think that all of my remaining suggestions replace `to` with `[to]`, With that, the code compiles and executes successfully.

2019-07-11 05:32 UTC, Youssef1313 commented
> Yes, to is a reserved word, @Youssef1313. I think that all of my remaining suggestions replace `to` with `[to]`, With that, the code compiles and executes successfully.

Oh sorry for that, I thought I already had the square brackets and read the suggestions backwards. Going to apply the changes now.

2019-07-11 16:31 UTC, rpetrusha commented
Thanks for the additional changes, @Youssef1313. I'll approve and merge your PR now.

2019-07-11 16:31 UTC, rpetrusha approved these changes

2019-07-11 16:31 UTC, merged