Added missing vb sample.
dotnet/docs pull request #13300
Opened 2019-07-09 07:42 UTC by Youssef1313

2019-07-10 17:36 UTC, rpetrusha requested changes
Thank you for adding a Visual Basic version of this example, @Youssef1313. Extensions methods, though, must be in modules, where the `Shared` keyword is not supported.

2019-07-10 17:36 UTC, rpetrusha commented on docs/standard/using-linq.md
> +Public Shared Function PublicInstancePropertiesEqual(Of T As Class)(self As T, [to] As T, ParamArray ignore As String()) As Boolean
```suggestion
Public Function PublicInstancePropertiesEqual(Of T As Class)(self As T, [to] As T, ParamArray ignore As String()) As Boolean
```

2019-07-10 18:06 UTC, Youssef1313 commented
> 
> 
> Thank you for adding a Visual Basic version of this example, @Youssef1313. Extensions methods, though, must be in modules, where the `Shared` keyword is not supported.

Thanks, I've committed your change :)

2019-07-11 16:32 UTC, rpetrusha commented
Thanks for the additional change, @Youssef1313. I'll merge your PR now.

2019-07-11 16:32 UTC, rpetrusha approved these changes

2019-07-11 16:32 UTC, merged