WIP: Move documentation of COM interop features in both NETFX and Core into .NET Guide.
dotnet/docs pull request #13402
Opened 2019-07-15 20:07 UTC by jkoritzinsky

## Summary

Move some of the documentation of COM interoperability features that exist in both .NET Framework and .NET Core into the .NET Guide instead of the .NET Framework Guide.

Add tutorial on exposing .NET components to COM in .NET Core as a counterpart to the .NET Framework documentation.

2019-07-16 18:26 UTC, rpetrusha requested changes
Thanks for handling this migration of interop documentatation to the .NET Guide, @jkoritzinsky. I've left some comments and suggested changes.

2019-07-16 18:26 UTC, rpetrusha commented on docs/standard/native-interop/cominterop.md
> +The Component Object Model (COM) lets an object expose its functionality to other components and to host applications. To help enable users to interoperate with their existing code bases, the .NET Fr
```suggestion
The Component Object Model (COM) lets an object expose its functionality to other components and to host applications on Windows platforms. To help enable users to interoperate with their existing code bases, the .NET Framework has always provided strong support for interoperating with COM libraries. In .NET Core 3.0, a large portion of this support has been added to .NET Core on Windows. The documentation here will explain how the common COM interop techonologies work and how you can utilize them to interoperate with your existing COM libraries.
```
I thought that making it clear that this applies to Windows only in the first sentence is important.

2019-07-19 23:52 UTC, rpetrusha commented
@jkoritzinsky, there are merge conflicts. Can you resolve them?

2019-07-24 06:54 UTC, mairaw commented on docs/core/native-interop/exposing-dotnet-components-to-com.md
> +---
File name: for SEO and general guidelines (https://review.docs.microsoft.com/en-us/help/contribute/file-path-guidelines?branch=master#name-your-files)
I think the file name of this article should be expose-components-to-com.md (dotnet is already part of the path and shouldn't be repeated if possible)

2019-07-24 06:54 UTC, mairaw commented on .openpublishing.redirection.json
> +            "redirect_url": "/dotnet/standard/native-interop/applying-interop-attributes",
I'd the opportunity to fix some SEO and naming issues here as well

```suggestion
            "redirect_url": "/dotnet/standard/native-interop/apply-attributes",
```

2019-07-24 06:54 UTC, mairaw commented on .openpublishing.redirection.json
> +            "redirect_url": "/dotnet/standard/native-interop/qualifying-net-types-for-introspection",
```suggestion
            "redirect_url": "/dotnet/standard/native-interop/qualify-types-for-introspection",
```

2019-07-26 21:44 UTC, rpetrusha approved these changes

2019-07-26 21:44 UTC, rpetrusha commented
The builds look really good, @jkoritzinsky. I'll merge this now.

2019-07-26 21:44 UTC, merged