Added install pages to docs
dotnet/docs pull request #1341
Opened 2016-12-17 02:30 UTC by kendrahavens

Move Step-by-Step Install Instructions for .NET Core to Docs

## Summary

* These pages are a starting place for creating more descriptive installation steps

Fixes #1321 

## Details
- Topics Added
   - Visual Studio 2017
  - Visual Studio 2015 Update 3
  - Windows with CLI Tools (VSCode)
  - RHEL
  - Ubuntu or Linux Mint
  - Debian
  - Fedora
  - CentOS or Oracle
  - openSUSE
  - macOS
  - Docker VS 2017 RC
  - Docker CLI
- Added Index Folder and Page
- Changed Core/Getting Started page into a folder
  - Moved getting-started.md to index.md in getting-started folder
  - Update references to getting-started.md to getting-started/index.md

## Suggested Reviewers
@mairaw @BillWagner @richlander @blackdwarf

2016-12-19 22:19 UTC, BillWagner reviewed
The content looks great. I like the way it's been re-organized for each OS and distro.

A lot of comments, but they are pretty repetitive and mostly in the meta data.  The "Description" field shows up in search requests, so we should make sure that's really helpful for people searching for this content. 

Also, note that a few of the comments were questions, where I wasn't sure what the right content should be.

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/index.md
> +description: Install .NET Core
I'd go for something more descriptive here:

> How to install .NET Core on Linux, Mac, or Windows.

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/index.md
> +ms.assetid:
Add Asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/mac.md
> +description: Install for macOS 10.11 or higher
This should include .NET Core:

> How to install .NET Core for macOS ....

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/mac.md
> +ms.assetid:
add asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/mac.md
> +## 1. Install pre-requisites
This doesn't say anything about uninstalling previous versions. Is that not necessary on Mac? (If not, it doesn't need to be stated. I was just noticing after reading all the others)

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/opensuse.md
> +description: Install for openSUSE
The Description should include .NET Core:

> Install .NET Core and SDK for open SUSE

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/opensuse.md
> +ms.assetid:
add asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/opensuse.md
> +openSUSE 13.2
Should this (and 'openSUSE 42.1 below) be highlighted? A list perhaps?

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/mac.md
> +- The first command will restore the packages specified in the project.json file, and the second command will run the actual sample:
Is it still project.json, or csproj?

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/opensuse.md
> +- The first command will restore the packages specified in the project.json file, and the second command will run the actual sample:
Is it still project.json, or csproj?

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/rhel.md
> +description: Install for Red Hat Enterprise Linux 7 Server
Description should include .NET Core.

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/rhel.md
> +ms.assetid:
Include the asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/rhel.md
> +- For help on registering your machine to get access to the channel see the [Chapter 1](https://access.redhat.com/documentation/en/net-core/1.0/getting-started-guide/chapter-1-install-net-core-100-on
nit: "see the Chapter 1" could be "see Chapter 1"

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/rhel.md
> +- Now you can install .NET Core 1.0 and then enable the .NET Core software collection.
This is 1.0. Most of the others are 1.1.  Is 1.0 correct?

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/ubuntu-mint.md
> +description: Install for Ubuntu 14.04, 16.04, 16.10 & Linux Mint 17
Description should include .NET Core

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/ubuntu-mint.md
> +ms.assetid:
add asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/ubuntu-mint.md
> +Ubuntu 14.04 / Linux Mint 17
Should this (and "Ubuntu 16.04", "Ubuntu 16.10" below) be highlighted?

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/win-cli.md
> +description: Install for Windows - Command Line
The description should include .NET Core.

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/win-cli.md
> +ms.assetid:
add the asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/win-vs2015.md
> +description: Install for Windows - Visual Studio 2015
The description should include .NET Core

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/win-vs2015.md
> +ms.assetid:
add the asset ID

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/win-vs2017.md
> +description: Install for Windows - Visual Studio 2017
This should include .NET Core.

Also, should it include RC in the Visual Studio 2017 name?

2016-12-19 22:19 UTC, BillWagner commented on docs/core/getting-started/install/win-vs2017.md
> +ms.assetid:
add the GUID for asset ID

2016-12-21 00:01 UTC, mairaw commented
I'm doing the review now but I can't comment on the renaming action so adding a separate comment here. We can't simply rename files. We need to add a redirect metadata to the original file and then have a new file created in the desired destination, otherwise we impact SEO and break external links. This is an example where we "moved" the topic to a new location: https://raw.githubusercontent.com/dotnet/docs/master/docs/core/app-types.md

I'd also look for where we use that link in our own content to avoid having to apply the redirect. The links should all go to the right place.

2016-12-21 01:02 UTC, mairaw requested changes
added a few comments for now but haven't gone through all topics yet.

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/centos-oracle.md
> +```
you can say it's console commands using this syntax:
```markdown
```console
```

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2017.md
> +  ## [Download Visual Studio 2017 RC](https://www.visualstudio.com/vs/visual-studio-2017-rc/)
remove the ## from this line

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2017.md
> +## 2. Install the .NET Core tools preview workload
We have one topic on the vs docs that covers installation. I kind of like how they show the exact steps and screenshots you get:
https://docs.microsoft.com/en-us/visualstudio/install/install-visual-studio

The main difference here would be that in our case we tell them which specifically workload to choose. In this topic, we're going from download VS to install the workload. There are some missing steps in between.

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2017.md
> +- An experimental release of .NET Core tools for Visual Studio is included in Visual Studio 2017 RC.
experimental -> preview?

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/opensuse.md
> +## 3. Initialize some code
do we really want to have the part of writing code for each installation topic?

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2017.md
> +You now have .NET core running on your machine!
should we also change this topic: https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio-2017?branch=pr-en-us-1341 to not have install instructions in the prerequisites and instead just link to this topic?

2016-12-21 01:02 UTC, mairaw commented on docs/standard/getting-started.md
> -* [Getting Started with .NET Core](../core/getting-started.md) provides an overview of articles which show how to get started with .NET Core on different operating systems and using different tools.
should you also add the installation topic(s) here in this article as a separate section?

2016-12-21 01:02 UTC, mairaw commented on docs/toc.md
> +#### [RHEL](rhel.md)
these links are all broken. take a look at the build report. they should look like core/getting-started/install/rhel.md

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2017.md
> +---
I'd spell out windows in the filename since it helps with SEO too

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/mac.md
> +[!TIP] [Video: Install .NET Core and Visual Studio Code on a Mac](https://sec.ch9.ms/ch9/91a8/38eb734a-ea5a-4e3d-92ee-15de701391a8/VSCodeMac_high.mp4)
Right syntax for tips is (notice the greater then sign):
```markdown
> [!TIP]
tip text
```

same for notes as below

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/mac.md
> +## [Download .NET Core SDK](https://go.microsoft.com/fwlink/?LinkID=835011)
I don't think you meant to have this as a section title

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2015.md
> +  ## [Download Visual Studio 2015 with Update 3](https://go.microsoft.com/fwlink/?LinkId=691978)
remove ##

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/win-vs2015.md
> +- Or just download [Visual Studio 2015 Update 3](https://go.microsoft.com/fwlink/?LinkId=691129) if you already have Visual Studio 2015 installed.
Our windows prerequisites page calls out Update 3.3 as well, take a look: https://docs.microsoft.com/en-us/dotnet/articles/core/windows-prerequisites

also, what are your plans for that particular topic? it also has some notes about the offline installer option that should be part of both VS topics (I know the VS 2015 one is correct; I'm not sure the status of offline installer for VS 2017).

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/index.md
> +# Install .NET Core
Are we covering Installing the runtime or the SDK in the topics? I believe it's the latter, so should we call this topic Install the .NET Core SDK?

I'm also wondering if we really need this topic. For example, the Install node doesn't HAVE to have a topic associated. It makes sense if we think we want to link to this topic and not to the child topics directly and if we think it's better organized here if the OS groupings.

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/index.md
> +### [Install for RHEL](rhel.md)
shouldn't this one match the others?

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/mac.md
> +## Want some tools?
this question could be confusing. You already installed .NET SDK which we often call it .NET Core tools. Should we change this here to something like "Want some developing tools?"

2016-12-21 01:02 UTC, mairaw commented on docs/core/getting-started/install/mac.md
> +
comment refers to the images below that are not part of this topic: for the images that are duplicate, should we just put them in one single place and then refer to the same image? like we have the same debug image at least 3x. If we need to localize these images later, loc will have to pay for 3 different images. Also, we already have some of these in the C# folder. https://github.com/dotnet/docs/blob/master/docs/csharp/getting-started/media/simple_hello.jpg

2016-12-22 23:59 UTC, kendrahavens commented on docs/core/getting-started/install/opensuse.md
> +openSUSE 13.2
Yeah, putting them in a list makes them blend in too much with the bulleted list they follow. I'll try 3 hashtags.

2016-12-23 00:19 UTC, kendrahavens commented on docs/core/getting-started/install/centos-oracle.md
> +description: Install for CentOS 7.1 & Oracle Linux 7.1
Gotcha.

2017-01-14 04:12 UTC, mairaw commented
@kendrahavens I've added the GUIDs as you requested and did a couple of other fixes like broken links. Haven't addressed all the feedback though.

2017-03-04 05:07 UTC, mairaw commented
@kendrahavens should I close this one based on what we discussed offline?

2017-03-05 00:05 UTC, kendrahavens commented
@mairaw Sure, we can re-open if necessary after syncing with .NET Core landing page owners. The main problems addressed with this PR would be more easily solved and maintained on the dot.net/core pages.

2017-03-05 00:05 UTC, closed without merging