Remove inaccurate information
dotnet/docs pull request #13605
Opened 2019-07-27 19:25 UTC by Youssef1313

The article says:

> errors (also called exceptions) fall into one of three categories: syntax errors, run-time errors, and logic errors.

I don't think that referring to errors as exception is correct, since the syntax errors and logic errors aren't exceptions.

2019-07-28 03:36 UTC, rpetrusha requested changes
Thanks, @Youssef1313. You've identified a major weakness in a topic that is in serious need of revision. I've suggested some quick-and-dirty fixes to improve the topic a bit more. Let me know what you think.

2019-07-28 03:36 UTC, rpetrusha commented on docs/visual-basic/programming-guide/language-features/error-types.md
> + *Syntax errors* are those that appear while you write code. Visual Basic checks your code as you type it in the **Code Editor** window and alerts you if you make a mistake, such as misspelling a wor
```suggestion
 *Syntax errors* are those that appear while you write code. If you're using Visual Studio, Visual Basic checks your code as you type it in the **Code Editor** window and alerts you if you make a mistake, such as misspelling a word or using a language element improperly. If you compile from the command line, Visual Basic displays a compiler error with information about the syntax error. Syntax errors are the most common type of errors. You can fix them easily in the coding environment as soon as they occur.
```

2019-07-28 03:36 UTC, rpetrusha commented on docs/visual-basic/programming-guide/language-features/error-types.md
> + *Run-time errors* are those that appear only after you compile and run your code. These involve code that may appear to be correct in that it has no syntax errors, but that will not execute. For exa
```suggestion
 *Run-time errors* are those that appear only after you compile and run your code. These involve code that may appear to be correct in that it has no syntax errors, but that will not execute. For example, you might correctly write a line of code to open a file. But if the file does not exist, the application cannot open the file, and it throws an exception. You can fix most run-time errors by rewriting the faulty code or by using [exception handling](../../language-reference/statements/try-catch-finally-statement.md), and then recompiling and rerunning it.
```

2019-07-28 03:36 UTC, rpetrusha commented on docs/visual-basic/programming-guide/language-features/error-types.md
> + *Logic errors* are those that appear once the application is in use. They are most often unwanted or unexpected results in response to user actions. For example, a mistyped key or other outside infl
```suggestion
 *Logic errors* are those that appear once the application is in use. They are most often faulty assumptions made by the developer, or unwanted or unexpected results in response to user actions. For example, a mistyped key might provide incorrect information to a method, or you may assume that a valid value is always supplied to a method that is not the case. Although logic errors can be handled by using [exception handling](../../language-reference/statements/try-catch-finally-statement.md) (for example, by testing whether an argument is `Nothing` and throwing a <xref:System.ArgumentNullException>), most commonly they should be addressed by correcting the error in logic and recompiling the application.
```

2019-07-28 04:10 UTC, Youssef1313 commented
Thanks for your suggestions, @rpetrusha :)
I've applied them, I just replaced `a ArgumentNullException` with `an ArgumentNullException`.

2019-07-29 16:12 UTC, rpetrusha approved these changes

2019-07-29 16:13 UTC, rpetrusha commented
Thanks for making the additional changes, @Youssef1313. I'll merge your PR as soon as our internal build completes successfully.

2019-07-29 16:19 UTC, merged