Clarify 3.0 note about serial ports
dotnet/docs pull request #13627
Opened 2019-07-29 18:04 UTC by krwq

Clarify 3.0 note about serial ports.

Related to https://github.com/dotnet/corefx/issues/39814

2019-07-29 18:59 UTC, Thraka requested changes
LGTM here are a few suggestions on clarifying the wording. Please accept these. Thanks!

2019-07-29 18:59 UTC, Thraka commented on docs/core/whats-new/dotnet-core-3-0.md
> +.NET Core 3.0 have basic support for <xref:System.IO.Ports.SerialPort?displayProperty=nameWithType> on Linux.
```suggestion
.NET Core 3.0 provides basic support for <xref:System.IO.Ports.SerialPort?displayProperty=nameWithType> on Linux.
```

2019-07-29 18:59 UTC, Thraka commented on docs/core/whats-new/dotnet-core-3-0.md
> +Please refer to https://github.com/dotnet/corefx/issues/33146 for information on limitations.
Changing this to our standard verbage

```suggestion
For more information about the limited support for the serial port on Linux, see [GitHub issue #33146](https://github.com/dotnet/corefx/issues/33146).
```

2019-07-29 20:02 UTC, krwq commented
Thanks @Thraka!

2019-08-19 17:23 UTC, Thraka approved these changes

2019-08-19 17:23 UTC, merged