Moved and revised the default operator article
dotnet/docs pull request #13684
Opened 2019-08-01 06:14 UTC by pkulikov

Contributes to #10741
Supported by dotnet/samples#1132

2019-08-01 20:25 UTC, rpetrusha commented
Closing and reopening to begin new build after dotnet/samples#1132 was merged.

2019-08-01 20:58 UTC, rpetrusha commented
Code did not appear in the most recent build. Closing and reopening to begin new build.

2019-08-01 22:24 UTC, rpetrusha requested changes
Thanks for doing this, @pkulikov. This looks good. I've left a few suggestions and one question for you to consider.

2019-08-01 22:24 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/default.md
> +- As the [default operator](../operators/default.md) to produce the default value of a type.
Should this also mention the default literal?

2019-08-01 22:24 UTC, rpetrusha commented on docs/csharp/language-reference/operators/default.md
> +The `default` operator produces the [default value](../keywords/default-values-table.md) of a type. An argument of the `default` operator must be the name of a type or a type parameter.
```suggestion
The `default` operator produces the [default value](../keywords/default-values-table.md) of a type. The argument to the `default` operator must be the name of a type or a type parameter.
```

2019-08-01 22:24 UTC, rpetrusha commented on docs/csharp/language-reference/operators/default.md
> +- assignment or initialization of a variable
```suggestion
- In the assignment or initialization of a variable.
```

2019-08-01 22:24 UTC, rpetrusha commented on docs/csharp/language-reference/operators/default.md
> +- declaration of the default value for an optional method parameter
```suggestion
- In the declaration of the default value for an optional method parameter.
```

2019-08-01 22:24 UTC, rpetrusha commented on docs/csharp/language-reference/operators/default.md
> +- providing the argument value in a method call
```suggestion
- In an argument to a method call.
```

2019-08-01 22:24 UTC, rpetrusha commented on docs/csharp/language-reference/operators/default.md
> +- in a `return` statement or as an expression in an expression-bodied member
```suggestion
- In a `return` statement or as an expression in an expression-bodied member.
```

2019-08-02 04:06 UTC, pkulikov commented
@rpetrusha thanks for the review and suggestions. I've addressed your feedback; please take a look at the latest commit.

2019-08-02 15:00 UTC, rpetrusha commented
This looks very good, @pkulikov; thanks for the additional changes. I'll merge your PR now.

2019-08-02 15:00 UTC, rpetrusha approved these changes

2019-08-02 15:00 UTC, merged