Correction in "Develop ASP.NET Core MVC apps"
dotnet/docs pull request #13812
Opened 2019-08-12 01:57 UTC by widjesh

## Summary

I changed this 

"
app.UseMvc(routes =>;
{
    routes.MapRoute("default","{controller=Home}/{action=Index}/{id?}");
});
"

 into this

"
app.UseMvc(routes =>
{
    routes.MapRoute("default","{controller=Home}/{action=Index}/{id?}");
});
"

2019-08-12 02:02 UTC, widjesh reviewed
the ";" should not be there

2019-08-12 02:02 UTC, widjesh commented on docs/architecture/modern-web-apps-azure/develop-asp-net-core-mvc-apps.md
> -app.UseMvc(routes =>;
the ";" should not be there

2019-08-12 09:34 UTC, Youssef1313 requested changes
Shouldn't the same fix be applied to this line ?
`_connection.On("receiveMessage", (arguments) =>;`

2019-08-12 09:36 UTC, Youssef1313 requested changes
I also think that there shouldn't be a `\`s in this line:
`Console.WriteLine(\$"{arguments\[0\]} said: {arguments\[1\]}");`

**Update:**

I've made a separate [PR](https://github.com/dotnet/docs/pull/13819) for this `\` issue.

2019-08-12 17:48 UTC, rpetrusha requested changes
Thank you, @widjesh, for contributing to the dotnet/docs repo and correcting the syntactically incorrect line of code. There are a number of other compiler errors in the code. Could you correct them also? They are:
- line 205: should begin with `public class` to define the type.
- line 471: no `;` following `=>`

2019-08-27 19:34 UTC, rpetrusha approved these changes

2019-08-27 19:35 UTC, merged