Note that these features aren't installed by default.
dotnet/docs pull request #13836
Opened 2019-08-13 18:10 UTC by dasetser

Customers have reported confusion when they're unable to create new WCF files by default in recent version of Visual Studio. This not should give them a hint if they look for documentation as to why these are missing.

2019-08-13 20:07 UTC, rpetrusha requested changes
I've left some suggested changes, @dasetser.

2019-08-13 20:07 UTC, rpetrusha commented on docs/framework/wcf/using-the-wcf-development-tools.md
> + > Starting with Visual Studio 2017 the WCF Development Tools are not installed by default. In order to use these features you must ensure the Windows Communication Foundation individual component is
```suggestion
 > Starting with Visual Studio 2017, the WCF development tools are not installed by default. In order to use these features, you must ensure the Windows Communication Foundation component is selected in the Visual Studio installer.
```

2019-08-13 21:13 UTC, HongGit approved these changes

2019-08-14 22:38 UTC, rpetrusha approved these changes

2019-08-14 22:38 UTC, merged