[framework] Remove redundant path segments (part 1)
dotnet/docs pull request #13928
Opened 2019-08-19 22:49 UTC by nemrism

Remove redundant path in relative links inside /framework/** files

Contributes to #10653

2019-08-20 02:27 UTC, mairaw commented
I know these changes are super straightforward but let's try to keep these PRs with ~100 files. I'll review this one as-is though.

2019-08-20 02:29 UTC, mairaw commented on docs/framework/additional-apis/index.md
> +- [The .NET Framework and Out-of-Band Releases](the-net-framework-and-out-of-band-releases.md)
I think this path needs to look like this:

```suggestion
- [The .NET Framework and Out-of-Band Releases](../get-started/the-net-framework-and-out-of-band-releases.md)
```

2019-08-20 03:11 UTC, mairaw requested changes
Wonderful to see these changes. In addition to the broken link I've pointed out, I also have a few additional comments. I've reviewed 200/502 files so far.

2019-08-20 03:27 UTC, mairaw reviewed
A few more comments... 300/502 files reviewed.

2019-08-20 03:27 UTC, mairaw commented on docs/framework/network-programming/using-an-asynchronous-server-socket.md
>  - [Threading](../../../docs/standard/threading/index.md)
```suggestion
- [Threading](../../standard/threading/index.md)
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/performance/etw-events.md
>   In the .NET Framework, ETW event tracing is available for the common language runtime (CLR), the [Task Parallel Library](../../../docs/standard/parallel-programming/task-parallel-library-tpl.md), an
```suggestion
 In the .NET Framework, ETW event tracing is available for the common language runtime (CLR), the [Task Parallel Library](../../standard/parallel-programming/task-parallel-library-tpl.md), and [Parallel LINQ (PLINQ)](../../standard/parallel-programming/parallel-linq-plinq.md).  
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/performance/etw-events.md
>  - [Task Parallel Library (TPL)](../../../docs/standard/parallel-programming/task-parallel-library-tpl.md)
```suggestion
- [Task Parallel Library (TPL)](../../standard/parallel-programming/task-parallel-library-tpl.md)
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/performance/lazy-initialization.md
>  - [Managed Threading Basics](../../../docs/standard/threading/managed-threading-basics.md)
```suggestion
- [Managed Threading Basics](../../standard/threading/managed-threading-basics.md)
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/performance/lazy-initialization.md
>  - [Threads and Threading](../../../docs/standard/threading/threads-and-threading.md)
```suggestion
- [Threads and Threading](../../standard/threading/threads-and-threading.md)
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/performance/lazy-initialization.md
>  - [Task Parallel Library (TPL)](../../../docs/standard/parallel-programming/task-parallel-library-tpl.md)
```suggestion
- [Task Parallel Library (TPL)](../../standard/parallel-programming/task-parallel-library-tpl.md)
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md
> + ![Dynamic Language Runtime Architecture Overview](media/dlr-archoverview.png "DLR_ArchOverview")
```suggestion
 ![Dynamic Language Runtime Architecture Overview](./media/dlr-archoverview.png "DLR_ArchOverview")
```

2019-08-20 03:27 UTC, mairaw commented on docs/framework/reflection-and-codedom/dynamically-loading-and-using-types.md
>  - [Type Conversion in the .NET Framework](../../../docs/standard/base-types/type-conversion.md)
```suggestion
- [Type Conversion in the .NET Framework](../../standard/base-types/type-conversion.md)
```

2019-08-20 04:17 UTC, mairaw reviewed
More comments,,, 400/502

2019-08-20 04:17 UTC, mairaw commented on docs/framework/tools/winres-exe-windows-forms-resource-editor.md
>  - [Globalization and Localization](../../../docs/standard/globalization-localization/index.md)
```suggestion
- [Globalization and Localization](../../standard/globalization-localization/index.md)
```

2019-08-20 04:17 UTC, mairaw commented on docs/framework/ui-automation/access-embedded-objects-using-ui-automation.md
> + ![Embedded objects in a text container.](media/uia-textpattern-embeddedobjects.PNG "UIA_TextPattern_EmbeddedObjects")
```suggestion
 ![Embedded objects in a text container.](./media/uia-textpattern-embeddedobjects.PNG "UIA_TextPattern_EmbeddedObjects")  
```

2019-08-20 04:46 UTC, mairaw reviewed
Finished the review now. A couple more comments...

Also, apologies for including two commits here that were supposed to be done on a separate PR I'm working on. It's fine to leave them here if they don't cause any issues.

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/implementing-the-ui-automation-table-control-pattern.md
> + ![Table with complex header items.](media/uia-tablepattern-complex-column-headers.PNG "UIA_TablePattern_Complex_Column_Headers")
```suggestion
 ![Table with complex header items.](./media/uia-tablepattern-complex-column-headers.PNG "UIA_TablePattern_Complex_Column_Headers")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/implementing-the-ui-automation-table-control-pattern.md
> + ![Table with ambiguous RowOrColumnMajor property.](media/uia-tablepattern-roworcolumnmajorproperty.PNG "UIA_TablePattern_RowOrColumnMajorProperty")
```suggestion
 ![Table with ambiguous RowOrColumnMajor property.](./media/uia-tablepattern-roworcolumnmajorproperty.PNG "UIA_TablePattern_RowOrColumnMajorProperty")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/implementing-the-ui-automation-value-control-pattern.md
> + ![Editable list item.](media/uia-valuepattern-editable-listitem.PNG "UIA_ValuePattern_Editable_ListItem")
```suggestion
 ![Editable list item.](./media/uia-valuepattern-editable-listitem.PNG "UIA_ValuePattern_Editable_ListItem")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/implementing-the-ui-automation-value-control-pattern.md
> + ![Color picker with yellow highlighted.](media/uia-valuepattern-colorpicker.png "UIA_ValuePattern_ColorPicker")
```suggestion
 ![Color picker with yellow highlighted.](./media/uia-valuepattern-colorpicker.png "UIA_ValuePattern_ColorPicker")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> + ![Embedded Table with Image in a Text Container](media/uia-textpattern-embedded-objects-overview-example1.png "UIA_TextPattern_Embedded_Objects_Overview_Example1")
```suggestion
 ![Embedded Table with Image in a Text Container](./media/uia-textpattern-embedded-objects-overview-example1.png "UIA_TextPattern_Embedded_Objects_Overview_Example1")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> + ![Content view for the preceding example](media/uia-textpattern-embedded-objects-overview-example2.PNG "UIA_TextPattern_Embedded_Objects_Overview_Example2")
```suggestion
 ![Content view for the preceding example](./media/uia-textpattern-embedded-objects-overview-example2.PNG "UIA_TextPattern_Embedded_Objects_Overview_Example2")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> + ![Text ranges spanned by embedded objects.](media/uia-textpattern-embeddedobjecttextranges.png "UIA_TextPattern_EmbeddedObjectTextRanges")
```suggestion
 ![Text ranges spanned by embedded objects.](./media/uia-textpattern-embeddedobjecttextranges.png "UIA_TextPattern_EmbeddedObjectTextRanges")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> + ![Range adjustments by Move & ExpandToEnclosingUnit](media/uia-textpattern-moveandexpand-examples.png "UIA_TextPattern_MoveAndExpand_Examples")
```suggestion
 ![Range adjustments by Move & ExpandToEnclosingUnit](./media/uia-textpattern-moveandexpand-examples.png "UIA_TextPattern_MoveAndExpand_Examples")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> + {The image ![Embedded Image Example](media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample") is embedded in text}.
```suggestion
 {The image ![Embedded Image Example](./media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample") is embedded in text}.  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> + {The image} ![Embedded Image Example](media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample") is embedded in text.
```suggestion
 {The image} ![Embedded Image Example](./media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample") is embedded in text.  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> +|![Embedded Image Example](media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample")|X|
```suggestion
|![Embedded Image Example](./media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample")|X|  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> +|![Embedded Image Example 2](media/uia-textpattern-embedded-objects-overview-imageexample2.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample2")|Y|
```suggestion
|![Embedded Image Example 2](./media/uia-textpattern-embedded-objects-overview-imageexample2.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample2")|Y|  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> +|![Embedded Image Example 3](media/uia-textpattern-embedded-objects-overview-imageexample3.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample3")<br /><br /> Image for Z|Z|
```suggestion
|![Embedded Image Example 3](./media/uia-textpattern-embedded-objects-overview-imageexample3.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample3")<br /><br /> Image for Z|Z|  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/textpattern-and-embedded-objects-overview.md
> +|<xref:System.Windows.Automation.TextPattern.RangeFromChild%2A> where <xref:System.Windows.Automation.AutomationElement> is the object returned by the previous `GetItem` method.|Returns the range tha
```suggestion
|<xref:System.Windows.Automation.TextPattern.RangeFromChild%2A> where <xref:System.Windows.Automation.AutomationElement> is the object returned by the previous `GetItem` method.|Returns the range that spans the image ![Embedded Image Example](./media/uia-textpattern-embedded-objects-overview-imageexample.PNG "UIA_TextPattern_Embedded_Objects_Overview_ImageExample").|  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/ui-automation-support-for-the-pane-control-type.md
> + ![Screenshot of applet window with two panes](media/uiauto-pane.GIF "uiauto_pane")
```suggestion
 ![Screenshot of applet window with two panes](./media/uiauto-pane.GIF "uiauto_pane")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/ui-automation-support-for-the-splitbutton-control-type.md
> + ![Split button](media/uiauto-splitbutton-detailed.gif "uiauto_splitbutton_detailed")
```suggestion
 ![Split button](./media/uiauto-splitbutton-detailed.gif "uiauto_splitbutton_detailed")  
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/ui-automation/ui-automation-textpattern-overview.md
> +![TextPatternRangeEndpoints &#40;start and end&#41;.](media/uia-textpattern-endpoints.PNG "UIA_TextPattern_Endpoints")
```suggestion
![TextPatternRangeEndpoints &#40;start and end&#41;.](./media/uia-textpattern-endpoints.PNG "UIA_TextPattern_Endpoints")
```

2019-08-20 04:46 UTC, mairaw commented on docs/framework/windows-services/how-to-create-windows-services.md
> +     ![Set the ServiceName property.](media/windowsservice-servicename.PNG "WindowsService_ServiceName")
```suggestion
     ![Set the ServiceName property.](./media/windowsservice-servicename.PNG "WindowsService_ServiceName")  
```

2019-08-20 08:27 UTC, nemrism commented
I applied all suggested fixes about "incorrect" includes of `media` files.

I've changed all links to `/standard` section in the following PR: #13925 as this replacement work is quite huge even if I split by folders...
Once it will be merged I could rebase this branch in order to "facilitate" the final review.

2019-08-21 05:46 UTC, mairaw commented
@nemrism can you fix the merge conflicts?

2019-08-21 10:06 UTC, nemrism commented
Yes, I'll push that asap

2019-08-21 14:06 UTC, nemrism commented
Merged, resolved and ready for your review @mairaw

2019-08-22 01:47 UTC, mairaw commented
Thanks @nemrism. @rpetrusha I'm afraid this will cause new merge conflicts for #13851. Should we hold off until that one is merged?

2019-08-28 08:29 UTC, nemrism commented
cc @mairaw / @rpetrusha 

Just tested the [v-thepet/move2](https://github.com/v-thepet/docs/tree/move2) branch against this one. It is indeed the most impacted one by merge conflicts but it is quite easy to resolve them.

Let me know when the #13851 PR will be merged, I'll handle the conflicts.

I'll continue to work on the #10653 resolution, it seems that other section are less impacted, automatic merge works fine on most of other related PR.

2019-09-13 20:12 UTC, mairaw commented
That PR was now merged. Can you please rebase your PR? Thanks!

2019-09-14 05:04 UTC, nemrism commented
Yes of course!
I'll prepare that and tell you when this one is ready for final review.

2019-09-16 19:57 UTC, nemrism commented
All done, ready for final review @mairaw

2019-09-16 22:46 UTC, mairaw approved these changes
Changes look good! Thank you @nemrism!

2019-09-16 22:47 UTC, merged