Improve description of dotnet restore --source
dotnet/docs pull request #14015
Opened 2019-08-23 13:09 UTC by jiimaho

## Summary

Tried to make the description very explicit about the fact that the nuget.config file won't be used. Please improve/change further if you want to.

Fixes #Issue_Number (if available)

2019-08-24 19:05 UTC, Thraka commented
Does it actually ignore the whole file? There are a lot of other settings, such as the global packages folder, that I would assume it continues to use.

https://docs.microsoft.com/en-us/nuget/reference/nuget-config-file#example-config-file

@KathleenDollard please comment.

2019-08-25 16:55 UTC, jiimaho commented
Well at least when I tried it doesn't use any of the specified sources in NuGet.Config if the `--source` parameter is provided. However as you say, i'm not sure about the other settings. 

Anyone else knows this?

2019-08-27 11:34 UTC, jiimaho commented on docs/core/tools/dotnet-restore.md
> +Specifies a NuGet package source to use during the restore operation. This overrides all of the sources specified in the *nuget.config* files, practically speaking ignoring the nuget.config file. Mul
Okey, then I understand, and I totally agree that the suggested change by me will be misleading. 

I just think the word "overrides" is a bit misleading by itself. When I read it by myself, one interpretation of it was that it overrides sources _with the same name_, but rest stays as-is, which is wrong.

2019-08-27 11:40 UTC, jiimaho commented on docs/core/tools/dotnet-restore.md
> +Specifies a NuGet package source to use during the restore operation. This overrides all of the sources specified in the *nuget.config* files, practically speaking ignoring the nuget.config file. Mul
I did another update to this PR. Please see if you like it better.

2019-08-27 18:45 UTC, nkolev92 reviewed
This is semantically correct, so from my side, this change is ok.

2019-09-05 04:18 UTC, Thraka approved these changes

2019-09-05 04:19 UTC, Thraka commented on docs/core/tools/dotnet-restore.md
> +Specifies a NuGet package source to use during the restore operation. This overrides all of the sources specified in the *nuget.config* files, effectively reading the NuGet.Config file as if the <pac
```suggestion
Specifies a NuGet package source to use during the restore operation. This overrides all of the sources specified in the *nuget.config* files, effectively reading the *nuget.config* file as if the <packageSource> element was not there. Multiple sources can be provided by specifying this option multiple times.
```

2019-09-05 04:21 UTC, Thraka requested changes
@jiimaho  One minor thing that needs to be fixed

2019-09-09 18:31 UTC, Thraka approved these changes
Thanks!

2019-09-09 18:32 UTC, merged

2019-09-11 17:03 UTC, jiimaho reviewed
Looks good