Updated documentation for Line Continuation Comments and added VB16 V…
dotnet/docs pull request #14018
Opened 2019-08-23 17:10 UTC by paul1956

…S 2019 headings. There may be other VB16 features

## Summary
Added documentation for Comment after Line Continuation which is new in VB 16
Describe your changes here.

Fixes #Issue_Number (if available)

2019-08-23 19:10 UTC, rpetrusha commented
@paul1956, there's a merge conflict; could you resolve it, please. Also, your *.gitignore* file should not be included in your commit.

2019-08-24 18:58 UTC, Thraka requested changes
In addition to what Ron pointed out, I found a few minor fixes if you want to accept them with the button below each one. Thanks!

2019-08-24 18:58 UTC, Thraka commented on docs/visual-basic/programming-guide/program-structure/how-to-break-and-combine-statements-in-code.md
> +-   Use the line-continuation character, which is an underscore (`_`), at the point at which you want the line to break. The underscore must be immediately preceded by a space and immediately followe
```suggestion
-   Use the line-continuation character, which is an underscore (`_`), at the point at which you want the line to break. The underscore must be immediately preceded by a space and immediately followed by a line terminator (carriage return) or starting with language version 16 a comment is allowed after a line continuation..  
```

2019-08-24 18:58 UTC, Thraka commented on docs/visual-basic/getting-started/whats-new.md
> +## Visual Basic 16
Adding spacing around headers.

```suggestion

## Visual Basic 16

```

2019-08-24 18:58 UTC, Thraka commented on docs/visual-basic/getting-started/whats-new.md
> +Visual Basic 15.5 / Visual Studio 2017 Version 15.5
Adding spacing around header
```suggestion

Visual Basic 15.5 / Visual Studio 2017 Version 15.5  
```

2019-08-24 18:58 UTC, Thraka commented on docs/visual-basic/getting-started/whats-new.md
> +Visual Basic 16 / Visual Studio 2019 Version 16.0
Add spacing around header
```suggestion

Visual Basic 16 / Visual Studio 2019 Version 16.0  
```

2019-09-04 22:38 UTC, Thraka commented
@paul1956 Sorry, I was on vacation. I'm back now. Please fix the merge conflicts and then I'll approve this PR. Thanks a bunch!

2019-09-05 03:58 UTC, paul1956 commented
@Thraka The resolve conflict button is disabled. I though I worked with @rpetrusha to resolve the .gitignore Issue and put back the original.

2019-09-05 19:25 UTC, Thraka commented
@paul1956 Sorry for not noticing this earlier, but your copy of the repo you were working out of was a year out of date, which is causing all sorts of conflicts. For example, the current article has the latest version as **Visual Basic 15.8** yet your version lists **Visual Basic 15.5** as the latest (before you added 16). Additionally, the `.vb` file you edited was actually deleted from the repo about 5 months ago.

Again, I do apologize for not spotting this earlier, but it would be easier for you to start over with a fresh copy of the repo. You can do that by deleting your fork on github and recreating it with the fork button at the top of this repo. OR you can open a pull request from this repo into your own updating master. ([here is a link to do that](https://github.com/paul1956/docs/compare/master...dotnet:master?expand=0)) Then, create a **new** working branch (like you did with LineContinuationWithComments) and start fresh.

2019-09-05 19:25 UTC, closed without merging

2019-09-06 01:40 UTC, paul1956 commented
@ThrakaThere is no VB 15.8 that I know of,  VB went from 15.5 to 16.

2019-09-06 03:15 UTC, paul1956 commented
From Roslyn Sosurce, notice no VisualBasic15_8, I think the change you are refering to as 15_8 is a performance improvement but does not change the language in any way.
```VB
    Public Enum LanguageVersion
        [Default] = 0
        VisualBasic9 = 9
        VisualBasic10 = 10
        VisualBasic11 = 11
        VisualBasic12 = 12
        VisualBasic14 = 14
        VisualBasic15 = 15
        VisualBasic15_3 = 1503
        VisualBasic15_5 = 1505
        VisualBasic16 = 1600

        Latest = Integer.MaxValue
    End Enum
        Friend Function GetLanguageVersion(feature As Feature) As LanguageVersion
            Select Case feature
                 ' lines deleted for simplicity
                Case Feature.LeadingDigitSeparator,
                    Feature.NonTrailingNamedArguments,
                    Feature.PrivateProtected
                    Return LanguageVersion.VisualBasic15_5

                Case Feature.UnconstrainedTypeParameterInConditional,
                    Feature.CommentsAfterLineContinuation
                    Return LanguageVersion.VisualBasic16
```