Update anchors-in-regular-expressions.md
dotnet/docs pull request #14012
Opened 2019-08-23 07:36 UTC by noctwolf

## Summary

More accurate description

2019-08-23 07:42 UTC, noctwolf commented
dotnet/docs.zh-cn#437

2019-08-23 19:34 UTC, rpetrusha requested changes
Thanks for making these corrections, @noctwolf. I've suggested one change: "white space" as a noun consists of two words. See #4439.

2019-08-23 19:34 UTC, rpetrusha commented on docs/standard/base-types/anchors-in-regular-expressions.md
> +|`((\w+(\s?)){2,}`|Match one or more word characters followed either by zero or by one space at least two times. This is the first capturing group. This expression also defines a second and third cap
```suggestion
|`((\w+(\s?)){2,}`|Match one or more word characters followed either by zero or by one space at least two times. This is the first capturing group. This expression also defines a second and third capturing group: The second consists of the captured word, and the third consists of the captured white space.|  
```

2019-08-23 21:01 UTC, noctwolf commented
@rpetrusha Thank you for your guidance

2019-08-26 17:56 UTC, rpetrusha approved these changes

2019-08-26 17:56 UTC, merged