Update link from obsolete to current event
dotnet/docs pull request #14081
Opened 2019-08-29 07:34 UTC by ite-klass

The Form.Closing event is obsolete since .NET Framework version 2.0 as
per its documentation.
It has been replaced by the Form.FormClosing event, which we now link to
instead.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-08-29 09:46 UTC, Youssef1313 commented
There is another occurrence in the same paragraph you edited, and also in the `See Also` section.

2019-08-29 10:04 UTC, ite-klass commented
@Youssef1313 good catch. fixed 👍

2019-08-29 19:53 UTC, rpetrusha requested changes
Thank you, @ite-klass, for contributing to the dotnet/docs repo and updating the documentation. I thought that one of the cross-references should also be updated to mention the **FormClosingEventArgs** class.

2019-08-29 19:53 UTC, rpetrusha commented on docs/framework/winforms/user-input-validation-in-windows-forms.md
>  - <xref:System.ComponentModel.CancelEventArgs?displayProperty=nameWithType>
```suggestion
- <xref:System.Windows.Forms.FormClosingEventArgs?displayProperty=nameWithType>
```

2019-08-30 18:50 UTC, rpetrusha approved these changes

2019-08-30 18:51 UTC, rpetrusha commented
Thanks, @ite-klass, for making the additional change. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

2019-08-30 18:51 UTC, merged

2019-09-02 07:40 UTC, ite-klass commented
Thank you