.NET Hub page: Adding a new Getting started tab.
dotnet/docs pull request #14125
Opened 2019-08-31 01:02 UTC by wadepickett

For the .NET Hub page: https://docs.microsoft.com/en-us/dotnet/ 

- Moved the old Get Started content that presented the guides links down one tab (menu item) and renamed it to ".NET Guides"
- Added a link to the Microsoft Learn .NET Modules available.
- Created a new default top tab with content centered on 3 getting started choices and named that "Get Started".  
- Fixed a cap typo left in the previous version of the .md.

2019-08-31 01:11 UTC, wadepickett commented
Setting to WIP while I get a look at this in review...

2019-08-31 01:20 UTC, wadepickett commented
On the new Get Started tab the C# and .NET Core logos need to be displayed at a smaller size.  They fill up the card.  Taking care of that...

2019-08-31 03:09 UTC, wadepickett commented
@mairaw , 
Does this look good to you?
Review link: 
https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-14125#pivot=docs&panel=getstarted

2019-08-31 05:59 UTC, mairaw requested changes
Overall looks great @wadepickett. Left you some comments to address before merging though.

2019-08-31 05:59 UTC, mairaw commented on index.md
> +                        <a href="#dotnetguides">.Net Guides</a>
```suggestion
                        <a href="#dotnetguides">.NET Guides</a>
```

2019-08-31 05:59 UTC, mairaw commented on index.md
> +                                <a href="https://www.asp.net/get-started">
This redirects. Better to have the right target.

```suggestion
                                <a href="https://dotnet.microsoft.com/learn/aspnet/hello-world-tutorial/intro">
```

2019-08-31 16:43 UTC, wadepickett commented
@Maira, your changes committed (thank you)  and I took a look again at the generated preview to verify.  Merge?

2019-08-31 20:27 UTC, wadepickett commented
This fixes #14130

2019-09-03 19:47 UTC, mairaw commented
Fixes keyword need to be in the PR description. I'll add that.

2019-09-03 19:49 UTC, mairaw reviewed
A few more suggestions...

2019-09-03 19:49 UTC, mairaw commented on index.md
> +                                                <p><a href="https://docs.microsoft.com/en-us/learn/browse/?roles=developer&products=dotnet">Hands-on Learn Modules</a></p>
```suggestion
                                                <p><a href="https://docs.microsoft.com/learn/browse/?roles=developer&products=dotnet">Hands-on Learn Modules</a></p>
```

2019-09-03 19:49 UTC, mairaw commented on index.md
> +ms.date: "08/30/2019"
```suggestion
ms.date: "09/03/2019"
```

2019-09-03 19:49 UTC, mairaw commented on index.md
> +                     <li>
removing extra space added 

```suggestion
                    <li>
```

2019-09-11 00:42 UTC, wadepickett commented
@mairaw,
Changes for review for merge here:
https://review.docs.microsoft.com/en-us/dotnet/index?branch=pr-en-us-14125#pivot=docs&panel=dotnetguides

The #dotnetguides tab has been moved to the default (which has to be the top position given the way our landing page works) per the requests in the review.  Thanks again for all the help.

2019-09-11 18:11 UTC, mairaw approved these changes
I think this looks good @wadepickett. Good to merge?

2019-09-11 18:12 UTC, BillWagner commented
This is great.  :shipit:!

2019-09-11 18:24 UTC, merged