Add language identifiers
dotnet/docs pull request #14144
Opened 2019-09-02 11:43 UTC by Youssef1313

- Added some missing language identifiers.
- Fixed some bad indentations.
- Fixed some code that had `Throw` instead of `throw` and `Else` instead of `else` which will cause compile error in C#.

2019-09-03 15:21 UTC, BillWagner requested changes
Overall, this is good @Youssef1313 

I noticed a number of locations where tab characters are modifying the formatting. Can you update those?

2019-09-03 15:21 UTC, BillWagner commented on docs/framework/wcf/extending/how-to-import-custom-wsdl.md
> +	System.Collections.ObjectModel.Collection<ContractDescription> contracts = importer.ImportAllContracts();
The tab character is causing extra indentation on the second line.  I'd suggest the following:

```suggestion
    System.Collections.ObjectModel.Collection<ContractDescription> contracts = importer.ImportAllContracts();  
```

2019-09-03 15:21 UTC, BillWagner commented on docs/framework/wcf/extending/how-to-write-an-extension-for-the-servicecontractgenerator.md
> +	System.Collections.ObjectModel.Collection<ContractDescription> contracts = importer.ImportAllContracts();
Same tab to space conversion:

```suggestion
    System.Collections.ObjectModel.Collection<ContractDescription> contracts = importer.ImportAllContracts();  
```

2019-09-03 15:21 UTC, BillWagner commented on docs/framework/wcf/samples/custom-wsdl-publication.md
> +	    }
Again, a stray tab character:

```suggestion
        }
```

2019-09-03 15:21 UTC, BillWagner commented on docs/framework/wcf/samples/custom-wsdl-publication.md
> +	}
and again:

```suggestion
    }
```

2019-09-03 18:36 UTC, mairaw commented on docs/csharp/programming-guide/concepts/linq/how-to-query-an-arraylist-with-linq.md
>  ...
add the comment here so it becomes "compilable"

```suggestion
//...  
```

2019-09-03 19:35 UTC, mairaw commented
Resolved some merge conflicts after merging someone else's PR

2019-09-10 15:17 UTC, Youssef1313 commented
Fixed other merge conflicts that occurred again.

2019-10-02 22:34 UTC, mairaw commented
There were more merge conflicts since then. Can you please check @Youssef1313?

2019-10-03 05:37 UTC, Youssef1313 commented
@mairaw, Fixed them.

2019-10-10 17:34 UTC, Thraka requested changes
Found a few more code problems that need to be fixed. That weird mix of VB/C# that snuck through at some point.

2019-10-10 17:34 UTC, Thraka commented on docs/framework/wcf/feature-details/how-to-use-configuration-to-add-an-aspnet-ajax-endpoint.md
> +		//Other operations omitted…
Fix indentation here.
```suggestion
        // Other operations omitted…
```

2019-10-10 17:34 UTC, Thraka commented on docs/framework/wcf/feature-details/wcf-web-http-error-handling.md
>  Public string Operation1()
```suggestion
public string Operation1()
```

2019-10-10 17:34 UTC, Thraka commented on docs/framework/wcf/feature-details/wcf-web-http-error-handling.md
>  Public string Operation2()
```suggestion
public string Operation2()
```

2019-10-10 17:34 UTC, Thraka commented on docs/framework/wcf/feature-details/wcf-web-http-error-handling.md
> +   MyErrorDetail detail = new MyErrorDetail
```suggestion
   MyErrorDetail detail = new MyErrorDetail()
```

2019-10-15 21:59 UTC, Thraka approved these changes

2019-10-15 22:40 UTC, mairaw commented on docs/framework/wcf/feature-details/flowing-transactions-into-and-out-of-workflow-services.md
> +
```suggestion

```

2019-10-15 22:40 UTC, mairaw commented on docs/framework/wcf/feature-details/wcf-web-http-error-handling.md
>  {   // Operation logic
```suggestion
{
    // Operation logic  
```

2019-10-15 22:41 UTC, mairaw commented on docs/framework/wcf/feature-details/wcf-web-http-error-handling.md
> +public string Operation2()
```suggestion
public string Operation2()
{
```

2019-10-15 22:44 UTC, mairaw requested changes
Great changes. Left some suggestions @Youssef1313!

2019-10-15 22:44 UTC, mairaw commented on docs/framework/wcf/samples/custom-message-filter.md
>  class MatchEAddressFilter : MessageFilter …
```suggestion
class MatchEAddressFilter : MessageFilter { }
```

2019-10-15 22:44 UTC, mairaw commented on docs/framework/wcf/samples/custom-message-filter.md
>  // Matches any message whose To address does not contain the letter 'e'
could do the same on the line 33 as well

2019-10-15 22:44 UTC, mairaw commented on docs/framework/wcf/samples/custom-message-filter.md
>  public class FilteringEndpointBehaviorExtension : BehaviorExtensionElement
```suggestion
public class FilteringEndpointBehaviorExtension : BehaviorExtensionElement { }
```

2019-10-15 22:44 UTC, mairaw commented on docs/framework/wcf/samples/saml-token-provider.md
>      public class SamlSecurityTokenManager :
```suggestion
    public class SamlSecurityTokenManager : ClientCredentialsSecurityTokenManager
```

2019-10-15 22:44 UTC, mairaw commented on docs/framework/wcf/samples/saml-token-provider.md
>       ClientCredentialsSecurityTokenManager
```suggestion
```

2019-10-23 12:35 UTC, BillWagner approved these changes

2019-10-23 12:36 UTC, BillWagner commented
Thanks for making these updates @Youssef1313 

I'm approving this PR.

@mairaw when you are happy with the changes, this is ready to :shipit:

2019-10-29 14:56 UTC, Youssef1313 commented
Fixed merge conflicts again.

2019-11-07 21:57 UTC, mairaw approved these changes
Thanks @Youssef1313. I've fixed some merge conflicts and we can merge this.

2019-11-07 22:42 UTC, merged