Restore XML hierarchy to WCF configuration section (part 2)
dotnet/docs pull request #14151
Opened 2019-09-02 16:01 UTC by nemrism

Applied XML hierarchy format to WCF configuration section files for:
- `<system.serviceModel.activation><bindings>...</bindings></system.serviceModel.activation>` sub-section

Contributes to #2038 & #2149

2019-09-03 20:33 UTC, rpetrusha requested changes
Thanks, @nemrism, for another PR that improves the formatting of the configuration hierarchy. I've suggested a number of changes, most of them to address broken links.

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/add-of-claimtyperequirements-element.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-wsfederationhttpbinding.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/issuedtokenparameters.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/issuer-of-issuedtokenparameters.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/issuermetadata-of-issuedtokenparameters.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/localclientsettings-element.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/localservicesettings-element.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/message-element-of-ws2007federationhttpbinding.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-ws2007federationhttpbinding.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-element-of-ws2007federationhttpbinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/secureconversationbootstrap.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-custombinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/transport-of-netpeertcpbinding.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-netpeertcpbinding.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<security>**](security-of-netpeerbinding.md)\
```

2019-09-03 20:33 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/xmlelement.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**\<xmlElement>**]
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**\<xmlElement>**  
```

2019-09-03 20:51 UTC, nemrism commented
Thanks for the review and suggested changes @rpetrusha!
I just applied all of the suggested changes.

2019-09-05 16:45 UTC, rpetrusha approved these changes

2019-09-05 16:45 UTC, rpetrusha commented
Thanks, @nemrism, for making these additional changes. I'll merge your PR now.

2019-09-05 16:45 UTC, merged