Restore XML hierarchy to WCF configuration section (part 3)
dotnet/docs pull request #14162
Opened 2019-09-02 21:12 UTC by nemrism

## Summary

Applied XML hierarchy format to WCF configuration section files for:
- `<system.serviceModel.activation><client>...</client></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><comContracts>...</comContracts></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><diagnostics>...</diagnostics></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><protocolMapping>...</protocolMapping></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><routing>...</routing></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><serviceHostingEnvironment>...</serviceHostingEnvironment></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><services>...</services></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><standardEndpoints>...</standardEndpoints></system.serviceModel.activation>` sub-section
- `<system.serviceModel.activation><tracking>...</tracking></system.serviceModel.activation>` sub-section

Contributes to #2038 & #2149

## Remarks

Content of [workflow-for-wcf.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/wcf/workflow-of-wcf.md) file seems a copy-paste of an unaccurate content.

Shouldn't it be replaced with the one form WF section [workflow.md](https://github.com/dotnet/docs/blob/master/docs/framework/configure-apps/file-schema/windows-workflow-foundation/workflow.md) page?

2019-09-03 21:05 UTC, rpetrusha requested changes
Thank you for another PR that improves the formatting of the configuration element hierarchy, @nemrism. I've left a number of suggestions.

2019-09-03 21:05 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/participants-of-wcf.md
> +&nbsp;&nbsp;&nbsp;&nbsp;[**\<tracking>**](tracking-of-wcf.md)\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;[**\<tracking>**](tracking-of-wcf.md)  
```

2019-09-03 21:05 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/policyimporter.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**\<policyImporters>**\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<policyImporters>**](policyimporters.md)  
```

2019-09-03 21:05 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/wsdlimporter.md
> +&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;**\<wsdlImporters>**\
```suggestion
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;[**\<wsdlImporters>**](wsdlimporters.md)  
```

2019-09-03 21:09 UTC, nemrism commented
Thanks again @rpetrusha!
I've just applied them and added the commits to this PR.

2019-09-05 16:46 UTC, rpetrusha approved these changes

2019-09-05 16:47 UTC, rpetrusha commented
Thanks, @nemrism. I've resolved a merge conflict, so I'll merge once our internal build completes successfully.

2019-09-09 19:09 UTC, merged