Corrections to image-classification.md
dotnet/docs pull request #14183
Opened 2019-09-03 20:10 UTC by mstfbl

Corrected the ".tsv" file name to "tags.tsv".
Corrected the method name PairAndDisplayResults() to DisplayResults() as PairAndDisplayResults() was renamed to DisplayResults().

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-09-04 09:05 UTC, Youssef1313 commented
It's not a file name, this is the snippet identifier. I think it should remain tsv.

2019-09-10 00:14 UTC, natke requested changes

2019-09-10 00:14 UTC, natke commented on docs/machine-learning/tutorials/image-classification.md
> +```tags.tsv
```suggestion
```tsv
```

2019-09-10 00:15 UTC, natke commented
Thank you @mstfbl/ I've requested one small change.

2019-09-16 17:58 UTC, natke commented
Will fix as part of AB#1596621

2019-09-16 20:01 UTC, closed without merging