US 1583733 Add missing language IDs - 10
dotnet/docs pull request #14191
Opened 2019-09-03 22:37 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "output" for program output examples.
- Used "console" for csc command line C# compiler examples and snk (strong name tool) commands.
- Used "env" for Environment variable settings.
- Used "text" for examples of assembly reference strings in XML metadata.

2019-09-03 23:23 UTC, mairaw commented
This looks good @v-thpra. I'm putting this one on hold just because it conflicts with a huge PR we have going on for content under the app-domains folder that I'm trying to avoid creating merge conflicts. So we'll deal with the merge conflicts here later on.

2019-09-04 14:49 UTC, BillWagner reviewed
I've reviewed the changes, and everything LGTM.

Once the related PR is merged, and we address any merge conflicts, I'll give it a final review and ship it.

2019-09-13 20:11 UTC, mairaw requested changes
@v-thpra now that the other PR was merged, we have several conflicts. Please rebase your branch. Thanks!

2019-09-13 21:14 UTC, v-thpra commented
@mairaw The conflicts should be fixed now. Thanks.

2019-09-13 21:46 UTC, mairaw commented
I've deleted some of the files that were being reincluded. They were moved to a new location instead.

2019-09-19 16:45 UTC, tfosmark commented
@v-thpra Please make sure Maira's requested changes are marked as Resolved. Thanks!

2019-09-24 22:00 UTC, v-thpra commented
@mairaw I believe all of the changes have been addressed in this PR. It should be ready to merge. Thanks!

2019-09-29 21:58 UTC, mairaw reviewed
Thank you @v-thpra. Left you a few other comments.

2019-09-29 21:58 UTC, mairaw commented on docs/csharp/tour-of-csharp/program-structure.md
> +```output
```suggestion
```console
```

2019-09-29 21:58 UTC, mairaw commented on docs/csharp/versioning.md
> +```output
```suggestion
```console
```

2019-09-29 21:58 UTC, mairaw commented on docs/csharp/versioning.md
> +```output
```suggestion
```console
```

2019-09-29 21:58 UTC, mairaw commented on docs/standard/assembly/enhanced-strong-naming.md
> +    ```text
Let's remove this identifier

2019-09-29 21:58 UTC, mairaw commented on docs/standard/assembly/names.md
> +```text
let's not add an identifier to these two blocks in this article

2019-09-30 17:27 UTC, v-thpra commented on docs/standard/assembly/enhanced-strong-naming.md
> +    ```text
Fixed

2019-09-30 17:34 UTC, v-thpra commented
@mairaw I Implemented your suggestions. Thanks!

2019-10-02 22:50 UTC, mairaw approved these changes
Thank you @v-thpra!

2019-10-02 22:50 UTC, merged