US 1583733 Add missing language IDs - 11
dotnet/docs pull request #14204
Opened 2019-09-04 17:41 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "output" for program output examples.
- Used "env" for Environment variable settings.
- Used "text" for example of base addresses.
- Used "xml" for Syntax examples.

2019-09-19 16:48 UTC, tfosmark commented
@v-thpra Please address the conflict. Thanks!

2019-09-24 22:19 UTC, v-thpra commented
@mairaw Conflicts have been addressed and this PR should be ready to merge. Thanks!

2019-10-28 02:41 UTC, BillWagner commented
We have another new merge conflict. Can you address it?

2019-10-28 16:57 UTC, v-thpra commented
@BillWagner I addressed the conflict. This should be ready for review and merge. Thanks!

2019-10-28 17:15 UTC, Youssef1313 requested changes

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/runtime/compatsortnlsversion-element.md
>   When you run the example on the .NET Framework 4, it displays the following output.
```suggestion
 When you run the example on the .NET Framework 4, it displays the following output:
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/runtime/compatsortnlsversion-element.md
>   This is completely different from the output that is displayed when you run the example on the .NET Framework 3.5.
```suggestion
 This is completely different from the output that is displayed when you run the example on the .NET Framework 3.5:
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf-directive/servicehost.md
>  Factory = "Factory, FactoryNamespace"
```suggestion
Factory = "Factory, FactoryNamespace"
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf-directive/servicehost.md
>  Debug = "Debug"
```suggestion
Debug = "Debug"
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf-directive/servicehost.md
> +%>
```suggestion
%>
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/add-of-baseaddressprefixfilter.md
>   For example, your site can contain the following base addresses.
```suggestion
 For example, your site can contain the following base addresses:
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/baseaddressprefixfilters.md
>   For example, your site can contain the following base addresses.
```suggestion
 For example, your site can contain the following base addresses:
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/commonparameters.md
> +
```suggestion
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/commonparameters.md
>   The following sample code shows how to change the common parameters programmatically.
```suggestion
 The following sample code shows how to change the common parameters programmatically:
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/commonparameters.md
>  Configuration config=WebConfigurationManager.OpenWebConfiguration("/Workflow", "Default Web Site", null, "localhost");
```suggestion
Configuration config = WebConfigurationManager.OpenWebConfiguration("/Workflow", "Default Web Site", null, "localhost");
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/commonparameters.md
>  WorkflowRuntimeSection wfruntime=config.GetSection("WorkflowRuntime") as WorkflowRuntimeSection;
```suggestion
var wfruntime = config.GetSection("WorkflowRuntime") as WorkflowRuntimeSection;  
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/commonparameters.md
>  NameValueConfigurationCollection commonParameters=wfruntime.CommonParameters;
```suggestion
NameValueConfigurationCollection commonParameters = wfruntime.CommonParameters;
```

2019-10-28 17:15 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/windows-identity-foundation/issuertokenresolver.md
>  public override void LoadCustomConfiguration(System.Xml.XmlNodeList nodelist)
The usage of `XmlNode` in the foreach loop indicates that there is already a `using System.Xml;` statement. Which means `System.Xml` is not needed here.

```suggestion
public override void LoadCustomConfiguration(XmlNodeList nodelist)
```

2019-10-28 17:17 UTC, Youssef1313 commented
My suggested changes are all unrelated to your changes.

2019-10-28 17:47 UTC, v-thpra commented
@mairaw  I applied all of the suggested changes from @Youssef1313. Even though they are mostly unrelated to mine, they looked correct.

2019-11-01 07:36 UTC, mairaw requested changes
Great changes @v-thpra. Left a few comments to be addressed.

2019-11-01 07:36 UTC, mairaw commented on docs/framework/configure-apps/file-schema/wcf/add-of-baseaddressprefixfilter.md
> +```text
Let's keep this one without.

2019-11-01 07:36 UTC, mairaw commented on docs/framework/configure-apps/file-schema/wcf/baseaddressprefixfilters.md
> +```text
same here

2019-11-01 16:32 UTC, v-thpra commented
@mairaw Thanks for the suggestions and comments. I implemented them all.

2019-11-07 21:59 UTC, mairaw approved these changes

2019-11-07 21:59 UTC, merged