US 1583733 Add missing language IDs - 18
dotnet/docs pull request #14261
Opened 2019-09-06 18:17 UTC by v-thpra

- Used "cpp" for "unmanaged" function signatures.
- Used "cpp" for the IDL file example.
- Used "console" for tlbimp.exe command examples.
- Used "console" for Mefx command examples, even commands combined with output.
- Used "output" for examples of Mefx command output only.

2019-09-06 19:13 UTC, Youssef1313 commented on docs/framework/interop/how-to-implement-callback-functions.md
> +    `BOOL EnumWindows(WNDENUMPROC lpEnumFunc, LPARAM lParam)`
I think adding an identifier here is better.

2019-09-09 18:39 UTC, rpetrusha requested changes
I've left one suggestion for you to consider, @v-thpra.

2019-09-09 18:39 UTC, rpetrusha commented on docs/framework/interop/how-to-implement-callback-functions.md
> +    ```csharp
```suggestion
    ```cpp
```

2019-09-10 17:41 UTC, rpetrusha approved these changes

2019-09-10 17:41 UTC, rpetrusha commented
I'll merge your PR now. Thanks, Tom.

2019-09-10 17:41 UTC, merged