US 1583733 Add missing language IDs - 19
dotnet/docs pull request #14264
Opened 2019-09-06 20:19 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "output" for exception messages, error messages, and call stack examples.
- Used "console" for PerfView and xperf command examples.
- Used "text" for registry file example.

2019-09-09 18:11 UTC, rpetrusha approved these changes
Thanks, @v-thpra. I left two suggestions for you to consider.

2019-09-09 18:11 UTC, rpetrusha commented on docs/framework/network-programming/interpreting-network-tracing.md
> +`[588]   (4357)   Entering Socket#33574638::Send()`
I think it's best to leave this fenced, as it was, and label it as `output`.

2019-09-09 18:11 UTC, rpetrusha commented on docs/framework/reflection-and-codedom/dynamically-loading-and-using-types.md
>  Imports System
```suggestion
```
The line can be deleted, since it's unnecessary.

2019-09-09 18:28 UTC, rpetrusha requested changes
Sorry, Tom. I meant to request changes rather than approve.

2019-09-09 18:48 UTC, v-thpra commented
Made the changes. Thanks Ron.

2019-09-10 17:42 UTC, rpetrusha approved these changes

2019-09-10 17:43 UTC, rpetrusha commented
Thanks for making the changes, Tom. I'll merge your PR now.

2019-09-10 17:43 UTC, merged