US 1583733 Add missing language IDs - 22
dotnet/docs pull request #14277
Opened 2019-09-06 23:17 UTC by v-thpra

- Used "console" for all Framework tool syntax and command examples.
- Used "csharp" for examples of an assembly and a type library.

2019-09-06 23:45 UTC, rpetrusha requested changes
Thanks for adding these language identifiers, @v-thpra. I've suggested some changes.

2019-09-06 23:45 UTC, rpetrusha commented on docs/framework/tools/tlbexp-exe-type-library-exporter.md
> +```csharp
```suggestion
```cpp
```

2019-09-06 23:45 UTC, rpetrusha commented on docs/framework/tools/tlbexp-exe-type-library-exporter.md
> +```csharp
```suggestion
```cpp
```

2019-09-06 23:45 UTC, rpetrusha commented on docs/framework/tools/tlbimp-exe-type-library-importer.md
> +```console
```suggestion
```cpp
```

2019-09-06 23:45 UTC, rpetrusha commented on docs/framework/unmanaged-api/guid-managedname-attribute.md
> +```csharp
```suggestion
```cpp
```

2019-09-06 23:45 UTC, rpetrusha commented on docs/framework/unmanaged-api/guid-managedname-attribute.md
> +```csharp
```suggestion
```idl
```

2019-09-07 00:02 UTC, v-thpra commented on docs/framework/unmanaged-api/guid-managedname-attribute.md
> +```csharp
Thanks for reviewing these, Ron!

2019-09-09 15:35 UTC, rpetrusha requested changes
Sorry, Tom. I seem to have missed two

2019-09-09 15:35 UTC, rpetrusha commented on docs/framework/tools/tlbexp-exe-type-library-exporter.md
> +```cpp
```suggestion
```csharp  
```

2019-09-09 15:35 UTC, rpetrusha commented on docs/framework/unmanaged-api/guid-managedname-attribute.md
> +```csharp
```suggestion
```idl
```

2019-09-09 16:38 UTC, v-thpra commented
Made the changes. Thanks for catching those, Ron.

2019-09-10 17:26 UTC, rpetrusha approved these changes

2019-09-10 17:27 UTC, rpetrusha commented
Thanks for the changes, Tom. I'll merge your PR now.

2019-09-10 17:27 UTC, merged