Add missing cell in table
dotnet/docs pull request #14291
Opened 2019-09-08 08:52 UTC by Youssef1313

Found the label1 text in the [designer file](https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_CLR/CryptoWalkThru/vb/Form1.Designer.vb#L132)

2019-09-09 18:06 UTC, rpetrusha requested changes
Changing the cell value to "Key not set" implies that that's the value of the label's text property. It's best to leave it blank, as it was, or change it to something that differs in appearance from the text properties that should be set, such as **\<not set>**.

2019-09-09 19:46 UTC, Youssef1313 commented
@rpetrusha, The value is **indeed** the literal string `"Key not set"`.

![image](https://user-images.githubusercontent.com/31348972/64561508-3bc0a680-d34b-11e9-843d-81143d59874c.png)

2019-09-10 17:53 UTC, rpetrusha commented
Sorry, @Youssef1313. I'd completely overlooked line 132. I'll approve and merge your PR now. Thanks for making this correction.

2019-09-10 17:53 UTC, rpetrusha approved these changes

2019-09-10 17:53 UTC, merged