US 1583733 Add missing language IDs - 27
dotnet/docs pull request #14345
Opened 2019-09-10 19:38 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- For .svc files, I used single-tick for one line examples, and "text" for multi-line.  
- Used "console" for command-line tool examples (Svcutil.exe, Appcmd.exe. findprivatekey.exe, icacls.exe).

Contributes to #2192

2019-09-10 23:55 UTC, mairaw requested changes
Thank you @v-thpra! A few suggestions before we merge.

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-create-a-wcf-service-that-communicates-over-websockets.md
> +```text
I think it's better not to add anything to svc content

```suggestion
```
```

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-exchange-messages-within-a-reliable-session.md
> +   `<%@ServiceHost language=c# Service="CalculatorService" %>`
I'd not change because people then cannot copy and paste

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-host-a-wcf-service-in-iis.md
> +    `<%@ServiceHost language=c# Debug="true" Service="Microsoft.ServiceModel.Samples.CalculatorService"%>`
same here. just leave these without id.

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-host-a-wcf-service-in-was.md
> +    `<%@ServiceHost language=c# Service="CalculatorService" %>`
ditto

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-register-and-configure-a-service-moniker.md
```suggestion
```

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-register-and-configure-a-service-moniker.md
> +    ```vb
```suggestion
    ```
```

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-register-and-configure-a-service-moniker.md
> +    ```vb
```suggestion
    ```
```

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-replace-the-wcf-url-reservation-with-a-restricted-reservation.md
> +```console
```suggestion
```
```

2019-09-10 23:55 UTC, mairaw commented on docs/framework/wcf/feature-details/how-to-use-configuration-to-add-an-aspnet-ajax-endpoint.md
> +    ```text
```suggestion
    ```
```

2019-09-11 17:56 UTC, v-thpra commented
Thanks for the careful review @mairaw!

2019-09-12 21:22 UTC, mairaw approved these changes
Made a few minor changes but it's good to merge. Thanks!

2019-09-12 22:33 UTC, merged