US 1583733 Add missing language IDs - 28
dotnet/docs pull request #14348
Opened 2019-09-10 21:20 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "console" for command-line tool examples (Svcutil.exe, ComSvcConfig.exe).
- Used "text" for HTTP response example.
- Used "xml" for SOAP 1.x examples.

Contributes to #2192

2019-09-10 23:46 UTC, mairaw requested changes
Great changes @v-thpra! Left a couple of suggestions for two articles where I think we might leave the code blocks with no identifier.

2019-09-10 23:46 UTC, mairaw commented on docs/framework/wcf/feature-details/http-post-and-http-get-requests-for-aspnet-ajax-endpoints.md
> +    ```text
I'd not add here

```suggestion
    ```
```

2019-09-10 23:46 UTC, mairaw commented on docs/framework/wcf/feature-details/messaging-protocols.md
> +        ```xml
All of these entries on this page are not really xml. Maybe leave without id?

```suggestion
        ```
```

2019-09-11 17:17 UTC, v-thpra commented
Thanks for the careful review, and great feedback @mairaw! I left "xml" on the larger soap/xml examples because it seemed a close enough fit. However, if it just doesn't seem right to you, then it's no problem to take them off too.

2019-09-11 19:40 UTC, mairaw commented
I think I'd still remove those.

2019-09-11 20:12 UTC, v-thpra commented
Fixed them. Thanks @mairaw.

2019-09-11 21:26 UTC, HongGit approved these changes

2019-09-13 21:39 UTC, mairaw approved these changes

2019-09-13 21:39 UTC, merged