Remove redundant path segments
dotnet/docs pull request #14419
Opened 2019-09-13 15:59 UTC by Youssef1313

- Removed redundant path segments.
- Added language identifier.
- Removed extraspaces.

2019-09-24 00:13 UTC, rpetrusha requested changes
No, the note is not correct, @Youssef1313. I think that it was true of VB in .NET Framework 2.0, but changed in VB in .NET Framework 3.5.  You can remove the note.

2019-09-24 05:29 UTC, Youssef1313 commented
> No, the note is not correct, @Youssef1313. I think that it was true of VB in .NET Framework 2.0, but changed in VB in .NET Framework 3.5. You can remove the note.

Already removed it

2019-09-26 17:46 UTC, rpetrusha approved these changes

2019-09-26 17:47 UTC, rpetrusha commented
Thanks, @Youssef1313. I've (hopefully) corrected a broken link and approved your PR. We'll merge when the build completes successfully.

2019-09-26 18:33 UTC, merged