fix: Replace vb on vbc/cl/csc/svcutil code fences
dotnet/docs pull request #14431
Opened 2019-09-14 05:18 UTC by nschonni

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-09-16 14:04 UTC, Thraka requested changes
Looks great! One minor change. These format of code example where the parameters are broken up into italic/bold to indicate something is no longer used. It was ported from MSDN. I've fixed that one.

2019-09-16 14:04 UTC, Thraka commented on docs/standard/assembly/sign-strong-name.md
> +**al** **/out:**\<*assemblyName*> *\<moduleName>* **/keyfile:**\<*keyfileName*>
```suggestion
`al /out:\<assemblyName> \<moduleName> /keyfile:\<keyfileName>`
```

2019-09-16 18:00 UTC, mairaw commented on docs/framework/app-domains/build-multifile-assembly.md
> +   ```console
If we change these to console, all three will show up for any selected language and confuse costumers.

2019-09-16 18:01 UTC, mairaw requested changes
I'm still not sure if changing to console on the multi-language topics is the right thing to do.

2019-09-18 03:23 UTC, mairaw commented on docs/framework/app-domains/build-multifile-assembly.md
> +   ```console
yeah, to change that to console, we'd have to use tabs. not sure if it's worth it in these topics.
There's no support for double identifiers.

2019-09-18 16:00 UTC, closed without merging