WcfTestClient.exe tool availability
dotnet/docs pull request #14454
Opened 2019-09-16 06:58 UTC by Vasistan

This tool won't be available by default in Visual Studio install, we have to select the option explicitly

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-09-16 14:35 UTC, Thraka requested changes

2019-09-16 14:35 UTC, Thraka commented on docs/framework/wcf/wcf-test-client-wcftestclient-exe.md
> +This WcfTestClient.exe only available by selecting the Windows Communication Foundation (under Development activities of VS installer)
The https://docs.microsoft.com/en-us/dotnet/framework/wcf/using-the-wcf-development-tools article notes this with the following note block. I've edited your contribution to match that note.

```suggestion

[!NOTE] Starting with Visual Studio 2017, the WCF development tools are not installed by default. In order to use these features, you must ensure the Windows Communication Foundation component is selected in the Visual Studio installer.
```

2019-09-16 14:35 UTC, Thraka commented on docs/framework/wcf/wcf-test-client-wcftestclient-exe.md
> +## Prerequisite
```suggestion
## Prerequisites
```

2019-11-22 23:50 UTC, mairaw commented
@Vasistan can you apply @Thraka's suggestions?

2020-02-19 20:42 UTC, tdykstra commented
Closing the PR. @Vasistan when you have time to address the comments, you can reopen this PR with new content.

2020-02-19 20:42 UTC, closed without merging