Add missing identifier, use pascal case for method
dotnet/docs pull request #14464
Opened 2019-09-16 18:44 UTC by Youssef1313

2019-09-17 12:14 UTC, Youssef1313 commented on docs/visual-basic/language-reference/statements/for-each-next-statement.md
> +    Next
The `element` is indeed optional after the `Next`. but this change isn't really to show that. It's useless, and most of the code in docs doesn't put anything after `Next`.

2019-09-17 15:25 UTC, KathleenDollard commented
@Youssef1313 You make a good point that the element is optional, but this is the one case where I think it's helpful to include it to clarify the syntax notation.  People sometimes struggle with that notation. 

I can see several approaches that would do both:

- Add a comment in the code that the element is optional
- Add a sentence to the following paragraph that the element is optional
- Add a new explanatory paragraph and give the sample twice - once with and once without the element

I tend away from the last, but could support any of these approaches.

2019-09-17 16:17 UTC, Youssef1313 commented
@KathleenDollard, If it doesn't look good to just remove it, then in my opinion keeping it without any changes is better to avoid the repetition of a piece information that was mentioned already in the start of the article.

2019-09-17 16:21 UTC, KathleenDollard commented
@Youssef1313 I don't want to make the change you propose. I believe the presence of `thisControl` is important to clarify the syntax notation. 

But this caught your eye for a reason. Is there a different way you can make that point? Or do you just want to close this issue?

2019-09-17 16:23 UTC, Youssef1313 commented
> 
> 
> @Youssef1313 I don't want to make the change you propose. I believe the presence of `thisControl` is important to clarify the syntax notation.
> 
> But this caught your eye for a reason. Is there a different way you can make that point? Or do you just want to close this issue?

I may just revert this specific change and keep the other changes.

2019-09-24 00:01 UTC, rpetrusha requested changes
In addition to the other comments, @Youssef1313, I thought that the For Each statement could be shortened by taking advantage of type inference.

2019-09-26 17:49 UTC, rpetrusha commented
Thanks,, @Youssef1313. I'll merge your PR now.

2019-09-26 17:49 UTC, rpetrusha approved these changes

2019-09-26 17:49 UTC, merged