US 1583733 Add missing language IDs - 40
dotnet/docs pull request #14466
Opened 2019-09-16 21:03 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "console" for commands to F# Interactive.
- Used "console" for program output displayed on the console.

Contributes to #2192

2019-09-16 21:06 UTC, mairaw commented
@cartermp do you mind validating those are the right identifiers for the F# content?

2019-09-17 04:09 UTC, cartermp requested changes
Small suggested change

2019-09-17 04:09 UTC, cartermp commented on docs/fsharp/language-reference/attributes.md
>  *property-name* = *property-value*
```suggestion
property-name = property-value
```

2019-09-17 04:09 UTC, cartermp commented on docs/fsharp/language-reference/attributes.md
> -```
Please add as `fsharp` in conjunction with suggested change

2019-09-17 04:09 UTC, cartermp commented on docs/fsharp/language-reference/attributes.md
> -```
Please add back in conjunction with suggested change

2019-09-17 16:29 UTC, v-thpra commented
@cartermp Made the change. Thanks! that's a good solution.

2019-09-17 16:33 UTC, cartermp approved these changes

2019-09-17 22:10 UTC, merged