Update Windows pre-reqs article for 3.0 release
dotnet/docs pull request #14555
Opened 2019-09-20 19:51 UTC by mairaw

Contributes to #14217 

I still need to add the screenshots for VS 2019 but you can review the text already

2019-09-20 22:25 UTC, jamshedd requested changes

2019-09-20 22:25 UTC, jamshedd commented on docs/core/windows-prerequisites.md
> +## Prerequisites with Visual Studio
Is "with" the right word here?

2019-09-20 22:25 UTC, jamshedd commented on docs/core/windows-prerequisites.md
> +You can use any editor to develop .NET Core applications using the .NET Core SDK. Visual Studio provides an integrated development environment for .NET Core apps on Windows.
Should we qualify Visual Studio as "Visual Studio 2017 or later". That's protection against someone assuming an older version like VS 2015 could be used for Core development.

2019-09-21 00:40 UTC, mairaw commented
Thanks @jamshedd. I've addressed your feedback.

2019-09-21 01:36 UTC, mairaw commented
I have a related question. If you try to target .NET Core 3.0 in a VS version that isn't supported, you get a build error with the error code NETSDK1045. 

That error message doesn't have any topic associated with a doc right now:
https://docs.microsoft.com/en-us/visualstudio/index?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1045)%26rd%3Dtrue&view=vs-2019

Should I add that keyword to this topic?

2019-09-21 20:27 UTC, jamshedd commented
> I have a related question. If you try to target .NET Core 3.0 in a VS version that isn't supported, you get a build error with the error code NETSDK1045.
> 
> That error message doesn't have any topic associated with a doc right now:
> https://docs.microsoft.com/en-us/visualstudio/index?f1url=https%3A%2F%2Fmsdn.microsoft.com%2Fquery%2Fdev16.query%3FappId%3DDev16IDEF1%26l%3DEN-US%26k%3Dk(NETSDK1045)%26rd%3Dtrue&view=vs-2019
> 
> Should I add that keyword to this topic?

Yes you can, additionally I would consider pointing a user that gets the error to the SDK version selection article: https://docs.microsoft.com/en-us/dotnet/core/versions/selection

2019-09-23 15:56 UTC, rpetrusha approved these changes
I've left a couple of comments for you to consider, @mairaw.

2019-09-23 15:56 UTC, rpetrusha commented on docs/core/windows-prerequisites.md
> +If you want your existing projects to use the latest .NET Core runtime, retarget existing .NET Core projects to .NET Core 3.0 using the following instructions:
Perhaps make it clearer that this is a per-project setting (e.g., retarget each existing .NET Core project...)

2019-09-23 22:26 UTC, Thraka commented
@mairaw Did you get a screenshot? I was doing this same update but I can revert mine since yours seems more detailed. 

Screenshot I was going to use: https://github.com/dotnet/docs/blob/2bb2107901735265b8c0958bbfbd9d4dd5de56c1/docs/core/media/windows-prerequisites/vs-2019-workloads.png

2019-09-23 22:32 UTC, mairaw commented
Yes, I did add a screenshot. Similar to the one we had before:
https://github.com/dotnet/docs/blob/625d95a99165c12edb5088ac2be944c667a967d8/docs/core/media/windows-prerequisites/vs-2019-workloads.jpg

2019-09-23 22:33 UTC, mairaw commented
I was ready to merge this. If you want, you can help with the macOS version. Let me know.

2019-09-23 22:35 UTC, merged

2019-09-23 22:41 UTC, Thraka commented
My PR did some stuff to the macOS article. I'll remove the window article from my PR