Fix figure numbers in ch1
dotnet/docs pull request #14556
Opened 2019-09-20 20:10 UTC by ardalis

## Summary

Updated figure numbers in first chapter.

2019-09-20 21:36 UTC, mvelosop reviewed
Hi @ardalis just a micro issue I fixed locally for generation.

2019-09-20 21:36 UTC, mvelosop commented on docs/architecture/cloud-native/definition.md
> +Figure 1.8 shows the separation across the deployment process.
minor-minor issue
```suggestion
Figure 1-8 shows the separation across the deployment process.
```

2019-09-20 21:43 UTC, mairaw requested changes
Looks good. Left a few comments in addition to the ones from @mvelosop.

2019-09-20 21:43 UTC, mairaw commented on docs/architecture/cloud-native/definition.md
> +**Figure 1-3**. Cloud-native foundational pillars
```suggestion

**Figure 1-3**. Cloud-native foundational pillars
```

2019-09-20 21:43 UTC, mairaw commented on docs/architecture/cloud-native/definition.md
> +**Figure 1-7**. Common backing services
```suggestion

**Figure 1-7**. Common backing services
```

2019-09-20 21:43 UTC, mairaw commented on docs/architecture/cloud-native/candidate-apps.md
> +**Figure 1-10**. Strategies for migrating legacy workloads
```suggestion

**Figure 1-10**. Strategies for migrating legacy workloads
```

2019-09-20 21:43 UTC, mairaw commented on docs/architecture/cloud-native/definition.md
> +**Figure 1-8**. Deployment steps in a CI/CD Pipeline
```suggestion

**Figure 1-8**. Deployment steps in a CI/CD Pipeline
```

2019-09-30 13:29 UTC, ardalis commented
Hopefully all set now.

2019-10-04 08:28 UTC, mvelosop commented
@ardalis, I'm a bit confused or perhaps I'm missing something. Did you mean to close this PR so as not to apply the changes?

2019-10-04 12:02 UTC, ardalis commented
No, I must have hit the wrong button with my last comment.

2019-10-11 21:28 UTC, mairaw approved these changes
LGTM. Thanks @ardalis!

2019-10-11 21:28 UTC, merged