US 1583733 Add missing language IDs - 46
dotnet/docs pull request #14669
Opened 2019-09-25 20:13 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "vb" for syntax examples of VB operators. 

Contributes to #2192

2019-09-27 21:44 UTC, rpetrusha requested changes
Thanks for adding these language identifiers, @v-thpra. I've left two suggestions unrelated to your PR that I think make the syntax clearer.

2019-09-27 21:44 UTC, rpetrusha commented on docs/visual-basic/language-reference/operators/addition-operator.md
>  + expression1
```suggestion
+expression1  
```

2019-09-27 21:44 UTC, rpetrusha commented on docs/visual-basic/language-reference/operators/subtraction-operator.md
>  – expression1
```suggestion
–expression1  
```

2019-09-27 22:32 UTC, v-thpra commented
@rpetrusha Thanks for the review. I implemented your suggestions.

2019-09-30 16:41 UTC, rpetrusha commented
Thanks, @v-thpra. I'll merge now.

2019-09-30 16:41 UTC, rpetrusha approved these changes

2019-09-30 16:41 UTC, merged