Update targets supported by Polly
dotnet/docs pull request #14710
Opened 2019-09-26 20:20 UTC by reisenberger

## Summary

Updates the target frameworks quoted as supported by Polly, to reflect the latest 

Reference: https://github.com/App-vNext/Polly/wiki/Supported-targets

(Contributor reference: I'm the lead Polly maintainer.)

2019-09-27 04:39 UTC, mairaw requested changes
Thanks @reisenberger. I left one suggestion unrelated to your change to fix some branding issues but I also have some questions. Should we mention .NET Standard support is from 1.0 through 2.0 or do you prefer to cover only current? Should we also mention 3.5 support?

2019-09-27 04:39 UTC, mairaw commented on docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md
> +Polly is a .NET library that provides resilience and transient-fault handling capabilities. You can implement those capabilities by applying Polly policies such as Retry, Circuit Breaker, Bulkhead Is
```suggestion
Polly is a .NET library that provides resilience and transient-fault handling capabilities. You can implement those capabilities by applying Polly policies such as Retry, Circuit Breaker, Bulkhead Isolation, Timeout, and Fallback. Polly targets .NET Framework 4.x and the .NET Standard 1.1 and 2.0 (which supports .NET Core).
```

2019-09-28 07:03 UTC, reisenberger commented
Thanks for the good questions around supported Polly targets. 

>Should we mention .NET Standard support is from 1.0 through 2.0 or do you prefer to cover only current? 

I pushed a commit to incorporate this (happy also if you want to reword it).

>Should we also mention 3.5 support?

FWIW my feeling is that it probably isn't necessary (against the downside that mentioning .NET 3.5 could make Polly look outdated).  Statistically, we have only had one request around .NET3.5 support in Polly over the last 3 years.

2019-09-30 07:11 UTC, nishanil approved these changes
LGTM.

2019-09-30 07:13 UTC, mairaw commented on docs/architecture/microservices/implement-resilient-applications/implement-http-call-retries-exponential-backoff-polly.md
> +Polly is a .NET library that provides resilience and transient-fault handling capabilities. You can implement those capabilities by applying Polly policies such as Retry, Circuit Breaker, Bulkhead Is
```suggestion
Polly is a .NET library that provides resilience and transient-fault handling capabilities. You can implement those capabilities by applying Polly policies such as Retry, Circuit Breaker, Bulkhead Isolation, Timeout, and Fallback. Polly targets .NET Framework 4.x and .NET Standard 1.0, 1.1, and 2.0, which supports .NET Core.
```

2019-09-30 07:14 UTC, mairaw commented
Looks good @reisenberger. Made just one more suggestion.

2019-10-01 19:46 UTC, reisenberger commented
Ah, the Oxford comma! Thanks for picking that up, committed. Thanks again @mairaw @nishanil  for taking the time to review and accept this.

2019-10-14 17:33 UTC, mairaw approved these changes
Thank you @reisenberger!

2019-10-14 17:33 UTC, merged