US 1583733 Add missing language IDs - 53
dotnet/docs pull request #14719
Opened 2019-09-26 22:52 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "console" for sample program output displayed on the console.
- Used "xml" for sample program output that is mostly XML with some text.

Contributes to #2192

2019-09-27 06:08 UTC, mairaw requested changes
Thanks @v-thpra. A few suggestions.

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-filter-on-an-attribute-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-a-child-element-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-a-list-of-child-elements-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-a-union-of-two-location-paths-xpath.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-descendant-elements-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-elements-in-a-namespace.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-elements-with-a-specific-attribute.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-preceding-siblings-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-related-elements-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 06:08 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-find-sibling-nodes-xpath-linq-to-xml.md
> +```xml
```suggestion
```console
```

2019-09-27 17:27 UTC, v-thpra commented
@mairaw Thanks for the review suggestions! I implemented them all.

2019-09-28 00:04 UTC, rpetrusha submitted a review, later dismissed
This looks good, @v-thpra. I'll merge now.

2019-10-03 22:53 UTC, rpetrusha commented
I think that this is ready to merge once you approve, @maira.

2019-10-09 23:48 UTC, mairaw approved these changes
Looks good. Thanks!

2019-10-09 23:48 UTC, merged