Added Intro, removed TODO
dotnet/docs pull request #14723
Opened 2019-09-27 02:27 UTC by OzBob

Updated Description using text from Mark's article
Made 'UPDATE THIS' notes non-public comments for editors only - I'm still learning MD so I hope that syntax works ...

## Summary

removed TODO and UPDATETHIS

Fixes #Issue_Number (if available)

2019-09-27 13:54 UTC, ThatRendle approved these changes

2019-09-29 19:30 UTC, mairaw requested changes
Thanks @OzBob. Left some suggestions.

2019-09-29 19:30 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
> +Helping machines communicate with each other has been one of the primary preoccupations of the digital age.
Maybe a simpler language?

```suggestion
Helping machines communicate with each other has been one of the main concerns of the digital age. 
```

2019-09-29 19:30 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
> +The popular framework 'gRPC' is a natural choice for new apps and WCF apps moving to .NET Core.  This is a short introduction to building gRPC Services in ASP.NET Core 3.0 and offers guidance for mig
```suggestion
The popular framework gRPC is a natural choice for new apps and existing WCF apps moving to .NET Core.  This book is a short introduction to building gRPC services in ASP.NET Core and offers guidance for migrating an existing WCF application to gRPC.
```

2019-09-29 19:30 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
> +[//]: #(UPDATE THIS)
Should we just remove this?

```suggestion
```

2019-09-29 19:30 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
```suggestion
```

2019-09-29 19:30 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
> +[//]: #(UPDATE THIS)
```suggestion
```

2019-09-29 19:30 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
```suggestion
```

2019-10-04 17:18 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/index.md
> +[//]: #(UPDATE THIS)
Still unclear why these are still here.

2019-10-22 07:57 UTC, mairaw commented
@OzBob can you please address my questions? @markrendle @shirhatti what was the plan for these two sections?

2019-10-25 14:46 UTC, nishanil commented
I emailed @markrendle. He is planning to address it this weekend.

2019-10-31 09:59 UTC, mvelosop commented
Closing this PR as it's beeing replaced with https://github.com/dotnet/docs/pull/15586

2019-10-31 09:59 UTC, closed without merging