US 1583733 Add missing language IDs - 54
dotnet/docs pull request #14721
Opened 2019-09-26 23:08 UTC by v-thpra

US 1583733 - Fix CATS P1 issues by adding missing language IDs to code blocks.
- Used "console" for sample program output displayed on the console.
- Used "csv" for example of csv input to a sample program.
- Used "xml" for sample program output that is mostly XML with some text.

Contributes to #2192

2019-09-27 04:48 UTC, Youssef1313 commented on docs/visual-basic/programming-guide/concepts/linq/how-to-project-an-anonymous-type.md
> +```xml
I don't think xml is correct here.

2019-09-27 04:49 UTC, Youssef1313 commented on docs/visual-basic/programming-guide/concepts/linq/how-to-retrieve-the-value-of-an-attribute-linq-to-xml.md
> +```xml
I don't think xml is correct here too.

2019-09-27 06:02 UTC, mairaw approved these changes
Thanks @v-thpra. Left a few suggestions.

2019-09-27 06:02 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-retrieve-the-value-of-an-attribute-linq-to-xml.md
> +```xml
```suggestion
```console  
```

2019-09-27 06:02 UTC, mairaw requested changes
Oops, clicked the wrong button...

2019-09-27 17:06 UTC, v-thpra commented
@mairaw Thanks for the review! I implemented your changes.

2019-10-12 08:15 UTC, mairaw approved these changes
Thank you @v-thpra!

2019-10-12 08:15 UTC, merged