Changing some docs for RC3
dotnet/docs pull request #1474
Opened 2017-01-31 08:09 UTC by blackdwarf

Some of the docs had outdated syntax so that is now updated. Added the
<PackageFallbackTarget> to the csproj reference. More work is needed to
get the docs up to date completely especially given the new CRUD
commands.

2017-01-31 08:40 UTC, blackdwarf commented
Also added the dotnet clean command. I plan to maybe add other commands as well, such as CRUD commands.

2017-01-31 08:54 UTC, mairaw requested changes
Thanks for doing this. Left a couple of comments for the dotnet-clean topic

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +ms.date: 10/12/2016
use today's date is 01/31/2017

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +`-v|--verbosity [Quiet|Minimal|Normal|Diag]
missing backtick in the end of the sentence

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +> [!WARNING]
you could just include the warning like this:
`[!INCLUDE[preview-warning](../../../includes/warning.md)]`

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +#dotnet-clean (Tooling )
we're not adding any version when the command only exists in the csproj version

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +dotnet-clean -- Cleans the output of a project
dotnet-clean inside backticks and add the missing period in the end of the sentence.

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +    [--configuration]  [--runtime] [--verbosity]
does --runtime really an option here?

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +The `dotnet clean` command will clean the output of the previous build. It is implemented as an MSBuild target, so the project will get evaluated. Only the outputs that were created during the build
avoid future tense

2017-01-31 08:54 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +The framework that was specified for the build that is cleaned. If you didn't specify this property during build time, you don't have to specify it for clean. The framework needs to be defined in the
The framework that was specified for the build that is cleaned -> this reads a bit strange

2017-01-31 18:32 UTC, blackdwarf commented on docs/core/preview3/tools/dotnet-clean.md
> +> [!WARNING]
This is existing, so will not change.

2017-01-31 18:40 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +> [!WARNING]
not sure what you mean @blackdwarf. adding that line would add the warning similar to the dotnet nuget commands that only exist in csproj: https://review.docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/dotnet-nuget-delete?branch=pr-en-us-1474

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/deploying/index.md
> +\  <PropertyGroup>
Typo: an extraneous "\"

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
>  `<Version>` specifies the version of the package to restore. The element respects the rules of the NuGet versioning scheme.
Conventionally, attributes aren't bracketed -- 'Version' instead of '<Version>'. You've left them bracketed here throughout your changes.

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +`<IncludeAssets>` attribute specifies what assets belonging to the package specified by `<PackageReference>` should be
"The `IncludeAssets` attribute specifies", or just "`IncludeAssets` specifies"

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +`<ExcludeAssets>` attribute specifies what assets belonging to the package specified by `<PackageReference>` should not
just "`ExcludeAssets` specifies..."

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +`<PrivateAssets>` attribute specifies what assets belonging to the package specified by `<PackageReference>` should be
`PrivateAssets` specifies

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
>  `<DotnetCliToolReference>` element specifies the CLI tool that the user wants restores in the context of the project. It is
`DotnetCliToolReference` specifies...

that the user wants restores --> that the user wants to restore?, to restore?

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +`<Version>` specifies the version of the package to restore. The attribute respect the rules of the NuGet versioning scheme.
`Version`
respect --> respects

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +### RuntimeIdentifier
A syntax block would be helpful, along with a usage example with a few RIDs.

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +The `<RuntieIdentifier>` elements allows you to specify only one [Runtime Identifier (RID)](../../rid-catalog.md) for the project. RIDs enable publishing a self-contained deployment.
elements --> element

Here also, syntax and a usage example would be helpful.

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +The `<PackageTargetFallback>` property allows you to specify a set of compatible targets to be used when restoring packages. They are designed to allow packages that use the dotnet TxM to operate wit
property --> element

"They are designed" --> "It is designed"

"is using the dotnet TxM" --> "uses the dotnet TxM,"

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +Below is an example of providing the fallbacks for all of the targets in your project:
The following example provides the fallbacks...

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/csproj.md
> +This example specifies the fallbacks only for `netcoreapp1.0` target:
The following example specifies the fallbacks only for the `netcoreapp1.0` target:

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/dotnet-clean.md
> +ms.date: 10/12/2016
I think that you should use today's date on the other files as well.

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/dotnet-clean.md
> +The framework that was specified for the build that is cleaned. If you didn't specify this property during build time, you don't have to specify it for clean. The framework needs to be defined in the
Perhaps "The framework whose build is to be cleaned"?

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/dotnet-clean.md
> +The framework that was specified for the build that is cleaned. If you didn't specify this property during build time, you don't have to specify it for clean. The framework needs to be defined in the
"at build time" reads a bit better than "during build time" throughout.

2017-01-31 18:43 UTC, rpetrusha commented on docs/core/preview3/tools/dotnet-clean.md
> +Clean a project built using Release configuration:
Release --> the Release

2017-02-01 19:06 UTC, blackdwarf commented on docs/core/preview3/deploying/index.md
> +\  <PropertyGroup>
good catch. Fixed.

2017-02-01 19:44 UTC, rpetrusha commented
@blackdwarf It occurs to me that one of the things missing from the documentation for the XML elements is their parent element, if they are nested.

2017-02-02 00:23 UTC, blackdwarf commented
@rpetrusha well, in MSBuild parlance, most of these are either properties or items, so by saying that we say that their parent element is either `<PropertyGroup>` or `<ItemGroup>`.

2017-02-02 00:51 UTC, rpetrusha commented
@blackdwarf But I'm not sure that customers who are beginning to use MSBuild-based project files for the first time will understand that. It just seems like a basic reference item that should be present.

2017-02-02 18:09 UTC, blackdwarf commented
@rpetrusha I'm pretty sure that this is not the place to educate them on that. There is a link at the top of the article which points them to the general docs about how MSBuild works.

2017-02-02 18:27 UTC, blackdwarf commented on docs/core/preview3/tools/csproj.md
>  `<DotnetCliToolReference>` element specifies the CLI tool that the user wants restores in the context of the project. It is
Fixed.

2017-02-04 20:02 UTC, blackdwarf commented
@mairaw is this good to go?

2017-02-06 04:33 UTC, mairaw approved these changes

2017-02-06 04:34 UTC, mairaw commented
You've addressed my last comment. ms.date should be updated to reflect the docs have been updated as well.

2017-02-06 04:40 UTC, mairaw requested changes
decided to double check the topics on staging. found some things to address before merging plus the ms.date I've mentioned.

2017-02-06 04:40 UTC, mairaw commented on docs/core/preview3/tools/csproj.md
> +### IsPackable
this is not looking good on the built topic. probably would be better to just have a simple list for now until we describe these, correct?

2017-02-06 04:40 UTC, mairaw commented on docs/core/preview3/tools/dotnet-clean.md
> +> This topic applies to Visual Studio 2017 RC - .NET Core Tools TODO:addtoolingstring
leftover todo here. use the warning we're using in the dotnet-nuget commands.

2017-02-07 15:02 UTC, blackdwarf commented
@mairaw all things should be good now, providing the build passes. I've also rebased the PR to the latest master.

2017-02-07 23:56 UTC, mairaw approved these changes
I think it looks good now. Thanks!

2017-02-07 23:56 UTC, merged