Markdown improvements in nothing.md
dotnet/docs pull request #14773
Opened 2019-09-28 06:47 UTC by Youssef1313

2019-09-29 19:13 UTC, mairaw requested changes
Looks good @Youssef1313. Left a few suggestions!

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> +- [Dim Statement](statements/dim-statement.md)
```suggestion
- [Dim Statement](./statements/dim-statement.md)
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> +- [Is Operator](operators/is-operator.md)
```suggestion
- [Is Operator](./operators/is-operator.md)
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> +- [IsNot Operator](operators/isnot-operator.md)
```suggestion
- [IsNot Operator](./operators/isnot-operator.md)
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + When you assign `Nothing` to an object variable, it no longer refers to any object instance. If the variable had previously referred to an instance, setting it to `Nothing` does not terminate the in
```suggestion
When you assign `Nothing` to an object variable, it no longer refers to any object instance. If the variable had previously referred to an instance, setting it to `Nothing` does not terminate the instance itself. The instance is terminated, and the memory and system resources associated with it are released, only after the garbage collector (GC) detects that there are no active references remaining.
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
>  title: "Nothing (Visual Basic)"
```suggestion
title: "Nothing keyword - Visual Basic"
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
>  # Nothing (Visual Basic)
```suggestion
# Nothing keyword (Visual Basic)
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + `Nothing` represents the default value of a data type. The default value depends on whether the variable is of a value type or of a reference type.
```suggestion
`Nothing` represents the default value of a data type. The default value depends on whether the variable is of a value type or of a reference type.
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + A variable of a *value type* directly contains its value. Value types include all numeric data types, `Boolean`, `Char`, `Date`, all structures, and all enumerations. A variable of a *reference type
```suggestion
A variable of a *value type* directly contains its value. Value types include all numeric data types, `Boolean`, `Char`, `Date`, all structures, and all enumerations. A variable of a *reference type* stores a reference to an instance of the object in memory. Reference types include classes, arrays, delegates, and strings. For more information, see [Value Types and Reference Types](../programming-guide/language-features/data-types/value-types-and-reference-types.md).
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + If a variable is of a value type, the behavior of `Nothing` depends on whether the variable is of a nullable data type. To represent a nullable value type, add a `?` modifier to the type name. Assig
```suggestion
If a variable is of a value type, the behavior of `Nothing` depends on whether the variable is of a nullable data type. To represent a nullable value type, add a `?` modifier to the type name. Assigning `Nothing` to a nullable variable sets the value to `null`. For more information and examples, see [Nullable Value Types](../programming-guide/language-features/data-types/nullable-value-types.md).
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + If a variable is of a value type that is not nullable, assigning `Nothing` to it sets it to the default value for its declared type. If that type contains variable members, they are all set to their
```suggestion
If a variable is of a value type that is not nullable, assigning `Nothing` to it sets it to the default value for its declared type. If that type contains variable members, they are all set to their default values. The following example illustrates this for scalar types.
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + [!code-vb[VbVbalrKeywords#7](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrKeywords/VB/Class2.vb#7)]
```suggestion
[!code-vb[VbVbalrKeywords#7](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrKeywords/VB/Class2.vb#7)]
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + If a variable is of a reference type, assigning `Nothing` to the variable sets it to a `null` reference of the variable's type. A variable that is set to a `null` reference is not associated with an
```suggestion
If a variable is of a reference type, assigning `Nothing` to the variable sets it to a `null` reference of the variable's type. A variable that is set to a `null` reference is not associated with any object. The following example demonstrates this:
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + [!code-vb[VbVbalrKeywords#8](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrKeywords/VB/class3.vb#8)]
```suggestion
[!code-vb[VbVbalrKeywords#8](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrKeywords/VB/class3.vb#8)]
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + When checking whether a reference (or nullable value type) variable is `null`, do not use `= Nothing` or `<> Nothing`. Always use `Is Nothing` or `IsNot Nothing`.
```suggestion
When checking whether a reference (or nullable value type) variable is `null`, do not use `= Nothing` or `<> Nothing`. Always use `Is Nothing` or `IsNot Nothing`.
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + For strings in Visual Basic, the empty string equals `Nothing`. Therefore, `"" = Nothing` is true.
```suggestion
For strings in Visual Basic, the empty string equals `Nothing`. Therefore, `"" = Nothing` is true.
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + The following example shows comparisons that use the `Is` and `IsNot` operators:
```suggestion
The following example shows comparisons that use the `Is` and `IsNot` operators:
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + [!code-vb[VbVbalrKeywords#9](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrKeywords/VB/Class4.vb#9)]
```suggestion
[!code-vb[VbVbalrKeywords#9](~/samples/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrKeywords/VB/Class4.vb#9)]
```

2019-09-29 19:13 UTC, mairaw commented on docs/visual-basic/language-reference/nothing.md
> + If you declare a variable without using an `As` clause and set it to `Nothing`, the variable has a type of `Object`. An example of this is `Dim something = Nothing`. A compile-time error occurs in t
```suggestion
If you declare a variable without using an `As` clause and set it to `Nothing`, the variable has a type of `Object`. An example of this is `Dim something = Nothing`. A compile-time error occurs in this case when `Option Strict` is on and `Option Infer` is off.
```

2019-09-29 19:13 UTC, Youssef1313 commented
@mairaw, Should I start removing the space at the beginning of each paragraph ?

2019-11-08 15:26 UTC, Youssef1313 commented
Ping, @mairaw

2019-11-10 02:22 UTC, mairaw approved these changes
Looks good. Thanks @Youssef1313.

2019-11-10 02:22 UTC, merged