Update error-handling.md
dotnet/docs pull request #14810
Opened 2019-09-30 08:15 UTC by Youssef1313

Made some cleanup.

I noticed that the following sentence doesn't have a link for the `Tracing and Logging`:

> Tracing is the only "catch-all" place where one can potentially see all exceptions. For more information on tracing and logging exceptions, see Tracing and Logging.

2019-10-02 05:35 UTC, mairaw requested changes
Changes look good @Youssef1313. Added a few suggestions unrelated to your changes.

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
>  # Error handling
```suggestion
# Error handling in Windows Communication Foundation
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +## Error handling in Windows Communication Foundation
we should remove this heading and make this the title 
```suggestion
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +
```suggestion
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +### The Microsoft Enterprise Library
```suggestion
## The Microsoft Enterprise Library
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +### Dealing with expected exceptions
```suggestion
## Dealing with expected exceptions
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +### Dealing with unexpected exceptions using an IErrorHandler
```suggestion
## Dealing with unexpected exceptions using an IErrorHandler
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +### Dealing with exceptions outside WCF
```suggestion
## Dealing with exceptions outside WCF
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +### Tracing exceptions
```suggestion
## Tracing exceptions
```

2019-10-02 05:35 UTC, mairaw commented on docs/framework/wcf/feature-details/error-handling.md
> +### URI template errors when using WebGetAttribute and WebInvokeAttribute
```suggestion
## URI template errors when using WebGetAttribute and WebInvokeAttribute
```

2019-10-04 17:45 UTC, Youssef1313 commented
Sorry, @mairaw. Just noticed your review now. I've applied your suggestions and made one additional change.

2019-10-04 17:47 UTC, mairaw approved these changes
Thank you @Youssef1313!

2019-10-04 17:47 UTC, merged