Emphasize exceptions to culture name two-letter rule
dotnet/docs pull request #14816
Opened 2019-09-30 12:13 UTC by Youssef1313

Fixes #12029

2019-09-30 12:19 UTC, pkulikov commented on docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md
> +> There are some exceptions for the two-letter culture names such as `zh-Hans` for Chienese (Simplieied).
```suggestion
> There are some exceptions for the two-letter culture names such as `zh-Hans` for Chienese (Simplifi
ed).
```

2019-09-30 12:23 UTC, Youssef1313 commented on docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md
> +> There are some exceptions for the two-letter culture names such as `zh-Hans` for Chienese (Simplieied).
@pkulikov, Thanks!

2019-09-30 18:56 UTC, rpetrusha requested changes
Thanks for adding this note, @Youssef1313. I've suggested a change.

2019-09-30 18:56 UTC, rpetrusha commented on docs/framework/resources/packaging-and-deploying-resources-in-desktop-apps.md
> +> There are some exceptions for the two-letter culture names such as `zh-Hans` for Chienese (Simplified).
```suggestion
> There are some exceptions for the two-letter culture names, such as `zh-Hans` for Chinese (Simplified).
```

2019-10-01 17:31 UTC, rpetrusha approved these changes

2019-10-01 17:31 UTC, rpetrusha commented
Thanks for making the additional change, @Youssef1313. I'll merge your PR now.

2019-10-01 17:31 UTC, merged