Minor updates
dotnet/docs pull request #14837
Opened 2019-09-30 18:31 UTC by mairaw

I don't understand what "The Desktop Guide for .NET Core covers Windows Presentation Foundation." means so removing that.

Acronyms are only defined once at first usage and then the acronym should be used throughout the rest of the text.

I'd also change the links to be inline with the content as we usually do because if there are any title updates, it's harder to do the changes if link text and link url are broken down like that, but haven't done in this PR.

2019-09-30 18:35 UTC, Youssef1313 requested changes
@mairaw, A quick [search on GitHub](https://github.com/dotnet/docs/search?q=desktop-guide-intro&unscoped_q=desktop-guide-intro), it seems like `desktop-guide-intro.md` isn't referenced anywhere else, so it can be removed.

2019-09-30 18:37 UTC, mairaw commented
Good call @Youssef1313!

2019-10-01 20:37 UTC, Thraka commented on docs/desktop-wpf/overview/index.md
> +For more information, see [Data Binding Overview](../data/data-binding-overview).
```suggestion
For more information, see [Data Binding Overview](../data/data-binding-overview.md).
```

2019-10-01 20:37 UTC, Thraka approved these changes

2019-10-01 20:37 UTC, Thraka commented on docs/desktop-wpf/overview/index.md
> +For more information, see [Data Binding Overview](../data/data-binding-overview).
```suggestion
For more information, see [Data Binding Overview](../data/data-binding-overview.md).
```

2019-10-02 06:35 UTC, merged