Update nullable-reference-types.md
dotnet/docs pull request #14875
Opened 2019-10-01 19:00 UTC by Youssef1313

2019-10-02 06:22 UTC, mairaw commented on docs/csharp/tutorials/nullable-reference-types.md
> +# Tutorial: express your design intent more clearly with nullable and non-nullable reference types
Even though we don't cover this scenario in our guidelines, I think that in the case of tutorials, I actually prefer if the title after the : starts with uppercase. It seems to be different than the How to: guidance that we were given.

2019-10-02 06:23 UTC, mairaw commented on docs/csharp/tutorials/nullable-reference-types.md
>  1. Create a survey and add questions to it.
It seems these steps should be in 3rd person, like
```suggestion
1. Creates a survey and adds questions to it.
```

2019-10-02 17:56 UTC, Youssef1313 commented
I've added a missing comma from #14890.

2019-10-02 17:58 UTC, Youssef1313 commented
@BillWagner, Please, can you review the text under ` ## Create the application and enable nullable reference types` ?

I suspect that it's outdated. With the release of C# 8.0, I don't think there is a need to enable the nullable manually by adding it to csproj file.

2019-10-02 18:33 UTC, BillWagner commented
@Youssef1313 I just checked, and it is still necessary to explicitly opt in to a nullable context (either using `#nullable enable` in source code or `<Nullable>enable</Nullable>` in the project file.

2019-10-02 22:10 UTC, BillWagner commented
I read through the changes, and I'm happy with this update.

@mairaw Do you have more feedback?
@Youssef1313 Is this ready for final review?

2019-10-02 22:12 UTC, mairaw commented
Nope. changes LGTM.

2019-10-03 05:45 UTC, Youssef1313 commented
Made a few minor changes. It's now ready for final review, @BillWagner.

2019-10-03 16:00 UTC, BillWagner requested changes
This is looking very good.  I had one comment, related to the `LangVersion` and `Nullable` elements in the csproj file. I may not have expressed that well in my earlier comment. 

Once that's updated, this is ready to merge.

2019-10-03 18:11 UTC, BillWagner approved these changes

2019-10-03 18:45 UTC, merged