Add Unicode escape Char literal example
dotnet/docs pull request #14953
Opened 2019-10-04 14:29 UTC by zanedp

## Summary
Added an example showing that unicode escape sequences can be used in char literals.

Fixes #13371

2019-10-04 15:16 UTC, Youssef1313 commented on docs/fsharp/language-reference/literals.md
> +|Char|Unicode character|none|`'a'` or `'\u0000'`|
I think this is how it should.

```suggestion
|Char|Unicode character|none|`'a'` or `'\u0061'`|
```

2019-10-04 15:25 UTC, cartermp commented on docs/fsharp/language-reference/literals.md
> +|Char|Unicode character|none|`'a'` or `'\u0000'`|
This is correct 🙂

2019-10-28 15:51 UTC, BillWagner requested changes
Thanks for making this fix @zanedp 

If you accept the suggested change, this is ready to merge.

2019-10-28 20:49 UTC, mairaw commented
@BillWagner I've applied the feedback so we can merge this PR.

2019-10-28 20:55 UTC, BillWagner approved these changes

2019-10-28 20:55 UTC, merged