Fix the page describing native library loading
dotnet/docs pull request #15036
Opened 2019-10-08 20:05 UTC by vitek-karas

This change modifies the docs to match the runtime behavior:
* The ALC used is the one which declares the PInvoke (not the caller)
* There's no event raised when the library is loaded successfully

2019-10-08 20:11 UTC, vitek-karas commented
@swaroop-sridhar please review for correctness.

2019-10-08 20:48 UTC, swaroop-sridhar approved these changes

2019-10-08 20:51 UTC, CoffeeFlux approved these changes

2019-10-09 07:06 UTC, mairaw requested changes
Looks good @vitek-karas. left a small nit to be fixed.

2019-10-09 07:06 UTC, mairaw commented on docs/core/dependency-loading/loading-unmanaged.md
> +1. Determine the `active` <xref:System.Runtime.Loader.AssemblyLoadContext>. For an unmanaged load library, the `active` AssemblyLoadContext is the one with the assembly which defines the `PInvoke`.
```suggestion
1. Determine the `active` <xref:System.Runtime.Loader.AssemblyLoadContext>. For an unmanaged load library, the `active` AssemblyLoadContext is the one with the assembly that defines the `PInvoke`.
```

2019-10-09 07:07 UTC, mairaw commented
Also, please update the ms.date given the nature of the changes.

2019-10-09 20:39 UTC, mairaw approved these changes
Thanks!

2019-10-09 20:39 UTC, merged