Remove project-json.md
dotnet/docs pull request #1520
Opened 2017-02-06 19:12 UTC by spboyer

## Summary

remove project-json.md 

Fixes #1513 

## Suggested Reviewers
@mairaw @blackdwarf

2017-02-06 20:13 UTC, thesmithee approved these changes

2017-02-07 01:11 UTC, mairaw requested changes
we cannot remove topics. we should add the redirect metadata and redirect this topic somewhere. For an example, see https://github.com/dotnet/docs/blob/master/docs/core/app-types.md

2017-02-07 01:17 UTC, mairaw commented
Also, remove that topic from the TOC please.

2017-02-07 15:52 UTC, spboyer commented
@blackdwarf @mairaw - so redirect to where?

2017-02-07 16:04 UTC, mairaw commented
@spboyer, @blackdwarf maybe here for now: https://docs.microsoft.com/en-us/dotnet/articles/core/preview3/tools/layering? Once we have the doc with Nate's blog post, then we could change to that one.

2017-02-07 16:35 UTC, spboyer commented
@mairaw ok made the changes.  That appears to be the best place for now until @natemcmaster post is converted to a doc.

2017-02-07 18:39 UTC, mairaw requested changes
redirect looks good! some suggestions on the wording for people finding this on GH. Also, remove the entry from the TOC file.

2017-02-07 18:39 UTC, mairaw commented on docs/core/tools/project-json.md
> +## Content moved!
moved -> removed

2017-02-07 18:39 UTC, mairaw commented on docs/core/tools/project-json.md
> +This content has merged and moved to the [High-level overview of changes in CLI RC3](../preview3/tools/layering.md) topic.
This content is no longer relevant. For information on the changes, see the [High-level overview of changes in CLI RC4](../preview3/tools/layering.md) topic.

2017-02-07 19:22 UTC, spboyer commented
The following also link to this doc:

* docs/core/migrating-from-dnx.md
* docs/core/porting/libraries.md
* docs/core/tools/dotnet-build.md
* docs/core/tools/dotnet-pack.md
* docs/core/tools/dotnet-publish.md
* docs/core/tools/dotnet-restore.md
* docs/core/tools/dotnet-run.md
* docs/core/tools/extensibility.md

2017-02-07 22:47 UTC, mairaw approved these changes

2017-02-07 22:49 UTC, mairaw commented
Thanks @spboyer! Yes, I'm aware of that. The only one we need to make sure is updated is the libraries one. The migrating-from-dnx should be removed by RTM and the tools folder content should be replaced by the tools content in the preview3 folder. In the meantime, those links will be redirected in the csproj branch.

2017-02-07 22:50 UTC, merged

2017-02-20 14:07 UTC, spboyer commented
@mairaw is there an issue with Nate's blog > doc yet? And is there an ETA on it?  I have another item that I need to link to that on.

Thanks.

2017-02-20 17:38 UTC, mairaw commented
No issues. Just other things that popped up @spboyer. But I've started the draft on Friday. I should have a PR soon.

2017-02-20 18:24 UTC, spboyer commented
@mairaw ha, I meant a guthub issue (for tracking).

2017-02-20 19:07 UTC, mairaw commented
Ha, completely misread that the first time. Yes, #1456 is the issue tracking that work.