Add missing asterik
dotnet/docs pull request #15263
Opened 2019-10-18 05:02 UTC by Youssef1313

2019-10-21 23:08 UTC, mairaw requested changes
Thanks @Youssef1313 for the changes. This article is actually on my backlog to upgrade to VS 2019 and .NET Core 3.0 but I've suggested some changes for now.

2019-10-21 23:08 UTC, mairaw commented on docs/core/tutorials/with-visual-studio.md
> +1. Launch Visual Studio 2017. Select **File** > **New** > **Project** from the menu bar. In the **New Project** dialog, select the **Visual C#** node followed by the **.NET Core** node. Then select t
Let's remove the version from this sentence then

```suggestion
1. Launch Visual Studio. Select **File** > **New** > **Project** from the menu bar. In the **New Project** dialog, select the **Visual C#** node followed by the **.NET Core** node. Then select the **Console App (.NET Core)** project template. In the **Name** text box, type "HelloWorld". Select the **OK** button.
```

2019-10-21 23:08 UTC, mairaw commented on docs/core/tutorials/with-visual-studio.md
> +[Visual Studio 2017 or later](https://aka.ms/vsdownload?utm_source=mscom&utm_campaign=msdocs) with the ".NET Core cross-platform development" workload installed. You can develop your app with .NET Co
we shouldn't use the aka link in this case 

```suggestion
[Visual Studio 2017 or later](https://visualstudio.microsoft.com/downloads/?utm_medium=microsoft&utm_source=docs.microsoft.com&utm_campaign=inline+link&utm_content=download+vs2019) with the ".NET Core cross-platform development" workload installed. You can develop your app with .NET Core 2.1 or later versions.
```

2019-10-22 15:47 UTC, Youssef1313 commented
@mairaw, I've made some additional minor changes that need to be reviewed.

2019-11-01 08:13 UTC, mairaw approved these changes
LGTM. Thanks @Youssef1313!

2019-11-01 08:13 UTC, merged