Typo in Docker - introduction
dotnet/docs pull request #15265
Opened 2019-10-18 05:12 UTC by seangwright

## Summary

Describe your changes here.

Removed extra `to create`

Fixes #Issue_Number (if available)

2019-10-18 06:56 UTC, Youssef1313 commented on docs/core/docker/introduction.md
> +A **Dockerfile** is a file that defines a set of instructions that creates an image. Each instruction in the **Dockerfile** creates a layer in the image. For the most part, when you rebuild the image
```suggestion
A **Dockerfile** is a file that defines a set of instructions that creates an image. Each instruction in the **Dockerfile** creates a layer in the image. For the most part, when you rebuild the image, only the layers that have changed are rebuilt. The **Dockerfile** can be distributed to others and allows them to recreate a new image in the same manner you created it. While this allows you to distribute the *instructions* on how to create the image, the main way to distribute your image is to publish it to a registry.
```

2019-10-18 08:08 UTC, mairaw requested changes
Thank you for making this improvement. Would you mind applying @Youssef1313's suggestion as well?

2019-10-28 04:54 UTC, seangwright commented on docs/core/docker/introduction.md
> +A **Dockerfile** is a file that defines a set of instructions that creates an image. Each instruction in the **Dockerfile** creates a layer in the image. For the most part, when you rebuild the image
Added!

2019-10-28 04:55 UTC, seangwright commented
@mairaw 👍, added it!

2019-10-28 07:10 UTC, mairaw approved these changes
Thanks!

2019-10-28 07:10 UTC, merged