Update mstest tutorial for csproj
dotnet/docs pull request #1531
Opened 2017-02-09 17:05 UTC by BillWagner

And, add that mstest is now cross-platform.

2017-02-10 01:13 UTC, mairaw requested changes
Looks good @BillWagner! I've left some comments.

2017-02-10 01:13 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +Save this file, then run `dotnet build` to build the test project.
later on this article you skip the build step because dotnet test builds the project for you, no? do you need this step here?

2017-02-10 01:13 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +//////////////////////////////////////
do you need this?

2017-02-10 01:13 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +### Adding More Features
should this be H2?

2017-02-10 01:13 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +```
remove this stray ```

2017-02-10 01:13 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +# Unit testing with MSTest and .NET Core
usually our guidelines recommend on not using ing for the verbs on titles and filenames. I know we haven't followed this pattern for the pair topics so it's up to you whether you want to follow the guideline here or not.

Also this topic is having some issues with TOC. TOC link takes me to the topic but it doesn't stick once you go to the topic.

2017-02-10 01:13 UTC, mairaw commented on docs/toc.md
> +### [Unit testing with dotnet test and MSTest](core/testing/unit-testing-with-mstest.md)
capitalization doesn't match the previous entry

2017-02-10 01:14 UTC, mairaw commented
One more question: if this change is applicable to RC4, it should actually be going to master instead of csproj. We're only making the changes in csproj that cannot go live before VS 2017 RTM.

2017-02-10 14:45 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +# Unit testing with MSTest and .NET Core
On the title: I tried alternatives to 'unit  testing' and anything I tried seemed very contrived. I'd rather leave it as is.

On the TOC: I tried the review site this morning, and I'm not seeing any issues. Can you check again after this update builds?

2017-02-10 14:45 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +CD into that directory, and run `dotnet new classib` to create the source
Fixed.

2017-02-10 14:45 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +Next, cd back into the 'unit-testing-using-mstest' directory, and create the `PrimeServices.Tests` directory.
fixed.

2017-02-10 14:45 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +that uses mstest as the test library.
Yes, fixed.

2017-02-10 14:45 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +Or, you can directly edit the `PrimeService.Tests.csproj` file.
Fixed.

2017-02-10 14:46 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +Save this file, then run `dotnet build` to build the test project.
You can do either. I wanted to just show both verbs at some point. Do you think that will cause confusion?

2017-02-10 14:47 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +test runner, and provides a command line argument to the
fixed.

2017-02-10 14:47 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +testrunner indicating the assembly that contains your tests.
fixed.

2017-02-10 14:47 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +In the `PrimeService.Tests` directory, run `dotnet test` again. The
test will run the build. I wanted to show both. Does it make sense?

2017-02-10 14:47 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +//////////////////////////////////////
NOpe. removed.

2017-02-10 14:47 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +### Adding More Features
Yes.

2017-02-10 14:48 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +```
fixed.

2017-02-10 14:48 UTC, BillWagner commented on docs/core/testing/index.md
> +Try this [walkthrough creating unit tests with xunit and the .NET CLI](unit-testing-with-dotnet-test.md).
Fixed.

2017-02-10 14:49 UTC, BillWagner commented on docs/toc.md
> +### [Unit testing with dotnet test and MSTest](core/testing/unit-testing-with-mstest.md)
Fixed for consistency.

2017-02-10 14:52 UTC, BillWagner commented
@mairaw When did the args change for `dotnet new`? This topic uses the new args for class library and test projects. 

Let me know which it should be. The same probably also applies to #1487  If so, I'll close both those PRs and reopen new ones with those changes targeting the master branch.

2017-02-10 20:44 UTC, BillWagner commented
Closing this. The changes are now in PR #1538 and target the master branch instead of the csproj branch.

2017-02-11 01:11 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +# Unit testing with MSTest and .NET Core
Sounds good! 

I'll check the new PR.

2017-02-11 01:12 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +Save this file, then run `dotnet build` to build the test project.
Below you explain you the build step is not required. I don't think is a big deal.

2017-02-11 01:13 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +In the `PrimeService.Tests` directory, run `dotnet test` again. The
Yes, makes sense.

2017-02-11 01:14 UTC, mairaw commented
RC4 introduced the new `dotnet new` @BillWagner

2017-02-11 20:42 UTC, BillWagner commented
Ignore previous comments. These changes should target the csproj branch. Re-opening and closing #1538

2017-02-14 18:36 UTC, BillWagner commented
@mairaw Can you review this now that I've re-opened the original PR (targeting the csproj branch) and address the previous review comments?

2017-02-14 18:53 UTC, mairaw commented
Does staging show you the latest content @BillWagner? I'm not seeing some of the changes there, it's bizarre.

2017-02-14 18:54 UTC, mairaw commented on docs/core/testing/index.md
> +If you prefer using MSTest, try the [walkthrough creating unit tests with MSt   est and the .NET CLI](unit-testing-with-mstest.md).
nit: MSTest has a space in the middle of the word

2017-02-14 18:57 UTC, mairaw approved these changes
LGTM. Found some small nits but unfortunately couldn't see the latest built topics on staging.

2017-02-14 18:57 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +that uses MSstest as the test library.
typo: MSstest

2017-02-14 18:57 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
> +in the PrimeServiceTests.csproj:
nit: style file name as italic (some other instances are using inline code)

2017-02-14 18:57 UTC, BillWagner commented
@mairaw The staging site isn't showing everything. I'll fix the changes you've added in this review and see if that triggers a new build that works.

2017-02-14 19:00 UTC, BillWagner commented on docs/core/testing/index.md
> +If you prefer using MSTest, try the [walkthrough creating unit tests with MSt   est and the .NET CLI](unit-testing-with-mstest.md).
fixed.

2017-02-14 19:00 UTC, BillWagner commented on docs/core/testing/unit-testing-with-mstest.md
> +that uses MSstest as the test library.
fixed.

2017-02-24 23:37 UTC, mairaw commented
Good to merge @BillWagner? The staging site now seems to be working.

2017-02-24 23:43 UTC, BillWagner commented
Yes, I'll merge it now.  :shipit:

2017-02-24 23:43 UTC, merged