Single-character keywords
dotnet/docs pull request #1533
Opened 2017-02-09 17:50 UTC by rpetrusha

# Single-character keywords

## Summary

Documents `$` (the interpolated string identifier) and `@` (the verbatim identifier)

## Details

These have never been completely documented in the C# language reference. 

The verbatim identifier also documents its use to disambiguate attributes. That's something of an edge case, so I'm not certain how important it is to document here, although I chose to include it for the sake of completeness. 

## Suggested Reviewers

@BillWagner

2017-02-10 00:39 UTC, mairaw requested changes
Just did a quick copy edit and found some issues. I'll leave to @BillWagner to do a more thorough review.

2017-02-10 00:39 UTC, mairaw commented on docs/csharp/language-reference/keywords/index.md
> +|[@](../../../csharp/language-reference/keywords/verbatim.md)|[$](../../../csharp/language-reference/keywords/interpolated.md)||
this table looks a bid odd in the built page

2017-02-10 00:39 UTC, mairaw commented on docs/csharp/language-reference/keywords/verbatim.md
> +  - @ keyword [C#]"
missing quote here is causing rendering issues

2017-02-10 00:39 UTC, mairaw commented on docs/csharp/language-reference/keywords/verbatim.md
> +   [!code-csharp[verbatim1](../../../../samples/snippets/csharp/language-reference/keywords/verbatim1.cs#1)]
these snippet references are not rendering

2017-02-10 00:39 UTC, mairaw commented on docs/csharp/language-reference/keywords/verbatim.md
> +1. To indicate that a string literal is to be interpreted verbatim. The `@` character in this instance defines an *verbatim string literal*. Simple escape sequences (such as `"\\"` for a backslash),
an verbatim -> a verbatim

2017-02-10 18:43 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/index.md
> +|[@](../../../csharp/language-reference/keywords/verbatim.md)|[$](../../../csharp/language-reference/keywords/interpolated.md)||
I agree. Unless there are other elements to add, I think it's probably best to present this as a bulleted list -- I'll make the correction.

2017-02-10 18:53 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/verbatim.md
> +  - @ keyword [C#]"
Thanks for noticing and figuring out why, @mairaw.

2017-02-10 18:54 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/verbatim.md
> +   [!code-csharp[verbatim1](../../../../samples/snippets/csharp/language-reference/keywords/verbatim1.cs#1)]
I'm not sure why. Maybe it's a side-effect of the missing quotation mark previously. I've added a space before [verbatim], though I doubt it's significant. The path is correct, and the snippet tag is present.

2017-02-10 22:37 UTC, mairaw commented on docs/csharp/language-reference/keywords/verbatim.md
> +   [!code-csharp[verbatim1](../../../../samples/snippets/csharp/language-reference/keywords/verbatim1.cs#1)]
The indentation perhaps?

2017-02-10 22:42 UTC, mairaw requested changes
LGTM. A few more fixes needed. Thanks!

2017-02-10 22:42 UTC, mairaw commented on docs/csharp/language-reference/keywords/interpolated.md
> +[!CODE[interpolated-string-symbol](../../../../samples/snippets/csharp/language-reference/keywords/dollar-sign1.cs#1)]
this is missing the language identifier so colorization is missing

2017-02-10 22:42 UTC, mairaw commented on docs/csharp/language-reference/keywords/index.md
> +- The [$](../../../csharp/language-reference/keywords/interpolated.md)` symbol is the interpolated string character. It identifies literal string that follows as an interpolated string.
stray backtick here

I'd also leave the explanation of what they do for the page reference since you don't explain what the other keywords do.

2017-02-13 20:05 UTC, rpetrusha commented
@BillWagner I've now documented `@` and `$` as tokens rather than keywords.

2017-02-14 02:30 UTC, BillWagner commented on docs/csharp/language-reference/tokens/index.md
> +Tokens are predefined, contextual, single-character symbols, such as `@` and `$`, that have a special meaning to the C# compiler. C# supports the following tokens:
This is really misleading.  A 'token' in the lexical analysis could be any of:
an identifier
a keyword
literals
operators
punctuation

These two, the `@` an the `$` are kind of special. The spec calls them out as special cases of literals that start with the right character: https://github.com/dotnet/csharplang/blob/master/spec/lexical-structure.md#string-literals

So, I would refer to these characters as "tokens", but I wouldn't add a page for 'tokens' that includes only these characters.  I'm sorry if I misled you earlier in our meeting.

2017-02-14 02:39 UTC, BillWagner requested changes
Overall, this looks really good. I'm concerned that the new topic for 'tokens' could be very misleading for readers.

2017-02-14 16:42 UTC, BillWagner commented on docs/csharp/language-reference/tokens/index.md
> +Tokens are predefined, contextual, single-character symbols, such as `@` and `$`, that have a special meaning to the C# compiler. C# supports the following tokens:
@rpetrusha I realized this morning that I wasn't much help by just saying that I wouldn't add a page for 'tokens'. 

The interesting problem is that neither symbol is an 'operator' or a 'keyword'. 
In the case of the `@` sign, it's a modifier on either a variable name or a string. In the case of `$`, it's modifying a string.

How about renaming the 'tokens' page as 'special characters'. Then, we can get this merged. In the meantime, I'll see if @madstorgersen has a better term.

2017-02-14 18:49 UTC, rpetrusha commented
@BillWagner I've changed 'token' to 'special character'. Please take a look to make sure that I haven't overlooked something.

2017-02-14 18:52 UTC, BillWagner approved these changes
This LGTM.  I found one typo that should be fixed before merging. I also had one suggestion to consider.

2017-02-14 18:52 UTC, BillWagner commented on docs/csharp/language-reference/toc.md
> +## [C$ Special Characters](tokens.md)
Typo:  C$ vs. C#

2017-02-14 18:52 UTC, BillWagner commented on docs/csharp/language-reference/tokens/toc.md
> +## [$](interpolated.md)
Suggestion: Should we spell out more in the TOC? For example, '$ -- string interpolation' and '@ -- verbatim string'? I'm not sure which readers would be more likely to search for.

2017-02-14 22:59 UTC, rpetrusha commented on docs/csharp/language-reference/toc.md
> +## [C$ Special Characters](tokens.md)
Fixed.

2017-02-14 23:44 UTC, rpetrusha commented on docs/csharp/language-reference/tokens/toc.md
> +## [$](interpolated.md)
I've modified the TOC -- I think that that at least makes it clear what the symbols are called.

2017-02-21 21:53 UTC, merged