Rearrange into categories
dotnet/docs pull request #15354
Opened 2019-10-22 19:30 UTC by Thraka

## Summary

Rearranged the H2s into H3s under parent groups.

Fixes #14538

2019-10-23 06:07 UTC, mairaw requested changes
Overall, changes look good but left some comments.

2019-10-23 06:07 UTC, mairaw commented on docs/core/whats-new/dotnet-core-3-0.md
> +## Compile/Publish
wouldn't Deploy be better here?

```suggestion
## Compile/Deploy
```

2019-10-23 06:07 UTC, mairaw commented on docs/core/whats-new/dotnet-core-3-0.md
> +### Improved .NET Core Version APIs
I'd put this in the same API Changes bucket instead of runtime/SDK

2019-10-23 06:07 UTC, mairaw commented on docs/core/whats-new/dotnet-core-3-0.md
> +### .NET Platform-Dependent Intrinsics
same here

2019-10-23 06:07 UTC, mairaw commented on docs/core/whats-new/dotnet-core-3-0.md
> +## .NET Core 3.0 API improvements
Here you could move the sections I commented earlier that are API changes

```suggestion
## .NET Core 3.0 API changes and improvements
```

2019-10-23 06:09 UTC, mairaw commented
@richlander @KathleenDollard can you review these changes to the What's new article and also see if there's anything that's missing or not accurate? Thanks!

2019-10-23 15:02 UTC, Thraka commented on docs/core/whats-new/dotnet-core-3-0.md
> +### Ranges and indices
The API ref pages for these only show standard 2.1 and core 3.0. Do those need to be updated?

2019-10-23 18:28 UTC, mairaw commented on docs/core/whats-new/dotnet-core-3-0.md
> +### Ranges and indices
That's what I meant by shared framework. They're shipped with .NET Core 3.0 as well, but you've added this under the .NET Standard 2.1 header. We still need to do the what's new in .NET Standard 2.1 that would cover specific additions to .NET Standard 2.1. /cc @terrajobst

2019-10-23 21:00 UTC, Thraka commented
#please-review

2019-10-28 19:19 UTC, mairaw approved these changes
LGTM. I don't see anywhere a link to the breaking changes article. Might be good to add for folks looking to upgrade to 3.0. Maybe in the intro or in a see also section?

2019-10-29 00:23 UTC, merged