WIP - Load Data in Model Builder How-To
dotnet/docs pull request #15373
Opened 2019-10-23 15:33 UTC by luisquintanilla

How-To guide to load data in Model Builder

AB#1622265

2019-10-23 17:35 UTC, Youssef1313 requested changes

2019-10-23 17:35 UTC, Youssef1313 commented on docs/machine-learning/how-to-guides/load-data-model-builder.md
> +Training dataset limit is 1GB.
```suggestion
- Training dataset limit is 1GB.
```

2019-10-23 17:35 UTC, Youssef1313 commented on docs/machine-learning/how-to-guides/load-data-model-builder.md
> +SQL Server has a limit of 100 thousand rows.
```suggestion
- SQL Server has a limit of 100 thousand rows.
```

2019-10-23 17:35 UTC, Youssef1313 commented on docs/machine-learning/how-to-guides/load-data-model-builder.md
> +Model builder supports loading data from a file in comma-delimited and tab-demlimited formats.
To be consistent with other occurrences of Model Builder.

```suggestion
Model Builder supports loading data from a file in comma-delimited and tab-demlimited formats.
```

2019-10-23 17:35 UTC, Youssef1313 commented on docs/machine-learning/how-to-guides/load-data-model-builder.md
> +In the folder structure illustrated below, the top-level directory is *flower_photos*. There are five subdirectories corresponsing to the categories to predict: daisy, dandelion, roses, sunflowers an
```suggestion
In the folder structure illustrated below, the top-level directory is *flower_photos*. There are five subdirectories corresponsing to the categories to predict: *daisy*, *dandelion*, *roses*, *sunflowers*, and tulips. Each of these subdirectories contains images belonging to their respective category. 
```

2019-10-23 17:35 UTC, Youssef1313 commented on docs/machine-learning/how-to-guides/load-data-model-builder.md
> +
```suggestion
```

2019-10-29 14:16 UTC, luisquintanilla commented
Work for this was merged as part of #15472

2019-10-29 14:16 UTC, closed without merging