Updating using-tcp-services.md to remove deprecated message
dotnet/docs pull request #15385
Opened 2019-10-24 14:55 UTC by RickAcb

Solved the issue of TcpListener constructor is deprecated see issue #11836

Fixes #11836

2019-10-24 17:18 UTC, Youssef1313 requested changes

2019-10-24 17:18 UTC, Youssef1313 commented on docs/framework/network-programming/using-tcp-services.md
> +        TcpListener listener = new TcpListener(IPAddress.Any, portNum);
```suggestion
        var listener = new TcpListener(IPAddress.Any, portNum);  
```

2019-10-24 17:18 UTC, Youssef1313 commented on docs/framework/network-programming/using-tcp-services.md
>      public static int Main(String[] args) {
```suggestion
    public static int Main(String[] args)
    {
```

2019-10-24 17:18 UTC, Youssef1313 commented on docs/framework/network-programming/using-tcp-services.md
> +Imports System
```suggestion
```

2019-10-28 18:47 UTC, BillWagner approved these changes
This LGTM. I've resolved the conflicts, and I'll :shipit: when the build is clean.

2019-10-28 18:50 UTC, merged