Rewrite standard/index to be a guide into the documentation
dotnet/docs pull request #1539
Opened 2017-02-10 22:14 UTC by cartermp

This attempts to address #1359.

2017-03-04 02:06 UTC, cartermp commented
Ping @mairaw and @BillWagner for review

2017-03-06 16:36 UTC, BillWagner reviewed
Looks good. Left comments for a couple fixes and one suggestion.

2017-03-06 16:36 UTC, BillWagner commented on docs/standard/index.md
> +## Porting a NuGet package from to .NET Standard
From *what* to .NET Standard?

2017-03-06 16:36 UTC, BillWagner commented on docs/standard/index.md
> +If you're looking to port a NuGet package to .NET Standard, check out [Porting to .NET Core from .NET Framework](../core/porting/index.md).
The heading says I'm porting to .NET Standard. This text says I'm porting to .NET Core. This should be consistent.

2017-03-06 16:36 UTC, BillWagner commented on docs/standard/index.md
> +* [Asynchronous Programming](async.md)
Some of these feel a bit advanced for a heading that says "fundamentals". I like that you've included them, but we might want to consider splitting into two lists. I'll suggest "fundamentals" and "major concepts", but I'm really not thrilled with that term. 

Specifically I'm thinking the interop, GC and async are more advance and more specialized.

2017-03-06 20:59 UTC, cartermp commented on docs/standard/index.md
> +If you're looking to port a NuGet package to .NET Standard, check out [Porting to .NET Core from .NET Framework](../core/porting/index.md).
Yeah, right now the article is itself about porting to .NET Core, but is also relevant for .NET Standard.  This is something we'll have to clean up later, but for now I can update the text saying that the concerns are shared here.

2017-03-06 21:09 UTC, cartermp commented on docs/standard/index.md
> +* [Asynchronous Programming](async.md)
I decided to split out the languages from here and just call them Major concepts.

2017-05-02 01:23 UTC, BillWagner requested changes
Overall, I really like this.

There are a few changes we should make before we merge.  See the comments on Getting started vs. Get Started.

2017-05-02 01:23 UTC, BillWagner commented on docs/standard/index.md
> +ms.date: 2/10/2017
the date should get updated.

2017-05-02 01:23 UTC, BillWagner commented on docs/standard/index.md
> +If you're new to .NET, check out the [Getting Started](getting-started.md) article.
We've been given guidance that the gerund forms of verbs are bad for SEO. We've been updating the 'getting started' with 'get started' based on that.  /cc @mairaw

2017-05-02 01:23 UTC, BillWagner commented on docs/standard/index.md
> +If you're new to .NET Core, check out [Getting Started with .NET Core](../core/getting-started.md).
consider 'Get started'.

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="/dotnet/articles/standard/getting-started">Getting Started</a></p>
I'd leave this as 'Get started'

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="/dotnet/articles/core/getting-started">Getting Started</a></p>
I'd consider leaving this as 'get started'

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="https://msdn.microsoft.com/library/hh425099(v=vs.110).aspx">Getting Started</a></p>
Consider leaving as 'get started'

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="https://developer.xamarin.com/guides/cross-platform/getting_started">Getting Started</a></p>
'Get started'

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="/dotnet/articles/csharp/getting-started">Getting Started</a></p>
'Get started'

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="/dotnet/articles/fsharp/tutorials/getting-started">Getting Started</a></p>
'Get started'

2017-05-02 01:23 UTC, BillWagner commented on index.md
> +                                                <p><a href="/dotnet/articles/visual-basic/getting-started">Getting Started</a></p>
'Get started'

2017-05-13 16:12 UTC, cartermp commented
@mairaw @BillWagner Could I get another round of review?

2017-05-14 01:02 UTC, BillWagner commented on docs/welcome.md
> +- [.NET Framework on Docker Guide](framework/index.md)
I'm confused by this change. The target link doesn't say anything about Docker.

2017-05-14 01:02 UTC, BillWagner approved these changes

2017-05-14 01:03 UTC, BillWagner commented
@cartermp I approved all the changes requested in my earlier review. I had one question/comment left. Then, it LGTM.

2017-05-14 01:36 UTC, cartermp commented on docs/welcome.md
> +- [.NET Framework on Docker Guide](framework/index.md)
Derp, this was before the framework docs got migrated.  I'll change this.

2017-05-14 21:51 UTC, merged