Update differences-from-net-framework.md
dotnet/docs pull request #15407
Opened 2019-10-25 21:14 UTC by Kellylorenebaker

@Thraka 

Edits complete per https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1608924.

## Be sure to include all required metadata values per your repo guidelines. I notice that there's no ms.topic, and ms.service or ms.prod values. That's all....otherwise in good shape! 

Fixes https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1608924.

2019-10-26 06:23 UTC, Youssef1313 requested changes

2019-10-26 06:23 UTC, Youssef1313 commented on docs/desktop-wpf/migration/differences-from-net-framework.md
> +When your project uses `<PackageReference>`, packages aren't stored locally in a Packages folder, they're stored globally. Open the project file and remove any `<Analyzer>` elements that referred to
folders should be italic.

2019-10-26 06:23 UTC, Youssef1313 commented on docs/desktop-wpf/migration/differences-from-net-framework.md
> +1. In your WPF project, select *packages.config* > **Migrate packages.config to PackageReference**.
```suggestion
1. In **Solution Explorer**, right-click **packages.config** > **Migrate packages.config to PackageReference**.
```

2019-10-28 21:00 UTC, Thraka approved these changes

2019-10-29 00:41 UTC, Thraka commented
Contributes to #14676

2019-10-29 02:00 UTC, merged