Fix O(N2) → O(N²)
dotnet/docs pull request #15410
Opened 2019-10-26 07:54 UTC by ForNeVeR

## Summary

There's a small formatting issue in the document that is fixed by this PR.

2019-10-26 09:06 UTC, Youssef1313 requested changes
Replaced double spaces with a single space and used `<sup>2</sup>`.

2019-10-26 09:06 UTC, Youssef1313 commented on docs/standard/asynchronous-programming-patterns/consuming-the-task-based-asynchronous-pattern.md
> + There is a potential performance problem with using the <xref:System.Threading.Tasks.Task.WhenAny%2A> method to support an interleaving scenario when you're working with very large sets of tasks.  E
```suggestion
 There is a potential performance problem with using the <xref:System.Threading.Tasks.Task.WhenAny%2A> method to support an interleaving scenario when you're working with very large sets of tasks. Every call to <xref:System.Threading.Tasks.Task.WhenAny%2A> results in a continuation being registered with each task. For N number of tasks, this results in O(N²) continuations created over the lifetime of the interleaving operation. If you're working with a large set of tasks, you can use a combinator (`Interleaved` in the following example) to address the performance issue:
```

2019-10-26 09:21 UTC, ForNeVeR commented
Thanks for your suggestion, I've searched through the docs and found that we, indeed, use `O<sup>2</sup>` here. I'll apply it.

2019-10-27 21:16 UTC, BillWagner approved these changes
thanks for making these changes @ForNeVeR  

This will produce a better published document. I'll :shipit: now.

2019-10-27 21:16 UTC, merged