Removed useless back to top links
dotnet/docs pull request #15445
Opened 2019-10-27 17:38 UTC by sarahliii

## Summary

Removed all instances of "[Back to top](#top)" from project 

Fixes #15431

2019-10-27 17:38 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=15445) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=15445) before we can accept your contribution.<br/><br/>:x: sarahliii [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=15445)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=15445) it.</sub>

2019-10-27 18:11 UTC, pkulikov commented on docs/framework/interop/interop-marshaling.md
> - [Back to top](#top)
With that PR, all `<a name="top"></a>` at the beginning of the files become useless.

2019-10-27 18:20 UTC, mairaw requested changes
Thanks @sarahliii for creating this PR to remove those legacy back to top links. @pkulikov is right that we should remove the anchor from the top as well. 

I'd even take a step further and remove the menu on the top and the additional anchors from those articles since that's already generated in the new system. But I'd leave it up to you whether you'd like to address this on this PR or not.

2019-10-27 23:02 UTC, sarahliii commented
> Thanks @sarahliii for creating this PR to remove those legacy back to top links. @pkulikov is right that we should remove the anchor from the top as well.
> 
> I'd even take a step further and remove the menu on the top and the additional anchors from those articles since that's already generated in the new system. But I'd leave it up to you whether you'd like to address this on this PR or not.

I'll work on removing the anchor for "top". I think I'll hold off on the further changes since I'm not so familiar with the system. (Wouldn't want to break anything!)

2019-10-28 07:25 UTC, mairaw commented
Yeah including the intro sentence. Here’s an example:
![722C226F-A559-4EC3-92AB-6F8BA8E502FD](https://user-images.githubusercontent.com/12971179/67659272-35958200-f919-11e9-815f-846df4ee44e7.jpeg)

But it’s totally fine. Let’s keep this one focused on the task at hand.

Don’t be afraid though! You shouldn’t be able to break anything and we can always revert PRs as well. Thank you!

2019-10-28 07:27 UTC, mairaw commented
And I wouldn’t remove the anchors wholesale. We can clean some that seem useless and see if we get any build warnings.

2019-10-28 07:45 UTC, mairaw requested changes
Thanks @sarahliii. There are still a few things to address before we can merge this.

2019-10-28 07:45 UTC, mairaw commented on docs/framework/misc/security-transparent-code-level-2.md
Remove the top anchor from this file too please

2019-10-28 07:45 UTC, mairaw commented on docs/framework/misc/security-transparent-code.md
Same on this file

2019-10-28 07:45 UTC, mairaw commented on docs/framework/performance/interop-etw-events.md
> +- [Interop ETW Events](#interop-etw-events)
I’d roll back this change

2019-10-28 07:45 UTC, mairaw commented on docs/framework/performance/method-etw-events.md
>  ## CLR Method Marker Events
Still has the anchor tag as well

2019-10-28 07:45 UTC, mairaw commented on docs/framework/performance/security-etw-events.md
> +- [Security ETW Events](#security-etw-events)
Please roll back this change

2019-10-28 07:45 UTC, mairaw commented on docs/standard/security/cryptographic-services.md
> +- [Cryptographic Services](#cryptographic-services)
Please undo this change

2019-10-29 01:48 UTC, nemrism commented
I'm surprised this subject is not on @NextTurn bucket list ;)
Nice 1st contribution @sarahliii

2019-10-29 01:58 UTC, mairaw commented
I have resolved some merge conflicts that showed up during the day since they were complicated to resolve. Make sure to do git pull before you push any changes. Also, please let us know if you need any help to finish this PR. Thanks!

2019-10-29 02:08 UTC, NextTurn commented
@nemrism I've got a bunch of other things to work on recently 😅.

2019-10-29 02:13 UTC, nemrism commented
> @nemrism I've got a bunch of other things to work on recently 😅.

I'm also still trying to design a better solution to work on the #10653 subject!

2019-11-10 02:45 UTC, mairaw approved these changes
I've addressed my final feedback so we can merge this. Thanks @sarahliii!

2019-11-10 03:26 UTC, merged