Fixes to the CI document
dotnet/docs pull request #1556
Opened 2017-02-14 19:17 UTC by blackdwarf

Various fixes to the CI document.

2017-02-14 22:43 UTC, mairaw requested changes
Thanks @blackdwarf. Some quick edit notes for you. I'll review this more thoroughly later on.

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +![Adding a build step](media/vsts-screens/screen_4.png)
rename the folder vsts-screens to the name of the topic

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +This document outlines the usage of .NET Core SDK and its tools on the build server. When we started building the .NET Core SDK and its command-line tools, we have envisioned the toolset being able t
typos:
- interactivelly
- choosng

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +The document will focus on various scenarios of acqusition of the tools and show the tools that we built to help with that. We will then delve into some reccomendations on how to design and structure
typos:
- acqusition 
- reccomendations

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +Native installers are available for MacOS, Windows and Ubuntu (in the form of DEB files and a dedicated apt-get feed). They have the following characteristics:
macOS

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +* For Ubuntu, the apt-get feed allows native depencenies to be acquired at the same time the tools are acquired.
typo: depencenies

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +Using these is straightforward, provided that your CI server or service allows you administrative access. In the case of Windows and macOS, you can download the MSI or PKG installers respectivelly. F
typos:
- respectivelly
- acqusition

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +In general, as desrcibed in the acqusition section above, the main thing in manual setup is to acquire the needed version of the tools (or the latest) and then run the build script that you have. The
typos:
- desrcibed 
- acqusition

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +* We use the `Invoke-WebRequest` cmd-let of PowerShell on line 14 to get the installation script and put it into our installation directory.
cmd-let -> cmdlet

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +After all of this, we are ready to run our build process. For brevity, I have left out that portion of the script, but the [orchestration section](#orchestrating-the-build) goes into more details.
no I in technical docs

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
>  Travis can run both `osx` (OS X 10.11) and `linux` ( Ubuntu 14.04 ) job in a build matrix, see [example .travis.yml](https://github.com/dotnet/docs/blob/master/.travis.yml)
don't we support other versions now? 10.12 for example?

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +The MSBuild-based tools bring both the LTS and Current runtimes (1.0.x and 1.1.x) in the package, so by installing the SDK you will get everything you need to build.
1.0.x and 1.1.x, respectively

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +> If you need to brush up on basics, please visit the [VSTS build documentation](https://www.visualstudio.com/en-us/docs/build/overview).
If you need to brush up on basics, please visit -> For more information, see 

Link should not have locale

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +Taking the script we have started above and using it in VSTS is very simple. You can create a new build definition and then specify
specify what?

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +First, start by creating a new build definition. Once you get the screen that gives you an option to define what kind of a build you wish to create, click on the "Empty" option as the
Remove all these extra words for First, After, etc... 
Just list the steps in sequence
UI options are styled as bold

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +Which to use should be decided mostly based on how familar and comfortable you are with each of the mentioned ways. For example, MSBuild can give you access to expressing your build(s) as tasks and t
Always use the plural form of a noun rather than adding (s).

typo: familar

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +The choice here is dependent on familiarity; some people are more comfortable using more familiar languages like shell scripts while others are well-versed in MSBuild projects and have no problems us
This is kind of repeating the last paragraph

2017-02-14 22:43 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +Here, you can select the script you've created and committed to source control. After this is done, you can save the build definition and try it out by enquining it. From that moment on, you are good
typo: enquining

2017-02-14 23:12 UTC, blackdwarf commented on docs/core/preview3/tools/using-ci-with-cli.md
>  Travis can run both `osx` (OS X 10.11) and `linux` ( Ubuntu 14.04 ) job in a build matrix, see [example .travis.yml](https://github.com/dotnet/docs/blob/master/.travis.yml)
This is what Travis runs, not what we support.

2017-02-14 23:14 UTC, blackdwarf commented on docs/core/preview3/tools/using-ci-with-cli.md
> +> If you need to brush up on basics, please visit the [VSTS build documentation](https://www.visualstudio.com/en-us/docs/build/overview).
I don't know how to get the locale-less link out of there. Just remove it?

2017-02-15 01:06 UTC, mairaw commented on docs/core/preview3/tools/using-ci-with-cli.md
> +> If you need to brush up on basics, please visit the [VSTS build documentation](https://www.visualstudio.com/en-us/docs/build/overview).
@blackdwarf yes. Although in this case you can ignore that since those docs don't seem to have other languages.

2017-02-15 17:39 UTC, blackdwarf commented on docs/core/preview3/tools/using-ci-with-cli.md
> +> If you need to brush up on basics, please visit the [VSTS build documentation](https://www.visualstudio.com/en-us/docs/build/overview).
@mairaw so I guess this is ok? 😄

2017-02-23 01:09 UTC, blackdwarf commented
@mairaw pls take a look. @enricosada will update the PR to add the new AppVeyor script that uses manual install of the newest bits.

2017-02-24 10:53 UTC, enricosada reviewed
I'll add updated travis/appveyor, downloading and invoking install script, because is best option atm

2017-02-24 10:53 UTC, enricosada commented on docs/core/preview3/tools/using-ci-with-cli.md
>  Travis can run both `osx` (OS X 10.11) and `linux` ( Ubuntu 14.04 ) job in a build matrix, see [example .travis.yml](https://github.com/dotnet/docs/blob/master/.travis.yml)
@mairaw @blackdwarf you can specify what osx you want to use (also do a build matrix on that) with normal travis conf, so let's use the default in these docs, and travis users can customize as usual ref [travis docs](https://docs.travis-ci.com/user/osx-ci-environment/#OS-X-Version)

A really good idea is also update directly the [f#, c#, vb official travis docs](https://docs.travis-ci.com/user/languages/csharp/) with .net core support (at least a link to this document)

2017-02-24 10:55 UTC, enricosada commented
also afaik (up to two days ago), travis doesnt yet support rc4, ref https://github.com/travis-ci/travis-ci/issues/7301
i'll check with travis.yml embedded in this repo

2017-02-24 12:12 UTC, enricosada commented
@blackdwarf added https://github.com/dotnet/docs/pull/1599 with cleanup appveyor/travis for rc4

2017-02-24 14:32 UTC, blackdwarf commented
@enricosada I've added support for RC* in Travis with travis-ci/travis-build#968 that was merged yesterday or on Wed.

2017-02-28 00:27 UTC, blackdwarf commented
@mairaw are you ok for this going in?

2017-03-07 03:25 UTC, mairaw commented on .travis.yml
>        dotnet: 1.0.0-preview2-003121
do we need to change these versions @enricosada?

2017-03-07 03:25 UTC, mairaw commented on .travis.yml
>    - dotnet new
should probably be changed to dotnet new console

2017-03-07 03:25 UTC, mairaw commented on appveyor.yml
> +# NOTE .NET Core SDK preview2 is already installed in the build worker image Visual Studio 2015
we would need to update these for vs 2017 correct?

2017-03-07 04:28 UTC, mairaw commented
I've made some improvements @blackdwarf but I still don't think this is ready. Here are the my questions now:
- we have images that are not being used. Delete them?
- The section on Using a manual script seems to skip a few steps but I don't know how to fix that since I've never used VSTS. For example, how do I get to the Create new build definition page/dialog?
- The topic still talks about VS 2015

2017-03-07 04:53 UTC, blackdwarf commented
@mairaw comments:

* Sure, delete all of them.
* You click on the "Build & Release" in the top row.
* Hmmm, @enricosada I thought you added the YAML file for AppVeyor that uses the script and not the VS2015 image?

2017-03-07 04:56 UTC, blackdwarf commented on .travis.yml
>        dotnet: 1.0.0-preview2-003121
Yes. That should say 1.0.1

2017-03-07 13:14 UTC, am11 commented on .travis.yml
> +      dotnet: 1.0.0-rc4-0044771
Please CMIIW, but I think it's `0044771` -> `004771`.

It will work after travis-ci/travis-build#973 :)

2017-03-08 15:53 UTC, enricosada commented
> Hmmm, @enricosada I thought you added the YAML file for AppVeyor that uses the script and not the VS2015 image?

@blackdwarf i have do it, the `appveyor.yml` is

```yaml
 install:
    - ps: $env:DOTNET_INSTALL_DIR = "$pwd\.dotnetsdk"
    - ps: mkdir $env:DOTNET_INSTALL_DIR -Force | Out-Null
    - ps: Invoke-WebRequest -Uri "https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.ps1" -OutFile "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1"
    - ps: '& "$($env:DOTNET_INSTALL_DIR)/dotnet-install.ps1" -Version $env:CLI_VERSION -InstallDir $env:DOTNET_INSTALL_DIR'
    - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
```

btw all that should be updated for 1.0 rtm i think.

@blackdwarf all that should be updated with .net core tools 1.0.1 , i'll send a PR asap, checking locally because the channel is changed (btw the descript of `channel` show dev/future/production, but production doesnt work and default is undocumented `rel-1.0.0`), i'll open an issue in dotnet/cli about that

2017-03-08 16:24 UTC, enricosada commented
@blackdwarf added some comment about dotnet-install script and docs in https://github.com/dotnet/cli/issues/5952

2017-05-16 08:05 UTC, GuardRex commented
Replaced by https://github.com/dotnet/docs/pull/2161

2017-05-16 08:05 UTC, closed without merging