Fix up links in ML folder
dotnet/docs pull request #15580
Opened 2019-10-30 23:42 UTC by gewarren

- replace redirected links
- replace site-relative links with file-relative links

Contributes to #15560

2019-10-31 18:03 UTC, cjgronlund requested changes
Good catches! Your corrections pointed out other issues with the content. See below.

2019-10-31 18:03 UTC, cjgronlund commented on docs/machine-learning/how-does-mldotnet-work.md
> +The `CreatePredictionEngine()` method takes an input class and an output class. The field names and/or code attributes determine the names of the data columns used during model training and predictio
```suggestion
The `CreatePredictionEngine()` method takes an input class and an output class. The field names and/or code attributes determine the names of the data columns used during model training and prediction. See [Make predictions with a trained model](how-to-guides/machine-learning-model-predictions-ml-net.md) in the How-to guides.
```

2019-10-31 18:03 UTC, cjgronlund commented on docs/machine-learning/how-does-mldotnet-work.md
> +The `CreatePredictionEngine()` method takes an input class and an output class. The field names and/or code attributes determine the names of the data columns used during model training and predictio
LInk text and the target page heading need to align.

2019-11-01 17:59 UTC, gewarren commented
@cjgronlund Thanks for the review. I've addressed all of your suggestions.

2019-11-08 00:04 UTC, cjgronlund approved these changes

2019-11-08 01:43 UTC, merged