Add links to the C# 101 video series
dotnet/docs pull request #15605
Opened 2019-10-31 19:41 UTC by BillWagner

Fixes #15008

Provide links to the C# 101 video series from the C# home page, the tutorials home page, and the intro to C# tutorials home page.

/cc @JaySing @shanselman @kendrahavens

2019-10-31 19:42 UTC, BillWagner commented
I'm trying one page with the first video in the series embedded in the page. Comments on that experience?

2019-10-31 19:48 UTC, pkulikov commented on docs/csharp/tutorials/index.md
> +If you want to start your exploration in video format, [this series](https://aka.ms/dotnet3-csharp) provides an introduction to C#. You'll learn about concepts you can explore in this tutorials.
```suggestion
If you want to start your exploration in video format, [this series](https://aka.ms/dotnet3-csharp) provides an introduction to C#. You'll learn about concepts you can explore in these tutorials.
```

2019-10-31 20:03 UTC, BillWagner commented
I like the embedded video on the Intro to C# tutorial page. Other opinions?

2019-10-31 20:38 UTC, gewarren commented
@ghogen Did we ever add links to the videos from the VS docs?

2019-10-31 20:41 UTC, Youssef1313 requested changes
I think this is a better link text.

2019-10-31 20:41 UTC, Youssef1313 commented on docs/csharp/tutorials/intro-to-csharp/index.md
> +[this video series](https://aka.ms/dotnet3-csharp) before starting these interactive lessons.
```suggestion
[C# 101 video series](https://aka.ms/dotnet3-csharp) before starting these interactive lessons.
```

2019-10-31 20:41 UTC, Youssef1313 commented on docs/csharp/index.md
> +  - Watch this [video series](https://aka.ms/dotnet3-csharp). It provides an introduction to the important concepts you'll explore in these tutorials.
```suggestion
  - Watch [C# 101 video series](https://aka.ms/dotnet3-csharp). It provides an introduction to the important concepts you'll explore in these tutorials.
```

2019-10-31 20:41 UTC, Youssef1313 commented on docs/csharp/tutorials/index.md
> +If you want to start your exploration in video format, [this series](https://aka.ms/dotnet3-csharp) provides an introduction to C#. You'll learn about concepts you can explore in these tutorials.
```suggestion
If you want to start your exploration in video format, [C# 101 video series](https://aka.ms/dotnet3-csharp) provides an introduction to C#. You'll learn about concepts you can explore in these tutorials.
```

2019-10-31 21:58 UTC, Thraka approved these changes

2019-11-01 00:35 UTC, mairaw commented
I like it @BillWagner!

2019-11-01 01:41 UTC, merged