Update `dotnet run` Documentation
dotnet/docs pull request #15608
Opened 2019-10-31 22:02 UTC by sfoslund

## Summary

Adding option descriptions for 3.0

Fixes #15521

2019-11-01 00:27 UTC, mairaw requested changes
Thanks @sfoslund with your help with this. I've been making some formatting changes and getting rid of the tabs as I'm updating these docs, but I can do this in a separate PR (e.g. https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-build).

2019-11-01 00:27 UTC, mairaw commented on docs/core/tools/dotnet-run.md
> +# [.NET Core 3.0 and 3.1](#tab/netcore21)
```suggestion
# [.NET Core 3.0 and 3.1](#tab/netcore30)
```

2019-11-01 00:27 UTC, mairaw commented on docs/core/tools/dotnet-run.md
> +# [.NET Core 3.0 and 3.1](#tab/netcore21)
```suggestion
# [.NET Core 3.0 and 3.1](#tab/netcore30)
```

2019-11-01 00:27 UTC, mairaw commented on docs/core/tools/dotnet-run.md
> +Allows the command to stop and wait for user input or action (for example to complete authentication).
```suggestion
Allows the command to stop and wait for user input or action (for example, to complete authentication).
```

2019-11-01 00:27 UTC, mairaw commented on docs/core/tools/dotnet-run.md
Replace line 8 with the following markdown:

```markdown
**This article applies to: ✓** .NET Core 1.x SDK and later versions

<!-- todo: uncomment when all CLI commands are reviewed
[!INCLUDE [topic-appliesto-net-core-all](../../../includes/topic-appliesto-net-core-all.md)]
-->
```

2019-11-01 22:56 UTC, dsplaisted approved these changes

2019-11-02 00:14 UTC, mairaw approved these changes
Looks good. Thanks @sfoslund!

2019-11-02 00:14 UTC, merged