Update links in winforms/wcf/windows-workflow-foundation folders
dotnet/docs pull request #15641
Opened 2019-11-01 18:21 UTC by gewarren

- replace redirected links
- replace site-relative links with file-relative links

Contributes to #15560

2019-11-12 20:42 UTC, gewarren commented
@thraka Could you take a look at this one?

2019-11-14 01:07 UTC, Thraka commented
Sure

2019-11-14 22:15 UTC, Thraka requested changes

2019-11-14 22:15 UTC, Thraka commented on docs/framework/windows-workflow-foundation/samples/built-in-activities.md
> + [Using the InvokeMethod Activity](built-in-activities.md)
This just navigates back to the same page. We should remove this link and remove the page from the TOC.

2019-11-14 23:58 UTC, gewarren commented
@thraka Thanks for the review. I made the requested changes.

2019-11-15 00:44 UTC, Thraka approved these changes
Awesome!

2019-11-15 00:45 UTC, merged