Update doc on ALC used for Assembly.Load(Byte[])
dotnet/docs pull request #15696
Opened 2019-11-05 04:37 UTC by elinor-fung

## Summary

The `Assembly.Load(Byte[])` and `Assembly.Load(Byte[], Byte[])` functions create and use a new ALC. Update the doc on managed assembly loading to indicated this.

2019-11-05 04:38 UTC, elinor-fung commented
/cc @lpereira @vitek-karas

2019-11-05 10:03 UTC, vitek-karas approved these changes

2019-11-07 21:22 UTC, mairaw requested changes
LGTM. The sentence is just missing a period.

2019-11-07 21:22 UTC, mairaw commented on docs/core/dependency-loading/loading-managed.md
> +|<xref:System.Reflection.Assembly.Load(System.Byte[])?displayProperty=nameWithType><p><xref:System.Reflection.Assembly.Load(System.Byte[],System.Byte[])?displayProperty=nameWithType>|Load from object
Add missing period

```suggestion
|<xref:System.Reflection.Assembly.Load(System.Byte[])?displayProperty=nameWithType><p><xref:System.Reflection.Assembly.Load(System.Byte[],System.Byte[])?displayProperty=nameWithType>|Load from object in a new <xref:System.Runtime.Loader.AssemblyLoadContext> instance.|The new <xref:System.Runtime.Loader.AssemblyLoadContext> instance.|
```

2019-11-10 02:20 UTC, mairaw approved these changes

2019-11-10 02:20 UTC, merged