Clarify info about tiered compilation in "what's new" doc
dotnet/docs pull request #15708
Opened 2019-11-05 18:46 UTC by kouvel

## Summary

Clarify what Quick JIT means, that it is enabled in .NET Core 3.0 by default, and describe how to disable it if there are issues.

Fixes https://github.com/dotnet/docs/issues/15143

2019-11-05 18:47 UTC, kouvel commented
CC @noahfalk

2019-11-05 18:47 UTC, kouvel commented
CC @mairaw

2019-11-06 16:19 UTC, Thraka requested changes
Missing period. Otherwise it's ready to go. Thanks!

2019-11-06 16:19 UTC, Thraka commented on docs/core/whats-new/dotnet-core-3-0.md
> +- If the method has AOT-compiled code (ReadyToRun), the pregenerated code will be used
```suggestion
- If the method has AOT-compiled code (ReadyToRun), the pregenerated code will be used.
```

2019-11-07 16:15 UTC, Thraka approved these changes
Looks good, thanks!

2019-11-07 16:15 UTC, merged