Update expose-components-to-com.md
dotnet/docs pull request #15750
Opened 2019-11-07 17:32 UTC by AaronRobinsonMSFT

## Summary

Clarify notes based on customer feedback - https://github.com/dotnet/coreclr/issues/22529#issuecomment-549062371

/cc @jeffschwMSFT @jkoritzinsky @govert

2019-11-07 18:11 UTC, jkoritzinsky approved these changes

2019-11-07 21:10 UTC, mairaw requested changes
Change looks good. Changing from you to a less direct way is usually not usual though.
Left a small comment regarding contractions.

2019-11-07 21:10 UTC, mairaw commented on docs/core/native-interop/expose-components-to-com.md
> +Additionally, loading both .NET Framework and .NET Core into the same process does have diagnostic limitations. The primary limitation is the debugging of managed components as it is not possible to
```suggestion
Additionally, loading both .NET Framework and .NET Core into the same process does have diagnostic limitations. The primary limitation is the debugging of managed components as it is not possible to debug both .NET Framework and .NET Core at the same time. In addition, the two runtime instances don't share managed assemblies. This means that it isn't possible to share actual .NET types across the two runtimes and instead all interactions must be restricted to the exposed COM interface contracts.
```

2019-11-07 21:56 UTC, AaronRobinsonMSFT commented
Thanks @mairaw. Committed your suggestions.

2019-11-10 02:19 UTC, mairaw approved these changes

2019-11-10 02:19 UTC, merged