pj to csproj mapping
dotnet/docs pull request #1581
Opened 2017-02-22 03:48 UTC by mairaw

Fixes #1456 

/cc @blackdwarf @natemcmaster @spboyer

2017-02-22 18:26 UTC, natemcmaster requested changes
I found a few things that are outdated, and some typos to fix (guess I need to proof-read my own blog posts better).

It would be good to also have someone from the SDK team help verify this. cc @blackdwarf or someone else.

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +<Project Sdk="Microsoft.NET.Sdk">
It may be worth noting that Web projects should use `Microsoft.NET.Sdk.Web` here.

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +In project.json, defining a `runtimes` section mean the app was standalone during
Grammar: mean => means.

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +      "url": "https://github.com/natemcmaster/natemcmaster.github.io"
Can we change these examples to something more official, like https://github.com/dotnet?

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
I have since learned that `Summary` is not supported by NuGet. It should be `Title` instead. cref https://github.com/NuGet/Home/issues/4150

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +## packOptions
Would be good to verify this with @rrelyea and/or @rohit21agrawal

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +<PropertyGroup>
We should also add `PackageId`. It defaults to the value of AssemblyName.

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +All settings in this group should be placed in the project folder into a file called
This section is outdated now. Here's the latest on configuring runtime options:

----------------------


```xml
<PropertyGroup>
  <ServerGarbageCollection>true</ServerGarbageCollection>
  <ConcurrentGarbageCollection>true</ConcurrentGarbageCollection>
  <RetainVMGarbageCollection>true</RetainVMGarbageCollection>
  <!-- I'm not suggesting these settings...just showing usage ;) -->
  <ThreadPoolMinThreads>10</ThreadPoolMinThreads>
  <ThreadPoolMaxThreads>100</ThreadPoolMaxThreads>
</ProeprtyGroup>
```

**Tip:** If you are working on a web project, specifying `<Project Sdk="Microsoft.NET.Sdk.Web">`
will automatically default ServerGarbageCollection to true. 

See [CoreCLR configuration](https://github.com/dotnet/coreclr/blob/master/Documentation/project-docs/clr-configuration-knobs.md)
for information on these settings.

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +be included in the package. By default, this will be but in the 'content' folder
Typo: but => put

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +  <PackageReference Include="MSTest.TestAdapter" Version="1.0.0-*" />
The latest is version 1.1.12

2017-02-22 18:26 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +  <PackageReference Include="MSTest.TestFramework" Version="1.0.0-*" />
The latest of this one is 1.1.11

2017-02-22 22:35 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +<Project Sdk="Microsoft.NET.Sdk">
Added.

2017-02-22 22:35 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +In project.json, defining a `runtimes` section mean the app was standalone during
Fixed.

2017-02-22 22:37 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
Fixed

2017-02-23 00:19 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +In project.json, defining a `runtimes` section mean the app was standalone during
Can you push updates to the PR?

2017-02-23 00:23 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +In project.json, defining a `runtimes` section mean the app was standalone during
@natemcmaster I will as soon as I finish working on all your feedback. I'll let you know.

2017-02-23 00:24 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
@natemcmaster actually, summary seems to migrate to the `Description` field. I'll download the latest CLI to make sure.

2017-02-23 00:26 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +be included in the package. By default, this will be but in the 'content' folder
That's a sentence I was going to ask you about. Thanks! Fixed.

2017-02-23 01:06 UTC, rohit21agrawal commented on docs/core/tools/project-json-to-csproj.md
> +be included in the package. By default, this will be but in the 'content' folder
Might be worth mentioning that ```IncludeContentInPack```, which is true by default, is what makes all items of type ```Content``` to be added to the nupkg by default. This behavior can be overridden by setting it  to false.

2017-02-23 01:21 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
scratch what I said. the value actually didn't migrate it to any field. should it? @natemcmaster

2017-02-23 01:21 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +All settings in this group should be placed in the project folder into a file called
I've added all the knobs into my test project.json file:
```json
  "runtimeOptions": {
    "configProperties": {
      "System.GC.Server": true,
      "System.GC.Concurrent": true,
      "System.GC.RetainVM": true,
      "System.Threading.ThreadPool.MinThreads": 4,
      "System.Threading.ThreadPool.MaxThreads": 25
    }
  },
```

and the only one that got migrated was `<ServerGarbageCollection>true</ServerGarbageCollection>`

2017-02-23 01:29 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +All settings in this group should be placed in the project folder into a file called
It's probably a limitation of dotnet-migrate, but these options are definitely supported. cref https://github.com/dotnet/sdk/pull/746

2017-02-23 01:31 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +<PropertyGroup>
PackageId maps to "name" in project.json.  PJ => csproj isn't a one-to-one mapping. "name" maps to both PackageId and AssemblyName.

2017-02-23 01:36 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
Scratch what I said too. `Title` isn't what we want. Basically, "Summary" is not supported (yet). This should be added to "Description".

2017-02-23 20:18 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
I'm confused. The description property is migrated to Description.

2017-02-23 20:21 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +All settings in this group should be placed in the project folder into a file called
Thanks @natemcmaster. I'll open an issue.

2017-02-23 20:32 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +  <Summary>A bundle of cats</Summary>
To clarify, NuGet doesn't support `<Summary>`. PJ's packOptions/summary doesn't have an equivalent in csproj. 

csproj added a new field, `<Title>`, but this is not the same as packOptions/summary.

2017-02-23 20:39 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +<PropertyGroup>
That's not the behavior I'm seeing with the migration @natemcmaster. This is what I see:
name -> not supported
buildOptions\outputName -> AssemblyName
AssemblyTitle and PackageID are by default based on the directory name and they don't come from anywhere in pj

2017-02-23 20:43 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +<PropertyGroup>
Yeah, that's intended migration behavior. PJ's "name" setting was always a bit buggy. Setting "name" different from directory name never worked completely. 99.9% of PJ project's have folder name set to PackageId.

2017-02-24 01:23 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +<PropertyGroup>
but what exactly do you want me to say? PackageId and AssemblyName can be different if buildOptions\outputName was defined

2017-02-24 01:31 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +<PropertyGroup>
In project.json, `"name"` was used for the assembly name as well as the name of the package. In MSBuild, these default to the name of the csproj file. Assembly name can be overridden with `<AssemblyName>` and package name can be overridden with `<PackageId>`.

2017-02-24 02:44 UTC, mairaw commented
I think I took care of all the feedback so far. Thanks for the comments! Please take a look and see if it's good to merge. I've also added the behavior of the migration of the .NET Standard metapackage to a <NetStandardImplicitPackageVersion> property that wasn't part of the original post. 

I've opened issue https://github.com/dotnet/cli/issues/5827 for the runtimeOptions behavior.

/cc @natemcmaster @rohit21agrawal @blackdwarf

2017-02-24 17:22 UTC, natemcmaster approved these changes
One minor change (see comment below). Otherwise looks good. :shipit:

2017-02-24 17:22 UTC, natemcmaster commented on docs/core/tools/project-json-to-csproj.md
> +  <Title>numl is a machine learning library intended to ease the use of using standard modeling techniques for both prediction and clustering.</Title>
Should be `<Description>`, not `<Title>`...sorry if my comments cause confusion.

2017-02-25 00:39 UTC, mairaw commented on docs/core/tools/project-json-to-csproj.md
> +  <Title>numl is a machine learning library intended to ease the use of using standard modeling techniques for both prediction and clustering.</Title>
No, your comments didn't cause confusion. It was a leftover change I forgot to edit. Thanks for your review @natemcmaster!

2017-02-25 05:46 UTC, merged