Relativize links
dotnet/docs pull request #15923
Opened 2019-11-21 16:33 UTC by Youssef1313

2019-11-21 19:21 UTC, Thraka commented
@mairaw Is there something about these architecture guides that need the full links?

2019-11-22 04:19 UTC, mairaw commented
Nope. Only for the ones that are shown on the book as URLs.

2019-11-22 04:20 UTC, mairaw requested changes
Thanks for doing this @Youssef1313. Left a small comment.

2019-11-22 04:20 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/self-hosted.md
> +On Windows hosts, the certificate may be loaded from a secure [Certificate Store](https://docs.microsoft.com/windows/win32/seccrypto/managing-certificates-with-certificate-stores) using the [X509Stor
```suggestion
On Windows hosts, the certificate may be loaded from a secure [Certificate Store](/windows/win32/seccrypto/managing-certificates-with-certificate-stores) using the [X509Store class](xref:system.security.cryptography.x509certificates.x509store). The `X509Store` class can also be used with the OpenSSL key-store on some Linux hosts.
```

2019-12-03 02:56 UTC, mairaw requested changes
There are still some broken links.

2019-12-03 02:56 UTC, mairaw commented on docs/architecture/grpc-for-wcf-developers/self-hosted.md
> +On Windows hosts, the certificate may be loaded from a secure [Certificate Store](/windows/win32/seccrypto/managing-certificates-with-certificate-stores) using the [X509Store class](xref:system.secur
There are still some broken links

```suggestion
On Windows hosts, the certificate may be loaded from a secure [Certificate Store](/windows/win32/seccrypto/managing-certificates-with-certificate-stores) using the <xref:System.Security.Cryptography.X509Certificates.X509Store> class. The `X509Store` class can also be used with the OpenSSL key-store on some Linux hosts.
```

2019-12-03 02:56 UTC, mairaw commented on docs/standard/datetime/system-text-json-support.md
> +then pass it to the corresponding <xref:system.text.json.utf8jsonwriter.writestringvalue?displayProperty=nameWithType>
```suggestion
then pass it to the corresponding <xref:System.Text.Json.Utf8JsonWriter.WriteStringValue%2A?displayProperty=nameWithType>
```

2019-12-03 02:56 UTC, mairaw commented on docs/standard/datetime/system-text-json-support.md
> +or <xref:system.text.json.utf8jsonwriter.writestring?displayProperty=nameWithType> method.
```suggestion
or <xref:System.Text.Json.Utf8JsonWriter.WriteString%2A?displayProperty=nameWithType> method.
```

2019-12-12 09:26 UTC, Youssef1313 commented
@mairaw, changes were addressed here.

2019-12-23 18:58 UTC, mairaw approved these changes
Thank you @Youssef1313!

2019-12-23 18:58 UTC, merged