Note to escape exclamation mark in *nix
dotnet/docs pull request #15972
Opened 2019-11-25 15:56 UTC by joacar

## Summary

Add note that exclamation mark need to be escaped on *nix.

~Fixes #Issue_Number (if available)~

2019-12-03 22:31 UTC, mairaw requested changes
Thanks for your contribution @joacar. I left a few suggestions.

@dsplaisted who can validate this change?

2019-12-04 12:47 UTC, joacar commented
Thanks for correcting my errors.

2019-12-04 20:05 UTC, KathleenDollard commented
@kendrahavens

2019-12-04 20:45 UTC, mairaw commented
Can you commit my suggestions @joacar?

You can click on the button under the suggestion:
![image](https://user-images.githubusercontent.com/12971179/70179970-e79c3880-1693-11ea-828a-f96be659d8bb.png)

2019-12-04 20:50 UTC, joacar commented
Sorry, I was certain I did. Will do it

2020-01-23 22:49 UTC, mairaw commented
@joacar I still see my suggestions haven't been applied. Do you need any help doing that?

2020-01-28 14:59 UTC, joacar commented
@mairaw Sorry for taking time but once again I thought I'd done that. Did it from mobile view so perhaps missed a "submit" button. Now I see the commit is pushed.

2020-02-21 01:25 UTC, kendrahavens approved these changes
Namespace is one word, but we can fix that in a different run. Thank you!

2020-02-21 02:03 UTC, mairaw commented on docs/core/testing/selective-unit-tests.md
> +> skips all tests if name space contains IntegrationTests `dotnet test --filter FullyQualifiedName\!~IntegrationTests`.
```suggestion
> skips all tests if the namespace contains IntegrationTests: `dotnet test --filter FullyQualifiedName\!~IntegrationTests`.
```

2020-02-21 10:10 UTC, mairaw approved these changes
Thank you @joacar

2020-02-21 10:10 UTC, merged