Add new snippets for LINQ SetOperation
dotnet/docs pull request #16022
Opened 2019-11-28 05:34 UTC by SuperNova911

Link snippets from dotnet/sample [this](https://github.com/dotnet/samples/pull/1804#issue-346512804) pull request

Fixes #15951

2019-11-28 05:56 UTC, Youssef1313 requested changes
As @BillWagner stated in https://github.com/dotnet/docs/issues/15951#issuecomment-557961289, these samples seem to be good to have the interactive experience.

2019-11-28 05:56 UTC, Youssef1313 commented on docs/csharp/programming-guide/concepts/linq/set-operations.md
> + [!code-csharp[Distinct](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#1)]
```suggestion
 [!code-csharp-interactive[Distinct](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#1)]
```

2019-11-28 05:56 UTC, Youssef1313 commented on docs/csharp/programming-guide/concepts/linq/set-operations.md
> +[!code-csharp[Except](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#2)]
```suggestion
[!code-csharp-interactive[Except](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#2)]
```

2019-11-28 05:56 UTC, Youssef1313 commented on docs/csharp/programming-guide/concepts/linq/set-operations.md
> +[!code-csharp[Intersect](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#3)]
```suggestion
[!code-csharp-interactive[Intersect](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#3)]
```

2019-11-28 05:56 UTC, Youssef1313 commented on docs/csharp/programming-guide/concepts/linq/set-operations.md
> +[!code-csharp[Union](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#4)]
```suggestion
[!code-csharp-interactive[Union](~/samples/snippets/csharp/VS_Snippets_VBCSharp/CsLINQSetOperation/CS/SetOperation.cs#4)]
```

2019-11-28 06:35 UTC, SuperNova911 commented
Change `code-csharp` tag to `code-csharp-interactive`

2019-12-02 19:19 UTC, BillWagner approved these changes
I like the way you've incorporated the new snippets into the existing explanations.

I'll :shipit: now.

2019-12-02 19:20 UTC, merged