Fixed Typos on tour.md.
dotnet/docs pull request #1603
Opened 2017-02-25 20:46 UTC by Jaxelr

# Fixed typos on Tour of F#  doc.

## Summary

There was some minor typos on the Tour of F# doc.

## Details

Fixed typos on tour.md

## Suggested Reviewers

2017-02-25 20:46 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-02-25 21:54 UTC, svick commented on docs/fsharp/tour.md
> +[Units of Measure](language-reference/units-of-measure.md) allow you to associate a numeric type to a unit, such as Meters, and have functions perform work on units rather than numeric literals.  Thi
This doesn't seem to be grammatically correct. Did you delete the "certain context" part by accident?

2017-02-25 22:49 UTC, Jaxelr commented on docs/fsharp/tour.md
> +[Units of Measure](language-reference/units-of-measure.md) allow you to associate a numeric type to a unit, such as Meters, and have functions perform work on units rather than numeric literals.  Thi
Woops, yes this was my mistake.

2017-02-26 00:14 UTC, cartermp requested changes
Thanks, @Jaxelr!  Looks good modulo the change @svick noted.  Once that's fixed, I'll go ahead and merge.

2017-02-27 19:44 UTC, mairaw commented
Thanks @Jaxelr! I made the fixes for you so we can merge this. Thank you for catching and fixing those typos.

2017-02-27 20:08 UTC, mairaw commented
@cartermp ok to merge this now?

2017-02-27 21:49 UTC, cartermp approved these changes

2017-02-27 21:49 UTC, merged