Update corefx to runtime in rid-catalog
dotnet/docs pull request #16146
Opened 2019-12-06 20:03 UTC by Youssef1313

Contributes to #15982

2019-12-06 20:35 UTC, mairaw requested changes
Thanks @Youssef1313. I left some comments for you to consider.

2019-12-06 20:35 UTC, mairaw commented on docs/core/rid-catalog.md
> +For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) file on CoreFX repo.
```suggestion
For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) file on the `dotnet/runtime` repository.
```

2019-12-06 20:35 UTC, mairaw commented on docs/core/rid-catalog.md
> +The RID graph or runtime fallback graph is a list of RIDs that are compatible with each other. The RIDs are defined in the [Microsoft.NETCore.Platforms](https://www.nuget.org/packages/Microsoft.NETCo
```suggestion
The RID graph or runtime fallback graph is a list of RIDs that are compatible with each other. The RIDs are defined in the [Microsoft.NETCore.Platforms](https://www.nuget.org/packages/Microsoft.NETCore.Platforms/) package. You can see the list of supported RIDs and the RID graph in the [*runtime.json*](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) file, which is located at the `dotnet/runtime` repository. In this file, you can see that all RIDs, except for the base one, contain an `"#import"` statement. These statements indicate compatible RIDs.
```

2019-12-06 20:35 UTC, mairaw commented on docs/core/rid-catalog.md
> +Only common values are listed. For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) fi
```suggestion
Only common values are listed. For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) file on `dotnet/runtime` repository.
```

2019-12-06 20:35 UTC, mairaw commented on docs/core/rid-catalog.md
> +Only common values are listed. For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) fi
```suggestion
Only common values are listed. For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) file on the `dotnet/runtime` repository. Devices running a distribution not listed below may work with one of the Portable RIDs. For example, Raspberry Pi devices running a Linux distribution not listed can be targeted with `linux-arm`.
```

2019-12-06 20:35 UTC, mairaw commented on docs/core/rid-catalog.md
> +macOS RIDs use the older "OSX" branding. Only common values are listed. For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Mic
```suggestion
macOS RIDs use the older "OSX" branding. Only common values are listed. For the latest and complete version, see the [runtime.json](https://github.com/dotnet/runtime/blob/master/src/libraries/pkg/Microsoft.NETCore.Platforms/runtime.json) file on the `dotnet/runtime` repository.
```

2020-01-07 23:23 UTC, gewarren approved these changes
Thanks @Youssef1313 .

2020-01-07 23:24 UTC, gewarren commented
@mairaw Can you approve this?

2020-01-24 02:10 UTC, mairaw approved these changes
Thanks @Youssef1313!

2020-01-24 02:18 UTC, merged