Move Migration to Docker to ASP.NET docs
dotnet/docs pull request #1619
Opened 2017-03-03 15:03 UTC by spboyer

Related to https://github.com/aspnet/Docs/issues/2679
Dependent on https://github.com/aspnet/Docs/pull/2877

@mairaw - do we also remove from ToC?

2017-03-03 20:09 UTC, mairaw requested changes
Yes, let's remove it from the TOC as well. Thanks!

2017-03-03 20:09 UTC, mairaw commented on docs/framework/docker/aspnetmvc.md
> +redirect_url: /aspnet/mvc/overview/deployment/docker-aspnetmvc
we would want to preserve the comments when we migrate too, so add the following metadata as well:

`redirect_document_id: TRUE`

2017-03-06 14:44 UTC, spboyer commented
@mairaw - should be good to go now, once the ASP.NET items are merged.
cc:/ @tdykstra @Rick-Anderson

2017-03-07 23:40 UTC, mairaw approved these changes
I'll merge as soon as build is green. Thanks @spboyer!

2017-03-08 00:24 UTC, merged