setup -> set up
dotnet/docs pull request #16257
Opened 2019-12-14 05:11 UTC by gewarren

2019-12-14 06:37 UTC, Youssef1313 requested changes

2019-12-14 06:37 UTC, Youssef1313 commented on docs/machine-learning/tutorials/iris-clustering.md
>  ## Setup data loading
```suggestion
## Set up data loading
```

2019-12-14 16:47 UTC, mairaw approved these changes
LGTM modulo the comment from @Youssef1313

2019-12-16 17:42 UTC, gewarren commented
Thanks for the review Maira and @Youssef1313 .

2019-12-16 17:42 UTC, merged