Add note about microsoft archive repo in readme
dotnet/docs pull request #16378
Opened 2019-12-22 11:47 UTC by Youssef1313

The link that was specified to the code gallery (<https://code.msdn.microsoft.com>) redirects to the samples browser and is no longer useful. I removed that link, specified that the code gallery is retired, and pointed to where the samples were moved.

2019-12-22 11:47 UTC, Youssef1313 commented on README.md
> +We anticipate that [Xamarin](https://docs.microsoft.com/xamarin), [Mono](http://docs.go-mono.com/?link=root%3a%2fclasslib), and [Unity](https://docs.unity3d.com/Manual/index.html) will also use this
nit: comma

2019-12-23 20:05 UTC, mairaw requested changes
Thanks @Youssef1313. Left a few comments.

2019-12-23 20:05 UTC, mairaw commented on README.md
> +If you're interested in helping migrate existing code that targets the .NET Framework from the retired code gallery to .NET Core applications stored in our [samples repository](https://github.com/dot
```suggestion
If you're interested in helping migrate existing code that targets the .NET Framework from the [retired Code Gallery](https://docs.microsoft.com/teamblog/msdn-code-gallery-retired) site to .NET Core applications stored in our [samples repository](https://github.com/dotnet/samples) and downloadable from the [Samples Browser](https://docs.microsoft.com/samples/browse), see the [Code Gallery migration](https://github.com/dotnet/docs/projects/88) project. The code gallery samples were moved to the [Microsoft Archive](https://github.com/microsoftarchive?q=msdn-code-gallery) organization.
```

2019-12-23 20:05 UTC, mairaw commented on README.md
> +We anticipate that [Xamarin](https://docs.microsoft.com/xamarin), [Mono](http://docs.go-mono.com/?link=root%3a%2fclasslib), and [Unity](https://docs.unity3d.com/Manual/index.html) will also use this
I don't think this is true. I'd remove this. Xamarin already has its own repo on docs.

```suggestion
```

2020-01-17 09:02 UTC, Youssef1313 commented
#please-review

2020-01-17 09:05 UTC, Youssef1313 commented
*.ghal.rules.json* has the following segment:

```json
  "comment": {
    "created": {
      "processor-comment": {
        "body": {
          "^#please-review$": {
            "condition-1": {
              "type": "query",
              "value": "Issue.state == 'open' && Issue.user.id == Comment.user.id",
              "actions": {
                "labels-add": "changes-addressed"
              }
            }
          }
        }
      }
    }
  }
```

I was expecting that commenting with #please-review would automatically add "changes-address" label. Is it a bug somewhere or a misunderstanding from me ?

2020-01-17 17:57 UTC, Thraka commented
@Youssef1313 we didn't turn on the webhook for that. It's in the config in case we want to. I don't think we've seen a real huge need for it yet.

2020-01-17 17:57 UTC, Thraka commented
Whoops clicked the wrong button.

2020-01-24 00:18 UTC, mairaw approved these changes
Looks great. Thank you @Youssef1313!

2020-01-24 00:19 UTC, mairaw commented
BTW, we don't have the automation here, but if you click on the refresh icon next to the reviewer's name, it will request a new review from them:
![image](https://user-images.githubusercontent.com/12971179/73035199-2761df80-3dfc-11ea-87f0-a401d8310d62.png)

That can help bring those back to our queue.

2020-01-24 00:20 UTC, merged