GC config knobs touch-ups
dotnet/docs pull request #16504
Opened 2020-01-02 23:48 UTC by gewarren

Fixes #16075 

@Maoni0 I didn't add the web.config examples that Nick Craver requested since this article is really about .NET Core. LMK if you think I should add them anyway.

2020-01-03 21:12 UTC, Maoni0 commented on docs/core/run-time-config/garbage-collector.md
> +         "System.GC.HeapHardLimit": 80000
I know this is supposed to be an example only but it'd be good to have a more realistic value :) like 209715200 which is 200MiB.

2020-01-03 21:13 UTC, Maoni0 commented on docs/core/run-time-config/garbage-collector.md
> +> If you're setting the option in *runtimeconfig.json*, specify a decimal value. If you're setting the option as an environment variable, specify a hexadecimal value. For example, to specify a heap h
probably would the 80,000 bytes here too..sorry I should have pointed this out before

2020-01-03 21:14 UTC, Maoni0 requested changes
the rest looks great!

2020-01-06 22:49 UTC, Maoni0 approved these changes
LGTM!

2020-01-06 22:49 UTC, Maoni0 approved these changes

2020-01-08 23:16 UTC, gewarren commented
@mairaw This one is preapproved by Maoni if you could take a quick look.

2020-01-09 06:57 UTC, mairaw approved these changes
LGTM. Would this warrant an ms.date update? Also, I've noticed that the acronym GC was introduced several times in this doc. Can you just say GC on the subsequent introductions?

2020-01-09 19:26 UTC, merged