Fixed "[+&#124;-]"→"[+|-]"
dotnet/docs pull request #16526
Opened 2020-01-04 14:07 UTC by hyoshioka0128

https://docs.microsoft.com/en-us/dotnet/visual-basic/reference/command-line-compiler/compiler-options-listed-alphabetically

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2020-01-04 17:22 UTC, Youssef1313 requested changes
I think it must be escaped.

2020-01-08 18:39 UTC, mairaw requested changes
Thanks @hyoshioka0128 for the bug fix but that didn't quite work. I left a suggestion on how I think we can make that work instead.

2020-01-08 18:39 UTC, mairaw commented on docs/visual-basic/reference/command-line-compiler/compiler-options-listed-alphabetically.md
> +|`-parallel[+\|-]`|Specifies whether to use concurrent build (+).|
That didn't work. Let's try this instead.

```suggestion
|<code>-parallel[+&#124;-]</code>|Specifies whether to use concurrent build (+).|  
```

2020-01-14 03:00 UTC, mairaw approved these changes
I've applied the feedback so we can merge this PR if build looks good. We're starting to get customer feedback on this issue, so I'd like to merge this sooner rather than later.

2020-01-14 03:04 UTC, merged