Remove link within `code block`
dotnet/docs pull request #1665
Opened 2017-03-07 19:46 UTC by johncrim

Apparently the link doesn't render correctly within the code block - better to remove it than to display misleading info (particularly in an introductory article).

2017-03-07 19:46 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-07 21:22 UTC, mairaw requested changes
Good catch @johncrim! The backticks should have been placed like this:
```markdown
[`dotnet new console`](../tools/dotnet-new.md)
```

Would you mind changing it to that? I can also make the change for you, if you prefer. Thanks!

2017-03-08 06:02 UTC, johncrim commented
Updating as requested @mairaw . Thanks for the guidance on the correct fix.

2017-03-08 06:28 UTC, mairaw approved these changes
Thank you for catching and fixing this!

2017-03-08 06:29 UTC, merged