Revised deployment topic to include Visual Studio
dotnet/docs pull request #1666
Opened 2017-03-07 23:44 UTC by rpetrusha

# Revised deployment topic to include Visual Studio

## Summary

This addresses a customer complaint that it did not appear to be possible to deploy a self-contained app outside of the command line.

## Suggested Reviewers

@blackdwarf  @mairaw

2017-03-10 08:25 UTC, mairaw commented on docs/core/deploying/index.md
> +   **In Visual Studio 2017:** Select **File**, **New**, **Project**. In the **Add New Project** dialog, select **.NET Core** in the **Installed** project types pane, and select the **Console App (.NE
MSFT style guide: Use > to separate sequential steps

2017-03-10 08:25 UTC, mairaw commented on docs/core/deploying/index.md
> +1. Open the `Program.cs` file in your editor, and replace the auto-generated code with the following code. It prompts the user to enter text, and then displays the individual words entered by the use
style file names as italic

2017-03-10 08:29 UTC, mairaw commented
I've been thinking about this topic and wondering whether we should separate the theory from the practice. And then we could have a topic that is totally done through VS vs. one that is all CLI. Thoughts?

2017-03-10 18:41 UTC, rpetrusha commented on docs/core/deploying/index.md
> +   **In Visual Studio 2017:** Select **File**, **New**, **Project**. In the **Add New Project** dialog, select **.NET Core** in the **Installed** project types pane, and select the **Console App (.NE
Fixed.

2017-03-10 18:42 UTC, rpetrusha commented on docs/core/deploying/index.md
> +1. Open the `Program.cs` file in your editor, and replace the auto-generated code with the following code. It prompts the user to enter text, and then displays the individual words entered by the use
Fixed.

2017-03-10 18:50 UTC, rpetrusha commented
I can see the advantages of each approach, though my own preference here is for a single, longer topic, as long as the steps for CLI/VS are clearly differentiated, and I think that they are here -- or at least, I've tried to make them clearly distinct. At the same time, I have to admit that I tend to have a bias toward longer topics. @blackdwarf, do you have a sense of whether this should remain one single topic, or be broken up into one conceptual overview, one CLI how-to topic, and one VS topic?

2017-03-13 15:52 UTC, rpetrusha commented
@mairaw In thinking more about it, although I'd prefer not to essentially duplicate content in separate Visual Studio and CLI topics, I agree that the best thing to do here would be to separate the two implementation topics from the conceptual topic. I'll do that, and in the meantime, I'll add the WIP label.

2017-03-17 22:32 UTC, rpetrusha commented
@mairaw @blackdwarf I've separated the conceptual portion of the topic from the CLI and Visual Studio examples, which I've put in separate topics.

2017-04-11 04:21 UTC, GuardRex commented
@rpetrusha Is it ok if I review this and we make a move to get it in there. I :heart: SCD ... It is my favorite deployment type.

2017-04-11 15:11 UTC, rpetrusha commented
@GuardRex, yes, by all means!

2017-04-12 17:57 UTC, GuardRex commented
@rpetrusha I noticed that you moved content from the initial doc into the two examples docs unchanged/uncorrected. I see you were just getting the content in the right spot on this pass. Should I skip the nits for now? ... someone can make a grammar/style pass later.

2017-04-12 21:09 UTC, rpetrusha commented
@GuardRex, no, review it thoroughly. My intent was to do more than get the content in the right places, it was to get the content correct.

2017-04-13 05:58 UTC, guardrex requested changes
@rpetrusha There are a handful of purely writing style suggestions that will be easy for you to skip if you don't like them. The vast majority of these comments are nit-picky little grammar-ish thingies. There are a few gems in there. Although text is duplicated between two docs, I tried to catch every instance in both docs to make it easier for you to run down the suggestions. You don't need to see a suggestion in one and skip to the other ... my comment re-appears in the other at the right spot (I hope).

2017-04-13 05:58 UTC, GuardRex commented on docs/core/deploying/index.md
>  - Self-contained deployment. Unlike FDD, a self-contained deployment (SCD) does not rely on any shared components to be present on the target system. All components, including both .NET Core librarie
* does not :point_right: doesn't
* "rely on any shared components to be present on the target system" :point_right: "rely on the presence of shared components on the target system"
* "both .NET Core libraries" :point_right: "both the .NET Core libraries"
* .dll :point_right: italics?
* \`app.dll\` :point_right: italics

2017-04-13 05:58 UTC, GuardRex commented on docs/core/deploying/index.md
>  For an FDD, you deploy only your app and any third-party dependencies. You do not have to deploy .NET Core, since your app will use the version of .NET Core that's present on the target system. This
"do not" :point_right: "don't"

2017-04-13 05:58 UTC, GuardRex commented on docs/core/deploying/index.md
>  Deploying an FDD has a number of advantages:
In the list below ...

First bullet:
* "do not" :point_right: "don't"
* "You do not have to define the target operating systems that your .NET Core app will run on in advance." :point_right: "You don't need to define in advance the target operating systems where your .NET Core app will run."
* "PE file format" isn't defined (it's linked, but not defined)
* The 2nd sentence somewhat restates the info in the first sentence

Second bullet:
* "You only have to deploy" :point_right: "You only deploy"

2017-04-13 05:58 UTC, GuardRex commented on docs/core/deploying/index.md
>  - It is possible for the .NET Core runtime and libraries to change without your knowledge in future releases. In rare cases, this may change the behavior of your app.
* "It is" :point_right: "It's"
* Vaguely feels like an example is needed to flesh out the last remark "in rare cases ..."

2017-04-13 05:58 UTC, GuardRex commented on docs/core/deploying/index.md
> +For a self-contained deployment, you deploy not only your app and any third-party dependencies, but the version of .NET Core that you build your app with. Creating an SCD does not, however, include t
> dependencies, but the version

remove comma

... or another way to state this that kills the sentence-ending preposition is ...

> For a self-contained deployment, you deploy your app and any included third-party dependencies along with the version of .NET Core used to build the app.

Next sentence:
* In that position, "however" seems *more formal* than just starting with the word.
* "does not" :point_right: "doesn't"
* I would drop the word "itself"
* "need to be installed" :point_right: "must be present" (the dev doesn't need to do it if they're already there)
* application :point_right: app

> However, creating an SCD doesn't include ...

2017-04-13 05:58 UTC, GuardRex commented on docs/core/deploying/index.md
> +# See also
Consistency: A blank line after the section heading

2017-04-13 05:58 UTC, GuardRex commented on samples/snippets/core/deploying/deployment-example.cs
> +using System;
As I stated up at the start, this isn't necessary to teach these concepts or show how the tooling works to create these deployment types. Therefore, I suggest removing this and just going with a good 'ole default "Hello World!" console app.

2017-04-13 17:52 UTC, GuardRex commented
A passing note on web apps + 👣 small footprint 👣 SCD: The tracking issue is https://github.com/dotnet/cli/issues/5769. Nobody has asked beyond my tracking, so perhaps nothing needs to be noted at this time in the small footprint section. I'm going to check again this weekend and at least see if the `web.config` fix works for me, and I'll see if the other two issues are still problems.

2017-04-18 22:13 UTC, rpetrusha commented
@GuardRex, I've finally revised this based on your comments. Thanks for the extremely through review!

2017-04-19 03:34 UTC, guardrex approved these changes

2017-04-19 03:34 UTC, GuardRex commented on docs/core/deploying/deploying-with-cli.md
> +   Open the *Program.cs* file in your editor and replace the auto-generated code with the following code. It prompts the user to enter text, and then displays the individual words entered by the user
Remove comma after "text" (I suggest dropping "then" as well)

> It prompts the user to enter text and displays the individual words entered by the user.

2017-04-19 03:34 UTC, GuardRex commented on docs/core/deploying/deploying-with-cli.md
> +   Open the *Program.cs* file in your editor and replace the auto-generated code with the following code. It prompts the user to enter text and displays the individual words entered by the user. It u
Remove comma after "text" (I suggest dropping "then" as well)

> It prompts the user to enter text and displays the individual words entered by the user.

2017-04-19 03:34 UTC, GuardRex commented on docs/core/deploying/deploying-with-vs.md
> +   Open the `Program.cs` file in your editor, and replace the auto-generated code with the following code. It prompts the user to enter text, and then displays the individual words entered by the use
\*Program.cs\*
Remove comma after "text" (I'd suggest dropping "then" as well)

> It prompts the user to enter text and displays the individual words entered by the user.

2017-04-19 03:34 UTC, GuardRex commented on docs/core/deploying/deploying-with-vs.md
> +1. If Newtonsoft.Json is already installed on your system, add it to your project by selecting your project in the right pane of hte **Manage Packages for Solution** tab.
\`Newtonsoft.Json\`

2017-04-19 03:34 UTC, GuardRex commented on docs/core/deploying/index.md
> +- Self-contained deployment. Unlike FDD, a self-contained deployment (SCD) doesn't rely on the presence of shared components on the target system. All components, including both the .NET Core librari
\*app.exe\*

2017-04-19 03:37 UTC, GuardRex commented
@rpetrusha Looks great ... just a handful of minor touches and :shipit:

2017-04-19 17:49 UTC, rpetrusha commented
Thanks, @GuardRex. I've incorporated all of your remaining changes; I'll merge when the build finishes.

2017-04-19 19:08 UTC, merged