Add language identifiers and minor changes
dotnet/docs pull request #16826
Opened 2020-01-24 10:25 UTC by Youssef1313

2020-01-24 16:16 UTC, tdykstra requested changes
Thanks for the corrections. Most of this LGTM, but I'm not inclined to go with "output" on inline code blocks since it's not a supported language identifier.

2020-01-24 16:54 UTC, Youssef1313 commented
> 
> 
> Thanks for the corrections. Most of this LGTM, but I'm not inclined to go with "output" on inline code blocks since it's not a supported language identifier.

It's currently in use:

![image](https://user-images.githubusercontent.com/31348972/73087209-d5dc5200-3eda-11ea-8148-f3e0d4b939f6.png)

When an identifier isn't supported, the name will just display without syntax highlighting. I *think* this is okay.

2020-01-24 18:44 UTC, mairaw approved these changes
Changes LGTM. We've adopted the output style in the past @tdykstra but happy to reconsider.

2020-01-24 18:44 UTC, mairaw commented on docs/framework/wcf/samples/custom-service-host.md
>  ## Running the Sample
```suggestion
## Run the sample  
```

2020-01-27 16:32 UTC, tdykstra commented
>When an identifier isn't supported, the name will just display without syntax highlighting.

That's correct, and some writers have used "output" in some cases. But in other cases, "text" or "console" have been used instead and may be a better fit. In some cases it may be best to leave off the identifier. The team discussed this and didn't reach a consensus on a standard approach.  That being the case, I believe it would usually be best to leave whatever the writer used as-is except where there's an obvious error like a typo or a missing supported language identifier. In this PR the changes I'd prefer to see reverted are the ones in the System.Text.Json docs; "output" might work for console output but it doesn't seem to me ideal for labeling error messages returned by a library.

2020-01-27 17:29 UTC, tdykstra approved these changes
Looks good, thanks again for the corrections.

2020-01-27 17:30 UTC, merged