Update with-visual-studio.md
dotnet/docs pull request #1686
Opened 2017-03-09 02:46 UTC by GuardRex

* Building a C# Hello World application with .NET Core in Visual Studio 2017
* docs/csharp/getting-started/with-visual-studio.md

Fixes #1675 

Blocked by https://github.com/dotnet/docs/pull/1679 ... waiting for a doc to move.

Originally started to add stroke outlines to images, but these changes will result in the grammar/style of this doc matching the other *Getting Started* series docs.

~"freely downloadable"~ :grinning:

2017-03-09 02:46 UTC, dnfclas commented
@GuardRex,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-05-03 05:54 UTC, GuardRex commented
@mairaw This is no longer blocked now that https://github.com/dotnet/docs/pull/1679 is merged.

2017-05-16 00:02 UTC, rpetrusha requested changes
A number of the new images do not appear in the build. Hopefully, they'll be addressed by the rebuild.

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +   ![New Project dialog with Console App selected](./media/with-visual-studio/newproject.png)
I have no idea why, but this image isn't displaying in the built topic.

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +1. To cause the application to pause before it closes the console window, add the following code immediately after the call to the @System.Console.WriteLine(System.String) method:
use either displayProperty=fullName, or `[Console.WriteLine(String)](<xref:System.Console.WriteLine(System.String)>)` (I think that's the correct form.)

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +   ![Visual Studio and the new HelloWorld project](./media/with-visual-studio/devenv.png)
This image also doesn't appear in the page.

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +   The template creates a simple "Hello World" application. It calls the @System.Console.WriteLine(System.String) method to display the literal string "Hello World!" in the console window. By selecti
Rather than using the @ syntax, it's best to use <xref> with ?displayProperty=fullName here.
the Main --> the Main method

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +   ![Console window showing Hello World Press any key to continue](./media/with-visual-studio/helloworld1.png)
This image also isn't rendering.

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +   This code displays "What is your name?" in the console window and waits until the user enters a string followed by the Enter key. It stores this string to a variable named `name`. It also retrieve
DateTime.Now should be fully qualified.

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +   ![Console window with modified program output](./media/with-visual-studio/helloworld2.png)
This image also isn't rendering.

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
>  - For information on developing a publishing a distributable version of your application, see [Publishing the Hello World application](publishing-with-visual-studio.md).
on developing a publishing --> on publishing ?

2017-05-16 00:02 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +You can also develop a .NET Core console app on Mac, Linux, and Windows by using Visual Studio Code, a downloadable code editor. For a step-by-step tutorial, see [Getting Started with Visual Studio C
Instead of freely (which was incorrect), I would still add that it's a free downloadable code editor.

2017-05-16 00:13 UTC, GuardRex commented on docs/csharp/getting-started/with-visual-studio.md
> +You can also develop a .NET Core console app on Mac, Linux, and Windows by using Visual Studio Code, a downloadable code editor. For a step-by-step tutorial, see [Getting Started with Visual Studio C
@rpetrusha The style manual flags "free" wording: Although this isn't advertising and marketing, I guessed (perhaps incorrectly) that the legal guidelines still apply. For example if the free item is a download and listed as being "free," we're supposed to say, "Connect time charges may apply." They have a six month rule, where they say a product or service can't be listed as "free" past six months. They want a link to terms and conditions. Idk how serious they would be about this, but I felt that just removing the word fixes the problem.

2017-05-16 00:53 UTC, GuardRex commented
Found a few other little things to touch up. The images seem to be in the right spot, so we'll see if they decide to show up to the party this time.

2017-05-16 14:07 UTC, GuardRex commented
@rpetrusha Images seem ok now: https://review.docs.microsoft.com/en-us/dotnet/articles/csharp/getting-started/with-visual-studio?branch=pr-en-us-1686

2017-05-16 15:32 UTC, rpetrusha commented on docs/csharp/getting-started/with-visual-studio.md
> +You can also develop a .NET Core console app on Mac, Linux, and Windows by using Visual Studio Code, a downloadable code editor. For a step-by-step tutorial, see [Getting Started with Visual Studio C
@GuardRex, I suspect you're right. It's probably best to delete it. It may be a good idea, though, to link to the VS Code download site.

2017-05-16 15:38 UTC, rpetrusha approved these changes

2017-05-16 15:39 UTC, rpetrusha commented
@GuardRex, LGTM, and the images are finally appearing. You can decide whether or not you want to add a link to the VS Code download, and then merge.

2017-05-16 16:19 UTC, GuardRex commented
> add a link to the VS Code download

@rpetrusha Great idea!

2017-05-16 22:16 UTC, merged