Fixed instances of e.g. and i.e.
dotnet/docs pull request #1701
Opened 2017-03-09 23:33 UTC by tompratt-AQ

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary
Replaced all instances of e.g. and i.e. in .md files with "for example," and "that is,".
Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers
@mairaw 
If you know who should review this, use '@' to request a review.

2017-03-09 23:33 UTC, dnfclas commented
@__tompratt-AQ__,
Thanks for your contribution.
To ensure that the project team has proper rights to use your work, please complete the Contribution License Agreement at https://cla2.dotnetfoundation.org.

It will cover your contributions to all .NET Foundation-managed open source projects.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-09 23:42 UTC, dnfclas commented
__@tompratt-AQ__, thanks for signing the contribution license agreement. We will now validate the agreement and then the pull request.
<br />_Thanks, .NET Foundation Pull Request Bot_

2017-03-09 23:56 UTC, rpetrusha requested changes

2017-03-09 23:56 UTC, rpetrusha commented on docs/csharp/programming-guide/concepts/linq/how-to-use-annotations-to-transform-linq-to-xml-trees-in-an-xslt-style.md
> + For any given text node, there may be any number of child `<b>` and `<i>` elements. This approach extends to a number of other situations: that is, pages that can contain a variety of child elements
the i.e. wasn't optimal here, so replacing it only slightly helps. Possibly better is "...other situations, such as pages that can contain a variety of child elements like regular paragraphs, bulleted paragraphs, and bitmaps"

Also, document-centric.

2017-03-09 23:56 UTC, rpetrusha commented on docs/csharp/programming-guide/concepts/object-oriented-programming.md
> +>  C# doesn't support multiple inheritance, that is, you can specify only one base class for a derived class.
i.e. again was awkward. I'd make these two sentences.

2017-03-09 23:56 UTC, rpetrusha commented on docs/standard/base-types/formatting-types.md
> +* The specific way in which an object is represented as a string, if the object implements the [IFormattable](xref:System.IFormattable) interface and supports format strings. You do this by following
This also needs a closing paren -- ...digits).

2017-03-09 23:56 UTC, rpetrusha commented on docs/standard/common-type-system.md
> +*   Provide a library that contains the basic primitive types that are used in application development (that is, `Boolean`, `Byte`, `Char` etc.)
"such as" reads somewhat better than "that is" here.

2017-03-09 23:56 UTC, rpetrusha commented on docs/visual-basic/programming-guide/concepts/linq/how-to-use-annotation-trees-to-transform-linq-to-xml-trees-in-an-xslt-style.md
> + For any given text node, there may be any number of child `<b>` and `<i>` elements. This approach extends to a number of other situations: that is, pages that can contain a variety of child elements
See earlier comment.

2017-03-09 23:56 UTC, rpetrusha commented on docs/visual-basic/programming-guide/concepts/object-oriented-programming.md
> +>  Visual Basic doesn't support multiple inheritance, that is, you can specify only one base class for a derived class.
See earlier comment.

2017-03-10 00:56 UTC, tompratt-AQ commented
Addressed the review comments and took all of the suggestions from rpetrusha.

2017-03-10 01:15 UTC, cartermp approved these changes

2017-03-10 16:23 UTC, rpetrusha approved these changes
LGTM.

2017-03-10 17:04 UTC, merged