updating links from fwlink to real link if exists - contributes to #3391
dotnet/docs pull request #17053
Opened 2020-02-11 23:15 UTC by eddynaka

updating links from fwlink to real link if exists - contributes to #3391

2020-02-12 20:02 UTC, mairaw requested changes
Thanks @eddynaka. Submitting the first comments re. this PR. GitHub tends to crash if I go over 50.

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/table-valued-parameters.md
> +|[Table-Valued Parameters (Database Engine)](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/bb510489(v=sql.100)) in SQL Server Books Online|Describes how to create and use table-val
```suggestion
|[Use Table-Valued Parameters (Database Engine)](/sql/relational-databases/tables/use-table-valued-parameters-database-engine)|Describes how to create and use table-valued parameters.|  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/table-valued-parameters.md
> +|[User-Defined Table Types](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/bb522526(v=sql.100)) in SQL Server Books Online|Describes user-defined table types that are used to declar
```suggestion
|[User-Defined Table Types](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/bb522526(v=sql.100))|Describes user-defined table types that are used to declare table-valued parameters.|  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/table-valued-parameters.md
> + Table-valued parameters are based on strongly-typed table structures that are defined by using Transact-SQL CREATE TYPE statements. You have to create a table type and define the structure in SQL Se
```suggestion
 Table-valued parameters are based on strongly-typed table structures that are defined by using Transact-SQL CREATE TYPE statements. You have to create a table type and define the structure in SQL Server before you can use table-valued parameters in your client applications. For more information about creating table types, see [User-Defined Table Types](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/bb522526(v=sql.100)).  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/the-context-connection.md
>   **SQL Server Books Online**
```suggestion
 **SQL Server documentation**  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/sql-server-common-language-runtime-integration.md
> +1. [Common Language Runtime (CLR) Integration Programming Concepts](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/ms131102(v=sql.100))
```suggestion
1. [Common Language Runtime (CLR) Integration Programming Concepts](/sql/relational-databases/clr-integration/common-language-runtime-clr-integration-programming-concepts)  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/sql-server-data-types.md
> +1. [Data Types (Database Engine)](https://docs.microsoft.com/previous-versions/sql/sql-server-2008-r2/ms187594(v=sql.105))
```suggestion
1. [Data Types (Transact-SQL)](/sql/t-sql/data-types/data-types-transact-sql)  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/sql-server-in-process-specific-behavior-of-adonet.md
> +1. [SQL Server In-Process Specific Extensions to ADO.NET](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/ms131070(v=sql.100))
```suggestion
1. [SQL Server In-Process Specific Extensions to ADO.NET](/sql/relational-databases/clr-integration-data-access-in-process-ado-net/sql-server-in-process-specific-extensions-to-ado-net)  
```

2020-02-12 20:30 UTC, mairaw commented on docs/framework/data/adonet/sql/the-context-connection.md
> +1. [The Context Connection](https://docs.microsoft.com/previous-versions/sql/sql-server-2008/ms131053(v=sql.100))
```suggestion
1. [The Context Connection](/sql/relational-databases/clr-integration/data-access/context-connection)  
```

2020-02-12 21:12 UTC, eddynaka commented on docs/framework/data/adonet/sql/date-and-time-data.md
can you check if thats what you wanted, pls? Thanks

2020-02-14 05:16 UTC, mairaw commented
We were having some build issues yesterday

2020-02-14 05:18 UTC, mairaw commented on docs/framework/data/adonet/sql/date-and-time-data.md
yes, thanks!

2020-02-14 05:19 UTC, mairaw approved these changes
Thank you @eddynaka.

2020-02-14 09:24 UTC, merged