Revisions for support of binary literals
dotnet/docs pull request #1723
Opened 2017-03-14 01:49 UTC by rpetrusha

# Revisions for support of binary literals

## Summary

Documents support for 0x to define hexadecimal literals and 0b to define binary literals

Fixes #1709

## Details

Expands the literal assignment section of each primitive integral type (`byte`, `short`, `int`, `long`, `sbyte`, `ushort`, `uint`, `ulong` to include hex and binary assignment.

Also fixed a number of other issues, including absence of language in fenced code blocks, organization of section, separating literals from compiler overload resolution, etc.

## Suggested Reviewers

@BillWagner

2017-03-15 01:23 UTC, BillWagner requested changes
@rpetrusha overall, this looks great. I found one typo, and I had one suggestion. Once that's done, let's :shipit:

2017-03-15 01:23 UTC, BillWagner commented on docs/csharp/language-reference/keywords/long.md
> + A common use of the suffix is to call overloaded methods. Tor example, the following overloaded methods have parameters of type `long` and [int](../../../csharp/language-reference/keywords/int.md):
typo: Tor => For

2017-03-15 01:23 UTC, BillWagner commented on samples/snippets/csharp/language-reference/keywords/numeric-literals.cs
> +      short shortValue3 = 0b010000001010;
I'd recommend adding the _ separator in all the binary constants. It does improve readability

2017-03-16 15:55 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/long.md
> + A common use of the suffix is to call overloaded methods. Tor example, the following overloaded methods have parameters of type `long` and [int](../../../csharp/language-reference/keywords/int.md):
Fixed.

2017-03-16 15:55 UTC, rpetrusha commented on samples/snippets/csharp/language-reference/keywords/numeric-literals.cs
> +      short shortValue3 = 0b010000001010;
Definitely. Done.

2017-03-16 16:46 UTC, mairaw commented on docs/csharp/language-reference/keywords/uint.md
> + Integer literals can also include a suffix that denotes the type. The suffix `U` or 'u' denotes either a `uint` or a `ulong`, depending on the numeric value of the literal. The following example use
an `uint` -> a `uint`?

2017-03-16 17:46 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/uint.md
> + Integer literals can also include a suffix that denotes the type. The suffix `U` or 'u' denotes either a `uint` or a `ulong`, depending on the numeric value of the literal. The following example use
Fixed.

2017-03-20 17:35 UTC, BillWagner approved these changes

2017-03-20 17:35 UTC, merged