Add new article: Inspecting assembly contents using MetadataLoadContext
dotnet/docs pull request #17427
Opened 2020-03-10 17:06 UTC by MSDN-WhiteKnight

Fixes #17360

Contributes to #2729

Related samples PR: https://github.com/dotnet/samples/pull/2053

2020-03-17 16:41 UTC, Thraka commented
@MSDN-WhiteKnight Looking good! You should move your snippet content into a child folder named for the article. This way others can include snippets for other articles in the assembly area.

2020-03-18 16:55 UTC, Thraka requested changes
Per my other comment. The snippet should be in its own folder

2020-03-18 22:30 UTC, gewarren reviewed
Looks good with some minor suggestions. Thanks!

2020-03-18 22:30 UTC, gewarren commented on docs/standard/assembly/inspect-contents-using-metadataloadcontext.md
> +Creating the <xref:System.Reflection.MetadataLoadContext> requires providing the instance of the <xref:System.Reflection.MetadataAssemblyResolver>. The simplest way to provide one is to use the <xref
```suggestion
Creating the <xref:System.Reflection.MetadataLoadContext> requires providing the instance of the <xref:System.Reflection.MetadataAssemblyResolver>. The simplest way to provide one is to use the <xref:System.Reflection.PathAssemblyResolver>, which resolves assemblies from the given collection of assembly path strings. This collection, besides assemblies you want to inspect directly, should also include all needed dependencies. For example, to read the custom attribute located in an external assembly, you should include that assembly or an exception will be thrown. In most cases, you should include at least the *core assembly*, that is, the assembly containing built-in system types, such as <xref:System.Object?displayProperty=nameWithType>. The following code shows how to create the <xref:System.Reflection.PathAssemblyResolver> using the collection consisting of the inspected assembly and the current runtime's core assembly:
```

2020-03-18 22:30 UTC, gewarren commented on docs/standard/assembly/inspect-contents-using-metadataloadcontext.md
> +If you need access to all BCL types, you can include all runtime assemblies into the collection. The following code shows how to create the <xref:System.Reflection.PathAssemblyResolver> using the col
```suggestion
If you need access to all BCL types, you can include all runtime assemblies in the collection. The following code shows how to create the <xref:System.Reflection.PathAssemblyResolver> using the collection consisting of the inspected assembly and all assemblies of the current runtime:
```

2020-03-18 22:30 UTC, gewarren commented on docs/standard/assembly/inspect-contents-using-metadataloadcontext.md
> +After you've created the context, you can load assemblies into it using methods such as <xref:System.Reflection.MetadataLoadContext.LoadFromAssemblyPath%2A>. You can use all reflection APIs on loaded
```suggestion
After you've created the context, you can load assemblies into it using methods such as <xref:System.Reflection.MetadataLoadContext.LoadFromAssemblyPath%2A>. You can use all reflection APIs on loaded assemblies except ones that involve code execution. The <xref:System.Reflection.MemberInfo.GetCustomAttributes%2A> method does involve the execution of constructors, so use the <xref:System.Reflection.MemberInfo.GetCustomAttributesData%2A> method instead when you need to examine custom attributes in the <xref:System.Reflection.MetadataLoadContext>.
```

2020-03-18 22:30 UTC, gewarren commented on docs/standard/assembly/inspect-contents-using-metadataloadcontext.md
> +The following code sample creates <xref:System.Reflection.MetadataLoadContext>, loads the assembly into it and outputs assembly attributes into the console:
```suggestion
The following code sample creates <xref:System.Reflection.MetadataLoadContext>, loads the assembly into it, and outputs assembly attributes into the console:
```

2020-03-19 15:30 UTC, gewarren commented
@Thraka The snippet is in its own folder now AFAICT. Can you approve if you agree?

2020-03-23 18:04 UTC, Thraka approved these changes

2020-03-23 18:45 UTC, merged