19). Add topic files 47 to 50
dotnet/docs pull request #17688
Opened 2020-04-03 00:14 UTC by jameshkramer

@mairaw @BillWagner
This PR is for user story #1576037.

It adds four article files, makes corresponding deletions from the C# and VB folders, and adds redirection entries. There are also some fixes to past articles.

Please merge https://github.com/dotnet/docs/pull/17675 before merging this.

cc: @tfosmark @marteeleigh

2020-04-03 23:33 UTC, mairaw commented
@jameshkramer do you wanna resolve the conflicts here now that I merged the previous PR?

2020-04-04 00:43 UTC, mairaw commented
You need to actually resolve the conflicts. You can do via the UI (https://github.com/dotnet/docs/pull/17688/conflicts) or locally on your computer.

2020-04-06 14:46 UTC, BillWagner requested changes
I noticed one item to fix. After that, I'm good.

2020-04-06 14:46 UTC, BillWagner commented on docs/standard/linq/query-xml-trees-overview.md
> +## In This Section
This heading should have remained sentence cased:

```suggestion
## In this section
```

2020-04-06 16:23 UTC, Thraka commented
Lots of missing links to fix in the build report.

2020-04-06 16:39 UTC, jameshkramer commented
@Thraka The cause for most, perhaps all, of the broken links is that only about 1/3 of the articles for the LINQ to XML section have been added so far.  The links will be fixed over time as articles are added. At the end we will attend to any remaining ones.

2020-04-06 17:05 UTC, jameshkramer commented
@BillWagner thanks, I committed your change.

2020-04-06 18:09 UTC, mairaw reviewed
Left a few comments but LGTM

2020-04-06 18:09 UTC, mairaw commented on docs/standard/linq/find-elements-specific-attribute.md
> +title: "How to find elements with a specific attribute (XPath-LINQ to XML) (C#)"
```suggestion
title: "How to find elements with a specific attribute - XPath-LINQ to XML"
```

2020-04-06 18:09 UTC, mairaw commented on docs/standard/linq/find-elements-specific-attribute.md
> +# How to find elements with a specific attribute (XPath-LINQ to XML) (C#)
```suggestion
# How to find elements with a specific attribute in C# (XPath-LINQ to XML)
```

2020-04-06 20:53 UTC, jameshkramer commented
I deleted the file in which Maira found problems. Solved! I had inadvertently included the file because it has a very similar name to another. It had never been properly edited.  It is scheduled to be added later.

2020-04-06 21:14 UTC, jameshkramer commented
I did commit Bill's change. I don't know why GitHub seems to indicate that there is more to do.

2020-04-07 19:58 UTC, BillWagner approved these changes

2020-04-07 19:59 UTC, mairaw commented
He just needed to re-review @jameshkramer. Merging now.

2020-04-07 19:59 UTC, merged