Issue 1737 update language identifiers
dotnet/docs pull request #1769
Opened 2017-03-21 21:26 UTC by tompratt-AQ

# Title
Replace language identifiers to use the supported ones for OPS (#1737)

## Summary
Changed the following language identifiers to match our [internal list of supported identifiers](https://review.docs.microsoft.com/en-us/csi/msdocs/code?branch=master
):
```cs``` TO ```csharp```, ```fs``` TO ```fsharp```, ```PHP``` to ```php```

Fixes #1737 

## Suggested Reviewers
@mairaw

2017-03-21 21:26 UTC, dnfclas commented
@tompratt-AQ,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-21 22:20 UTC, tompratt-AQ commented
Resolved merge conflicts.

2017-03-21 23:17 UTC, mairaw requested changes
This looks great @tompratt-AQ! The only thing missing is to update the topic (https://github.com/dotnet/docs/blob/master/styleguide/template.md#inline-code-blocks-with-language-identifier) to have the list of supported identifiers instead of linking to https://github.com/jmm/gfm-lang-ids/wiki/GitHub-Flavored-Markdown-(GFM)-language-IDs. Can you please add that to this PR? Thanks.

2017-03-21 23:20 UTC, mairaw commented on docs/core/testing/unit-testing-with-dotnet-test.md
>  if(candidate < 2)
for the merge conflicts, you should add the identifier csharp but keep the change that @GuardRex made to the topic: 
`if (candidate < 2)` (note he added a space after the if). and also remove the extra lines added.

2017-03-21 23:20 UTC, mairaw commented on docs/core/testing/unit-testing-with-mstest.md
>  if(candidate < 2)
same here.

2017-03-22 18:46 UTC, tompratt-AQ commented
Updated the style guide link to point to the list of Supported Identifiers and fixed the merge conflicts.

2017-03-24 00:16 UTC, mairaw requested changes
Left a comment. Plus something seems to have gone wrong with the rebase since there are some extra commits from other PRs showing up. I might need to help you to clean this up. Let me know.

2017-03-24 00:16 UTC, mairaw commented on styleguide/template.md
> +Use three backticks (\`\`\`) + a language ID to apply language-specific color coding to a code block. Here is the list of [Supported Languages](https://review.docs.microsoft.com/en-us/csi/msdocs/code
customers won't have access to the list. you need to add the values from that topic here.

2017-03-24 17:49 UTC, closed without merging