20). Add topic files 51 to 54
dotnet/docs pull request #17732
Opened 2020-04-06 22:40 UTC by jameshkramer

@mairaw @BillWagner
This PR is for user story #1576037.

It adds four article files, makes corresponding deletions from the C# and VB folders, and adds redirection entries. There are also fixes to two past articles.

Please merge #17688 before merging this.

cc: @tfosmark @marteeleigh

2020-04-07 15:13 UTC, BillWagner approved these changes
This LGTM @jameshkramer 

I'll wait to :shipit: until @mairaw has a chance to review.

2020-04-07 20:00 UTC, mairaw commented
@jameshkramer can you review the merge conflicts here?

2020-04-07 21:32 UTC, jameshkramer commented
@mairaw   @BillWagner 

I fixed the merge conflicts. Thanks for reviewing so quickly!

2020-04-08 22:29 UTC, jameshkramer commented
@mairaw @BillWagner 

Is there a reason why this hasn't been merged?

2020-04-09 04:56 UTC, mairaw commented
I haven’t had a chance to review yet. Will do it tomorrow

2020-04-09 16:19 UTC, jameshkramer commented
@mairaw, sorry, I thought your merge indicated you had looked at it.

2020-04-09 20:17 UTC, mairaw requested changes
I'm not seeing the redirection file updates and the files being deleted to introduce filter-optional-element.md, find-all-nodes-namespace.md, sort-elements.md, and write-queries-complex-filtering.md.

2020-04-09 20:17 UTC, mairaw commented on docs/standard/linq/xdocument-class-overview.md
> +description: The LINQ to XML XDocument class contains the information necessary for a valid XML document. In many cases you don't require the functionality of an XDocument object and can use an XElem
```suggestion
description: The LINQ to XML XDocument class contains the information necessary for a valid XML document. In many cases, you don't need the functionality of an XDocument object and can use an XElement object instead.
```

2020-04-09 23:17 UTC, jameshkramer commented
Maira, you were right - I didn't do that work. Sorry for the bother. I think it's fixed now.

2020-04-10 01:35 UTC, mairaw requested changes
A few extra comments

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/filter-optional-element.md
> +- [XML Child Axis Property](../../visual-basic/language-reference/xml-axis/xml-child-axis-property.md)
```suggestion
- [XML Child Axis Property (Visual Basic)](../../visual-basic/language-reference/xml-axis/xml-child-axis-property.md)
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/filter-optional-element.md
> +- [XML Attribute Axis Property](../../visual-basic/language-reference/xml-axis/xml-attribute-axis-property.md)
```suggestion
- [XML Attribute Axis Property (Visual Basic)](../../visual-basic/language-reference/xml-axis/xml-attribute-axis-property.md)
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/sort-elements.md
> +description: Wite a query that sorts its results
```suggestion
description: Write a query that sorts its results.
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/sort-elements.md
> +- [Sorting Data](../../visual-basic/programming-guide/concepts/linq/sorting-data.md)
```suggestion
- [Sorting Data (Visual Basic)](../../visual-basic/programming-guide/concepts/linq/sorting-data.md)
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/sort-elements.md
> +
Can you add a quick intro here?

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/write-queries-complex-filtering.md
> +- a child `Address` element whose `Type` attribute equals "Shipping", and
```suggestion
- A child `Address` element whose `Type` attribute equals "Shipping".
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/write-queries-complex-filtering.md
> +- a child `State` element that equals "NY".
```suggestion
- A child `State` element that equals "NY".
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/write-queries-complex-filtering.md
> + It uses a nested query in the `Where` clause, and the `Any` operator returns `true` if the collection has any elements in it. The example uses XML document [Sample XML file: Multiple purchase orders
```suggestion
It uses a nested query in the `Where` clause, and the `Any` operator returns `true` if the collection has any elements in it. The example uses XML document [Sample XML file: Multiple purchase orders](sample-xml-file-multiple-purchase-orders.md).
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/write-queries-complex-filtering.md
> +- [XML Child Axis Property](../../visual-basic/language-reference/xml-axis/xml-child-axis-property.md)
```suggestion
- [XML Child Axis Property (Visual Basic)](../../visual-basic/language-reference/xml-axis/xml-child-axis-property.md)
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/write-queries-complex-filtering.md
> +- [XML Attribute Axis Property](../../visual-basic/language-reference/xml-axis/xml-attribute-axis-property.md)
```suggestion
- [XML Attribute Axis Property (Visual Basic)](../../visual-basic/language-reference/xml-axis/xml-attribute-axis-property.md)
```

2020-04-10 01:35 UTC, mairaw commented on docs/standard/linq/write-queries-complex-filtering.md
> +- [XML Value Property](../../visual-basic/language-reference/xml-axis/xml-value-property.md)
```suggestion
- [XML Value Property (Visual Basic)](../../visual-basic/language-reference/xml-axis/xml-value-property.md)
```

2020-04-10 17:52 UTC, jameshkramer commented
@mairaw @BillWagner 

Maira, thanks for the review. I wrote the intro you requested. I'll be more careful in the future when I copy links from articles (to be sure all the need link text is there).

2020-04-15 00:44 UTC, mairaw approved these changes
LGTM

2020-04-15 00:45 UTC, merged