Removing outdated VS references (Part 2)
dotnet/docs pull request #1810
Opened 2017-03-27 22:43 UTC by GuardRex

Addresses #1795: This is Part 2 of the updates, so let's call it *Shark Happens!*

* Primarily aims to remove and harden against VS2010 references.
* Also licks a handful of Visual C# 2010 references and removes a 2010 (C# 4-era) book frequently mentioned (in one doc, also drops some C# 3-era references).

2017-03-27 22:44 UTC, dnfclas commented
@GuardRex,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-29 00:10 UTC, mairaw requested changes
Looks great @GuardRex! Left a few comments.

2017-03-29 00:10 UTC, mairaw commented on docs/fsharp/language-reference/source-line-file-path-identifiers.md
> +Source Directory: C:\Users\username\Documents\Visual Studio <version>\Projects\SourceInfo\SourceInfo
since this is an example output, should we just show a newer version?

2017-03-29 00:10 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/?LinkId=169513), which also applies to later versions of Visual Stud
same as the previous comment for FwLink 169513

2017-03-29 00:30 UTC, BillWagner commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/?LinkId=169513), which also applies to later versions of Visual Stud
I think the second would be the best to link to. 

And, yes, we should merge these in time.

2017-03-29 00:40 UTC, mairaw commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/?LinkId=169513), which also applies to later versions of Visual Stud
@GuardRex can you please open an issue for this then? Thanks!

2017-03-29 00:41 UTC, GuardRex commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/?LinkId=169513), which also applies to later versions of Visual Stud
Sure ... will do.

2017-03-29 00:45 UTC, GuardRex commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/?LinkId=169513), which also applies to later versions of Visual Stud
https://github.com/dotnet/docs/issues/1821

2017-03-29 01:39 UTC, mairaw reviewed
Looks good. A few comments.

2017-03-29 01:39 UTC, mairaw commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Expression Trees (C#)](../../../../csharp/programming-guide/concepts/expression-trees/index.md), which also applies to later versions of Visual Studio.
I just noticed we're linking to the topic itself. Sorry. 
So maybe let's just keep the change as you previously made here and in the vb topic and then we should check if we cover the subject of the blog post on the docs or not. I prefer not to link to stale content.

2017-03-29 01:39 UTC, mairaw commented on docs/csharp/programming-guide/interop/walkthrough-office-programming.md
> +     This code demonstrates several of the new features in C#: the ability to omit the `ref` keyword in COM programming, named arguments, and optional arguments. These features already exist in Visua
remove en-us from the link

2017-03-29 01:52 UTC, GuardRex commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Expression Trees (C#)](../../../../csharp/programming-guide/concepts/expression-trees/index.md), which also applies to later versions of Visual Studio.
:smile: ... For more information, *re-read this topic!*

![draith2](https://cloud.githubusercontent.com/assets/1622880/24434964/2ca661c2-13f8-11e7-9d3e-9763b57c147f.jpg)


"Tell Dexeter we've come full circle!" - First Decider Draith (Leonard Maguire) Dr. Who: Full Circle, 1980

How about this one? https://msdn.microsoft.com/en-us/library/mt654263.aspx

2017-03-29 02:02 UTC, GuardRex commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Expression Trees (C#)](../../../../csharp/programming-guide/concepts/expression-trees/index.md), which also applies to later versions of Visual Studio.
I mean there is nothing else to point to "for more information" if this is all of the information.

2017-03-30 23:25 UTC, mairaw commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> + For more information, see [Expression Trees (C#)](../../../../csharp/programming-guide/concepts/expression-trees/index.md), which also applies to later versions of Visual Studio.
I meant, your first change looked like this:
```markdown
For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/?LinkId=169513), which also applies to later versions of Visual Studio.
```
So if that blog post contains useful information that we don't have in our docs, it should probably be added as an official topic. Makes sense? So my suggestion was to keep the link to the blog post for now.

2017-03-31 00:41 UTC, mairaw commented on docs/csharp/programming-guide/concepts/expression-trees/index.md
> +For more information, see [Generating Dynamic Methods with Expression Trees in Visual Studio 2010](http://go.microsoft.com/fwlink/p/?LinkId=169513), which also applies to later versions of Visual Stu
same thing for the vb version of this topic

2017-03-31 00:41 UTC, mairaw approved these changes
One last thing and you can merge 🎆

2017-03-31 00:45 UTC, GuardRex commented
> One last thing

I wouldn't make any rash judgments given my performance today! :cry:

2017-03-31 00:48 UTC, merged