Added example w.r.t. you can use the `typeof` expression along with `…
dotnet/docs pull request #1829
Opened 2017-03-30 19:46 UTC by peteraritchie

…nameof` for clarity

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-03-30 19:46 UTC, dnfclas commented
@peteraritchie,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-03-31 15:43 UTC, rpetrusha requested changes
Thanks for adding the code examples, @peteraritchie! We'll merge if you can made one small correction to the first example.

2017-03-31 15:43 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/nameof.md
> +void f(int i) {
Could you wrap this in the C class as you did in the next example so that it can be compilable?

2017-03-31 22:05 UTC, peteraritchie commented
Sure

2017-03-31 23:59 UTC, peteraritchie commented
Changes made @rpetrusha.

2017-04-03 16:38 UTC, rpetrusha approved these changes
Thanks for making the change, @peteraritchie

2017-04-03 16:38 UTC, merged