Update cqrs-microservice-reads.md
dotnet/docs pull request #18335
Opened 2020-05-09 15:47 UTC by aymanizz

## Summary

Ordering microservice changed to use static ViewModels instead of dynamic ones in [this PR](https://github.com/dotnet-architecture/eShopOnContainers/pull/380).

2020-05-09 18:46 UTC, aymanizz commented
If this is in reference to the implementation in the docs (not the latest implementation on the repo) then this change might not be needed (besides there is already a tip explaining the change.)

If that's the case, I do think that the wording could be improved to something like `as implemented below`?

2020-08-28 12:19 UTC, IEvangelist commented on docs/architecture/microservices/microservice-ddd-cqrs-patterns/cqrs-microservice-reads.md
> +The ViewModels can be static types defined in classes (as is implemented in the ordering microservice.) Or they can be created dynamically based on the queries performed, which is very agile for deve
```suggestion
The ViewModels can be static types defined in classes (as is implemented in the ordering microservice). Or they can be created dynamically based on the queries performed, which is very agile for developers.
```

2020-08-28 12:20 UTC, IEvangelist requested changes
Corrected the placement of the `.`

2020-09-01 15:13 UTC, BillWagner commented
@IEvangelist I think your requests have been addressed. Can you check, and merge if so?

2020-09-01 15:35 UTC, IEvangelist approved these changes
Looks good to me, we'll :shipit: - thank you 🙏

2020-09-01 15:35 UTC, merged