Add project files to best-practices samples
dotnet/docs pull request #18390
Opened 2020-05-12 23:42 UTC by Youssef1313

2020-05-13 15:14 UTC, IEvangelist requested changes
Please fix this one aspect of the pull request, and we should be able to continue reviewing it. Thank you

2020-05-13 15:14 UTC, IEvangelist commented on docs/standard/base-types/best-practices-strings.md
>  - For string concatenation, do not allow the compiler to perform any implicit conversions. Instead, perform an explicit conversion by calling a `ToString` overload that has a `provider` parameter. Fo
```suggestion
- For string concatenation, do not allow the compiler to perform any implicit conversions. Instead, perform an explicit conversion by calling a `ToString` overload that has a `provider` parameter. For example, the compiler implicitly uses the current culture when converting a <xref:System.Double> value to a string in the following code:
```

Remove the **C#** callout here and just call it code, as you've added VB.

2020-05-13 18:27 UTC, Youssef1313 commented on docs/standard/base-types/best-practices-strings.md
>    Instead, you can explicitly specify the culture whose formatting conventions are used in the conversion by calling the <xref:System.Double.ToString(System.IFormatProvider)?displayProperty=nameWithT
```suggestion
  Instead, you can explicitly specify the culture whose formatting conventions are used in the conversion by calling the <xref:System.Double.ToString(System.IFormatProvider)?displayProperty=nameWithType> method, as the following code does:
```

2020-05-14 16:06 UTC, Thraka commented
This looks like an opportunity to move the snippet out of the samples folder and into a snippets folder with the article.

2020-05-14 20:38 UTC, Youssef1313 commented
> 
> 
> This looks like an opportunity to move the snippet out of the samples folder and into a snippets folder with the article.
> 
> https://docs.microsoft.com/en-us/contribute/dotnet/dotnet-contribute#example-structure

I've moved them

2020-05-15 12:41 UTC, IEvangelist approved these changes
Looks good to me :shipit:

2020-05-15 12:43 UTC, merged