Base-types folder migration cleanup
dotnet/docs pull request #1867
Opened 2017-04-09 00:56 UTC by tdykstra

Moved changes from docs-internal; deleted earlier versions of base-types docs with truncated names, changed .NET Framework to .NET in newly migrated docs.  Another PR by @tompratt-AQ will do the redirects from the short names to the long names.

2017-04-10 17:14 UTC, tompratt-AQ commented
[PR 1869](https://github.com/dotnet/docs/pull/1869) covers the redirects.

2017-04-10 21:00 UTC, guardrex requested changes

2017-04-10 21:00 UTC, GuardRex commented on docs/standard/base-types/common-type-system.md
> + A structure is a value type that derives implicitly from <xref:System.ValueType?displayProperty=fullName>, which in turn is derived from <xref:System.Object?displayProperty=fullName>. A structure is
> In .NET class library, ...

In .NET class libraries, ...

or

In a .NET class library, ...

... and the comma splice in the previous sentence almost knocked me right out of my chair. :grinning:

2017-04-10 21:00 UTC, GuardRex commented on docs/standard/base-types/trimming.md
> +# Trimming and Removing Characters from Strings in the .NET Framework
Trimming and Removing Characters from Strings in .NET

2017-04-10 21:04 UTC, GuardRex commented
@tdykstra I only see :eyes: two here. I wish I was that good. :+1:

2017-04-10 21:14 UTC, GuardRex commented on docs/standard/base-types/trimming.md
> +# Trimming and Removing Characters from Strings in the .NET Framework
... and the title as well. Did you leave this one alone on purpose?

2017-04-10 21:30 UTC, GuardRex commented
@tdykstra Was the plan to catch-up on titles for TOC later? ... here's one, but there might be more lurking out there ...
```
### [.NET Framework Regular Expressions](regular-expressions.md)
```
Line 33 at https://github.com/dotnet/docs/edit/master/docs/standard/base-types/toc.md

2017-04-10 21:34 UTC, tdykstra commented
@GuardRex No, I missed that.  I'll fix that and review toc.md,

2017-04-10 22:07 UTC, guardrex approved these changes

2017-04-10 22:07 UTC, GuardRex commented on docs/standard/base-types/trimming.md
> +title: "Trimming and Removing Characters from Strings  in .NET | Microsoft Docs"
Nit: double-space before "in"

2017-04-10 22:08 UTC, GuardRex commented on docs/standard/base-types/trimming.md
> +title: "Trimming and Removing Characters from Strings  in .NET | Microsoft Docs"
why do I do this ... genetic mutation? :alien: ... probably!

2017-04-10 23:01 UTC, GuardRex commented
@tdykstra Thanks ... @wadepickett is going to either ❤️ me or 🔫 me for this, but I'm determined not to have @mairaw come back to a PR insanity! :grinning:

2017-04-11 00:14 UTC, merged

2017-04-11 01:55 UTC, tdykstra commented
Thanks, @GuardRex, it'll be ❤️ not 🔫

Stale PRs are a breeding ground for merge conflicts.

2017-04-11 01:59 UTC, GuardRex commented
> Stale PRs are a breeding ground for merge conflicts.

Tom, we're so on the same wavelength here ... @mairaw should come back to *FEWER* unmerged PR's than she left us with. For our kindred spirit, let's end the vacation on a high note 🎵 🎷.