restoring well formatted sections in what's new
dotnet/docs pull request #1868
Opened 2017-04-09 07:15 UTC by mairaw

Last migration had some issues. Restoring well formed links and tokens from the previous version.

2017-04-09 19:22 UTC, guardrex requested changes
I put the nits in here; but if these little changes are for another time, I get it. We can do an old skool grammar/style pass later. If that's the case, there is very little to address here.

2017-04-09 19:22 UTC, GuardRex commented on docs/framework/whats-new/index.md
> +           <binding>
Nit: 2-space indent

2017-04-09 19:22 UTC, GuardRex commented on docs/framework/whats-new/index.md
> +            </appSettings>
Nit: 2-space indent

2017-04-09 19:22 UTC, GuardRex commented on docs/framework/whats-new/index.md
> +    </appSettings>
Nit: 2-space indent

2017-04-09 19:22 UTC, GuardRex commented on docs/framework/whats-new/index.md
> +     The method may be used by an enlistment that was previously created by <xref:System.Transactions.Transaction.EnlistPromotableSinglePhase%2A?displayProperty=fullName> in response to the <xref:Sys
Nit: Two spaces before "This method can ..." near the bottom.

2017-04-09 19:22 UTC, GuardRex commented on docs/framework/whats-new/index.md
> +    -   The new  <xref:System.Activities.WorkflowIdentity> class, which provides a mapping between a persisted workflow instance and its workflow definition.
Nit: Two spaces after "new"

2017-04-09 19:34 UTC, mairaw commented on docs/framework/whats-new/index.md
> + This article does not provide comprehensive information about each new feature and is subject to change. For general information about the .NET Framework, see [Getting Started](../../../docs/framewo
this is a migration behavior. we can decide which one to use and change links for consistency later.

2017-04-09 19:39 UTC, mairaw commented on docs/framework/whats-new/index.md
> + For a list of new APIs added to the [!INCLUDE[net_v462](../../../includes/net-v462-md.md)], see [.NET Framework 4.6.2 API Changes](https://github.com/Microsoft/dotnet/blob/master/releases/net462/dot
a lot of the migrated topics suffer from extra spaces in the beginning and in the end

2017-04-09 19:43 UTC, mairaw commented on docs/framework/whats-new/index.md
> + The [!INCLUDE[net_v462](../../../includes/net-v462-md.md)] includes new features in the following areas:
I just brought what was the original behavior which is like that. You'll see some of the include files that use the product codename for example. I think in this case the token was created when we already knew the product name/version, so it shows like that.

2017-04-09 19:44 UTC, mairaw commented on docs/framework/whats-new/index.md
> + Data annotation validators enable you to perform validation by adding one or more attributes to a class property. The attribute's <xref:System.ComponentModel.DataAnnotations.ValidationAttribute.Erro
No, the * means the link is going to the overload page instead of going to the specific overload. It was the default behavior in our old tool.

2017-04-09 19:46 UTC, mairaw commented
My goal here was to reduce the number of broken links. I won't have time to address the nits now. My suggestion would be to merge this once the build finishes and then address the nits on a separate PR. This brings the total warnings on our build report from 911 down to 866 and this is an important topic.

2017-04-09 20:16 UTC, guardrex approved these changes

2017-04-09 20:21 UTC, GuardRex commented
@mairaw Looks like build report is showing three:

* Warning	Unspecified	docs/framework/whats-new/index.md	Invalid file link:(\~/docs/framework/whats-new/Windows Forms Configuration Section.md).	Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save	128	04/09/2017 19:57:03
* Warning	Unspecified	docs/framework/whats-new/index.md	Invalid file link:(\~/docs/framework/whats-new/High DPI Support In Windows Forms.md).	Build Document.LinkPhaseHandlerWithIncremental.ConceptualDocumentProcessor.Save	128	04/09/2017 19:57:03
* Warning	Unspecified	docs/framework/whats-new/index.md	Invalid file link:(\~/docs/framework/whats-new/sql/relational-databases/security/encryption/always-encrypted-client-development).

2017-04-10 14:51 UTC, mairaw commented
Fixed those 3, I think. I won't be able to check the others that don't show in the report but look weird on staging (under a table that lists ECDiffieHellman methods) since I'm going offline now. Please squish and merge this when build completes and continue to make improvements on a new PR.

2017-04-10 15:58 UTC, merged