39). Add topic files 123 to 126
dotnet/docs pull request #18700
Opened 2020-05-29 17:56 UTC by jameshkramer

This PR is for user story #1576037.

It adds four article files, makes corresponding deletions from the C# and VB folders, and adds redirection entries. It also provides fixes to toc.yml and some article files.

Please merge #18413, #18439, #18541, #18580, #18589, and #18673 before merging this.

cc: @BillWagner @mairaw @tfosmark @marteeleigh

Contributes to #4728

2020-06-03 17:16 UTC, Thraka commented
Just curious, why do we care if there is or isn't quotes around the title?

2020-06-03 17:53 UTC, jameshkramer commented
@Thraka, my reason for removing the quotes is not very substantial, but here it is. Quotes are only required around the title (or description) if there is a colon in it. So, if they are not required, I prefer they not be there, consistently. What it comes down to is simply that I like consistency in general, and in this case just because it is neater.

2020-06-15 15:49 UTC, BillWagner commented
@jameshkramer After a quick look, this is fine.  I'll review more carefully after resolving the conflicts.

2020-06-23 19:18 UTC, mairaw commented
@jameshkramer can you resolve the conflicts here so we can review and merge? Thx!

2020-06-23 19:38 UTC, jameshkramer commented
@mairaw 

The conflicts are resolved

2020-06-23 19:57 UTC, mairaw requested changes
Some quick suggestions to address

2020-06-23 19:57 UTC, mairaw commented on docs/standard/linq/atomized-xname-xnamespace-objects.md
> + This example produces the following output:
```suggestion
This example produces the following output:
```

2020-06-23 19:57 UTC, mairaw commented on docs/standard/linq/wordprocessingml-document-styles.md
> +To understand styles it's helpful to know something about document structure. A WordprocessingML document is stored in a *package* that comprises *parts*. Specifically, the term *package* corresponds
```suggestion
To understand styles, it's helpful to know something about document structure. A WordprocessingML document is stored in a *package* that comprises *parts*. Specifically, the term *package* corresponds to a ZIP archive and the term *part* corresponds to a file stored within the ZIP. If a document contains paragraphs that are formatted with styles, there will be a document part that contains paragraphs that have styles applied to them, and a style part that defines the styles referenced in the document part.
```

2020-06-23 20:36 UTC, mairaw approved these changes
LGTM

2020-06-23 20:36 UTC, merged