Migration: Update docs/framework/install/guide-for-developers
dotnet/docs pull request #1882
Opened 2017-04-12 06:41 UTC by GuardRex

2017-04-12 13:42 UTC, GuardRex commented
@rpetrusha ready for review+merge.

2017-04-12 17:57 UTC, rpetrusha requested changes
Again, some issues with link targets.

2017-04-12 17:57 UTC, rpetrusha commented on docs/framework/install/guide-for-developers.md
> +>  For information on the .NET Framework 3.5, see [Installing the .NET Framework 3.5 on Windows 8 and later versions](~/docs/framework/install/dotnet-35-windows-10.md).
The link you've provided is a user installation topic, not a developer installation topic. The correct link is [Installing the .NET Framework 3.5 on Windows 8, Windows 8.1 and Windows 10](net-framework-3-5-on-windows-8-plus.md).

2017-04-12 17:57 UTC, rpetrusha commented on docs/framework/install/guide-for-developers.md
> + [Installing the .NET Framework 3.5 on Windows 8 and later versions](~/docs/framework/install/dotnet-35-windows-10.md)
Again, the wrong topic. The correct link is above.

2017-04-13 16:15 UTC, rpetrusha approved these changes
LGTM.

2017-04-13 16:16 UTC, merged