Markdownlint problem matcher
dotnet/docs pull request #18896
Opened 2020-06-11 03:24 UTC by nschonni

## Summary
Allows the lines to be directly flagged in the GitHub UI when there is a markdownlint issue

2020-06-11 03:25 UTC, nschonni commented
I added a commit to show how it looks when files aren't touched in the PR, but have flagged issues. I'll rebase it off and undraft if this looks OK

2020-06-11 03:26 UTC, nschonni commented
In case you can't see it because it's a beta feature
![image](https://user-images.githubusercontent.com/1297909/84341733-d87dd200-ab71-11ea-89db-c0a5737ae2bc.png)

2020-06-11 17:40 UTC, Thraka approved these changes
I like it.

2020-06-11 18:00 UTC, tdykstra requested changes
This PR enables MD004 but we discussed this as a team and decided to leave it turned off.

2020-06-11 19:24 UTC, nschonni commented on .markdownlint.json
> -    "MD004": false,
Yes, this was just added in a WIP commit to show the matching

2020-06-11 20:19 UTC, nschonni commented
Rebased out the test commit and marked this ready for review. You can see the screenshot above as a reference for what it'll look like

2020-06-11 20:20 UTC, tdykstra approved these changes
Thanks!

2020-07-01 03:35 UTC, nschonni commented
Any blockers on this landing?

2020-07-01 17:42 UTC, adegeo commented
LGTM

2020-07-01 17:46 UTC, merged