SEODescriptionAdditions: User Story 1657424, part4
dotnet/docs pull request #19054
Opened 2020-06-22 21:54 UTC by damabe

## Summary

https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1657424

2020-06-26 15:06 UTC, adegeo requested changes
Thanks! Some minor issues to take care of.

2020-06-26 15:06 UTC, adegeo commented on docs/framework/winforms/controls/how-to-anchor-and-dock-child-controls-in-a-flowlayoutpanel-control.md
> +description: Learn how to programatically anchor and dock child controls in a Windows Forms FlowLayoutPanel control.
I'm seeing this spelling error in quite a few places.

```suggestion
description: Learn how to programmatically anchor and dock child controls in a Windows Forms FlowLayoutPanel control.
```

2020-06-26 15:06 UTC, adegeo commented on docs/framework/winforms/advanced/how-to-create-mdi-parent-forms.md
> +description: Learn how to create MDI parent Windows Forms programatically and by using the Windows Forms Designer.
```suggestion
description: Learn how to create an MDI parent form programmatically and by using the Windows Forms Designer.
```

2020-06-26 15:06 UTC, adegeo commented on docs/framework/winforms/advanced/how-to-print-a-windows-form.md
> +description: Learn how to programatically print a copy of the current Windows Form by using the CopyFromScreen method.
```suggestion
description: Learn how to programmatically print a copy of the current Windows Form by using the CopyFromScreen method.
```

2020-06-26 15:06 UTC, adegeo commented on docs/framework/winforms/controls/how-to-view-multiple-lines-in-the-windows-forms-textbox-control.md
> +description: Learn how to view multiple lines in the Windows Forms TextBox control by setting the Multiline, WordWrap, and ScrollBars properties to appropriate values.
This change feels a bit better.
```suggestion
description: Learn how to view multiple lines in the Windows Forms TextBox control by setting the Multiline, WordWrap, and ScrollBars properties.
```

2020-06-26 22:51 UTC, damabe commented
@adegeo Thanks for the review. I've made the changes. Please sign off or merge. I don't have sign off permissions on this repo.

2020-07-08 05:40 UTC, damabe commented
@adegeo Gentle reminder to review the updates and sign off when ready.

2020-07-08 15:48 UTC, adegeo approved these changes

2020-07-08 15:49 UTC, adegeo commented
👍 Sorry about that.

2020-07-08 15:49 UTC, merged