Added missing summary description
dotnet/docs pull request #1917
Opened 2017-04-14 20:45 UTC by slobo80

The summary is missing important bit of info that is present on the old site at https://msdn.microsoft.com/en-us/library/system.web.httpresponse.setcookie(v=vs.110).aspx

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-04-14 20:45 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-04-14 21:24 UTC, rpetrusha commented
Thanks, @slobo80, for adding the missing internal-only boilerplate. Unfortunately, this is part of a more general problem that in migrating from our existing authoring system to GitHub, all information on internal-only types and members was not migrated.
We'll still merge your PR if you can make one change. The first and second sentences will in the same paragraph, and so the internal-only text will not clearly stand out. Could you add a `<br/>` at the end of the first sentence?

2017-04-14 21:50 UTC, rpetrusha requested changes
Change requested in previous comment.

2017-04-15 03:28 UTC, GuardRex commented on xml/System.Web/HttpResponse.xml
> +        <summary>Because the <b>HttpResponse.SetCookie</b> method is intended for internal use only, you should not call it in your code. Instead, you can call the <b>HttpResponse.Cookies.Set</b> met
Change `HttpResponse.Cookies.Set` to `HttpResponse.Cookies.Add`

2017-04-15 04:38 UTC, slobo80 commented on xml/System.Web/HttpResponse.xml
> +        <summary>Because the <b>HttpResponse.SetCookie</b> method is intended for internal use only, you should not call it in your code. Instead, you can call the <b>HttpResponse.Cookies.Set</b> met
Are you sure? Add is for adding a new cookie whereas Set is for updating the existing cookie in the collection per https://msdn.microsoft.com/en-us/library/system.web.httpcookiecollection.set(v=vs.110).aspx

2017-04-15 05:16 UTC, GuardRex commented on xml/System.Web/HttpResponse.xml
> +        <summary>Because the <b>HttpResponse.SetCookie</b> method is intended for internal use only, you should not call it in your code. Instead, you can call the <b>HttpResponse.Cookies.Set</b> met
Depends on what @rpetrusha wants to do: The original C# snippet was for `Response.Cookies.Add(MyCookie);`. He called for `Add()` in https://github.com/dotnet/docs/pull/1915#issuecomment-294248842.

2017-04-15 05:17 UTC, slobo80 commented on xml/System.Web/HttpResponse.xml
> +        <summary>Because the <b>HttpResponse.SetCookie</b> method is intended for internal use only, you should not call it in your code. Instead, you can call the <b>HttpResponse.Cookies.Set</b> met
The original was wrong as well. :(

2017-04-15 05:24 UTC, GuardRex commented on xml/System.Web/HttpResponse.xml
> +        <summary>Because the <b>HttpResponse.SetCookie</b> method is intended for internal use only, you should not call it in your code. Instead, you can call the <b>HttpResponse.Cookies.Set</b> met
I'm inclined to agree with you, but let's hold for a sec until @rpetrusha comes back to make a ruling on it.

2017-04-17 20:33 UTC, rpetrusha approved these changes

2017-04-17 20:33 UTC, merged

2017-04-17 20:34 UTC, rpetrusha commented
Thanks for making the changes, @slobo80!

2017-04-17 20:34 UTC, slobo80 commented
My pleasure @rpetrusha ! :)