twelve meta descriptions for app dev
dotnet/docs pull request #19238
Opened 2020-06-26 18:13 UTC by LauraKellerGitHub

https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1657392

Adding meta descriptions to topics

2020-06-26 23:25 UTC, adegeo requested changes
Thank you for these changes! I left some small suggestions for you.

2020-06-26 23:25 UTC, adegeo commented on docs/framework/wpf/data/how-to-implement-property-change-notification.md
> +description: Enable your binding target properties to automatically reflect the dynamic changes of the binding source in Windows Presentation Foundation (WPF).
I think this is a bit clearer.
```suggestion
description: Enable your properties to automatically notify a binding source when the property value changes in Windows Presentation Foundation (WPF).
```

Is it possible for you to also edit the intro paragraph? It seems completely incomprehensible. It looks like there was some update at some point that merged two intros.

I think that intro should change to:

```
To support <xref:System.Windows.Data.BindingMode.OneWay> or <xref:System.Windows.Data.BindingMode.TwoWay> binding and enable your binding target properties to automatically reflect the changes of the binding source .......
```

2020-06-26 23:25 UTC, adegeo commented on docs/framework/wpf/data/how-to-specify-the-binding-source.md
> +description: Find out about ways to specify the binding source through this example in the Windows Presentation Foundation (WPF).
I think this is a bit clearer.
```suggestion
description: Learn how to specify the binding source through this example in the Windows Presentation Foundation (WPF).
```

2020-06-29 02:46 UTC, LauraKellerGitHub commented on docs/framework/wpf/app-development/dialog-boxes-overview.md
> +description: Learn about the varieties of dialog boxes in Windows Foundation Presentation (WPF). Find out about menu bars, status bars and tool bars.
There's a require for the character count to be between 100 and 160 characters. Will this 134-character description work?  Learn about the varieties of dialog boxes in Windows Foundation Presentation (WPF) that you can use to gather and display information.

2020-06-29 02:48 UTC, LauraKellerGitHub commented
@adegeo 
Thanks for your review and feedback. I've changed four descriptions as shown.
The description for dialog-boxes-overview.md was too short according to our requirement of 100 to 160 characters. See what you think of the rewrite, which is 134 characters.
Thanks!

2020-06-29 17:53 UTC, adegeo commented
Looks good, thanks!!!

2020-06-29 17:53 UTC, adegeo approved these changes

2020-06-29 17:53 UTC, merged