[WIP] Migration: winforms & wpa group updates
dotnet/docs pull request #1928
Opened 2017-04-17 18:41 UTC by GuardRex

**WIP** Hold off on review. I need to check the report and review the table updates after it builds.

2017-05-01 07:18 UTC, mairaw commented on docs/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element.md
>  ### Attributes
i've noticed this topic and some others are missing the ms.prod value which is a required metadata. we should file an issue to take care of that.

2017-05-01 07:18 UTC, mairaw commented on docs/framework/winforms/high-dpi-support-in-windows-forms.md
> +In addition to running on .NET Framework 4.7 and Windows 10 Creators Update, you application may also run in an environment in which it's not compatible with high DPI improvements. In this case, you'
your application seemed correct here

2017-05-01 07:18 UTC, mairaw commented on docs/framework/wpf/advanced/the-ink-object-model-windows-forms-and-com-versus-wpf.md
> +|Load Ink|Create a <xref:System.Windows.Ink.StrokeCollection> with the <xref:System.Windows.Ink.StrokeCollection.%23ctor%2A> constructor.|[Microsoft.Ink.Ink.Load](https://msdn.microsoft.com/library/m
wondering if we should perhaps add this api to the https://github.com/dotnet/docs/blob/master/_zip/missingapi.yml file. Or at least I'd link to version that is linked to the TOC: https://msdn.microsoft.com/en-us/library/microsoft.ink.ink.load(v=vs.90).aspx

2017-05-01 08:51 UTC, GuardRex commented on docs/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element.md
>  ### Attributes
https://github.com/dotnet/docs/issues/2061

2017-05-01 08:53 UTC, GuardRex commented on docs/framework/winforms/high-dpi-support-in-windows-forms.md
> +In addition to running on .NET Framework 4.7 and Windows 10 Creators Update, you application may also run in an environment in which it's not compatible with high DPI improvements. In this case, you'
yep ... typo ... thx

2017-05-01 09:17 UTC, GuardRex commented on docs/framework/wpf/advanced/the-ink-object-model-windows-forms-and-com-versus-wpf.md
> +|Load Ink|Create a <xref:System.Windows.Ink.StrokeCollection> with the <xref:System.Windows.Ink.StrokeCollection.%23ctor%2A> constructor.|[Microsoft.Ink.Ink.Load](https://msdn.microsoft.com/library/m
Link updated. Noted API in Migration Project for additional work.

2017-05-16 19:57 UTC, rpetrusha requested changes
@Guardrex, can you add the top-level file-schema/winforms/index.md to your PR? The syntax section for the `ConfigurationSection` element has `\<` for both the begin and end tags. Also, the first entry int he "See also" section needs to be terminated by 3 spaces. Also, the element name is System.Windows.Forms.ApplicationConfigurationSection.

2017-05-16 20:30 UTC, GuardRex commented
@rpetrusha 

> add the top-level file-schema/winforms/index.md

... in *docs\framework\configure-apps\toc.md*? If so, then updates are complete.

2017-05-16 21:09 UTC, rpetrusha requested changes
The major issue here is that the documentation was inconsistent in the name of the config element. The correct name is `System.Windows.Forms.ApplicationConfigurationSection`.

2017-05-16 21:09 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element.md
> +<System.Windows.Forms.ConfigurationSection>
The original is correct in both cases (ApplicationConfigurationSection, not ConfigurationSection)

2017-05-16 21:09 UTC, rpetrusha commented on docs/framework/winforms/high-dpi-support-in-windows-forms.md
> +  Windows Forms introduces a new [`<System.Windows.Forms.ConfigurationSection>`](../../../docs/framework/configure-apps/file-schema/winforms/index.md) element to support new features and customizatio
ApplicationConfigurationSection is correct.

2017-05-16 21:09 UTC, rpetrusha commented on docs/framework/winforms/high-dpi-support-in-windows-forms.md
> +  <System.Windows.Forms.ConfigurationSection>
`ApplicationConfigurationSection ` is correct in both cases.

2017-05-16 21:09 UTC, rpetrusha commented on docs/framework/winforms/high-dpi-support-in-windows-forms.md
> +<System.Windows.Forms.ConfigurationSection>
The original `ApplicationConfigurationSection` is correct in both cases.

2017-05-16 21:23 UTC, GuardRex commented
@rpetrusha Updates complete.

2017-05-16 22:03 UTC, rpetrusha reviewed
Sorry, @GuardRex, I missed one ConfigurationSection -> ApplicationConfigurationSection.

2017-05-16 22:03 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/winforms/index.md
> +  <System.Windows.Forms.ConfigurationSection>
ApplicationConfigurationSection for both line 23 and line 25

2017-05-16 22:09 UTC, GuardRex commented on docs/framework/configure-apps/file-schema/winforms/index.md
> +  <System.Windows.Forms.ConfigurationSection>
Lines 17, 51, and 53 look like they need this change, too.

2017-05-16 22:11 UTC, GuardRex commented on docs/framework/configure-apps/file-schema/winforms/index.md
> +  <System.Windows.Forms.ConfigurationSection>
... and same thing with lines 68 and 70 in *windows-forms-add-configuration-element.md*.

2017-05-17 20:45 UTC, rpetrusha commented on docs/framework/configure-apps/toc.md
> +## [Windows Forms Configuration Section](winforms/index.md)
This should be removed -- Windows Forms configuration section is a child of Configuration file schema, and it's already listed in the Configuration file schema topic.

2017-05-17 20:45 UTC, rpetrusha commented on docs/framework/configure-apps/toc.md
> +## [Windows Forms Configuration Section](winforms/index.md)
This should be removed. The topic is a parent of the Configuration file schema topic, and it already appears both in the TOC and as a link from that topic.

2017-05-17 20:46 UTC, rpetrusha approved these changes
@GuardRex, aside from my comment about the TOC entry, this looks good. After you address the TOC issue, you can merge this when the build completes.

2017-05-18 01:53 UTC, merged