Fix Asset IDs and esolve xrefs for TODO messages.
dotnet/docs pull request #1943
Opened 2017-04-18 01:09 UTC by tompratt-AQ

# Title
Fix Asset IDs and resolve xrefs for TODO messages.

## Summary
This resolves issues from PR 1886 which replaced some assetid: tags with TODO messages containing xrefs for entity references that needed to be confirmed and entered correctly in the topics.

PR1886 should now be closed and replaced by this PR.

## Suggested Reviewers
@rpetrusha

2017-04-18 18:36 UTC, rpetrusha requested changes

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/add-of-backuplist.md
> + [<xref:System.ServiceModel.Routing.Configuration.BackupEndpointElement>
this should include "?displayProperty=fullName" I think that the opening bracket needs to be removed as well.

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/add-of-entries.md
> + <xref:System.ServiceModel.Routing.Configuration.RoutingSection>
Again, both of these should include ?displayProperty=fullName

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/add-of-namespacetable.md
> + <xref:System.ServiceModel.Routing.Configuration.NamespaceElement>
This should also include "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/add-of-protocolmapping.md
> + <xref:System.ServiceModel.Configuration.ProtocolMappingSection>
Both of these should include  "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/backuplist.md
> + <xref:System.ServiceModel.Routing.Configuration.BackupEndpointCollection>
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/backuplists.md
> + <xref:System.ServiceModel.Routing.Configuration.BackupEndpointCollection>
This should include "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/bookmarkresumptionqueries-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElementCollection>
again,  "?displayProperty=fullName" for both of these

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/bookmarkresumptionquery-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.BookmarkResumptionQueryElementCollection>
"?displayProperty=fullName" for both of these

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/cancelrequestedquery-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.CancelRequestQueryElement>
"?displayProperty=fullName" for both of these.

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/customtrackingqueries-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElementCollection>
"?displayProperty=fullName" for both.

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/customtrackingquery-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.CustomTrackingQueryElementCollection>
"?displayProperty=fullName" for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/entries.md
> + <xref:System.ServiceModel.Routing.Configuration.RoutingSection>
"?displayProperty=fullName" for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/faultpropagationqueries-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElementCollection>
"?displayProperty=fullName" for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/faultpropagationquery-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.FaultPropagationQueryElement>
"?displayProperty=fullName" for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/filter.md
> +<xref:System.ServiceModel.Routing.Configuration.FilterElement>
All three of these should have  "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/filters-of-routing.md
> + <xref:System.ServiceModel.Routing.Configuration.FilterElement>
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/filtertable.md
> + <xref:System.ServiceModel.Routing.Configuration.RoutingSection>
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/filtertables.md
> + <xref:System.ServiceModel.Routing.Configuration.RoutingSection>
"?displayProperty=fullName" for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/namespacetable.md
> + <xref:System.ServiceModel.Routing.Configuration.NamespaceElementCollection>
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/protocolmapping.md
> + <xref:System.ServiceModel.Configuration.ProtocolMappingSection>
"?displayProperty=fullName" for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/routing.md
> + <xref:System.ServiceModel.Routing.Configuration.RoutingSection>
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/servicedebug.md
> +|httpHelpPageBinding|A string value that specifies the type of binding to be used when HTTP is utilized to access the service help page.<br /><br /> Only bindings with inner binding elements that sup
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/servicedebug.md
> +|httpsHelpPageBinding|A string value that specifies the type of binding to be used when HTTPS is utilized to access the service help page.<br /><br /> Only bindings with inner binding elements that s
The last two xrefs should be  "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/servicedebug.md
> + The optional `httpHelpPageBinding` and `httpHelpPageBinding` attributes allow you to configure the bindings used to access the service web page. If they are not specified, the default bindings (`Htt
The last two xrefs should include  "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/state-of-wcf-workflowinstancequery.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement>
All three should include "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/states-of-wcf-workflowinstancequery.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement>
All three should include "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/tracking-of-wcf.md
> - [System.ServiceModel.Activities.Tracking.Configuration.TrackingSection](assetId:///System.ServiceModel.Activities.Tracking.Configuration.TrackingSection?qualifyHint=False&amp;autoUpgrade=True)
add "?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/workflowinstancequeries-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElementCollection>
add "?displayProperty=fullName"  to both xrefs

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/workflowinstancequeries-of-wcf.md
> + <xref:System.Activities.Tracking.WorkflowInstanceQuery>
"?displayProperty=fullName"

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/workflowinstancequery-of-wcf.md
> + <xref:System.ServiceModel.Activities.Tracking.Configuration.WorkflowInstanceQueryElement>
"?displayProperty=fullName"  for both

2017-04-18 18:36 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/wcf/workflowinstancequery-of-wcf.md
> + <xref:System.Activities.Tracking.WorkflowInstanceQuery>
"?displayProperty=fullName"

2017-04-18 18:40 UTC, rpetrusha commented
I went through about half of these in detail, but where the fully qualified name appears in brackets, such as [System.ServiceModel.SomeType](<assetId:T:System.ServiceModel.Routing.Configuration.RoutingSection>), this should be translated either as [System.ServiceModel.SomeType](<xref:System.ServiceModel.Routing.Configuration.RoutingSection>) or, preferably, as <xref:System.ServiceModel.Routing.Configuration.RoutingSection?displayProperty=fullName>.

A second issue, which I've noticed in a number of the topics, is that when there are multiple See Also items, there must be three spaces at the end of a line that is followed by another item. Otherwise, they'll be rendered on a single line.

2017-04-18 21:37 UTC, tompratt-AQ commented
@rpetrusha  I went through all the changes and made corrections as you suggested. All of my fixes, except for two, are in See Also links where I completely missed adding the display=fullname and adding 3 spaces at the end of the line in some cases.

2017-04-19 19:41 UTC, rpetrusha approved these changes

2017-04-19 19:41 UTC, rpetrusha commented
Thanks, @tompratt-AQ. This is ready to merge.

2017-04-19 19:42 UTC, merged

2017-04-21 18:36 UTC, GuardRex commented
@rpetrusha

> A second issue, which I've noticed in a number of the topics, is that when there are multiple See Also items, there must be three spaces at the end of a line that is followed by another item. Otherwise, they'll be rendered on a single line.

Just learning this. Over on the ASP.NET Core side, every "See also/Additional resources" list is a bullet list, so it wasn't an issue. I just spoke with @mairaw, and I'll go with 3-spaces, no blank lines between resources, and no bullets over here. I'm running through all of my open PR's now to correct this.

2017-04-21 19:18 UTC, rpetrusha commented
@GuardRex, sorry that I didn't notice that -- it's something I always forget about until I eventually see topics published live.

2017-04-21 19:20 UTC, GuardRex commented
@rpetrusha It was ok ... only one doc on one PR needed a fix ... it was the one we're just about to merge: The wcf migration links update. I **definitely** want to go back and make a pass over merged PR's to see if I ... er ... "fixed" :grinning: ... any other "See also" lists. I'll get 'um patched in a new PR if I find any.