1657389 Add descriptions for SEO (series of related PRs)
dotnet/docs pull request #19571
Opened 2020-07-17 21:23 UTC by TimShererWithAquent

## Add descriptions for SEO

For anyone that GitHub notifies, this is for [1657389](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1657389).

You're welcome but not required, according to KhairunJ's guidance, to review these proposed meta descriptions. I'll leave this PR open for 48 hours and address any feedback. After that, we'll sign off for merge. Thanks!

Please keep in mind our 100-160 char length for descriptions.

Fixes #1657392

2020-07-17 21:31 UTC, TimShererWithAquent commented
Closing and reopening to try to clear that failed check. Not familiar with that, but maybe a restart will clear it.

2020-07-17 21:31 UTC, TimShererWithAquent commented
And reopen.

2020-07-20 17:30 UTC, BillWagner requested changes
Thanks @TimShererWithAquent 

I had a few comments on some of the descriptions. Once those are addressed, I'll :shipit:

2020-07-20 17:30 UTC, BillWagner commented on docs/csharp/programming-guide/classes-and-structs/named-and-optional-arguments.md
> +description: Named arguments in C# specify arguments by name, not position. Optional arguments can be omitted. Named & optional arguments facilitate calls to COM interfaces.
Let's drop the last sentence. Named and optional arguments will be much more useful for records (coming in C# 9)
```suggestion
description: Named arguments in C# specify arguments by name, not position. Optional arguments can be omitted.
```

2020-07-20 17:30 UTC, BillWagner commented on docs/csharp/programming-guide/classes-and-structs/nested-types.md
> +description: A type defined within a class, struct, or interface is called a nested type in C#. Nested types are accessible only from their containing type.
The last sentence is incorrect. (If they have the default, `private`, access, it's true.)

```suggestion
description: A type defined within a class, struct, or interface is called a nested type in C#. 
```

2020-07-20 17:30 UTC, BillWagner commented on docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md
> +description: Object initializers in C# assign values to accessible fields or properties of an object at creation without invoking a constructor and assignment statements.
In this context, object initializers are executed *after* the constructor:

```suggestion
description: Object initializers in C# assign values to accessible fields or properties of an object at creation after invoking a constructor.
```

2020-07-20 17:30 UTC, BillWagner commented on docs/csharp/programming-guide/classes-and-structs/objects.md
> +description: C# uses a class or struct definition to create an object. In an object-oriented language such as C#, a program consists of objects interacting dynamically.
Definitions don't create an object:

```suggestion
description: C# uses a class or struct definition to define types of objects. In an object-oriented language such as C#, a program consists of objects interacting dynamically.
```

2020-07-20 17:30 UTC, BillWagner commented on docs/csharp/programming-guide/classes-and-structs/private-constructors.md
> +description: A private constructor is a special instance constructor in C#, generally used in classes that contain static members only.
There are other good uses for private constructors. (factory methods, etc). Let's leave it open in the description.

```suggestion
description: A private constructor is a special instance constructor in C# used to restrict how an object can be created. They may be used with factory methods or other construction idioms.
```

2020-07-20 17:41 UTC, BillWagner approved these changes

2020-07-20 17:42 UTC, BillWagner commented
Thanks @TimShererWithAquent 

FYI: From the "files" tab, you can add all the suggestions to a batch and add them in one commit.

2020-07-20 17:42 UTC, merged