[WIP] Migration: migration-guide & whats-new updates
dotnet/docs pull request #1957
Opened 2017-04-18 20:19 UTC by GuardRex

**WIP** Hold on review until checks/updates are complete.

2017-05-01 22:29 UTC, mairaw commented on docs/framework/migration-guide/net-compatibility-diagnostics.md
> +|Affected APIs|<xref:System.Linq.Enumerable.Empty%60%601%2A?displayProperty=fullName>|
although the link now works, it seems to be an issue with the build system. why this method requires the *? I see that the page shows ms.assetid with the * but seems wrong somehow.

2017-05-01 22:46 UTC, GuardRex commented on docs/framework/migration-guide/net-compatibility-diagnostics.md
> +|Affected APIs|<xref:System.Linq.Enumerable.Empty%60%601%2A?displayProperty=fullName>|
Yep ... let me revert. The build report lied ... the original link works. https://docs.microsoft.com/en-us/dotnet/articles/framework/migration-guide/net-compatibility-diagnostics#42-enumerableemptytresult-always-returns-cached-instance

2017-05-18 16:56 UTC, rpetrusha requested changes
@GuardRex, can you also add one more topic to this PR? In docs/framework/migration-guide/retargeting-changes-in-the-net-framework-4-7.md, there's a link to BringIndexInfoView(Int32) between the header and the table that should be removed.

2017-05-18 16:56 UTC, rpetrusha commented on docs/framework/migration-guide/mitigation-cspparameters-parentwindowhandle-expects-an-hwnd.md
>  - By programmatically setting compatibility switches on the <xref:System.Security.AppContext> instance.
This also should be `<xref:System.Security.AppContext>`.

2017-05-18 16:56 UTC, rpetrusha commented on docs/framework/migration-guide/runtime-changes-in-the-net-framework-4-6-2.md
> +| <xref:System.Web.HttpRuntime.AppDomainAppPath%2A> | In the .NET Framework 4.6.2, the runtime throws a <xref:System.NullReferenceException> when retrieving an <xref:System.Web.HttpRuntime.AppDomainA
The xref to AppDomainAppPath should include `?displayProperty=fullname`

2017-05-18 16:56 UTC, rpetrusha commented on docs/framework/whats-new/obsolete-members.md
> +|<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.GetDragDropCompletedEffects%2A>|First deprecated in the .NET Framewo
@GuardRex, I had meant to address this issue for quite some time, but it's fallen on the back burner. I've finally started to investigate. AFAIK, the recommended alternative method doesn't actually exist in the release versions of the .NET Framework.

2017-05-18 19:10 UTC, GuardRex commented on docs/framework/whats-new/obsolete-members.md
> +|<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.GetDragDropCompletedEffects%2A>|First deprecated in the .NET Framewo
It should be *GetDragDropMovedViewElements*: https://referencesource.microsoft.com/#System.Activities.Presentation/System.Activities.Presentation/System/Activities/Presentation/DragDropHelper.cs,673

... but *GetDragDropMovedViewElements* isn't public as the obsolete notes states ...
https://referencesource.microsoft.com/#System.Activities.Presentation/System.Activities.Presentation/System/Activities/Presentation/DragDropHelper.cs,710

2017-05-18 19:10 UTC, GuardRex commented
@rpetrusha 

> In docs/framework/migration-guide/retargeting-changes-in-the-net-framework-4-7.md, there's a link to BringIndexInfoView(Int32) between the header and the table that should be removed.

I don't see it. Even a global search for "BringIndexInfoView" of all docs on my branch doesn't find it. Where is it?

2017-05-18 19:27 UTC, rpetrusha commented
@GuardRex, I'm sorry -- it's in Runtime Changes in the .NET Framework 4.7 (docs/framework/migration-guide/runtime-changes-in-the-net-framework-4-7.md), and the API is BringIndexIntoView. I used to be able to type without error...

2017-05-18 19:28 UTC, rpetrusha commented on docs/framework/whats-new/obsolete-members.md
> +|<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.GetDragDropCompletedEffects%2A>|First deprecated in the .NET Framewo
@Guardrex, thanks for looking in the source.

2017-05-18 19:42 UTC, GuardRex commented on docs/framework/whats-new/obsolete-members.md
> +|<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.GetDragDropCompletedEffects%2A>|First deprecated in the .NET Framewo
@rpetrusha I performed a broader Internet search as well and didn't turn anything up on the depreciation of these. In a case like this, what's the next step? ... and do we hold this PR for further updates or does this become a new issue?

2017-05-18 19:45 UTC, GuardRex commented on docs/framework/whats-new/obsolete-members.md
> +|<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.GetDragDropCompletedEffects%2A>|First deprecated in the .NET Framewo
I guess the low-hanging fruit is to put a note in the project to address this. I'll do that now.

2017-05-19 16:10 UTC, rpetrusha commented on docs/framework/whats-new/obsolete-members.md
>  |<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.DoDragMove%28System.Activities.Presentation.WorkflowViewElement%2CSy
The obsolete text should read, "This method does not support dragging multiple items."

2017-05-19 16:10 UTC, rpetrusha commented on docs/framework/whats-new/obsolete-members.md
>  |<xref:System.Activities.Presentation.DragDropHelper?displayProperty=fullName>|<xref:System.Activities.Presentation.DragDropHelper.SetDragDropCompletedEffects%2A>|First deprecated in the .NET Framewo
The obsolete text should red, "This method does not support dragging multiple items."

2017-05-19 17:24 UTC, GuardRex commented
@rpetrusha I removed some stray spaces from lines 322 and 323. As you instructed, I only actually changed the *Message* column text for lines 319, 321, and 324.

2017-05-19 18:02 UTC, rpetrusha approved these changes

2017-05-19 18:02 UTC, rpetrusha commented
@GuardRex, this is ready to merge when the build completes.

2017-05-19 18:45 UTC, GuardRex commented
@rpetrusha It choked on the change to ...
```
<xref:System.Security.AppContext>
```
Should we look to restore that documentation, or should we inline code the reference? I couldn't find it. I only see: https://referencesource.microsoft.com/#mscorlib/system/AppContext/AppContext.cs,24

The other one, `System.Windows.Controls.VirtualizingStackPanel.IsVirtualizing` was known and listed for further investigation in the project.

It's private ...

https://referencesource.microsoft.com/#PresentationFramework/Framework/System/Windows/Controls/VirtualizingStackPanel.cs,11126

Because the text is just mentioning virtualization in passing to make a behavioral point ...

> When an <xref:System.Windows.Controls.ItemsControl> displays a collection using virtualization (<xref:System.Windows.Controls.VirtualizingStackPanel.IsVirtualizing%2A> = `true`) and item-scrolling ...

... I suggest we inline code the ref with (set privately) on it ...

> When an <xref:System.Windows.Controls.ItemsControl> displays a collection using virtualization [`VirtualizingStackPanel.IsVirtualizing` = `true` (set privately)] and item-scrolling ...

... or using whatever alternative language you'd like to see there.

2017-05-22 20:09 UTC, GuardRex commented
@rpetrusha I updated the ref to `System.Security.AppContext` to inline code, since that content doesn't exist in the API docs. I used ...

> [\`VirtualizingStackPanel.IsVirtualizing\` = \`true\` (set privately)]\`

... for the `IsVirtualizing` prop, which also doesn't exist due to its `private` access.

If those moves are ok, it should be ready to go.

2017-05-22 21:03 UTC, rpetrusha commented
It's not System.Security.AppContext. It's System.AppContext. That should resolve in an <xref>. With that change, you can merge.

2017-05-22 21:05 UTC, GuardRex commented
I had it that way initially. I must have misunderstood tho what you wanted changed: https://github.com/dotnet/docs/pull/1957#discussion_r117291487

2017-05-22 21:09 UTC, rpetrusha commented
I think that I confused myself. I meant that it should also be System.AppContext, but that's not what I wrote.

2017-05-23 02:23 UTC, merged