fix token in summary
dotnet/docs pull request #1958
Opened 2017-04-19 08:40 UTC by yishengjin1413

# Fix token in summary

To fix CSI bug 966058:[.NET API Browser] Token is not shown correctly in description of API browser page, flattened the token reference in summary node under docs.

2017-04-19 17:24 UTC, rpetrusha requested changes
Thanks for flattening these tokens, @yishengjin1413. Would you mind making a four changes? "Microsoft .NET Framework" should simply be ".NET Framework".

2017-04-19 17:24 UTC, rpetrusha commented on xml/Microsoft.Windows.Themes/ButtonChrome.xml
> +    <summary>Creates the theme-specific look for Microsoft .NET Framework <see cref="T:System.Windows.Controls.Button" /> elements.</summary>
Microsoft .NET Framework --> .NET Framework

2017-04-19 17:24 UTC, rpetrusha commented on xml/Microsoft.Windows.Themes/ListBoxChrome.xml
> +    <summary>Creates the theme-specific look for Microsoft .NET Framework <see cref="T:System.Windows.Controls.ListBox" /> elements.</summary>
Microsoft .NET Framework --> .NET Framework

2017-04-19 17:24 UTC, rpetrusha commented on xml/Microsoft.Windows.Themes/PlatformCulture.xml
> +    <summary>Provides culture-specific information used by the Microsoft .NET Framework system themes.</summary>
Microsoft .NET Framework --> .NET Framework

2017-04-19 17:24 UTC, rpetrusha commented on xml/Microsoft.Windows.Themes/ScrollChrome.xml
> +    <summary>Creates the theme-specific look for Microsoft .NET Framework <see cref="T:System.Windows.Controls.Primitives.ScrollBar" /> elements.</summary>
Microsoft .NET Framework --> .NET Framework

2017-04-21 22:55 UTC, mairaw commented
I've edited the files via GitHub UI so we can merge this after builds are completed successfully.

2017-04-28 16:31 UTC, mairaw approved these changes

2017-04-28 17:04 UTC, rpetrusha approved these changes

2017-04-28 17:06 UTC, merged