Corrected collection initializer requirements
dotnet/docs pull request #1961
Opened 2017-04-19 18:12 UTC by svick

According to the previous wording, code like `new C { 1 }` should compile, as long as `C` has an extension method called `Add` that takes an `int` parameter, even if `C` does not implement `IEnumerable`. But it doesn't, according to [the spec](https://github.com/dotnet/csharplang/blob/master/spec/expressions.md#collection-initializers):

> The collection object to which a collection initializer is applied must be of a type that implements `System.Collections.IEnumerable` or a compile-time error occurs. For each specified element in order, the collection initializer invokes an `Add` method on the target object with the expression list of the element initializer as argument list, applying normal member lookup and overload resolution for each invocation. Thus, the collection object must have an applicable instance or extension method with the name `Add` for each element initializer.

While here, I have also added missing language identifiers.

cc: @DavidArno

2017-04-20 22:10 UTC, rpetrusha requested changes
Thanks for noticing these inaccuracies, @svick! Just a couple of corrections.

2017-04-20 22:10 UTC, rpetrusha commented on docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md
> + Collection initializers let you specify one or more element initializers when you initialize a collection type that implements <xref:System.Collections.IEnumerable> and has `Add` with appropriate si
with appropriate signature --> with the appropriate signature
as instance method or extension method --> as an instance method or an extension method

2017-04-20 22:13 UTC, svick commented
@rpetrusha Updated.

2017-04-21 00:40 UTC, rpetrusha approved these changes
Thanks, @svick!

2017-04-21 00:40 UTC, merged