1657389 Add descriptions for SEO (series of related PRs)
dotnet/docs pull request #19650
Opened 2020-07-23 14:56 UTC by TimShererWithAquent

## Add descriptions for SEO

For anyone that GitHub notifies, this is for [1657389](https://dev.azure.com/mseng/TechnicalContent/_workitems/edit/1657389).

You're welcome but not required, according to KhairunJ's guidance, to review these proposed meta descriptions. I'll leave this PR open for 48 hours and address any feedback. After that, we'll sign off for merge. Thanks!

Please keep in mind our 100-160 char length for descriptions.

Fixes #1657389

2020-07-23 14:58 UTC, TimShererWithAquent commented
There was a build failure. I'm going to close and reopen.

2020-07-23 14:58 UTC, TimShererWithAquent commented
And reopen.

2020-07-27 14:09 UTC, BillWagner requested changes
Thanks @TimShererWithAquent 

I have one requested change. I'll try and commit that and :shipit: it.

2020-07-27 14:09 UTC, BillWagner commented on docs/csharp/programming-guide/concepts/linq/sample-xml-file-customers-and-orders-in-a-namespace.md
>  title: "Sample XML File: Customers and Orders in a Namespace2"
Not related to your PR. Let's delete the erroneous "2":

```suggestion
title: "Sample XML File: Customers and Orders in a Namespace"
```

2020-07-27 14:09 UTC, BillWagner approved these changes

2020-07-27 14:16 UTC, merged