SQL Dependency for distributed caches
dotnet/docs pull request #19669
Opened 2020-07-24 10:57 UTC by mohsinnasir

Providing sample for keeping SQL database and distributed cache synchronized using SQL dependency

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2020-08-04 06:34 UTC, mohsinnasir commented
@stevestein Any update Regarding the PR

2020-08-13 10:16 UTC, mohsinnasir commented
@stevestein Reminder Regarding the PR

2020-08-27 07:29 UTC, mohsinnasir commented
@stevestein Kindly review the pull request . If there are any suggestions do tell me.

2020-08-27 15:03 UTC, rothja commented
@mohsinnasir Thanks for the suggested edit. I'm reviewing it and will get back to you soon. #reassign:rothja

2020-08-27 15:04 UTC, rothja commented
#assign:rothja

2020-08-31 07:07 UTC, mohsinnasir commented
@rothja Thanks I ill be waiting and do let me know if there are any changes

2020-08-31 13:35 UTC, rothja commented
@mohsinnasir Thanks for the ping on this one. My only concern on this section is that it points off to a third-party solution, which could be seen as a recommendation or preference for this solution. Do you know if this is a preferred solution by Microsoft (for example maybe we blogged about it or wrote about it on other sites)? If not, the way we typically do this is to refer to the type of solution and then say, ", such as <third-party solution>" and we would not make it its own H2. Let me know if you have any more details and I then I'll suggest an edit to get it synced with our documentation standards. Thanks!

2020-09-01 06:05 UTC, mohsinnasir commented
@rothja Thanks for a quick response. However this section does not only points to thirdparty rather an architecture that is currently unavailable by the Microsoft distributed cache implementation. There are multiple distributed caches and Microsoft's Azure cache for redis does not have any feature to use SQL dependency for distributed caches. So, the documentation should have a place where a user knows there is a thirdparty which provides SQL dependency with distributed caches as well.

One more thing just like Mircosoft ASP.NET Core SignalR, it dosent have the support to provide backplane because it is only in memory so it mentions to provide SignalR backplane use Azure cache for redis or other thirdparties like mentioned [here](https://docs.microsoft.com/en-us/aspnet/signalr/overview/getting-started/introduction-to-signalr).

Built-in providers include:

Service Bus
SQL Server
Redis
Third-party providers include:

NCache.

2020-09-01 15:28 UTC, rothja commented
@mohsinnasir Thanks for the explanation. I see how this could benefit readers to know about. Let me talk to the product team with this additional information, and I'll let you know what we recommend.

2020-09-08 15:30 UTC, IEvangelist requested changes
Hi 👋 
Thank you so much for posting this issue. We really appreciate it. I have a few minor nits.

2020-09-08 15:30 UTC, IEvangelist commented on docs/framework/data/adonet/sql/sqldependency-in-an-aspnet-app.md
> +- [Distributed Cache SQL Dependency Sample](https://github.com/Alachisoft/NCache-Samples/tree/master/dotnet/Dependencies/SQLDependency)
```suggestion
## Distributed cache synchronization using SQL Dependency

Some of the third-party distributed caches such as [NCache](https://www.alachisoft.com/ncache) provide support to synchronize the SQL database and cache using [SQL Dependency](https://www.alachisoft.com/resources/docs/ncache/prog-guide/sql-dependency.html). For more information and an example source code implementation, see [Distributed cache SQL Dependency sample](https://github.com/Alachisoft/NCache-Samples/tree/master/dotnet/Dependencies/SQLDependency).
```

2020-09-09 05:50 UTC, mohsinnasir commented
@IEvangelist Thanks for taking the time for reviewing it. I have reviewed the the suggestions and agree with them. Kindly review the changes and let me know if there are any other changes required.

2020-09-09 11:37 UTC, IEvangelist approved these changes
Looks good to me, we'll :shipit: - thank you 🙏

2020-09-09 11:41 UTC, IEvangelist commented
Hey @rothja - noticed that you were waiting to hear back from the product team on this. What did you hear?

2020-09-09 17:59 UTC, rothja commented
@IEvangelist David, yes I got approval from the product team to put this change in. Thank you, @mohsinnasir for your patience.

2020-09-09 18:00 UTC, merged