Update snippet links
dotnet/docs pull request #19811
Opened 2020-08-04 03:00 UTC by tsmarvin

Updated snippet links - The snippets still arent rendering for me but at least the links go to the right place.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2020-08-04 14:11 UTC, BillWagner requested changes
Thanks for making these fixes @tsmarvin 

I checked the review site, and I have a few suggestions that should fix the snippet rendering. Once you accept those suggestions, I'll :shipit:

Thanks again!

2020-08-04 14:11 UTC, BillWagner commented on docs/csharp/programming-guide/main-and-command-args/main-return-values.md
> + [!code-csharp[csProgGuideMain#12](~../../../../../../samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideMain/CS/Class3.cs#12)]
Can you remove the `~` character and the first two `..` paths: here:

```suggestion
 [!code-csharp[csProgGuideMain#12](../../../../samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideMain/CS/Class3.cs#12)]
```

2020-08-04 14:11 UTC, BillWagner commented on docs/csharp/programming-guide/main-and-command-args/main-return-values.md
> + [!code-csharp[csProgGuideMain#13](~../../../../../../samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideMain/CS/Class3.cs#13)]
same:

```suggestion
 [!code-csharp[csProgGuideMain#13](../../../../samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideMain/CS/Class3.cs#13)]
```

2020-08-04 14:11 UTC, BillWagner commented on docs/csharp/programming-guide/main-and-command-args/main-return-values.md
> + [!code-csharp[csProgGuideMain#14](~../../../../../../samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideMain/CS/Class3.cs#14)]
same:

```suggestion
 [!code-csharp[csProgGuideMain#14](../../../../samples/snippets/csharp/VS_Snippets_VBCSharp/csProgGuideMain/CS/Class3.cs#14)]
```

2020-08-04 20:42 UTC, Youssef1313 commented
@BillWagner, I see the current live already renders the snippets correctly.

2020-08-06 05:41 UTC, tsmarvin commented
Apologies for the delay - work has been hectic.

2020-08-17 22:09 UTC, adegeo commented
@BillWagner I think these got ninja fixed by something else. As @Youssef1313 said, these are currently displaying correctly.

2020-09-01 16:27 UTC, BillWagner commented
I'll close this because all snippets are rendering correctly.

2020-09-01 16:27 UTC, closed without merging