Added values of WindowStartupLocation enum
dotnet/docs pull request #1991
Opened 2017-04-24 18:37 UTC by yeremee

# Title

Added values of WindowStartupLocation enum

2017-04-24 18:37 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-04-24 18:48 UTC, rpetrusha requested changes
@yeremee, thanks for fixing this! Could you also make one more change?

2017-04-24 18:48 UTC, rpetrusha commented on docs/framework/wpf/app-development/wpf-windows-overview.md
>   If the startup location is specified as                  <xref:System.Windows.WindowStartupLocation>, and the                  <xref:System.Windows.Window.Left%2A> and                  <xref:System.
@yeremee, would you mind also changing this to <xref:System.WIndows.WindowStartupLocation.Manual?displayProperty=fullName>?

2017-04-26 22:15 UTC, mairaw commented
@rpetrusha how about we merge this one and continue the changes on a separate PR? there are more links to enum fields missed in the conversion.

2017-04-26 23:23 UTC, rpetrusha commented
@mairaw, yes, I agree.

2017-04-26 23:23 UTC, rpetrusha approved these changes

2017-04-26 23:23 UTC, merged

2017-04-27 23:11 UTC, yeremee commented on docs/framework/wpf/app-development/wpf-windows-overview.md
>   If the startup location is specified as                  <xref:System.Windows.WindowStartupLocation>, and the                  <xref:System.Windows.Window.Left%2A> and                  <xref:System.
Ok.