Document API's for Application Insights/Azure diagnostics
dotnet/docs pull request #2000
Opened 2017-04-24 23:15 UTC by GuardRex

TFS: 406224

2017-04-24 23:37 UTC, mairaw reviewed
Overall it looks great. I let some comments for you, @GuardRex.

2017-04-24 23:37 UTC, mairaw commented on docs/framework/additional-apis/_httpresponse.md
> +# _HttpResponse Field
you need to escape the underscore (`\_`)

2017-04-24 23:37 UTC, mairaw commented on docs/framework/additional-apis/_httpresponse.md
> +caps.latest.revision: 3
you can remove this metadata and the other empty ones we don't generally use. they come with the migrated topics

2017-04-24 23:37 UTC, mairaw commented on docs/framework/additional-apis/_httpresponse.md
> +  - "System.Net"
API Name needs to be the unique API identifier. So in this case it should be System.Net.HttpWebRequest._HttpResponse.

2017-04-24 23:37 UTC, mairaw commented on docs/framework/additional-apis/_httpresponse.md
> +ms.topic: "article"
the "template" topics got incorrectly migrated to articles when they were converted to MarkDown. the ms.topic value should be reference.

2017-04-24 23:37 UTC, mairaw commented on docs/framework/additional-apis/_httpresponse.md
> +  - "dotnet-winforms"
leave this empty or remove it. I need to ask to create a value for NCL.

2017-04-24 23:52 UTC, GuardRex commented
@mairaw Ready for another look :eyes:

2017-04-25 17:52 UTC, mairaw commented
Please fix the apiscan metadata the same way we did in https://github.com/dotnet/docs/pull/2007 asnd also add an extra metadata called topic_type with the value apiref. I'll review it this afternoon!

2017-04-25 18:25 UTC, GuardRex commented
@mairaw :rocket:

2017-04-25 19:38 UTC, GuardRex commented
I have a question in to Liudmila, so I've marked this **WIP** for a moment until I hear back from her.

Otherwise, I included `Connection` and `ConnectionGroup` and made a few other minor updates.

2017-05-01 23:20 UTC, mairaw commented
You're getting some warnings for the metadata. api_type and topic_type expect an array, so you get that very "helpful" message: unexpected type String for metadata api_type, the expected type is string 😄 

For now, just break into a new line like we had to do with PR #2007

2017-05-01 23:23 UTC, GuardRex commented
Will add ...

`HttpWebRequest._AutoRedirects`
Counts number of redirects  made off this HttpWebRequest
http://referencesource.microsoft.com/#System/net/System/Net/HttpWebRequest.cs,386b7e101de743c6,references

2017-05-01 23:35 UTC, mairaw requested changes
Already left a few comments and adding some more. Overall LGTM!

2017-05-01 23:35 UTC, mairaw commented on docs/framework/additional-apis/_httpresponse.md
> +# \_HttpResponse Field
For the member pages, I'm thinking we should add the class name to the title too similar to an automated generated page: https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualbasic.constants.vbapplicationmodal?view=netframework-4.6.2

2017-05-01 23:35 UTC, mairaw commented on docs/framework/additional-apis/s_servicepointtable.md
> +`ServicePointManager.s_ServicePointTable` is a <xref:System.​Collections.​Hashtable> that contains the list of active HTTP connections (<xref:System.​Net.​Service​Point>s) in the <xref:System.​App​Do
that's odd. the xref links are not resolving here. maybe it's a build issue?

2017-05-01 23:35 UTC, mairaw commented on docs/framework/additional-apis/toc.md
> +## [s_ServicePointTable Field](../../../docs/framework/additional-apis/s_servicepointtable.md)
perhaps we could add the namespace as entry to the TOC now without any topic attached. I think it would increase readability.

2017-05-01 23:53 UTC, GuardRex commented on docs/framework/additional-apis/s_servicepointtable.md
> +`ServicePointManager.s_ServicePointTable` is a <xref:System.​Collections.​Hashtable> that contains the list of active HTTP connections (<xref:System.​Net.​Service​Point>s) in the <xref:System.​App​Do
Probably a separate problem; but when I paste `System.​Collections.​Hashtable` into the API Browser search box, it's coming back "No results." When I type in the ref starting with "System" it works.

Let's see what happens now that I'm fixing the metadata and re-building soon.

2017-05-02 00:09 UTC, mairaw commented on docs/framework/additional-apis/s_servicepointtable.md
> +`ServicePointManager.s_ServicePointTable` is a <xref:System.​Collections.​Hashtable> that contains the list of active HTTP connections (<xref:System.​Net.​Service​Point>s) in the <xref:System.​App​Do
I'll open a bug for that. I can repro that.

2017-05-02 00:15 UTC, GuardRex commented
@mairaw I alphabetized the TOC with namespaces.

2017-05-02 00:16 UTC, GuardRex commented
Stand-by a sec ... It still doesn't like that underscore unless it's escaped in the heading.

2017-05-03 08:31 UTC, mairaw submitted a review, later dismissed
We should also add the syntax block similar to this one:
https://docs.microsoft.com/en-us/dotnet/articles/framework/additional-apis/datamemberlisteditor-class

2017-05-03 08:31 UTC, mairaw commented on docs/framework/additional-apis/toc.md
> +## [System.Net.Connection Class](../../../docs/framework/additional-apis/connection.md)
I'd prefer the TOC node that just opens and close since the full name in the TOC doesn't render too well

2017-05-03 16:49 UTC, GuardRex commented
@mairaw 

* Shortened the TOC names
* Added syntax blocks
* Went to sentence case titles (although I know ur planning to run [@]spboyer's script for that globally)
* Made the internal/private warning on preexisting topics match the new ones
* Few other formatting changes (mostly line spacing)

2017-05-11 20:05 UTC, GuardRex commented
@mairaw This would be ready, but it's not clear why (showing one for example) ...

> Invalid cross reference "&lt;xref:System.​Net.​Service​Point&gt;".

`System.Net.ServicePoint` is fine: https://docs.microsoft.com/en-us/dotnet/api/system.net.servicepoint?view=netframework-4.7

I'll try a rebuild.

2017-05-11 22:11 UTC, GuardRex commented
@mairaw I'll bet you $10 bucks this is failing due to invisible :ghost: characters! I'll see what's what.

2017-05-11 22:17 UTC, GuardRex commented
![capture](https://cloud.githubusercontent.com/assets/1622880/25974244/9ada3c44-366d-11e7-9660-0f63fe35780a.PNG)

😠 Where's my :gun:!!!?????

2017-05-12 02:45 UTC, GuardRex commented
@mairaw Refs fixed. This one is ready for another look :eyes:.

2017-05-24 22:30 UTC, mairaw commented
Did you copy the text from the API page title? I've opened a bug for them re. weird characters there and it's due to this:
![image](https://cloud.githubusercontent.com/assets/12971179/26428200/3c988faa-4095-11e7-8d45-18597ca9f89e.png)
Although yours doesn't seem like it.

I'm not seeing the changes to the TOC as I'm expecting. I'll go ahead and submit a new commit and we can discuss whether we like that or not. 😄

2017-05-24 22:34 UTC, GuardRex commented
@mairaw 

> copy the text from the API page title

I admit it took a few bad experiences with cut-and-paste to conclude that **CUT-AND-PASTE SUCKS!** :angry: ... Yeah, it's not something I'm inclined to do going forward.

> I'll go ahead and submit a new commit and we can discuss whether we like that or not.

Sure :+1: ... hit me up if I need to take further action.

2017-05-24 22:37 UTC, mairaw commented
Apparently I can't type commit messages. 😄 

When build is done, let's take a look and send that around to the thread to see if folks approve it.

2017-05-24 22:39 UTC, GuardRex commented
> namepasces

I thought that was the Brazilian spelling! :grinning:

2017-05-25 00:21 UTC, mairaw commented
I don't even know how people say this in Brazil. They might just use the English spelling for this one.

BTW, I've changed the capitalization of Class and Field in the TOC since for API titles we're still using title case: https://docs.microsoft.com/en-us/dotnet/api/system.accessviolationexception?view=netframework-4.6.2. Can you fix that in the topics themselves?

2017-05-25 00:22 UTC, GuardRex commented
> Can you fix that in the topics themselves?

Sure ... I'll do it right after the uid fix commit goes in.

2017-05-25 00:23 UTC, mairaw commented on docs/framework/additional-apis/datamemberlisteditor-class.md
> -This API supports the product infrastructure and is not intended to be used directly from your code.
this is a boilerplate that we use in these situations. I'd keep it here.

2017-05-25 04:08 UTC, GuardRex commented
@mairaw I capitalized "field" and "class" in the files. I left the TOC alone.

2017-05-30 22:14 UTC, rpetrusha commented
Closing and re-opening to kick off a new build.
@GuardRex, is this ready to merge if the build succeeds?

2017-05-30 22:16 UTC, GuardRex commented
@rpetrusha Yes, I made the [@]miaraw updates, so I think we're good to go after the build finishes.

2017-05-30 22:37 UTC, rpetrusha approved these changes

2017-05-30 23:51 UTC, merged