Fix a typo
dotnet/docs pull request #20046
Opened 2020-08-14 00:13 UTC by nabeel-InfoTrack

## Summary

This Pull Request will fix a small typing error in the original article. "_that the topic could **easy** take several books_" should be written like "_that the topic could **easily** take several books_".

Fixes #Issue_Number (if available)

2020-08-14 00:16 UTC, mairaw requested changes
Thanks @nabeel-InfoTrack. I've noticed this sentence could be further improved. Do you mind applying my suggestion as well? Thanks

2020-08-14 00:16 UTC, mairaw commented on docs/architecture/microservices/secure-net-microservices-web-applications/index.md
> +There are so many aspects about security in microservices and web applications that the topic could easily take several books like this one so, in this section, you'll focus on authentication, author
```suggestion
There are so many aspects about security in microservices and web applications that the topic could easily take several books like this one. So, in this section, we'll focus on authentication, authorization, and application secrets.
```

2020-08-19 04:25 UTC, gewarren commented
@mairaw Can you recheck this one?

2020-08-19 04:40 UTC, mairaw approved these changes
Thanks @nabeel-InfoTrack!

2020-08-19 04:40 UTC, merged