[DO NOT MERGE] removing articles from URL
dotnet/docs pull request #2012
Opened 2017-04-25 17:38 UTC by mairaw

Need to test if the configuration I've applied on docfx.json was done correctly.

2017-04-25 17:53 UTC, BillWagner requested changes
Overall this looks good.
I'm wondering if there is a way in the global redirection file to catch any links from outside the site that contain 'articles' and route them correctly? If not, where do they go?

If we have time, it would be better to use the relative links inside our own docset. Would you agree?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/Fibonacci/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
Wouldn't these be more resilient if we targeted the markdown using a relative link?
e g: ../../tutorials/using-with-xplat-cli.md

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/FibonacciBetter/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/FibonacciBetterMsBuild/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/Hello/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/HelloMsBuild/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/NewTypes/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/NewTypesMsBuild/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli) for creating .NET Core Console Applications. Please see that topic for detail
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/console-apps/fibonacci-msbuild/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/getting-started/unit-testing-using-dotnet-test/README.md
> +This sample is part of the [unit testing tutorial](https://docs.microsoft.com/dotnet/core/testing/unit-testing-with-dotnet-test) for creating applications with unit tests included. See that topic for
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/getting-started/unit-testing-using-mstest/README.md
> +This sample is part of the [unit testing tutorial](https://docs.microsoft.com/dotnet/core/testing/unit-testing-with-mstest) for creating applications with unit tests included. See that topic for deta
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/hosting/README.md
> +This sample demonstrates a very simple .NET Core host. It is part of the [.NET Core hosting tutorial](https://docs.microsoft.com/en-us/dotnet/core/tutorials/netcore-hosting). Please see that topic fo
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/core/hosting/README.md
> +1. Build a simple .NET Core app (like 'hello world') as a [self-contained](https://docs.microsoft.com/en-us/dotnet/core/deploying/#self-contained-deployments-scd) app (since this host looks for corec
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/delegates-and-events/README.md
> +This sample is created during the [Delegates and Events topic](https://docs.microsoft.com/dotnet/csharp/delegates-events)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/expression-trees/README.md
> +This sample is created during the [Expression Trees topic](https://docs.microsoft.com/dotnet/csharp/expression-trees)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/getting-started/console-linq/README.md
> +This sample is created during the [Working with LINQ tutorial](https://docs.microsoft.com/dotnet/csharp/tutorials/working-with-linq) for learning C# features. Please see that topic for detailed steps
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/getting-started/console-teleprompter/README.md
> +This sample is created during the [Console Application Tutorial](https://docs.microsoft.com/dotnet/csharp/tutorials/console-teleprompter)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/getting-started/console-webapiclient/README.md
> +This sample is created during the [REST client tutorial](https://docs.microsoft.com/dotnet/csharp/tutorials/console-webapiclient)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/indexers/README.md
> +This sample is created during the [Indexers](https://docs.microsoft.com/dotnet/csharp/indexers)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/iterators/README.md
> +This sample is created during the [Iterators topic](https://docs.microsoft.com/dotnet/csharp/iterators)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/versioning/new/README.md
> +This sample is created during the [Versioning](https://docs.microsoft.com/dotnet/csharp/versioning)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/csharp/versioning/override/README.md
> +This sample is created during the [Versioning](https://docs.microsoft.com/dotnet/csharp/versioning)
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/framework/libraries/README.md
> +These samples are buildable projects whose source is used for code snippets in [the guide for writing cross-platform libraries](https://docs.microsoft.com/dotnet/core/tutorials/libraries).  They can
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/framework/libraries/README.md
> +It uses the `netstandard1.2` Target Framework Moniker introduced with the [.NET Standard Library](https://docs.microsoft.com/en-us/dotnet/standard/library).
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/framework/libraries/README.md
> +The project under `/net40-library` targets the .NET Framework 4.0 and above.  It also demonstrates how to use [#if](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/preprocessor-dire
relative link?

2017-04-25 17:53 UTC, BillWagner commented on samples/framework/libraries/README.md
> +The project under `/pcl-library` shows how to target a supported PCL Profile (for example, 344).  It shows how to structure the `Library.csproj` file to allow for targeting a PCL.  It also demonstrat
relative link?

2017-04-25 18:05 UTC, rpetrusha approved these changes
LGTM also.

2017-04-25 21:38 UTC, mairaw commented on samples/core/console-apps/Fibonacci/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
@BillWagner these are supposed to be the readme files for the samples. they are not published so if you're looking at this file on your machine, you need the absolute URL.

2017-04-25 21:40 UTC, BillWagner commented on samples/core/console-apps/Fibonacci/README.md
> +This sample is part of the [step-by-step tutorial](https://docs.microsoft.com/dotnet/core/tutorials/using-with-xplat-cli)
@mairaw I need to get my eyes checked. I thought they were in the main doc set.  Not sure what I was seeing...

2017-04-25 21:40 UTC, BillWagner approved these changes

2017-04-25 21:41 UTC, mairaw commented
If I understand the redirection process correctly, any links to https://docs.microsoft.com/en-us/dotnet/articles/* would go to https://docs.microsoft.com/en-us/dotnet/*. This is the part that will be done via Akamai.

We do use relative urls in our repo. The ones I'm fixing were done like this because they are for the readme files. But they would continue to work. I'm just avoiding the redirection by fixing them).

2017-04-25 21:47 UTC, mairaw commented
URLs don't have articles any longer on staging but there are some oddities I'm seeing on the TOC. I'll need to investigate why is that happening. 

![image](https://cloud.githubusercontent.com/assets/12971179/25409246/0d7c2b7c-29c6-11e7-9641-e7796e89276d.png)

2017-05-03 08:14 UTC, mairaw commented
The changes need to be in a branch for the build to fully work (engineering team opened a bug). So merging this one now and opening a new PR to merge against master to test this change.

2017-05-03 08:14 UTC, merged