URI paths on Unix
dotnet/docs pull request #20144
Opened 2020-08-17 22:22 UTC by gewarren

Fixes #19965.

Preview link.

2020-08-18 07:31 UTC, MihaZupan approved these changes
Description LGTM, thanks!

2020-08-18 08:55 UTC, Youssef1313 commented on includes/core-changes/corefx/5.0/non-ascii-chars-in-uri-parsed-correctly.md
> +Uri myuri = new Uri("/üri");
nit

```suggestion
var myUri = new Uri("/üri");
```

2020-08-18 08:58 UTC, Youssef1313 commented on includes/core-changes/corefx/5.0/non-ascii-chars-in-uri-parsed-correctly.md
> +Uri myuri = new Uri("/üri");
I'm unsure if this file will need the BOM character at its beginning or not, since it contains non-ascii (ü).

cc: @sharwell

2020-08-19 15:39 UTC, BillWagner approved these changes
This LGTM @gewarren 

You can :shipit: when ready.

2020-08-20 16:49 UTC, Youssef1313 requested changes

2020-08-20 16:49 UTC, Youssef1313 commented on includes/core-changes/corefx/5.0/non-ascii-chars-in-uri-parsed-correctly.md
> +Console.WriteLine(myuri.AbsoluteUri);
@gewarren I updated the casing with my suggestion and forgot to do it here and next line.

2020-08-20 17:05 UTC, merged