Add missing language identifiers
dotnet/docs pull request #20202
Opened 2020-08-20 13:33 UTC by bradriske

## Summary

Add language identifiers to code blocks specified

Fixes #2192

2020-08-20 14:09 UTC, Youssef1313 requested changes
I've suggested changes where I *think* there is a more appropriate identifier.
If you're unsure of a specific suggestion, we can wait for an official review.

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/add-of-baseaddressprefixfilter.md
> +```text
```suggestion
```http
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/configure-apps/file-schema/wcf/baseaddressprefixfilters.md
> +```text
```suggestion
```http
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/wcf/feature-details/messaging-protocols.md
> +```text
```suggestion
```http
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/wcf/feature-details/messaging-protocols.md
> +```text
```suggestion
```http
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/wcf/feature-details/messaging-protocols.md
> +```text
```suggestion
```http
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/wcf/feature-details/messaging-protocols.md
> +```text
```suggestion
```http
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/wcf/feature-details/workflow-services-overview.md
> +```text
```suggestion
```aspx-csharp
```

2020-08-20 14:09 UTC, Youssef1313 commented on docs/framework/wpf/advanced/globalization-for-wpf.md
> +```xaml
I don't think this is xaml

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/core/testing/unit-testing-using-dotnet-test/csharp/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/core/testing/unit-testing-using-mstest/csharp/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/core/testing/unit-testing-using-nunit/csharp/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/classes-quickstart/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/delegates-and-events/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/events/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/getting-started/console-linq/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/getting-started/console-webapiclient/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/versioning/new/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 14:09 UTC, Youssef1313 commented on samples/snippets/csharp/versioning/override/README.md
> +```console
```suggestion
```dotnetcli
```

2020-08-20 18:05 UTC, tdykstra reviewed
Thanks for this PR. Unfortunately, "text" and "conf" are not valid identifiers. We don't have a good choice for text yet, which is why many of these had been left blank.  The closest is "output", which doesn't fit many of those that are actually just text blocks. I recommend leaving the identifier off text blocks that aren't showing CLI output. At some future date a build validation will require identifiers, and hopefully by then we will have something like "text" available.

2020-08-21 01:39 UTC, bradriske commented
Applied the suggestions and removed the ```conf entries.  After the latest commit there are still 152 lines of ```text in 85 .md files across the repo, should those all get changed to ``` or just leave as is for the later add to allow text type?

2020-08-21 02:20 UTC, tdykstra commented
I would omit the "text" identifier. However, some of the blocks labeled "text" (and some that got labeled "console") are actually showing console output, and for those, "output" is a valid identifier that could be used and would accurately describe the content.

2020-08-23 17:54 UTC, tdykstra commented
It looks like the PR still changes a number of blocks to text, some to console that could be output, and a couple to console that could be left blank.

2020-08-23 19:43 UTC, bradriske commented
That should be it this time

2020-08-23 21:04 UTC, tdykstra approved these changes
Looks good, thanks!

2020-08-23 21:04 UTC, merged