Added Visual Basic tuple documentation
dotnet/docs pull request #2025
Opened 2017-04-26 16:46 UTC by rpetrusha

# Added Visual Basic tuple documentation

## Suggested Reviewers

@BillWagner @AnthonyDGreen

2017-04-26 18:19 UTC, BillWagner requested changes
Overall, this looks great.

I pointed out a couple errors (one of which I'd done in the C# topic tool 😞  I fixed that one in PR #2027, so this helped find that error.

2017-04-26 18:19 UTC, BillWagner commented on docs/visual-basic/programming-guide/language-features/data-types/tuples.md
> +Visual Basic supports assignment between tuple types that have the same number of fields and the same type for each field. Those types must be exact compile-time matches. Other conversions are not co
The second sentence is incorrect. The types of each field don't have to be the same. There must be an implicit conversion from the field type in the right-hand-side tuple to the field type in the left-hand-side tuple.  As a trivial example:

```vb
        Dim longs = (19L, 23L)
        Dim ints = (19, 23)
        longs = ints
```

2017-04-26 18:19 UTC, BillWagner commented on docs/visual-basic/programming-guide/language-features/data-types/tuples.md
> +Visual Basic supports assignment between tuple types that have the same number of fields and the same type for each field. Those types must be exact compile-time matches. Other conversions are not co
And, of course, I made the same mistake in the C# version.  See PR #2027

2017-04-26 18:19 UTC, BillWagner commented on docs/visual-basic/programming-guide/language-features/data-types/tuples.md
> +## Visual Basic tuples and tuples in the .NET Framework
Consider updating the descriptions to compare `System.Tuple` and `System.ValueTuple`. The two types are different. The VB (and C#) teams provided language features that map to System.Tuple.

2017-04-27 00:33 UTC, rpetrusha commented on docs/visual-basic/programming-guide/language-features/data-types/tuples.md
> +## Visual Basic tuples and tuples in the .NET Framework
@BillWagner, language features map to ValueTuple, no?

2017-04-27 00:39 UTC, rpetrusha commented on docs/visual-basic/programming-guide/language-features/data-types/tuples.md
> +## Visual Basic tuples and tuples in the .NET Framework
@BillWagner, I've addressed your comments and modified the example slightly.

2017-04-27 01:10 UTC, BillWagner commented on docs/visual-basic/programming-guide/language-features/data-types/tuples.md
> +## Visual Basic tuples and tuples in the .NET Framework
Yes, Ron you are correct ValueTuple, not Tuple

2017-04-27 01:11 UTC, BillWagner approved these changes

2017-04-30 18:46 UTC, merged