Update defining-default-values-with-the-shouldserialize-and-reset-methods.md
dotnet/docs pull request #20256
Opened 2020-08-24 07:25 UTC by RussKie

## Summary

Make the methods private as those are invoked by convention.

2020-08-24 08:56 UTC, Youssef1313 requested changes
nits

These suggestions can also be applied to other parts of the article.

2020-08-24 08:56 UTC, Youssef1313 commented on docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md
> +private void ResetMyFont() {
```suggestion
private void ResetMyFont()
{
```

2020-08-24 08:56 UTC, Youssef1313 commented on docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md
>     Return Not (thefont Is Nothing)
```suggestion
   Return thefont IsNot Nothing
```

2020-08-24 08:56 UTC, Youssef1313 commented on docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md
> +private bool ShouldSerializeMyFont() {
```suggestion
private bool ShouldSerializeMyFont()
{
```

2020-08-24 08:56 UTC, Youssef1313 commented on docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md
>        Return Not (thefont Is Nothing)
```suggestion
      Return thefont IsNot Nothing
```

2020-08-24 08:56 UTC, Youssef1313 commented on docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md
> +   private bool ShouldSerializeMyFont() {
```suggestion
   private bool ShouldSerializeMyFont()
   {
```

2020-08-24 08:56 UTC, Youssef1313 commented on docs/framework/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods.md
> +   private void ResetMyFont() {
```suggestion
   private void ResetMyFont()
   {
```

2020-09-01 15:34 UTC, BillWagner commented
@RussKie Can you apply the suggestions above? Then, this is ready to merge.

2020-09-02 03:22 UTC, RussKie commented
@BillWagner I can't merge without an approval. 
Squash-merge is recommended.

2020-09-04 13:52 UTC, BillWagner approved these changes
This LGTM @RussKie 

Once you resolve the merge conflicts, this is ready to :shipit:

2020-09-04 23:36 UTC, adegeo commented
@RussKie This content was moved to https://github.com/dotnet/docs-desktop and you'll have to file the PR there. Sorry about that! Bad timing!

@BillWagner fyi, can't fix the merge conflict because the file doesn't exist 😄

2020-09-04 23:36 UTC, closed without merging

2020-09-07 03:46 UTC, RussKie commented
> fyi, can't fix the merge conflict because the file doesn't exist 😄

BOO! 😈 
Here's the new one - https://github.com/dotnet/docs-desktop/pull/34