Update trim-self-contained.md
dotnet/docs pull request #20278
Opened 2020-08-25 17:54 UTC by samsp-msft

## Summary

Broke up big paragraph and provided a bit more detail.
Corrected trim argument.

2020-08-25 17:54 UTC, samsp-msft commented
@jamshedd

2020-08-25 19:03 UTC, LakshanF reviewed
I believe the TrimMode is link for BlazorApps (what was there before)

2020-08-25 20:07 UTC, adegeo requested changes
Some minor things to fix.

2020-08-25 20:07 UTC, adegeo commented on docs/core/deploying/trim-self-contained.md
> +The trim mode for the applications can be configured via the TrimMode and will default (`copyused`) to bundle assemblies that are used in the application. Blazor WebAssembly applications will use a m
Minor wording adjustments. We generally don't put a value in ``(`value`)`` syntax and instead call it out directly.

```suggestion
The trim mode for the applications is configured with the `TrimMode` setting. The default value is `copyused` and bundles referenced assemblies with the application. The `trim` value is used with Blazor WebAssembly applications and trims unused code within assemblies. Trim analysis warnings give information on code patterns where a full dependency analysis was not possible. These warnings are suppressed by default and can be turned on by setting the flag `SuppressTrimAnalysisWarnings` to `false`. For more information about the trim options available, see the [ILLinker page](https://github.com/mono/linker/blob/master/docs/illink-options.md).
```

2020-08-26 17:44 UTC, adegeo approved these changes
LGTM thanks!

2020-08-26 17:44 UTC, merged