New content for VB 2017
dotnet/docs pull request #2059
Opened 2017-04-30 20:15 UTC by rpetrusha

# New content for VB 

## Summary

Changed order of What's New items, added What's New for VB 2017, documented ref return values and added examples.

This PR replaces an earlier PR that I closed.

## Suggested Reviewers

@BillWagner @AnthonyDGreen

2017-05-02 01:36 UTC, BillWagner requested changes
Overall, this looks great.

The anchor links see incorrect. Once those are fixed, this should be ready to merge.

2017-05-02 01:36 UTC, BillWagner commented on docs/visual-basic/getting-started/whats-new.md
> +For new features, see [Visual Basic 2017](visual-basic-2017)
I think the link targets should start with a '#'. It doesn't appear to work right now.

2017-05-02 01:36 UTC, BillWagner commented on docs/visual-basic/getting-started/whats-new.md
> +For new features, see [Visual Basic 14](visual-basic-14)
Same think: link should start with '#'

2017-05-03 16:47 UTC, rpetrusha commented
@BillWagner, I've fixed the anchors, which now work.

2017-05-15 19:08 UTC, mairaw approved these changes
LGTM. Let's merge this!

2017-05-15 19:09 UTC, merged