Add targeting/runtime pack missing
dotnet/docs pull request #20641
Opened 2020-09-15 04:16 UTC by wli3

New doc for issue https://github.com/dotnet/sdk/pull/13571

2020-09-15 23:08 UTC, tdykstra reviewed
We'll have more SDK error docs later, so I would put this in core/tools/sdk-errors (new folder) and name it netsdk1145.md.

To add this to the TOC, I would edit fundamentals/toc.yml:

* Change **.NET Core SDK overview** to a parent node and remove the word "overview"
* Make an **Overview** node directly under it that goes to the SDK overview article
* After the Overview node add an Error messages parent node and NETSDK1145 under it.

Example

* .NET Core SDK
  * Overview
  * Error messages
    * NETSDK1145

2020-09-16 16:03 UTC, adegeo requested changes, later dismissed

2020-09-16 16:03 UTC, adegeo commented on docs/core/tools/targeting-apphost-pack-missing-cannot-restore.md
> +**This article applies to:** ✔️ .NET Core 5.0.100 SDK and later versions
I believe were supposed to call it .NET 5 without Core

```suggestion
**This article applies to:** ✔️ .NET 5.0.100 SDK and later versions
```

2020-09-16 16:03 UTC, adegeo commented on docs/core/tools/targeting-apphost-pack-missing-cannot-restore.md
> +  </ItemGroup>
Indentation is wrong here:

```suggestion
<ItemGroup>
  <KnownAppHostPack Update="@(KnownAppHostPack)">
    <AppHostPackVersion Condition="'%(TargetFramework)' == 'TARGETFRAMEWORK'">EXISTINGVERSION</AppHostPackVersion>
  </KnownAppHostPack>
</ItemGroup>
```

2020-09-16 16:03 UTC, adegeo commented on docs/core/tools/targeting-apphost-pack-missing-cannot-restore.md
> +  </ItemGroup>
Indentation is wrong here:

```suggestion
<ItemGroup>
  <KnownAppHostPack Update="@(KnownAppHostPack)">
    <AppHostPackVersion Condition="'%(TargetFramework)' == 'TARGETFRAMEWORK'">EXISTINGVERSION</AppHostPackVersion>
  </KnownAppHostPack>
</ItemGroup>
```

2020-10-01 18:18 UTC, wli3 commented
Sorry for the delay. I will address the review once I finished GA blocking bugs

2020-10-01 22:17 UTC, wli3 commented on docs/core/tools/targeting-apphost-pack-missing-cannot-restore.md
> +---
I edited the title and description. Looks better?

Although do you have a link on how to use search results preview? I cannot find the option after install the doc writing pack

2020-10-01 22:18 UTC, wli3 commented
@tdykstra @adegeo I just updated according to your review

2020-10-01 22:27 UTC, adegeo commented on docs/core/tools/targeting-apphost-pack-missing-cannot-restore.md
> +---
Open the command palette in vs code (<kbd>ctrl</kbd>+<kbd>shift</kbd>+<kbd>p</kbd>) and search for "Search"

![image](https://user-images.githubusercontent.com/67293991/94869586-800d6180-03fa-11eb-93da-98fd2f82a5b3.png)

2020-10-01 22:28 UTC, adegeo commented on docs/core/tools/sdk-errors/netsdk1145.md
> +ms.date: 09/14/2020
I think this will also help with discovery.
```suggestion
ms.date: 09/14/2020
f1_keywords:
- NETSDK1145
```

2020-10-01 22:29 UTC, adegeo commented on docs/core/tools/sdk-errors/netsdk1145.md
> +When SDK issues error NETSDK1145, the targeting or apphost pack is not installed and NuGet package restore is not supported. This is typically caused by having a newer SDK than the one included in VS
```suggestion
When SDK issues error NETSDK1145, the targeting or apphost pack is not installed and NuGet package restore is not supported. This is typically caused by having a newer SDK than the one included in Visual Studio for C++/CLI projects. Upgrade Visual Studio, remove _global.json_ if it specifies a certain SDK version, and uninstall the newer SDK. Alternatively, you could override the targeting or apphost version: Find the version that exists under the pack directory from the error message and matches the target framework of the project. Add the following to the project:
```

2020-10-01 22:32 UTC, adegeo commented on docs/fundamentals/toc.yml
> +      href: ../core/tools/netsdk1145.md
This link is to the wrong file now. But thinking about it, I think the current path of the file (_core/tools/sdk-errors_) is too deep. I think we should move it to _core/sdk-errors/_

Thoughts on that @tdykstra ?

2020-10-05 23:36 UTC, wli3 commented
@adegeo is this good to merge now?

2020-10-06 15:16 UTC, tdykstra commented
@wli3 Yes this is ready to merge, all comments and suggestions have been addressed.

2020-10-06 15:17 UTC, tdykstra approved these changes

2020-10-06 15:17 UTC, merged