Update middleware-database-error-page-obsolete.md
dotnet/docs pull request #20704
Opened 2020-09-19 01:01 UTC by Rick-Anderson

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2020-09-21 12:53 UTC, IEvangelist requested changes
Please accept suggestion to remove extra space

2020-09-21 12:53 UTC, IEvangelist commented on includes/core-changes/aspnetcore/5.0/middleware-database-error-page-obsolete.md
> +1. Add the `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` NuGet package to the project file.
```suggestion

1. Add the `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` NuGet package to the project file.
```

Remove whitespace that is causing MD lint failure

2020-09-21 12:54 UTC, IEvangelist approved these changes
Looks good to me, :shipit: when you're ready.

2020-09-21 15:56 UTC, scottaddie requested changes

2020-09-21 15:56 UTC, scottaddie commented on includes/core-changes/aspnetcore/5.0/middleware-database-error-page-obsolete.md
> +1. Add the `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` NuGet package to the project file.
```suggestion
1. Add the [Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore](https://www.nuget.org/packages/Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore) NuGet package to the project file.
```

2020-09-21 15:56 UTC, scottaddie commented on includes/core-changes/aspnetcore/5.0/middleware-database-error-page-obsolete.md
> +1. Add the `Microsoft.AspNetCore.Diagnostics.EntityFrameworkCore` NuGet package to the project file.
This step should appear before the previous step. The `AddDatabaseDeveloperPageExceptionFilter` method lives in this NuGet package.

2020-09-22 16:58 UTC, scottaddie approved these changes

2020-09-22 18:05 UTC, merged