Port logging articles - adapt to .NET docs
dotnet/docs pull request #20782
Opened 2020-09-25 16:41 UTC by IEvangelist

## Summary

- Add code samples that correspond to using the .NET logging
- Add Microsoft Extensions logging articles
- Update TOC entry to add logging overview, providers, implement custom provider, and logger message

Contributes to: #4567

2020-09-29 02:33 UTC, tdykstra requested changes
This is more great content.  It covers a lot of ground, but unless I missed it somewhere, it omits non-host content. Without that, for non-web non-host apps, devs still have to go to the ASP.NET Core docs for help. See https://docs.microsoft.com/en-us/aspnet/core/fundamentals/logging/?view=aspnetcore-3.1#non-host-console-app and https://docs.microsoft.com/en-us/aspnet/core/migration/logging-nonaspnetcore?view=aspnetcore-3.1

2020-09-29 02:33 UTC, tdykstra commented on docs/core/extensions/logging.md
> +Logs that begin with "Microsoft" categories are from .NET code, and application code use the same logging API and providers.
This sentence is garbled.

2020-09-29 02:33 UTC, tdykstra commented on docs/core/extensions/logging.md
> +- In the console window when the app is run with `dotnet run`.
Here it's not clear what group "default providers" refers to -- those loaded by CreateDefaultBuilder or all of the built-in ones?  It's definitely not true of all the built-in ones, and I suspect it's only true of Debug and Console providers.

2020-09-29 11:34 UTC, IEvangelist commented on docs/core/extensions/logging-providers.md
> +#### dotnet trace tooling
> this is a gigantic section on dotnet trace, should it go in the dotnet trace documentation or is that documentation already adequate?

That's a good callout. I'll look into that and merge what makes sense, or cut it.

2020-09-29 11:42 UTC, IEvangelist commented on docs/core/extensions/logging.md
> +- Logging bugs should be created in the [github.com/dotnet/runtime/](https://github.com/dotnet/runtime/issues) repo.
I'll fix that, good catch.

2020-09-30 16:27 UTC, tdykstra reviewed
The updates look good, but I still don't see non-host content.

2020-09-30 18:48 UTC, IEvangelist commented
> The updates look good, but I still don't see non-host content.

Ah, yes... I forgot that bit. I'll add it, thanks.

2020-09-30 20:46 UTC, tdykstra approved these changes
One additional change and this is ready to go. 😄

2020-09-30 20:46 UTC, tdykstra commented on docs/core/extensions/logging.md
> +.NET supports a logging API that works with a variety of built-in and third-party logging providers. This article shows how to use the logging API with built-in providers. The code examples shown in
```suggestion
.NET supports a logging API that works with a variety of built-in and third-party logging providers. This article shows how to use the logging API with built-in providers. Most of the code examples shown in this article apply to any .NET app that uses the [Generic Host](generic-host.md). For apps that don't use the Generic Host, see [Non-host console app](#non-host-console-app).
```

2020-09-30 22:06 UTC, merged

2020-10-01 18:17 UTC, gewarren commented
There were some warnings introduced here. Can you fix them @IEvangelist ?

2020-10-01 19:05 UTC, IEvangelist commented
> There were some warnings introduced here. Can you fix them @IEvangelist David Pine FTE ?

Good catch, thank you - see https://github.com/dotnet/docs/pull/20875