[DO NOT MERGE] removing articles from URL
dotnet/docs pull request #2079
Opened 2017-05-03 08:17 UTC by mairaw

2017-05-17 07:00 UTC, mairaw commented
@rpetrusha @GuardRex @BillWagner i think this can be reviewed now and it would be important to do it. I think you need to use the branch url to see the behavior: https://review.docs.microsoft.com/en-us/dotnet-new/framework/?branch=change-url

I can't tell if breadcrumb is broken with this PR or not since a lot of times it doesn't work on staging. I think we will need to merge to master and test on the final master environment to make sure.

/cc @mikeblome

2017-05-17 17:39 UTC, GuardRex commented
Sorry @tompratt-AQ ... stray mouse click!

2017-05-17 20:16 UTC, mairaw commented
Actually the TOC issue is still there 😢

2017-05-17 20:24 UTC, mairaw commented
I'm following up with the engineering team to see if I was supposed to see the fixed TOC on the branch or not. The steps they gave me might suggest I'd only see it fixed on master.

2017-05-17 20:26 UTC, GuardRex commented
btw --- I almost have the review done. Just a few more links to check.

2017-05-17 20:28 UTC, mairaw commented
Thanks. The issue I see is that the TOC is not correct:
![image](https://cloud.githubusercontent.com/assets/12971179/26174565/adb1b0ea-3b04-11e7-9a2c-fb40518dd440.png)

I'm doing a manual build to see if it fixes that.

2017-05-17 20:29 UTC, GuardRex commented
My only concern was that with the review pending something might :boom:.

2017-05-17 20:43 UTC, guardrex requested changes
"GuardRex strikes again!" - [@]piotrpMSFT

A couple of side questions, and most of these are comments on trailing slashes on links + link text to match the topic title (where you want to do that).

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/framework/get-started/">Get Started</a></p>
The doc title is ...

*Get started with the .NET Framework*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/framework/development-guide">Tutorials</a></p>
The topic title is ...

*.NET Framework Development Guide*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/framework/develop-client-apps">Client Development</a></p>
The topic title is ...

*Developing Client Applications with the .NET Framework*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <p><a href="/aspnet/#pivot=aspnet">ASP.NET</a></p>
The page title is ...

*ASP.NET Documentation*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/core/get-started">Get Started</a></p>
Topic title is ...

*Get started with .NET Core*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/standard/components">.NET Architectural Concepts</a></p>
Topic title is ...

*.NET Architectural Components*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <h3><a href="/dotnet/welcome">.NET Platform Guide</a></h3>
Topic title is ...

*Welcome to .NET*

2017-05-17 20:43 UTC, GuardRex commented on docs/project-json.md
> +* [.NET Core documentation](./core/index.md)
Topic title is ...

*.NET Core*

2017-05-17 20:43 UTC, GuardRex commented on docs/project-json.md
> +* [ASP.NET Core documentation](/aspnet/core/)
Topic title is ...

*Introduction to ASP.NET Core*

2017-05-17 20:43 UTC, GuardRex commented on docs/framework/get-started/net-core-and-open-source.md
> + [ASP.NET Core Documentation](/aspnet/core/)
Topic title is ...

*Introduction to ASP.NET Core*

2017-05-17 20:43 UTC, GuardRex commented on docs/framework/get-started/net-core-and-open-source.md
> +-   **Flexible deployment:** there are two main ways to deploy your app: framework-dependent deployment or self-contained deployment. With framework-dependent deployment, only your app and third-part
The casing is fixed on the topic, so for sure it can go to ...

*.NET Core application deployment*

2017-05-17 20:43 UTC, GuardRex commented on CONTRIBUTING.md
> +a link to the live document on the [.NET documentation site](http://docs.microsoft.com/dotnet/welcome).
Topic title is ...

*Welcome to .NET*

2017-05-17 20:43 UTC, GuardRex commented on index.md
> +                                                <a href="/dotnet/fsharp/using-fsharp-on-azure">
*/dotnet/fsharp/using-fsharp-on-azure/*

2017-05-17 20:43 UTC, GuardRex commented on samples/csharp/getting-started/console-teleprompter/README.md
> +This sample is created during the [Console Application Tutorial](https://docs.microsoft.com/dotnet/csharp/tutorials/console-teleprompter)
I don't think that link text is a proper noun ???? ...

*console application tutorial*

2017-05-17 20:43 UTC, GuardRex commented on samples/framework/libraries/README.md
> +It uses the `netstandard1.2` Target Framework Moniker introduced with the [.NET Standard Library](https://docs.microsoft.com/en-us/dotnet/standard/library).
Topic title is ...

*.NET Standard*

2017-05-17 20:43 UTC, GuardRex commented on samples/snippets/fsharp/tour.fs
> +/// To learn more, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/values/index#why-immutable
I thought we were leaving *index* off when going to *index.md* ???

*https://docs.microsoft.com/dotnet/fsharp/language-reference/values/#why-immutable*

2017-05-17 20:43 UTC, GuardRex commented on samples/snippets/fsharp/tour.fs
> +    // To learn more about this operator, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/values/index#mutable-variables
Same thing here ... should it be ...

*https://docs.microsoft.com/dotnet/fsharp/language-reference/values/#mutable-variables*

2017-05-17 20:43 UTC, GuardRex commented on samples/snippets/fsharp/tour.fs
> +/// To learn more, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/functions/index#recursive-functions
... and here ...

*https://docs.microsoft.com/dotnet/fsharp/language-reference/functions/#recursive-functions*

2017-05-17 20:43 UTC, GuardRex commented on samples/snippets/fsharp/tour.fs
> +/// To learn more about Members, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/members
Trailing slash ...

*https://docs.microsoft.com/dotnet/fsharp/language-reference/members/*

2017-05-17 20:43 UTC, GuardRex commented on xml/System.Data.SqlClient/SqlAuthenticationMethod.xml
> +    <summary>Describes the different SQL authentication methods that can be used by a client connecting to Azure SQL Database. For details, see [Connecting to SQL Database By Using Azure Active Direc
The topic title is ...

*Use Azure Active Directory Authentication for authentication with SQL Database or SQL Data Warehouse*

2017-05-17 20:55 UTC, GuardRex commented
@mairaw There was one more note for a line where I couldn't attach a comment ...

*.openpublishing.redirection.json* Line 730 *articles* appears in the `redirect_url`

2017-05-17 23:59 UTC, mairaw commented on index.md
> +                                                <p><a href="/dotnet/framework/get-started/">Get Started</a></p>
No need to have the full title on the hub page.

2017-05-18 00:05 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/framework/get-started/">Get Started</a></p>
Yes, I didn't mean to suggest any of them should change, per se. I put these titles in the review just in case you wanted to make any changes.

2017-05-18 17:05 UTC, mairaw commented
Ok, good news. Force publish resolved the TOC issue. I just resolved a merge conflict and once that's done, we can review and merge if things look good. I'll take a look at @GuardRex's comments now, although they don't seem related to the goal of this PR which is only focused on removing the /articles from the URLs. 😄

2017-05-18 17:20 UTC, GuardRex commented
> don't seem related to the goal of this PR

... hence the quote by [@]piotrpMSFT: *"GuardRex strikes again!"* :grinning:

2017-05-18 17:31 UTC, mairaw commented
I can totally see where that comes from @GuardRex 😄 but I like your attention to detail!

2017-05-18 17:39 UTC, GuardRex commented
This is the third time this has happened: Two wrong guesses by me and once when I had the bright idea to ask @rpetrusha if he wanted a full review (app types topics; he requested full review on that one).

There's potentially a label option for PR's of "only-review-changes" vs. "full-review-request", but it would only probably apply to a GooberRex:tm: reviewer. Therefore, I'll prob just ask in the future if I'm unsure.

2017-05-22 19:31 UTC, mairaw commented on .openpublishing.redirection.json
> +            "redirect_url": "/dotnet/core/preview3/tools/dotnet-nuget-delete"
Good catch. The redirect existed at one point and got deleted. although the next redirect also exists so it wasn't a big deal.

2017-05-22 19:31 UTC, mairaw commented on .openpublishing.redirection.json
>              "source_path": "docs/standard/getting-started.md",
I think some weird things happened when merging changes from master or maybe something I've overlooked. I think there's no /articles left in this file.

2017-05-22 19:31 UTC, mairaw commented on samples/snippets/fsharp/tour.fs
> +/// To learn more about Members, see: https://docs.microsoft.com/dotnet/fsharp/language-reference/members
This link is not working for me. Maybe it got deleted and a redirect not put in place. I'll focus on just removing articles on this PR.

2017-05-25 09:04 UTC, merged

2017-05-26 18:00 UTC, mletterle commented
Just an FYI, the Pull #2012 mentions having a redirect from `dotnet/articles/*` to `dotnet/*` this doesn't appear to be occurring.

2017-05-26 18:03 UTC, BillWagner commented
Thanks @mletterle  We're working on it.  You can see the ongoing conversation on Issue #2259

2017-05-26 18:08 UTC, mletterle commented
Thanks @BillWagner, I'm seeing the redirects starting to go live now, so awesome!