Add remarks on default decompression methods for HttpClientHandler.AutomaticDecompression
dotnet/docs pull request #2086
Opened 2017-05-03 22:51 UTC by GuardRex

Fixes #1054 

Add remarks on default decompression methods for `HttpClientHandler.AutomaticDecompression`.

cc @davidsh

2017-05-03 22:58 UTC, davidsh commented
Actually, this change should not be made anymore to the documentation.

We recently reverted the change in behavior for this property in .NET Core.  Instead, it now matches the original .NET Framework.

See PR https://github.com/dotnet/corefx/pull/17701

So, we should close issue and PR.

2017-05-03 23:03 UTC, mairaw commented
But doesn't that apply to some versions of .NET Core then @davidsh?

2017-05-03 23:09 UTC, davidsh commented
Ok.

Well for .NET Core 1.0 and 1.1, the doc change (difference from .NET Framework) applies.

But for the upcoming .NET Core 2.0, we reverted that change.

2017-05-03 23:10 UTC, GuardRex commented
> for .NET Core 1.0 and 1.1, the doc change (difference from .NET Framework) applies.

Since 1.1 is current, we could take this now and open a new issue to mod the language again when 2.0 lands.

2017-05-03 23:19 UTC, davidsh commented
>Since 1.1 is current, we could take this now and open a new issue to mod the language again when 2.0 lands.

ok

2017-05-03 23:20 UTC, davidsh approved these changes

2017-05-12 00:44 UTC, GuardRex commented
@rpetrusha @mairaw This one is ready for :eyes:+merge.

2017-05-12 16:51 UTC, rpetrusha requested changes

2017-05-12 16:51 UTC, rpetrusha commented on xml/System.Net.Http/HttpClientHandler.xml
> +For the .NET Framework 4.x <xref:System.Net.Http> binary in the Global Assembly Cache (GAC), the default value is <xref:System.Net.DecompressionMethods.None>. However, the .NET Core default is <xref:
`<xref:System.Net.Http>` identifies a namespace, not an assembly, which is what you're referring to here. This shouldn't be a link.

2017-05-12 16:51 UTC, rpetrusha commented on xml/System.Net.Http/HttpClientHandler.xml
> +For the .NET Framework 4.x <xref:System.Net.Http> binary in the Global Assembly Cache (GAC), the default value is <xref:System.Net.DecompressionMethods.None>. However, the .NET Core default is <xref:
Rather than "However...", I'd just make the second sentence parallel to the first. "For .NET Core..."

2017-05-12 16:51 UTC, rpetrusha commented on xml/System.Net.Http/HttpClientHandler.xml
> +The [`System.Net.Http` NuGet package (v4.1.0 and later)](https://www.nuget.org/packages/System.Net.Http/) carries the .NET Core implementation of <xref:System.Net.Http>. When the NuGet package (v4.1.
"carries" sounds strange to me. "includes"? "provides"?

2017-05-12 18:14 UTC, GuardRex commented
@rpetrusha @davidsh In addition to those fixes, I reorganized this a hair. Feels like it composes better to state in the first two sentences: What ... where ... the info. Then, the 3rd sentence can make its point cleanly.

2017-05-12 18:46 UTC, rpetrusha approved these changes

2017-05-12 18:46 UTC, rpetrusha commented
LGTM. @davidsh, do you want to take a look at it again, or is it OK to merge?

2017-05-15 23:41 UTC, davidsh commented
ok to merge

2017-05-15 23:42 UTC, merged