Top level statements tutorial
dotnet/docs pull request #21259
Opened 2020-10-28 17:08 UTC by BillWagner

Fixes #20593 

Create tutorial for using top-level statements.

This tutorial enables readers to explore top level statements to learn the syntax rules for using top-level statements, learn to create script-like programs, and refactor those script-like programs into maintainable utilities.

2020-10-28 17:31 UTC, Youssef1313 commented on docs/csharp/tutorials/exploration/top-level-statements.md
> +```console
~~~suggestion
```dotnetcli
~~~

2020-10-29 21:51 UTC, CamSoper requested changes, later dismissed

2020-10-29 21:51 UTC, CamSoper commented on docs/csharp/tutorials/exploration/top-level-statements.md
> +```console
```suggestion
```dotnetcli
```

2020-10-30 00:55 UTC, BillWagner commented
@CamSoper Thanks for the review. I've made all the requested updates. Can you approve?

2020-10-30 05:33 UTC, pkulikov commented on docs/csharp/tutorials/exploration/top-level-statements.md
> +Introduction and problem statement
That line looks to be the remaining one from original outline.

2020-10-30 05:34 UTC, pkulikov commented on docs/csharp/tutorials/exploration/top-level-statements.md
> +. Top-level statements can only be in one file, and that file cannot contain namespaces or types.
Typo:
```suggestion
Top-level statements can only be in one file, and that file cannot contain namespaces or types.
```

2020-10-30 15:57 UTC, CamSoper approved these changes

2020-10-30 15:58 UTC, merged

2020-11-02 19:23 UTC, gewarren commented
@BillWagner This introduced a build warning.