fixed broken links and other fixes
dotnet/docs pull request #2127
Opened 2017-05-10 07:38 UTC by mairaw

fixing some broken links, formatting and other fixes

there was also feedback on msdn that we were using the wrong version number for creators update so changed that too. (there is also complaints about the lack of vb that I haven't addressed here, need a new issue for it)

2017-05-10 23:50 UTC, rpetrusha requested changes

2017-05-10 23:50 UTC, rpetrusha commented on docs/framework/winforms/high-dpi-support-in-windows-forms.md
> +(../../../docs/framework/configure-apps/file-schema/winforms/windows-forms-add-configuration-element.md) to support new features and customizations added starting with the .NET Framework 4.7. To take
instead of windows-forms-add-configuration-element.md, the link should go to its parent, index.md

2017-05-17 05:25 UTC, mairaw commented
Thanks for your review @rpetrusha. I've update the link as you requested. Please take a look.

2017-05-18 21:29 UTC, rpetrusha approved these changes

2017-05-18 21:29 UTC, rpetrusha commented
@mairaw, LGTM. This is ready to merge.

2017-05-24 07:48 UTC, merged