Move alternatives out of String.Split ref
dotnet/docs pull request #21288
Opened 2020-10-30 23:51 UTC by gewarren

Contributes to dotnet/dotnet-api-docs#4309.

2020-10-31 15:06 UTC, gewarren commented
Close/reopen.

2020-11-02 21:43 UTC, adegeo requested changes
- Some minor things to fix and a thought about the end of the article.
- Code snippets aren't showing correctly because of the wrong code language.

2020-11-02 21:43 UTC, adegeo commented on docs/standard/base-types/parse-strings.md
> +:::code language="visual-basic" source="snippets/parse-strings/vb/regex.vb" id="2":::
```suggestion
:::code language="vb" source="snippets/parse-strings/vb/regex.vb" id="2":::
```

2020-11-02 21:43 UTC, adegeo commented on docs/standard/base-types/parse-strings.md
> +:::code language="visual-basic" source="snippets/parse-strings/vb/regex.vb" id="1":::
```suggestion
:::code language="vb" source="snippets/parse-strings/vb/regex.vb" id="1":::
```

2020-11-02 21:43 UTC, adegeo commented on docs/standard/base-types/parse-strings.md
> +:::code language="visual-basic" source="snippets/parse-strings/vb/regex.vb" id="3":::
```suggestion
:::code language="vb" source="snippets/parse-strings/vb/regex.vb" id="3":::
```

2020-11-02 21:43 UTC, adegeo commented on docs/standard/base-types/parse-strings.md
> +:::code language="visual-basic" source="snippets/parse-strings/vb/indexof.vb" id="1":::
```suggestion
:::code language="vb" source="snippets/parse-strings/vb/indexof.vb" id="1":::
```

2020-11-02 21:43 UTC, adegeo commented on docs/standard/base-types/parse-strings.md
> +:::code language="visual-basic" source="snippets/parse-strings/vb/indexof.vb" id="1":::
This ends abruptly; perhaps **see also** with link back to overview or some other string related examples?

2020-11-02 21:43 UTC, adegeo commented on docs/standard/base-types/parse-strings.md
> +## String.Split method
This section is missing VB versions.

2020-11-03 17:51 UTC, adegeo approved these changes
LGTM!

2020-11-03 18:43 UTC, gewarren commented
@adegeo Apologies for requesting review and then adding a couple more commits. It was just things I noticed on my final review. I added an intro and a couple of links.

2020-11-03 19:01 UTC, merged