Update configure-language-version.md
dotnet/docs pull request #21516
Opened 2020-11-12 14:51 UTC by benmccallum

## Summary

Couple of changes now that C# 9.0 is released.

2020-11-12 14:54 UTC, benmccallum commented on docs/csharp/language-reference/configure-language-version.md
> +The following table shows all current C# language versions. Your compiler may not necessarily understand every value if it's older. If you install the latest .NET SDK, then you have access to everyth
Seems kind of pointless to be overly specific here and need to update it all the time.

2020-11-12 16:21 UTC, BillWagner requested changes
This looks great @benmccallum 

If you accept the one white-space suggestion I made, I'll :shipit:.  That will fix the markdownlint error.

Thanks again!

2020-11-12 16:21 UTC, BillWagner commented on docs/csharp/language-reference/configure-language-version.md
> +> 8.0
quick nit for the markdownlint error (whitespace removal):

```suggestion
> 8.0
```

2020-11-12 18:08 UTC, benmccallum commented
Whoops, that's what you get for editing in GitHub haha. Fixed and back to you @BillWagner

2020-11-13 15:01 UTC, BillWagner approved these changes

2020-11-13 15:01 UTC, merged