SQL Server no longer add Administratos
dotnet/docs pull request #21510
Opened 2020-11-12 04:15 UTC by taroarai

SQL Server no longer add `BUILTIN\Administrators` group since SQL Server 2005, so could you remove this as SQL Server 2005 is no longer supported, or add what I add as it is until SQL Server 2005.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2020-12-16 03:30 UTC, gewarren commented
@mashamsft Could you verify this?

2020-12-16 23:54 UTC, gewarren requested changes, later dismissed
@taroarai Thanks for noticing this. We decided the sentence should just be removed completely.

2020-12-16 23:54 UTC, gewarren commented on docs/framework/data/adonet/sql/authentication-in-sql-server.md
> +> SQL Server installs with a SQL Server login named `sa` (an abbreviation of "system administrator"). Assign a strong password to the `sa` login and do not use the `sa` login in your application. The
```suggestion
> SQL Server installs with a SQL Server login named `sa` (an abbreviation of "system administrator"). Assign a strong password to the `sa` login and do not use the `sa` login in your application. The `sa` login maps to the `sysadmin` fixed server role, which has irrevocable administrative credentials on the whole server. There are no limits to the potential damage if an attacker gains access as a system administrator.
```

2021-02-16 18:14 UTC, adegeo approved these changes
@gewarren I went ahead and committed your suggestion as it's the appropriate fix.

2021-02-16 18:15 UTC, merged