Restore index page dropped content
dotnet/docs pull request #2181
Opened 2017-05-17 05:42 UTC by mairaw

While resolving some merge conflicts in one of my PRs, I've noticed that some content of the main page has been rolled back to an earlier version or content that we still wanted has been removed.

/cc @cartermp @GuardRex

2017-05-17 05:49 UTC, GuardRex commented
@mairaw I only removed a Visual Studio 2015 ref from this. https://github.com/dotnet/docs/commit/50e128137fde445f64e10cf7c2a1ee5fdecb34e6#diff-d680e8a854a7cbad6d490c445cba2eba

I'm as innocent as newborn babe! 👶 ......... this time. :grinning:

2017-05-17 05:51 UTC, GuardRex commented
oh ... you wanted that VS2015 ref back. I see. That was done on-purpose but apparently inadvertently.

2017-05-17 06:32 UTC, guardrex requested changes

2017-05-17 06:32 UTC, GuardRex commented on index.md
> +                                                <h3><a href="/dotnet/articles/standard">.NET Platform Guide</a></h3>
Were we terminating the ones that will resolve to an *index.md* with a trailing slash, right?

*/dotnet/articles/standard/*

2017-05-17 19:11 UTC, guardrex approved these changes

2017-05-17 19:12 UTC, mairaw commented
That one was added on purpose so people looking for the project.json docs could find it. 

I've addressed your comment.

2017-05-17 19:13 UTC, GuardRex commented
Do you want to use the "verify-build-before-merge" every time an approval is made but before the build completes?

2017-05-17 21:19 UTC, GuardRex commented on index.md
> +                                                <p><a href="/dotnet/articles/framework/development-guide">Tutorials</a></p>
One more ? ...

This one goes to ...

*.NET Framework Development Guide*

... not that that's wrong if that's where it should go, but it is a little bit :zap: shocking :zap: to land on something titled so differently and not obviously a list of tutorials.

2017-05-17 21:21 UTC, GuardRex commented
@mairaw One more question :point_up: before it merges. I also raise this over at https://github.com/dotnet/docs/pull/2079/files#r117099449

2017-05-17 23:56 UTC, mairaw commented on index.md
> +                                                <p><a href="/dotnet/articles/framework/development-guide">Tutorials</a></p>
I agree. Not sure how I missed that! I just simply replaced the URL.

2017-05-18 01:26 UTC, mairaw commented
Good to go @GuardRex?

2017-05-18 01:51 UTC, merged