Document CA1071: Override base.Equals when implementing IEquatable
dotnet/docs pull request #21838
Opened 2020-12-05 02:05 UTC by manfred-brands

## Summary

Added documentation for new rule CA1071: Override base.Equals if implementing IEquatable.

Belongs to roslyn analyzer PR: https://github.com/dotnet/roslyn-analyzers/pull/3992

2020-12-05 08:46 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1071.md
> +See [here](/dotnet/api/system.iequatable-1#notes-to-implementers) for more
```suggestion
For more information, see [Notes to implementers](/dotnet/api/system.iequatable-1#notes-to-implementers).
```

2020-12-07 19:05 UTC, gewarren requested changes
Thanks for adding this article. Please also add it to the [TOC.yml file](https://github.com/dotnet/docs/blob/master/docs/fundamentals/toc.yml) and the [index page](https://github.com/dotnet/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/design-warnings.md).

2020-12-07 19:08 UTC, gewarren commented on docs/fundamentals/code-analysis/quality-rules/ca1071.md
> +    public sealed override bool Equals(B other) => Equals(other as C);
```suggestion
    // This line fixes the violation.
    public sealed override bool Equals(B other) => Equals(other as C);
```

2020-12-07 19:08 UTC, gewarren commented on docs/fundamentals/code-analysis/quality-rules/ca1071.md
> +```csharp
```suggestion
The following code snippet shows the same two classes with the violation addressed.

```csharp
```

2020-12-07 19:09 UTC, gewarren commented
[Preview link (internal)](https://review.docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1071?branch=pr-en-us-21838).

2020-12-08 02:59 UTC, gewarren commented
Oops, looks like it also needs to be added to https://github.com/manfred-brands/docs/blob/master/docs/fundamentals/code-analysis/quality-rules/index.md, sorry.

2020-12-08 03:29 UTC, gewarren approved these changes

2020-12-08 03:29 UTC, merged