Restore top level TOC content for the .NET Platform Guide
dotnet/docs pull request #2208
Opened 2017-05-19 18:03 UTC by GuardRex

Fixes #2202

2017-05-19 21:43 UTC, mairaw requested changes

2017-05-19 21:43 UTC, mairaw commented on docs/toc.md
>  # [.NET Platform Guide](standard/)
I think you need to change this to standard/index.md and remove the toc.md file from that folder. the TOC now is all broken now on stage

2017-05-19 21:49 UTC, GuardRex commented
@mairaw Done :+1:

2017-05-24 08:15 UTC, mairaw approved these changes
🚀 thanks!

2017-05-24 14:34 UTC, merged