Update FileSystemInfo.Attributes details
dotnet/docs pull request #2209
Opened 2017-05-19 19:14 UTC by JeremyKuhne

# Update FileSystemInfo.Attributes details

## Summary

The returned value is -1 when the file doesn't exist. This is important to document as that means all flags are set.

## Details

As stated, this property returns -1 when the file doesn't exist. It doesn't throw `File/DirectoryNotFound` when retrieving, but does when setting. (`File.GetAttributes` conversely does throw.) As the behavior varies between the two entry points and flag checking is impacted this is important to document. Also clarified that access of other properties will cache the state.

## Suggested Reviewers

I'm the dev on this.

2017-05-19 19:14 UTC, dnfclas commented
@JeremyKuhne,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-05-19 20:37 UTC, mairaw commented on xml/System.IO/FileSystemInfo.xml
> + The value is cached when it or length or time properties are retrieved. To get the latest value, call the <xref:System.IO.FileSystemInfo.Refresh%2A> method.
when it or length or time properties are retrieved -> this doesn't read well. can you clarify what your intention is here?

2017-05-19 21:08 UTC, mairaw commented on xml/System.IO/FileSystemInfo.xml
> + If the path does not exist as of the last cached state, the returned value will be `(FileAttributes)(-1)`. <xref:System.IO.FileNotFoundException%2A> or <xref:System.IO.DirectoryNotFoundException%2A>
does not -> doesn't 
returned value -> return value
will be -> is
Remove the %2A from the exception links. links are not working like that. See staging at https://review.docs.microsoft.com/en-us/dotnet-new/api/system.io.filesysteminfo.attributes?view=netframework-4.7&branch=pr-en-us-2209#System_IO_FileSystemInfo_Attributes
Should this information about exception only being thrown when setting the value be moved to the exceptions table? Remarks don't make it into the IntelliSense.

2017-05-19 21:08 UTC, mairaw requested changes
Thanks @JeremyKuhne. Left a few comments for you to address.

2017-05-19 21:49 UTC, JeremyKuhne commented on xml/System.IO/FileSystemInfo.xml
> + The value is cached when it or length or time properties are retrieved. To get the latest value, call the <xref:System.IO.FileSystemInfo.Refresh%2A> method.
The value may be cached when either the value itself or other FileSystemInfo properties are accessed.

Is that better?

2017-05-19 21:55 UTC, JeremyKuhne commented on xml/System.IO/FileSystemInfo.xml
> + If the path does not exist as of the last cached state, the returned value will be `(FileAttributes)(-1)`. <xref:System.IO.FileNotFoundException%2A> or <xref:System.IO.DirectoryNotFoundException%2A>
Thanks, I'll update.

I'll put the comment in the exceptions table too.

2017-05-19 22:13 UTC, mairaw commented on xml/System.IO/FileSystemInfo.xml
> + The value is cached when it or length or time properties are retrieved. To get the latest value, call the <xref:System.IO.FileSystemInfo.Refresh%2A> method.
Yes!

2017-06-10 01:35 UTC, mairaw commented
@JeremyKuhne please let me know if you'll address my comments. Otherwise, I can make the edits for you. Thanks!

2017-06-27 07:29 UTC, mairaw commented
@JeremyKuhne do you want to take a look at the changes I made? Thanks.

2017-07-07 22:14 UTC, mairaw approved these changes
@JeremyKuhne has looked at the changes and approved offline.

2017-07-07 22:14 UTC, merged