Added articles about additional tooling and overall checklist
dotnet/docs pull request #22213
Opened 2021-01-04 16:13 UTC by DavidCBerry13

2021-01-05 14:49 UTC, IEvangelist reviewed
A few minor nits...

2021-01-05 14:49 UTC, IEvangelist commented on docs/azure/azure-tools.md
> +## Next Steps
```suggestion
## Next steps
```

2021-01-05 14:49 UTC, IEvangelist commented on docs/azure/dotnet-dev-env-checklist.md
> +## Create an Azure Account
```suggestion
## Create an Azure account
```

2021-01-05 14:49 UTC, IEvangelist commented on docs/azure/install-azure-cli.md
> +### Next Steps
```suggestion
### Next steps
```

2021-01-07 20:08 UTC, CamSoper requested changes
Couple of small things. Other than that LGTM :shipit:

2021-01-07 20:08 UTC, CamSoper commented on docs/azure/dotnet-dev-env-checklist.md
> +* [Install Azure Storage Explorer](https://azure.microsoft.com/en-us/features/storage-explorer/) to upload, download, and manage data in Azure storage resources including blobs, queues, tables, and C
```suggestion
* [Install Azure Storage Explorer](https://azure.microsoft.com/features/storage-explorer/) to upload, download, and manage data in Azure storage resources including blobs, queues, tables, and CosmosDB.
```

Also, does CosmosDB support in Storage Explorer include Mongo? Or just SQL API (or whatever they call DocumentDB these days)?

2021-01-07 20:08 UTC, CamSoper commented on docs/azure/dotnet-dev-env-checklist.md
> +* Azure Cloud Shell - [https://portal.azure.com/](https://portal.azure.com/)
```suggestion
* Azure Cloud Shell - [https://shell.azure.com/](https://shell.azure.com/)
```

2021-01-07 20:19 UTC, CamSoper approved these changes

2021-01-07 20:19 UTC, merged

2021-01-07 22:06 UTC, gewarren commented
@CamSoper or @DavidCBerry13 Can you fix the warnings this PR introduced?

![image](https://user-images.githubusercontent.com/24882762/103950367-9a3d9680-50f1-11eb-83ce-dc922667dbd9.png)

2021-01-07 23:56 UTC, CamSoper commented
@gewarren dang it, I should have caught that. My bad.