File renames
dotnet/docs pull request #2223
Opened 2017-05-23 01:58 UTC by mairaw

Not sure why our migration tool not always respected the new files names we've defined. There are a few of those but the ones included in this PR are a little bit more problematic because they're either GUIDs or have special characters.

2017-05-23 22:50 UTC, mairaw commented
This is ready for review. It would be good to get this one merged asap since it impacts the redirection I'm requesting from msdn to docs for .net docs. @rpetrusha @BillWagner @GuardRex

2017-05-23 22:55 UTC, GuardRex commented
@mairaw I'll do it now.

2017-05-23 23:23 UTC, guardrex requested changes

2017-05-23 23:23 UTC, GuardRex commented on xml/System.Windows.Forms/DataGridView.xml
> + See [Walkthrough: Creating a Master/Detail Form Using Two Windows Forms DataGridView Controls](~/docs/framework/winforms/controls/creating-a-master-detail-form-using-two-datagridviews.md)and [How to
Space before "and" right after the link.

2017-05-23 23:23 UTC, GuardRex commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> + However, you can still display the braces as literal characters by using an escape sequence that is particular to XAML instead of XML. For more information, see [{} Escape Sequence - Markup Extensio
This one had a bit of a :boom: on the review site: https://review.docs.microsoft.com/en-us/dotnet-new/articles/framework/xaml-services/xml-character-entities-and-xaml?branch=pr-en-us-2223

2017-05-23 23:35 UTC, mairaw commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> + However, you can still display the braces as literal characters by using an escape sequence that is particular to XAML instead of XML. For more information, see [{} Escape Sequence - Markup Extensio
Good catch. It's already like that in production. Usually it's a bad character in the metadata section like the ones i fixed for https://docs.microsoft.com/en-us/dotnet/articles/framework/xaml-services/%7B%7D-escape-sequence-markup-extension above

2017-05-23 23:42 UTC, GuardRex commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> + However, you can still display the braces as literal characters by using an escape sequence that is particular to XAML instead of XML. For more information, see [{} Escape Sequence - Markup Extensio
Sprinkled in there by the looks of it ...

![capture](https://cloud.githubusercontent.com/assets/1622880/26380998/80babbe4-3fe7-11e7-9faf-98982b002bd1.PNG)

2017-05-23 23:46 UTC, GuardRex commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> + However, you can still display the braces as literal characters by using an escape sequence that is particular to XAML instead of XML. For more information, see [{} Escape Sequence - Markup Extensio
`0A` = LF ... that's not it. I'm curious tho if it can be spotted.

2017-05-23 23:57 UTC, GuardRex commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> + However, you can still display the braces as literal characters by using an escape sequence that is particular to XAML instead of XML. For more information, see [{} Escape Sequence - Markup Extensio
Single quotes???

![capture](https://cloud.githubusercontent.com/assets/1622880/26381351/b543f68a-3fe9-11e7-9e30-b6cc8b54aaf2.PNG)

2017-05-24 00:35 UTC, guardrex approved these changes

2017-05-24 06:32 UTC, merged