Dapr/ch9 observability
dotnet/docs pull request #22593
Opened 2021-02-01 07:12 UTC by EdwinVW

Chapter 9 - Observability

2021-02-01 07:13 UTC, EdwinVW commented
This is the Dapr for .NET Devs book chapter 9 about Observability.
@nishanil and @IEvangelist, please review. Thanks!

2021-02-01 20:37 UTC, IEvangelist requested changes
A few suggestions, tag me when you update this and I'll review it again.

2021-02-01 20:37 UTC, IEvangelist commented on docs/architecture/dapr-for-net-developers/observability.md
> +See the [Dapr metrics documentation](https://docs.dapr.io/developing-applications/building-blocks/observability/metrics/) for a complete list of available metrics.
```suggestion
For more information on available metrics, see the [Dapr metrics documentation](https://docs.dapr.io/developing-applications/building-blocks/observability/metrics).
```

2021-02-01 20:37 UTC, IEvangelist commented on docs/architecture/dapr-for-net-developers/observability.md
> +| level    | Level of the entry (debug \| info \| warn  \| error) | `info`                              |
```suggestion
| level    | Level of the entry (`debug` \| `info` \| `warn`  \| `error`) | `info`                              |
```

2021-02-02 06:08 UTC, EdwinVW commented
> A few suggestions, tag me when you update this and I'll review it again.

@IEvangelist Great suggestions! Applied them all.

2021-02-02 13:53 UTC, IEvangelist approved these changes
Looks good to me, we'll :shipit: - thank you 🙏

2021-02-02 13:53 UTC, merged