Move include files from internal folders to master/includes folder (Part 2)
dotnet/docs pull request #2266
Opened 2017-05-26 23:21 UTC by tompratt-AQ

# Title
Move include files from internal folders to master/includes folder (Part 2)

## Summary
This PR completes the job that was mostly done by PR #2187 by moving the include files from these internal directories:

- docs/csharp/programming-guide/interop/includes
- docs/csharp/programming-guide/types/includes
- docs/visualbasic/developing-apps/customizing-extending-my/includes
- docs/visualbasic/developing-apps/includes
- docs/visualbasic/developing-apps/printing/includes
- docs/visualbasic/language-reference/objects/includes
- docs/visualbasic/misc/includes
- docs/visualbasic/reference/command-line-compiler/includes  

Once this PR has been reviewed and merged, all include files will be in the (~/includes) folder and will be named with dashes instead of underscores. This will fix Issue 2179.

Fixes #2179 

## Suggested Reviewers
@mairaw

2017-05-31 23:22 UTC, rpetrusha requested changes
@tompratt-AQ, unfortunately, some of the Visual Basic 2005 content tied general features to the specific Visual Basic 2005 version. Otherwise, the PR looked really good. There are also some merge conflicts that need to be resolved, though.

2017-05-31 23:22 UTC, rpetrusha commented on docs/visual-basic/programming-guide/program-structure/limitations.md
> +Earlier versions of [!INCLUDE[vbprvb](~/includes/vbprvb-md.md)] enforced boundaries in code, such as the length of variable names, the number of variables allowed in modules, and module size. In [!IN
In [token] --> In Visual Basic .NET

2017-05-31 23:22 UTC, rpetrusha commented on docs/visual-basic/reference/command-line-compiler/compiler-options-listed-alphabetically.md
>  |[/main](../../../visual-basic/reference/command-line-compiler/main.md)|Specifies the class that contains the `Sub``Main` procedure to use at startup.|
Can you fix the formatting here, @tompratt-AQ? 
`Sub``Main` --> `Sub Main`

2017-05-31 23:22 UTC, rpetrusha commented on docs/visual-basic/reference/command-line-compiler/how-to-invoke-the-command-line-compiler.md
> +     The exact name of the directory where the compiler is located depends on the location of the Windows directory and the version of the [!INCLUDE[Compact](~/includes/compact-md.md)] installed. If
Wow. This is even the wrong token, and it's been here for more than a decade. Change both occurrences of [token] to ".NET Framework".

2017-05-31 23:22 UTC, rpetrusha commented on docs/visual-basic/reference/command-line-compiler/netcf.md
> + The following code compiles `Myfile.vb` with the [!INCLUDE[Compact](~/includes/compact-md.md)], using the versions of Mscorlib.dll and Microsoft.VisualBasic.dll found in the default installation dir
Mscorlib.dll --> mscorlib.dll (the first "m" is lowercase)

2017-06-01 00:09 UTC, tompratt-AQ commented
@rpetrusha Thanks for detail on each correction! I made those changes and a change for the merge conflict.

2017-06-01 19:01 UTC, rpetrusha approved these changes

2017-06-01 19:01 UTC, rpetrusha commented
LGTM. I'll merge.

2017-06-01 19:01 UTC, merged