Add respectivity async handling patterns by languages.
dotnet/docs pull request #2284
Opened 2017-05-30 06:16 UTC by kekyo

# Async in depth summarise focusing only C#

Async in depth summarise focusing only C# language, so add "for C#" and another languages have respective pattern.

# Details

If we are using for F#, async pattern is "async workflow" and using Async type better than Task type. But I feel this article suit for C#, one of the representative example.

I changed:

* Write to it's C# pattern.
* Write no explicitly  languages, but it's difference.

2017-05-30 15:04 UTC, rpetrusha requested changes
Thanks for suggesting this change, @keyko! `async` and `await` are also keywords in Visual Basic, so it's not C# only. Could you revise your PR by incorporating the changes that I've suggested?

2017-05-30 15:04 UTC, rpetrusha commented on docs/standard/async-in-depth.md
> +Writing I/O- and CPU-bound asynchronous code is straightforward using the .NET Task-based async model. The model is exposed by the `Task` and `Task<T>` types and the `async` and `await` C# language k
better: "`async` and `await` C# language keywords." --> "`async` and `await` keywords in C# and Visual Basic."
"Any other languages have respective pattern." --> (Other languages may have a different syntax or different keywords.)

2017-05-30 15:05 UTC, GuardRex commented
Extending @kekyo's point a little bit: Cross-references to the language-specific docs, such as:

* Asynchronous programming - https://docs.microsoft.com/en-us/dotnet/csharp/async
* Async Programming in F# - https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/asynchronous-and-concurrent-programming/async
* Asynchronous Programming with Async and Await (Visual Basic) - https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/

... seem missing here in a *See also* section at the bottom. If adding them makes sense, then the line @kekyo added ...

> (Any other languages have respective pattern.)

... could call out the language-specific resources in that section (and we'd possibly even remove the "C#" that @kekyo added in this PR, since that's somewhat obvious) ...

> (Language-specific resources are found in the [See also](#see-also) section.)

(:point_up: something along those lines)

```
## See also

[Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/async)   
[Async Programming in F#](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/asynchronous-and-concurrent-programming/async)   
[Asynchronous Programming with Async and Await (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/)
```

Last question: If that's a good add here, wouldn't it also be a good add these over in [Asynchronous Programming Patterns](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/) with a little better cross-linking among the three docs on async in the .NET Platform Guide section?

cc/ @cartermp @BillWagner @rpetrusha

2017-05-30 18:50 UTC, GuardRex commented
@kekyo If you want to add a *See also* section here (and at the bottom of [Asynchronous Programming Patterns](https://docs.microsoft.com/en-us/dotnet/standard/asynchronous-programming-patterns/)), there's an important thing to note about lists without bullet points. When you list links back-to-back without a blank line between them, such as ...

```
## See also

[Asynchronous programming in C#](https://docs.microsoft.com/en-us/dotnet/csharp/async)   
[Async Programming in F#](https://docs.microsoft.com/en-us/dotnet/fsharp/tutorials/asynchronous-and-concurrent-programming/async)   
[Asynchronous Programming with Async and Await (Visual Basic)](https://docs.microsoft.com/en-us/dotnet/visual-basic/programming-guide/concepts/async/)
```
... you must include three spaces at the end of lines before the last line. This is currently undocumented (but we'll document it soon). So for those three links, set them up like this ...

```
## See also

[TITLE_HERE](<LINK_HERE>)<PUT_THREE_SPACES_HERE>
[TITLE_HERE](<LINK_HERE>)<PUT_THREE_SPACES_HERE>
[TITLE_HERE](<LINK_HERE>)
```

2017-05-31 16:14 UTC, rpetrusha commented
@GuardRex, I think your suggested improvements to the topic are valuable. Could you open an issue that addresses them? @kekyo, thank you so much for pointing out the single-language focus of this topic and for making corrections. We'll merge your PR. Thanks again for your contribution!

2017-05-31 16:14 UTC, rpetrusha approved these changes

2017-05-31 16:15 UTC, merged

2017-06-04 01:40 UTC, kekyo commented
I respond late sorry, thanks merged my proposal!