Mention restriction on usage of UnmangedType.CustomMarshaler
dotnet/docs pull request #2303
Opened 2017-06-02 01:17 UTC by dlech

Copy sentence from UnmangedType.LPStruct to UnmangedType.CustomMarshaler since the same restriction applies.

See dotnet/coreclr#12029

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-06-02 01:17 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-02 01:31 UTC, yizhang82 requested changes

2017-06-02 01:31 UTC, yizhang82 commented on xml/System.Runtime.InteropServices/UnmanagedType.xml
> +        <summary>Specifies the custom marshaler class when used with the <see cref="F:System.Runtime.InteropServices.MarshalAsAttribute.MarshalType" /> or <see cref="F:System.Runtime.InteropServices.
This also works on COM interop. So this statement is not accurate.
How about: 
This member is valid for parameters and return values only. It cannot be used on struct fields.

2017-06-10 01:34 UTC, mairaw commented
@dlech let us know if you'll make the changes suggested by @yizhang82. Otherwise, we can make them for you in this PR. Thanks!

2017-06-10 01:44 UTC, dlech commented
Whoops, forgot about this one. I have added the change now.

2017-06-10 01:45 UTC, yizhang82 approved these changes
LGTM. Thank you!

2017-06-12 15:20 UTC, rpetrusha approved these changes

2017-06-14 23:05 UTC, merged