Add information about how to achieve different equality comparison with records
dotnet/docs pull request #2359
Opened 2017-06-07 14:21 UTC by realvictorprm

#### Add additional information how to create records with class like comparison / reference equality.

Sometimes records are faster to write than classes and so the reference equality is still a need.
To avoid further search for beginners I would like to see this in the documentation.

cc @cartermp

2017-06-07 14:21 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-08 00:07 UTC, cartermp requested changes
👍 On the addition.  One wording chage needed and this is good to merge!

2017-06-08 00:07 UTC, cartermp commented on docs/fsharp/language-reference/records.md
> +If you need class like comparison or rather reference-equality for records add the attribute `[<ReferenceEquality>]` above the record.
I'd change this:

> If you need class like comparison or rather reference-equality for records

To this:

> If you need reference equality for records

2017-06-22 18:00 UTC, realvictorprm commented on docs/fsharp/language-reference/records.md
> +If you need class like comparison or rather reference-equality for records add the attribute `[<ReferenceEquality>]` above the record.
Thanks I totally missed your reply

2017-07-11 14:57 UTC, cartermp commented on docs/fsharp/language-reference/records.md
> +If you need class like comparison or rather reference-equality for records add the attribute `[<ReferenceEquality>]` above the record.
Had a chance to change this?

2017-08-12 01:14 UTC, mairaw commented on docs/fsharp/language-reference/records.md
> +If you need class like comparison or rather reference-equality for records add the attribute `[<ReferenceEquality>]` above the record.
Since it's been a month, I took care of the update, so we can merge. @cartermp can you please review it? Thanks!

2017-08-12 04:13 UTC, cartermp approved these changes

2017-08-12 04:13 UTC, merged

2017-08-12 14:52 UTC, realvictorprm commented
@cartermp sorry totally forgot about this