Document APIs for the System.Composition.Hosting.Core Namespace.
dotnet/docs pull request #2379
Opened 2017-06-09 21:48 UTC by tompratt-AQ

# Title
Add missing documentation for the System.Composition.Hosting.Core Namespace

This namespace contains the following classes and delegates:

- CompositeActivator 
- CompositionContract  **(NOTE:  There was no code file for this class)**
- CompositionDependency
- CompositionOperation
- DependencyAccessor
- ExportDescriptor
- ExportDescriptorPromise
- ExportDescriptorProvider
- LifetimeContext

Information was pulled from the source code at:
https://github.com/dotnet/corefx/tree/master/src/System.Composition.Hosting/src/System/Composition/Hosting/Core

Fixes #2349

## Suggested Reviewers
@mairaw

2017-06-13 16:24 UTC, tompratt-AQ commented
@mairaw Does this also need to be restarted (same issue as PR #2309)? It passed all checks last Friday and is waiting for a review.

2017-06-20 22:21 UTC, tompratt-AQ commented
@rpetrusha I checked the documentation against the MSDN topics and made adjustments accordingly.

2017-07-08 01:49 UTC, rpetrusha requested changes
@tompratt-AQ, sorry that it took so long to review this. Just a few corrections, but otherwise it looks good.

2017-07-08 01:49 UTC, rpetrusha commented on xml/System.Composition.Hosting.Core/CompositionDependency.xml
> + A missing dependency is an error, and is different from an optional dependency.
no comma here. It would actually be better to replace the second clause with, "(A missing dependency is different from an optional dependency.)"

2017-07-08 01:49 UTC, rpetrusha commented on xml/System.Composition.Hosting.Core/LifetimeContext.xml
> +A shared part instance is lock-free readable and does not result in issues if it is added to during disposal. It is protected by being locked itself. Activation logic is unavoidably called under this
lock free, readable, and does...

2017-07-13 19:28 UTC, tompratt-AQ commented
@rpetrusha Thanks Ron! Made all the changes you suggested. This should be good to go.

2017-07-13 21:59 UTC, rpetrusha approved these changes
Thanks, @tompratt-AQ. This looks good to merge.

2017-07-13 21:59 UTC, merged