Update how-to-query-the-contents-of-files-in-a-folder-lin.md
dotnet/docs pull request #2455
Opened 2017-06-20 23:51 UTC by bruceburge

adding "Text" to the title makes what this does clearer, this method will not work on docx, pdf, etc...

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-06-20 23:52 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-06-21 17:45 UTC, rpetrusha requested changes
Thanks, @bruceburge. Adding "Text" to the title is an enormous clarification. You've modified the title metadata; could you also modify the topic title on line 25?

2017-06-21 17:57 UTC, bruceburge commented
Line 25 updated, let me know if you need anything else.

2017-06-21 18:09 UTC, rpetrusha approved these changes
Thanks so much, @bruceburge. This looks good. We'll merge after the build successfully completes.

2017-06-21 20:41 UTC, merged