Issue #24577: edit commonly-used-collection-types.md
dotnet/docs pull request #24614
Opened 2021-06-09 15:26 UTC by jkendall327

## Summary
Copy-edit for readability and flow by introducing more paragraph breaks, bulletpoints, headings and simplified language. I've also changed the date as this is a fairly major edit.

Please let me know if I've done anything wrong, I've not worked on the .NET docs before!

Fixes #24577

2021-06-09 15:27 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=24614) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=24614) before we can accept your contribution.<br/><br/>:x: jkendall327 [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=24614)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=24614) it.</sub>

2021-06-11 21:47 UTC, gewarren requested changes
@jkendall327 thanks for your contribution to improving docs. I've left some requested changes.

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +- They are concise and easier to understand
Please add periods to the bullet points.

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +- They can filter, order and group data
```suggestion
- They can filter, order, and group data.
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +The LINQ to Objects feature provides a common pattern for accessing the in-memory objects of any type that implements <xref:System.Collections.IEnumerable> or <xref:System.Collections.Generic.IEnumer
```suggestion
The LINQ to Objects feature provides a common pattern for accessing in-memory objects of any type that implements <xref:System.Collections.IEnumerable> or <xref:System.Collections.Generic.IEnumerable%601>. LINQ queries have several benefits over standard constructs like `foreach` loops:
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +## Creating generic collections
```suggestion
## Strong typing
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +Generic collections are the best solution to strong typing. A `List<xref:System.Int32>`, for instance, will present a compile-time error if you add any other type to it.
```suggestion
Generic collections are the best solution to strong typing. For example, adding any type other than an <xref:System.Int32> to a `List<Int32>` collection causes a compile-time error.
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +If your language does not support generics, the <xref:System.Collections> namespace includes abstract base classes that you can extend to create strongly-typed collections:
```suggestion
However, if your language does not support generics, the <xref:System.Collections> namespace includes abstract base classes that you can extend to create collection classes that are strongly typed. These base classes include:
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +Collections vary depending on how they store elements, how they perform searches, how they compare elements, and how they are sorted.
```suggestion
Collections vary in how they store, sort, and compare elements, and how they perform searches. 
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +The <xref:System.Collections.Queue> and <xref:System.Collections.Generic.Queue%601> classes provide first-in-first-out lists. The <xref:System.Collections.Stack> and <xref:System.Collections.Generic.
This doesn't have anything to do with sorting.

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +You cannot sort the <xref:System.Collections.Hashtable> or the <xref:System.Collections.Generic.Dictionary%602> classes. The <xref:System.Collections.SortedList> class and the generic <xref:System.Co
I don't think that's true. You can call OrderBy to sort dictionaries and hash tables. I would just keep the original version of this sentence.

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
>  # Commonly Used Collection Types
```suggestion
# Commonly used collection types
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +Collection types represent ways to collect data, such as hash tables, queues, stacks, bags, dictionaries, and lists.
```suggestion
Collection types represent different ways to collect data, such as hash tables, queues, stacks, bags, dictionaries, and lists.
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +All collections are based on the <xref:System.Collections.ICollection> interface. <xref:System.Collections.IList>, <xref:System.Collections.IDictionary> and their generic counterparts both derive fro
```suggestion
All collections are based on the <xref:System.Collections.ICollection> or <xref:System.Collections.Generic.ICollection%601> interface, either directly or indirectly. <xref:System.Collections.IList> and <xref:System.Collections.IDictionary> and their generic counterparts all derive from these two interfaces. 
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +In collections based on <xref:System.Collections.IList>, or directly on <xref:System.Collections.ICollection>, every element contains only a value. Examples include:
```suggestion
In collections based on <xref:System.Collections.IList> or directly on <xref:System.Collections.ICollection>, every element contains only a value. These types include:
```

2021-06-11 21:47 UTC, gewarren commented on docs/standard/collections/commonly-used-collection-types.md
> +In collections based on the <xref:System.Collections.IDictionary> interface, every element contains both a key and a value. Examples include:
```suggestion
In collections based on the <xref:System.Collections.IDictionary> interface, every element contains both a key and a value. These types include:
```

2021-06-12 10:14 UTC, jkendall327 commented
@gewarren Thanks for the comments, I've just incorporated them all. Let me know if you think any further changes would help.

2021-06-14 17:53 UTC, gewarren commented
I made a few more changes directly, hope you don't mind. Looks like there are still some trailing spaces to clean up.

For the periods on the bullet points, that's only if the bullet points are more than a few words. If it's just one word, don't add a period.

2021-06-15 07:36 UTC, jkendall327 commented
No worries, I appreciate the improvements. I've just removed the trailing spaces caught by the linter. Thanks!

2021-06-15 20:58 UTC, gewarren approved these changes

2021-06-15 20:58 UTC, gewarren commented
This looks good to me. @IEvangelist do you want to sign off on this? [Preview link](https://review.docs.microsoft.com/en-us/dotnet/standard/collections/commonly-used-collection-types?branch=pr-en-us-24614).

2021-06-16 13:24 UTC, IEvangelist approved these changes
Looks good to me, we'll :shipit: - thank you 🙏

2021-06-16 13:25 UTC, merged