Update how-to-encrypt-xml-elements-with-asymmetric-keys.md
dotnet/docs pull request #24626
Opened 2021-06-10 12:51 UTC by IEvangelist

## Summary

Address typo and a few other minor concerns.

Fixes #24624

2021-06-10 20:18 UTC, Youssef1313 commented on docs/standard/security/how-to-encrypt-xml-elements-with-asymmetric-keys.md
> +You can use XML Encryption to replace any XML element or document with an <`EncryptedData`> element that contains the encrypted XML data.  The <`EncryptedData`> element can also contain sub elements
Should all these `<` and `>` be inside the backticks?

2021-06-15 16:05 UTC, IEvangelist commented on docs/standard/security/how-to-encrypt-xml-elements-with-asymmetric-keys.md
> +You can use XML Encryption to replace any XML element or document with an <`EncryptedData`> element that contains the encrypted XML data.  The <`EncryptedData`> element can also contain sub elements
```suggestion
You can use XML Encryption to replace any XML element or document with an `<EncryptedData>` element that contains the encrypted XML data.  The `<EncryptedData>` element can also contain sub elements that include information about the keys and processes used during encryption.  XML Encryption allows a document to contain multiple encrypted elements and allows an element to be encrypted multiple times.  The code example in this procedure shows how to create an `<EncryptedData>` element along with several other sub elements that you can use later during decryption.
```

2021-06-15 16:06 UTC, IEvangelist commented on docs/standard/security/how-to-encrypt-xml-elements-with-asymmetric-keys.md
>  7. Construct an <xref:System.Security.Cryptography.Xml.EncryptedData> object and populate it with the URL identifier of the encrypted XML element.  This URL identifier lets a decrypting party know th
```suggestion
7. Construct an <xref:System.Security.Cryptography.Xml.EncryptedData> object and populate it with the URL identifier of the encrypted XML element.  This URL identifier lets a decrypting party know that the XML contains an encrypted element.  You can use the <xref:System.Security.Cryptography.Xml.EncryptedXml.XmlEncElementUrl> field to specify the URL identifier.  The plaintext XML element will be replaced by an `<EncryptedData>` element encapsulated by this <xref:System.Security.Cryptography.Xml.EncryptedData> object.  
```

2021-06-17 21:34 UTC, CamSoper requested changes

2021-06-17 21:34 UTC, CamSoper commented on docs/standard/security/how-to-encrypt-xml-elements-with-asymmetric-keys.md
> +
```suggestion

> [!TIP]
> For development, use [Secret Manager](/aspnet/core/security/app-secrets) for secure secret storage. In production, consider a product like [Azure Key Vault](/aspnet/core/security/key-vault-configuration). 

```

2021-06-21 23:12 UTC, CamSoper approved these changes

2021-06-22 13:52 UTC, merged