fixing code formatting
dotnet/docs pull request #2483
Opened 2017-06-23 00:45 UTC by mairaw

Was looking at this topic (https://docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer#adding-startup-parameters) and noticed the code was all so badly formatted that it wasn't even readable.

2017-06-23 02:50 UTC, guardrex requested changes
Looks like one return needed in a vb example.

2017-06-23 02:50 UTC, GuardRex commented on docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md
> +    Dim ServicesToRun() As System.ServiceProcess.ServiceBase = New System.ServiceProcess.ServiceBase() {New MyNewServiceVB(cmdArgs)}         System.ServiceProcess.ServiceBase.Run(ServicesToRun)
Return needed here.

2017-06-23 15:34 UTC, rpetrusha commented on docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md
> +        System.Diagnostics.EventLog.CreateEventSource(eventSourceName, logName)
There's probably a tab here that should be replace with whitespace -- this line is indented much too far.

2017-07-06 22:49 UTC, mairaw commented on docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md
> +        System.Diagnostics.EventLog.CreateEventSource(eventSourceName, logName)
I don't see this @rpetrusha. It looks the same as others. Or am I missing something?
![image](https://user-images.githubusercontent.com/12971179/27935866-9a399b60-6262-11e7-86f8-d84bc82db4e4.png)

2017-07-06 22:50 UTC, mairaw commented
This should be ready for another review after build finishes @GuardRex.

2017-07-06 23:00 UTC, guardrex approved these changes

2017-07-06 23:02 UTC, GuardRex commented
@mairaw Cool ... but I'm putting the interpolated strings into one of the PR's I'm working. That's an option here, too. ... Either way, it's :shipit: good! :smile:

2017-07-07 17:33 UTC, rpetrusha commented on docs/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer.md
> +        System.Diagnostics.EventLog.CreateEventSource(eventSourceName, logName)
I think it was the `MyNewService` constructor in C#. The `eventLog1` assignment is intended too far, and the call to `CreateEventSource` is also indented too far in the [published page](https://review.docs.microsoft.com/en-us/dotnet/framework/windows-services/walkthrough-creating-a-windows-service-application-in-the-component-designer?branch=pr-en-us-2483).

2017-07-07 17:41 UTC, merged