Add instructions for disabling top-level imports
dotnet/docs pull request #25232
Opened 2021-07-20 08:45 UTC by kant2002

Based on comment https://github.com/dotnet/runtime/issues/55855#issuecomment-883213093

2021-07-21 16:19 UTC, tdykstra requested changes
Thanks for proposing this change! But I'd prefer to wait until #25250  is merged so we can link to msbuild-props.md#disableimplicitnamespaceimports.

2021-08-03 02:13 UTC, RussKie commented
Related https://github.com/dotnet/docs/issues/25436

2021-08-05 16:17 UTC, BillWagner commented
ping @tdykstra It looks like #25250 has been merged. Should this be merged now?

2021-08-05 16:27 UTC, tdykstra commented on docs/core/tutorials/top-level-templates.md
> +If you want to opt-out of that behaviour and manually control all namespaces in your project. Add `<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>` in the project file.
```suggestion
If you want to opt-out of that behavior and manually control all namespaces in your project, add [`<DisableImplicitNamespaceImports>true</DisableImplicitNamespaceImports>`](../project-sdk/msbuild-props.md#disableimplicitnamespaceimports) in the project file.
```

2021-08-05 16:29 UTC, tdykstra commented
> Should this be merged now?

Yes, I added the link.

2021-08-05 16:34 UTC, tdykstra approved these changes

2021-08-05 16:34 UTC, merged