Expand compatibility descriptions
dotnet/docs pull request #25360
Opened 2021-07-27 18:13 UTC by gewarren

Based on discussion with Mark Miller and Priya.

2021-07-27 18:59 UTC, PriyaPurkayastha approved these changes

2021-07-27 19:00 UTC, PriyaPurkayastha commented
cc @marklio

2021-07-28 00:11 UTC, marklio requested changes
A couple of tweaks to the wording that make things a little more clear to me in this context. It feels like we should have a larger document with more complete definitions, and some examples. I'm requesting changes because the proposed wording seems to indicate that breaks are guaranteed. We rarely break things in this way. Typically, there is only a narrow breaking scenario.

2021-07-28 00:11 UTC, marklio commented on .github/ISSUE_TEMPLATE/breaking-change.yml
> +        - label: Binary incompatible (breaks existing binaries when loaded into the new runtime/component - for example, failure to load/execute or different run-time behavior)
```suggestion
        - label: Binary incompatible (existing binaries may encounter a breaking change in behavior - for example, failure to load/execute or different run-time behavior)
```

2021-07-28 00:11 UTC, marklio commented on .github/ISSUE_TEMPLATE/breaking-change.yml
> +        - label: Source incompatible (breaks source code when targeting the new runtime/component/SDK - for example, compile errors or different run-time behavior)
```suggestion
        - label: Source incompatible (existing source code may encounter a breaking change in behavior when targeting the new runtime/component/SDK - for example, compile errors or different run-time behavior)
```

2021-07-28 18:10 UTC, marklio approved these changes
I think this is a big improvement from a content perspective. I'm not entirely familiar with the template process to know whether this would be a breaking change to the template (would it make new issues different from existing ones and make it hard to to machine categorization, etc.)

2021-07-28 18:14 UTC, gewarren commented
> I think this is a big improvement from a content perspective. I'm not entirely familiar with the template process to know whether this would be a breaking change to the template (would it make new issues different from existing ones and make it hard to to machine categorization, etc.)

Thanks. We only just added these compatibility types, so I don't think any issues are actually labeled accordingly yet. A good time to make it right.

2021-07-28 18:14 UTC, merged