[WIP] GetHostEntry sample using wrong overload
dotnet/docs pull request #2550
Opened 2017-07-04 22:08 UTC by GuardRex

**WIP** for updates and final checks.

Fixes #2548 

Validated for C# locally ...

```console
GetHostEntry(169.254.80.85) returns HostName: DESKTOP-RexPC
```

2017-07-05 18:27 UTC, rpetrusha requested changes
A few comments. In addition, though, I'd consider including an entire executable example rather than just the source for the DoGetHostEntry(IPAddress) method.

2017-07-05 18:27 UTC, rpetrusha commented on samples/snippets/cpp/VS_Snippets_Remoting/System.Net.Dns/CPP/dnsnewmethods.cpp
> +   DNSChanges::DoGetHostEntry(IPAddress.Parse("127.0.0.1"));
This should be `IPAddress::Parse`

2017-07-05 18:27 UTC, rpetrusha commented on samples/snippets/csharp/VS_Snippets_Remoting/System.Net.Dns/CS/dnsnewmethods.cs
> +            Console.WriteLine("GetHostEntry({0}) returns HostName: {1}", address, host.HostName);
Using interpolated strings is preferable here:
`Console.WriteLine($"GetHostEntry({address}) returns HostName: {host.HostName}");`

2017-07-05 18:27 UTC, rpetrusha commented on samples/snippets/visualbasic/VS_Snippets_Remoting/System.Net.Dns/vb/dnsnewmethods.vb
>  '        Dim hostName As [String] = "www.contoso.com"
no need for `[String]` -- just `Dim hostName As String...`

2017-07-05 18:27 UTC, rpetrusha commented on samples/snippets/visualbasic/VS_Snippets_Remoting/System.Net.Dns/vb/dnsnewmethods.vb
> +        Console.WriteLine("GetHostEntry(" + address.ToString() + ") returns HostName: " + host.HostName)
Use an interpolated string here as well, as the C# example did.

2017-07-05 18:35 UTC, svick commented on samples/snippets/csharp/VS_Snippets_Remoting/System.Net.Dns/CS/dnsnewmethods.cs
> +            host = Dns.GetHostEntry(address);
Why split declaration and assignment of the `host` variable?

2017-07-05 19:59 UTC, GuardRex commented on samples/snippets/csharp/VS_Snippets_Remoting/System.Net.Dns/CS/dnsnewmethods.cs
> +            host = Dns.GetHostEntry(address);
@svick This one and the avoidance of interpolated strings was because I found the samples in this state. I'll change it on this upcoming commit.

2017-07-05 20:52 UTC, GuardRex commented
@rpetrusha @svick I did some additional cleanup on the spacing and naming. I'd like to take another look before I say its ready for another round of review, so I've marked it **WIP**. I'm slammed today, and I'll get back to this asap.

> entire executable example

I was economical with this enhancement. It felt since this sample already deals with `GetHostEntry` that it would be ok to put this on here. However if you want a new sample just showing `GetHostEntry(IPAddress)`, let me know.

2017-07-10 19:02 UTC, GuardRex commented
@svick @rpetrusha In addition to the feedback changes, I did a little more work with cosmetic issues (e.g., spaces, `ip`/`ips` to `address`/`addresses`, etc.). It's ready for another :eye: :eye: look.

@rpetrusha 

> I'd consider including an entire executable example rather than just the source for the DoGetHostEntry(IPAddress) method.

I don't quite follow, since the source for this and `GetHostEntry(hostname)` is an "entire executable example." Do you mean a separate sample for `GetHostEntry(IPAddress)`?

2017-07-10 19:12 UTC, rpetrusha commented
@GuardRex, what I meant was that it would be nice if the code displayed in the documentation for GetHostEntry is all of the source for an executable example, rather than just a method call to DoGetHostEntry. That requires the user to add the necessary code to call the method with some appropriate arguments; it's good to spare them the effort, particularly for less experienced developers.

Otherwise, LGTM. I'll approve this and let you decide whether you want to present a fully executable example in the documentation.

2017-07-10 19:12 UTC, rpetrusha approved these changes

2017-07-10 19:35 UTC, GuardRex commented
@rpetrusha I see. Given the way this sample is setup, we'd need a separate sample then. I'm just about to start wrapping things up on the repo, so I've opened a new issue at https://github.com/dotnet/docs/issues/2583 for this. If I run out of time and don't get to it, then I'll unassign it on 7/31.

@svick Do you want to take a last look at this before I shoot it in there?

2017-07-10 21:10 UTC, rpetrusha commented
@GuardRex, that sounds good. If you run out of time, rather than unassigning it, you can assign it to me.

2017-07-10 21:11 UTC, GuardRex commented
> rather than unassigning it, you can assign it to me.

@rpetrusha :+1: Sure thing ... will do.

2017-07-11 16:45 UTC, rpetrusha commented
Is this ready to merge, @GuardRex?

2017-07-11 16:59 UTC, GuardRex commented
@rpetrusha Yes ... I'll do it now. @svick if you spot anything off here, let me know, and I'll get a patch PR setup for this work.

2017-07-11 17:00 UTC, merged