Add vulnerable option to dotnet list package doc
dotnet/docs pull request #25652
Opened 2021-08-16 17:15 UTC by ciwchris

## Summary

The `dotnet list package` package is out of date, it is missing the `vulnerable` option. I used the output from `dotnet list package --help` as the content of my proposed changes.

Feel free to close this PR and update the documentation through a different PR if there's another preferred workflow for updating this content.

2021-08-16 17:51 UTC, tdykstra requested changes
@ciwchris Thanks for this submission! Just a couple minor adjustments and it's ready to merge.

2021-08-16 17:51 UTC, tdykstra commented on docs/core/tools/dotnet-list-package.md
>      [--outdated] [--source <SOURCE>] [-v|--verbosity <LEVEL>]
We generally try to present the options in alphabetic order.

```suggestion
    [--deprecated]
    [--framework <FRAMEWORK>] [--highest-minor] [--highest-patch]
    [--include-prerelease] [--include-transitive] [--interactive]
    [--outdated] [--source <SOURCE>] [-v|--verbosity <LEVEL>]
    [--vulnerable]
```

2021-08-16 17:51 UTC, tdykstra commented on docs/core/tools/dotnet-list-package.md
> +
This should go at the end of the list, following --verbosity.

2021-08-16 19:12 UTC, tdykstra approved these changes
Looks good, thanks!

2021-08-16 19:14 UTC, merged

2021-08-16 19:32 UTC, ciwchris commented
@tdykstra sorry about the extra space though. 😞 I didn't want to make another commit to remove it. I was going to clone the repo down so I could amend the last commit but it's a big repo and was taking a long time. So then I was going to try to clone just the last so many commits so I could quickly amend but then needed to take care of something else for a bit.

2021-08-18 18:19 UTC, tdykstra commented
Not a problem at all, thanks again for catching and correcting the omission of --vulnerable!