Clarify technology choices
dotnet/docs pull request #25684
Opened 2021-08-17 21:13 UTC by arturohernandez10

## Summary

Describe your changes here.

Since  *.NET Core/5+* is the latest and greatest. Let's not muddle the waters, by having an unspecified *.NET Framework* above. If there is something else Microsoft would like to let us know, please be clear.

2021-08-18 17:36 UTC, tdykstra requested changes
Thanks for the submission! I have one suggestion that might help make the text clearer.

2021-08-18 17:36 UTC, tdykstra commented on docs/standard/choosing-core-framework-server.md
> +* *.NET Framework*, legacy versions.
Reversing the order and clarifying versions here makes sense, but "legacy" has connotations that don't apply to .NET Framework.

```suggestion
* *.NET Core/5+*, which includes .NET Core, .NET 5, and later versions.
* *.NET Framework*, which includes 4.8 and earlier versions.
```

2021-08-18 17:38 UTC, tdykstra commented
@gewarren Your thoughts on the proposed change?

2021-08-18 20:48 UTC, gewarren commented
> @gewarren Your thoughts on the proposed change?

I like your proposal better.

2021-08-30 21:52 UTC, tdykstra approved these changes
This is a good idea. It might make it clear enough that you could consider changing ".NET Core/5+" to ".NET" throughout.

2021-09-01 16:35 UTC, dnfadmin commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=25684) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=25684) before we can accept your contribution.<br/><br/>:x: arturohernandez10 [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=25684)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=25684) it.</sub>

2021-09-01 16:36 UTC, gewarren commented
@tdykstra I applied your suggestion in the latest commit. Can you look and see what you think?

2021-09-01 16:57 UTC, tdykstra approved these changes
I added one suggestion. The multiple meanings of ".NET" could still be confusing but that's inherent in the officially approved terminology, and this limits the multiple meanings to the intro where they are explained. I'm inclined to go ahead with this approach.

2021-09-01 16:57 UTC, tdykstra commented on docs/standard/choosing-core-framework-server.md
> +There are two supported .NET implementations for building server-side apps.
```suggestion
There are two supported [.NET implementations](glossary.md#implementation-of-net) for building server-side apps.
```

2021-09-01 17:56 UTC, gewarren approved these changes

2021-09-01 17:57 UTC, gewarren commented
@arturohernandez10 Could you sign the license agreement, and then we can merge this?

2021-09-06 08:09 UTC, arturohernandez10 commented
@gewarren I just signed. Thanks!

2021-09-06 15:12 UTC, merged