Add doc about resolving trim warnings
dotnet/docs pull request #26012
Opened 2021-09-08 17:54 UTC by agocke

## Summary

Should serve as an introduction to trim warnings and guidance about how to fix the most common problems.

2021-09-13 18:35 UTC, adegeo requested changes
Thank you for submitting this article, there are a few things to handle as well as adding this article to the TOC and linking to it from other related publishing articles.

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +Conceptually, trimming is very simple: when publishing the application, the .NET SDK analyzes the
These should be single lines without the column cut off

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> + 2. `DynamicallyAccessedMembers`
For some reason these are indented
```suggestion
1. `RequiresUnreferencedCode`
2. `DynamicallyAccessedMembers`
```

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +In this example, `Type.GetType` dynamically requests a type with an unknown name, and then prints
The first introduction of a type should use the xref syntax

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +accessing types from `Assembly.LoadFrom`, or other runtime code generation technologies.  An
xref here for Assembly.LoadFrom

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +to explain to the trimmer. This would often be true for methods which use the C# `dynamic` keyword,
dynamic could link to the csharp article

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +accessing types from `Assembly.LoadFrom`, or other runtime code generation technologies.  An
Search for double spaces and remove them.
```suggestion
accessing types from `Assembly.LoadFrom`, or other runtime code generation technologies. An
```

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +```C#
We use csharp as the language identifier
```suggestion
```csharp
```

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +```
I would use a blockquote for this.

2021-09-13 18:35 UTC, adegeo commented on docs/core/deploying/fixing-warnings.md
> +To prevent changes in behavior when trimming applications, the .NET SDK provides static analysis of
You should link to other publishing/trimming articles in the intro

2021-09-16 23:13 UTC, sbomer reviewed
This reads really nicely! It needs to be added to the TOC at https://github.com/dotnet/docs/blob/3e6c9e8767e53ad5b7cf90c975bf70900b745380/docs/fundamentals/toc.yml#L1576

I'm wondering how to deal with the overlap with https://docs.microsoft.com/en-us/dotnet/core/deploying/prepare-libraries-for-trimming#resolve-trim-warnings. I think your doc is a better landing page and intro to the warnings. Maybe we could separate things out into the following?

- Prepare .NET libraries for trimming, landing page for library authors
  - move the section "Resolving trim warnings" out to a separate page (intended to provide the next level of detail compared to this intro)
  - link to this doc instead

- This doc, landing page for the trim warnings
  - at the end of the walkthrough, link to the separate doc about "Resolving trim warnings"

2021-09-16 23:34 UTC, agocke commented
@sbomer Yup, there's a lot of overlap here. My approach was to try to get this in first, then I was going to try to consolidate and get your review. Happy to include whatever you think is useful

2021-09-24 21:16 UTC, adegeo approved these changes
Looks great!

2021-09-24 21:37 UTC, agocke commented
Thanks! I'll try to follow-up later by removing duplication in other files and centralizing links.

2021-09-24 21:37 UTC, merged