Uninstall .NET scripts on macOS / Linux are incorrect
dotnet/docs pull request #26020
Opened 2021-09-09 09:00 UTC by johnkors

The SDK and framework versions are never the same, and the proposed scripts won't uninstall as intentioned. Would be nice if that was explicit in the uninstall docs as proposed in this PR or similar.

2021-09-17 11:24 UTC, johnkors commented
This is what the same script would look like for removing .NET 6 RC1 installed on macOS right now:

```shell
sdk_version="6.0.100-rc.1.21458.32"
netcoreapp="6.0.0-rc.1.21451.13"
aspnetcoreapp="6.0.0-rc.1.21452.15"
fw_version="6.0.0-rc.1.21451.13"
sudo rm -rf /usr/local/share/dotnet/sdk/$sdk_version
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.NETCore.App/$netcoreapp
sudo rm -rf /usr/local/share/dotnet/shared/Microsoft.AspNetCore.App/$aspnetcoreapp
sudo rm -rf /usr/local/share/dotnet/host/fxr/$fw_version
```

2022-06-23 22:19 UTC, gewarren commented
Ping @adegeo.

2022-06-27 20:16 UTC, adegeo requested changes
Thanks for submitting this PR. The paragraphs above the examples talk about a specific version. That needs to be updated too, to be in line with the code.

2022-06-28 08:22 UTC, johnkors commented
Feel free to do whatever you want (update this PR, or do the changes outside of it). Just wanted to point out the errors.

2022-11-02 18:32 UTC, closed without merging