SEO updates
dotnet/docs pull request #2610
Opened 2017-07-12 22:28 UTC by GuardRex

Addresses #2468 

This is 🥊 **Round 1** 🥊 of an eight round contest. 🔔 Ding ding ..... and a series of devastating uppercuts from The Rex to open the match! 😵

2017-07-13 18:48 UTC, GuardRex commented
@rpetrusha Do you have time to review? [@]mairaw isn't free. I'm running these down and fixing them with the help of a script. Since we want each batch of 20 (there are >150 of them) on a separate PR and I wrote my script kind'a dumb (like ME), I'm relying on each batch to merge, update my local master each morning, and then run the script to catch and fix the next 20.

Another option is for me to make the script a little smarter: Run them in groups by path or have it store where I stop each day and pick back up from there on a new branch each morning. Unfortunately, there will be at least eight batches (PRs) to process. *I'm kind'a leaning toward creating a smarter script!*

2017-07-13 21:46 UTC, mairaw requested changes

2017-07-13 21:46 UTC, mairaw commented on docs/core/tutorials/aspnet-core.md
> +description: Redirection topic to get you started with ASP.NET Core.
let's take this one out of the pile for now. maybe this one should go away.

2017-07-13 21:46 UTC, mairaw commented on docs/core/tutorials/libraries.md
> +description: This article covers how to create libraries for .NET using cross-platform CLI tools.
instead of cross-platform CLI tools, let's use the name .NET Core CLI.

2017-07-13 21:46 UTC, mairaw commented on docs/core/deploying/creating-nuget-packages.md
> +description: Shows how to create a NuGet package with the 'dotnet pack' command.
I was reading a bit about best practices for descriptions. Two things I'd like to highlight from that:
- its main purpose is to get the visitor from Google to click your link
- It should be actionable, in an active voice.

So, in this example, I'd change from "Shows how" to "Learn how". Review the others to see if they're following that and use words like Learn, Understand, etc.

2017-07-13 21:46 UTC, mairaw commented on docs/core/index.md
> +description: .NET Core is a general-purpose development platform maintained by Microsoft and the .NET community.
Suggestion:
.NET Core is a modular and high performance implementation of .NET for creating applications that run on Windows, Linux and Mac. Learn more about .NET Core and resources to get started.

2017-07-13 21:53 UTC, GuardRex commented on docs/core/index.md
> +description: .NET Core is a general-purpose development platform maintained by Microsoft and the .NET community.
185 chars > 145 ... I'll see if I can shorten it a hair.

2017-07-15 00:26 UTC, mairaw approved these changes
Looks great. One comment left.

2017-07-15 00:26 UTC, mairaw commented on docs/core/tutorials/libraries.md
> +description: This article covers how to create libraries for .NET using .NET Core CLI tools.
change this one to an action oriented phrase like you did in others

2017-07-15 00:27 UTC, GuardRex commented on docs/core/tutorials/libraries.md
> +description: This article covers how to create libraries for .NET using .NET Core CLI tools.
thx --- will do

2017-07-15 02:39 UTC, merged