Fix inconsistencies
dotnet/docs pull request #26228
Opened 2021-09-23 00:44 UTC by gewarren

Fixes #26022, fixes #26023.

2021-09-23 00:58 UTC, gewarren commented
@tommcdon Would you be able to verify that these changes are correct, or point me to someone who could verify them?

2021-09-23 14:59 UTC, BillWagner approved these changes
This LGTM @gewarren 

You can :shipit: when ready

2021-09-27 20:18 UTC, tommcdon requested changes
I believe the existing documentation for in/out parameters on FindAssembliesByName is correct: https://github.com/dotnet/runtime/blob/b0159122f3570decd8ced6228681a210e2711de6/src/coreclr/inc/cor.h#L1355-L1361

2021-09-27 20:25 UTC, gewarren commented on docs/framework/unmanaged-api/metadata/imetadataassemblyimport-interface.md
> +|[FindAssembliesByName Method](imetadataassemblyimport-findassembliesbyname-method.md)|Gets an array of `IMetaDataImport` interface pointers for the assemblies with the specified name.|
```suggestion
|[FindAssembliesByName Method](imetadataassemblyimport-findassembliesbyname-method.md)|Gets an array of `IMetaDataAssemblyImport` interface pointers for the assemblies with the specified name.|  
```

2021-09-27 20:26 UTC, tommcdon approved these changes
Looks good to me - thank you!

2021-09-27 20:27 UTC, gewarren commented
> Looks good to me - thank you!

Thanks for reviewing and providing that link!

2021-09-27 20:31 UTC, merged