Document Signature APIs in the System.​Reflection.​Metadata Namespace.
dotnet/docs pull request #2630
Opened 2017-07-14 23:42 UTC by tompratt-AQ

# Title
Add Undocumented APIs: System.​Reflection.​Metadata Namespace - Signature APIs

## Summary
Added missing documentation for the group of Signature APIs in the System.​Reflection.​Metadata Namespace. This group contains the following topics:

- ConstantTypeCode.xml
- CustomAttributeNamedArgument`1.xml
- CustomAttributeNamedArgumentKind.xml
- CustomAttributeTypedArgument`1.xml
- CustomAttributeValue`1.xml
- MemberReferenceKind.xml
- MethodSignature`1.xml
- PrimitiveSerializationTypeCode.xml
- PrimitiveTypeCode.xml
- SerializationTypeCode.xml
- SignatureAttributes.xml
- SignatureCallingConvention.xml
- SignatureHeader.xml
- SignatureKind.xml
- SignatureTypeCode.xml
- SignatureTypeKind.xml
- StandaloneSignatureKind.xml

The source code for these topics is located at:
https://github.com/dotnet/corefx/blob/master/src/System.Reflection.Metadata/src/System/Reflection/Metadata/Signatures

Issue #2487 

## Suggested Reviewers
@mairaw

2017-07-18 00:17 UTC, rpetrusha requested changes
@tompratt-AQ, a few comments. It would also be helpful if you could take a quick look at this, @tmat.

2017-07-18 00:17 UTC, rpetrusha commented on xml/System.Reflection.Metadata/SignatureHeader.xml
> +        <summary>Gets the raw value.</summary>
"Gets the raw value of the header byte."

2017-07-18 00:17 UTC, rpetrusha commented on xml/System.Reflection.Metadata/SignatureHeader.xml
> +        <value>The raw value.</value>
The raw value of the header byte.

2017-07-18 00:17 UTC, rpetrusha commented on xml/System.Reflection.Metadata/SignatureTypeCode.xml
> +        <summary>Represents <see cref="System.Byte"/> in signatures.</summary>
There should be an article for this and each of the following member descriptions -- e.g., "Repesents a Byte...."

2017-07-18 00:17 UTC, rpetrusha commented on xml/System.Reflection.Metadata/SignatureTypeCode.xml
> +        <summary>Represents a <see cref="System.Object"/> in signatures.</summary>
a -> an

2017-07-18 19:48 UTC, tompratt-AQ commented
@rpetrusha Thanks for the review Ron! I made all of your suggested changes.

2017-07-24 17:48 UTC, rpetrusha approved these changes

2017-07-24 19:52 UTC, tmat commented
Not sure how this process works - wouldn't it be better to add the doc comments to the actual source code? What happens if we add them in future? Which comment wins?

2017-07-24 22:22 UTC, rpetrusha commented
@tmat, doc comments in source code are a good starting point -- we can then use them to generate the initial documentation for a type/member. We don't have a mechanism for migrating documentation back to source comments, though, so once documentation is written, it exists independently of source code comments.
In this case, there were no comments in the source code for a number of the members and I didn't think that they were completely self-explanatory, so I was hoping that you could take a look at the docs to make sure the documentation is accurate.

2017-07-27 21:29 UTC, mairaw commented
@tompratt-AQ can you also add a description to the namespace itself?

2017-07-27 21:31 UTC, mairaw commented
@tmat @nguerrera if you guys want to review this, you can go to staging site at https://review.docs.microsoft.com/en-us/dotnet/api/system.reflection.metadata.constanttypecode?view=netcore-2.0&branch=pr-en-us-2630 and then navigate through the classes listed on the PR description

2017-07-27 21:52 UTC, mairaw submitted a review, later dismissed
LGTM. Left a few minor comments plus the request to add namespace description.

2017-07-27 21:52 UTC, mairaw commented on xml/System.Reflection.Metadata/ConstantTypeCode.xml
> +        <summary>A null.</summary>
wouldn't be better to say "A null reference?"

2017-07-27 21:52 UTC, mairaw commented on xml/System.Reflection.Metadata/MethodSignature`1.xml
> + This value will be equal to the length of the <xref:System.Reflection.Metadata.MethodSignature`1.ParameterTypes> property, unless this method signature represents the standalone call site of a varar
will be equal -> is equal

vararg should probably be inline code

2017-07-27 21:52 UTC, mairaw commented on xml/System.Reflection.Metadata/SignatureHeader.xml
> +        <summary>Indicates whether this <see cref="T:System.Reflection.Metadata.SignatureHeader"/> structure has the <see cref="T:System.Reflection.Metadata.SignatureAttributes.ExplicitThis"/> signat
Boolean properties summaries start with Gets a value that indicates whether

2017-07-27 21:52 UTC, mairaw commented on xml/System.Reflection.Metadata/SignatureHeader.xml
> +        <summary>Determines whether two <see cref="T:System.Reflection.Metadata.SignatureHeader"/> values are unequal</summary>
missing period

2017-07-27 21:52 UTC, mairaw commented on xml/System.Reflection.Metadata/SignatureTypeKind.xml
> +        <summary>It is not known in the current context if the type reference or definition is a class or value type.</summary>
It is not -> It isn't

2017-07-28 00:15 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <param name="sizes">The sizes of each dimension.</param>
>s [](start = 36, length = 1)

Singular?

2017-07-28 00:16 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <param name="lowerBounds">The lower-bounds of each dimension.</param>
>s [](start = 49, length = 1)

Singular?

2017-07-28 00:17 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <summary>Gets the lower-bounds of each dimension. Length may be smaller than rank, in which case the trailing dimensions have unspecified lower bounds.</summary>
>each dimension [](start = 42, length = 14)

"all dimensions"?

2017-07-28 00:18 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <value>A collection of lower-bounds values.</value>
>values [](start = 44, length = 6)

omit "values"

2017-07-28 00:18 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <value>A collection of lower-bounds values.</value>
>A collection [](start = 15, length = 12)

"An array"

2017-07-28 00:19 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <summary>Gets the sizes of each dimension.</summary>
>each dimension [](start = 35, length = 14)

"all dimensions"

2017-07-28 00:19 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> +        <value>A collection of size values.</value>
>A collection of size values [](start = 15, length = 27)

An array of sizes

2017-07-28 00:20 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> + The number of elements in the returned array may be fewer than the number of dimensions of the array type (its rank). In that case, the trailing dimensions have unspecified sizes.
>fewer [](start = 53, length = 5)

smaller

2017-07-28 00:20 UTC, tmat commented on xml/System.Reflection.Metadata/ArrayShape.xml
> + The number of elements in the returned array may be fewer than the number of dimensions of the array type (its rank). In that case, the trailing dimensions have unspecified sizes.
>s [](start = 178, length = 1)

singular

2017-07-28 00:35 UTC, tmat commented on xml/System.Reflection.Metadata/ConstantTypeCode.xml
> +    <summary>Specifies constants that define types in a metadata type signature.</summary>
>Specifies constants that define types in a metadata type signature [](start = 13, length = 66)

Rather "Values representing types of metadata constants"

2017-07-28 00:36 UTC, tmat commented on xml/System.Reflection.Metadata/ConstantTypeCode.xml
> +        <summary>A <see cref="System.Boolean"/> type.</summary>
><see cref="System.Boolean"/> [](start = 19, length = 28)

Not sure why we link System type here and in "Char" but not in other places.

2017-07-28 00:40 UTC, tmat commented on xml/System.Reflection.Metadata/CustomAttributeNamedArgumentKind.xml
> +    <summary>Specifies constants that define the kinds of arguments in a custom metadata attribute.</summary>
>custom metadata attribute [](start = 73, length = 25)

... in a custom attribute signature

2017-07-28 00:43 UTC, tmat commented on xml/System.Reflection.Metadata/CustomAttributeNamedArgument`1.xml
> +    <summary>Represents a named argument of the specified generic type for a custom metadata attribute.</summary>
>generic [](start = 58, length = 7)

omit "generic"

2017-07-28 00:47 UTC, tmat commented on xml/System.Reflection.Metadata/CustomAttributeNamedArgument`1.xml
> +    <summary>Represents a named argument of the specified generic type for a custom metadata attribute.</summary>
>Represents a named argument of the specified generic type for a custom metadata attribute [](start = 13, length = 89)

Represents a named argument decoded from a custom attribute signature

2017-07-28 00:49 UTC, tmat commented on xml/System.Reflection.Metadata/CustomAttributeNamedArgument`1.xml
> +    <typeparam name="TType">The type of the argument.</typeparam>
>The type of the argument [](start = 28, length = 24)

Type used to represent types of values decoded from the custom attribute signature.

2017-07-28 00:49 UTC, tmat commented on xml/System.Reflection.Metadata/CustomAttributeNamedArgument`1.xml
> +        <param name="kind">The kind of argument.</param>
the

2017-07-28 00:49 UTC, tmat commented on xml/System.Reflection.Metadata/CustomAttributeNamedArgument`1.xml
> +        <param name="type">The type of argument.</param>
the

2017-07-28 23:27 UTC, tompratt-AQ commented
@tmat 
@mairaw 
I made all of the suggested changes from both of you. There are just two remaining items:

1. In the[ xml/System.Reflection.Metadata/ConstantTypeCode.xml](https://github.com/dotnet/docs/pull/2630/files/694ed6a0e0139e75b062d0adb64d793370c3af7b#diff-7bfab040906f7ecf7b349f9710fa4486 ) file, I borrowed the summary descriptions for each type from the [CorElementType Enumeration1](https://docs.microsoft.com/en-us/dotnet/framework/unmanaged-api/metadata/corelementtype-enumeration). I did this because the code file for [ConstantTypeCode](https://raw.githubusercontent.com/dotnet/corefx/master/src/System.Reflection.Metadata/src/System/Reflection/Metadata/Signatures/ConstantTypeCode.cs) indicates that these values map to CorElementType values. Should I keep these descriptions, or should I use link to the CorElementType values?

2. Please review my namespace description for ns-System.Reflection.Metadata. 

Thanks to both of you for the detailed review!

2017-08-18 17:40 UTC, merged