Update distributed-data.md
dotnet/docs pull request #26320
Opened 2021-09-30 06:13 UTC by ZahraBayatgh

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2021-10-22 21:03 UTC, robvet reviewed
Zahra, thank you so much for your input. But it looks like on line 98 you adding a space between the word 'events' and a comma. Don't space should be added there.

2021-10-22 21:08 UTC, robvet requested changes
Zahra, thank you so much for your input. But it looks like on line 98 you adding a space between the word 'events' and a comma. Don't think a space should be added there. Also, would not recommend changing from "read" and "write" as these terms are common across developers. 

However, really like removing the comma on line 106 following "cqrs)" and italizing on line 110.

Can you resumbit PR to match those changes.

Again, thank you so much for you suggestions!

2022-01-26 16:49 UTC, IEvangelist commented on docs/architecture/cloud-native/distributed-data.md
> +Saga patterns are typically choreographed as a series of related events , or orchestrated as a set of related commands. In Chapter 4, we discussed the service aggregator pattern that would be the fou
```suggestion
Saga patterns are typically choreographed as a series of related events, or orchestrated as a set of related commands. In Chapter 4, we discussed the service aggregator pattern that would be the foundation for an orchestrated saga implementation. We also discussed eventing along with Azure Service Bus and Azure Event Grid topics that would be a foundation for a choreographed saga implementation.
```

2022-01-26 16:50 UTC, IEvangelist commented on docs/architecture/cloud-native/distributed-data.md
> +For normal scenarios, the same entity model and data repository object are used for *both* reading and write operations.
```suggestion
For normal scenarios, the same entity model and data repository object are used for *both* read and write operations.
```

2022-01-26 16:51 UTC, IEvangelist commented
Closing this PR as it's stale and the OP is unresponsive.

2022-01-26 16:51 UTC, closed without merging