Update signTask 36552572: Edit signtool docs /fd /td infotool-exe.md
dotnet/docs pull request #26325
Opened 2021-09-30 18:24 UTC by jjhenry21

## Changes
Top Note: "A warning (error code 0, initially) will be thrown if /fd is not specified during signing and if /td is not specified during timestamping. In later versions of SignTool, the warning will become an error. " --> An error (error code 1) will be thrown if /fd is not specified during signing and if /td is not specified during timestamping.
All table rows where /td specified the note in the row needs to be updated to "An error is generated if /td is not provided while timestamping." (there is no default anymore <- does not need to go in doc"
All table rows where /fd is specified the note in the row needs to be updated to "An error  is generated if the/fd switch is not provided while signing."

2021-09-30 20:10 UTC, jgeurten requested changes

2021-09-30 20:10 UTC, jgeurten commented on docs/framework/tools/signtool-exe.md
> +|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if /td is not provided while timestamping." (there
"the does not need to go in doc" was not supposed to go in the doc

```suggestion
|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if `/td` is not provided while timestamping.|
```

2021-09-30 20:10 UTC, jgeurten commented on docs/framework/tools/signtool-exe.md
> +|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if /td is not provided while timestamping." (there
See above requested changes please

2021-09-30 20:10 UTC, jgeurten commented on docs/framework/tools/signtool-exe.md
> +|`/fd`  *certHash*|Specifying the string *certHash* will default to the algorithm used on the signing certificate. </br> **Note:** An error  is generated if the /fd switch is not provided while signi
```suggestion
|`/fd`  *certHash*|Specifying the string *certHash* will default to the algorithm used on the signing certificate. </br> **Note:** An error is generated if the `/fd` switch is not provided while signing.|  
```

2021-09-30 20:10 UTC, jgeurten commented on docs/framework/tools/signtool-exe.md
> +> A warning (error code 0, initially) will be thrown if /fd is not specified during signing and if /td is not specified during timestamping. In later versions of SignTool, the warning will become an
```suggestion
> The Windows 10 SDK, Windows 10 HLK, Windows 10 WDK and Windows 10 ADK **builds 20236 and later** require specifying the digest algorithm. The SignTool `sign` command requires the `/fd` **file digest algorithm** and the `/td` **timestamp digest algorithm** option to be specified during signing and timestamping, respectively. An error (error code 1) will be thrown if `/fd` is not specified during signing and if `/td` is not specified during timestamping.
```

2021-09-30 23:23 UTC, jgeurten requested changes

2021-09-30 23:23 UTC, jgeurten commented on docs/framework/tools/signtool-exe.md
> +|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if /td is not provided while timestamping.|
```suggestion
|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if `/td` is not provided while timestamping.|
```

2021-09-30 23:23 UTC, jgeurten commented on docs/framework/tools/signtool-exe.md
> +|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if /td is not provided while timestamping.|
```suggestion
|`/td`  *alg*|Used with the `/tr` option to request a digest algorithm used by the RFC 3161 time stamp server. </br> **Note:** An error is generated if `/td` is not provided while timestamping.|
```

2021-11-01 18:08 UTC, jgeurten approved these changes

2021-11-01 18:10 UTC, jgeurten commented
@CamSoper could you please review this PR and merge. The feature team has reviewed the changes and approved them.

2021-11-01 22:54 UTC, CamSoper approved these changes
LGTM

2021-11-01 22:54 UTC, merged