Non-GUID link updates
dotnet/docs pull request #2634
Opened 2017-07-15 15:41 UTC by GuardRex

Addresses Part 3(2) of #2580

Converts Non-GUID MSDN links ...

```
https?://msdn.microsoft.com(/en-us)?/library/[A-Za-z]{2}[\d]{6}\(v=vs\.[\d]{2,3}\).aspx
```

All link changes are logged. No bad links were found on this pass.

[log-nonGUID.txt](https://github.com/dotnet/docs/files/1150436/log-nonGUID.txt) (CSV file)

2017-07-18 00:07 UTC, mairaw requested changes
LGTM. Left a few comments.

2017-07-18 00:07 UTC, mairaw commented on docs/framework/migration-guide/net-framework-4-migration-issues.md
> +| **Script functions** | The [function-available function](https://msdn.microsoft.com/library/ms256124(v=vs.110).aspx) no longer incorrectly returns `false` when the function is actually available. |
this is odd. it seems this content should be redirecting to docs but it's not. can you please open an issue for me to investigate this?

2017-07-18 00:07 UTC, mairaw commented on docs/framework/migration-guide/net-framework-4-migration-issues.md
> +[New Types and Members in the .NET Framework 4](https://msdn.microsoft.com/library/ff641764(v=vs.110).aspx)
vs.100 was the correct version

2017-07-18 00:07 UTC, mairaw commented on docs/framework/migration-guide/net-framework-4-migration-issues.md
> +[Migration Guide to the .NET Framework 4](https://msdn.microsoft.com/library/ff657133(v=vs.110).aspx)
same for these other links

2017-07-18 00:07 UTC, mairaw commented on docs/framework/wpf/advanced/cleartype-registry-settings.md
> + [ClearType Antialiasing](https://msdn.microsoft.com/library/windows/desktop/dd183433(v=vs.85).aspx)
previous link was correct

2017-07-18 00:07 UTC, mairaw commented on docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md
> +In microservices-based architectures, you should choose availability and tolerance, and you should deemphasize strong consistency. Therefore, in most modern microservice-based applications, you usual
there's a link with en-us still

2017-07-18 00:07 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/async/index.md
> + The Windows Runtime also contains many methods that you can use with `Async` and `Await` in Windows apps. For more information and example methods, see [Quickstart: using the await operator for asyn
keep the old link

2017-07-18 00:07 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/async/index.md
> +|[WhenAny: Bridging between the .NET Framework and the Windows Runtime](https://msdn.microsoft.com/library/jj635140.aspx)|Shows how to bridge between Task types in the .NET Framework and IAsyncOperat
ditto

2017-07-18 00:23 UTC, GuardRex commented on docs/csharp/language-reference/compiler-messages/cs2032.md
> +3.  Open the **Start** menu. Locate and select the [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/dotnet/framework/tools/developer-command-prompt-for-vs).
@mairaw You want this change (use relative paths) made everywhere?

2017-07-18 01:12 UTC, GuardRex commented on docs/framework/wpf/advanced/cleartype-registry-settings.md
> + [ClearType Antialiasing](https://msdn.microsoft.com/library/windows/desktop/dd183433(v=vs.85).aspx)
It's the canonical URL, which is why the script dropped this in.

2017-07-18 01:14 UTC, GuardRex commented on docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md
> +In microservices-based architectures, you should choose availability and tolerance, and you should deemphasize strong consistency. Therefore, in most modern microservice-based applications, you usual
Yes ... the anchor resulted in the link not getting picked up by the RegEx on this one.

2017-07-18 01:18 UTC, GuardRex commented on docs/csharp/language-reference/compiler-messages/cs2032.md
> +3.  Open the **Start** menu. Locate and select the [Developer Command Prompt for Visual Studio](https://docs.microsoft.com/dotnet/framework/tools/developer-command-prompt-for-vs).
I think we should do this on another branch/PR ... I'm about to blow up GH here. :boom: ... 🚒 🚑 🚓

2017-08-23 00:40 UTC, mairaw approved these changes

2017-08-24 23:52 UTC, rpetrusha commented
The build failed, but its status is not reported here, and the build report appears to be unavailable. Closing and reopening to start new build.

2017-08-24 23:52 UTC, dnfclas commented
@guardrex,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-26 04:22 UTC, dnfclas commented
@guardrex,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-28 18:27 UTC, merged