Update Azure links
dotnet/docs pull request #2635
Opened 2017-07-15 16:03 UTC by GuardRex

Addresses Part 4 of #2580

2017-07-17 22:22 UTC, mairaw requested changes
LGTM but I'd change the URLs from https://azure.microsoft.com/documentation/ to the new docs.microsoft.com URL. I've commented in a few cases, not all, but it should be easy to find them.

2017-07-17 22:22 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/containerize-monolithic-applications.md
> +Monolithic applications in Microsoft Azure can be deployed using dedicated VMs for each instance. Additionally, using [Azure VM Scale Sets](https://azure.microsoft.com/documentation/services/virtual-
change https://azure.microsoft.com/documentation/services/virtual-machine-scale-sets/ to https://docs.microsoft.com/azure/virtual-machine-scale-sets/

2017-07-17 22:22 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/docker-application-state-data.md
> +-   [Azure Storage](https://azure.microsoft.com/documentation/services/storage/), which provides geo-distributable storage, providing a good long-term persistence solution for containers.
change https://azure.microsoft.com/documentation/services/storage/ to https://docs.microsoft.com/azure/storage/

2017-07-17 22:22 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/index.md
> +When you design a container image, you will see an [ENTRYPOINT](https://docs.docker.com/engine/reference/builder/) definition in the Dockerfile. This defines the process whose lifetime controls the l
change https://azure.microsoft.com/documentation/articles/websites-webjobs-resources/ to https://docs.microsoft.com/azure/app-service-web/websites-webjobs-resources

2017-07-17 22:22 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications.md
> +> [Service Fabric](https://azure.microsoft.com/documentation/articles/service-fabric-overview/) is a Microsoft microservices platform for building applications. It is an [orchestrator](https://azure.
- change https://azure.microsoft.com/documentation/articles/service-fabric-overview/ to https://docs.microsoft.com/azure/service-fabric/service-fabric-overview
-  change https://azure.microsoft.com/documentation/articles/service-fabric-cluster-resource-manager-introduction/ to https://docs.microsoft.com/azure/service-fabric/service-fabric-cluster-resource-manager-introduction

2017-07-17 22:22 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/scalable-available-multi-container-microservice-applications.md
> +> Service Fabric services can be developed in many ways, from using the [Service Fabric programming models ](https://azure.microsoft.com/documentation/articles/service-fabric-choose-framework/)to dep
review the remainder https://azure.microsoft.com/documentation/ links to go to the new docs.microsoft.com link without en-us

2017-07-17 22:25 UTC, GuardRex commented
@mairaw Ah ... yes ... np. These were all handled by script, and another little script will do the job. I'll take care of it. :cake:

2017-07-17 22:40 UTC, GuardRex commented
@mairaw Script only found four lines in four files with this. Did I catch all of them looking for ...

```
azure.microsoft.com/documentation/services
```

2017-07-18 00:15 UTC, mairaw commented
There are still a couple left such as https://azure.microsoft.com/documentation/articles/websites-webjobs-resources/

2017-07-18 00:25 UTC, GuardRex commented
I see. I only checked with a "services" segment ... I didn't address an "articles" segment. I'll get that on the next pass.

2017-07-18 01:34 UTC, GuardRex commented
@mairaw I've added relative links as an action item on the main issue: https://github.com/dotnet/docs/issues/2580. I'll do those on a new PR after these go in.

2017-07-18 04:53 UTC, mairaw commented
@GuardRex do you mean changing the docs.microsoft.com links to /azure? If so, these are ok like this because they're part of the microservices book. if we change them to relative links, then they can't use that as a source for a new edition as-is.

2017-07-18 05:18 UTC, mairaw approved these changes

2017-07-18 05:20 UTC, merged