Csharp10 interpolated strings
dotnet/docs pull request #26456
Opened 2021-10-11 18:50 UTC by BillWagner

Fixes #25679
Also fixes #26566, since it's in the same area.

C# guide updates for interpolated string enhancements. The way the compiler processes an interpolated string now uses a pattern. You can implement this pattern to construct the resulting string from an interpolated string expression. Many APIs and types in the .NET libraries already do this.

- [Preview link: LanguageReference/Attributes/Miscellenaneous](https://review.docs.microsoft.com/en-us/dotnet/csharp/language-reference/attributes/general?branch=pr-en-us-26456)
- [Preview link: LanguageReference/Tokens/StringInterpolation](https://review.docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated?branch=pr-en-us-26456)
- [Preview link: WhatsNew/Tutorials/WriteACustomStringInterpolationHandler](https://review.docs.microsoft.com/en-us/dotnet/csharp/whats-new/tutorials/interpolated-string-handler?branch=pr-en-us-26456)

2021-10-14 19:22 UTC, gewarren reviewed
I realize it's still in draft.

2021-10-19 19:37 UTC, CamSoper requested changes
Just one bit of feedback. Other than that LGTM

2021-10-20 22:24 UTC, CamSoper approved these changes
LGTM

2021-10-21 00:02 UTC, 333fred approved these changes

2021-10-21 01:19 UTC, merged