Update "Containerize a .NET app" to .NET 6 and C# 10
dotnet/docs pull request #27458
Opened 2021-12-08 20:59 UTC by IEvangelist

## Summary

Update "Containerize a .NET app" to .NET 6 and C# 10

Closes #26546

2021-12-09 17:27 UTC, CamSoper requested changes, later dismissed

2021-12-09 17:27 UTC, CamSoper commented on docs/core/docker/build-container.md
> + var counter = 0;
```suggestion
var counter = 0;
```

2021-12-09 18:54 UTC, IEvangelist commented on docs/core/docker/build-container.md
> + var counter = 0;
Good catch @CamSoper, thank you.

2021-12-10 14:03 UTC, BillWagner approved these changes
All requested changes have been made. I'll approve while @CamSoper is out.

2021-12-10 14:03 UTC, merged