[WIP] Netfx framework tools topics fixup
dotnet/docs pull request #2747
Opened 2017-07-25 04:17 UTC by GuardRex

Fixes #2739

Cleans up these topics and goes for consistency in option formats.

2017-07-25 15:28 UTC, GuardRex commented
Ready for :eyes:

2017-07-25 20:38 UTC, rpetrusha requested changes
Other than the one comment about the note, LGTM.

2017-07-25 20:38 UTC, rpetrusha commented on docs/framework/tools/al-exe-assembly-linker.md
> +> To avoid being subject to virtualization on a Windows Vista computer, your assembly must include a Win32 manifest that specifies the requested execution level. When you use *Al.exe* directly from t
Since Vista is not supported on later .NET Framework versions, you can delete everything up to the "Starting with..."

2017-07-25 20:43 UTC, GuardRex commented
@rpetrusha Done :+1:

2017-07-26 17:58 UTC, rpetrusha approved these changes

2017-07-26 17:59 UTC, rpetrusha commented
LGTM, @GuardRex. I'll merge this.

2017-07-26 17:59 UTC, merged