Mentioned that partial methods cannot be constructors
dotnet/docs pull request #27652
Opened 2021-12-22 07:35 UTC by SteveDunn

## Summary

Mentioned that partial methods cannot be constructors

2021-12-22 07:37 UTC, SteveDunn commented
@BillWagner - this PR is a result from experimenting with 'value objects/invariants' - I'd love your comments and thoughts on this thread in a language proposal: https://github.com/dotnet/csharplang/discussions/5075#discussioncomment-1856470

2021-12-22 16:52 UTC, BillWagner commented
Hi :wave: @SteveDunn 

I like this change. I would like to wait to merge this PR to address the [other restrictions](https://docs.microsoft.com/dotnet/csharp/language-reference/proposals/csharp-9.0/extending-partial-methods#partial-on-all-members) that still exist for partial methods.  The language in the feature spec is a bit vague, so we'll have to look through the LDM notes on partial methods to be sure what was defined. I *think* that none of these are allowed to be partial:

- constructors
- finalizers
- operators
- properties (I think the parser interprets them as auto-implemented properties).

2022-01-06 16:37 UTC, BillWagner requested changes
Thanks for making this addition @SteveDunn 

After checking the LDM notes, I made a suggestion to update the restrictions. Once you accept that, it's ready to merge.

Thanks again.

2022-01-06 16:37 UTC, BillWagner commented on docs/csharp/language-reference/keywords/partial-method.md
> +- Signatures are not constructors.
Given all the restrictions, I'd write this as follows:

```suggestion
The `partial` keyword isn't allowed on constructors, finalizers, overloaded operators, property declarations, or event declarations. 
```

2022-01-07 06:23 UTC, SteveDunn commented
Many thanks Bill. Accepted that change.

On Thu, 6 Jan 2022 at 16:38, Bill Wagner ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Thanks for making this addition @SteveDunn <https://github.com/SteveDunn>
>
> After checking the LDM notes, I made a suggestion to update the
> restrictions. Once you accept that, it's ready to merge.
>
> Thanks again.
> ------------------------------
>
> In docs/csharp/language-reference/keywords/partial-method.md
> <https://github.com/dotnet/docs/pull/27652#discussion_r779682852>:
>
> > @@ -16,6 +16,8 @@ A partial method has its signature defined in one part of a partial type, and it
>
>
>
>  - Signatures in both parts of the partial type must match.
>
>
>
> +- Signatures are not constructors.
>
>
> Given all the restrictions, I'd write this as follows:
> ⬇️ Suggested change
>
> -- Signatures are not constructors.
>
> +The `partial` keyword isn't allowed on constructors, finalizers, overloaded operators, property declarations, or event declarations.
>
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/docs/pull/27652#pullrequestreview-845818997>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AACAJ6C34MNNLBIIJHAJPFTUUXAO3ANCNFSM5KR44XXQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-01-07 13:56 UTC, BillWagner approved these changes

2022-01-07 13:56 UTC, BillWagner commented on docs/csharp/language-reference/keywords/partial-method.md
> +The `partial` keyword isn't allowed on constructors, finalizers, overloaded operators, property declarations, or event declarations.
```suggestion
The `partial` keyword isn't allowed on constructors, finalizers, overloaded operators, property declarations, or event declarations.
```

2022-01-07 14:00 UTC, merged