Add explanation of library and language dependency
dotnet/docs pull request #2774
Opened 2017-07-28 18:06 UTC by BillWagner

Fixes #1760

The C# language maps syntax to methods and types. This expalins what to
do when you have a newer compiler than framework.

2017-07-31 15:48 UTC, rpetrusha requested changes
Thanks for adding this to the doc set, @BillWagner; this is a really useful topic.

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +types, and certain accessible members on those types. The compiler generates
nit; no comma

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +`System.Exception`, `System.String`, `System.Int32` and more. That first
perhaps format these as xrefs rather than fenced?

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +C# 7.0 continues this by adding a dependency on `System.ValueTuple` to
This doesn't need to be a separate paragraph.

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/index.md
> +> The C# language relies on types and methods in a *standard library* for some of the features. To use the latest language features in older environments, you may need to install specific libraries.
I think this needs to be phrased a bit more strongly to make it clear that this isn't just about the compiler resolving type and method references, but about those types being used internally by the compiler for multiple language features. An example would help, and the best is probably Exception -- the exception handling system relies on the presence of System.Exception.

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +`System.Exception`, `System.String`, `System.Int32` and more. That first
I'd make this into a bulleted list and add a brief explanation for why each type is required by the compiler.

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +against a clean design where new library features are incorporated cleanly
There's a repetition of clean and cleanly here

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +on the many supported platforms. In fact, different .NET libraries have different release
on the many supported --> on supported

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +cycles: the .NET Framework on Windows is relesed as a Windows Update. .NET Core ships on
typo: released --> released
comma, not a period, after Update

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +its schedule, and the Xamarin versions of library updates ship with the Xamarin tools
its schedule --> a separate schedule?

2017-07-31 15:48 UTC, rpetrusha commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +As all the platforms your app supports are updated with new framework installations,
As all --> Once? 
Are platforms and framework installations the best terms?

2017-08-09 20:36 UTC, BillWagner commented on docs/csharp/whats-new/relationships-between-language-and-library.md
> +As all the platforms your app supports are updated with new framework installations,
@rpetrusha The usage of 'platform' and 'framework' are consistent with the glossary we just added. Thanks for making me check.

2017-08-09 20:57 UTC, BillWagner commented
@rpetrusha I updated based on your feedback. Let me know what you think. 

/cc @mairaw

2017-08-15 20:24 UTC, rpetrusha approved these changes

2017-08-15 20:25 UTC, rpetrusha commented
LGTM, @BillWagner. This is ready to merge when you want.

2017-08-15 20:56 UTC, merged