move serialization docs
dotnet/docs pull request #2780
Opened 2017-07-29 01:16 UTC by mairaw

Fixes Part 1 of #2770

2017-07-31 21:08 UTC, rpetrusha requested changes
@mairaw, this looks good. There is one formatting issue, a number of MSDN URLs that could be converted to xrefs, and a number of other MSDN URLs that could be converted to docs.

2017-07-31 21:08 UTC, rpetrusha commented on xml/System.Xml.Serialization/XmlIgnoreAttribute.xml
>   For more information about using attributes, see [Attributes](http://msdn.microsoft.com/library/30386922-1e00-4602-9ebf-526b271a8b87).
Change link to `~/docs/standard/attributes/`?

2017-07-31 21:08 UTC, rpetrusha commented on xml/System.Xml.Serialization/XmlTypeAttribute.xml
>   For more information about using attributes, see [Attributes](http://msdn.microsoft.com/library/30386922-1e00-4602-9ebf-526b271a8b87).
Change link to `~/docs/standard/attributes/`?

2017-08-01 02:32 UTC, mairaw commented
@rpetrusha good catch on those links! Even though the comments were not really related to moving the docs, I made the fixes. Please review. I've done some global fixes, so the number of files impacted is probably bigger than the number of files you've given feedback to.

2017-08-01 16:27 UTC, rpetrusha commented
Thanks for making the additional changes, @mairaw. This looks really good. It's ready to merge when you want to.

2017-08-01 16:27 UTC, rpetrusha approved these changes

2017-08-01 23:18 UTC, mairaw commented
I've noticed I've missed one of the serializer msdn links (my VS Code was super slow yesterday). Fixed that one and I'll merge if builds looks good. Thanks @rpetrusha!

2017-08-03 17:27 UTC, merged