Document Explicit/Implicit operators for System.Numerics.Complex.
dotnet/docs pull request #2792
Opened 2017-07-31 19:44 UTC by tompratt-AQ

Document all Explicit and Implicit operators for System.Numerics.Complex.

## Summary
Pulled information from MSDN to document 2 Explicit and 10 Implicit operators for System.Numerics.Complex.

## Suggested Reviewers
@rpetrusha

2017-08-03 18:14 UTC, rpetrusha requested changes
This looks really good, @tompratt-AQ. Just one thing to change -- when I wrote the original code examples, I used an `int` instead of a `uint` in one of the C# code samples.

2017-08-03 18:14 UTC, rpetrusha commented on xml/System.Numerics/Complex.xml
> + [!code-csharp[System.Numerics.Complex.Implicit#9](~/samples/snippets/csharp/VS_Snippets_CLR_System/system.numerics.complex.implicit/cs/implicit1.cs#9)]
The C# code is incorrect. Could you change it, Tom? In its present form:
```
private static void ComplexFromUInt32()
   {
      // <Snippet9>
      int intValue = 197461;
      System.Numerics.Complex c1 = intValue;
      Console.WriteLine(c1);
      // The example displays the following output:
      //       (197461, 0)
      // </Snippet9>
   }
```
Change
``` 
int intValue = 197461;
```
to
```
int intValue = 197461;
```
The VB code is OK.

2017-08-03 22:58 UTC, tompratt-AQ commented
@rpetrusha  Thanks Ron. I changed int intValue; to uint value; and System.Numerics.Complex c1 = intValue; to System.Numerics.Complex c1 = value; as you suggested in your email.

2017-08-03 23:18 UTC, rpetrusha commented
Thanks, @tompratt-AQ. I'll review it first thing tomorrow.

2017-08-04 14:38 UTC, rpetrusha commented
@tompratt-AQ, this looks good. I'll merge now.

2017-08-04 14:38 UTC, rpetrusha approved these changes

2017-08-04 14:38 UTC, merged