Update create template tutorial for .NET 6
dotnet/docs pull request #28070
Opened 2022-02-03 20:08 UTC by adegeo

## Summary

- Updated wording and content to account for .NET 6's new default console template project.
- Removed the editing of the project file step in the tutorial, as these were specific to .NET 5.
- Added a link to the samples repo. Dependent on dotnet/samples#4962

Fixes #27977

@tdykstra tagging you since you've worked in this area

2022-02-04 17:20 UTC, CamSoper requested changes, later dismissed

2022-02-04 17:20 UTC, CamSoper commented on docs/core/tutorials/cli-templates-create-project-template.md
> +Project templates produce ready-to-run projects that make it easy for users to start with a working set of code. .NET includes a few project templates such as a console application or a class library
```suggestion
Project templates produce ready-to-run projects that make it easy for users to start with a working set of code. .NET includes a few project templates such as a console application or a class library. In this example, you'll create a new console project that replaces the standard "Hello World" console output with one that runs asynchronously.
```

2022-02-05 02:25 UTC, tdykstra approved these changes
Looks good.  A couple of nit suggestions to change preexisting text.

2022-02-05 02:25 UTC, tdykstra commented on docs/core/tutorials/cli-templates-create-project-template.md
> +Open up the _program.cs_ file. The standard console project doesn't asynchronously write to the console output, so let's add that. Change your code to the following and save the file:
```suggestion
Open up the _program.cs_ file. The standard console project doesn't asynchronously write to the console output, so let's add that. Change the code to the following and save the file:
```

2022-02-05 02:25 UTC, tdykstra commented on docs/core/tutorials/cli-templates-create-project-template.md
> +Example templates: async project                  consoleasync             [C#]              Common/Console
above in line 111 
extra files folders and files you don't want
-->
extra folders and files you don't want

2022-02-07 20:59 UTC, merged