Teminology Update: .NET runtime -> .NET implementation
dotnet/docs pull request #2818
Opened 2017-08-02 18:57 UTC by tompratt-AQ

## Summary
Of the 62 instances of ".NET runtime(s)", I changed 27 instances across 12 files to ".NET implementation(s)".

I didn't change 35 instances in 17 files for the following reasons:

1. The instance referred to "ASP.NET runtime"
2. The instance was the name of a native image service (for example, ".NET Runtime Optimization Service v2.0.50727_X86").
3. The instances were in "components.md", already completed in [PR 2753](https://github.com/dotnet/docs/pull/2753).

## Suggested Reviewers
@rpetrusha

2017-08-03 17:37 UTC, rpetrusha requested changes
@tompratt-AQ, one suggested change, and a number of changes that should be reverted.

2017-08-03 17:37 UTC, rpetrusha commented on docs/core/index.md
> +- A [.NET implementation](https://github.com/dotnet/coreclr), which provides a type system, assembly loading, a garbage collector, native interop and other basic services.
runtime, and not implementation, is correct here.

2017-08-03 17:37 UTC, rpetrusha commented on docs/core/docker/building-net-docker-images.md
> +The minimal image capable of being used on Linux, `core-deps`, is quite smaller, however your application will need to copy a private copy of the .NET implementation with it. Since containers are alr
runtime, and not implementation, is correct here.

2017-08-03 17:37 UTC, rpetrusha commented on docs/core/docker/building-net-docker-images.md
> +- `microsoft/dotnet:<version>-core-deps` : that is **microsoft/dotnet:1.0.0-core-deps**, if you wish to run self-contained applications use this image. It contains the operating system with all of th
runtime, and not implementation, is correct here.

2017-08-03 17:37 UTC, rpetrusha commented on docs/standard/exceptions/best-practices-for-exceptions.md
> +For example, on .NET implementations that implement App Domains, exceptions may occur across App domains. Suppose App Domain A creates App Domain B, which executes code that throws an exception. For
implement App Domains --> support App Domains

2017-08-03 17:37 UTC, rpetrusha commented on docs/standard/tour.md
> +Some objects reference *unmanaged resources*. Unmanaged resources are resources that aren't automatically maintained by the .NET implementation. For example, a file handle is an unmanaged resource. A
runtime, rather than implementation, is correct here.

2017-08-03 17:37 UTC, rpetrusha commented on docs/standard/tour.md
> +Once the `using` block completes, the .NET implementation automatically calls the `stream` object's <xref:System.IDisposable.Dispose> method, which releases the file handle. The runtime also does thi
runtime, not implementation, is correct here.

2017-08-03 17:37 UTC, rpetrusha commented on docs/standard/tour.md
> +.NET languages are object-oriented with hierarchies of base and derived classes. The .NET implementation only allows object casts and calls that align with the object hierarchy. Remember that every t
runtime, not implementation, is correct here.

2017-08-03 17:37 UTC, rpetrusha commented on xml/System.Data.SqlClient/SqlCommand.xml
> + Because the callback procedure executes from within a background thread supplied by the Microsoft .NET implementation, it is very important that you take a rigorous approach to handling cross-thread
runtime, not implementation, is correct here.

2017-08-03 21:50 UTC, tompratt-AQ commented
@rpetrusha I made your review changes, but also changed instances of ".NET platform" to ".NET implementations" in the following files, so they will need review:
 
docs/core/index.md
docs/core/versions/index.md 
docs/standard/assembly-format.md 
docs/standard/net-standard.md 
docs/standard/tour.md   

The rest of the changes for ".NET platform" are in PR #2831.

2017-08-04 15:21 UTC, rpetrusha commented
Your changes all look good, @tompratt-AQ. I'll merge now.

2017-08-04 15:21 UTC, rpetrusha approved these changes

2017-08-04 15:21 UTC, merged