Terminology Update: .NET platform -> .NET implementation
dotnet/docs pull request #2831
Opened 2017-08-03 20:08 UTC by tompratt-AQ

## Summary
Of the 65 instances of ".NET platform(s)" to ".NET implementation(s)" in 35 files. I changed 60 instances in 32 files. I also changed all instances of ""Core CLR" to "CoreCLR". 

Some of the changes will be done as part of a commit to PR 2818, as they involve the same files.

## Suggested Reviewers
@rpetrusha

2017-08-03 20:12 UTC, tompratt-AQ commented
@rpetrusha I resolved the conflicting file using the "Resolve Conflicts" button, and it indicated that the conflict was resolved. So, I'm not sure why the message still appears.

2017-08-03 21:09 UTC, rpetrusha commented
@tompratt-AQ, I've fixed it.

2017-08-04 15:15 UTC, rpetrusha requested changes
Looks good, @tompratt-AQ. I've left some comments on.

2017-08-04 15:15 UTC, rpetrusha commented on docs/standard/choosing-core-framework-server.md
> +There are two supported implementations for building server-side applications with .NET: .NET Framework and .NET Core. Both share a lot of the same .NET Standard components and you can share code acr
same .NET Standard components --> same components

2017-08-04 15:15 UTC, rpetrusha commented on docs/standard/class-libraries.md
The heading should read ".NET Standard class libraries", not ".NET Core Class Libraries"

2017-08-04 15:15 UTC, rpetrusha commented on docs/standard/class-libraries.md
> +.NET Core exposes a set of library _contracts_. .NET implementations must support each contract fully or not at all. Each implementation, therefore, supports a set of .NET Core contracts. The corolla
.NET Core exposes --> The .NET Standard 
.NET Core contracts --> .NET Standard contracts
.NET Core class library --> .NET Standard class library

2017-08-04 15:15 UTC, rpetrusha commented on docs/standard/class-libraries.md
>  .NET Core contracts do not expose the entire functionality of the .NET Framework (nor is that a goal), however, they do expose many more APIs than Portable Class Libraries. More APIs will be added ov
.NET Core contracts do --> The .NET Standard does

2017-08-04 15:15 UTC, rpetrusha commented on xml/System.Timers/Timer.xml
> +>  The <xref:System.Timers.Timer> class is available in the .NET Framework only. It is not included in the .NET Standard and is not available on other platforms, such as .NET Core or the Universal Wi
There are a couple more occurrences of platform in this text that should be changed to implementation.

2017-08-04 15:15 UTC, rpetrusha commented on xml/System/Type.xml
> + If the <xref:System.Type.Assembly%2A?displayProperty=fullName> property is not available on a particular .NET implementation, such as .NET Core or the Universal Windows Platform, use the  `System.Re
"use the  `System.Reflection.TypeInfo.Assembly` property instead. ?qualifyHint=False&autoUpgrade=True": I wonder how this happened. it should be `use the <xref:System.Reflection.TypeInfo.Assembly?displayProperty=fullName> property instead.`

2017-08-04 22:46 UTC, rpetrusha commented
Thanks for making the changes, @tompratt-AQ. This looks good, so I'll merge it now.

2017-08-04 22:46 UTC, rpetrusha approved these changes

2017-08-04 22:47 UTC, rpetrusha commented
Actually, take that back, @tompratt-AQ. I'll merge when the build finishes.

2017-08-04 22:52 UTC, tompratt-AQ commented
@rpetrusha Thanks Ron!

2017-08-05 01:14 UTC, merged