Update tuples topic for C# 7.1
dotnet/docs pull request #2849
Opened 2017-08-08 02:07 UTC by BillWagner

Fixes #2798

This update discusses tuple field name projections.

2017-08-08 13:58 UTC, BillWagner commented
Would you like to look over this one as well @jcouv?

2017-08-08 17:33 UTC, mairaw reviewed
minor edits

2017-08-08 17:33 UTC, mairaw commented on docs/csharp/tuples.md
> +The tuple in the above example was initialized using literal constants and
above -> previous

2017-08-08 17:33 UTC, mairaw commented on docs/csharp/tuples.md
> +will not have field names created using *Tuple field name projections* in C# 7.1.
will not -> won't

2017-08-08 17:33 UTC, mairaw commented on docs/csharp/tuples.md
> +In general, tuple projection initializers work by using the variable or
right-hand should be hyphened

2017-08-08 21:33 UTC, BillWagner commented
@mairaw I fixed everything you mentioned. Ready to :shipit:?

2017-08-08 21:42 UTC, jcouv commented on docs/csharp/tuples.md
>  their fields `Item1`, `Item2`, and so on. Those names carry no semantic
Those where properties, not fields.

2017-08-08 21:43 UTC, jcouv commented on docs/csharp/tuples.md
> +and use semantically meaningful names for the fields in a tuple.
Perhaps "elements" instead of "fields".

2017-08-08 21:43 UTC, jcouv commented on docs/csharp/tuples.md
> +the language support for tuples leverages the new `ValueTuple` classes.
Perhaps "types" or "structs" instead of "classes".

2017-08-08 21:45 UTC, jcouv commented on docs/csharp/tuples.md
> +won't have field names created using *Tuple field name projections* in C# 7.1.
>field [](start = 11, length = 5)

General terminology: we refer to "elements" of tuples, and the "cardinality" of tuples (for the number of elements).
ValueTuple on the other hand has fields and an arity (from 0 to 8).

2017-08-08 21:47 UTC, jcouv commented on docs/csharp/tuples.md
> +> In C# 7.1, tuple projections enable you to create named tuples using fields, in a manner simlar to the property naming in anonymous types. In the above code,
>simlar [](start = 91, length = 6)

s/simlar/similar/

2017-08-08 21:48 UTC, jcouv approved these changes
LGTM with a couple of nits and suggestions.

2017-08-08 22:14 UTC, jcouv commented on docs/csharp/tuples.md
> +won't have element names created using *Tuple field name projections* in C# 7.1.
You may want to do a scrub on the whole file for "fields". For instance, here you can say "Tuple element name projections".

2017-08-08 23:08 UTC, jcouv approved these changes
Awesome. Thanks!

2017-08-17 22:37 UTC, rpetrusha requested changes
This looks good, @BillWagner. Left a few comments.

2017-08-18 22:29 UTC, BillWagner commented
@rpetrusha I addressed all your comments. Do you want to give it a final look?

2017-08-18 23:25 UTC, rpetrusha commented
@BillWagner, LGTM. I'll merge.

2017-08-18 23:25 UTC, rpetrusha approved these changes

2017-08-18 23:25 UTC, merged