Remove Windows 7 incompatibility mention
dotnet/docs pull request #28627
Opened 2022-03-11 01:50 UTC by NN---

.NET 6.0.3 brings single file support for Windows 7 back.
https://github.com/dotnet/runtime/pull/63533

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2022-03-18 18:50 UTC, adegeo requested changes
How does this sound? I think it would be nice to specify the supported version this starts in.

2022-03-18 18:50 UTC, adegeo commented on docs/core/deploying/single-file/overview.md
Let's improve this a bit so there isn't any confusion.
```suggestion

> [IMPORTANT]
> To run a single file app on Windows 7, you must use .NET Runtime 6.0.3 or later.
```

2022-06-23 18:00 UTC, gewarren commented on docs/core/deploying/single-file/overview.md
> +> To run a single file app on Windows 7, you must use .NET Runtime 6.0.3 or later.
```suggestion
> To run a single file app on Windows 7, you must use .NET Runtime 6.0.3 or later.

```

2023-06-30 23:18 UTC, adegeo approved these changes

2023-06-30 23:24 UTC, merged