Add document for CA1851
dotnet/docs pull request #28732
Opened 2022-03-18 22:42 UTC by Cosifne

Hi,
I checked in a new analyzer in Roslyn Analyzer repo 
[PR](https://github.com/dotnet/roslyn-analyzers/pull/5907)
[Design](https://github.com/dotnet/runtime/issues/63381)

2022-03-19 07:31 UTC, Youssef1313 requested changes
This needs an entry in [performance-warnings.md](https://github.com/dotnet/docs/blob/main/docs/fundamentals/code-analysis/quality-rules/performance-warnings.md) as well.

2022-03-19 07:32 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +title: "CA1851: Possible multiple enumerations of `IEnumerable` collection"
I don't think titles and descriptions should use backticks.

2022-03-19 07:32 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +Collection with [IEnumerable](https://docs.microsoft.com/en-us/dotnet/api/system.collections.ienumerable?view=net-6.0) or [IEnumerable\<T\>](https://docs.microsoft.com/en-us/dotnet/api/system.collect
All these links should be `xref`s

2022-03-19 07:33 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +If the underlying type of `IEnumerable` collection is an iterator-based implementation generated by [yield return](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/yield) st
This should be a relative link.

2022-03-19 07:33 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +## Configure customized enumeration methods and LINQ chain methods.
Titles shouldn't end in periods

2022-03-19 07:34 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +[Deferred execution example (LINQ to XML)](https://docs.microsoft.com/en-us/dotnet/standard/linq/deferred-execution-example)
Should be relative link

2022-03-19 13:01 UTC, Youssef1313 commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +```
There need to be VB code snippets I think.

2022-03-21 19:12 UTC, gewarren reviewed
Thanks for adding this!

2022-03-21 19:12 UTC, gewarren commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +Customized LINQ chain methods (methods take `IEnumerable` parameters and return a new `IEnumerable` instance) could also be added by setting the [`linq_chain_methods`](https://github.com/dotnet/rosly
```suggestion
You can also add customized LINQ chain methods (that is, methods take an `IEnumerable` argument and return a new `IEnumerable` instance) to the analysis scope by setting the [`linq_chain_methods`](https://github.com/dotnet/roslyn-analyzers/blob/main/docs/Analyzer%20Configuration.md#linq-chain-methods) option in an *.editorconfig* file.
```

2022-03-21 19:12 UTC, gewarren commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +By default, all the customized methods accepting `IEnumerable` parameters are considered not enumerating the parameters. It can changed by setting the [`assume_method_enumerates_parameters`](https://
```suggestion
By default, all customized methods that accept an `IEnumerable` argument are assumed not to enumerate the argument. You can change this by setting the [`assume_method_enumerates_parameters`](https://github.com/dotnet/roslyn-analyzers/blob/main/docs/Analyzer%20Configuration.md#assume-method-enumerates-parameters) option in an *.editorconfig* file.
```

2022-03-21 19:12 UTC, gewarren commented on docs/fundamentals/code-analysis/quality-rules/ca1851.md
> +It is safe to suppress the warnings if the underlying of the `IEnumerable` collection is some other type like `List` or `Array`, or if you are sure the methods accepting `IEnumerable` collection woul
```suggestion
It is safe to suppress this warning if the underlying of the `IEnumerable` collection is some other type like `List` or `Array`, or if you're sure that methods that take an `IEnumerable` collection do not enumerate it.
```

2022-03-21 19:12 UTC, gewarren commented on docs/fundamentals/code-analysis/quality-rules/index.md
> +> | [CA1851: Possible multiple enumerations of `IEnumerable` collection](ca1851.md) | Possible multiple enumerations of `IEnumerable` collection. Consider using an implementation that avoid multiple
```suggestion
> | [CA1851: Possible multiple enumerations of `IEnumerable` collection](ca1851.md) | Possible multiple enumerations of `IEnumerable` collection. Consider using an implementation that avoids multiple enumerations. |
```

2022-03-31 17:41 UTC, Cosifne commented
Ah, I forget this PR in the last few weeks, will update it soon.

2022-04-01 19:45 UTC, gewarren approved these changes

2022-04-01 21:19 UTC, merged