Update struct.md
dotnet/docs pull request #28893
Opened 2022-04-01 22:05 UTC by chessboards

Readonly static members are possible. I may have not exhausted the list of members excluded from being applicable to both readonly and static, so further edits may be necessary.

## Summary

Fixes unclear and misleading information regarding the usage of static readonly members.

Fixes #Issue_Number (if available)

2022-04-04 19:46 UTC, BillWagner commented
Hi 👋 @chessboards 

That statement on disallowing `readonly` should stay. It's meant to cover this example:

```csharp
struct S
{
    // CS 8657: Can't apply "readonly" to a static method:
    public static readonly void M()
    {

    }
}
```

How did you interpret that statement? Would a different wording make that more clear?

2022-04-06 23:43 UTC, chessboards commented
I think the wording could be changed to make the distinction clearer between static members that should not interact with the structure instance or state (methods, events, props with setters), and those that have no state changing logic (therefore can be made readonly). The wording of `members` led me to include static fields and get-only properties as also being excluded, which they are not. https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/members

2022-04-07 14:00 UTC, BillWagner requested changes
Thanks @chessboards 

I made a suggestion to this PR. Once you accept that, I'll :shipit:

2022-04-07 14:00 UTC, BillWagner commented on docs/csharp/language-reference/builtin-types/struct.md
> +You can apply the `readonly` modifier to static members of a structure type excluding static members able to modify the structure instance.
Thanks for adding your comments @chessboards. That helps. I'd suggest updating this PR as follows:

```suggestion
You can apply the `readonly` modifier to static fields of a structure type, but not any other static members, such as properties or methods.
```

2022-04-08 00:40 UTC, BillWagner approved these changes

2022-04-08 00:41 UTC, BillWagner commented
thanks again @chessboards 

I've set this to auto merge as soon as the builds finish.  You should see it live tomorrow, on our regular publishing cycle.

Thanks again!

2022-04-08 00:42 UTC, merged