Fix broken tabs
dotnet/docs pull request #2904
Opened 2017-08-14 22:26 UTC by mairaw

Tabs are broken for dotnet page:

![image](https://user-images.githubusercontent.com/12971179/29294570-d73d207a-8104-11e7-9dd4-896bd69c692d.png)

2017-08-15 15:31 UTC, JRAlexander requested changes
A couple of minor changes.

2017-08-15 15:31 UTC, JRAlexander commented on docs/core/tools/dotnet.md
> +
Still broken. Remove blank lines before each hr. Tabs don't like them.

2017-08-15 18:15 UTC, mairaw commented on docs/core/tools/dotnet.md
> +
That's how it was before, no @JRAlexander? I'll change to the code block. It works on the other topics like that.

2017-08-15 18:53 UTC, JRAlexander commented on docs/core/tools/dotnet.md
> +
ok.

2017-08-15 18:54 UTC, JRAlexander approved these changes

2017-08-16 16:39 UTC, rpetrusha commented
@mairaw, I have no idea why, but although the tabs are rendering (that is, there are separate tabs for 1.x and 2.x, as expected), their content is identical.

2017-08-16 18:02 UTC, mairaw commented
@rpetrusha it's not actually switching. I'll try one more thing to see if I can workaround this.

/cc @EisenbergEffect - one issue we're facing with tabs

2017-08-16 20:19 UTC, EisenbergEffect commented
@jdanyow It looks like we might have a bug in tabs. Can you investigate?

@mairaw Is there a chance that I could get added as a member of the dotnet org? Notifications for dotnet are going to my personal email address instead of my Microsoft address, so I sometimes don't see these in a timely fashion. I'd love to improve that.

2017-08-17 05:49 UTC, mairaw commented
I think I might have found the issue @EisenbergEffect @jdanyow

2017-08-17 05:50 UTC, EisenbergEffect commented
@mairaw Was it a syntax problem or is there a legitimate bug we need to follow up on?

2017-08-17 06:42 UTC, mairaw commented
I had a syntax problem but I'll make some more tests tomorrow to make sure @EisenbergEffect

2017-08-17 06:50 UTC, EisenbergEffect commented
Sounds good. If you confirm the syntax issue, I'd love to understand the details of that as well. We hope to put some syntax validation in place as part of Gauntlet and OPS in the future.

2017-08-17 15:21 UTC, rpetrusha commented
@mairaw, this looks as if it builds correctly now!

2017-08-17 16:06 UTC, merged