Update ref-returns.md
dotnet/docs pull request #2914
Opened 2017-08-15 15:06 UTC by franckyj

It seems like there's a missing 'not' when explaining why ref return values cannot be part of `async` methods. I might be wrong but it would make sense that since their values are not know, they cannot be in `async` methods.

2017-08-15 15:06 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-15 15:46 UTC, rpetrusha requested changes
Thanks for submitting this PR, @franckyj. The original sentence is correct, though it can easily be misinterpreted. The intent is that an async method can return: 1. before it has finished execution; and 2. before its return method is known. So adding "not" doesn't help here. I'd suggest changing the sentence instead to, "In addition, because an asynchronous method may return before it has finished execution, while its return value is still unknown, reference return values are not allowed on `async` methods." Could you make this change? If not, let us know, and we'll make it.

2017-08-15 15:54 UTC, franckyj commented
Thanks @rpetrusha for the clarification. Your suggestion, I think, will avoid any confusion in the future (at least for me!).

2017-08-15 17:21 UTC, rpetrusha commented
Thanks for making the additional change and doing it so quickly, @franckyj! This looks good. Once the build finishes, we'll merge.

2017-08-15 17:21 UTC, rpetrusha approved these changes

2017-08-16 06:07 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-16 06:51 UTC, mairaw commented
Thank you @franckyj! We appreciate your contribution to make our topic more clear.

2017-08-16 06:51 UTC, merged