Update backtracking in regex to mention global timeout
dotnet/docs pull request #29160
Opened 2022-04-23 22:15 UTC by danmoseley

The little-known global timeout security feature is worth describing here. 
Copied from https://docs.microsoft.com/en-us/dotnet/api/system.text.regularexpressions.regex?view=net-6.0#defining-a-time-out-value

2022-04-24 18:09 UTC, adegeo requested changes
LGTM. One minor thing to fix.

2022-04-24 18:09 UTC, adegeo commented on docs/standard/base-types/backtracking-in-regular-expressions.md
> +If you do not set a time-out value explicitly, the default time-out value  is determined as follows:
There is a double space mid sentence here
```suggestion
If you do not set a time-out value explicitly, the default time-out value is determined as follows:
```

2022-04-25 03:43 UTC, danmoseley commented
Fixed it

2022-05-01 19:11 UTC, danmoseley commented
@gewarren are you able to merge this?

2022-05-02 16:58 UTC, gewarren approved these changes

2022-05-02 17:17 UTC, adegeo approved these changes

2022-05-02 17:17 UTC, merged