Modified TOC, corrected bad link
dotnet/docs pull request #2916
Opened 2017-08-15 22:38 UTC by rpetrusha

# Modified TOC, corrected bad link

## Summary

Added getting started tutorials to the .NET Core Getting Started section

## Suggested Reviewers

@mairaw

2017-08-16 05:49 UTC, mairaw requested changes

2017-08-16 05:49 UTC, mairaw commented on docs/toc.md
> +### [Build a Visual Basic Hello World app with .NET Core in Visual Studio 2017](core/tutorials/w)
broken link

2017-08-16 05:49 UTC, mairaw commented on docs/toc.md
> +### [Build a class library with Visual Basic and .NET Core in Visual Studio 2017](core/tutorials/vb-library-with-visual-studio.md)
why do we have the same link in two places? For example, you'll end up with two locations on the TOC highlighted and screen will always sync on the first one, even if you click inside the VB toc. e.g. https://review.docs.microsoft.com/en-us/dotnet/core/tutorials/vb-library-with-visual-studio?branch=pr-en-us-2916

2017-08-16 05:49 UTC, mairaw commented on docs/toc.md
> +### [Get started with C# and Visual Studio Code](core/tutorials/with-visual-studio-code.md)
I was actually thinking about these topics this week and I think they belong under Get Started as you did here. Let's test this new location and if we feel that's the right spot, we should also move physical locations (again).

2017-08-16 17:58 UTC, rpetrusha commented on docs/toc.md
> +### [Build a class library with Visual Basic and .NET Core in Visual Studio 2017](core/tutorials/vb-library-with-visual-studio.md)
@mairaw, I've removed it.

2017-08-17 21:05 UTC, rpetrusha commented
@mairaw, addressed your comments and removed the duplication from the TOC.

2017-08-17 21:05 UTC, rpetrusha commented
Closing and reopening to restart build.

2017-08-29 01:11 UTC, mairaw approved these changes
LGTM but build report still showing warnings. I've highlighted the one I found. Good to merge once builds are green.

2017-08-29 01:11 UTC, mairaw commented on docs/toc.md
> +### [Build a Visual Basic Hello World app with .NET Core in Visual Studio 2017](core/tutorials/w)
broken link

2017-08-29 16:38 UTC, merged