Updated portal pages for VB getting started
dotnet/docs pull request #2939
Opened 2017-08-18 17:36 UTC by rpetrusha

# Updated portal pages for VB getting started

## Suggested Reviewers

@mairaw

2017-08-18 19:01 UTC, mairaw commented on docs/core/get-started.md
> +* [Build a Visual Basic Hello World application with .NET Core in Visual Studio 2017](../../core/tutorials/vb-with-visual-studio.md) - Learn to to build, debug, and publish a simple .NET Core console
build is giving you warnings for these new links. Probably should be ./tutorials

2017-08-18 19:01 UTC, mairaw requested changes
needs to fix broken links

2017-08-18 19:12 UTC, rpetrusha commented
@mairaw, I've fixed them.

2017-08-18 19:14 UTC, mairaw approved these changes
I thought we were going to use tabs for these C#/VB tutorials. But as-is, these changes look good.

2017-08-18 19:27 UTC, rpetrusha commented
@mairaw, I merged this, but I hadn't thought of using tabs for the portal page. I think that's a good idea. I'll submit a new PR later.

2017-08-18 19:35 UTC, mairaw commented
I didn't mean for the portals but for the actual tutorials. That's why I requested the language tabs.

2017-08-18 19:37 UTC, rpetrusha commented
@mairaw, I used tabs for the debugging, publishing, testing, and consuming topics. Tabs didn't seem very helpful for the initial tutorial, so I did separate ones.

2017-08-18 20:39 UTC, merged

2017-08-19 00:43 UTC, mairaw commented
Sounds good @rpetrusha. Thanks!