xref specific TaskStatus fields
dotnet/docs pull request #2943
Opened 2017-08-18 20:43 UTC by Magnificus36

Specify specific states (RanToCompletion, Faulted or Canceled) instead of xref to the entire System.Threading.Tasks.TaskStatus Enum.

2017-08-18 20:43 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-18 21:42 UTC, rpetrusha requested changes
Thank you so much, @Magnificus36, for making these corrections. The missing enumeration member names were a result of content loss when we migrated from MSDN to GitHub. 
Where enumeration members are used, it's clearest if their type name (as in TaskStatus.RanToCompletion rather than just RanToCompletion) appears in the documentation. In an `<xref>`, that's done by including `?displayProperty=fullName` after the member name. I've indicated each case where displayProperty should be added. You've already put an impressive amount of work into this PR, though, so if you'd prefer that we make the change instead, please let us know.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + This property returns a task whose <xref:System.Threading.Tasks.Task.Status%2A> property is set to <xref:System.Threading.Tasks.TaskStatus.RanToCompletion>. To create task that returns a value and r
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + After the specified time delay, the task is completed in the <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + After the specified time delay, the task is completed in <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If the cancellation token is signaled before the specified time delay, a <xref:System.Threading.Tasks.TaskCanceledException> exception results, and the task is completed in the <xref:System.Threadin
The two xrefs should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>` and `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + The following example launches a task that includes a call to the <xref:System.Threading.Tasks.Task.Delay%28System.Int32%2CSystem.Threading.CancellationToken%29> method with a one second delay. Befo
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If the cancellation token is signaled before the specified time delay, a <xref:System.Threading.Tasks.TaskCanceledException> exception results, and the task is completed in the <xref:System.Threadin
The two xrefs should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>` and `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + The following example launches a task that includes a call to the <xref:System.Threading.Tasks.Task.Delay%28System.TimeSpan%2CSystem.Threading.CancellationToken%29> method with a one-and-a-half seco
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + This method creates a <xref:System.Threading.Tasks.Task> object whose <xref:System.Threading.Tasks.Task.Status%2A> property is <xref:System.Threading.Tasks.TaskStatus.Faulted> and whose <xref:System
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + This method creates a <xref:System.Threading.Tasks.Task%601> object whose <xref:System.Threading.Tasks.Task.Status%2A> property is <xref:System.Threading.Tasks.TaskStatus.Faulted> and whose <xref:Sy
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + This method creates a <xref:System.Threading.Tasks.Task%601> object whose <xref:System.Threading.Tasks.Task%601.Result%2A?displayProperty=fullName> property is `result` and whose <xref:System.Thread
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + A <xref:System.Threading.Tasks.Task> will complete in the <xref:System.Threading.Tasks.TaskStatus.Canceled> state under any of the following conditions:
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + Tasks executed by calling the <xref:System.Threading.Tasks.Task.RunSynchronously%2A> method are instantiated by calling a <xref:System.Threading.Tasks.Task> or <xref:System.Threading.Tasks.Task%601>
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Created?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + Tasks executed by calling the <xref:System.Threading.Tasks.Task.RunSynchronously%2A> method are instantiated by calling a <xref:System.Threading.Tasks.Task> or <xref:System.Threading.Tasks.Task%601>
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Created?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + The following example illustrates the simple use of a cancellation token to cancel waiting for a task's completion. A task is launched, calls the <xref:System.Threading.CancellationTokenSource.Cance
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If any of the supplied tasks completes in a faulted state, the returned task will also complete in a <xref:System.Threading.Tasks.TaskStatus.Faulted> state,  where its exceptions will contain the ag
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the supplied tasks faulted but at least one of them was canceled, the returned task will end in the <xref:System.Threading.Tasks.TaskStatus.Canceled> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the tasks faulted and none of the tasks were canceled, the resulting task will end in the <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state.
The xrefs should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If the supplied array/enumerable contains no tasks, the returned task will immediately transition to a <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state before it's returned to the call
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If any of the supplied tasks completes in a faulted state, the returned task will also complete in a <xref:System.Threading.Tasks.TaskStatus.Faulted> state, where its exceptions will contain the agg
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the supplied tasks faulted but at least one of them was canceled, the returned task will end in the <xref:System.Threading.Tasks.TaskStatus.Canceled> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the tasks faulted and none of the tasks were canceled, the resulting task will end in the <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If the supplied array/enumerable contains no tasks, the returned task will immediately transition to a <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state before it's returned to the call
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If any of the supplied tasks completes in a faulted state, the returned task will also complete in a <xref:System.Threading.Tasks.TaskStatus.Faulted> state, where its exceptions will contain the agg
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the supplied tasks faulted but at least one of them was canceled, the returned task will end in the <xref:System.Threading.Tasks.TaskStatus.Canceled> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the tasks faulted and none of the tasks were canceled, the resulting task will end in the <xref:System.Threading.Tasks.TaskStatus.RanToCompletion state.  The <xref:System.Threading.Tasks.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`. Note that the closing bracket is missing here.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If the `tasks` argument contains no tasks, the returned task will immediately transition to a <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state before it's returned to the caller. The r
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If any of the supplied tasks completes in a faulted state, the returned task will also complete in a <xref:System.Threading.Tasks.TaskStatus.Faulted> state, where its exceptions will contain the agg
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Faulted?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the supplied tasks faulted but at least one of them was canceled, the returned task will end in the <xref:System.Threading.Tasks.TaskStatus.Canceled> state.
The xref should be `<xref:System.Threading.Tasks.TaskStatus.Canceled?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If none of the tasks faulted and none of the tasks were canceled, the resulting task will end in the <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state.  The <xref:System.Threading.Tasks
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 21:42 UTC, rpetrusha commented on xml/System.Threading.Tasks/Task.xml
> + If the supplied array/enumerable contains no tasks, the returned task will immediately transition to a <xref:System.Threading.Tasks.TaskStatus.RanToCompletion> state before it's returned to the call
The xref should be `<xref:System.Threading.Tasks.TaskStatus.RanToCompletion?displayProperty=fullName>`.

2017-08-18 22:44 UTC, Magnificus36 commented
Regarding the `?displayProperty=fullName` I followed lines 2692, 2753, 2937 and 3219 where specific members of TaskStatus where already referenced.
Plus I choose to remove/omit the `?displayProperty=fullName` because I thought that adding it would result in `System.Threading.Tasks.TaskStatus.RanToCompletion` being displayed not just `TaskStatus.RanToCompletion` which would make the documentation less nice to read. Currently `<xref:System.Threading.Tasks.TaskStatus?displayProperty=fullName>` is displayed as `System.Threading.Tasks.TaskStatus` on the final documentation webpages.

However, if the addition of `?displayProperty=fullName` is indeed desired I'll gladly add it.
And should it then also be added on lines 2692, 2753, 2937 and 3219? If so, I'll directly change them too.

2017-08-24 01:22 UTC, rpetrusha commented
I apologize that I've allowed your PR to languish, @Magnificus36. Although I'd like `?displayProperty=fullName` to be present, I have to agree with you that it actually makes the documentation less readable rather than more. I'm hoping that we'll restore the MSDN behavior, in which the fully qualified name of a member is only the type and member, rather than the namespace, type, and member. If and until that happens, though, I think that it's best to accept your PR. So thank you so much for noticing the loss of content, for fixing it, and for responding so quickly.

2017-08-24 01:23 UTC, rpetrusha approved these changes

2017-08-24 01:23 UTC, merged