Simplify Linux install overview
dotnet/docs pull request #29462
Opened 2022-05-14 21:53 UTC by richlander

2022-05-16 19:08 UTC, adegeo requested changes
I'm willing to try this since it simplifies the content. However, note that we do have a lot of views on this content (almost 50k a month) and it has good ratings. This would indicate that it is satisfying the needs of the readers.

There are a few things to fix up before merging.

2022-05-16 19:08 UTC, adegeo commented on docs/core/install/linux.md
> +## Other Distros
I don't think we use the word distro in docs
```suggestion
## Other distributions
```

2022-05-16 19:08 UTC, adegeo commented on docs/core/install/linux.md
> +Installation information is als provided for other distributions.
bug
```suggestion
Installation information is also provided for other distributions.
```

2022-05-18 05:31 UTC, richlander commented
I don't doubt that some people like the current format. It has a lot of information and it is (mostly) accurate. I have to believe that others are overwhelmed by all the information. There is a lot more information than is needed for folks to be successful. Last,  all of this support information take a lot of care and feeding. Ideally, we can just rely on it in release notes (which uses a simpler format) and call it good.

Yes, let's see if we can maintain or improve the rating!

2022-05-30 15:51 UTC, richlander commented
I believe this topic is ready to go @adegeo.

2022-05-30 16:46 UTC, richlander commented
I believe this topic is ready to go @adegeo.

2022-05-31 17:36 UTC, adegeo approved these changes

2022-05-31 17:43 UTC, richlander commented
Thanks @adegeo!

2022-05-31 18:10 UTC, merged