Update link with download location for MEFX
dotnet/docs pull request #2946
Opened 2017-08-19 01:05 UTC by terrajobst

CodePlex is being shutdown. I've updated the archived version of MEF and included the source & binaries of MEFX.

2017-08-19 01:05 UTC, dnfclas commented
@terrajobst,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-19 01:08 UTC, dsplaisted commented on docs/framework/mef/composition-analysis-tool-mefx.md
> + Mefx is available on Codeplex at [Managed Extensibility Framework](https://github.com/MicrosoftArchive/mef/releases/tag/4.0). Simply download and unzip the tool.
It still says "available on Codeplex"

2017-08-19 22:58 UTC, mairaw requested changes
Please address @dsplaisted comment. LGTM otherwise.

2017-08-21 20:03 UTC, terrajobst commented on docs/framework/mef/composition-analysis-tool-mefx.md
> + Mefx is available on Codeplex at [Managed Extensibility Framework](https://github.com/MicrosoftArchive/mef/releases/tag/4.0). Simply download and unzip the tool.
Good call 😄

2017-08-23 18:08 UTC, mairaw approved these changes

2017-08-23 18:08 UTC, merged