.NET Standard 2 does not support net461
dotnet/docs pull request #29599
Opened 2022-05-24 01:12 UTC by SimonCropp

it is misleading to imply that is does when there are so many incompatibilities between the two
https://www.google.com/search?q=netStandard2+net461+error

2022-05-24 13:00 UTC, IEvangelist commented
I defer to @terrajobst on this one. From the standpoint of the docs, we were relying on Immo's interactive table as a source of truth. Immo, are you good with this change?

2022-05-24 23:30 UTC, terrajobst approved these changes
The suggested wording seems clearer. Thanks @SimonCropp!

2022-05-24 23:37 UTC, gewarren reviewed
Left a couple suggestions. I think it would look funny to have the superscript 2 at the start of the list.

2022-05-24 23:37 UTC, gewarren commented on includes/net-standard-2.0.md
> +| .NET Framework <sup>1</sup> | <sup>2</sup> 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8        |
```suggestion
| .NET Framework <sup>1</sup> | 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8 <sup>2</sup>        |
```

2022-05-24 23:37 UTC, gewarren commented on includes/net-standard-2.0.md
> +<sup>2</sup> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. For .NET Framework projects that need to use such libraries
```suggestion
<sup>2</sup> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. For .NET Framework projects that need to use .NET Standard 2.0, we recommend that you upgrade the project to target .NET Framework 4.7.2 or higher.
```

2022-05-25 00:23 UTC, terrajobst requested changes
Oh, I didn't realize that @SimonCropp was suggesting removing 4.6.1 from the table. I think that would be a mistake. People need to know the compatibility rules baked into NuGet because it controls which assets are selected. I think we should leave 4.6.1 there or it can result in surprises.

2022-05-25 00:24 UTC, terrajobst commented on includes/net-standard-2.0.md
> +| .NET Framework <sup>1</sup> | <sup>2</sup> 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8        |
I think we should revert this part.

2022-05-25 00:24 UTC, terrajobst commented on includes/net-standard-2.0.md
> +<sup>2</sup> The versions listed here represent the rules that NuGet uses to determine whether a given .NET Standard library is applicable. For .NET Framework projects that need to use such libraries
I like that!

2022-05-25 01:03 UTC, SimonCropp commented
>  I think we should leave 4.6.1 there or it can result in surprises.

the point of this PR is that there are so many issues with mixing  4.6.1 with netstandard2, that having in that table is leading people down a path of pain,

2022-05-25 01:41 UTC, SimonCropp commented
> Sadly, this is the kind of bug we can't fix without breaking even more stuff

i get that. and i am ok with this. but given the caveats and problems people have, i think having net461 in that table does more harm than good

2022-07-11 15:00 UTC, IEvangelist commented on includes/net-standard-2.0.md
> +| .NET Framework <sup>1</sup> | <sup>2</sup> 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8        |
```suggestion
| .NET Framework <sup>1</sup> | 4.6.1 <sup>2</sup>, 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8 |
```

Revert this per @terrajobst

2022-07-11 15:01 UTC, IEvangelist approved these changes

2022-07-15 01:43 UTC, closed without merging