Update .NET Core installation instructions for RHEL 7
dotnet/docs pull request #2965
Opened 2017-08-22 17:53 UTC by omajid

## Summary

Clean up RHEL 7 installation text and make it shorter, more complete and more consistent with rest of the documentation.

## Details

- Fix strange heading and make it more consistent with other headings in this doc
- Remove warnings about removing previous versions - the whole point of SCL is to make everything, including native libraries, installable side-by-side.
- Add separate installation steps for 1.0, 1.1 and 2.0. 

One note: I dont know how to render this doc locally. Some formatting may be off.

2017-08-22 17:53 UTC, dnfclas commented
@omajid,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-08-25 19:48 UTC, JRAlexander requested changes
@omajid  ,
This is great! Just a small set of changes and we will be good to go. Thanks!

2017-08-25 19:48 UTC, JRAlexander commented on docs/core/linux-prerequisites.md
> +---
Omair, This is great!
Just one set of changes and we are good to go.
The code snippet sections inside the tab (# [.NET Core 2.x](#tab/netcore2x)) need to be fully left justified to display correctly. Look at the tabs in the Ubuntu section for an example.
Please update those and I will get it merged. Thanks for your contribution!!!

2017-08-25 19:57 UTC, omajid commented
Thanks for the review. I have updated the spaces in the code segments.

2017-08-28 02:47 UTC, JRAlexander approved these changes

2017-08-28 02:47 UTC, merged

2017-08-28 13:04 UTC, omajid commented
Thanks for merging this! Can you let me know when this version goes live?

2017-08-28 20:42 UTC, JRAlexander commented
Sorry!