Update configure-language-version.md
dotnet/docs pull request #29722
Opened 2022-06-04 06:15 UTC by zzfima

C# 11 add info

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2022-06-04 12:28 UTC, Youssef1313 commented on docs/csharp/language-reference/configure-language-version.md
> +[C# 11](../whats-new/csharp-11.md) is supported only on .NET 6.0.200 and newer versions. [C# 10](../whats-new/csharp-10.md) is supported only on .NET 6 and newer versions. [C# 9](../whats-new/csharp-
I'm not sure this is correct. C# 11 should be *officially* supported on .NET 7 and later.

2022-06-06 14:50 UTC, BillWagner requested changes
Thanks @zzfima 

As @Youssef1313 points out, using C# 11 with the .NET 6 SDK is enabled, but not supported. I made some suggestions to clarify that.

Once you accept those suggestions, this is ready to merge.

2022-06-06 14:50 UTC, BillWagner commented on docs/csharp/language-reference/configure-language-version.md
>  The latest C# compiler determines a default language version based on your project's target framework or frameworks. Visual Studio doesn't provide a UI to change the value, but you can change it by e
Adding a sentence here to clarify preview usage:

```suggestion
The latest C# compiler determines a default language version based on your project's target framework or frameworks. Visual Studio doesn't provide a UI to change the value, but you can change it by editing the *csproj* file. The choice of default ensures that you use the latest language version compatible with your target framework. You benefit from access to the latest language features compatible with your project's target. This default choice also ensures you don't use a language that requires types or runtime behavior not available in your target framework. Choosing a language version newer than the default can cause hard to diagnose compile-time and runtime errors. In some cases, preview features are enabled to gather feedback on those features. Those scenarios aren't officially supported.
```

2022-06-06 14:50 UTC, BillWagner commented on docs/csharp/language-reference/configure-language-version.md
> +| .NET             | 6.0.200 | C# 11                       |
Same change here:

```suggestion
| .NET             | 7.x | C# 11                       |
```

2022-06-07 09:13 UTC, zzfima reviewed
ok

2022-06-07 09:16 UTC, Youssef1313 approved these changes

2022-06-07 12:57 UTC, BillWagner approved these changes

2022-06-07 12:58 UTC, BillWagner commented
Thanks again @zzfima 

I've approved this, and it will merge once the build completes.

2022-06-07 13:02 UTC, merged