Fixes #28590
dotnet/docs pull request #29920
Opened 2022-06-18 00:45 UTC by rafcon-dev

Added a clarification explaining that nint's and nuint's max and min values are calculated at runtime. Also added that note to the table with the various types.

2022-06-20 19:16 UTC, BillWagner requested changes
Thanks @rafcon-dev 

I like the change. I made some suggestions for clarity. You can accept the suggestion, or make alternative edits and I'll take another look.

2022-06-20 19:16 UTC, BillWagner commented on docs/csharp/language-reference/builtin-types/integral-numeric-types.md
> +Each of the integral types has `MinValue` and `MaxValue` properties, that provide the minimum and maximum value of that type. These properties are compile-time constants, except for the case of the n
This is missing one closing code fence tick. Also, unnecessary commas. I split the sentences into multiple sentences to make it easier to understand. Finally, I removed the references to 32 bit and 64 bit. (The sizes are also different on IoT devices that could be different sizes. 

```suggestion
Each of the integral types has `MinValue` and `MaxValue` properties that provide the minimum and maximum value of that type. These properties are compile-time constants except for the case of the native-sized types (`nint and `nuint`). The `MinValue` and `MaxValue` properties are calculated at runtime for native-sized types. The sizes of those types depend on the processor.
```

2022-06-21 15:36 UTC, BillWagner commented on docs/csharp/language-reference/builtin-types/integral-numeric-types.md
> +Each of the integral types has `MinValue` and `MaxValue` properties that provide the minimum and maximum value of that type. These properties are compile-time constants except for the case of the nat
```suggestion
Each of the integral types has `MinValue` and `MaxValue` properties that provide the minimum and maximum value of that type. These properties are compile-time constants except for the case of the native-sized types (`nint` and `nuint`). The `MinValue` and `MaxValue` properties are calculated at runtime for native-sized types. The sizes of those types depend on the processor.
```

2022-06-21 22:49 UTC, rafcon-dev commented
Thanks for the hints Bill, I believe the edits are fine.
I ran some tests, and noticed that in fact for these types, it doesn't really depend on the processor of the machine, but instead it depends on the platform target. I tried, on the same i7 computer, with the default settings (which targets x64) and got the corresponding max and min values. Then I changed the target to x86 and I get the expected values for 32bits . That is, as it says on the nint and nuint page (https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/builtin-types/integral-numeric-types#native-sized-integers), the value really depends on the executable settings, and not exactly on the physical processor in the machine. I suspect for other weird IOT cpus the same thing could apply.

2022-06-22 13:43 UTC, BillWagner approved these changes

2022-06-22 13:43 UTC, merged

2022-06-22 13:43 UTC, BillWagner commented
Thanks again @rafcon-dev

2022-06-22 15:04 UTC, rafcon-dev commented
@BillWagner ok, but then isn't the phrase "The sizes of those types depend on the processor." in contradition with what is on the nint and nuint page ("// output when run in a 64-bit process"), which seems to be correct?

2022-06-22 15:26 UTC, BillWagner commented
@rafcon-dev 

Yes, we should make that one additional change. I'd overlooked that in the existing diffs.

2022-06-27 17:46 UTC, rafcon-dev commented
@BillWagner sure thing, I made a new PR for that