Update classification-of-standard-query-operators-by-manner-of-execut…
dotnet/docs pull request #29955
Opened 2022-06-21 23:48 UTC by poojarsn

…ion.md

Updated deferred and Immediate section only.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2022-06-22 14:07 UTC, BillWagner requested changes
Thanks for making these changes @poojarsn 

I had a couple suggestions to improve the clarity. Once you accept those, this is ready to merge.

Thanks for helping us improve.

2022-06-22 14:07 UTC, BillWagner commented on docs/csharp/programming-guide/concepts/linq/classification-of-standard-query-operators-by-manner-of-execution.md
> + Immediate execution means that the data source is read and the operation is performed at the point in the code where the query is declared. All the standard query operators that return a single, non
A couple nits, and replace method names with linkable xrefs:

```suggestion
 Immediate execution means that the data source is read and the operation is performed once. All the standard query operators that return a scalar result execute immediately. You can force a query to execute immediately using the <xref:System.Linq.Enumerable.ToList%2A?displayProperty=nameWithType> or <xref:System.Linq.Enumerable.ToArray%2A?displayProperty=nameWithType> methods. Immediate execution provides reuse of query results, not query declaration. The results are retrieved once, then stored for future use.
```

2022-06-24 19:01 UTC, BillWagner commented
Hi @poojarsn

Did you close this by mistake? It looks like you accepted my changes, and I was ready to merge this.

Let me know, and we'll take care of it.

2022-06-25 01:19 UTC, poojarsn commented
Yes, I happened to close by mistake. I would be grateful if you can merge
it. Thank you much.

On Sat, Jun 25, 2022, 5:01 AM Bill Wagner ***@***.***> wrote:

> Hi @poojarsn <https://github.com/poojarsn>
>
> Did you close this by mistake? It looks like you accepted my changes, and
> I was ready to merge this.
>
> Let me know, and we'll take care of it.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/docs/pull/29955#issuecomment-1165851676>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AD5F3WLE2UDQKKYTD4OPGNLVQYA2NANCNFSM5ZOI2RMQ>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2022-06-25 19:03 UTC, BillWagner approved these changes

2022-06-25 19:03 UTC, merged