Validation  Chapter for MAUI eBook
dotnet/docs pull request #30260
Opened 2022-07-18 15:19 UTC by michaelstonis

## Summary

Provides the validation chapter for the .NET MAUI eBook

2022-07-20 13:40 UTC, IEvangelist requested changes
Looks great, I'm curious, how much of this is homegrown versus built-in? It looks like the `ValidatableObject<T>` is custom. Does .NET MAUI not yet support DataAnnotations for validation?

2022-07-20 13:40 UTC, IEvangelist commented on docs/architecture/maui/validation.md
> +    }
```suggestion
    public bool Check(T value) =>
        value is string str &&
        !string.IsNullOrWhiteSpace(str);
```

Algebraic reduction.

2022-07-20 13:40 UTC, IEvangelist commented on docs/architecture/maui/validation.md
> +    }
```suggestion
    private readonly Regex _regex = new(@"^([w.-]+)@([w-]+)((.(w){2,3})+)$");

    public bool Check(T value) =>
        value is string str && _regex.IsMatch(str);
```

Algebraic reduction, and avoid cache regex in a class-scoped field.

2022-07-20 13:40 UTC, IEvangelist commented on docs/architecture/maui/validation.md
> +The `Check` method returns a boolean indicating whether or not the value argument is a valid email address. This is achieved by searching the value argument for the first occurrence of the regular ex
```suggestion
The `Check` method returns a boolean indicating whether or not the value argument is a valid email address. This is achieved by searching the value argument for the first occurrence of the regular expression pattern specified in the `Regex` constructor. Whether the regular expression pattern has been found in the input string can be determined by checking the `value` against <xref:System.Text.RegularExpressions.Regex.IsMatch%2A?displayProperty=nameWithType>.
```

2022-07-20 13:40 UTC, IEvangelist commented on docs/architecture/maui/validation.md
> +}
```suggestion
  public ValidatableObject<string> UserName { get; private set; }

  public ValidatableObject<string> Password { get; private set; }
```

Use auto-properties when possible.

2022-07-21 22:23 UTC, michaelstonis commented on docs/architecture/maui/validation.md
> +Any app that accepts input from users should ensure that the input is valid. An app could, for example, check for input that contains only characters in a particular range, is of a certain length, or
I like it and agree.

2022-07-21 22:31 UTC, michaelstonis commented
> Looks great, I'm curious, how much of this is homegrown versus built-in? It looks like the `ValidatableObject<T>` is custom. Does .NET MAUI not yet support DataAnnotations for validation?

Unfortunately we don't have any built-in support for data annotations and similar validation constructs. For mobile we either need to use a homegrown solution or a 3rd party component (e.g. [ObservableValidator](https://docs.microsoft.com/en-us/windows/communitytoolkit/mvvm/observablevalidator)).

2022-07-25 20:09 UTC, IEvangelist approved these changes

2022-07-25 20:09 UTC, merged