Add dotnet nuget why documentation
dotnet/docs pull request #30497
Opened 2022-08-04 22:28 UTC by pragnya17

## Summary

Add documentation for `dotnet nuget why`. The implementation of this command is still in progress: https://github.com/NuGet/Home/issues/11782.

2022-08-05 00:51 UTC, tdykstra commented on docs/core/tools/dotnet-nuget-why.md
> +description: The 'dotnet nuget why' command provides the user to view the dependency graph of a package.
```suggestion
description: The 'dotnet nuget why' command shows the dependency graph of a package.
```

2022-08-05 00:51 UTC, tdykstra commented on docs/core/tools/dotnet-nuget-why.md
> +  The NuGet sources to use when searching for newer packages. Requires the `--outdated` option.
The --outdated option isn't in the doc here.

2022-08-05 00:51 UTC, tdykstra commented on docs/core/tools/dotnet-nuget-why.md
> +The `dotnet list package` command provides a way to print out the dependency graph for a package to allow users to understand the nature of top-level packages and their transitive dependencies. This
This would be easier to understand with actual command output using real package/project names rather than packageA and B and projectA and B.

2022-08-05 00:51 UTC, tdykstra commented on docs/core/tools/dotnet-nuget-why.md
> +**This article applies to:** ✔️ .NET Core 3.1 SDK and later versions
Which preview is this in? We will want to make sure it doesn't get merged before it's available, and this applies-to text should be updated to .NET 7 Preview SDK.

2022-08-05 00:51 UTC, tdykstra commented on docs/core/tools/dotnet-nuget-why.md
> +- Print dependency graph of `packageA`, the package has dependencies in multiple projects so all dependencies are printed by default:
```suggestion
- Print dependency graph of `packageA`. The package has dependencies in multiple projects so all dependencies are printed by default:
```

But the command only looks at one project per the arguments section, so it's not clear what this means by referring to multiple projects.

2022-08-18 19:12 UTC, pkulikov commented on docs/core/tools/dotnet-nuget-why.md
> +The `dotnet list package` command provides a way to print out the dependency graph for a package to allow users to understand the nature of top-level packages and their transitive dependencies. This
```suggestion
The `dotnet nuget why` command provides a way to print out the dependency graph for a package to allow users to understand the nature of top-level packages and their transitive dependencies. This command is dependent on the `project.assets.json` file being present in the project. The following example shows the output of the `dotnet nuget why` command for `packageA` which has dependencies in `projectNameA` and `projectNameB`:
```

2022-09-07 15:40 UTC, tdykstra requested changes
Waiting on responses to earlier review comments.

2022-11-09 15:54 UTC, BillWagner commented
Hi @pragnya17 

Can you address the comments on this PR? Once you do that, we can merge it.

2022-12-01 17:41 UTC, tdykstra commented
Closing due to no response from PR author.

2022-12-01 17:41 UTC, closed without merging