Clarification OpenWrite does not support reading.
dotnet/docs pull request #3067
Opened 2017-09-06 14:14 UTC by samrueby

It was not perfectly clear that OpenWrite does not support reading and writing, but strictly only writing.

# Title

On the title describe
Added clarification to not use OpenWrite for both reading and writing.

## Summary

"System.NotSupportedException: Stream does not support reading. " is thrown when you attempt to read the stream after using this overload.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-09-06 14:14 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-06 16:17 UTC, rpetrusha requested changes
Thanks, @samrueby, for adding this additional detail and enriching the documentation. However, the link to the FileStream class is incorrect. Would you mind changing it? If you prefer, we can also change it for you.

2017-09-06 16:17 UTC, rpetrusha commented on xml/System.IO/File.xml
> + The returned <xref:System.IO.File.FileStream> does not support reading. To open a file for both reading and writing, use <xref:System.IO.File.Open>.
This should be System.IO.FileStream, not System.IO.File.FileStream.

2017-09-06 17:41 UTC, samrueby commented
Thank you! Should be fixed now.

2017-09-06 21:37 UTC, rpetrusha commented
I apologize, @samrueby; I missed the fact that the second link also was broken. Because the method is an overload, the xref has to be System.IO.File.Open%2A instead of System.IO.File.Open.

2017-09-07 14:09 UTC, samrueby commented
Okay, all set.

2017-09-07 16:39 UTC, rpetrusha approved these changes

2017-09-07 16:40 UTC, rpetrusha commented
Thanks for making the additional changes, and thanks again for improving the documentation, @samrueby. We'll merge your PR now. It should go live by tomorrow.

2017-09-07 16:40 UTC, merged

2017-09-07 17:06 UTC, samrueby commented
Thank you!