Unit testing with core 2 0
dotnet/docs pull request #3076
Opened 2017-09-06 23:43 UTC by BillWagner

Fixes #2713

Update C# unit testing with xUnit and MStest.
Add topics for VB and F# with both xUnit and MSTest.

2017-09-07 19:02 UTC, rpetrusha requested changes
Looks good, @BillWagner, despite a large number of comments.

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-fsharp-with-mstest.md
> +Before building the library or the tests, execute [`dotnet sln add .\PrimeService.Tests\PrimeService.Tests.csproj`](../tools/dotnet-restore.md) in the *unit-testing-using-dotnet-test* directory.
.csproj --> .fsproj

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-fsharp-with-dotnet-test.md
> +The `[<Fact>]` attribute denotes a method as a single test. From the *unit-testing-with-fsharp*, execute [`dotnet test`](../tools/dotnet-test.md) to build the tests and the class library and then run
"denotes a method as a single test" is unclear -- I find "single test" misleading. The attributes denotes a particular method as a test method that's to be run by the test framework. Non-marked methods aren't run unless they're called from a test method. I'd change this to "denotes a test method that is be run by the test framework." This applies as well to the `[TestMethod]` attribute

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-fsharp-with-mstest.md
> +title: Unit testing F# libraries in .NET Core using dotnet test and xUnit
Not xUnit, but MSTest

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-fsharp-with-mstest.md
> +description: Learn unit test concepts for F# in .NET Core through an interactive experience building a sample solution step-by-step using dotnet test and xUnit.
xUnit --> MSTest

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-fsharp-with-mstest.md
> +# Unit testing F# libraries in .NET Core using dotnet test and xUnit
xUnit --> MSTest

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-fsharp-with-mstest.md
> +Make the *MathService.Tests* directory the current directory and create a new project using [`dotnet new mstest -lang F#`](../tools/dotnet-new.md). This creates a test project that uses xUnit as the
xUnit --> MSTest
test library, or test framework?

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-dotnet-test.md
> +title: Unit testing in .NET Core using dotnet test and xUnit
Title should also include VB

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-dotnet-test.md
> +description: Learn unit test concepts in .NET Core through an interactive experience building a sample visual basic solution step-by-step using dotnet test and xUnit.
visual basic --> Visual Basic

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-dotnet-test.md
> +Imports System
You don't need to import System; it's imported automatically by the compiler.

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-mstest.md
> +title: Unit testing in .NET Core using dotnet test and MSTes
MSTes --> MSTest
Add language to the title

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-mstest.md
> +description: Learn unit test concepts in .NET Core through an interactive experience building a sample visual basic solution step-by-step using MSTest.
visual basic --> Visual Basic

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-mstest.md
> +The test project requires other packages to create and run unit tests. `dotnet new` in the previous step added xUnit and the xUnit runner. Now, add the `PrimeService` class library as another depende
not xUnit and xUnit runner.

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-visual-basic-with-mstest.md
> +Now that you've made one test pass, it's time to write more. There are a few other simple cases for prime numbers: 0, -1. You could add those cases as new tests with the `<TestMethod>` attribute, but
`<<DataTestMethod>>` --> `<DataTestMethod>`

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-with-dotnet-test.md
>  description: Learn unit test concepts in .NET Core through an interactive experience building a sample solution step-by-step using dotnet test and xUnit.
Title and description need to mention C#

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-with-mstest.md
>  ### Creating the source project
The title and description should mention C#, and the description can be expanded

2017-09-07 19:02 UTC, rpetrusha commented on docs/core/testing/unit-testing-with-mstest.md
> +Make the *PrimeService.Tests* directory the current directory and create a new project using [`dotnet new mstest`](../tools/dotnet-new.md). The Botnet new command creates a test project that uses MSt
Botnet --> dotnet

2017-09-07 19:02 UTC, rpetrusha commented on samples/core/getting-started/unit-testing-vb-dotnet-test/PrimeService/PrimeService.vb
> +Imports System
No need to import System

2017-09-07 19:02 UTC, rpetrusha commented on samples/core/getting-started/unit-testing-vb-mstest/PrimeService/PrimeService.vb
> +Imports System
No need to import System

2017-09-08 18:08 UTC, BillWagner commented on docs/core/testing/index.md
> +* If you are using Visual Studio, checkout [Live Unit Testing in .NET Core]()
Thanks for spotting that I'd forgotten the link. (Yes, that's where I intended to go. I ran the samples, and the experience is the same for .NET Framework and .NET Core testing).

2017-09-08 19:10 UTC, BillWagner commented on docs/core/testing/unit-testing-fsharp-with-dotnet-test.md
> +Before building the library or the tests, execute [`dotnet sln add .\PrimeService.Tests\PrimeService.Tests.csproj`](../tools/dotnet-restore.md) in the *unit-testing-using-dotnet-test* directory.
I was also linking to the wrong `dotnet` command.

2017-09-08 19:31 UTC, BillWagner commented on docs/core/testing/unit-testing-fsharp-with-dotnet-test.md
> +The `[<Fact>]` attribute denotes a method as a single test. From the *unit-testing-with-fsharp*, execute [`dotnet test`](../tools/dotnet-test.md) to build the tests and the class library and then run
I checked the others for similar errors.

2017-09-08 19:32 UTC, mairaw commented on docs/core/testing/index.md
> +You can read about those combinations in these walk-througs:
typo: walk-througs. Also I think we don't hyphen that. So it should be walkthroughs.

2017-09-08 19:50 UTC, mairaw commented on docs/core/testing/index.md
> +.NET Core 2.0 supports [.NET Standard 2.0](../../standard/net-standard.md). The libraries used to demonstrate unit testing in this section rely on .NET Standard and will work in other project types a
will work -> work

2017-09-08 19:50 UTC, mairaw commented on docs/core/testing/index.md
>  Having a suite of automated tests is one of the best ways to ensure a software application does what its authors intended it to do. There are many different kinds of tests for software applications,
Also the sentence that starts with "At the lowest level" seems to be missing a subject

will want -> want

2017-09-08 19:50 UTC, mairaw commented on docs/core/testing/index.md
> +You can choose different languages for your class libraries and your unit test libraries. You can learn how by mixing and matching the walk-throughs referenced above.
walk-throughs referenced above -> walkthroughs previously referenced

2017-09-08 19:50 UTC, mairaw commented on docs/core/testing/index.md
> +* For a additional information and examples on how to use selective unit test filtering, see [Running selective unit tests](selective-unit-tests.md).
For a additional -> For additional

2017-09-12 14:19 UTC, BillWagner commented
I just pushed all the changes addressing feedback. Ready for another go @rpetrusha

2017-09-12 21:27 UTC, rpetrusha commented
This looks good, @BillWagner. The only unaddressed comment is one from Maira, from test/index.md:  
walk-throughs referenced above -> walkthroughs previously referenced (on line 44)
With that change, this is ready to merge.

2017-09-12 21:27 UTC, rpetrusha approved these changes

2017-09-12 21:53 UTC, mairaw commented on docs/core/testing/index.md
> +* If you are using Visual Studio, just see [Live Unit Testing in .NET Core](~/visualstudio/test/live-unit-testing)
to cross link to the visualstudio docs, you need to remove the ~.  

`[Live Unit Testing in .NET Core](/visualstudio/test/live-unit-testing)`

2017-09-12 21:58 UTC, mairaw commented on docs/core/testing/index.md
> +Beginning with .NET Core 2.0, there are unit test project templates for VB.NET and F# as well as C#.
one little nit thing: I think throughout the docs we usually refer to VB as Visual Basic. Should we be consistent on that?

2017-09-13 00:45 UTC, merged