Explaining how to disable all globs
dotnet/docs pull request #3115
Opened 2017-09-11 21:41 UTC by adrianvmsft

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Providing more information on how to disable the different types of implicit globs and explaining how to disable all globs.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-09-11 21:41 UTC, dnfclas commented
@adrianvmsft,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-11 23:56 UTC, mairaw requested changes
Thanks @adrianvmsft. LGTM but left a few comments re. style guide rules.

2017-09-11 23:56 UTC, mairaw commented on docs/core/tools/csproj.md
> +`<EnableDefaultCompileItems>` only disables `Compile` globs but doesn't affect other globs, like the implicit `None` glob which also applies to \*.cs items. Because of that, `Solution Explorer` will
missing comma before which

UI items such as Solution Explorer need to be formated in bold

2017-09-11 23:56 UTC, mairaw commented on docs/core/tools/csproj.md
> +If you would like to disable **all implicit globs**, you can set the `<EnableDefaultItems>` to `false`:
If you would like to disable -> To disable

you can set the `<EnableDefaultItems>` to `false` -> set the `<EnableDefaultItems>` property to `false` as in the following example:

2017-09-12 00:00 UTC, mairaw commented on docs/core/tools/csproj.md
> +`<EnableDefaultCompileItems>` only disables `Compile` globs but doesn't affect other globs, like the implicit `None` glob which also applies to \*.cs items. Because of that, `Solution Explorer` will
also please change ms.date value on line 7 to today's date

2017-09-22 07:29 UTC, mairaw commented
Thanks @adrianvmsft for making the fixes. @dsplaisted can you take a look at this PR?

/cc @KathleenDollard

2017-09-22 16:10 UTC, livarcocc approved these changes

2017-09-22 16:28 UTC, mairaw approved these changes

2017-09-22 16:29 UTC, dnfclas commented
@adrianvmsft,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-22 23:17 UTC, dnfclas commented
@adrianvmsft,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-22 23:17 UTC, dnfclas commented
@adrianvmsft,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-22 23:17 UTC, mairaw commented
Builds were stuck. Retrying again.

2017-09-25 04:02 UTC, dsplaisted approved these changes
This change is good.

Looking at the rest of the page, I think it could use some additional changes.  I don't understand what the recommendation for globbing is trying to say, and I don't think the distinction between exclude and remove expressions for the globs is helpful.

2017-09-25 05:12 UTC, mairaw commented
I'll merge this and we can discuss improvements to the CLI docs when we meet @dsplaisted.

2017-09-25 05:16 UTC, merged