addressed customer questions/comments
dotnet/docs pull request #3119
Opened 2017-09-12 01:41 UTC by mairaw

addressing LiveFyre comments/questions for the following two related WCF topics:
1 - https://docs.microsoft.com/en-us/dotnet/framework/wcf/find-private-key-tool-findprivatekey-exe
- see... what??? It's blank!

2 - https://docs.microsoft.com/en-us/dotnet/framework/wcf/samples/findprivatekey
- Where is the download link for the "sample code"?
- Repeating Meng_Wang's question - where is the sample code?
- For those of you wandering... you can download the sample code here: https://www.microsoft.com/en-us/download/details.aspx?id=21459

For the service account names, I've changed the references to Windows XP and Windows Server 2003 to generic names. @Rick-Anderson @tdykstra do you know if they are still correct? See the part about ASPNET and NETWORK SERVICE accounts.

2017-09-12 16:27 UTC, tdykstra commented
Rick may know but is on vacation.  If you don't get an answer from him, I'd ask [@]shirhatti

2017-09-12 16:28 UTC, tdykstra commented on docs/framework/wcf/samples/findprivatekey.md
> +X.509 certificates are installed by an Administrator or any user in the machine. However, the certificate may be accessed by a service running under a different account. For example, the ASPNET on Wi
Missing "account" after ASPNET

2017-09-22 08:23 UTC, zhenlan commented
> For the service account names, I've changed the references to Windows XP and Windows Server 2003 to generic names.

This change is not accurate. For IIS, the default account is NETWORK SERVICE on IIS 7 or earlier and is Application Pool Identity on IIS 7.5 or later. This is same for client and server skus. You can find more information [here](https://docs.microsoft.com/en-us/iis/manage/configuring-security/application-pool-identities).

Other than this, all other changes look good to me.

2017-09-27 15:14 UTC, BillWagner requested changes
Overall, this looks great.

Once you address the comments from @zhenlan we can merge this.

2017-12-05 01:35 UTC, mairaw commented
@BillWagner @zhenlan sorry for the delay. I've addressed the comments. Thanks!

2017-12-05 01:41 UTC, zhenlan approved these changes
LGTM. Thanks!

2017-12-05 01:45 UTC, BillWagner approved these changes

2017-12-05 01:45 UTC, BillWagner commented
Looks great. Once the build finishes, let's merge it.

2017-12-11 16:05 UTC, merged