Location of (0,0)
dotnet/docs pull request #3126
Opened 2017-09-12 10:45 UTC by michal-ciechan

Specifying (0,0) is at the top left

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-09-12 10:45 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-12 17:44 UTC, mairaw requested changes
I like the change @michal-ciechan! I just have a suggestion to add a noun after the top left adjective,

2017-09-12 17:44 UTC, mairaw commented on docs/framework/wpf/graphics-multimedia/path-markup-syntax.md
> + Describes the x- and y-coordinates of a point where (0,0) is the top left.
top left -> top-left corner?

2017-09-13 12:23 UTC, michal-ciechan commented
@mairaw Thanks for the suggestion, definitely makes sense! Have edited commit.

2017-09-13 18:01 UTC, mairaw approved these changes
Thank you @michal-ciechan! Your fix will show up in the live site probably later today or tomorrow.

2017-09-13 18:01 UTC, merged