Updating condition(s) under which the method throws
dotnet/docs pull request #3152
Opened 2017-09-15 20:04 UTC by stevewhims

# Updating the condition(s) under which Socket.BeginConnect throws

## Summary

There are four overloads; each behaves the same way with respect to this particular exception.

2017-09-15 20:04 UTC, dnfclas commented
@stevewhims,
Thanks for having already signed the Contribution License Agreement. Your agreement was validated by .NET Foundation. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-16 03:42 UTC, davidsh commented
cc: @caesar1995 

The System.InvalidOperationException can be thrown from BeginConnect for 2 possible reasons:

1. The socket is in a Listening state (This is already in the documentation and this PR seems to correct some grammar describing that.

and 

2. (Which is missing from the documentation and for which this bug was opened about). Another asynchronous operation is still in progress on the Socket, i.e. a prior unfinished BeginConnect() call

2017-09-16 03:42 UTC, davidsh requested changes
Please revise doc about InvalidOperationException.

2017-09-18 17:47 UTC, davidsh approved these changes
After offline discussion, this change is LGTM.

2017-09-18 17:48 UTC, caesar-chen approved these changes

2017-09-18 17:56 UTC, mairaw approved these changes
LGTM

2017-09-21 08:32 UTC, merged