Update starting1.cs
dotnet/docs pull request #3154
Opened 2017-09-15 23:40 UTC by gernotpokorny

# Controlling spacing example

The current inplementation of the "Controlling spacing"-example is bad practice.
 
Have a look at this video, it explains why it is bad practice:
https://www.youtube.com/watch?v=4lFAs6FYTXg

## Conclusion: 

In for-loops always use StringBuilder instead of string-concatenation. Strings are immutable and as a result you would create many unnecessary objects on the heap by using string-concatenation instead of StringBuilder.

2017-09-15 23:40 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-19 18:49 UTC, rpetrusha requested changes
Thanks for submitting this PR and enforcing best practices in the example, @gernotpokorny. The code for the example appears in Visual Basic and C++ as well as C#, though.  Could you modify the Visual Basic and C++ code as well? If not, we can do it for you.

2017-09-19 18:49 UTC, rpetrusha commented on samples/snippets/csharp/VS_Snippets_CLR_System/system.String.Format/cs/starting1.cs
> +       StringBuilder myStringBuilder = new StringBuilder();
this is a nit, but it would be good to name the variable something other than my(whatever). Perhaps simply `sb`, or `strBuilder`?

2017-09-19 18:49 UTC, rpetrusha commented on samples/snippets/csharp/VS_Snippets_CLR_System/system.String.Format/cs/starting1.cs
> -       String s = String.Format("{0,6} {1,15}\n\n", "Year", "Population");
a `using System.Text;` statement also should be added after the `using System;` statement.

2017-09-19 18:49 UTC, rpetrusha commented on samples/snippets/csharp/VS_Snippets_CLR_System/system.String.Format/cs/starting1.cs
> +       myStringBuilder.Append(String.Format("{0,6} {1,15}\n\n", "Year", "Population"));
In addition to the C# code, there is also Visual Basic and C++/CLI code that needs to have parallel changes. Can you make those, @gernotpokorny? The relevant files are: 
**For VB**, https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.String.Format/vb/starting1.vb.

The code changes:
   ```
   Dim sb As New StringBuilder()
   sb.Append($"{"Year",6} {"Population",15}{vbCrLf}{vbCrLf}")
   For index = 0 To years.Length - 1
      sb.Append($"{years(index),6} {population(index),15:N0}{vbCrLf}")
   Next
   ``` 
Also, there should be an `Imports System.Text` statement at the beginning of the file, and the variable name in the `Console.WriteLine` method call should be changed,

**For C++**, https://github.com/dotnet/docs/blob/master/samples/snippets/cpp/VS_Snippets_CLR_System/system.String.Format/cpp/starting1.cpp

The code changes: 
```
StringBuilder^ sb = gcnew StringBuilder();
for(int index = 0; index < years->Length; index++)
          sb += String::Format("{0,6} {1,15:N0}\n",
                              years[index], population[index]);

Also, there should be a `using namespace System::Text` statement at the beginning of the file, and the variable name in the `Console::WriteLine` method call should be changed,

2017-09-20 23:36 UTC, gernotpokorny commented
Hello,

I'm currently very busy. I hope that I'll have time at the weekend or at
the beginning of the next week. I have no VB-skills at the moment, but I'll
look if I can do it in VB too.

Ron Petrusha <notifications@github.com> schrieb am Di., 19. Sep. 2017 um
20:49 Uhr:

> *@rpetrusha* requested changes on this pull request.
>
> Thanks for submitting this PR and enforcing best practices in the example,
> @gernotpokorny <https://github.com/gernotpokorny>. The code for the
> example appears in Visual Basic and C++ as well as C#, though. Could you
> modify the Visual Basic and C++ code as well? If not, we can do it for you.
> ------------------------------
>
> In
> samples/snippets/csharp/VS_Snippets_CLR_System/system.String.Format/cs/starting1.cs
> <https://github.com/dotnet/docs/pull/3154#discussion_r139776846>:
>
> > @@ -41,18 +41,18 @@ private static void Snippet33()
>         // <Snippet33>
>         int[] years = { 2013, 2014, 2015 };
>         int[] population = { 1025632, 1105967, 1148203 };
> -       String s = String.Format("{0,6} {1,15}\n\n", "Year", "Population");
> -       for(int index = 0; index < years.Length; index++)
> -          s += String.Format("{0,6} {1,15:N0}\n",
> -                             years[index], population[index]);
> +       StringBuilder myStringBuilder = new StringBuilder();
>
> this is a nit, but it would be good to name the variable something other
> than my(whatever). Perhaps simply sb, or strBuilder?
> ------------------------------
>
> In
> samples/snippets/csharp/VS_Snippets_CLR_System/system.String.Format/cs/starting1.cs
> <https://github.com/dotnet/docs/pull/3154#discussion_r139778860>:
>
> > @@ -41,18 +41,18 @@ private static void Snippet33()
>         // <Snippet33>
>         int[] years = { 2013, 2014, 2015 };
>         int[] population = { 1025632, 1105967, 1148203 };
> -       String s = String.Format("{0,6} {1,15}\n\n", "Year", "Population");
>
> a using System.Text; statement also should be added after the using
> System; statement.
> ------------------------------
>
> In
> samples/snippets/csharp/VS_Snippets_CLR_System/system.String.Format/cs/starting1.cs
> <https://github.com/dotnet/docs/pull/3154#discussion_r139782348>:
>
> > @@ -41,18 +41,18 @@ private static void Snippet33()
>         // <Snippet33>
>         int[] years = { 2013, 2014, 2015 };
>         int[] population = { 1025632, 1105967, 1148203 };
> -       String s = String.Format("{0,6} {1,15}\n\n", "Year", "Population");
> -       for(int index = 0; index < years.Length; index++)
> -          s += String.Format("{0,6} {1,15:N0}\n",
> -                             years[index], population[index]);
> +       StringBuilder myStringBuilder = new StringBuilder();
> +       myStringBuilder.Append(String.Format("{0,6} {1,15}\n\n", "Year", "Population"));
>
> In addition to the C# code, there is also Visual Basic and C++/CLI code
> that needs to have parallel changes. Can you make those, @gernotpokorny
> <https://github.com/gernotpokorny>? The relevant files are:
> *For VB*,
> https://github.com/dotnet/docs/blob/master/samples/snippets/visualbasic/VS_Snippets_CLR_System/system.String.Format/vb/starting1.vb
> .
>
> The code changes:
>
> Dim sb As New StringBuilder()
> sb.Append($"{"Year",6} {"Population",15}{vbCrLf}{vbCrLf}")
> For index = 0 To years.Length - 1
>    sb.Append($"{years(index),6} {population(index),15:N0}{vbCrLf}")
> Next
>
> Also, there should be an Imports System.Text statement at the beginning
> of the file, and the variable name in the Console.WriteLine method call
> should be changed,
>
> *For C++*,
> https://github.com/dotnet/docs/blob/master/samples/snippets/cpp/VS_Snippets_CLR_System/system.String.Format/cpp/starting1.cpp
>
> The code changes:
>
> StringBuilder^ sb = gcnew StringBuilder();
> for(int index = 0; index < years->Length; index++)
>           sb += String::Format("{0,6} {1,15:N0}\n",
>                               years[index], population[index]);
>
> Also, there should be a `using namespace System::Text` statement at the beginning of the file, and the variable name in the `Console::WriteLine` method call should be changed,
>
>
>
> —
> You are receiving this because you were mentioned.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/docs/pull/3154#pullrequestreview-63757115>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ATiEqeA2NAwfGZrwW804f7CmCXAPg5lDks5skAzAgaJpZM4PZny9>
> .
>

2017-09-21 00:20 UTC, rpetrusha commented
If you'd like, @gernotpokorny, if you can add the `using` statement to the C# example and rename the variable, I can merge your PR and make the corresponding changes to the C++ and VB examples.

2017-09-25 15:55 UTC, rpetrusha commented
Thanks for making the additional change, @gernotpokorny. We'll merge your PR now. Changes should appear on docs.microsoft.com within the next day or two.

2017-09-25 15:55 UTC, rpetrusha approved these changes

2017-09-25 15:55 UTC, merged