Code cleanup
dotnet/docs pull request #3160
Opened 2017-09-16 04:06 UTC by paulroho

## Summary

- Removed useless comments
- Fixed indentation for better readability
- Fixed annoying `temp1` variable name to adhere to VB's naming convention

2017-09-16 04:06 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-09-27 21:31 UTC, rpetrusha commented
Thanks for submitting this PR to parallel PR #3158, @paulroho. However, some of your proposed changes are undesirable:
- The comments should not be removed. Although they're semi-obvious, they're also important for indicating in code exactly what must be done to implement a custom format string.
- The single-line `If` statements should not be changed to `If`...`End If` statements. The single-line `If` statement is commonly used in Visual Basic. It both enhances readability and creates compact code. There are thousands of occurrences of it in our code base.  
Changing the variable name from `temp1` to `temp` is acceptable. However, our variable name convention uses camel casing. So instead of `Temp`, the variable should be named `temp`. Would you mind making that change? Once it's made, we can merge your PR?

//cc @BillWagner

2017-09-27 21:34 UTC, rpetrusha requested changes
My earlier comment indicates the requested changes, @paulroho.

2017-10-05 21:13 UTC, mairaw commented
Build is stuck.

2017-10-05 21:13 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-10-11 21:22 UTC, rpetrusha approved these changes

2017-10-11 21:22 UTC, merged