[WIP] Onboard containerized docker apps
dotnet/docs pull request #3206
Opened 2017-09-22 17:50 UTC by BillWagner

Load the second eBook into Docs.

2017-09-25 19:36 UTC, BillWagner commented
closing and reopening to restart the build

2017-09-26 14:08 UTC, BillWagner commented
closing and reopening again.

2017-09-26 15:33 UTC, BillWagner commented
Removed the WIP label.  This is ready for review.  

cc @JRAlexander @mairaw

2017-09-26 18:00 UTC, JRAlexander commented
I will review this afternoon

2017-10-04 18:27 UTC, BillWagner commented
closing and reopening to start a new build.

2017-10-04 21:19 UTC, JRAlexander requested changes
Overall, great job @BillWagner! Just a couple of very small things.

2017-10-04 21:19 UTC, JRAlexander commented on docs/standard/architecture-containerized-liefecycle/docker-terminology.md
> +This section lists terms and definitions with which you should become familiar with before delving deeper into Docker (for further definitions, see the extensive [glossary](https://docs.docker.com/v1
This is an older url for the  glossary, the current one is here: https://docs.docker.com/glossary/, also it's listed twice with an extra parentheses at the end.

2017-10-04 21:19 UTC, JRAlexander commented on docs/standard/architecture-containerized-liefecycle/docker-terminology.md
> +    > docker-trusted-registry/overview/](https://docs.docker.com/docker-trusted-registry/overview/).
This URL is broken with a slash and linebreak.

2017-10-04 22:53 UTC, BillWagner commented
Thanks for the review @JRAlexander I've addressed all the feedback.

2017-10-05 17:42 UTC, JRAlexander approved these changes

2017-10-05 17:44 UTC, merged