.NET 7 is available in Fedora
dotnet/docs pull request #33551
Opened 2023-01-16 15:10 UTC by omajid

## Summary

.NET 7 packages are (almost) available for Fedora, 36 and later.

2023-01-16 15:11 UTC, omajid commented
The packages are still undergoing testing, and should become available to all Fedora users by default around next week. We should probably hold off on merging this for a few days.

2023-01-17 16:10 UTC, adegeo requested changes
Looks great 👍 Just two minor fixes. Just ping me when it's ready to merge.

2023-01-17 16:10 UTC, adegeo commented on docs/core/install/linux-fedora.md
> +### Errors related to missing `fxr`, `libhostfxr.so`, `FrameworkList.xml` or `/usr/share/dotnet`
The Microsoft docs style uses an oxford comma.
```suggestion
### Errors related to missing `fxr`, `libhostfxr.so`, `FrameworkList.xml`, or `/usr/share/dotnet`
```

2023-01-17 16:10 UTC, adegeo commented on docs/core/install/remove-runtime-sdk-versions.md
> +- [yum(8)](https://linux.die.net/man/8/yum) is used on Fedora, CentOS, Oracle Linux and RHEL.
And again
```suggestion
- [yum(8)](https://linux.die.net/man/8/yum) is used on Fedora, CentOS, Oracle Linux, and RHEL.
```

2023-01-23 14:55 UTC, omajid commented
@adegeo this is ready to merge from my point of view. .NET 7 is now available to Fedora users by default.

2023-02-10 16:18 UTC, omajid commented
Could someone please review/merge this?

2023-02-13 20:08 UTC, adegeo approved these changes
Sorry for the delay!

2023-02-13 20:08 UTC, merged

2023-02-13 21:07 UTC, omajid commented
Thanks!