Modern Web Apps eBook - Addressing feedback
dotnet/docs pull request #34183
Opened 2023-02-20 22:43 UTC by ardalis

## Summary

Addressing feedback and updating for Program.cs

Fixes #31981

2023-02-20 22:43 UTC, ardalis commented
@IEvangelist

2023-02-21 15:45 UTC, IEvangelist requested changes
A few nits, otherwise looks good.

2023-02-21 15:45 UTC, IEvangelist commented on docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md
> +In your ASP.NET Core application, you'll typically configure EF Core in `Program.cs` with your application's other dependencies. EF Core uses a `DbContextOptionsBuilder`, which supports several helpf
```suggestion
In your ASP.NET Core application, you'll typically configure EF Core in _Program.cs_ with your application's other dependencies. EF Core uses a `DbContextOptionsBuilder`, which supports several helpful extension methods to streamline its configuration. To configure CatalogContext to use a SQL Server database with a connection string defined in Configuration, you would add the following code:
```

2023-02-21 15:45 UTC, IEvangelist commented on docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md
> +builder.Services.AddDbContext<CatalogContext>(options => options.UseSqlServer (builder.Configuration.GetConnectionString("DefaultConnection")));
```suggestion
builder.Services.AddDbContext<CatalogContext>(
    options => options.UseSqlServer(
        builder.Configuration.GetConnectionString("DefaultConnection")));
```

2023-02-21 15:45 UTC, IEvangelist commented on docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md
> +It's a good idea to test your application while examining the actual database queries it makes. Under certain circumstances, EF Core may make many more queries or a more expensive query than is optim
```suggestion
It's a good idea to test your application while examining the actual database queries it makes. Under certain circumstances, EF Core may make many more queries or a more expensive query than is optimal for the application. One such problem is known as a [Cartesian Explosion](/ef/core/querying/single-split-queries#cartesian-explosion). The EF Core team makes available the [AsSplitQuery method](/ef/core/querying/single-split-queries#split-queries) as one of several ways to tune runtime behavior.
```

2023-02-21 15:45 UTC, IEvangelist commented on docs/architecture/modern-web-apps-azure/work-with-data-in-asp-net-core-apps.md
> +To configure the application to use the cached version of the service, but still allow the service to get the instance of CatalogService it needs in its constructor, you would add the following lines
```suggestion
To configure the application to use the cached version of the service, but still allow the service to get the instance of CatalogService it needs in its constructor, you would add the following lines in _Program.cs_:
```

2023-02-21 15:49 UTC, IEvangelist approved these changes

2023-02-21 15:56 UTC, merged

2023-02-21 16:16 UTC, ardalis commented
Looks good, thanks!