Standard Folder FWLink List
dotnet/docs pull request #3429
Opened 2017-10-17 00:38 UTC by xaviex

# FWLink Standard Folder fix

## Summary

FWLink Standard folder update to clarify links in the /docs/standard folder

Fixes #3425

## Suggested Reviewers

@mairaw

2017-10-17 00:38 UTC, dnfclas commented
@xaviex,
Thanks for having already signed the Contribution License Agreement. Your agreement has not been validated yet. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-10-17 01:06 UTC, mairaw requested changes
Looks great @xaviex! Really appreciate you tackling this. Again, please let me know if you'd like me to address the changes I'm requesting.

2017-10-17 01:06 UTC, mairaw commented on docs/standard/io/index.md
> +File and stream I/O (input/output) refers to the transfer of data either to or from a storage medium. In the .NET Framework, the [System.IO](http://msdn.microsoft.com/en-us/library/gg145019(v=VS.110)
Change this link to https://docs.microsoft.com/dotnet/api/?term=system.io&view=netframework-4.7.1

2017-10-17 01:06 UTC, mairaw commented on docs/standard/io/index.md
> + Isolated storage is not available for [!INCLUDE[win8_appname_long](../../../includes/win8-appname-long-md.md)] apps; instead, use application data classes in the [Windows.Storage](http://msdn.micros
remove en-us/ from the link

2017-10-17 01:06 UTC, mairaw commented on docs/standard/io/index.md
> +-   Isolated storage is not available; instead, use [application data](http://msdn.microsoft.com/en-us/library/windows/apps/hh464917.aspx).
remove en-us/ from the link

2017-10-17 01:06 UTC, mairaw commented on docs/standard/io/index.md
> + Default security policies prevent Internet or intranet applications from accessing files on the user’s computer. Therefore, do not use the I/O classes that require a path to a physical file when wri
remove en-us from the link

2017-10-17 01:06 UTC, mairaw commented on docs/standard/io/isolated-storage.md
> +>  Isolated storage is not available for [!INCLUDE[win8_appname_long](../../../includes/win8-appname-long-md.md)] apps. Instead, use the application data classes in the `Windows.Storage` namespaces i
remove en-us from the link

2017-10-17 01:06 UTC, mairaw commented on docs/standard/io/types-of-isolation.md
> +>  Isolated storage is not available for [!INCLUDE[win8_appname_long](../../../includes/win8-appname-long-md.md)] apps. Instead, use the application data classes in the `Windows.Storage` namespaces i
ditto

2017-10-17 13:50 UTC, xaviex commented on docs/standard/base-types/best-practices.md
> +>  For a more detailed discussion of the performance implications of using interpreted and compiled regular expressions, see [Optimizing Regular Expression Performance, Part II: Taking Charge of Back
It seems even the forward link goes to the incorrect location, would we like this to be changed to the proper location or no?

2017-10-17 19:04 UTC, mairaw commented on docs/standard/base-types/best-practices.md
> +-   Thoroughly test your regular expression using invalid and near-valid input as well as valid input. To generate input for a particular regular expression randomly, you can use [Rex](https://www.mi
a more cleaner url is https://www.microsoft.com/en-us/research/project/rex-regular-expression-exploration/

2017-10-17 19:04 UTC, mairaw commented on docs/standard/base-types/best-practices.md
> +>  For a more detailed discussion of the performance implications of using interpreted and compiled regular expressions, see [Optimizing Regular Expression Performance, Part II: Taking Charge of Back
yes, please change to https://blogs.msdn.microsoft.com/bclteam/2010/08/03/optimizing-regular-expression-performance-part-ii-taking-charge-of-backtracking-ron-petrusha/

2017-10-17 21:35 UTC, xaviex commented
@mairaw  I have cleaned up that odd-looking link, where there any other discrepancies?

2017-10-17 23:08 UTC, xaviex commented
It has come to my attention that this has actually removed more localization than was in the link replacements, is this ok?

2017-10-17 23:48 UTC, mairaw requested changes
Thanks for the fixes. The global changes to remove en-us from the links generated a new set of feedback @xaviex. In general, I'd recommend we solve one issue per PR. Let me know if you need help addressing the comments. Thanks again!

2017-10-17 23:48 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/monolithic-applications.md
> +You can deploy monolithic applications in Azure by using dedicated VMs for each instance. Using [Azure VM Scale Sets](https://azure.microsoft.com/documentation/services/virtual-machine-scale-sets/),
The scale sets link now goes here: https://docs.microsoft.com/azure/virtual-machine-scale-sets/ (and in the case of the e-books we keep the docs URL)

2017-10-17 23:48 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/docker-terminology.md
> +-   **Docker Community Edition (CE)** Development tools for Windows and macOS for building, running, and testing containers locally. Docker CE for Windows provides development environments for both L
let's update this link to https://www.microsoft.com/cloud-platform/server-virtualization

2017-10-17 23:48 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/what-is-docker.md
> +To run [Windows Containers](https://msdn.microsoft.com/virtualization/windowscontainers/about/about_overview), there are two types of runtimes:
let's update this link to https://docs.microsoft.com/virtualization/windowscontainers/about/index

2017-10-17 23:48 UTC, mairaw commented on docs/standard/cross-platform/cross-platform-development-with-the-portable-class-library.md
> +|Visual Studio 2012 Professional, Premium, or Ultimate|Yes. For phone support, install the [Windows Phone SDK 8.0](http://www.microsoft.com/click/services/Redirect2.ashx?CR_EAC=300063060).|
might be better to leave this one as FwLink

2017-10-17 23:48 UTC, mairaw commented on docs/standard/cross-platform/support-for-windows-store-apps-and-windows-runtime.md
> +|[Windows Runtime reference](https://docs.microsoft.com/uwp/api/)|The reference documentation for the [!INCLUDE[wrt](../../../includes/wrt-md.md)]. (In the Windows Dev Center.)|
link should be /uwp/api/

2017-10-17 23:48 UTC, mairaw commented on docs/standard/data/xml/xslt-extension-objects.md
> +>  The FullTrust permission set is required to call the <xref:System.Xml.Xsl.XsltArgumentList.AddExtensionObject%2A> method. For more information, see [Code Access Security](http://msdn.microsoft.com
please change the CAS link to ~/docs/framework/misc/code-access-security.md

2017-10-17 23:48 UTC, mairaw commented on docs/standard/data/xml/xslt-security-considerations.md
> + [Code Access Security](http://msdn.microsoft.com/23a20143-241d-4fe5-9d9f-3933fd594c03)
same here: please change the CAS link to ~/docs/framework/misc/code-access-security.md

2017-10-17 23:48 UTC, mairaw commented on docs/standard/design-guidelines/index.md
> + [Roadmap for the .NET Framework](http://msdn.microsoft.com/0b46b7c6-9163-4f99-8e58-0d1ee7da8c67)
please remove this link. This topic doesn't exist

2017-10-17 23:48 UTC, mairaw commented on docs/standard/garbage-collection/performance.md
> + You can use the [Windows Debugger (WinDbg)](https://msdn.microsoft.com/library/cc266321.aspx) to inspect objects on the managed heap.
please change the link to /windows-hardware/drivers/debugger/index

2017-10-17 23:48 UTC, mairaw commented on docs/standard/globalization-localization/best-practices-for-developing-world-ready-apps.md
> +    -   In the globalization section of a Web.config file. This file is external to the ASP.NET application. For more information, see [\<globalization> Element](http://msdn.microsoft.com/e2dffc8e-eb
change this link to https://msdn.microsoft.com/library/e2dffc8e-ebd2-439b-a2fd-e3ac5e620da7(v=vs.100)

2017-10-17 23:48 UTC, mairaw commented on docs/standard/globalization-localization/index.md
> + For additional information, see the [Go Global Developer Center](https://docs.microsoft.com/globalization/).
link should be /globalization

2017-10-17 23:48 UTC, mairaw commented on docs/standard/io/how-to-read-characters-from-a-string.md
> + [NIB: How to: Create a Directory Listing](http://msdn.microsoft.com/4d2772b1-b991-4532-a8a6-6ef733277e69)
remove this link

2017-10-17 23:48 UTC, mairaw commented on docs/standard/io/how-to-read-text-from-a-file.md
> + [NIB: How to: Create a Directory Listing](http://msdn.microsoft.com/4d2772b1-b991-4532-a8a6-6ef733277e69)
remove this link

2017-10-17 23:48 UTC, mairaw commented on docs/standard/io/index.md
> +File and stream I/O (input/output) refers to the transfer of data either to or from a storage medium. In the .NET Framework, the [System.IO](https://msdn.microsoft.com/library/gg145019(v=VS.110).aspx
I'd change this link to /api/?view=netframework-4.7.1&term=system.io

2017-10-17 23:48 UTC, mairaw commented on docs/standard/io/index.md
> + See [How to: Copy Directories](../../../docs/standard/io/how-to-copy-directories.md), [How to: Create a Directory Listing](http://msdn.microsoft.com/4d2772b1-b991-4532-a8a6-6ef733277e69), and [How t
remove this link

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/asynchronous-message-based-communication.md
> +-   Using full [Event Sourcing](https://msdn.microsoft.com/library/dn589792.aspx) pattern.
change this to https://docs.microsoft.com/azure/architecture/patterns/event-sourcing

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/asynchronous-message-based-communication.md
> +    [*https://msdn.microsoft.com/library/dn568103.aspx*](https://msdn.microsoft.com/library/dn568103.aspx)
change this to https://docs.microsoft.com/azure/architecture/patterns/cqrs

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/distributed-data-management.md
> +    [*https://msdn.microsoft.com/library/dn589782.aspx*](https://msdn.microsoft.com/library/dn589782.aspx)
change this to https://docs.microsoft.com/azure/architecture/patterns/materialized-view

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/architect-microservice-container-applications/distributed-data-management.md
> +    [*https://msdn.microsoft.com/library/dn589804.aspx*](https://msdn.microsoft.com/library/dn589804.aspx)
https://docs.microsoft.com/azure/architecture/patterns/compensating-transaction

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md
> +[Windows Containers](https://msdn.microsoft.com/virtualization/windowscontainers/about/about_overview) work with two types of runtimes:
change this to https://docs.microsoft.com/virtualization/windowscontainers/about/index

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/container-docker-introduction/docker-defined.md
> +The images for these containers are created and function the same way. They differ in how the container is created. For details, see [Hyper-V Containers](https://msdn.microsoft.com/virtualization/win
same here. change this to https://docs.microsoft.com/virtualization/windowscontainers/about/index

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/container-docker-introduction/docker-terminology.md
> +**Docker Community Edition (CE)**: Development tools for Windows and macOS for building, running, and testing containers locally. Docker CE for Windows provides development environments for both Linu
change Hyper-V link to https://www.microsoft.com/cloud-platform/server-virtualization

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/docker-application-development-process/docker-app-development-workflow.md
> +[Windows Containers](https://msdn.microsoft.com/virtualization/windowscontainers/about/about_overview) allow you to convert your existing Windows applications into Docker images and deploy them with
change this to https://docs.microsoft.com/virtualization/windowscontainers/about/index

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/enumeration-classes-over-enum-types.md
> +[Enumerations](https://msdn.microsoft.com/library/sbbt4032.aspx) (*enums* for short) are a thin language wrapper around an integral type. You might want to limit their use to when you are storing one
change this to https://docs.microsoft.com/dotnet/csharp/language-reference/keywords/enum

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/microservice-application-layer-implementation-web-api.md
> +// https://msdn.microsoft.com/library/bb383979.aspx
change this to https://docs.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/how-to-implement-a-lightweight-class-with-auto-implemented-properties

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/net-core-microservice-domain-model.md
> +    // https://msdn.microsoft.com/library/e78dcd75(v=vs.110).aspx
https://docs.microsoft.com/dotnet/api/system.collections.generic.list-1.asreadonly

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/seedwork-domain-model-base-classes-interfaces.md
> +The following code is an example of an Entity base class where you can place code that can be used the same way by any domain entity, such as the entity ID, [equality operators](https://msdn.microsof
Change this to https://docs.microsoft.com/cpp/cpp/equality-operators-equal-equal-and-exclpt-equal

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md
> +-   Using the full [Event Sourcing pattern](https://msdn.microsoft.com/library/dn589792.aspx).
change this to https://docs.microsoft.com/azure/architecture/patterns/event-sourcing

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/multi-container-microservice-net-applications/subscribe-events.md
> +    [*https://msdn.microsoft.com/library/ms978430.aspx\#bdadotnetasync2\_topic3c*](https://msdn.microsoft.com/library/ms978430.aspx%23bdadotnetasync2_topic3c)
@BillWagner this link doesn't seem to exist. delete?

2017-10-17 23:48 UTC, mairaw commented on docs/standard/microservices-architecture/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md
> +    [*https://msdn.microsoft.com/library/hh694602.aspx*](https://msdn.microsoft.com/library/hh694602.aspx)
change this to https://docs.microsoft.com/visualstudio/test/unit-test-basics

2017-10-17 23:48 UTC, mairaw commented on docs/standard/parallel-programming/how-to-speed-up-small-loop-bodies.md
> +When a <xref:System.Threading.Tasks.Parallel.For%2A?displayProperty=nameWithType> loop has a small body, it might perform more slowly than the equivalent sequential loop, such as the [for](~/docs/csh
change For link to ~/docs/visual-basic/language-reference/statements/for-each-next-statement.md

2017-10-17 23:48 UTC, mairaw commented on docs/standard/threading/threads-and-threading.md
> + Software that requires user interaction must react to the user's activities as rapidly as possible to provide a rich user experience. At the same time, however, it must do the calculations necessary
nit: there's a missing space before the link if you'd like to fix that

2017-10-18 01:24 UTC, xaviex commented
the removal of en-us was actually accidental on my part, I can re do it only changing the links that used to be fwlinks?

2017-10-18 01:26 UTC, xaviex commented
@mariaw Would you like me to create a new pull request with the basic changes along with what you have commented on here?

2017-10-19 02:29 UTC, mairaw commented
No need to open a new PR. We could probably just pull out the commit you made that change from this PR. I'll do that.

2017-10-19 21:58 UTC, xaviex commented
@mairaw  Was that change made I can not tell?

2017-10-20 07:57 UTC, mairaw commented
I've removed that commit now @xaviex.

2017-11-06 21:43 UTC, mairaw commented
@xaviex do you want to take care of the remainder comments or do you want me to address them? Sorry this PR has been lingering here but I was out for the past couple of weeks.

2017-11-07 22:26 UTC, xaviex commented
@mairaw Ive got this, should be pushing it in a day or two

2017-11-09 00:56 UTC, mairaw commented
Thank you @xaviex!

2017-11-20 21:43 UTC, BillWagner commented
@xaviex Are you still planning to make those final changes? If not, we'll address them and merge your PR.

Thanks again for contributing.

2017-11-20 22:13 UTC, xaviex commented
Im still planning on it, i just had something come up in the last weeks so
the code has lain dormant, i will be able to get it up soon

On Mon, Nov 20, 2017 at 4:43 PM Bill Wagner <notifications@github.com>
wrote:

> @xaviex <https://github.com/xaviex> Are you still planning to make those
> final changes? If not, we'll address them and merge your PR.
>
> Thanks again for contributing.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/dotnet/docs/pull/3429#issuecomment-345841432>, or mute
> the thread
> <https://github.com/notifications/unsubscribe-auth/ABVYXnF7NvoRNPuGLj2gfZQe5Y72PR6kks5s4fJygaJpZM4P7bIl>
> .
>

2017-12-02 01:31 UTC, xaviex commented
@mairaw  Hey my apologies, it doesn't look like I'm going to be able to get to this within the next week or so, work got very hectic recently, thanks for all the help

2017-12-02 02:55 UTC, mairaw commented
No worries @xaviex. I'll see what the remaining comments were and finish this PR. Thanks a bunch!

2018-01-09 00:26 UTC, mairaw approved these changes

2018-01-09 00:26 UTC, merged