Update Form1.cs
dotnet/docs pull request #3444
Opened 2017-10-17 17:21 UTC by bruceburge

Removed unneeded iconForFile = Icon.ExtractAssociatedIcon(file.FullName); this would cause extraction every time and defeat the purpose of the the imagelist check.

# Removed Extract Icon Extraction call

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

The extract call made the following statements moot, and defeated the purpose of the caching.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-10-17 17:21 UTC, dnfclas commented
This seems like a small (but important) contribution, so no Contribution License Agreement is required at this point. We will now review your pull request.
_Thanks,
.NET Foundation Pull Request Bot_

2017-10-17 23:27 UTC, rpetrusha requested changes
Thanks for correcting this example, @bruceburge. Could you also correct the corresponding Visual Basic example at docs/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Drawing.Icon.ExtractAssociatedIconEx/VB? Or if you'd prefer, we can change it.

2017-10-17 23:37 UTC, bruceburge commented
As near as I can tell
https://github.com/bruceburge/docs/edit/live/samples/snippets/visualbasic/VS_Snippets_Winforms/System.Drawing.Icon.ExtractAssociatedIconEx/VB/Form1.vb

doesn't have the extra code that I removed from the C# sample.

2017-10-18 17:53 UTC, rpetrusha commented
You're right, @bruceburge. I apologize. I didn't actually inspect the Visual Basic code, since it's supposed to be the same as the C# code. I'll merge your PR now. Thanks again for submitting this PR.

2017-10-18 17:53 UTC, rpetrusha approved these changes

2017-10-18 17:53 UTC, merged