.NET Standard serialization topic
dotnet/docs pull request #3462
Opened 2017-10-19 01:19 UTC by rpetrusha

# .NET Standard serialization topic

Shows how to check whether a type in a .NET Standard library is serializable, since the .NET Standard does not define serialization.

## Summary

Includes project files and source code files for VB and C#, and updates the TOC.

Fixes #3249 

## Details

For convenience, I combined the library method in the same file as the console application, which means that it's no longer a library method that targets the .NET Standard. 

## Suggested Reviewers
@mairaw, @BillWagner, @ViktorHofer

2017-10-19 16:26 UTC, ViktorHofer commented
The code snippet and related links still seem to be broken. I will review again after the code snippet is accessible. Thanks for your work @rpetrusha !!

2017-10-19 17:47 UTC, BillWagner requested changes
This looks great Ron.  I'd found a couple small grammar notes and had one other suggestion.

2017-10-19 17:47 UTC, BillWagner commented on docs/standard/serialization/how-to-determine-if-netstandard-object-is-serializable.md
> +The .NET Standard is a specification that defines the types and members that must be present on specific .NET implementations that conform to that version of the standard. However, the .NET Standard
missing word: "free determine" should be "free to determine"

2017-10-19 17:47 UTC, BillWagner commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +            var formatter = new BinaryFormatter();
indentation on this line is off

2017-10-19 17:47 UTC, BillWagner commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +            // Deserialize the value tuple.
These four lines are not indented correctly

2017-10-19 17:47 UTC, BillWagner commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +        public static bool IsSerializable(object obj)
Consider making this an extension method:

```csharp
public static bool IsSerializable(this object obj)
```

The example could then be:

```csharp
if (value.IsSerializable())
```

2017-10-19 17:47 UTC, BillWagner commented on samples/snippets/standard/serialization/is-serializable/vb/program.vb
> +    	Public Shared Function IsSerializable(obj As Object) As Boolean
Same comment as the C# sample: consider an extension method

2017-10-19 17:54 UTC, ViktorHofer commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +				stream.Close();
Use using around stream instead of manually closing it

2017-10-19 17:58 UTC, ViktorHofer commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +            var restoredValue = formatter.Deserialize(readStream);
object instead of var

2017-10-19 17:58 UTC, ViktorHofer commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +            var readStream = new FileStream("data.bin", FileMode.Open);
use using here. same comment as above

2017-10-19 17:59 UTC, ViktorHofer commented on samples/snippets/standard/serialization/is-serializable/csharp/Program.cs
> +            if (obj == null)
just for reference, the whole expression could be simplified as obj?.GetType()?.IsSerializable ?? false;

2017-10-19 17:59 UTC, ViktorHofer commented on samples/snippets/standard/serialization/is-serializable/csharp/test-serialization.csproj
> +  <ItemGroup>
remove empty ItemGroup

2017-10-19 18:00 UTC, ViktorHofer commented on samples/snippets/standard/serialization/is-serializable/vb/test.serialization.vb.vbproj
> +  <ItemGroup>
same as above. remove empty group.

2017-10-19 21:15 UTC, rpetrusha commented
@ViktorHofer, @BillWagner, I've addressed your review comments.

2017-10-20 18:59 UTC, rpetrusha commented
@ViktorHofer and @BillWagner, I've fixed a build error and also added a paragraph to the documentation for System.Type.IsSerializable, if you'd like to take a look.

2017-10-20 19:02 UTC, BillWagner approved these changes

2017-10-20 19:03 UTC, BillWagner commented
The updates look good.  Go ahead and :shipit: when the build finishes.

2017-10-20 19:12 UTC, ViktorHofer commented
Jep. LGTM

2017-10-20 19:46 UTC, mairaw approved these changes
LGTM but left some comments in case you want to address them

2017-10-20 19:46 UTC, mairaw commented on docs/standard/serialization/how-to-determine-if-netstandard-object-is-serializable.md
> +ms.custom: ""
nit: no need to add this in new articles

2017-10-20 19:46 UTC, mairaw commented on docs/standard/serialization/how-to-determine-if-netstandard-object-is-serializable.md
> +[!code-csharp[is-a-type-serializable](~/samples/snippets/standard/serialization/is-serializable/csharp/program.cs#2)]
this path doesn't look right for snippets unless we want to change it. it should go under the language folders first and then you give a name
so under https://github.com/dotnet/docs/tree/master/samples/snippets/csharp and under https://github.com/dotnet/docs/tree/master/samples/snippets/visualbasic

2017-10-20 19:46 UTC, mairaw commented on docs/standard/serialization/how-to-determine-if-netstandard-object-is-serializable.md
> +You can then pass any object to the method to determine whether it can be serialized and deserialized on the current .NET implementation, as the following example shows.
nit: end with a colon instead of period

2017-10-20 23:59 UTC, merged