Fix capturing groups order
dotnet/docs pull request #34892
Opened 2023-04-05 20:10 UTC by gewarren

Fixes #33333.

*Hide whitespace changes in diff.*

2023-04-05 20:11 UTC, gewarren commented on docs/standard/base-types/grouping-constructs-in-regular-expressions.md
> +| 4      | 4 (default name) | `(.*)`                             |
This table is the only place something significant was changed in the file (i.e. the order of the capturing groups).

2023-05-05 17:38 UTC, adegeo requested changes

2023-05-05 17:38 UTC, adegeo commented on docs/standard/base-types/grouping-constructs-in-regular-expressions.md
> +| 4      | 4 (default name) | `(.*)`                             |
I tested this and I think the original doc is correct. The suggestion the issue is making seems wrong, it's listing `(?<Two>xyz)` twice in the results.

```csharp
var results = Regex.Match("abc8xyzfdsa", "((?<One>abc)\\d+)?(?<Two>xyz)(.*)");

int index = 0;

//foreach (var group in results.Groups.Cast<Group>()) // .NET 4.8
foreach (var group in results.Groups) // .NET 7
{
    Console.WriteLine($"I:{index} N:{group.Name} V:{group.Value}");
    index++;
}
```

**.NET 7**
```output
I:0 N:0 V:abc8xyzfdsa
I:1 N:1 V:abc8
I:2 N:2 V:fdsa
I:3 N:One V:abc
I:4 N:Two V:xyz
```

**.NET Framework** (same as .NET 7 but I still included it)
```output
I:0 N:0 V:abc8xyzfdsa
I:1 N:1 V:abc8
I:2 N:2 V:fdsa
I:3 N:One V:abc
I:4 N:Two V:xyz
```

2023-05-05 19:40 UTC, gewarren commented on docs/standard/base-types/grouping-constructs-in-regular-expressions.md
> +Here, *subexpression* is any valid regular expression pattern. Captures that use parentheses are numbered automatically from left to right based on the order of the opening parentheses in the regular
```suggestion
Here, *subexpression* is any valid regular expression pattern. Captures that use parentheses are numbered automatically from left to right based on the order of the opening parentheses in the regular expression, starting from 1. However, [named capture groups](#named-matched-subexpressions) are always ordered last, after non-named capture groups. The capture that's numbered 0 is the text matched by the entire regular expression pattern.
```

2023-05-05 19:44 UTC, adegeo approved these changes
LGTM!

2023-05-05 19:45 UTC, merged