WCF breaking change
dotnet/docs pull request #34914
Opened 2023-04-06 23:49 UTC by gewarren

Fixes #34909

2023-04-07 02:11 UTC, mconnew commented on docs/core/compatibility/toc.yml
> +      - name: Duplex contract captures synchronization context
DuplexChannelFactory captures synchronization context

2023-04-07 02:12 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +title: "Breaking change: Duplex contract captures synchronization context"
```suggestion
title: "Breaking change: DuplexChannelFactory captures synchronization context"
```

2023-04-07 02:12 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +description: Learn about the breaking change in WCF Client 6.0 where the duplex contract now captures synchronization context when it's opened.
description: Learn about the breaking change in WCF Client 6.0 where the DuplexChannelFactory now captures the synchronization context when it's opened.

2023-04-07 02:13 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +The duplex contract now captures the synchronization context when it's opened and dispatches callbacks to the captured context.
```suggestion
DuplexChannelFactory now captures the synchronization context when it's opened and dispatches callbacks to the captured context.
```

2023-04-07 02:14 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +In previous versions, the duplex contract failed to capture synchronization context when the channel factory was opened.
In previous versions, DuplexChannelFactory failed to capture the current synchronization context when the channel factory was opened.

2023-04-07 02:15 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +Starting in WCF Client 6.0 RC, the duplex channel captures synchronization context and dispatches callbacks to the captured context. This behavior matches that of .NEt Framework.
```suggestion
Starting in WCF Client 6.0 RC, DuplexChannelFactory captures the current synchronization context when opened and dispatches callbacks to the captured context. This behavior matches that of .NET Framework.
```

2023-04-07 02:21 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +This change was made to [fix a bug](https://github.com/dotnet/wcf/issues/4946) where the client hung when making an asynchronous call followed by a synchronous call. The new behavior matches .NET Fra
That wasn't the bug for this change. It was an internal find which was reported directly to me. An issue was never opened for it. The internal problem was a callback was instantiating a STA COM object and as the initial callback and subsequent callbacks weren't being dispatched to a custom SynchronizationContext, the callbacks were happening on the wrong thread.

2023-04-07 02:22 UTC, mconnew commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +If the new behavior is undesirable, you can revert to version 4.x behavior by applying the <xref:System.ServiceModel.CallbackBehaviorAttribute> to your contract with the <xref:System.ServiceModel.Cal
```suggestion
If the new behavior is undesirable, you can revert to version 4.x behavior by applying the <xref:System.ServiceModel.CallbackBehaviorAttribute> to your callback contract with the <xref:System.ServiceModel.CallbackBehaviorAttribute.UseSynchronizationContext> property set to `false`.
```

2023-04-07 02:23 UTC, mconnew requested changes
Duplex contract should have been DuplexChannelFactory. I don't know if you want to put the generic parameter TChannel as part of the name or if it should be linked.

2023-04-07 03:22 UTC, gewarren commented on docs/core/compatibility/wcf-client/6.0/duplex-synchronization-context.md
> +This change was made to [fix a bug](https://github.com/dotnet/wcf/issues/4946) where the client hung when making an asynchronous call followed by a synchronous call. The new behavior matches .NET Fra
```suggestion
This change was made to fix a bug where callbacks were happening on the wrong thread. The new behavior matches .NET Framework functionality.
```

2023-04-08 00:47 UTC, mconnew approved these changes

2023-04-08 04:15 UTC, merged