Add binary specifier to standard numeric format strings
dotnet/docs pull request #35049
Opened 2023-04-18 18:40 UTC by stephentoub

.NET 8 is adding support for the "B"/"b" specifier.

2023-04-18 18:50 UTC, tannergooding approved these changes

2023-04-24 21:47 UTC, gewarren requested changes

2023-04-24 21:47 UTC, gewarren commented on docs/standard/base-types/standard-numeric-format-strings.md
> +| "B" or "b" | Binary | Result: A binary string.<br /><br /> Supported by: Integral types only (.NET 8+).<br /><br /> Precision specifier: Number of digits in the result string.<br /><br /> More info
```suggestion
| "B" or "b" | Binary | Result: A binary string.<br /><br /> Supported by: Integral types only (.NET 8+).<br /><br /> Precision specifier: Number of digits in the result string.<br /><br /> More information: [The Binary ("B") Format Specifier](#binary-format-specifier-b). | 42 ("B")<br />-> 101010<br /><br /> 255 ("b16")<br />-> 0000000011111111 |
```

2023-04-24 21:47 UTC, gewarren commented on docs/standard/base-types/standard-numeric-format-strings.md
>  <a name="CFormatString"></a>
Line 97 needs to be placed just above new line 107 since it supplies navigation to that section.

2023-04-24 23:06 UTC, gewarren approved these changes
Thanks for adding this!

2023-04-24 23:07 UTC, merged