Updating to a simple redirect to the main topic.
dotnet/docs pull request #35601
Opened 2023-06-02 22:29 UTC by stevewhims

This will get the reader to the detailed topic more quickly, and will be more economical to maintain going forward.

2023-06-05 20:25 UTC, gewarren approved these changes

2023-06-05 20:25 UTC, gewarren commented on docs/core/porting/upgrade-assistant-uwp-framework.md
> +ms.date: 09/02/2023
```suggestion
ms.date: 06/02/2023
```

2023-06-05 20:25 UTC, gewarren commented on docs/core/porting/upgrade-assistant-uwp-framework.md
> +title: Migrate UWP to Windows App SDK with the .NET Upgrade Assistant
```suggestion
title: Migrate from UWP to Windows App SDK with the .NET Upgrade Assistant
```

2023-06-06 17:50 UTC, stevewhims commented
#sign-off

2023-06-06 18:19 UTC, adegeo commented
👀

2023-06-06 18:28 UTC, adegeo requested changes
@stevewhims why not just put `/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/upgrade-assistant` in the TOC instead of this file and then create a redirect?

The toc file is in `/docs/navigate/migration-guide`

2023-06-06 19:45 UTC, stevewhims commented
> @stevewhims why not just put `/windows/apps/windows-app-sdk/migrate-to-windows-app-sdk/upgrade-assistant` in the TOC instead of this file and then create a redirect?
> 
> The toc file is in `/docs/navigate/migration-guide`

I've gone with that direction. Does it look ok?

2023-06-06 20:24 UTC, adegeo commented
@stevewhims Looks good. I think the redirect should be in `.openpublishing.redirection.core.json`, and the redirect you filed is missing .md at the end of the file name. Once that's fixed, it's merge time! Thanks!

2023-06-06 21:03 UTC, stevewhims commented
> @stevewhims Looks good. I think the redirect should be in `.openpublishing.redirection.core.json`, and the redirect you filed is missing .md at the end of the file name. Once that's fixed, it's merge time! Thanks!

Let's try this. Btw, I can't merge AFAIK, so if I eventually get these changes right, it'd be great if you could merge for me. Thank you!

2023-10-10 20:40 UTC, adegeo approved these changes
Sorry for the delay!

2023-10-10 20:40 UTC, merged