ComWrappers breaking change
dotnet/docs pull request #35759
Opened 2023-06-12 22:02 UTC by gewarren

Fixes #35728

2023-06-12 23:10 UTC, jkoritzinsky approved these changes, later dismissed

2023-06-12 23:12 UTC, jkoritzinsky requested changes
"managed object wrapper" is a term here, not a reference to the public ManagedObjectWrapper type.

2023-06-12 23:12 UTC, jkoritzinsky commented on docs/core/compatibility/interop/8.0/comwrappers-unwrap.md
> +Calling <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)> on a <xref:System.Runtime.InteropServices.Com
```suggestion
Calling <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)> on a <xref:System.Runtime.InteropServices.ComWrappers> instance with the <xref:System.Runtime.InteropServices.CreateObjectFlags.Unwrap?displayProperty=nameWithType> flag only unwraps a managed object wrapper from the <xref:System.Runtime.InteropServices.ComWrappers> instance that `GetOrCreateObjectForComInstance` was called on. If given a wrapper from a different <xref:System.Runtime.InteropServices.ComWrappers> instance, the `ComWrappers` instance creates a new wrapper.
```

2023-06-12 23:12 UTC, jkoritzinsky commented on docs/core/compatibility/interop/8.0/comwrappers-unwrap.md
> +Calling <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)> on a <xref:System.Runtime.InteropServices.Com
```suggestion
Calling <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)> on a <xref:System.Runtime.InteropServices.ComWrappers> instance with the <xref:System.Runtime.InteropServices.CreateObjectFlags.Unwrap?displayProperty=nameWithType> flag unwrapped a managed object wrapper from any <xref:System.Runtime.InteropServices.ComWrappers> instance.
```

2023-06-12 23:12 UTC, jkoritzinsky commented on docs/core/compatibility/interop/8.0/comwrappers-unwrap.md
> +Previously, if you called <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)?displayProperty=fullName?dis
```suggestion
Previously, if you called <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)?displayProperty=fullName?displayProperty=nameWithType> on a <xref:System.Runtime.InteropServices.ComWrappers> instance with the <xref:System.Runtime.InteropServices.CreateObjectFlags.Unwrap?displayProperty=nameWithType> flag, a managed object wrapper was unwrapped from *any* <xref:System.Runtime.InteropServices.ComWrappers> instance. Now when the flag is specified, only wrappers from the <xref:System.Runtime.InteropServices.ComWrappers> instance that `GetOrCreateObjectFromComInstance` was called on are unwrapped.
```

2023-06-13 02:52 UTC, gewarren commented on docs/core/compatibility/interop/8.0/comwrappers-unwrap.md
> +Calling <xref:System.Runtime.InteropServices.ComWrappers.GetOrCreateObjectForComInstance(System.IntPtr,System.Runtime.InteropServices.CreateObjectFlags)> on a <xref:System.Runtime.InteropServices.Com
Good catch, thanks!

2023-06-13 03:09 UTC, jkoritzinsky approved these changes

2023-06-13 03:27 UTC, merged