What's new in the .NET Standard 2.0
dotnet/docs pull request #3577
Opened 2017-10-31 18:42 UTC by rpetrusha

# What's new in the .NET Standard 2.0

## Suggested Reviewers

@BillWagner, @mairaw, @terrajobst

2017-11-06 21:26 UTC, JRAlexander requested changes
LGTM. Overall, great job, @rpetrusha! Just a few small things.

2017-11-06 21:26 UTC, JRAlexander commented on docs/standard/whats-new/whats-new-in-dotnet-standard.md
> +- Support for the <xref:System.AppDomain>] class.
Remove the ']'.

2017-11-06 21:26 UTC, JRAlexander commented on docs/standard/whats-new/whats-new-in-dotnet-standard.md
> +The .NET Standard is a formal specification that defines a versioned set of APIs which must be available on .NET implementations that comply with that version of the standard. The .NET Standard is ta
I would change "It aims to guarantee the functionality that is available to a library that targets a version of the .NET Standard on each .NET implementation. In other words, a library that targets a version of the .NET Standard can be used on any .NET Framework, .NET Core, or Xamarin implementation that supports that version of the standard." to something like "A library that targets a .NET Standard version can be used on any .NET Framework, .NET Core, or Xamarin implementation that supports that standard version."

2017-11-06 21:26 UTC, JRAlexander commented on docs/standard/whats-new/whats-new-in-dotnet-standard.md
> +
I would replace with something like "<xref:System> namespace additions in .NET Standard 2.0 include:".

2017-11-06 21:26 UTC, JRAlexander commented on docs/standard/whats-new/whats-new-in-dotnet-standard.md
> +You can now develop .NET Standard libraries in Visual Basic. For Visual Basic developers using Visual Studio 2017, Visual Studio now includes a .NET Standard Class Library template. For Visual Basic
Is there a minimum version of Visual Studio needed for the .NET Standard Template?

2017-11-07 17:56 UTC, rpetrusha commented
Thanks for the review, @JRAlexander. I've addressed all of your comments.

2017-11-07 18:49 UTC, JRAlexander commented on docs/standard/whats-new/whats-new-in-dotnet-standard.md
> +Some of the more additions to the <xref:System> namespace in .NET Standard 2.0 include:
This looks like a typo.

2017-11-09 17:13 UTC, rpetrusha commented
Thanks for catching the typo, @JRAlexander. I've corrected it.

2017-11-09 19:27 UTC, JRAlexander approved these changes

2017-11-09 19:27 UTC, JRAlexander commented
LGTM. Great work, @rpetrusha!

2017-11-09 19:59 UTC, rpetrusha commented
closing and reopening to begin new build...

2017-11-11 00:02 UTC, merged