Example Modification
dotnet/docs pull request #35861
Opened 2023-06-17 08:49 UTC by postmeback

I have updated the example, where `G` and `F` will have different result

Fixes #35854

2023-06-19 11:56 UTC, IEvangelist requested changes
This doesn't fix the ops concerns.

2023-06-19 13:55 UTC, postmeback commented
````C#
[Flags]
enum DaysOfWeek
{
    None = 0,
    Sunday = 1,
    Monday = 2,
    Tuesday = 4,
    Wednesday = 8,
    Thursday = 16,
    Friday = 32,
    Saturday = 64
}

class Program
{
    static void Main()
    {
        DaysOfWeek workDays = DaysOfWeek.Monday | DaysOfWeek.Tuesday | DaysOfWeek.Wednesday | DaysOfWeek.Thursday | DaysOfWeek.Friday;

        Console.WriteLine("Formatted using G: {0:G}", workDays);
        Console.WriteLine("Formatted using F: {0:F}", (int)workDays);
    }
}





````

will this example work ?, if yes, I am happy to update the file.

2023-06-22 17:46 UTC, postmeback commented
Requesting the maintainers to look at the example provided in the comment.

2023-06-27 14:45 UTC, BillWagner commented
Hi @postmeback 

Here's the output I get from the sample in your comment:

```console
Formatted using G: Monday, Tuesday, Wednesday, Thursday, Friday
Formatted using F: 62.00
```

See this [sharplab](https://sharplab.io/#v2:EYLgtghglgdgNAFxAJwK7wCYgNQB8ACATAAwCwAUEQIwUUDaAYgDYQDmAzgLoUCmMqYAAQARCAE92AeQBmAdR48A1hQDeFQRsEA5APYweggLyDicdZoDK6DOKOCqZ8psEBZPTbF3Cj5wBVUPOwedgAsPpryGPpBtsYAHOEavgAWqMgxnsZUAGyJggzIUMHGAMze5hoWEAhpxYLZIRQAvrSUhIL4VADsqhUdOR0hrtAwABQAlH1qTs6aohIy8kqCAO46yIrz7HZbiwqKAHRuMMG4IuJScvsH/oGn5wtXSgeR0fe7T4cpaRmCZx9LQ4FIriADcrVmmk6AE5RgAiBjrSAIBA8DAdYiCADiIEEKmIICxTThcFW602F3G4JmkJh8MRyGRqPR+ExDFx+JADGJpNGsAQ4zWGy2VL6LXI4taQA==)

2023-06-27 19:16 UTC, postmeback commented
The answer is expected

**Explanation**


In this example, we define an enumeration DaysOfWeek with the Flags attribute, indicating that it represents a bitwise combination of flags.

The enum has multiple members representing individual days of the week. Each member is assigned a power of 2 value to enable bitwise operations.

Within the Main method, we initialize a variable workDays with a combination of flags representing Monday through Friday.

When we use the "G" format specifier in Console.WriteLine("Formatted using G: {0:G}", workDays), it displays the string representation of the enum value. In this case, it prints Monday, Tuesday, Wednesday, Thursday, Friday since those are the flags set in workDays.

When we use the "F" format specifier with (int)workDays in Console.WriteLine("Formatted using F: {0:F}", (int)workDays), it formats the underlying integer value of the enum. In this case, the integer value of the combined flags is 62 (binary representation: 00111110), so it displays 62.

Thus, by using the "G" and "F" format specifiers, we can obtain different representations of the enum value, one as a combination of flag names and the other as the corresponding integer value.`

2023-06-27 19:53 UTC, BillWagner commented
> The answer is expected

I agree! This is a great example for this issue.

2023-06-28 04:31 UTC, postmeback commented
I will make a PR soon, with the necessary changes.

2023-06-28 12:29 UTC, IEvangelist commented
I already fixed the issue in question with https://github.com/dotnet/docs/pull/35873, I don't think this is needed anymore.

2023-06-28 17:00 UTC, postmeback commented
Okay then, closing the PR as of now

2023-06-28 17:00 UTC, closed without merging