Process.WaitForExit does not accept all negative numbers
dotnet/docs pull request #3590
Opened 2017-11-01 17:09 UTC by svick

The old wording made it sound as if e.g. `process.WaitForExit(-2)` was a valid way to specify infinite timeout, but it's not ("ArgumentOutOfRangeException: Number must be either non-negative and less than or equal to Int32.MaxValue or -1.").

So I've changed it to talk only about `Timeout.Infinite`, and also include the type name for that, to make it clearer.

2017-11-01 18:56 UTC, rpetrusha requested changes
Thanks, @svick. You've made the remarks much clearer. One issue, though, is that the ArgumentOutOfRangeException should be documented but is not. Could you add it to the documentation? Or if you'd rather, we can open a new PR after we merge yours. If you'd like to add it, the general format of exception conditions is that each condition appears on a separate line separated by a line containing "-or-".

2017-11-03 22:01 UTC, svick commented
@rpetrusha Good point, I have added the exception. (Though it's a separate exception type, so I didn't use the "-or-" approach.)

I looked into this further and discovered that the `ArgumentOutOfRangeException` is not currently thrown on .Net Core on Unix, but I don't think that's worth explicitly documenting. Especially since that might change in the future, see https://github.com/dotnet/corefx/issues/25056, which I just opened.

2017-11-04 02:07 UTC, rpetrusha approved these changes

2017-11-04 02:08 UTC, rpetrusha commented
Thanks, @svick, for adding the exception. This is ready to merge.

2017-11-04 02:08 UTC, merged