Update object-and-collection-initializers.md
dotnet/docs pull request #36232
Opened 2023-07-12 13:38 UTC by ErykKorzeniowski

## Summary

Added documentation for required and init keywords.

Fixes #35014

2023-07-12 14:42 UTC, BillWagner requested changes
Hi @ErykKorzeniowski 

This is a great addition.  I had a number of comments based on our style guide. Let me know what you think, and once we resolve these discussions, this is ready to merge.

2023-07-14 13:55 UTC, ErykKorzeniowski commented
@BillWagner, I loved your comments! Thank you, in the future, I will do more 2nd person speech!

2023-07-14 14:51 UTC, BillWagner approved these changes

2023-07-14 14:51 UTC, BillWagner commented
Thanks for making the updates @ErykKorzeniowski 

The warning is unrelated, so I'll :shipit: now.

2023-07-14 14:52 UTC, merged