fix formatting issues
dotnet/docs pull request #3625
Opened 2017-11-07 00:15 UTC by mairaw

While reviewing the issue #3623, I've noticed that the topic (https://docs.microsoft.com/en-us/dotnet/framework/wpf/advanced/how-to-localize-an-application) has some other issues:

- A broken table:
![image](https://user-images.githubusercontent.com/12971179/32470573-9a6abefa-c30d-11e7-9045-4313bc36caa0.png)

- Broken snippet references
![image](https://user-images.githubusercontent.com/12971179/32470588-ae267b96-c30d-11e7-9b98-2f949ad4b1db.png)

While we wait for the team to confirm the new location of the samples, I thought I'd fix these other issues.

2017-11-07 17:58 UTC, JRAlexander requested changes

2017-11-07 17:58 UTC, JRAlexander commented on docs/framework/wpf/advanced/how-to-localize-an-application.md
There are formatting issues.  The table still appears to be broken.

2017-11-07 22:38 UTC, mairaw commented
Thanks for checking @JRAlexander and adding the preview URL. Let's see if this change fixes the issue. It did on the Gauntlet preview at least.

2017-11-08 17:59 UTC, mairaw commented
@JRAlexander it seems that my last commit fixed the issue. Can you give me your seal of approval? 😄

2017-11-08 18:16 UTC, JRAlexander commented
Looks wonderful @mairaw!!!

2017-11-08 18:16 UTC, JRAlexander commented
Looks wonderful @mairaw!!!

2017-11-08 18:17 UTC, JRAlexander approved these changes

2017-11-08 18:19 UTC, merged