added %2A to fix a link
dotnet/docs pull request #3634
Opened 2017-11-08 04:39 UTC by MarkIannucci

# I fixed a link.

## Summary

Fixed a link which current reads like this in the web: 
`use the <xref:System.Threading.Tasks.ValueTask?displayProperty=nameWithType> structure`

2017-11-08 17:47 UTC, rpetrusha requested changes
Thanks for submitting your PR, @MarkIannucci. Unfortunately, it doesn't fix the link. (%2A is intended for use with members, not types.) Changing the link to  \<xref:System.Threading.Tasks.ValueTask%601?displayProperty=nameWithType> should fix the link, though. Would you like to make the change, or would you like us to make it?

2017-11-09 01:10 UTC, MarkIannucci commented
@rpetrusha , no better way to learn than by doing.  I committed the update a few minutes ago.  It look like it is building now.

2017-11-09 03:01 UTC, rpetrusha approved these changes

2017-11-09 03:01 UTC, rpetrusha commented
Thanks, @MarkIannucci. That fixes the link. I'll merge your PR now. Your correction should appear live on docs.microsoft.com tomorrow.

2017-11-09 03:01 UTC, merged