Added additional exception case
dotnet/docs pull request #3651
Opened 2017-11-10 14:40 UTC by samrueby

Documentation did not state what exception is thrown when a physical path is passed instead of a virtual path.

2017-11-10 16:35 UTC, rpetrusha commented on xml/System.Web/HttpServerUtility.xml
> +        <exception cref="T:System.Web.HttpException"><paramref name="path" /> is a physical path, but a virtual path was expected.</exception>
The convention used throughout the managed reference is to have a single \<exception> element for a particular exception type and to list multiple exception conditions separated by "-or-". So there should be a single exception element for HttpException that appears as follows:

\<exception cref="T:System.Web.HttpException">The current \<see cref="T:System.Web.HttpContext" /> is \<see langword="null" />.

-or-

\<paramref name="path" /> is a physical path, but a virtual path was expected.\</exception> 

Would you like to make the change, or would you prefer that we make it for you?

2017-11-10 16:38 UTC, rpetrusha requested changes
Thank you very much for adding the additional exception condition to the documentation, @samrueby. However, duplicating \<exception> elements for a single exception type is not consistent with the way exception information is presented throughout the API documentation. In my comment, I've indicated the correct format to use when adding an exception condition. Could you make this change, or would you prefer that we make it for you?

2017-11-14 13:33 UTC, samrueby commented
Sorry, I thought I updated this request days ago.  Thank you- I've made the changes you requested.

2017-11-14 22:15 UTC, rpetrusha commented
Thanks for making the additional change, @samrueby. We'll merge your PR now. Changes should appear on docs.microsoft.com in the next day or two.

2017-11-14 22:15 UTC, rpetrusha approved these changes

2017-11-14 22:15 UTC, merged

2017-11-14 22:25 UTC, samrueby commented
Thank you