Fixed exception list for GetFunctionPointerForDelegate<TDelegate>
dotnet/docs pull request #3671
Opened 2017-11-14 01:12 UTC by cleak

The generic form of GetFunctionPointerForDelegate<TDelegate> previously did not list System.ArgumentException as being thrown, even though it can be, just like its non-generic form.

# Title

Fixed exception list for GetFunctionPointerForDelegate<TDelegate>

## Summary

The generic form of GetFunctionPointerForDelegate<TDelegate> previously did not list System.ArgumentException as being thrown, even though it can be, just like its non-generic form.

## Details

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-11-14 18:18 UTC, rpetrusha requested changes
Thanks, @cleak, for contributing to the dotnet/docs repo and for adding this missing exception.  The en-US exception message is "The specified Type must not be a generic type definition." I think that the description here would be a bit clearer if "definition" were added, so that it instead read, "The \<paramref name="d" /> parameter is a generic type definition." Would you mind making the change? If you'd prefer, we can also make it for you.

2017-11-14 18:19 UTC, rpetrusha commented
Closing and reopening to begin new build.

2017-11-16 06:00 UTC, cleak reviewed
Changes made; ready for another review. There are several other places in the doc that use the phrase "generic type", but I don't have enough context to say whether they should change or not.

2017-11-16 20:00 UTC, rpetrusha approved these changes

2017-11-16 20:03 UTC, rpetrusha commented
Thanks for making the additional changes, @cleak. Yes, there are a number of other mentions of generic types in the System.Marshal.xml file. There's no need to address them in this PR, though. I'll open an issue so that they can be addressed later. In the meantime, I'll merge your PR. Your changes should appear live on docs.microsoft.com in the next day or two.

2017-11-16 20:03 UTC, merged