Update ipv6-element-network-settings.md
dotnet/docs pull request #3706
Opened 2017-11-16 03:15 UTC by JapNolt

Correct the XML in the Syntax section

# Title

Fix XML Syntax

## Summary

Correct the XML in the Syntax section

2017-11-16 19:06 UTC, rpetrusha requested changes
Thank you submitting this PR to correct both formatting and misformed XML, @JapNolt . However, your change isn't correct, since `enabled` is an attribute of `ipv6`. The correct syntax is:
```xml
<ipv6
   enabled="true|false"
/>
```

2017-11-16 19:17 UTC, JapNolt commented
@rpetrusha  I made the changes as requested. Sorry about that.

2017-11-16 23:21 UTC, rpetrusha approved these changes

2017-11-17 00:45 UTC, mairaw commented
Build looks good. Thanks once again @JapNolt! Your fix should go live in the next day or so.

2017-11-17 00:45 UTC, merged