Fix XML Syntax and other minor changes
dotnet/docs pull request #3709
Opened 2017-11-16 06:01 UTC by JapNolt

# Title

Fix XML Syntax and other minor changes

## Summary

Most of the changes are to fix XML formatting issues or to make the XML more readable. There are a few changes to attribute names which I note below.

## Details
[Fix attribute name in Example](https://github.com/dotnet/docs/commit/0fcad6fc02b54b5c7bf9a28ed68d0ba270263219)
[Fix attribute name in Syntax section](https://github.com/dotnet/docs/commit/86e478bfbc02da167ba8598d99aca298b0e77951)
[Change the "name" attribute to "address". According to VS Intellisense](https://github.com/dotnet/docs/commit/f42a2a5fb59827a80e47e211ef75d35ae03f6778)
[Change attribute from "name" to "type", per VS Intellisense.](https://github.com/dotnet/docs/commit/47a35bd722ebf60b953438bf18f3383616131921)
[Change attribute from "name" to "prefix", per VS intellisense](https://github.com/dotnet/docs/commit/e80904ae8d57f7d1fabd418a3ca190683dfe3686)
[Fix element name in Syntax section](https://github.com/dotnet/docs/commit/9de83243a241dde4c22ef1ded6971da6958a038f)

2017-11-16 18:47 UTC, rpetrusha requested changes
Thank you so much, @JapNolt, for improving the formatting of these topics, as well as for identifying and fix badly formed XML tags and correcting syntax errors. In reviewing your PR, I found a few other errors. Would you mind fixing them as well? Or, if you prefer, we can fix them for you.

2017-11-18 04:21 UTC, JapNolt reviewed
@rpetrusha Is this what you're looking for? I'm not an expert at DocFX formatting. Note that I also made 2 changes in the Remarks section.

2017-11-20 23:04 UTC, rpetrusha commented
This is what I was looking for, @JapNolt. Thank you so much. You've done a really outstanding job! We'll merge your PR now. Changes should appear live on docs.microsoft.com in the next day or two.

2017-11-20 23:04 UTC, rpetrusha approved these changes

2017-11-20 23:04 UTC, merged