add note for security concerns
dotnet/docs pull request #3727
Opened 2017-11-17 16:44 UTC by BillWagner

Also, add missing meta-data on new topics.

This is in response to a comment on the .NET Blog entry announcing C# 7.2

2017-11-17 19:11 UTC, JRAlexander requested changes
Just a few formatting issues.

2017-11-17 19:11 UTC, JRAlexander commented on docs/csharp/language-reference/keywords/private-protected.md
> + [Security concerns for internal virtual keywords](https://msdn.microsoft.com/library/heyd8kky(v=vs.110))
The added link is on the same line with the line above. See the internal URL I added.

2017-11-17 19:11 UTC, JRAlexander commented on docs/csharp/language-reference/keywords/protected-internal.md
> + [Security concerns for internal virtual keywords](https://msdn.microsoft.com/library/heyd8kky(v=vs.110))
Same here.

2017-11-17 19:35 UTC, JRAlexander approved these changes

2017-11-17 20:43 UTC, merged

2018-02-28 16:39 UTC, Alexandre-FR reviewed
test

2018-02-28 19:22 UTC, mairaw commented
@Alexandre-FR do you need help with anything?