Update external-functions.md
dotnet/docs pull request #37418
Opened 2023-10-10 10:50 UTC by roboz0r

## Summary

Provides examples of using managed and unmanaged types to declare external functions.

Fixes #37304

2023-10-10 10:52 UTC, roboz0r commented
@dotnet-policy-service agree

2023-10-10 14:07 UTC, BillWagner requested changes
Hi @roboz0r

The context of the changes looks great. I made suggestions that will address the warnings in the build. Once you accept those, and we have a clean build, I'll approve this and merge it.

Thanks for helping us improve.

2023-10-10 14:07 UTC, BillWagner commented on docs/fsharp/language-reference/functions/external-functions.md
> +You could use [`Marshal.StringToHGlobalUni`](https://learn.microsoft.com/en-us/dotnet/api/system.runtime.interopservices.marshal.stringtohglobaluni) to convert a .NET string to native format and rece
similar change, but use the XREF syntax for API reference:

```suggestion
You could use<xref:System.Runtime.InteropServices.Marshal.StringToHGlobalUni%2A?displayProperty=nameWithType> to convert a .NET string to native format and receive a pointer (`nativeint`) to it that could be supplied to `lpApplicationName`.
```

2023-10-10 14:07 UTC, BillWagner commented on docs/fsharp/language-reference/functions/external-functions.md
> +To obtain a pointer to an integer you would use the pointer of `&&` operator or the [`fixed`](https://learn.microsoft.com/en-us/dotnet/fsharp/language-reference/fixed) keyword.
and one more:

```suggestion
To obtain a pointer to an integer you would use the pointer of `&&` operator or the [`fixed`](../language-reference/fixed.md) keyword.
```

2023-10-10 21:48 UTC, roboz0r commented
Thanks for the review @BillWagner I'll know about the use of relative links next time.

2023-10-11 13:49 UTC, BillWagner approved these changes

2023-10-11 13:49 UTC, merged