Update diagnostic docs for SYSLIB0009
dotnet/docs pull request #37452
Opened 2023-10-11 18:39 UTC by deeprobin

## Summary

Follow-up for https://github.com/dotnet/runtime/pull/93171.
Change obsoletion documentation: Whole class marked as obsolete. 

See https://github.com/dotnet/runtime/issues/77459.

/cc @MihaZupan

2023-10-11 18:42 UTC, MihaZupan approved these changes
Thank you

2023-10-11 19:10 UTC, gewarren commented
Thank you. Since this is for .NET 9, we shouldn't merge it yet.

2023-10-11 19:16 UTC, gewarren commented
We also need to:

- Update https://github.com/dotnet/docs/blob/main/docs/fundamentals/syslib-diagnostics/obsoletions-overview.md
- Create a new article like this but for .NET 9: https://github.com/dotnet/docs/blob/main/docs/core/compatibility/core-libraries/8.0/obsolete-apis-with-custom-diagnostics.md

2023-10-11 19:19 UTC, gewarren requested changes

2023-10-11 19:19 UTC, gewarren commented on docs/fundamentals/syslib-diagnostics/syslib0009.md
> +# SYSLIB0009: AuthenticationManager is not supported. Methods will no-op or throw PlatformNotSupportedException
```suggestion
# SYSLIB0009: AuthenticationManager is not supported
```

2023-10-11 19:19 UTC, gewarren commented on docs/fundamentals/syslib-diagnostics/syslib0009.md
> +The methods will no-op or throw <xref:System.PlatformNotSupportedException>.
```suggestion
The methods in this class either no-op or throw a <xref:System.PlatformNotSupportedException> at run time.
```

2023-10-11 19:19 UTC, gewarren commented on docs/fundamentals/syslib-diagnostics/syslib0009.md
> +The entire <xref:System.Net.AuthenticationManager> class is marked as obsolete as of .NET 9. The usage of this class generates warning `SYSLIB0009` at compile time.
```suggestion
In .NET 9 and later versions, the entire <xref:System.Net.AuthenticationManager> class is marked obsolete. Use of this class generates warning `SYSLIB0009` at compile time.
```

2023-10-16 16:34 UTC, gewarren approved these changes

2023-11-07 19:37 UTC, gewarren commented
@wfurt It can be merged if we change the date that's causing a warning, but why publish .NET 9 documentation now when the first preview won't be available until February?

2023-11-09 03:27 UTC, wfurt commented
so can complete runtime issue tracking it :)

2024-04-05 18:12 UTC, gewarren commented on docs/core/compatibility/core-libraries/9.0/obsolete-apis-with-custom-diagnostics.md
> +ms.date: 10/15/2023
```suggestion
ms.date: 04/05/2024
```

2024-04-05 18:14 UTC, gewarren commented on docs/core/compatibility/9.0.md
> +- [What's new in .NET 9](../whats-new/dotnet-9.md)
```suggestion
- [What's new in .NET 9](../whats-new/dotnet-9/overview.md)
```

2024-04-05 18:43 UTC, merged