Fixed a few links which pointed to azure.microsoft.com/documentation
dotnet/docs pull request #3746
Opened 2017-11-20 21:01 UTC by sputier

Fixes #3452 

There were few links which needed to be changed, mainly under the containerized-lifecycle-architecture e-book folder. 4 links hadn't a counterpart under http://docs.microsoft.com : 
 
- https://azure.microsoft.com/documentation/samples/storage-blob-dotnet-getting-started/
- https://azure.microsoft.com/documentation/templates/
- https://azure.microsoft.com/documentation/samples/storage-table-dotnet-getting-started/
- https://azure.microsoft.com/en-us/documentation/articles/websites-webjobs-resources/ => links to GitHub

@mairaw for review

2017-11-20 22:51 UTC, mairaw requested changes
This is great @sputier! I wanted to get those links updated. Left just a few comments to be addressed,

2017-11-20 22:51 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/orchestrate-high-scalability-availability.md
> +As shown in Figure 4-10, and thinking from a logical/business microservice perspective, when implementing a Service Fabric Stateful Reliable Service, you usually will need to implement two tiers of s
double slashes on the last link

2017-11-20 22:51 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md
> -documentation/articles/vs-azure-tools-docker-edit-and-refresh/](https://azure.microsoft.com/documentation/articles/vs-azure-tools-docker-edit-and-refresh/)
should update the link text too

2017-11-20 22:51 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/design-develop-containerized-apps/visual-studio-tools-for-docker.md
> -documentation/articles/vs-azure-tools-docker-hosting-web-apps-in-docker/](https://azure.microsoft.com/documentation/articles/vs-azure-tools-docker-hosting-web-apps-in-docker/)
should update link text too

2017-11-20 23:07 UTC, sputier commented
Thanks for the review @mairaw . I fixed these issues !

2017-11-20 23:19 UTC, mairaw approved these changes
Thanks for making the fixes so promptly! I'll merge as soon as the build finishes successfully!

2017-11-21 01:15 UTC, mairaw commented
Build looks good. Your changes should show up live in the next day or so.

2017-11-21 01:15 UTC, merged