Add dotnet package search documentation
dotnet/docs pull request #37747
Opened 2023-10-26 17:12 UTC by Nigusu-Allehu

## Summary

Add `dotnet package search` documentation.
Implementation: https://github.com/NuGet/NuGet.Client/pull/5466

2023-10-26 18:49 UTC, tdykstra requested changes
Thanks for doing this, @Nigusu-Allehu! The content is great, but I noted some ways in which it could more closely follow the patterns we typically use for formatting the CLI docs.

2023-10-26 18:49 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +## Examples
See [dotnet tool search](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-search) for an example of how to format these examples and how to write the text that introduces each one. Also, note that the opening triple backtick for each output example can specify output as the type:
~~~
```output
~~~

2023-10-26 18:49 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +## Options
We generally try to put the options in alphabetical order.

2023-10-26 18:49 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +    [--skip <SKIP>]
See [dotnet tool search](https://learn.microsoft.com/en-us/dotnet/core/tools/dotnet-tool-search) for an example of how to format the Synopsis section. Also we generally try to put the options in alphabetical order.

2023-11-10 21:41 UTC, Nigusu-Allehu commented
> Thanks for doing this, @Nigusu-Allehu! The content is great, but I noted some ways in which it could more closely follow the patterns we typically use for formatting the CLI docs.

Thank you for reviewing! I will revise this as soon as the product is complete and is about to be released.

2024-03-13 19:23 UTC, tdykstra reviewed
Looks good, I left some suggestions.

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +- Search NuGet.org for packages using the search term "Newtonsoft.Json"
```suggestion
- Search NuGet.org for packages that match the search term "Newtonsoft.Json," and render the output as a table with up to 20 packages:
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +
```suggestion
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +- Search NuGet.org for packages using the search term "Newtonsoft.Json" and render the output as a json.
```suggestion
- Search NuGet.org for packages that match the search term "Newtonsoft.Json," and render the output as json.
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +                },
```suggestion
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +                },
```suggestion
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +                },
```suggestion
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +- Search NuGet.org for packages using the search term "Newtonsoft.Json", show only two results and skip the first packages in the search result
```suggestion
- Search NuGet.org for packages using the search term "Newtonsoft.Json," show only two results, and skip the first packages in the search result:
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +
```suggestion
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +- Search for packages that exactly match "Newtonsoft.Json" and list all available versions of it, ignoring any packages that contain "Newtonsoft.Json" as a part of their name or description but don't
```suggestion
- Search for packages that exactly match "Newtonsoft.Json" and list all available versions of it, ignoring any packages that contain "Newtonsoft.Json" as a part of their name or description but don't match it exactly:
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/dotnet-package-search.md
> +
```suggestion
```

2024-03-13 19:23 UTC, tdykstra commented on docs/core/tools/index.md
> +- [`package search`](dotnet-package-search.md) (Available since .NET 8.02 SDK)
```suggestion
- [`package search`](dotnet-package-search.md) (Available since .NET 8.02xx SDK)
```

2024-03-20 21:11 UTC, tdykstra approved these changes

2024-03-20 21:13 UTC, tdykstra commented
@Nigusu-Allehu is this ready to merge?

2024-03-20 23:34 UTC, donnie-msft approved these changes

2024-03-21 15:33 UTC, Nigusu-Allehu commented
> @Nigusu-Allehu Nigusu Yenework FTE is this ready to merge?

Yes

2024-03-21 15:37 UTC, merged