Clarify that that two empty cancellation tokens are always equal
dotnet/docs pull request #3787
Opened 2017-11-25 19:07 UTC by ohadschn

Addresses https://github.com/dotnet/corefx/issues/495#issuecomment-323999818

2017-11-25 19:42 UTC, jzeferino approved these changes
LGTM.

2017-11-25 22:41 UTC, rpetrusha requested changes
Thanks, @ohadschn, for contributing to the dotnet/docs repo and for noting that two empty cancellation tokens are equal. I've requested that you make two changes to the content that you've added.

2017-11-25 22:41 UTC, rpetrusha commented on xml/System.Threading/CancellationToken.xml
> + You can also use the C#  [default(CancellationToken)](~/docs/csharp/language-reference/keywords/default.md) statement to create an empty (and equivalent) cancellation token. Two empty cancellation t
Could you make the following changes:
1. Please remove "(and equivalent)" from the first sentence. It's unclear what equivalent refers to in the context of the sentence.
2. Please move the second sentence to be an independent paragraph that follows the first paragraph. The second sentence is related to the equality of CancellationTokens, not to the C# default keyword.

2017-11-26 00:19 UTC, ohadschn commented
@rpetrusha thank you, I've made the requested changes.

2017-11-26 20:07 UTC, rpetrusha commented
Thank you so much, @ohadschn, for making the additional change. We'll merge your PR now. Your changes should appear on docs.microsoft.com in the next day or two.

2017-11-26 20:07 UTC, rpetrusha approved these changes

2017-11-26 20:07 UTC, merged