Add UWP as platform that supports .NET Standard
dotnet/docs pull request #3813
Opened 2017-11-28 22:20 UTC by philippgille

https://blogs.msdn.microsoft.com/dotnet/2017/10/10/announcing-uwp-support-for-net-standard-2-0/

2017-11-28 22:30 UTC, philippgille commented
Well, the "Fall Creators Update" constraint isn't even necessary. UWP 10.0 supports .NET Standard 1.0, as seen in [this table](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support). What do you think?

2017-11-28 22:40 UTC, jzeferino reviewed
LGTM. 
Also I recommended to add more platforms see #3814.

2017-11-29 01:04 UTC, mairaw commented on docs/standard/class-libraries.md
> +*   Universal Windows Platform (UWP), Fall Creators Update or newer
should we simply list the version here instead?
Universal Windows Platform (UWP) 10.0 and later versions

@terrajobst?

2017-11-29 21:40 UTC, mairaw requested changes
Thanks @philippgille. Please see my comment regarding how I think we should list UWP here.

2017-12-02 13:37 UTC, philippgille commented
@mairaw: Thanks for the advice. I also thought about @jzeferino's advice. I decided that instead of listing all the platforms with their versions, where the info which .NET Standard version is supported is still missing, a listing with just the platform names *plus* a link to the [.NET Standard versions / .NET platforms versions matrix](https://docs.microsoft.com/en-us/dotnet/standard/net-standard#net-implementation-support) might be best. What do you think?

Also: Should I squash the commits?

2017-12-28 13:48 UTC, philippgille commented
@mairaw: Please see [my previous comment](https://github.com/dotnet/docs/pull/3813#issuecomment-348692601)

2018-02-28 07:22 UTC, mairaw requested changes
Apologies on not getting back to you sooner @philippgille . I lost track of this PR. I left a small comment for you but changes overall look good. Let me know if you'd like me to address the feedback for you.

2018-03-16 18:14 UTC, mairaw approved these changes

2018-03-16 19:02 UTC, merged