Include `sealed` keyword in access modifiers page
dotnet/docs pull request #38326
Opened 2023-11-19 15:09 UTC by BartoszKlonowski

This pull request closes #37453.
It adds the `sealed` keyword to access modifiers page in:
 - [X] listed access modifiers,
 - [ ] summary table,
 - [ ] Class, record, and struct accessibility section,
 - [ ] Class, record, and struct member accessibility section,

2023-11-20 18:03 UTC, BillWagner requested changes
Hi @BartoszKlonowski 

I should have provided more detailed thoughts on how to address this issue. 

I don't think `sealed` should be added to this page. This page is scoped to the *accessibility* of a member or type. Sealed is a bit different: it affects whether a type can be derived from, or if a `virtual` member can be overriden in a derived class.

Instead of trying to add a discussion of `sealed` into this page, I think that linking to the page on [`abstract` and `sealed`](https://learn.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members) would be a better fix.

What do you think?

2023-11-20 18:37 UTC, BartoszKlonowski commented
@BillWagner 
> What do you think?

What you pointed out makes sense now that I think of it, right!
The only question I have is regarding:
> Instead of trying to add a discussion of sealed into this page, I think that linking to the page on [abstract and sealed](https://learn.microsoft.com/dotnet/csharp/programming-guide/classes-and-structs/abstract-and-sealed-classes-and-class-members) would be a better fix.

You commented only on one part of the PR, but as I understand we want to basically revert every change where `sealed` is anyhow described/mentioned, and just link to it somewhere in the page.
If you agree to my understanding, I'll push the changes you described 👍

2023-11-20 18:57 UTC, BillWagner commented
@BartoszKlonowski 

> as I understand we want to basically revert every change where sealed is anyhow described/mentioned, and just link to it somewhere in the page.

Yes, that's what I think is the best fix. Thanks!

2023-11-21 14:15 UTC, BillWagner approved these changes

2023-11-21 14:15 UTC, merged