Add more keywords to F# Guide
dotnet/docs pull request #3843
Opened 2017-11-30 23:41 UTC by cartermp

I'm assuming that these help with SEO for F#.  Is that accurate?

2017-11-30 23:45 UTC, mairaw commented
Not really @cartermp. We're not even recommending adding them anymore. Apparently, Bing used to use them and Google doesn't use them since 2009. We should just remove them all. Title and URL are the biggest contributors to SEO.

2017-12-01 00:05 UTC, cartermp commented
Sounds good.  I'll change wording instead.

2017-12-01 02:03 UTC, mairaw requested changes
Looks great. Left a couple of suggestions for you.

2017-12-01 02:03 UTC, mairaw commented on docs/fsharp/index.md
> +description: Learn about F#, a functional programming language which runs on .NET.
which runs -> that runs or add comma before which

2017-12-01 02:03 UTC, mairaw commented on docs/fsharp/index.md
> +If you know your way around F#, or want to learn more about a specific language construct, you'll find a lot of use in the [Language Reference](language-reference/index.md).  It is a thorough guide o
you'll find a lot of use in the -> see the

It is -> It's

2017-12-01 02:03 UTC, mairaw commented on docs/fsharp/index.md
> +You'll also find a lot of use in the [F# Core Library Reference](https://msdn.microsoft.com/visualfsharpdocs/conceptual/fsharp-core-library-reference) when programming in F#.
This sentence is also super informal. How about telling what they'll find in the reference?

Something like: When programming in F#, the [F# Core Library Reference](https://msdn.microsoft.com/visualfsharpdocs/conceptual/fsharp-core-library-reference)  is a great resource for ...

2017-12-01 02:06 UTC, mairaw commented on docs/fsharp/index.md
>  ms.author: phcart
update ms.date too in this case

2017-12-01 22:49 UTC, mairaw approved these changes
LGTM. :shipit:

2017-12-01 22:50 UTC, merged