Document perfmap settings
dotnet/docs pull request #38538
Opened 2023-12-01 04:01 UTC by tommcdon

Document  DOTNET_PerfMapEnabled  behavior:

DOTNET_PerfMapEnabled | Behavior
-- | --
0 | Disabled
1 | Generate both
2 | Generate only JitDump
3 | Generate only PerfMaps

2023-12-01 17:15 UTC, gewarren requested changes
Can we standardize on perfmaps vs. perf maps vs. PerfMaps?
Also, I think it might be better to compare the formats in a table, e.g.

| Format | Description | Supported on |
| - | - | - |
...

2023-12-02 18:20 UTC, tommcdon commented
cc @davmason @hoyosjs as FYI

2023-12-05 00:51 UTC, gewarren approved these changes

2023-12-05 00:51 UTC, gewarren commented on docs/core/runtime-config/debugging-profiling.md
> +- Enabling perf maps or jit dumps causes a 10-20% overhead. It is recommended to selectively enable either perf maps or jit dumps, but not both to minimize performance impact.
```suggestion
- Enabling perf maps or jit dumps causes a 10-20% overhead. To minimize performance impact, it's recommended to selectively enable either perf maps or jit dumps, but not both.
```

2023-12-05 00:51 UTC, gewarren commented on docs/core/runtime-config/debugging-profiling.md
> +| Format | Description | Supported on |
```suggestion
The following table compares perf maps and jit maps.

| Format | Description | Supported on |
```

2023-12-05 00:51 UTC, gewarren commented on docs/core/runtime-config/debugging-profiling.md
> +| *Perf maps* | Emits `/tmp/perf-<pid>.map` which contains symbolic information for dynamically generated code.<br/>Emits `/tmp/perfinfo-<pid>.map` which includes ReadyToRun (R2R) module symbol infor
```suggestion
| *Perf maps* | Emits `/tmp/perf-<pid>.map`, which contains symbolic information for dynamically generated code.<br/>Emits `/tmp/perfinfo-<pid>.map`, which includes ReadyToRun (R2R) module symbol information and is used by [PerfCollect](../diagnostics/trace-perfcollect-lttng.md). | Perf maps are supported on all Linux kernel versions. |
```

2023-12-05 00:51 UTC, gewarren commented on docs/core/runtime-config/debugging-profiling.md
> +| *Jit dumps* | The jit dump format supercedes perf maps and contains more detailed symbolic information. When enabled, jit dumps will be output to `/tmp/jit-<pid>.dump` files.|Linux kernel versions
```suggestion
| *Jit dumps* | The jit dump format supersedes perf maps and contains more detailed symbolic information. When enabled, jit dumps are output to `/tmp/jit-<pid>.dump` files. | Linux kernel versions 5.4 or higher. |
```

2023-12-05 01:16 UTC, gewarren commented
@tommcdon For next time, it's best to batch the suggestions into a single commit (for docs, the build kicks off on each commit). You can batch them from the Files changed tab.

2023-12-05 01:17 UTC, merged