Adds NUnit test tutorial for .NET Core F#
dotnet/docs pull request #3858
Opened 2017-12-01 20:44 UTC by rprouse

## Summary

The [Getting Started with Testing](https://docs.microsoft.com/en-us/dotnet/core/testing/) page for .NET Core has tutorials for xUnit and MSTest. This adds documentation and a sample project for NUnit in C#. To keep the size of the PRs manageable, I will submit F# and Visual Basic tutorials separately.

See #1785 - Document NUnit in .NET Core Guide > Unit Testing

2017-12-04 20:03 UTC, BillWagner requested changes
Thanks again.

Just a couple small nits.  I've also asked @cartermp to look at the F# to make sure it's idiomatic F#.

Thanks again, and we'll merge this shortly.

2017-12-04 20:03 UTC, BillWagner commented on docs/core/testing/unit-testing-fsharp-with-nunit.md
> + ### Install the NUnit project template
H2

2017-12-04 20:03 UTC, BillWagner commented on docs/core/testing/unit-testing-fsharp-with-nunit.md
> + The NUnit test project templates need to be installed before creating a test project. This only needs to be done once. Run [`dotnet new -i NUnit3.DotNetNew.Template`](../tools/dotnet-new.md) to inst
Let's clarify that this is a per machine install.

2017-12-04 22:32 UTC, cartermp commented on docs/core/testing/unit-testing-fsharp-with-nunit.md
> +    |> Seq.filter isOdd |> Seq.toList
Nit: can we move the `|> Seq.toList` onto a new line?

2017-12-05 19:36 UTC, rprouse commented
@BillWagner updates have been made based on the code reviews and pushed for review.

2017-12-05 19:40 UTC, BillWagner approved these changes

2017-12-05 19:41 UTC, BillWagner commented
Thanks again @rprouse I've approved the changes, and I'll :shipit: as soon as the build finishes.

It will show up on the live site on the next publish cycle.

2017-12-05 19:44 UTC, cartermp approved these changes
Thanks @rprouse!

2017-12-05 22:05 UTC, merged