Adds NUnit test tutorial for .NET Core Visual Basic
dotnet/docs pull request #3859
Opened 2017-12-01 21:11 UTC by rprouse

## Summary

The [Getting Started with Testing](https://docs.microsoft.com/en-us/dotnet/core/testing/) page for .NET Core has tutorials for xUnit and MSTest. This adds documentation and a sample project for NUnit in C#. To keep the size of the PRs manageable, I will submit F# and Visual Basic tutorials separately.

See #1785 - Document NUnit in .NET Core Guide > Unit Testing

2017-12-04 19:59 UTC, BillWagner requested changes
Also really great content. Just a couple quick fixes, and then I'll merge it.

Thanks!

2017-12-04 19:59 UTC, BillWagner commented on docs/core/testing/unit-testing-visual-basic-with-nunit.md
> + ### Install the NUnit project template
H2 instead of H3.

2017-12-04 19:59 UTC, BillWagner commented on docs/core/testing/unit-testing-visual-basic-with-nunit.md
> + The NUnit test project templates need to be installed before creating a test project. This only needs to be done once. Run [`dotnet new -i NUnit3.DotNetNew.Template`](../tools/dotnet-new.md) to inst
Same comment as the C# project: Let's clarify that this is a per machine install.

2017-12-05 19:42 UTC, rprouse commented
@BillWagner suggested changes to installing the project template have been made and this is ready for re-review.

2017-12-05 19:45 UTC, BillWagner approved these changes

2017-12-05 19:46 UTC, BillWagner commented
Thanks again @rprouse 

These are a great addition. I'll :shipit: as soon as the build finishes.

Thanks again. 🎆

2017-12-05 22:05 UTC, merged