Fix tabs so content renders correctly
dotnet/docs pull request #3940
Opened 2017-12-14 20:20 UTC by rpetrusha

# Fix tabs so content renders correctly

## Summary

The tabbed content did not display properly, and there was some content drop-out. This PR attempts to correct it.

## Suggested Reviewers

@BillWagner @mairaw @JRAlexander

2017-12-14 22:48 UTC, mairaw commented
Ah funny, I was just looking at this topic!

2017-12-14 22:52 UTC, mairaw commented on docs/core/tutorials/debugging-with-visual-studio.md
> +---
line 89 - Gauntlet was telling me that the alt text here is too long

2017-12-14 22:52 UTC, mairaw commented on docs/core/tutorials/debugging-with-visual-studio.md
> +title: Debug your Hello World application with Visual Studio 2017
I was thinking of adding some more keywords to this title to help SEO, such as
"Debug your C# or Visual Basic Hello World .NET Core application with Visual Studio 2017"

2017-12-14 22:52 UTC, mairaw commented on docs/core/tutorials/debugging-with-visual-studio.md
>  ms.author: wiwagn
update ms.date?

2017-12-14 22:52 UTC, mairaw commented on docs/core/tutorials/debugging-with-visual-studio.md
>  # [Visual Basic](#tab/visual-basic)
according to the tab spec, it should be vb not visual-basic.

2017-12-14 23:23 UTC, rpetrusha commented
Thanks for adding the internal review URL, @JRAlexander. I forgot again!

2017-12-14 23:31 UTC, rpetrusha commented
I've addressed your comments, @mairaw, and the build from before this commit shows the tabs building correctly.

2017-12-18 23:23 UTC, mairaw requested changes
There's one part of the VB sequence that seems problematic. Other than that, everything looks great.

2017-12-18 23:23 UTC, mairaw commented on docs/core/tutorials/debugging-with-visual-studio.md
>  1. Enter `currentDate = new DateTime(2016,11,01,11,59,00)` in the **Immediate Window** and press the Enter key.
C# and VB are not matching at this point and VB starts numbering again:
![image](https://user-images.githubusercontent.com/12971179/34132967-3d375c64-e407-11e7-8e6d-ce6e1908c121.png)

Seems wrong.

2018-01-05 17:10 UTC, rpetrusha commented
@mairaw, I've fixed the VB renumbering problem.

2018-01-06 05:34 UTC, mairaw commented
Numbering issue is fixed but you still don't have the same content on the VB side (the immediate window screenshot with some info). By design @rpetrusha?

2018-01-08 22:30 UTC, rpetrusha commented
Yes, it's by design, @mairaw. The VB and C# Immediate windows don't behave in the same way.

2018-01-08 23:09 UTC, mairaw approved these changes
LGTM then.

2018-01-09 00:15 UTC, merged