Update text on intellisense
dotnet/docs pull request #39642
Opened 2024-02-22 20:46 UTC by BillWagner

Fixes #38985
Fixes #29186

Other tags in addition to `<summary>` may appear on intellisense, depending on the version of VS and the user's settings. Relax some of the statements on that.

In addition, looked for other issues on this article:

Fixes #32118

Add an example showing how to use the include tag.

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/csharp/language-reference/xmldoc/recommended-tags.md](https://github.com/dotnet/docs/blob/15fe122ed60424b7cd60c98690e04b205abd7268/docs/csharp/language-reference/xmldoc/recommended-tags.md) | [Recommended XML tags for C# documentation comments](https://review.learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags?branch=pr-en-us-39642) |

2024-02-22 21:43 UTC, BillWagner commented
ping @adegeo for review

2024-02-26 18:58 UTC, gewarren requested changes

2024-02-26 18:58 UTC, gewarren commented on docs/csharp/language-reference/xmldoc/recommended-tags.md
> +The .NET Runtime team uses the `<include>` tag extensively in its documentation. You can see many examples by [searching the `dotnet/runtime` repository](https://github.com/search?q=repo%3Adotnet%2Fr
Should this be a TIP block?

2024-02-26 22:02 UTC, BillWagner commented on docs/csharp/language-reference/xmldoc/recommended-tags.md
> +    <param name="p">This is the description of the parameter p of MyMethod. It comes from the included file.</param><summary>This is the summary of MyMethod. It comes from the included file.</summary
typo. I'll fix.

2024-02-26 22:07 UTC, BillWagner commented on docs/csharp/language-reference/xmldoc/recommended-tags.md
> +The .NET Runtime team uses the `<include>` tag extensively in its documentation. You can see many examples by [searching the `dotnet/runtime` repository](https://github.com/search?q=repo%3Adotnet%2Fr
```suggestion
> [!TIP]
> The .NET Runtime team uses the `<include>` tag extensively in its documentation. You can see many examples by [searching the `dotnet/runtime` repository](https://github.com/search?q=repo%3Adotnet%2Fruntime+language%3Acsharp+%3Cinclude+file+&type=code).
```

2024-02-26 22:08 UTC, BillWagner commented
Thanks @gewarren 

I've addressed all your comments.

2024-02-27 00:08 UTC, gewarren approved these changes

2024-02-27 00:08 UTC, merged