Updated links to Assertion in Managed Code docs
dotnet/docs pull request #4007
Opened 2017-12-22 14:56 UTC by jmlane

Pointing to the latest docs.microsoft.com article for [Assertions in Managed Code].

[Assertions in Managed Code]: https://docs.microsoft.com/en-ca/visualstudio/debugger/assertions-in-managed-code

# Title

On the title describe
what you've fixed (or created) with this Pull Request (PR).

## Summary

Insert a short (one or two sentence) summary here.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

Explain your changes, and why you made them. If that
information is already available in the issue referenced
above, just referencing the issue is preferred to copying
the text.

This may not be necessary depending on the scope of the PR 
changes. For example, "fix typo in introduction.md" is
sufficient to describe that PR.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2017-12-22 23:05 UTC, mairaw requested changes
Thanks for replacing these links @jmlane. I just left some feedback on how we usually do those so they work online across all locales and in our offline books too.

2017-12-22 23:05 UTC, mairaw commented on xml/System/Exception.xml
> +     Instead of using exception handling for usage errors, you can use the <xref:System.Diagnostics.Debug.Assert%2A?displayProperty=nameWithType> method to identify usage errors in debug builds, and
change the link from https://docs.microsoft.com/en-ca/visualstudio/debugger/assertions-in-managed-code to just /visualstudio/debugger/assertions-in-managed-code

2017-12-22 23:05 UTC, mairaw commented on xml/System/Exception.xml
> + Throwing or handling an exception consumes a significant amount of system resources and execution time. Throw exceptions only to handle truly extraordinary conditions, not to handle predictable even
same here

2017-12-22 23:06 UTC, mairaw commented
Related to #2037

2018-01-09 01:30 UTC, mairaw approved these changes

2018-01-09 01:33 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4007) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4007) before we can accept your contribution.<br/><br/>:x: jmlane [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4007)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=4007) it.</sub>

2018-01-09 01:38 UTC, mairaw commented
Thanks @jmlane. I've applied the feedback I've left you and also made the same changes to two other topics that had the same link. Once build finishes, we'll merge this PR and the fix should be live tomorrow or so.

2018-01-09 02:20 UTC, mairaw commented
I actually removed the two additional files because it was requiring us to have a CLA. I'll create a separate PR for the two other files.

2018-01-09 04:50 UTC, jmlane commented
Thanks for following up @mairaw. I signed the CLA. If you want to use this or close it in favour of another PR, go right ahead.

2018-01-09 20:30 UTC, mairaw commented
Thanks @jmlane. I've moved the additional changes to #4080 and kept only the original changes here.

As soon as build finishes, I'll merge your PR. Thanks for your contributions to our docs!

2018-01-09 22:21 UTC, merged