Create 04-april-security-and-quality-rollup
dotnet/docs pull request #40374
Opened 2024-04-09 21:17 UTC by TaraOverfield

## 4B
Create 4B Release Notes

2024-04-09 22:54 UTC, salagarw approved these changes

2024-04-09 22:59 UTC, salagarw commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +####ASP.NET
there will be a space here to make it a heading

2024-04-09 23:07 UTC, salagarw commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +####CLR
same here

2024-04-09 23:07 UTC, salagarw commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +####Compilers
and here

2024-04-09 23:11 UTC, salagarw commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +| **Microsoft server operating system, version 22H2 and version 21H2** | **[5037033](https://support.microsoft.com/kb/5037033)** |
will this be for both version 22h2 and 21h2?

2024-04-09 23:14 UTC, salagarw approved these changes

2024-04-10 02:34 UTC, TaraOverfield commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +| **Microsoft server operating system, version 22H2 and version 21H2** | **[5037033](https://support.microsoft.com/kb/5037033)** |
fixed

2024-04-10 02:34 UTC, TaraOverfield reviewed
fixed suggestions

2024-04-10 15:49 UTC, salagarw approved these changes

2024-04-10 19:55 UTC, gewarren reviewed
The new article should also be added to the TOC, and needs YAML frontmatter (metadata).

2024-04-10 19:55 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +## The following tables outline the updates in this release.
```suggestion
## Summary tables

The following tables outline the updates in this release. 
```

2024-04-10 19:55 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +### Quality and Reliability Improvements
```suggestion
### Quality and reliability improvements
```

2024-04-10 19:55 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup
> +## Known Issues in this Release
```suggestion
## Known issues
```

2024-04-12 17:58 UTC, TaraOverfield reviewed
Fixed suggestions

2024-04-12 22:27 UTC, charitys1 approved these changes

2024-04-12 22:30 UTC, charitysnellgrove approved these changes

2024-04-15 18:35 UTC, gewarren requested changes
Can you add the file extension to the file name, and also add it to the table of contents?

2024-04-17 02:34 UTC, TaraOverfield commented
> Can you add the file extension to the file name, and also add it to the table of contents?

I've added the extension.  
For the TOC I think it is already added, can you share where I may have missed this?

2024-04-17 16:29 UTC, gewarren reviewed
I left some more stylistic comments. It's best if you batch them into one commit (or I can do it if you prefer). 

Also, this file is not anchored in a TOC - you can check in the preview: https://review.learn.microsoft.com/en-us/dotnet/framework/release-notes/2024/04-april-security-and-quality-rollup?branch=pr-en-us-40374. This is the TOC file for .NET Framework: https://github.com/dotnet/docs/blob/main/docs/framework/toc.yml

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +This security update addresses a remote code execution vulnerability detailed in [CVE 2024-21409](https://portal.msrc.microsoft.com/en-US/security-guidance/advisory/CVE 2024-21409).
This link doesn't work for me. Should it point here? https://msrc.microsoft.com/update-guide/vulnerability/CVE-2024-21409

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +# April 2024 Security and Quality Rollup
```suggestion
# April 2024 security and quality rollup
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +# April 2024 Security and Quality Rollup
The docs style is to use "Sentence casing" in titles, where only the first word is capitalized.

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +## Summary of What's New in this Release
```suggestion
## Summary of what's new in this release
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +#### CVE-2024-21409 – Remote Code Execution Vulnerability
```suggestion
#### CVE-2024-21409 – Remote code execution vulnerability
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +#### Defense in Depth Vulnerability
```suggestion
#### Defense in depth vulnerability
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +This security update addresses an issue in AIA fetching process.
To avoid duplicate headings, can we combine this with the previous section, perhaps as two bullet points?

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> ++ Addresses an issue with JavaScriptSerializer where after installing the January Security and Quality update there is a performance degradation. (*applies to: .NET Framework 4.6.2, 4.7, 4.7.1,4.7.2,
```suggestion

Addresses an issue with `JavaScriptSerializer` where after installing the January Security and Quality update, there is a performance degradation. (*Applies to: .NET Framework 4.6.2, 4.7, 4.7.1,4.7.2, 4.8, 4.8.1*)
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> ++ Addressed an issue with thread pool recycled lists become unresponsive on multi-CPU-group computers (*applies to: .NET Framework 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 4.8.1*)
```suggestion

Addressed an issue with thread pool recycled lists becoming unresponsive on multi-CPU-group computers (*applies to: .NET Framework 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 4.8.1*).
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> ++ Addresses an issue using the native C# compiler (csc.exe) to compile code making calls to COM interop assemblies. (*applies to: .NET Framework 4.8.1*)
```suggestion

Addresses an issue when the native C# compiler (csc.exe) is used to compile code making calls to COM interop assemblies. (*Applies to: .NET Framework 4.8.1.*)
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +
```suggestion
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +The following tables outline the updates in this release.
```suggestion
The following table outlines the updates in this release.
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +| Product Version | Cumulative Update |
```suggestion
| Product version | Cumulative update |
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +| Product Version | Security and Quality Rollup |
```suggestion
| Product version | Security and quality rollup |
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +The following tables are for earlier Windows and Windows Server versions for Security Only updates which are not cumulative
```suggestion
The following table is for earlier Windows and Windows Server versions for Security Only updates, which aren't cumulative.
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +| Product Version | Security Only Update |
```suggestion
| Product version | Security only update |
```

2024-04-17 16:29 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +The following tables are for earlier Windows and Windows Server versions for Security and Quality Rollup updates.  
```suggestion
The following table is for earlier Windows and Windows Server versions for Security and Quality Rollup updates.  
```

2024-04-17 18:56 UTC, IEvangelist commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> ++ Addresses an issue with JavaScriptSerializer where after installing the January Security and Quality update there is a performance degradation. (*applies to: .NET Framework 4.6.2, 4.7, 4.7.1,4.7.2,
```suggestion
+ Addresses an issue with `JavaScriptSerializer` where after installing the January Security and Quality update there is a performance degradation. (*applies to: .NET Framework 4.6.2, 4.7, 4.7.1,4.7.2, 4.8, 4.8.1*)
```

2024-04-17 18:56 UTC, IEvangelist commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> ++ Addressed an issue with thread pool recycled lists become unresponsive on multi-CPU-group computers (*applies to: .NET Framework 4.6.2, 4.7, 4.7.1, 4.7.2, 4.8, 4.8.1*)
Why not simply say .NET Framework 4.6.2 and newer versions?

2024-04-18 04:04 UTC, gewarren commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +# April 2024 security and quality rollup
```suggestion
---
title: April 2024 security and quality rollup
description: Learn about the improvements in the .NET Framework April 2024 security and quality rollup.
ms.date: 04/17/2024
---
# April 2024 security and quality rollup
```

2024-04-19 03:23 UTC, TaraOverfield commented on docs/framework/release-notes/2024/04-april-security-and-quality-rollup.md
> +This security update addresses an issue in AIA fetching process.
These are two separate security vulnerabilities that are in two different areas of .NET Framework.  Separating them aligns with how the KB articles are published.  Generally, we don't have duplication of the titles like this.  I do want to make sure the content is distinctly different in each fix approach.

2024-04-19 03:24 UTC, TaraOverfield reviewed
4B comments

2024-04-24 17:47 UTC, gewarren approved these changes

2024-04-24 17:59 UTC, merged