Add Examples of Collection Initializers
dotnet/docs pull request #4069
Opened 2018-01-07 06:12 UTC by anonymousgituser

# Add Examples of Collection Initializers

## Summary

1. Added example showing an Add method with multiple parameters and its use with a collection initializer.

2. Added example with Add method using a variable number of parameters along with the use of indexers.

## Details

This change adds two examples to expound upon collection initializers.

The first example demonstrates using multiple parameters in an Add method and how to initialize a collection with multiple entries per item.

In the second example, a variable number of parameters is used with an Add method of a collection. Along with this, the example includes an implementation of an indexer.

## Suggested Reviewers

Current contributors: @mairaw, @svick, @PatrickHofman, @guardrex, @tompratt-AQ, @mjhoffman65, @mikeblome

2018-01-08 16:28 UTC, BillWagner requested changes
Thanks for adding these examples @anonymousgituser We appreciate it.

I had a few comments on the code. We're trying to promote the latest features where appropriate in our examples. I found several locations where expression bodied members would result in simpler code. (To that end, seeing the string interpolation in your samples made me :smile: ).

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/classes-and-structs/object-and-collection-initializers.md
> + Shown in the below example, an object which implements <xref:System.Collections.IEnumerable> containing an `Add` method with multiple parameters allows for collection initializers with multiple elem
For consistency, change "below example" to "following example".

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_7.cs
> +        public FormattedAddresses()
I'd prefer removing the constructor and initializing `internalList` as a field initializer.

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_7.cs
> +        public IEnumerator<string> GetEnumerator()
I'd prefer expression bodied members for both `GetEnumerator()` methods:

```csharp
public IEnumerator<string> GetEnumerator() => internalList.GetEnumerator();
```

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_8.cs
> +        public IEnumerator<KeyValuePair<TKey, List<TValue>>> GetEnumerator()
Here again, I'd prefer expression bodied members.

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_8.cs
> +        public RudimentaryMultiValuedDictionary()
As above, I'd prefer a field initializer and removing the default ctor.

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_8.cs
> +        public List<TValue> this[TKey key]
These could also both be expression bodied members.

2018-01-08 16:28 UTC, BillWagner commented on docs/csharp/programming-guide/arrays/codesnippet/CSharp/object-and-collection-initializers_8.cs
> +        {
Also an expression bodied member.

2018-01-09 01:09 UTC, anonymousgituser commented
@BillWagner,

Changes made.

Thanks for the thorough and positive feedback! 😄

2018-01-09 01:30 UTC, BillWagner approved these changes

2018-01-09 01:31 UTC, BillWagner commented
Thanks for making the updates @anonymousgituser I've approved this PR. 

Once the build finishes, we'll :shipit:.  The changes should show up on the live site in the next couple days, on our regular publish cycle.

Thanks again.

2018-01-09 18:42 UTC, merged