Update parse strings with split
dotnet/docs pull request #4083
Opened 2018-01-09 02:57 UTC by BillWagner

Fixes #3330 

Update samples based on common questions, make samples interactive, and update links.

The referenced sample is now linked in the topic as well.

2018-01-11 22:32 UTC, rpetrusha requested changes
I've left a number of comments, but this looks good, @BillWagner; the C# REPL really helps here.

2018-01-11 22:32 UTC, rpetrusha commented on docs/csharp/how-to/parse-strings-using-split.md
> +multiple separator characters. The following example uses spaces, commas, periods, colons, and tabs, all passed in an array containing these separating characters to <xref:System.String.Split%2A>.  E
comma after "separating characters"
I'm not quite sure what the last sentence means.

2018-01-12 20:59 UTC, BillWagner commented
I addressed all your comments @rpetrusha This is ready to go again.

2018-01-16 22:33 UTC, rpetrusha approved these changes

2018-01-16 22:40 UTC, rpetrusha commented
This looks good, @BillWagner. I'll merge now.

2018-01-16 22:40 UTC, merged