dotnet-trace: document waithandle keyword
dotnet/docs pull request #40852
Opened 2024-05-11 03:06 UTC by verdie-g

This keyword was added for .NET 9+

2024-05-11 15:33 UTC, tommcdon commented
This was added on https://github.com/dotnet/diagnostics/pull/4624 however we haven't shipped the updated version of dotnet-trace containing this change.  @mikem8361 @hoyosjs - we should merge this doc PR after we ship an updated version of the diagnostic tools.

2024-05-11 15:33 UTC, tommcdon requested changes
We should hold on merging this PR until we have shipped an updated version of dotnet-trace

2024-05-28 00:59 UTC, verdie-g commented
@tommcdon I added some documentation for the event so it would appear in https://learn.microsoft.com/en-us/dotnet/fundamentals/diagnostics/runtime-events.

2024-08-01 15:34 UTC, BillWagner commented
ping @tommcdon Is this still waiting, or is it ready?

2024-09-17 02:15 UTC, verdie-g commented
The change was released in https://github.com/dotnet/diagnostics/releases/tag/v8.0.532401

> Add waithandle to clrevents option.

2024-10-16 18:42 UTC, BillWagner commented on docs/fundamentals/diagnostics/runtime-events.md
> +[Wait handle events](runtine-wait-handle-events.md)\
typo:

```suggestion
[Wait handle events](runtime-wait-handle-events.md)\
```

2024-10-16 18:43 UTC, BillWagner commented
@tommcdon 

I looks like this feel through the cracks for final review. You'd marked it as "changes requested". Can you take a look?

2024-10-16 18:50 UTC, BillWagner reviewed
Added markdown lint fixes

2024-10-16 18:50 UTC, BillWagner commented on docs/fundamentals/diagnostics/runtime-events.md
> +These events collect information about wait handles. They help to diagnostic thread pool starvations.
```suggestion
These events collect information about wait handles. They help to diagnostic thread pool starvations.

```

2024-10-16 18:50 UTC, BillWagner commented on docs/fundamentals/diagnostics/runtime-wait-handle-events.md
> +- `Monitor.Wait`
```suggestion

- `Monitor.Wait`
```

2024-10-16 18:50 UTC, BillWagner commented on docs/fundamentals/diagnostics/runtime-wait-handle-events.md
> +|`ClrInstanceID`|`win:UInt16`|Unique ID for the instance of CoreCLR.|
```suggestion
|`ClrInstanceID`|`win:UInt16`|Unique ID for the instance of CoreCLR.|

```

2025-04-22 14:05 UTC, verdie-g commented
@tommcdon could you have have a look at this PR 🙏

2025-04-22 15:17 UTC, tommcdon approved these changes
LGTM thanks!

2025-05-18 04:50 UTC, merged