Update source3.cs
dotnet/docs pull request #4095
Opened 2018-01-10 11:46 UTC by matthewspencerboxuk

# Title

Updated source3.cs to check the array length is zero, instead of checking for null

## Summary

GetCustomAttributes never returns null, but instead returns an empty array when no attributes are found, as outlined here: https://msdn.microsoft.com/en-us/library/ms130871(v=vs.110).aspx. I have updated the docs to check that the array length is zero instead of checking for null.

2018-01-10 19:09 UTC, rpetrusha requested changes
Thanks for correcting this programming error, @matthewspencerboxuk, and for contributing to the dotnet/docs repo. There are also Visual Basic and C++ versions of this example (at samples/snippets/visualbasic/VS_Snippets_CLR/conceptual.attributes.usage/vb/source3.vb and samples/snippets/cpp/VS_Snippets_CLR/conceptual.attributes.usage\cpp/source3.cpp. Could you make this change there as well? We'd also be happy to make the change, If you'd prefer.

2018-01-12 20:26 UTC, Loridawn99 approved these changes

2018-01-15 08:53 UTC, matthewspencerboxuk commented
Hey @rpetrusha, happy to make the VB and C++ changes, will have a look into this later today.

2018-01-22 22:22 UTC, rpetrusha commented
Thanks for making this correction, @matthewspencerboxuk. We'll merge your PR now and open a separate PR to change the Visual Basic and C++ code.

2018-01-22 22:22 UTC, rpetrusha approved these changes

2018-01-22 22:23 UTC, merged