Create custom-configuration.md
dotnet/docs pull request #40967
Opened 2024-05-16 18:55 UTC by mckennabarlow

Adding public documentation for how to provide custom config files to customize AppCAT code analysis

## Summary

Fixes #Issue_Number (if available)

2024-08-01 15:47 UTC, BillWagner commented
ping @alexwolfmsft @CamSoper for review

2024-08-01 22:51 UTC, CamSoper commented
I'll give this a review Friday. Thanks, @mckennabarlow!

2024-08-02 14:17 UTC, CamSoper requested changes
Overall, looks great, @mckennabarlow! I made a few suggestions for readability. I'll also send a PR to this branch to add this doc to the TOC.

2024-08-02 14:17 UTC, CamSoper commented on docs/azure/migration/appcat/custom-configuration.md
> +After analysis is done, run config is stored in the report and re-used if user opens report again and refreshes.
```suggestion
## How to provide a JSON run configuration

### Using the CLI

- **Interactive mode**: The CLI will ask if you want to provide run configuration. Upon selecting *yes*, it prompts the user to type/paste the path to the run configuration file.
- **Non-interactive mode**: Use the `-c|--config` argument. This allows you to provide the path to the JSON run configuration.

### Using Visual Studio

- When editing analysis settings, use the UI to specify JSON run configuration.

After analysis is done, run configuration is stored in the report. The configuration is re-used if the user reopens the report and refreshes.
```

2024-08-02 14:17 UTC, CamSoper commented on docs/azure/migration/appcat/custom-configuration.md
> +- add new analyzers for existing or new rules
```suggestion
Before running an analysis, AppCAT discovers all rules and analyzers provided to it and then uses that information to match current the project's `traits`. However, some results could be too noisy for some applications.

To control/scope rules and/or analyzers used, you can provide a JSON run configuration file. This allows you to:

- Change default settings to include or exclude some binaries.
- Disable existing specific rules or specific analyzers.
- Change properties in existing rules.
- Add new rules.
- Add new analyzers for existing or new rules.
```

2024-08-02 14:17 UTC, CamSoper commented on docs/azure/migration/appcat/custom-configuration.md
> +`Analyzers` section contains analyzers, which similarly to rules could be disabled or new analyzers could be added.
```suggestion
Looking at the JSON objects contained in the preceding example:

- `analysis.settings` contains global includes or excludes. These include and exclude binaries to be analyzed. It's recommended to run binary analysis once to see any red flags, but results for binaries tend to be verbose. Some of the results could flag problems inside dependencies your application is consuming. Other results could be valid problems in your app, but located in unused code paths. These can be ignored to reduce the verbosity of the results.
- `analysis.rules` contains rules definitions. These definitions override or disable existing rules, as well as define new rules.
- `analysis.analyzers` contains analyzers. Similarly to the rules definitions, these can be disabled, overridden, or added on to.
```

2024-08-29 19:51 UTC, CamSoper approved these changes

2024-08-29 19:51 UTC, merged