Add missed documentation for CA's options.
dotnet/docs pull request #41001
Opened 2024-05-18 09:24 UTC by FrediKats

## Summary

File `code-quality-rule-options` does not contain all options of CA rules. I found that https://github.com/dotnet/roslyn-analyzers/blob/main/docs/Analyzer%20Configuration.md describes more options. I add missed part to this repo because documentation for all other rules located here.

2024-05-18 10:00 UTC, FrediKats commented
I rechecked usages of sufficient_IterationCount_for_weak_KDF_algorithm and unsafe_DllImportSearchPath_bits and don't understand what wrong.

@gewarren, can you help with this?

Error:

```
Error: In file 'docs/fundamentals/code-analysis/code-quality-rule-options.md': Invalid link: '#unsafe_DllImportSearchPath_bits'.
Error: In file 'docs/fundamentals/code-analysis/code-quality-rule-options.md': Invalid link: '#sufficient_IterationCount_for_weak_KDF_algorithm'.
```

File content:

```
- [unsafe_DllImportSearchPath_bits](#unsafe_DllImportSearchPath_bits)
- [sufficient_IterationCount_for_weak_KDF_algorithm](#sufficient_IterationCount_for_weak_KDF_algorithm)

...

### unsafe_DllImportSearchPath_bits
### sufficient_IterationCount_for_weak_KDF_algorithm
```

2024-05-19 03:06 UTC, gewarren commented
> I rechecked usages of sufficient_IterationCount_for_weak_KDF_algorithm and unsafe_DllImportSearchPath_bits and don't understand what wrong.
> 
> @gewarren, can you help with this?

@FrediKats I'm pretty sure the bookmark links to those sections need to use lower case letters only.

2024-05-19 08:06 UTC, FrediKats commented
@gewarren, thanks!

2024-05-20 21:36 UTC, gewarren requested changes
@FrediKats A little more feedback, but again, thanks for adding these.

2024-05-20 21:36 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +| Allowed suffixes | List (separated by `\|`) of allowed suffixes. |  | [CA1711](quality-rules/ca1711.md) |
```suggestion
| Specifies allowable suffixes | List (separated by `|`) of allowed suffixes. | None | [CA1711](quality-rules/ca1711.md) |
```

2024-05-20 21:36 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +| Enable platform compatibility analyzer for TFMs <= net5.0 | `true` or `false` | `false` | [CA1416](quality-rules/ca1416.md) |
```suggestion
| Specifies whether to enable analysis for TFMs prior to .NET 5 | `true` or `false` | `false` | [CA1416](quality-rules/ca1416.md) |
```

2024-05-20 21:36 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +Example:
Remove examples.

2024-05-20 21:36 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +| Enumeration methods | Fully qualified names of additional methods enumerating all parameters with IEnumerable type (separated by `\|`). | empty | [CA1851](quality-rules/ca1851.md) |
```suggestion
| Specifies additional custom methods that enumerate an IEnumerable | Fully qualified names of additional methods (separated by `|`). | None | [CA1851](quality-rules/ca1851.md) |
```

2024-05-20 21:36 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +| This option is used to include customized methods like `Select` into the analysis scope. | Fully qualified names of additional methods accepting IEnumerable parameters and return a new IEnumerable
```suggestion
| Specifies additional customized LINQ chain methods (that is, methods take an `IEnumerable` argument and return a new `IEnumerable` instance) | Fully qualified names of additional methods (separated by `|`). | None | [CA1851](quality-rules/ca1851.md) |
```

2024-05-20 21:36 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +| Assume method enumerates parameters | `true` or `false` | `false` | [CA1851](quality-rules/ca1851.md) |
```suggestion
| Specifies whether to assume that customized methods enumerate their `IEnumerable` parameters | `true` or `false` | `false` | [CA1851](quality-rules/ca1851.md) |
```

2024-05-20 21:39 UTC, gewarren commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +For example, consider the below code:
https://github.com/dotnet/docs/issues/41018

2024-05-22 07:43 UTC, FrediKats commented on docs/fundamentals/code-analysis/code-quality-rule-options.md
> +| Points to analysis kind for DFA rules based on PointsToAnalysis | - `None` - PointsToAnalysis is disabled.</br> - `PartialWithoutTrackingFieldsAndProperties` - Partial analysis that does not track
DFA - Data flow analysis. I'm not sure that it's easy to find a list of all rules that use DFA. It's some kind of general option that is not bound to specific rules. I guess we can remove it from the list of CA specific rules.

2024-05-22 07:49 UTC, FrediKats commented
@gewarren , you removed some backslash in your suggestions. But this broke md.

Before:
![image](https://github.com/dotnet/docs/assets/22368203/2f386fc8-ad4d-4064-a694-ee6ab7701992)


After:
![image](https://github.com/dotnet/docs/assets/22368203/bcd9bec6-f0f7-4932-8d3d-cc99d44f8b03)

Markdown parse `|` as column separator even when this symbol located in code block.

2024-05-23 21:22 UTC, gewarren commented
@FrediKats Were you previewing the file in GitHub? Not escaping the pipe character might not render correctly there, but it does on learn.microsoft.com. For example:

[source file](https://github.com/dotnet/docs/blob/2b4d5aff306d2ccc995ed438fa16fead6d122fea/docs/fundamentals/code-analysis/quality-rules/ca1710.md?plain=1#L146)
[rendered page](https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1710#additional-required-suffixes)

2024-06-04 17:53 UTC, gewarren approved these changes

2024-06-04 17:56 UTC, merged