Add SDK documentation for `Microsoft.Testing.Platform`
dotnet/docs pull request #41038
Opened 2024-05-22 07:15 UTC by MarcoRossignoli

2024-05-22 07:35 UTC, MarcoRossignoli commented
@IEvangelist this is good to go

cc: @Evangelink

2024-05-22 07:53 UTC, Evangelink approved these changes

2024-05-22 16:17 UTC, IEvangelist commented
We can't have an article that is a single sentence with a link elsewhere. Instead, just add a TOC entry that links to the desired location.

2024-05-22 16:17 UTC, IEvangelist commented on docs/core/testing/unit-testing-platform-sdk.md
Delete this

2024-05-22 16:17 UTC, IEvangelist commented on docs/navigate/devops-testing/toc.yml
> +            href: ../../core/testing/unit-testing-platform-sdk.md
```suggestion
            href: https://github.com/microsoft/testfx/blob/main/docs/testingplatform/Index.md
```

2024-05-22 16:18 UTC, IEvangelist requested changes
Let's fix this a bit...

2024-05-23 07:14 UTC, Evangelink commented
Done @IEvangelist .

2024-05-24 12:40 UTC, IEvangelist approved these changes

2024-05-24 12:40 UTC, merged