Removed links to Reference Source
dotnet/docs pull request #4136
Opened 2018-01-17 21:14 UTC by pkulikov

Removed all notes containing links to the .NET Framework source code on the [Reference Source](http://referencesource.microsoft.com)

Fixes #4122 

### Suggested Reviewers

@mairaw please review

2018-01-17 21:15 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4136) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4136) before we can accept your contribution.<br/><br/>:x: pkulikov [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4136)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=4136) it.</sub>

2018-01-19 00:19 UTC, mairaw requested changes
This looks great @pkulikov. I was trying to see if we missed any, here are the ones I could find:

- https://github.com/dotnet/docs/blob/master/xml/System.Threading/Thread.xml#L169
- https://github.com/dotnet/docs/blob/master/xml/System.Diagnostics/Process.xml#L46
- https://github.com/dotnet/docs/blob/master/xml/System.Text.RegularExpressions/Regex.xml#L37
- https://github.com/dotnet/docs/blob/master/xml/System.Xml/XmlReader.xml#L45
- https://github.com/dotnet/docs/blob/master/xml/System/Array.xml#L45
- https://github.com/dotnet/docs/blob/master/xml/System/Type.xml#L45

Do you want to take care of those too? Otherwise, we can help you! Thanks.

2018-01-19 07:05 UTC, pkulikov commented
@mairaw thank you for the feedback, I've updated the files you've mentioned and haven't found any more. Please look at the changes in the `Thread.xml` file with more care as that one was not standard (I've found only one link to "#Source" there).

2018-01-23 02:03 UTC, mairaw approved these changes
Thank you for making the additional fixes @pkulikov. I'll merge your changes now and your fix should be live in the  next day or so.

2018-01-23 02:03 UTC, merged