Replaced Codeplex Link for issue #2974
dotnet/docs pull request #4146
Opened 2018-01-18 19:25 UTC by fernandosoto138

# Replaced Codeplex Link

## Summary

Replaced codeplex from de DLR, it was http://go.microsoft.com/fwlink/?LinkId=141028 (redirects to codeplex : http://dlr.codeplex.com/) 

and now : https://github.com/IronLanguages/dlr 

## Suggested Reviewers

@mairaw

2018-01-18 20:06 UTC, mairaw requested changes
Thanks @fernandosoto138 for your contribution. I've left some comments for you to address.

2018-01-18 20:06 UTC, mairaw commented on docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md
> + Like the CLR, the DLR is a part of the .NET Framework and is provided with the .NET Framework and Visual Studio installation packages. The open-source version of the DLR is also available for downlo
[Iron Languages](https://github.com/IronLanguages/dlr) Github -> [IronLanguages/dlr](https://github.com/IronLanguages/dlr) repo on GitHub.

2018-01-18 20:06 UTC, mairaw commented on docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md
> +>  The open-source version of the DLR has all the features of the DLR that is included in Visual Studio and the .NET Framework. It also provides additional support for language implementers. For more
same here

2018-01-18 20:06 UTC, mairaw commented on docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md
>   <xref:System.Dynamic.DynamicObject>
should probably change line 98 to point to https://github.com/IronLanguages/dlr/tree/master/Docs instead of Codeplex as well

2018-01-18 20:19 UTC, fernandosoto138 commented on docs/framework/reflection-and-codedom/dynamic-language-runtime-overview.md
> + Like the CLR, the DLR is a part of the .NET Framework and is provided with the .NET Framework and Visual Studio installation packages. The open-source version of the DLR is also available for downlo
Done!

2018-01-18 20:56 UTC, mairaw approved these changes
Thank you for making the suggested changes. We'll merge your PR as soon as the build finishes successfully.

2018-01-19 01:21 UTC, mairaw commented
I realized I missed the GitHub capitalization when I approved. I made the change and once builds finishes again, I'll merge. Thanks again!

2018-01-19 18:24 UTC, merged