Update documentation for numerous IXCLRData* DAC interfaces, methods, and related structures / enumerations
dotnet/docs pull request #41675
Opened 2024-07-08 23:34 UTC by wmessmer-msft

## Summary

Adds new documentation for various IXCLRData* DAC interfaces, methods, and related structures / enumerations.  Such includes new method documentation for various methods on IXCLRDataProcess, IXCLRDataModule, IXCLRDataMethodInstance, and XCLRDataMethodDefinition.  It also includes new interface descriptions and related method definitions for various parts of IXCLRDataTask, IXCLRDataFrame, IXCLRDataValue, IXCLRDataStackWalk, IXCLRDataTypeInstance, IXCLRDataTypeDefinition, IXCLRDataExceptionState, and the various revisions of IXCLRDataExceptionNotification.  Related enumerations and structures to any newly documented interfaces and methods are also added.

All of this follows the style of the existing IXCLRData* documentation including the warning note that callers should prefer the much better supported DBI (ICorDebug) interfaces.

2024-07-09 08:20 UTC, noahfalk approved these changes

2024-07-09 08:39 UTC, noahfalk commented
Just a heads up @dotnet/docs, these are old debugging APIs that were originally defined for .NET Framework but have long been private. In the past we made a few selected APIs public to aid debugging tools but now we are adding a bunch more to assist some diagnostic tooling partners that wanted to call them. We expect extremely few people to use these APIs (<10 in the world?). Given the very narrow audience that would ever look at these pages and that we expect those folks to already have area expertise we are trying to keep effort on the docs minimal. While we do care about having a basic doc available I expect time spent on editorial improvements will have very low payoff given the tiny audience.

2024-07-09 14:00 UTC, gewarren requested changes
These files at least need to be added to the TOC so they're not orphaned - that file is [here](https://github.com/dotnet/docs/blob/main/docs/framework/unmanaged-api/debugging/toc.yml). Ideally they'd also be added to the overview pages such as https://github.com/dotnet/docs/blob/main/docs/framework/unmanaged-api/debugging/debugging-structures.md for structures.

2024-09-05 04:57 UTC, gewarren approved these changes

2024-09-05 15:27 UTC, merged