Add preferreduilang to F# compiler options table
dotnet/docs pull request #4193
Opened 2018-01-24 05:58 UTC by cartermp

Fixes #4183

2018-01-24 07:22 UTC, Roadkitten approved these changes

2018-01-24 14:59 UTC, BillWagner approved these changes
The change LGTM.  I'll close and reopen to trigger a new build as the OPS build seems stuck.

Once the build is clean, I'll :shipit:

2018-01-24 15:46 UTC, cartermp commented
Hang on - I'll add this to F# Interactive as well

2018-01-24 22:51 UTC, mairaw commented
there are some merge conflicts on the PR @cartermp

2018-01-25 17:21 UTC, mairaw commented on docs/fsharp/language-reference/compiler-options.md
> +|**--preferreduilang:&lt;lang&gt;**| Specifies the preferred output language culture name (e.g. es-ES, ja-JP). |
e.g. -> for example,

2018-01-25 17:22 UTC, mairaw requested changes
some small nits to be fixed

2018-01-25 17:22 UTC, mairaw commented on docs/fsharp/language-reference/fsharp-interactive-options.md
> +|**--preferreduilang:&lt;lang&gt;**| Specifies the preferred output language culture name (e.g. es-ES, ja-JP). |
ditto

2018-01-25 17:22 UTC, mairaw commented on docs/fsharp/tutorials/fsharp-interactive/index.md
> +|[F# Interactive Options](../../language-reference/fsharp-interactive-options.md)|Describes command line syntax and options for the F# Interactive, fsi.exe.|
command line -> command-line

2018-01-25 18:19 UTC, mairaw approved these changes
LGTM. You can merge it when build finishes

2018-01-25 18:21 UTC, cartermp commented
🎉

2018-01-26 06:10 UTC, cartermp commented
öööf that build is taking a while

2018-01-26 06:53 UTC, mairaw commented
The webhook seems to be failing for this PR. Not sure why. I can open a LSI in the morning if the issue persists.

2018-01-26 16:24 UTC, JRAlexander commented
Build still hung. Closing and reopening.

2018-01-26 16:35 UTC, JRAlexander commented
Submitting LSI

2018-01-29 18:03 UTC, merged