Following Naming Convention for Enums
dotnet/docs pull request #4196
Opened 2018-01-24 19:14 UTC by spottedmahn

## Summary

Change the Enum example to use[ the naming convention](https://docs.microsoft.com/en-us/dotnet/standard/design-guidelines/names-of-classes-structs-and-interfaces#naming-enumerations) of:

> DO use a singular type name for an enumeration unless its values are bit fields.

## Details

I made this change because this example violates the recommended naming convention.

2018-01-24 19:31 UTC, rpetrusha requested changes
Thanks for submitting this PR so that the example conforms to our coding guidelines, @spottedmahn! There are still two more occurrences of "Days" in the topic, on lines 55 and 68. Would you mind fixing those as well?

2018-01-24 19:34 UTC, spottedmahn commented
Hi @rpetrusha - done!

2018-01-24 19:59 UTC, rpetrusha approved these changes

2018-01-24 20:00 UTC, rpetrusha commented
Thanks for making the additional changes, @spottedmahn. We'll merge your PR once there's a successful internal build. Your changes should appear on docs.microsoft.com in the next day or two.

2018-01-25 00:08 UTC, merged

2018-01-25 19:56 UTC, spottedmahn commented
Well that didn't work:

![image](https://user-images.githubusercontent.com/14079228/35409352-efb2eeee-01df-11e8-9c01-ab9ab22c5363.png)

Wonder why?