Consolidated XAML fragments
dotnet/docs pull request #4232
Opened 2018-01-27 00:55 UTC by rpetrusha

# Consolidated XAML fragments

## Summary
This PR does the following:
- Replaces multiple XAML blocks with a single block.
- Removes all code snippet tags from the two SimpleBinding XAML files.
- Replaces snippet tags with line line numbers to display select blocks of the XAML file.
- Uses highlighting to focus on a select portion of the large XAML file.

## Note
Since I've used line numbers, which tend to be brittle, and highlighting, which I think is a first in our repo, we should make sure the build reflects the appropriate XAML block and highlighted lines. (I may have used faulty syntax.)

## Suggested Reviewers

@mairaw

2018-01-30 02:28 UTC, mairaw requested changes
This is great @rpetrusha. Left you a couple of comments.

2018-01-30 02:28 UTC, mairaw commented on docs/framework/wpf/data/how-to-control-when-the-textbox-text-updates-the-source.md
> + If you want the source to be updated as you are typing, set the <xref:System.Windows.Data.Binding.UpdateSourceTrigger%2A> of the binding to <xref:System.Windows.Data.UpdateSourceTrigger.PropertyChan
should we indicate the highlighted code when we introduce these samples now? Something like, "In the following example, in the highlighted code, ..."

2018-01-30 02:28 UTC, mairaw commented on docs/framework/wpf/data/how-to-control-when-the-textbox-text-updates-the-source.md
> + [!code-xaml[SimpleBinding#USTHowTo](../../../../samples/snippets/visualbasic/VS_Snippets_Wpf/SimpleBinding/VisualBasic/Page1.xaml?highlight=33-39)]
the original doc showed more lines. also should we just refer to the lines we want here instead of highlighting?

2018-01-30 02:28 UTC, mairaw commented on docs/framework/wpf/data/how-to-create-a-simple-binding.md
>   The following example instantiates the `Person` object with a `PersonName` property value of `Joe`. This is done in the `Resources` section and assigned an `x:Key`.
same here to indicate customers should look in the highlighted section

2018-01-30 02:28 UTC, mairaw commented on docs/framework/wpf/data/how-to-create-a-simple-binding.md
> + [!code-xaml[SimpleBinding#BDO1](../../../../samples/snippets/csharp/VS_Snippets_Wpf/SimpleBinding/CSharp/Page1.xaml#L37-L37)]
given that this is already shown on the snippet above, sould we perhaps remove this reference and add another highlight above with some explanation?

2018-01-30 02:28 UTC, mairaw commented on docs/framework/wpf/data/how-to-make-data-available-for-binding-in-xaml.md
> + [!code-xaml[SimpleBinding#Binding](../../../../samples/snippets/csharp/VS_Snippets_Wpf/SimpleBinding/CSharp/Page1.xaml#L37-L37)]
same here

2018-01-30 02:28 UTC, mairaw commented on xml/System.Windows.Data/Binding.xml
> + [!code-xaml[SimpleBinding](~/samples/snippets/csharp/VS_Snippets_Wpf/SimpleBinding/CSharp/Page1.xaml#L37-L37)]
same here

2018-01-30 02:28 UTC, mairaw commented on xml/System.Windows.Data/ObjectDataProvider.xml
>   The following example shows how to use this property:
add some info about the highlighted section?

2018-01-30 23:12 UTC, rpetrusha commented
Thanks for the thorough review, @mairaw. I've addressed all of your comments.

2018-02-14 03:26 UTC, mairaw approved these changes
Sorry it took me so long to perceive you had made the updates here @rpetrusha. I'm approving this but left some comments and questions for you.

2018-02-14 03:26 UTC, mairaw commented on xml/System.Windows.Data/Binding.xml
> + The highlighted line that contains the `<TextBlock>` elements shows how to bind to the `PersonName` property. As a result, the <xref:System.Windows.Controls.TextBlock> control appears with the value
same here. move above the code sample?

2018-02-16 16:13 UTC, merged