Replaced fwlinks with actual links in csharp/programming-guide/interop/ folder
dotnet/docs pull request #4255
Opened 2018-01-30 20:18 UTC by pkulikov

Replaced fwlinks with actual links in **csharp/programming-guide/interop** folder to progress #3424 
Tried to replace broken links with new links. 
If no substitution were found, just removed the link (Advanced COM Interoperability in interoperability-overview.md file)

## Suggested Reviewers

@mairaw please review

2018-01-30 23:32 UTC, mairaw requested changes
Your change looks great @pkulikov. Thanks for addressing those fwlinks. Left one small comment to be addressed.

2018-01-30 23:32 UTC, mairaw commented on docs/csharp/programming-guide/interop/how-to-use-platform-invoke-to-play-a-wave-file.md
> + [A Closer Look at Platform Invoke](https://docs.microsoft.com/en-us/dotnet/framework/interop/consuming-unmanaged-dll-functions#a-closer-look-at-platform-invoke)
good job finding the replacement here. Let's just do a relative link such as:
consuming-unmanaged-dll-functions.md#a-closer-look-at-platform-invoke

2018-01-31 07:04 UTC, pkulikov commented
@mairaw thanks for feedback and a lesson: I didn't know how to reference not pages but parts of them. I've updated the link to the relative one.

2018-01-31 07:49 UTC, mairaw commented
Cool @pkulikov! Thanks again.

2018-01-31 07:49 UTC, mairaw approved these changes

2018-01-31 07:49 UTC, merged