code and content updates
dotnet/docs pull request #42723
Opened 2024-09-25 18:16 UTC by alexwolfmsft

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/azure/sdk/protocol-convenience-methods.md](https://github.com/dotnet/docs/blob/e3184441fd0f25e8bb57bae481314a165223e4da/docs/azure/sdk/protocol-convenience-methods.md) | [docs/azure/sdk/protocol-convenience-methods](https://review.learn.microsoft.com/en-us/dotnet/azure/sdk/protocol-convenience-methods?branch=pr-en-us-42723) |

2024-09-26 13:57 UTC, scottaddie requested changes

2024-09-26 17:07 UTC, scottaddie commented on docs/azure/sdk/protocol-convenience-methods.md
> +:::code source="snippets/protocol-convenience-methods/SCM/ExceptionHandling/Program.cs" highlight="9-20":::
Thinking about this some more, it's probably best to only highlight the catch blocks in these 2 code samples. That is, after all, what we want the customer to focus on.

2024-09-26 17:07 UTC, scottaddie commented on docs/azure/sdk/protocol-convenience-methods.md
> +- `Azure.Core`-dependent libraries throw a <xref:Azure.RequestFailedException>.
```suggestion
When a service call fails, the service client throws an exception that exposes the HTTP status code and the details of the service response, if available. A `System.ClientModel`-dependent library throws a <xref:System.ClientModel.ClientResultException>, while an `Azure.Core`-dependent library throws a <xref:Azure.RequestFailedException>.
```

2024-09-26 17:28 UTC, scottaddie approved these changes
Looks good to me. Let's wait for Anne to review before merging.

2024-09-30 17:18 UTC, annelo-msft approved these changes

2024-09-30 17:50 UTC, merged