[BULK] - DocuTune remediation - Sensitive terms with GUIDs
dotnet/docs pull request #43126
Opened 2024-10-19 14:11 UTC by meganbradley

Applying sensitive terms with GUID changes as part of Content SFI and outlined in [Overview - Writing content securely - Platform Manual](https://review.learn.microsoft.com/en-us/help/platform/security-reference?branch=main). Changes are part of the Microsoft-wide SFI effort. Point of contact: @CelesteG

DocuTune v1.5.2.0
CorrelationId: [ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db](https://github.com/dotnet/docs/pulls?q=is%3Apr+ac15aa43-4e2b-437f-ab1c-fdd7e79cd4db+)

#docutune

2024-10-19 14:11 UTC, meganbradley commented
#docutune-review

2024-10-20 00:49 UTC, gewarren commented on docs/core/tools/dotnet-new-sdk-templates.md
> +  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `aaaabbbb-0000-cccc-1111-dddd2222eeee`.
This looks like it changes the meaning and is incorrect.

2024-10-21 14:45 UTC, cilwerner requested changes

2024-10-21 14:45 UTC, cilwerner commented on docs/core/tools/dotnet-new-sdk-templates.md
> +  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `aaaabbbb-0000-cccc-1111-dddd2222eeee`.
```suggestion
  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `22222222-2222-2222-2222-222222222222`.
```

2024-10-21 14:45 UTC, cilwerner commented on docs/core/tools/dotnet-new-sdk-templates.md
> +  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `aaaabbbb-0000-cccc-1111-dddd2222eeee`.
```suggestion
  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `22222222-2222-2222-2222-222222222222`.
```

2024-10-21 14:45 UTC, cilwerner commented on docs/core/tools/dotnet-new-sdk-templates.md
> +  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `aaaabbbb-0000-cccc-1111-dddd2222eeee`.
```suggestion
  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `22222222-2222-2222-2222-222222222222`.
```

2024-10-21 14:45 UTC, cilwerner commented on docs/core/tools/dotnet-new-sdk-templates.md
> +  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `aaaabbbb-0000-cccc-1111-dddd2222eeee`.
```suggestion
  The TenantId ID of the directory to connect to. Use with `SingleOrg` authentication. The default value is `22222222-2222-2222-2222-222222222222`.
```

2024-10-21 14:55 UTC, CelesteDG commented
@gewarren - Looks like Chris reverted the changes. Should we just go ahead and close this PR? I've added the GUID 22222222-2222-2222-2222-222222222222 to the allow list since it wasn't nominated and discovered until now.

2024-10-21 14:57 UTC, cilwerner commented
> @gewarren - Looks like Chris reverted the changes. Should we just go ahead and close this PR? I've added the GUID 22222222-2222-2222-2222-222222222222 to the allow list since it wasn't nominated and discovered until now.

Those changes still need to be committed and merged.

2024-10-21 15:00 UTC, CelesteDG commented
PR needs to be closed. I've added the GUID to the allow list.

#please-close

CC @gewarren @meganbradley 
FYI @cilwerner @OwenRichards1

2024-10-21 15:21 UTC, closed without merging