ClientWebSocket not reusable after Abort() is called
dotnet/docs pull request #4342
Opened 2018-02-08 17:56 UTC by rmkerr

# ClientWebSocket not reusable after Abort() is called

## Summary

There was some confusion over whether or not a ClientWebSocket can be reused after Abort() is called. This change adds a line to the method summary stating that the ClientWebSocket cannot be reused. 

## Details

A user ran into this issue and reported it [here](https://github.com/dotnet/corefx/issues/22535).

2018-02-08 20:29 UTC, rpetrusha commented
//cc @davidsh

2018-02-08 20:34 UTC, rpetrusha requested changes
Thanks for contributing to the dotnet/docs repo, @rmkerr, and for adding this additional detail. Your addition, though, would best go in the Remarks section. Also, so that the text can be more easily localized:
- ClientWebSocket should appear as \`ClientWebSocket\`.
- "once aborted" --> "once it is aborted"

2018-02-08 20:34 UTC, davidsh commented
cc: @stephentoub

2018-02-08 20:36 UTC, stephentoub commented on xml/System.Net.WebSockets/ClientWebSocket.xml
> +        <summary>Aborts the connection and cancels any pending IO operations. The ClientWebSocket cannot be reused once aborted.</summary>
As with @rpetrusha, seems like the addition would be better replacing the "To be added." below.

2018-02-08 20:36 UTC, stephentoub approved these changes
Thanks.

2018-02-08 21:01 UTC, davidsh approved these changes

2018-02-08 22:37 UTC, rpetrusha approved these changes

2018-02-08 22:40 UTC, rpetrusha commented
Thanks for making these additional changes, @rmkerr. We'll merge your PR now. Your changes will appear live on docs.microsoft.com in the next day or two.

2018-02-08 22:40 UTC, merged

2018-02-08 22:41 UTC, rmkerr commented
Great, thanks for the review!

2018-02-09 20:57 UTC, jzeferino reviewed
LGTM.