MSTest SDK list extensions per profile
dotnet/docs pull request #43715
Opened 2024-11-22 20:37 UTC by Evangelink

## Summary

Fixes #43710

---

#### Internal previews

| 📄 File | 🔗 Preview link |
|:--|:--|
| [docs/core/testing/unit-testing-mstest-sdk.md](https://github.com/dotnet/docs/blob/91b7124588e5f68142c9a3fb126dbcb5e6974793/docs/core/testing/unit-testing-mstest-sdk.md) | [MSTest SDK overview](https://review.learn.microsoft.com/en-us/dotnet/core/testing/unit-testing-mstest-sdk?branch=pr-en-us-43715) |

2024-11-25 13:09 UTC, nohwnd commented on docs/core/testing/unit-testing-mstest-sdk.md
> +[Fakes](https://www.nuget.org/packages/Microsoft.Testing.Extensions.Fakes) | | | :heavy_check_mark: starting with MSTest.Sdk 3.7.0
```suggestion
[Fakes](https://www.nuget.org/packages/Microsoft.Testing.Extensions.Fakes) | | | :heavy_check_mark: (MSTest.Sdk 3.7.0+)
```

maybe like this?

2024-11-26 09:14 UTC, MarcoRossignoli approved these changes

2024-11-27 00:06 UTC, adegeo requested changes
I cleaned up the table, but the preview of this doesn't really look great. Also, there needs to be an introduction to the table, otherwise it's just kind of plopped there after a code block and it doesn't really make sense.

----
![image](https://github.com/user-attachments/assets/52ccb8c2-0ea2-4113-822f-92d70132b09b)
----

What about listing them in bullets?

* `None` - No extensions are enabled.
* `Default` - Enables the recommended extensions for this version of MSTest.SDK. This is the default when the property isn't set explicitly.

  Enables the following extensions:

  * Code Coverage
  * Trx

* `AllMicrosoft` - Enable all extensions shipped by Microsoft (including extensions with a restrictive license).

  Enables the following extensions:

  * Code Coverage / Crash Dump / Fakes (MSTest.Sdk 3.7.0+)
  * Hang Dump / Hot Reload / Retry
  * Trx

2024-11-27 16:39 UTC, Evangelink commented
@adegeo Thanks for the suggestion, I have reworked it. Please review.

2024-12-02 20:13 UTC, adegeo approved these changes

2024-12-02 20:13 UTC, merged