fix broken links
dotnet/docs pull request #4422
Opened 2018-02-16 00:28 UTC by mairaw

PR #4380 made me look at the links from the topic 
https://docs.microsoft.com/en-us/dotnet/core/docker/intro-net-docker

@JRAlexander @richlander there are other broken links that I don't know where they're supposed to go now. It seems the folder structure changed since then:
![image](https://user-images.githubusercontent.com/12971179/36287959-2323deda-126d-11e8-8ab2-1c3b2865d982.png)

2018-02-16 02:17 UTC, JRAlexander commented
@mairaw - The docker samples are moving. I can take this and coordinate with @richlander

2018-02-16 02:24 UTC, mairaw commented
Sounds good @JRAlexander. So if you agree with my changes, let's merge this one once build finishes and you can take care of the ones when the samples location is well defined.

2018-02-22 04:46 UTC, JRAlexander requested changes
Just one small change.  Otherwise looks great!

2018-02-22 04:46 UTC, JRAlexander commented on docs/core/docker/intro-net-docker.md
> +* [Working with Visual Studio Docker Tools](/aspnet/core/publishing/visual-studio-tools-for-docker/index)
/aspnet/core/publishing/visual-studio-tools-for-docker

2018-02-22 16:31 UTC, JRAlexander approved these changes

2018-02-22 16:32 UTC, JRAlexander commented
Went ahead and made the change and merged after building. Thanks, @mairaw, for the great work!

2018-02-22 16:32 UTC, merged

2018-02-23 07:40 UTC, mairaw commented
Thanks for making the changes for me @JRAlexander.