fix broken links and review topic
dotnet/docs pull request #4432
Opened 2018-02-17 07:15 UTC by mairaw

I was just going to fix some broken links but this topic was very outdated.

2018-02-19 22:11 UTC, KathleenDollard reviewed
Let's patch this a bit and let me discuss this with the MVPs in two weeks. 

The first three forums appear to be archived from 2012, so probably remove. 

There's nothing on I'm a VB since 2010, probably remove

ASP.NET and MSDN are harder as VB programmers need content from those sites, but there isn't much (any?) VB specific content.

2018-02-20 22:53 UTC, rpetrusha requested changes
I've left a number of comments, @mairaw, along with a couple of suggestions for replacement links.

2018-02-20 22:53 UTC, rpetrusha commented on docs/visual-basic/getting-started/additional-resources.md
> +|[DevX Visual Basic Zone](http://www.devx.com/vb)|Provides in-depth technical articles for today's Visual Basic developer.|
Instead of devx, an active VB site is VBForums at http://www.vbforums.com.

2018-02-20 22:53 UTC, rpetrusha commented on docs/visual-basic/getting-started/additional-resources.md
> +|[vb.dotnet.technical](http://go.microsoft.com/fwlink/?LinkId=145986)|Provides a forum for discussion of new features in [!INCLUDE[vbprvb](~/includes/vbprvb-md.md)] in the DevX forums.|
This ultimately redirectly to devx. An alternative link is http://www.vbcity.com, which is an active VB.NET site.

2018-02-21 07:23 UTC, mairaw commented on docs/visual-basic/getting-started/additional-resources.md
> +|[Visual Basic Code Samples](https://code.msdn.microsoft.com/vstudio)|Provides application, web, and data samples in Visual Basic.|
seems to bring very similar results as the first link. I'm removing this one.

2018-02-21 08:35 UTC, mairaw commented
Great suggestions @KathleenDollard and @rpetrusha. Please let me know if it looks good now. We can later edit this a bit more.

2018-02-21 19:04 UTC, rpetrusha approved these changes
There's still one broken link, @mairaw, but otherwise this looks really good. You've done a great job in improving this topic and making it relevant, IMO.

2018-02-21 19:04 UTC, rpetrusha commented on docs/visual-basic/getting-started/additional-resources.md
> +|[Visual Basic documentation samples](https://github.com/dotnet/docs/samples/snippets/visualbasic)|Contains the samples used throughout the Visual Basic and .NET documentation.|
The link is broken; it should be https://github.com/dotnet/docs/tree/master/samples/snippets/visualbasic

2018-02-21 21:47 UTC, merged