Fixed example Snippet and clarified it.
dotnet/docs pull request #4434
Opened 2018-02-17 20:09 UTC by sas41

# Found a possible error in one of the snippets

## Summary

Fixes the 3rd snippet's return type and clarifies the local function's name to emphasize it's status as a local function

## Details

Changed return type of snippet 3 from bool to int, as returned variable was declared as int.

2018-02-17 20:36 UTC, pkulikov commented on docs/csharp/local-functions-vs-lambdas.md
>  The compiler can determine that `Local` definitely assigns `y` when called. Because `Local` is called before the `return` statement, `y` is definitiely
As `Local` is renamed to `LocalFunction` in the example, please update the paragraph after the example as well.

2018-02-20 18:25 UTC, rpetrusha requested changes
Thank you for contributing to the dotnet/docs repo, @sas41, and for clarifying both code and text. I've suggested a change to the paragraph that you modified. Also note the comment from @pkulikov about changing two occurrences of `Local` to `LocalFunction` in the sentence that follows the example.

2018-02-20 18:25 UTC, rpetrusha commented on docs/csharp/local-functions-vs-lambdas.md
> +The analysis that enables the example analysis enables the fourth difference.
Even with your clarification of "that", the meaning of this sentence is unclear. I'd suggest removing it, and changing the next sentence to "Fourth, depending..."

2018-02-21 18:55 UTC, rpetrusha approved these changes

2018-02-21 18:56 UTC, rpetrusha commented
Thank you so much, @sas41, for making the additional change. We'll merge your PR now. Your changes should appear live on docs.microsoft.com in the next day or two.

2018-02-21 18:56 UTC, merged