Remove unused variable
dotnet/docs pull request #4436
Opened 2018-02-19 15:25 UTC by VHellin

Remove unused variable creating confusion: GeometryDrawing myGeometryDrawing = new GeometryDrawing();

# Title

Remove unused variable in code sample

## Summary

Remove unused variable in code sample creating confusion.

Fixes #Issue_Number

>Note: The "Fixes #nnn" syntax in the PR description causes
>GitHub to automatically close the issue when this PR is merged.
> Remove that line if you don't have issues associated with this
> PR. Click on the Guidelines for Contributing link above for details.

## Details

GeometryDrawing myGeometryDrawing = new GeometryDrawing(); Variable never used.

## Suggested Reviewers

If you know who should review this, use '@' to request a review.

2018-02-20 18:11 UTC, rpetrusha requested changes
Thank you for contributing to the dotnet/docs repo and for removing the unused variable from the C# code, @VHellin. An equivalent unused variable is also declared in the Visual Basic code at samples/snippets/visualbasic/VS_Snippets_Wpf/LayoutInformation/VisualBasic/Window1.xaml.vb. Could you also remove it from there, or would you prefer that we do it?

2018-02-21 05:26 UTC, VHellin commented
Hi Ron,
Pull Request 4446 done to adapt the VB snippet.

2018-02-21 18:46 UTC, rpetrusha commented
Thanks, @VHellin, for also modifying the Visual Basic example. We'll merge your PR now. Your changes should appear live on docs.microsoft.com in the next day or two.

2018-02-21 18:46 UTC, rpetrusha approved these changes

2018-02-21 18:46 UTC, merged