Fix false/true error
dotnet/docs pull request #4480
Opened 2018-02-23 17:59 UTC by alexvy86

# Title
Fixed guidance for the ReadOnly property when implementing a custom read-only collection.

## Summary

Changed `false` to `true`.

2018-02-23 21:25 UTC, jzeferino approved these changes
LGTM.

2018-02-23 23:13 UTC, rpetrusha requested changes
Thank you, @alexvy86, for contributing to the dotnet/docs repo and for correcting the incorrect Boolean value. The paragraph has another error, though: the name of the property is IsReadOnly, not ReadOnly. Would you mind changing that as well?

2018-02-23 23:13 UTC, rpetrusha commented on docs/standard/design-guidelines/guidelines-for-collections.md
> + In general, prefer `ReadOnlyCollection<T>`. If it does not meet some requirement (e.g., the collection must not implement `IList`), use a custom collection by implementing `IEnumerable<T>`, `ICollec
The name of the property is actually ICollection\<T\>.IsReadOnly.

2018-02-28 20:58 UTC, rpetrusha commented
Thanks, @alexvy86, for submitting your PR. I've made the additional change for you. Once an internal build completes successfully, we'll merge your PR.

2018-02-28 21:38 UTC, alexvy86 commented
Hey Ron, sorry about the delay, I couldn't go through all my emails in the last couple of days. Thanks for taking care of the additional change!

2018-03-02 17:44 UTC, mairaw commented
Good to merge @rpetrusha?

2018-03-02 18:29 UTC, rpetrusha commented
Yes, this is good to merge, @mairaw. And thanks for the contribution, @alexvy86. We'll merge your PR now. The change should appear on docs.microsoft.com in the next day or two.

2018-03-02 18:29 UTC, rpetrusha approved these changes

2018-03-02 18:29 UTC, merged

2018-03-02 18:56 UTC, alexvy86 commented
Happy to help!