Fixed typos and style in string interpolation sections
dotnet/docs pull request #4491
Opened 2018-02-25 20:20 UTC by pkulikov

Fixed typos ("compile-time" as adjective goes with dash) and style (use present tense instead of future).
Also added links connecting various pages on string interpolation in the documentation.

2018-02-26 19:54 UTC, rpetrusha requested changes
Thanks for making these improvements, @pkulikov. Once again, there are a number of nits that are unrelated to your PR and that I'm hoping you wouldn't mind addressing.

2018-02-26 19:54 UTC, rpetrusha commented on docs/csharp/tutorials/string-interpolation.md
> +With <xref:System.String.Format%2A?displayProperty=nameWithType>, you specify "placeholders" in a string that are replaced by the parameters following the string. For instance:
nit: these are arguments, not parameters.

2018-02-26 19:54 UTC, rpetrusha commented on docs/csharp/tutorials/string-interpolation.md
> +By default, an interpolated string uses the current culture. To use a different culture, you could cast it as `IFormattable`. For instance:
nit: delete "could"

2018-02-26 19:54 UTC, rpetrusha commented on docs/csharp/tutorials/string-interpolation.md
> +In this tutorial, you learned how to use string interpolation features of C# 6. It's basically a more concise way of writing simple `String.Format` statements, with some caveats for more advanced use
nit: delete "of it"

2018-02-26 20:16 UTC, pkulikov commented
@rpetrusha I've addressed your feedback, thank you.

2018-02-27 01:07 UTC, rpetrusha approved these changes

2018-02-27 01:08 UTC, rpetrusha commented
Thanks for making the additional changes, @pkulikov. We'll merge your PR now. The changes should go live today or tomorrow.

2018-02-27 01:08 UTC, merged