Fix absolute URLs
dotnet/docs pull request #4520
Opened 2018-02-28 23:23 UTC by mairaw

Fixes #787 

- Fixed API links that were not using xref
- Fixed links that were going to docs.microsoft.com/dotnet/* insteaf of an .md file

Kept the ones that were being displayed on e-books as-is.

@rpetrusha this includes some of the include files for the migration guide. There were a couple of broken links in there that this will fix.

2018-03-01 18:01 UTC, rpetrusha requested changes
This looks good, @mairaw, and I've incorporated your changes into the microsoft/dotnet repo. The build report shows 8 broken links, but only one broken link causes it; I've indicated it. There are also three changes unrelated to your PR that I'd appreciate it if you could make.

2018-03-01 18:01 UTC, rpetrusha commented on includes/migration-guide/retargeting/jit/new-64-bit-jit-compiler-net-framework-46.md
> +|Suggestion|<strong>Mitigation of known issues</strong> If you encounter the issues listed above, you can address them by doing any of the following:<ul><li>Upgrade to the .NET Framework 4.6.2. The n
Again unrelated to your PR, on the ninth line from the top, could you change the [\<] to [\\\<useLegacyJit>]? The link has dropped out of the build.

2018-03-01 18:01 UTC, rpetrusha commented on includes/migration-guide/retargeting/networking/default-value-servicepointmanagersecurityprotocol.md
> +|Suggestion|This change affects applications that target the .NET Framework 4.7 or later versions.If you prefer to use a defined protocol rather than relying on the system default, you can explicitly
can you make the same change here? [\<runtime>] has again dropped out of the published topic.

2018-03-01 18:01 UTC, rpetrusha commented on includes/migration-guide/retargeting/winforms/accessibility-improvements-windows-forms-controls.md
> +|Suggestion|<strong>How to opt in or out of these changes</strong>In order for the application to benefit from these changes, it must run on the .NET Framework 4.7.1 or later. The application can ben
Broken link: one of the menubar-control-type links doesn't have an .md file extension

2018-03-01 19:05 UTC, mairaw commented
Thanks @rpetrusha. I've addressed your feedback and a couple of other broken links I found. Better to use rich diff to see the changes I think.

2018-03-02 22:18 UTC, rpetrusha approved these changes
LGTM, @mairaw. You can merge when you're ready.

2018-03-02 22:33 UTC, merged