System.Reflection docs for ProcessorArchitecture is misleading
dotnet/docs pull request #4539
Opened 2018-03-02 14:18 UTC by smcl

# System.Reflection docs for ProcessorArchitecture is misleading

## Summary

The documentation for ProcessorArchitecture is slightly misleading. It states that "IA64" indicates Intel 64 bit processors and "AMD64" indicates AMD 64 bit processors. This is _kinda_ true but is quite misleading since:

* IA64 = Intel Itanium only, mostly dead architecture that I imagine few people need to care about
* AMD64 = All modern Intel and AMD processors

No issue raised as it's a two-line wording fix. 

## Details

I have changed the description to make sure that "Itanium" is mentioned in the IA64 summary, and changed the AMD64 wording to reference "x86-64" architecture. I think the IA64 summary is fine, I don't know what the preferred Microsoft wording is for AMD64/x86-64 however.

2018-03-02 23:45 UTC, rpetrusha requested changes
Thanks for updating the documentation, @smcl. The preferred way to refer to ProcessorArchitecture Amd64 is as x64, which could be implemented as a link.

2018-03-02 23:45 UTC, rpetrusha commented on xml/System.Reflection/ProcessorArchitecture.xml
> +        <summary>A 64-bit processor based on the x86-64 architecture.</summary>
The preferred wording is x64 architecture. You could also do this as a link: \[x64 architecture]\(/windows-hardware/drivers/debugger/x64-architecture).

2018-03-12 16:27 UTC, rpetrusha approved these changes
Thanks, @smcl, for submitting the PR. I've made the change that I'd suggested earlier to conform to Microsoft's naming conventions, and we'll merge your PR as soon as a successful internal build completes.

2018-03-12 16:56 UTC, smcl commented
Hi @rpetrusha I'm sorry I missed the earlier notification somehow! Thanks for applying the changes!

2018-03-13 16:22 UTC, rpetrusha commented
You're welcome, @smcl, and thanks for submitting the PR. We'll merge it now. The changes should appear live on docs.microsoft.com in the next day or two.

2018-03-13 16:22 UTC, merged