Change check NotInheritedAttribute
dotnet/docs pull request #4668
Opened 2018-03-15 17:01 UTC by AlexandrTsvetkov

Change check `InheritedAttribute` for classes `BaseB` and `DerivedB` to check `NotInheritedAttribute`

2018-03-15 18:52 UTC, rpetrusha requested changes
Thank you , @AlexandrTsvetkov, for contributing to the dotnet/docs repo and for correcting what I suspect was a copy-and-paste error in the code example.  There's also a Visual Basic example in dotnet/docs/samples/snippets/visualbasic/VS_Snippets_CLR_System/System.AttributeUsageAttribute.Inherited/vb. Would you mind fixing that as well? Or if you prefer, we can make the changes for you.

2018-03-15 22:59 UTC, jzeferino requested changes

2018-03-15 22:59 UTC, jzeferino commented on samples/snippets/csharp/VS_Snippets_CLR_System/System.AttributeUsageAttribute.Inherited/cs/Inherited1.cs
>        MethodInfo memberB = typeB.GetMethod("MethodB");
Would be nice to use `nameof` operator here: `MethodInfo memberB = typeB.GetMethod(nameof(DerivedB.MethodB));`

In line 40, I suggest the same change to `MethodInfo memberA = typeA.GetMethod("MethodA");`

2018-03-19 09:35 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4668) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4668) before we can accept your contribution.<br/><br/>:x: AlexandrTsvetkov [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=4668)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=4668) it.</sub>

2018-03-19 09:47 UTC, AlexandrTsvetkov commented
Thank you for your suggestion @rpetrusha . Unfortunately, I don't use Visual Basic and it will be much more better, if you fix it by yourself.

2018-03-19 14:43 UTC, BillWagner approved these changes
Thanks for fixing this @AlexandrTsvetkov We do appreciate the work.

@rpetrusha I made the VB updates, and also switched the C# code to use interpolated strings.

2018-03-20 17:32 UTC, rpetrusha approved these changes

2018-03-20 17:33 UTC, rpetrusha commented
Thanks again for opening this issue and correcting the C# code, @AlexandrTsvetkov, and thanks for correcting the VB code, @BillWagner. We'll merge your PR now. The changes should appear live on docs.microsoft.com in the next day or two.

2018-03-20 17:33 UTC, merged