remove dead link
dotnet/docs pull request #4713
Opened 2018-03-20 15:37 UTC by jameswelle

## Dead Link

The inside diagnostics tools link is dead.

2018-03-20 15:40 UTC, jameswelle commented
Since [Rico Mariani](https://blogs.msdn.microsoft.com/ricom/) no longer works for Microsoft and his blog is not longer being updated, I would also suggest adding [Vance Morrison](https://blogs.msdn.microsoft.com/vancem/)'s blog to the list.

2018-03-20 16:08 UTC, rpetrusha requested changes
Thanks, @jameswelle, for contributing to the dotnet/docs repo and for removing this dead link. Would you like to add a link to Vance Morrison's blog in this PR? If so, we'll merge after you add it. Otherwise, we'll merge your PR after we hear from you.

2018-03-22 18:43 UTC, rpetrusha commented
Thanks for adding the link to Vance's blog, @jameswelle. The direct link is fine. We'll merge your PR now. Your changes should appear on docs.microsoft.com in the next day or two.

2018-03-22 18:43 UTC, rpetrusha approved these changes

2018-03-22 18:43 UTC, merged