Update how-the-runtime-locates-assemblies.md
dotnet/docs pull request #4759
Opened 2018-03-23 17:45 UTC by daveaglick

## Summary

Replaced reference to `AppDomain.AppendPrivatePath(String)` method with the `AppDomainSetup.PrivateBinPath` property due to the former being marked obsolete for all recent versions of .NET Framework.

2018-03-24 00:06 UTC, rpetrusha requested changes
Thanks, @daveaglick, for contributing to the dotnet/docs repo and for updating this obsolete API information. So that the link text appears with the type name as well as the property name, would you mind adding "?displayProperty=nameWithType" before the closing xref tag?

2018-03-24 00:33 UTC, daveaglick commented
Gotcha, that makes sense. Change committed (on mobile so I couldn’t squash, can do that later if needed or feel free to squash on merge). Thanks!

2018-03-26 16:46 UTC, rpetrusha commented
Thanks, @daveaglick, for making the additional change. We'll merge your PR (and squash on merge) as soon as the build completes successfully. (I made one additional modification -- the %2A cannot follow the nameWithType value).

2018-03-26 16:46 UTC, rpetrusha approved these changes

2018-03-26 16:52 UTC, daveaglick commented
👍 thanks!

2018-03-26 19:32 UTC, merged