ClientCertificates description was wrong
dotnet/docs pull request #4790
Opened 2018-03-27 09:21 UTC by rwatjen

The ClientCertificates property description had text from the MaxResponseHeadersLength property.

## Summary

Updated the summary and value of HttpClientHandler.ClientCertificates

2018-03-27 16:29 UTC, JRAlexander requested changes
Great catch, @rwatjen! A few tweaks and we will be good to go. Thanks!

2018-03-27 16:29 UTC, JRAlexander commented on xml/System.Net.Http/HttpClientHandler.xml
> +        <value>A collection of X.509 certificates to use when presenting client certificates to the server.</value>
See above about working with "ing".  We also usually add the type reference as a link.  How about something like "The \<see cref="T:System.Security.Cryptography.X509Certificates.X509CertificateCollection" /\>  that contains the security certificates associated with this request."?  Again, great catch!

2018-03-28 06:28 UTC, rwatjen commented
Hi @JRAlexander, I've updated with input from your comments. Since the HttpClientHandler can be reused in multiple requests, I haven't used your suggestions directly. I hope this will do :)

2018-04-04 22:36 UTC, JRAlexander commented
@rwatjen, my apologies for the delay! I wanted to check on something with the devs and then was out of office late last week. Your changes are great! In the meantime, the API has been split into a new repo. So we are going to need to open a new PR there and copy your changes, and then close this PR. https://github.com/dotnet/dotnet-api-docs/blob/master/xml/System.Net.Http/HttpClientHandler.xml
  
I've copied your changes here:
Summary - Gets the collection of security certificates that are associated requests to the server.
Value (removed the xref link, unnecessary after all) - The X509CertificateCollection that is presented to the server when performing certificate based client authentication.

After you copy those over, I'll merge straightaway after the build. Please let me know if you have any questions.

2018-04-04 22:37 UTC, JRAlexander approved these changes

2018-04-09 17:51 UTC, JRAlexander commented
@rwatjen, Would you like me to do this? I can definitely if you'd rather. Please let me know asap. Thanks!

2018-04-10 06:30 UTC, rwatjen commented
Hi @JRAlexander, I've created a new PR (https://github.com/dotnet/dotnet-api-docs/pull/37). Sorry for the delay, was busy at work.

2018-04-10 06:30 UTC, closed without merging