Convert links to https (where supported) in docs/standard
dotnet/docs pull request #4892
Opened 2018-04-06 12:11 UTC by ChrisMaddock

## Summary

Relates to #4504. This changes all the links in `docs/standard` to use https - where a) https is supported, and b) the link does not redirect.

As discussed on this issue, I wrote a small tool to do this. The tools, currently a little overkill - but I want to use it for more-involved tasks in future. 

The code can be seen [here](https://github.com/ChrisMaddock/https-checker). There's two classes of interest:

**HttpsChecker**: Takes a link, try's the https variant of it. Success if https returns 200, fails if anything else. This includes broken links, and links that don't support https. It also fails for redirects, as it really wants manual validation that the link is redirecting to an appropriate place - I have different plans to tackle some of the main cases there in future. 😈 

**LinkReplacer**: uses a markdown parser to find all links in `.md` files, and replaces links where an appropriate replacement is found. It uses a full markdown parser, as I wanted to be sure I was only replacing actual links - and not literal links or links in code samples - which may be intentionally http rather than https.

If the docs team are happy with this approach, I'd like to run this over the rest of the repo, in subsequent PRs. 🙂

2018-04-11 16:01 UTC, BillWagner approved these changes
Thanks again @ChrisMaddock This is really useful and thorough.

I'll approve it now. 

Tagging @mairaw to merge.

2018-04-13 06:09 UTC, mairaw requested changes
@ChrisMaddock this looks awesome! Thank you so much! Left two comments for two other URLs that could be replaced as well.

2018-04-13 06:09 UTC, mairaw commented on docs/standard/cross-platform/index.md
> +|Share source code between Windows Phone 8.1 and Windows 8.1 apps|**Shared projects** (Universal Apps template in Visual Studio 2013, Update 2).<br /><br /> -   Currently no Visual Basic support.<br
can you update this http link to be https://blogs.msdn.microsoft.com/visualstudio/2014/04/14/using-visual-studio-to-build-universal-xaml-apps/?

2018-04-13 06:09 UTC, mairaw commented on docs/standard/cross-platform/index.md
>  |Share binaries between apps that target different platforms|**Portable Class Library projects** for code that is platform-agnostic.<br /><br /> -   This approach is typically used for code that impl
another one that can be changed to https if new url is used: https://blogs.msdn.microsoft.com/dsplaisted/2012/08/27/how-to-make-portable-class-libraries-work-for-you/

2018-04-13 12:12 UTC, ChrisMaddock commented
Thanks @mairaw - changes made. 

I had a separate plan to tackle some of the links which could be redirected to a https site at a different URL - I'd done an enhancement to this tool which finds all the links that redirect to `docs.microsoft`, and replaces them with the appropriate relative link. Sounds like we could do the same for `blogs.msdn.microsoft.com`. 😄

2018-04-16 23:34 UTC, mairaw approved these changes
Thank you for addressing my comments @ChrisMaddock. Yes, adding a special case for blogs seems like a great idea.

2018-04-16 23:35 UTC, merged