Revision of string interpolation quickstart
dotnet/docs pull request #4944
Opened 2018-04-14 17:16 UTC by pkulikov

In my journey to fixing #3285 I've revised the string interpolation [quickstart](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/interpolated-strings). The philosophy behind made changes is the following.

First, I use *string interpolation* when referring to the feature and *interpolated string* when talking about a string literal. That looks that folks prefer *string interpolation* term when [searching in Google](https://trends.google.com/trends/explore?q=c%23%20string%20interpolation,c%23%20interpolated%20string). Let's hope those changes will bring the quickstart page to the top of the search results.

Second, [current comments](https://docs.microsoft.com/en-us/dotnet/csharp/quick-starts/interpolated-strings#step-5) under the quickstart show that audience is confused. That's why I've tried to simplify the quickstart, especially its second step.

At last, I've made one more pass on the [feature description itself](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/tokens/interpolated) to make it smoother.

@BillWagner @rpetrusha please review.

2018-04-16 19:38 UTC, BillWagner requested changes
Overall, this is great work @pkulikov.  

I had a few comments. Most are pertaining to dropping the use of an `enum` field in the sample. That's a very useful concept for beginners.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/index.md
> +## [Hello World](hello-world.yml)
Headings should stay sentence cased, not title cased.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/index.md
> +In the [Hello World](hello-world.yml) quickstart, you'll create the most basic
Same: "Hello world" is correct.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/index.md
> +This quickstart assumes that you have finished the [Hello World](hello-world.yml) lesson.
Hello world.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings-local.md
> +Open **Program.cs** in your favourite editor, and replace the line `Console.WriteLine("Hello World!");` with the following code, where you replace `<name>` with your name:
Our standard uses the American spellings (favorite).

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings-local.md
> +      Console.WriteLine($"On {date}, the price of {item} was {price} per item.");
I do like the example that adds the `enum` field value. That's useful for new developers.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings-local.md
> +- If the interpolated expression doesn't evaluate to `null`, typically the `ToString` method of the result type is called. You can test this by updating the implementation of the `Vegetable.ToString`
An additional sentence here describing the default behavior for enum fields would be useful.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings-local.md
> +Console.WriteLine($"On {date:d}, the price of {item} was {price:C2} per item.");
I'd like to revert to the previous sample.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings-local.md
> +      var titles = new Dictionary<string, string>()
Great addition.  😎

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings.yml
> +    var price = 1.99m;
I like the addition of the enum example here.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings.yml
> +    - If the interpolated expression doesn't evaluate to `null`, typically the `ToString` method of the result type is called. You can test this by updating the implementation of the `Vegetable.ToStr
As before, an additional statement about the enum behavior would be helpful.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings.yml
> +    Console.WriteLine($"On {date:d}, the price of {item} was {price:C2} per item.");
As before, I prefer the previous example with the enum field.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/interpolated-strings.yml
> +      };
😎 awesome.

2018-04-16 19:38 UTC, BillWagner commented on docs/csharp/quick-starts/local-environment.md
> +This quickstart assumes that you have finished the [Hello World](hello-world.yml) lesson.
"World" should be lower case.

2018-04-17 06:26 UTC, pkulikov commented
@BillWagner thank you for the feedback, I've addressed all comments.

2018-04-17 13:58 UTC, BillWagner approved these changes

2018-04-17 13:58 UTC, BillWagner commented
Thanks for making the updates @pkulikov It looks great.  I've approved the changes, and I'll :shipit: now.

Thanks again for your continued involvement.

2018-04-17 13:58 UTC, merged

2018-05-14 21:41 UTC, pkulikov commented
@BillWagner thank you very much for [the highlight](https://docs.microsoft.com/en-us/teamblog/release-notes-april-2018#contributor-highlights). 
So far, it's been very cool to work with you and your team (@mairaw @rpetrusha you also rock): your reviews and feedback are always good and welcoming; of course, my favorite one is :shipit: :).