Add missing AppContext Switches in WCF
dotnet/docs pull request #4972
Opened 2018-04-20 00:32 UTC by yujayee

@Lxiamail

2018-04-20 16:39 UTC, Lxiamail commented on docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md
> +|`Switch.System.IdentityModel.Internals`<br/>`IncludeNullExceptionMessageInETWTrace`|Controls whether to throw a NullReferenceException when the exception message is null.|.NET Framework 4.7|
Should it be Switch.System.ServiceModel.Internals.IncludeNullExceptionMessageInETWTrace instead?

2018-04-21 02:40 UTC, rpetrusha requested changes
Thanks for updating the list of supported switches, @yujayee. I've left a number of comments and suggested changes.

2018-04-21 02:40 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md
> +|`Switch.System.ServiceModel.`<br/>`DisableExplicitConnectionCloseHeader`|When using the HTTP transport with a self hosted service, settings this value to true causes WCF to ignore an application add
- This isn't in alphabetical order.
- self hosted --> self-hosted
- settings --> setting 
- true --> \`true\`
- false --> \`false\`
- headers which results in the closing of --> headers, which results in closing

2018-04-21 02:40 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md
> +|`Switch.System.ServiceModel.`<br/>`DontEnableSystemDefaultTlsVersions`|A value of false sets the default configuration to allow the operating system to choose the protocol. A value of true sets the
- This also should be in alphabetical order.
- false --> \`false\`
- true --> \`true\`

2018-04-21 02:40 UTC, rpetrusha commented on docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md
> +|`Switch.System.ServiceModel.Internals`<br/>`IncludeNullExceptionMessageInETWTrace`|Controls whether to throw a NullReferenceException when the exception message is null.|.NET Framework 4.7|
NullReferenceException should be a link: \<xref:System.NullReferenceException>

2018-04-23 16:45 UTC, yujayee commented
@rpetrusha Thank you so much for your suggestions. I've fixed those errors according to your comments.

2018-04-23 17:10 UTC, rpetrusha approved these changes
Thanks, @yujayee, for making the additional changes. I'll merge your PR now.

2018-04-23 17:10 UTC, merged