Update windows-prerequisites.md
dotnet/docs pull request #4977
Opened 2018-04-20 15:50 UTC by Petermarcu

Right now the docs only cover really old versions of Windows. This update is needed on everything below Win10. Switching the link to point to the list for all OS's.

2018-04-20 23:33 UTC, mairaw requested changes
Thanks @Petermarcu. Update looks good but I have a couple of suggestions/questions.

2018-04-20 23:33 UTC, mairaw commented on docs/core/windows-prerequisites.md
> +> *For Windows versions below Windows 10:*
Should we say this like the following instead?
"For Windows 8.1 and earlier versions, or Windows Server 2012 R2 and earlier versions:

2018-04-20 23:33 UTC, mairaw commented on docs/core/windows-prerequisites.md
> +> Make sure that your Windows installation is up-to-date and includes [KB2999226](https://support.microsoft.com/en-us/help/2999226/update-for-universal-c-runtime-in-windows) which can be installed th
do not have this -> don't have this update installed

you will -> you'll 

like this -> like the following:

2018-04-24 23:29 UTC, mairaw approved these changes
@Petermarcu I've made the changes for you. Just please confirm that OS versions are correct. Thx!

2018-04-25 00:26 UTC, Petermarcu reviewed
Lgtm. Thanks!

2018-04-25 03:28 UTC, merged