update config for conceptual versioning
dotnet/docs pull request #5006
Opened 2018-04-23 22:28 UTC by sudeepku

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-04-23 22:29 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=5006) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=5006) before we can accept your contribution.<br/><br/>:x: sudeepku [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=5006)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=5006) it.</sub>

2018-04-24 00:07 UTC, mairaw requested changes
@sudeepku something went wrong with this config. links between the folders no longer work and path doesn't include core any longer. For example, url looks like https://review.docs.microsoft.com/en-us/dotnet/additional-tools/index, when it should be https://review.docs.microsoft.com/en-us/dotnet/core/additional-tools/index. Also, how do we define the default moniker? We don't want to be 1.0 as it seems to be right now.

2018-04-24 03:50 UTC, fenxu commented on docfx.json
> +        "src": "docs/core",
>"src": "docs/core", [](start = 8, length = 19)

Remove this

2018-04-24 03:52 UTC, fenxu commented on docfx.json
> +          "**/*.yml"
And revert his

2018-04-24 04:51 UTC, mairaw approved these changes
Merging so we can test the changes on the local branch instead and queue full builds given these are config changes.

2018-04-24 04:51 UTC, merged