Update nullable-value-types_8.vb
dotnet/docs pull request #5007
Opened 2018-04-23 23:34 UTC by d-dizhevsky

Changed for readability because 'displays 3 * * *' can confuse people

2018-04-24 01:13 UTC, rpetrusha requested changes
Although it's certainly true that the example is confusing, @d-dizhevsky, it is the correct output. The following is the complete example (in the repo, it's been split into two noncompilable fragments):
```
Public Module Example
   Public Sub Main

        ' Variable n is a nullable type, but both m and n have proper values.
        Dim m As Integer = 3
        Dim n? As Integer = 2

        ' The comparison evaluated is 3>2, but compare1 is inferred to be of 
        ' type Boolean?.
        Dim compare1 = m > n
        ' The values summed are 3 and 2, but sum1 is inferred to be of type Integer?.
        Dim sum1 = m + n

        ' The following line displays: 3 * 2 * 5 * True
        Console.WriteLine(m & " * " & n & " * " & sum1 & " * " & compare1)

        ' Change the value of n to Nothing.
        n = Nothing

        Dim compare2 = m > n
        Dim sum2 = m + n

        ' Because the values of n, compare2, and sum2 are all Nothing, the
        ' following line displays 3 * * *
        Console.WriteLine(m & " * " & n & " * " & sum2 & " * " & compare2)
   End Sub
End Module
``` 
The output is:
```
3 *  *  *
```
I agree, though, that this is confusing. What I'd suggest is:
- Replacing string concatenation with string interpolation in the Console.WriteLine method call.
- Use the If() operator to display a string, such as "<null>", if the variable is null. For example:
```
Console.WriteLine($"{m} * {If(n, "<null>")} * {If(sum2, "<null>")} * {If(compare2, "<null>")}")
```

2018-04-24 04:31 UTC, mairaw commented
We should first make the change here to point to the samples repo instead and then make the change there to the code. I'll create a new PR with the location change.

2018-04-24 05:38 UTC, mairaw commented
Created PR #5011 to change the snippet references. Changes to the samples could then be done directly to https://github.com/dotnet/samples/blob/master/snippets/visualbasic/VS_Snippets_VBCSharp/VbVbalrNullableValue/VB/Class1.vb instead @rpetrusha.

2018-04-28 19:51 UTC, rpetrusha commented
Thanks for raising this issue, @d-dizhevsky. I've opened [dotnet/samples#34](https://github.com/dotnet/samples/pull/34) to address the issue. I'll close this PR now.

2018-04-28 19:51 UTC, closed without merging