Composite formatting: fixed processing order description
dotnet/docs pull request #5069
Opened 2018-04-28 23:36 UTC by pkulikov

The step 3c of the [composite formatting processing order](https://docs.microsoft.com/en-us/dotnet/standard/base-types/composite-formatting#processing-order) says:
>For objects of other types, if a composite formatting is called with an `IFormatProvider` argument, its value (including a `null`, if no `IFormatProvider` object is supplied) is passed directly to the `IFormattable.ToString` implementation. Otherwise, a `CultureInfo` object that represents the current thread culture is passed to the `IFormattable.ToString` implementation.

The second sentence is redundant. The first sentence covers two complimentary cases: when an `IFormatProvider` argument is supplied and not supplied. I've moved no-`IFormatProvider` argument case into the corrected second sentence.

I've used the following code to check the actual behavior (if you want to run it, just copy it to https://try.dot.net/):
```csharp
using System;
using System.Globalization;

public class Program
{
  public static void Main()
  {
    CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("en-EN");
    var ghost = new Ghost();
    Console.WriteLine($"I'm a ghost: {ghost:ghost}");
  }

  public class Ghost : IFormattable
  {
    public string ToString(string format, IFormatProvider formatProvider)
    {
      if (format == null) return null;
      if (formatProvider == null) return "not cultural ghost";
      return format.Equals("ghost") ? "~~~" : null;
    }
  }
}
```

Output:
```
I'm a ghost: not cultural ghost
```

[The source code](https://github.com/dotnet/coreclr/blob/2250e2ae2d733934b3aba0a18706a546f9c5fac3/src/mscorlib/shared/System/Text/StringBuilder.cs#L1605) proves that `provider` is just passed to `IFormattable.ToString` method (it's `null` if it is not given to the calling `string.Format` method).

2018-04-29 22:32 UTC, rpetrusha requested changes
Thanks, @pkulikov, for the clarification and correction. There's one issue unrelated to your PR that I'm hoping you can address -- the word "method" has at some point dropped out of the text.

2018-04-29 22:32 UTC, rpetrusha commented on docs/standard/base-types/composite-formatting.md
> +    -   For objects of other types, if a composite formatting is called with an <xref:System.IFormatProvider> argument, its value is passed directly to the <xref:System.IFormattable.ToString%2A?displ
unrelated to your PR: It seems that "method" has at some point dropped out of the text -- this was intended to read "if a composite formatting method is called".

2018-04-30 07:44 UTC, pkulikov commented
@rpetrusha thank you for review and noticing a missing word. I've brought it back.

2018-04-30 15:08 UTC, rpetrusha approved these changes
Thanks, @pkulikov, for making the additional correction. I'll merge your PR now.

2018-04-30 15:08 UTC, merged