L21207:  Code box creating inconsistency
dotnet/docs pull request #5556
Opened 2018-05-23 14:01 UTC by carolinacmoravia

Hello, @mairaw,

Localization team has reported source content issue that causes localized version to have broken format compared to en-us version.  

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.

Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-05-23 14:21 UTC, svick commented on docs/framework/wcf/extending/client-channel-factories-and-channels.md
> +-   The xref:System.ServiceModel.Channels.ChannelListenerBase class implements xref:System.ServiceModel.Channels.IChannelListener. It takes care of basic state management.
I think the right fix here is to remove the ``` `` ```, but keep the angle brackets as they are. Otherwise the `xref`s won't work.

2018-05-23 14:59 UTC, BillWagner requested changes
Thanks for fixing this. 

There's a better choice to fix this issue. Can you make those updates, and then we'll :shipit: it.

2018-05-24 14:04 UTC, carolinacmoravia commented
Hello, @BillWagner and @svick, 
Thanks for your comments. Committed as indicated. Could you review and help to merge, please? 
Thank you.

2018-05-24 14:10 UTC, BillWagner approved these changes

2018-05-24 14:10 UTC, BillWagner commented
Thanks for making the updates @carolinacmoravia 

I've reviewed the updates and I'll :shipit: now.

2018-05-24 14:10 UTC, merged