Clarify which assembly sets up compatibility modes
dotnet/docs pull request #5684
Opened 2018-05-30 16:18 UTC by twsouthwick

Fixes #5075

2018-05-30 16:23 UTC, twsouthwick commented
/cc @mjrousos

2018-05-30 18:55 UTC, svick commented on docs/framework/migration-guide/application-compatibility.md
> +by the entry assembly for the AppDomain that the code is running in.
Would it make sense to add that the assembly in question is usually the executable for the application?

2018-05-31 22:08 UTC, rpetrusha requested changes
Thanks, @twsouthwick; this is a really useful clarification. I left two suggested changes.

2018-05-31 22:08 UTC, rpetrusha commented on docs/framework/migration-guide/application-compatibility.md
> +of an executable, the framework the executable was targeted against is the compatibility
was targeted against --> targets

2018-05-31 22:08 UTC, rpetrusha commented on docs/framework/migration-guide/application-compatibility.md
> +mode all assemblies in that AppDomain will run under.
nit: compatibility mode is a general term that doesn't specify a version. I think I'd rephrase (starting from the current "This compatibility mode..."):

The version of the .NET Framework that an application targets is determined by the target version of the entry assembly for the application domain that the code is running in. All additional assemblies loaded in that application domain target that .NET Framework version.

2018-06-01 01:07 UTC, twsouthwick commented on docs/framework/migration-guide/application-compatibility.md
> +of an executable, the framework the executable was targeted against is the compatibility
fixed

2018-06-01 15:38 UTC, rpetrusha approved these changes
Thanks for making these additional changes, @twsouthwick. This looks really good. I'll merge your PR now.

2018-06-01 15:38 UTC, merged