FwLinks replacement (4)
dotnet/docs pull request #5761
Opened 2018-06-02 00:14 UTC by florinciubotariu

Relates to #3391 and #3426.

I have encountered some pages having a broken forward link for downloading Northwind Database. The files can be found here: https://github.com/dotnet/docs/search?q=LinkID%3D98088&unscoped_q=LinkID%3D98088

How should we approach this problem?

2018-06-04 06:25 UTC, mairaw requested changes
Another set of great changes @florinciubotariu. Left a few comments to be addressed.

2018-06-04 06:51 UTC, mairaw approved these changes
Thank you for making the changes @florinciubotariu!

2018-06-04 06:53 UTC, florinciubotariu commented
@mairaw 
I have edited again the Eric White's site description.

2018-06-04 06:53 UTC, mairaw commented
I just noticed the missing changes. Thanks for making them.

2018-06-04 07:15 UTC, merged

2018-06-05 07:17 UTC, florinciubotariu commented
@mairaw 
Can you give me a direction regarding how to approach the issue with Northwind Database links?

2018-06-05 07:52 UTC, mairaw commented
is it related to this PR @florinciubotariu?

2018-06-05 08:51 UTC, florinciubotariu commented
No, it is not related to this PR. 
I thought it was a good idea to ask here because I have to approach this in order to fix more links.