restored content + other fixes
dotnet/docs pull request #5773
Opened 2018-06-04 03:29 UTC by mairaw

Fixes #5665 

/cc @bradygaster 

Fixes done:
- Restored content missed during migration
- Acrolinx suggestions
- Fixed values for WebSocketTransportUsage

2018-06-04 15:56 UTC, rpetrusha requested changes
This looks good, @mairaw. There's a broken xref, though, and I've left a number of nits and comments,.

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +|<xref:System.ServiceModel.BasicHttpBinding>|[\<basicHttpBinding>](../configure-apps/file-schema/wcf/basichttpbinding.md)|A binding that is suitable for communicating with WS-Basic Profile conformant
nit: hyphen between "Profile" and "conformant"

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +|<xref:System.ServiceModel.WSFederationHttpBinding>|[\<wsFederationHttpBinding>](../configure-apps/file-schema/wcf/wsfederationhttpbinding.md)|A secure and interoperable binding that supports the WS-
There is one too many "that" here. I think "WS-Federation protocol, which enables..."

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +|<xref:System.ServiceModel.BasicHttpContextBinding>|[\<basicHttpContextBinding>](../configure-apps/file-schema/wcf/basichttpcontextbinding.md)|A binding that is suitable for communicating with WS-Bas
Two occurrences of "that" make this sentence hard to parse. Better: "A binding suitable for communicating...that enables..."

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +|<xref:System.ServiceModel.WSHttpContextBinding>|[\<wsHttpContextBinding>](../configure-apps/file-schema/wcf/wshttpcontextbinding.md)|A secure and interoperable binding that is suitable for non-duple
same as previous comment

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +> <xref:System.ServiceModel.NetHttpBinding> is a binding designed for consuming HTTP or WebSocket services and uses binary encoding by default. <xref:System.ServiceModel.NetHttpBinding> detects wheth
- change its behavior --> changes its behavior
- the hyphen between "match" and "it" should be a semicolon.
- the xref is broken; it's \<xref:System.ServiceModel.Channels.WebSocketTransportUsage>. But there's no Allowed value. I think the value is WhenDuplex. See https://docs.microsoft.com/en-us/dotnet/api/system.servicemodel.channels.websockettransportusage?view=netframework-4.7.2.

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +|<xref:System.ServiceModel.NetHttpBinding>|\<netHttpBinding>|A binding designed for consuming HTTP or WebSocket services that uses binary encoding by default.|
This \<netHttpBinding> should be s link. The URL is https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/nethttpbinding.

2018-06-04 15:56 UTC, rpetrusha commented on docs/framework/wcf/system-provided-bindings.md
> +|<xref:System.ServiceModel.NetHttpsBinding>|\<netHttpsBinding>|A secure binding designed for consuming HTTP or WebSocket services that uses binary encoding by default.|
This \<netHttpsBinding> should be a link. The URL is https://docs.microsoft.com/en-us/dotnet/framework/configure-apps/file-schema/wcf/nethttpsbinding.

2018-06-04 19:28 UTC, mconnew approved these changes

2018-06-04 22:28 UTC, mairaw commented
Thanks for your careful review @rpetrusha. I believe I've addressed all your comments.

2018-06-05 15:52 UTC, rpetrusha approved these changes
This looks really good. Thanks for making the additional changes, @mairaw, especially those unrelated to your PR. It's ready to merge.

2018-06-05 17:07 UTC, merged