Added link to ML samples repo
dotnet/docs pull request #5838
Opened 2018-06-06 18:30 UTC by pkulikov

Is it a good idea to add the link to the [ML samples repo}(https://github.com/dotnet/machinelearning-samples) to the docs? If yes, I'll move it to another page in case of the tutorials index isn't perfect place (I've chosen that page because the related issue has been submitted under it).

Related to #5722

2018-06-06 22:08 UTC, mairaw requested changes
It's almost like you read my mind @pkulikov. I was going to suggest the same. 😄 Thank you for adding this. Just left a tiny comment to be addressed.

2018-06-06 22:08 UTC, mairaw commented on docs/machine-learning/tutorials/index.md
> +For more examples that use ML.NET, check the [dotnet/machinelearning-samples GitHub repository](https://github.com/dotnet/machinelearning-samples).
one little nit: I usually like to keep just the repo name as the link as in `[dotnet/machinelearning-samples](https://github.com/dotnet/machinelearning-samples)  GitHub repository`

2018-06-07 05:45 UTC, pkulikov commented
@mairaw I've addressed your comment, thank you for review.

2018-06-07 05:56 UTC, mairaw approved these changes
Thanks for making the changes @pkulikov!

2018-06-07 05:56 UTC, merged