Update tuples.md
dotnet/docs pull request #5858
Opened 2018-06-07 18:05 UTC by vnextcoder

Fix Lifted Conversions Link

## Summary

Describe your changes here.  Fix the Lifted Conversions link

Fixes #Issue_Number (if available) - none

2018-06-07 18:43 UTC, mairaw requested changes
Thank you @vnextcoder! Your PR fixes the issue but the link wasn't following our guidelines for internal links. Can you make the change I suggested?

2018-06-07 18:43 UTC, mairaw commented on docs/csharp/tuples.md
> +There are several rules that make tuple equality tests more convenient. Tuple equality performs [lifted conversions](/dotnet/csharp/language-reference/language-specification/conversions#lifted-conver
That does fix the broken link but would you be so kind to change this to a relative url so the link gets validated during our build process?

/dotnet/csharp/language-reference/language-specification/conversions#lifted-conversion-operators -> ./language-reference/language-specification/conversions.md#lifted-conversion-operators

2018-06-12 07:10 UTC, mairaw approved these changes
Ah, my apologies. Your fix was correct. I forgot that link to the content outside our repo. Thank you @vnextcoder!

2018-06-12 07:10 UTC, merged

2018-06-14 07:42 UTC, vnextcoder commented
Sorry @mairaw , I couldn't see your messages earlier. I hope all fine with the PR and change I suggested.