update `readonly` with new usages in new C# versions.
dotnet/docs pull request #6086
Opened 2018-06-21 19:40 UTC by BillWagner

Fixes #5682 

/cc @fitdev

Relies on dotnet/samples#133

2018-06-21 23:06 UTC, BillWagner commented
closing and reopening to force a build.

2018-06-21 23:15 UTC, BillWagner commented
yet another build.

2018-07-02 19:58 UTC, JRAlexander requested changes
Bill, looks good , except for a few small items.

2018-07-02 19:58 UTC, JRAlexander commented on docs/csharp/language-reference/keywords/readonly.md
> +The preceding example uses readonly auto properties to declare its storage. That instructs the compiler to create `readonly` backing fields for those properties. You could also declare `readonly` fie
Should there be a link to readonly auto properties?

2018-07-02 19:58 UTC, JRAlexander commented on docs/csharp/language-reference/keywords/readonly.md
> +- For an instance field, in the instance constructors of the class that contains the field declaration, or for a static field, in the static constructor of the class that contains the field declarati
This first sentence is kind of awkward. I'm not sure what you are trying to say.

2018-07-02 19:58 UTC, JRAlexander commented on docs/csharp/language-reference/keywords/readonly.md
> +The `readonly` modifier on a `struct` definition declares that the struct is **immutable**. Every instance field of the `struct` must be marked `readonly`, as shown in the following example:
Should immutable be surrounded by "`"?

2018-07-02 20:02 UTC, BillWagner commented on docs/csharp/language-reference/keywords/readonly.md
> +The `readonly` modifier on a `struct` definition declares that the struct is **immutable**. Every instance field of the `struct` must be marked `readonly`, as shown in the following example:
Nope, that's not a keyword.

2018-07-02 21:07 UTC, BillWagner commented
Thanks @JRAlexander 
Changes have been addressed.

2018-07-02 21:12 UTC, JRAlexander approved these changes

2018-07-02 21:12 UTC, JRAlexander commented
LGTM. :shipit: when ready!

2018-07-02 21:33 UTC, merged