Remove bad link
dotnet/docs pull request #6113
Opened 2018-06-25 02:11 UTC by jstallm

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-06-25 15:54 UTC, rpetrusha requested changes
Thanks for contributing to the dotnet/docs repo and for reporting this broken link, @jstallm. However, the link is merely incorrect; the topic does exist. Would you mind replacing the incorrect link with the correct one?

2018-06-25 15:54 UTC, rpetrusha commented on docs/standard/microservices-architecture/multi-container-microservice-net-applications/test-aspnet-core-services-web-apps.md
> -    [*https://docs.microsoft.com/aspnet/core/testing/integration-testing*](/aspnet/core/testing/integration-testing)
The correct link to the topic is /aspnet/core/test/integration-tests

2018-06-25 15:55 UTC, rpetrusha commented
//cc @CESARDELATORRE

2018-07-03 02:40 UTC, mairaw commented
@rpetrusha I've fixed this for @jstallm.

2018-07-03 18:57 UTC, rpetrusha approved these changes

2018-07-03 18:57 UTC, merged