C26886: Misuse of ` character to create codeboxes
dotnet/docs pull request #6200
Opened 2018-06-28 20:03 UTC by v-maudel

Hello, @mairaw ,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
"this bug is affected by a source issue by the ´ character used to create codeboxes"
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.

Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-06-28 21:12 UTC, rpetrusha requested changes
There are still a number of issues with the use of the \` character here, @v-maudel. I've indicated where they need to be addressed in my comments.

2018-06-28 21:12 UTC, rpetrusha commented on docs/framework/wcf/samples/transport-udp.md
>  -   The``<xref:System.ServiceModel.Channels.ChannelManagerBase> class implements <xref:System.ServiceModel.Channels.CommunicationObject> and provides a unified base class for <xref:System.ServiceMode
The \`\` before \<xref:System.ServiceModel.Channels.ChannelManagerBase> should also be removed.

2018-06-28 21:12 UTC, rpetrusha commented on docs/framework/wcf/samples/transport-udp.md
> +-   The `<xref:System.ServiceModel.Channels.ChannelFactoryBase>` class implements `<xref:System.ServiceModel.Channels.ChannelManagerBase>` and `<xref:System.ServiceModel.Channels.IChannelFactory>` an
The fix here is to remove \`\`, not to replace it with a single \`. This should be, "The \<xref:System.ServiceModel.Channels.ChannelFactoryBase> class implements \<xref:..."

2018-06-28 21:12 UTC, rpetrusha commented on docs/framework/wcf/samples/transport-udp.md
> + The `UdpChannelListener` that the sample implements derives from the `<xref:System.ServiceModel.Channels.ChannelListenerBase>` class. It uses a single UDP socket to receive datagrams. The `OnOpen` m
\` and \` should be removed from \<xref:System.ServiceModel.Channgels.ChannelListenerBase>

2018-06-28 21:12 UTC, rpetrusha commented on docs/framework/wcf/samples/transport-udp.md
> + Because the same datagram channel represents messages that arrive from a number of sources, the `UdpChannelListener` is a singleton listener. There is, at most, one active `<xref:System.ServiceModel
remove \` and \` from \<xref:System.ServiceModel.Channels.IChannel>

2018-06-28 22:21 UTC, mairaw commented
@rpetrusha I took care of your comments to speed up the process.

2018-06-28 22:44 UTC, rpetrusha approved these changes
I should have thought to do it myself, @mairaw. This looks good, so I'll merge.

2018-06-28 22:44 UTC, merged

2018-06-29 13:08 UTC, v-maudel commented
Thanks both @rpetrusha and @mairaw .