Fix "whitespace" words - docs/framework
dotnet/docs pull request #6386
Opened 2018-07-10 05:48 UTC by lucasnobredev

## Fix "whitespace" words - docs/framework

This PR came out from this [issue](https://github.com/dotnet/docs/issues/4439). It's the third PR and it's all about docs/framework.

## Brief explanation
We should use **white-space** for adjectives and **white space** for nouns.

## Suggested Reviewers
@mairaw @rpetrusha @wstaelens

2018-07-10 19:15 UTC, rpetrusha requested changes
Thank you so much, @lucasnobredev, for continuing your work on correcting the use of white-space and whitespace; we really appreciate it. I've noted a number of cases where "white space" should be "white space" and also noted some changes that I'd appreciate your making, even though they're unrelated to your PR. I also changed some formatting problems introduced by our migration from our old authoring system to GitHub.

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xaml-related-clr-attributes-for-custom-types-and-libraries.md
> + <xref:System.Windows.Markup.WhitespaceSignificantCollectionAttribute> indicates that a collection type should be processed as white-space significant by a XAML processor, which influences the constr
White space Processing --> White-space processing

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> +|(nonbreaking space)|&\#160; (assuming UTF-8 encoding)|For flow document elements, or elements that take text such as the WPF <xref:System.Windows.Controls.TextBox>, nonbreaking spaces are not normal
White space Processing --> White-space processing

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-character-entities-and-xaml.md
> + [White space Processing in XAML](../../../docs/framework/xaml-services/whitespace-processing-in-xaml.md)
White space Processing --> White-space processing

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-space-handling-in-xaml.md
> +  - "XAML [XAML Services], white space processing"
white space --> white-space

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-space-handling-in-xaml.md
> +  - "white space processing [XAML Services]"
white space --> white-space

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-space-handling-in-xaml.md
> +The `xml:space` attribute is an XML-defined attribute that declares the significant white space processing behavior within an object element. This behavior is relevant for all content (inner text) co
white space processing --> white-space processing

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-space-handling-in-xaml.md
> + The default value of the `xml:space` attribute is the literal value `"default"`. For the value `"default"`, or if `xml:space` is not indicated at all, the behavior of significant white space parsing
white space parsing --> white-space parsing
White space Processing --> White space processing

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-space-handling-in-xaml.md
> + For a complete discussion of white space processing in XAML, see [White space Processing in XAML](../../../docs/framework/xaml-services/whitespace-processing-in-xaml.md).
white space processing --> white-space processing
in the title: White space Processing --> White-space processing

2018-07-10 19:15 UTC, rpetrusha commented on docs/framework/xaml-services/xml-space-handling-in-xaml.md
> + [White space Processing in XAML](../../../docs/framework/xaml-services/whitespace-processing-in-xaml.md)
White space Processing --> White-space processing

2018-07-11 00:50 UTC, lucasnobredev commented
Done!

2018-07-11 18:54 UTC, rpetrusha approved these changes
Thanks for making the additional changes, @lucasnobredev, and thanks for your commitment to this project. I've made a few additional changes. This is now ready to merge. Changes should go live on docs.microsoft.com in the next day or two.

2018-07-11 18:54 UTC, merged