Introduce net-standard-table more accurately
dotnet/docs pull request #6440
Opened 2018-07-13 08:19 UTC by rocifier

## Summary

It was realised that some people not only miss the bullet points below the net-standard-table, but that the table was inaccurately introduced. Making the introduction to the table more verbose by pre-emptively projecting the purpose of the table to the reader and anticipating their confusion with missing data will help align their thoughts more clearly and free them to interpret the table using their own method or the guides below the table.

Fixes #6022

2018-07-13 12:44 UTC, svick commented on docs/standard/net-standard.md
> +The following table lists the minimum platform versions required when targeting each .NET Standard version.
I think it's not clear what "required" means here.

I would say something like:

> The following table lists the minimum platform versions that support each .NET Standard version.

2018-07-13 15:01 UTC, rpetrusha requested changes
Thank you for contributing to the dotnet/docs repo, @rocifier, and for adding clarity to this introductory sentence. I agree with @svick, though, that  "that support" is clearer. Could you make that change?

2018-07-14 09:43 UTC, rocifier commented
Hi, I have made the recommended change, thanks.

2018-07-16 17:15 UTC, rpetrusha approved these changes
Thanks, @rocifier, for making the additional changes. We'll merge your PR now. your changes should appear live on docs.microsoft.com in the next day or two.

2018-07-16 17:15 UTC, merged