Fix XML syntax errors in schemaImporterExtensions docs
dotnet/docs pull request #6596
Opened 2018-07-21 16:01 UTC by louistio

## Summary

- Fix `SchemaImporterExtension` -> `schemaImporterExtensions`
- Fix missing '<' in `system.xml.serialization` closing tag
- Fix serializaiton -> serialization
- Fix `sxml` -> `xml`

2018-07-23 00:10 UTC, rpetrusha commented
Thanks, @louistio, for spotting this error. There is, though, one more inconsistency: the **Child Elements** section lists the name of this element as \<xmlSchemaImporterExtensions>, as does the article for the [\<add> Element>](https://docs.microsoft.com/en-us/dotnet/standard/serialization/add-element-for-xmlschemaimporterextensions). @ViktorHofer, can you confirm that the name of the element is \<schemaImporterExtensions> rather than \<xmlSchemaImporterExtensions>?

2018-07-23 00:16 UTC, louistio commented
@rpetrusha Good observation! I'll wait on the answer and make the changes accordingly in this PR.

2018-07-23 14:17 UTC, BillWagner submitted a review, later dismissed
Thanks for spotting this and fixing it @louistio We appreciate it.

I've reviewed the changes, and I'll :shipit: now.  

Thanks again for contributing to docs!

2018-07-23 20:22 UTC, ViktorHofer commented
Sorry not my area but fortunately I know the owners ;) @krwq, @pjanotti

2018-07-23 22:51 UTC, pjanotti commented
This is actually related to xml serialization and related tools. @huanwu, @Lxiamail, and @zhenlan are in a better position to answer @rpetrusha question.

2018-08-01 17:20 UTC, rpetrusha commented
I apologize for the delay in getting back to you, @louistio. It turns out that both `<schemaImporterExtensions>` and `<xmlSchemaImporterExtensions>` are supported. However, we should standardize on one variant consistently in the documentation. Could you change line 25 so that it reads "\<schemaImporterExtensions>" instead of "\<xmlSchemaImporterExtensions>"? Also, could you modify the [\<add> Element for \<xmlSchemaImporterExtensions>](https://github.com/dotnet/docs/blob/master/docs/standard/serialization/add-element-for-xmlschemaimporterextensions.md) so that "\<schemaImporterExtensions>" replaces "\<xmlSchemaImporterExtensions>" and "\<XmlSchemaImporterExtensions>" throughout the document?  It's not necessary to rename the file. If you prefer, you could also just make the additional change to the single file in this PR, and we could modify the **\<add> Element for \<xmlSchemaImporterExtensions>** article.

2018-08-01 17:21 UTC, rpetrusha requested changes
See my previous comment for requested changes, @louistio.

2018-08-01 21:34 UTC, louistio commented
Hey @rpetrusha, thank you for the clarification, I also agree the docs should standardize on one variant, which is not the case currently. Would you mind if I make these additional changes in another PR as I feel they are distinct from this PR that aims to specifically correct xml syntax errors?

2018-08-02 01:02 UTC, rpetrusha commented
No, that's fine, @louistio.

2018-08-02 21:57 UTC, louistio commented
Hey @rpetrusha, I disagree as I see both as separate changes and would prefer they are done as two different PRs, it makes more sense for the git history, rather than bundling them together. I created a PR for the consistency issue over at #6807, please tell me what you think.

2018-08-02 22:08 UTC, rpetrusha commented
Thanks, @louistio. If you'd like to do them as separate PRs, that's fine. It probably makes the most sense to merge them together, though, so I'll approve this one but won't merge until #6807 is approved.

2018-08-02 22:09 UTC, rpetrusha approved these changes

2018-08-02 22:36 UTC, rpetrusha commented
On second thought, there's no good reason not to merge this now, @louistio. It should be live on docs.microsoft.com tomorrow.

2018-08-02 22:36 UTC, merged