Note value for .NET 4.6.2 on Win10 1607 is also for Server 2016
dotnet/docs pull request #6678
Opened 2018-07-26 12:48 UTC by psychonic

## Summary

Clarify that the value for .NET Framework version 4.6.2 on Windows 10 Anniversary Update is also the value for Windows Server 2016 (which is otherwise unlisted).

2018-07-26 16:08 UTC, rpetrusha commented
//cc @vivmishra

2018-07-27 19:41 UTC, rpetrusha requested changes
Thank you, @psychonic, for contributing to the dotnet/docs repo and for correcting a major oversight in the documentation. Would you mind making one more change? Line 139 currently reads:
`|.NET Framework 4.6.2 installed on Windows 10 Anniversary Update|394802|`
Could you change it to:
`|.NET Framework 4.6.2 installed on Windows 10 Anniversary Update and Windows Server 2016|394802|`
Once that change is made, I'll merge your PR.

2018-07-27 20:02 UTC, psychonic commented
@rpetrusha Good catch! Thanks.

I've updated it there as well.

2018-07-27 20:20 UTC, rpetrusha approved these changes
Thanks, @psychonic, for making the additional change. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

2018-07-27 20:20 UTC, merged