Removed how to use thread pool topics
dotnet/docs pull request #6739
Opened 2018-07-30 20:30 UTC by pkulikov

Per [discussion](https://github.com/dotnet/docs/issues/6180#issuecomment-407232277) in #6180 and since PRs dotnet/samples#206 and dotnet/dotnet-api-docs#389 are merged, this PR removes "How to use a thread pool" topics from the conceptual docs and redirects to the [ThreadPool.QueueUserWorkItem](https://docs.microsoft.com/en-us/dotnet/api/system.threading.threadpool.queueuserworkitem?view=netframework-4.7.2) API page.

Contributes to #6180

2018-07-30 20:48 UTC, jzeferino approved these changes
LGTM, the link is working.

2018-07-30 23:29 UTC, rpetrusha requested changes
This looks really good, @pkulikov. Thanks for doing this work. I've left two comments and suggested changes that are unrelated to your PR.

2018-07-30 23:29 UTC, rpetrusha commented on docs/standard/threading/the-managed-thread-pool.md
> + Beginning with the .NET Framework 4, the easiest way to use the thread pool is to use the [Task Parallel Library (TPL)](../parallel-programming/task-parallel-library-tpl.md). By default, parallel li
nit unrelated to your PR: I wouldn't describe the TPL as "parallel library types"; I think I would change this to "TPL types like..."

2018-07-30 23:29 UTC, rpetrusha commented on docs/standard/threading/the-managed-thread-pool.md
> +You can also use the thread pool by calling <xref:System.Threading.ThreadPool.QueueUserWorkItem%2A?displayProperty=nameWithType> from managed code (or `CorQueueUserWorkItem` from unmanaged code) and
again unrelated to your PR: CoreQueueUserWorkItem should be described as ICorThreadpool::CorQueueUserWorkItem and can be a link (../../framework/unmanaged-api/hosting/icorthreadpool-corqueueuserworkitem-method.md)

2018-07-31 15:55 UTC, pkulikov commented
@rpetrusha thank you for review; I've addressed both of your comments.

2018-07-31 17:33 UTC, rpetrusha approved these changes
Thanks, @pkulikov, for all the work you've put into streamlining the docs, and also for making the additional set of changes. I'll merge your PR now.

2018-07-31 17:33 UTC, merged