Promote VB What's new
dotnet/docs pull request #6765
Opened 2018-07-31 22:03 UTC by rpetrusha

## Promoted VB What's new

This PR moves the VB What's new topic up one level in the TOC to make it more discoverable.

//cc @KathleenDollard

2018-07-31 22:44 UTC, KathleenDollard commented
👍

2018-07-31 22:51 UTC, JRAlexander requested changes
Looks good, @rpetrusha, except for the headings. They should only have the first word capitalized.

2018-07-31 22:51 UTC, JRAlexander commented on docs/visual-basic/getting-started/whats-new.md
> +**Smarter Fully-qualified Name Resolution**
Headings should be sentence-case.

2018-07-31 22:51 UTC, JRAlexander commented on docs/visual-basic/getting-started/whats-new.md
> + **Year-first Date Literals**
Heading.

2018-07-31 22:51 UTC, JRAlexander commented on docs/visual-basic/getting-started/whats-new.md
> + **Readonly Interface Properties**
Heading here.

2018-07-31 22:51 UTC, JRAlexander commented on docs/visual-basic/getting-started/whats-new.md
> + **XML Doc-comment Improvements**
Heading here.

2018-07-31 22:51 UTC, JRAlexander commented on docs/visual-basic/getting-started/whats-new.md
> + **CObj Allowed in Attributes Arguments**
Heading here

2018-07-31 22:51 UTC, JRAlexander commented on docs/visual-basic/getting-started/whats-new.md
> + **Declaring and Consuming Ambiguous Methods from Different Interfaces**
Heading here.

2018-08-01 18:30 UTC, rpetrusha commented
I've addressed your comments, @JRAlexander, if you'd like to take a look again.
@davkean, I've added Visual Studio versions for the last Visual Basic releases.
@KathleenDollard, you might want to take a look at the latest changes.

2018-08-01 19:32 UTC, JRAlexander approved these changes

2018-08-01 19:32 UTC, JRAlexander commented
LGTM, @rpetrusha!

2018-08-02 00:33 UTC, merged