Use <schemaImporterExtensions> instead of <xmlSchemaImporterExtensions>
dotnet/docs pull request #6807
Opened 2018-08-02 21:56 UTC by louistio

Both are supported but the usage inconsistency was brought up by @rpetrusha in #6596, and suggested we standardize one variant in the docs.

2018-08-02 22:12 UTC, pkulikov commented on docs/standard/serialization/add-element-for-schemaimporterextensions.md
> +title: "&lt;add&gt; Element for &lt;schemaImporterExtensions&gt;"
@louistio as the file is renamed, please update the json file with redirections:
https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json

Things to remember:
- `source_path` ends with the file extension ".md"
- `redirect_url` starts with `/`, no file extension; this bit is appended to the docs.microsoft.com

2018-08-02 22:17 UTC, rpetrusha requested changes
This looks really good, @louistio. Thanks for doing this additional work. It wasn't completely necessary to rename the add-element-for-xmlschemaimporterextensions.md file, But since you have, we also have to redirect from the old file to the new. That's done in https://github.com/dotnet/docs/blob/master/.openpublishing.redirection.json. Entries are supposed to be alphabetically in source URL order. Could you add the old URL of the add-... element to it?

2018-08-02 22:37 UTC, louistio commented
@rpetrusha @pkulikov Thanks, I was not aware of this. I added a redirect, I think I've done it correctly.

2018-08-03 15:09 UTC, rpetrusha approved these changes
Thank you, @louistio, for the work you've done in making the documentation consistent. The redirection looks good, so I'll merge your PR now. Your changes should be appear on the live site in the next day or two.

2018-08-03 15:09 UTC, merged