fix two typos in misc constructs in regex
dotnet/docs pull request #6841
Opened 2018-08-05 11:04 UTC by herohua

## Summary

Fix two typos in misc constructs in regex.

2018-08-06 00:02 UTC, rpetrusha commented on docs/standard/base-types/miscellaneous-constructs-in-regular-expressions.md
> -|`(?# case-sensitive comparison)`|A comment. It does not affect pattern-matching behavior.|
The original line is correct. The comment in the regex (and in the element-by-element description of the regex pattern) should have been "case-sensitive comparison".

2018-08-06 00:07 UTC, rpetrusha requested changes
Thanks for continuing to correct additional errors, omissions, and typos in the regex documentation, @herohua. Here, though, case-sensitive and case-insensitive (with a hyphen) is correct. Instead of changing the text here, the source code at samples/snippets/csharp/VS_Snippets_CLR/regularexpressions.language.miscellaneous/cs/miscellaneous2.cs#2 and samples/snippets/visualbasic/VS_Snippets_CLR/regularexpressions.language.miscellaneous/vb/miscellaneous2.vb#2 should be modified to include a hyphen after "case".    
Please let us know whether you'd like to make that change, or whether you'd like for us to make it.

2018-08-06 00:07 UTC, rpetrusha commented on docs/standard/base-types/miscellaneous-constructs-in-regular-expressions.md
> -|`(?#case-insensitive comparison)`|A comment. It does not affect pattern-matching behavior.|
The original line is correct. The comment in the regex (and in the element-by-element description of the regex pattern) should have been "case-insensitive comparison".

2018-08-08 02:08 UTC, herohua commented
@rpetrusha , understood. I will update the PR accordingly and can help with changes in source code after this PR.

2018-08-08 17:44 UTC, rpetrusha approved these changes
Thanks, @herohua, for the additional commit. I'll merge your PR now. The changes should be live on docs.microsoft.com in the next day or two.

2018-08-08 17:44 UTC, merged