converted additonal msdn links to site-relative, mostly to windows co…
dotnet/docs pull request #6865
Opened 2018-08-06 22:54 UTC by mikeblome

…ntent

## Summary

Conversion from msdn form to site-relative form for additional links. Includes site-relative links to new windows content on docs.

Fixes #Issue_Number (if available)

2018-08-07 07:30 UTC, mairaw requested changes
Thank you so much for doing this @mikeblome! Left a comment about previous-versions URLs and also this PR introduces a couple of broken links.

2018-08-07 07:30 UTC, mairaw commented on docs/framework/net-native/migrating-your-windows-store-app-to-net-native.md
> + <xref:System.Runtime.InteropServices.UnmanagedType.Struct?displayProperty=nameWithType> is supported, but it throws an exception in some scenarios, such as when it is used with [IDispatch](/previous
@mikeblome can we have the absolute url when the target URL is previous-versions? Because we won't have offline books for those.

2018-08-07 15:16 UTC, BillWagner submitted a review, later dismissed
Thanks for updating this @mikeblome Overall, this is great.

There are a few new build warnings for invalid referenced in this PR. I flagged a couple of them. The others are listed in the build report.

2018-08-07 15:16 UTC, BillWagner commented on docs/framework/deployment/deployment-guide-for-developers.md
> +- If you are referencing a Microsoft [out-of-band package](../../get-started/the-net-framework-and-out-of-band-releases.md) in your app, the assembly will be included in the app package.
This link should be "../get-started/*" not "../../get-started/*"

2018-08-07 15:16 UTC, BillWagner commented on docs/framework/migration-guide/net-framework-4-migration-issues.md
> +| **Global assembly cache location change** | For .NET Framework 4 assemblies, the global assembly cache has been moved from the Windows directory (%WINDIR%) to the Microsoft.Net subdirectory (*%WIND
One too many parent directories on "unmanaged-api/fusion/*"

2018-08-10 21:52 UTC, mairaw reviewed
Looks great @mikeblome. I just found two issues and left a suggestion.

2018-08-10 21:52 UTC, mairaw commented on docs/csharp/programming-guide/concepts/async/index.md
> + The Windows Runtime also contains many methods that you can use with `async` and `await` in Windows apps. For more information, see [Threading and async programming](/windows/uwp/threading-async/) f
not related to your PR but probably a better link for the async programming one would be the one on docs fresh: https://docs.microsoft.com/en-us/windows/uwp/threading-async/asynchronous-programming-universal-windows-platform-apps

2018-08-10 21:52 UTC, mairaw commented on docs/framework/develop-client-apps.md
> +[.NET API for Windows Phone Silverlight](https://docs.microsoft.com/en-ushttps://docs.microsoft.com/previous-versions/windows/apps/jj207211\(v=vs.105\))
broken link here

2018-08-10 21:52 UTC, mairaw commented on docs/framework/network-programming/network-programming-samples.md
> + [HttpListener ASPX Host Application Sample](https://docs.microsoft.com/en-ushttps://docs.microsoft.com/previous-versions/visualstudio/visual-studio-2008/dd767375(v%3dvs.90))
broken link

2018-08-11 00:24 UTC, mairaw approved these changes

2018-08-11 00:53 UTC, BillWagner approved these changes

2018-08-11 00:54 UTC, merged