Standardize See Also section using bulleted lists
dotnet/docs pull request #7249
Opened 2018-08-24 01:48 UTC by nemrism

Use bulleted list in `See Also` section of docs\csharp\language-reference\keywords\ files

Contributes to #6923 
Related PR #7245

2018-08-24 15:52 UTC, rpetrusha requested changes
Thank you so much for continuing to work on adding bullets to See also items, @nemrism. There was one accidental insertion of a hypen that needs to be removed in the async.md document, then this PR will be ready to merge.

2018-08-24 15:52 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/async.md
> +- [Walkthrough: Accessing the Web by Using Async and Await]-(../../../csharp/programming-guide/concepts/async/walkthrough-accessing-the-web-by-using-async-and-await.md)
there's a "-" between the link text and the link that is causing this not to render as a link.

2018-08-24 18:41 UTC, nemrism commented
Fixed it and pushed, @rpetrusha , thanks for the review.
I'll take a look again to the other PR to check I didn't made the same mistake.

2018-08-24 21:42 UTC, rpetrusha commented
No, you didn't make the same mistake anywhere else, @nemrism  -- at least not in the PRs that I've looked at.

2018-08-25 00:16 UTC, rpetrusha approved these changes
Thanks for making the additional change, @nemrism. I'll merge your PR now.

2018-08-25 00:16 UTC, merged