Update explicit.md to conform language specification
dotnet/docs pull request #7274
Opened 2018-08-24 21:38 UTC by pkulikov

Fixes #6952

Moved comment into the article text, so it will be localized.
Snippet is updated by dotnet/samples#254

2018-08-24 22:11 UTC, rpetrusha commented
Closing and reopening to begin new build after modified example merged.

2018-08-24 22:32 UTC, rpetrusha requested changes
Thanks, @pkulikov. This is an important change, since comments aren't localized, I've suggested two changes, one unrelated to your PR.

2018-08-24 22:32 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/explicit.md
> +The following example defines the operator that converts from a `Fahrenheit` class to a `Celsius` class (the operator must be defined either inside a `Fahrenheit` class or a `Celsius` class):
It would be best to make "(the operator must be defined..." a separate sentence.

2018-08-24 22:32 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/explicit.md
>  [How to: Implement User-Defined Conversions Between Structs](../../programming-guide/statements-expressions-operators/how-to-implement-user-defined-conversions-between-structs.md)
nit unrelated to your PR: the See also items could be made bulleted list items.

2018-08-24 22:37 UTC, pkulikov commented
@rpetrusha thank you for review; I've addressed your feedback.

2018-08-28 16:36 UTC, rpetrusha approved these changes
Thanks for making the additional changes, @pkulikov. I'll merge your PR now.

2018-08-28 16:36 UTC, merged