Revised docs related to operator overloading
dotnet/docs pull request #7283
Opened 2018-08-25 13:53 UTC by pkulikov

This PR removes [How to: Use Operator Overloading to Create a Complex Number Class](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/how-to-use-operator-overloading-to-create-a-complex-number-class) article, following the discussion that started with [this comment](https://github.com/dotnet/docs/pull/7265#issuecomment-415863730)

Moreover, this PR updates the [operator keyword](https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/operator) article with more information about how to overload an operator. Part of this information has previously resided in the [Overloadable operators](https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/statements-expressions-operators/overloadable-operators) topic, which now just references the keyword topic.

2018-08-25 13:54 UTC, pkulikov commented on docs/csharp/programming-guide/statements-expressions-operators/overloadable-operators.md
> +|[+=](../../language-reference/operators/addition-assignment-operator.md), [-=](../../language-reference/operators/subtraction-assignment-operator.md), [\*=](../../language-reference/operators/multip
Rich diff makes the review of the changes made in this table easier.

2018-08-27 18:15 UTC, rpetrusha requested changes
This looks really good, @pkulikov; thanks for submitting the PR and eliminating the outdated topic. I've left a couple of minor comments.

2018-08-27 18:15 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/operator.md
> +For the overview of the C# operators that can be overloaded, see the [Overloadable operators](../../programming-guide/statements-expressions-operators/overloadable-operators.md) article.
- the overview --> an overview
- I think this is more effective if it's moved into the second bulleted list item. Though it's also fine here.

2018-08-27 18:15 UTC, rpetrusha commented on docs/csharp/programming-guide/statements-expressions-operators/overloadable-operators.md
> +For the information about how to overload an operator, see the [operator](../../language-reference/keywords/operator.md) keyword article.
the information --> information

2018-08-27 18:15 UTC, rpetrusha commented on docs/csharp/language-reference/keywords/operator.md
> +For the information about how to define conversion operators, see the [explicit](explicit.md) and [implicit](implicit.md) keyword articles.
the information --> information

2018-08-27 23:59 UTC, rpetrusha approved these changes
Thanks, @pkulikov, for making the additional changes. I'll merge your PR now.

2018-08-27 23:59 UTC, merged