NUnit template included in cli
dotnet/docs pull request #7318
Opened 2018-08-27 21:42 UTC by kendrahavens

## Summary
NUnit template is now in dotnet CLI. 
Adding the package `dotnet new -i NUnit3.DotNetNew.Template` is no longer required since the template is pre-installed.

I also updated the version numbers and tweaked a few places the csproj names lost a period.

Fixes https://github.com/dotnet/docs/issues/7204

2018-08-28 18:08 UTC, mairaw requested changes
Thanks @kendrahavens. Changes look great! I've left just a few comments and questions for you. Please take a look. I can help with the updates if that helps. 

Also, as I was trying to follow along the tutorial to verify the steps, I've noticed there are a few parts of this article that can be improved, but I'll create a new issue for that.

2018-08-28 20:52 UTC, kendrahavens commented on docs/core/testing/unit-testing-with-nunit.md
Thank you! I wasn't sure if making sure the sample versions matched was terribly important.

2018-08-28 20:52 UTC, kendrahavens commented on docs/core/testing/unit-testing-with-nunit.md
> +  <PackageReference Include="Microsoft.NET.Test.Sdk" Version="15.7.2" />
Sure!

2018-08-28 20:59 UTC, kendrahavens commented on docs/core/testing/unit-testing-with-nunit.md
> +## Creating the test project
Yes, it was in CLI 2.1.401. I can add that.

2018-08-28 21:16 UTC, mairaw commented
Created PR for updating the project and also added tags so we can reference the csproj from here instead of having to update both places every time for package versions:
https://github.com/dotnet/samples/pull/269

2018-08-28 23:07 UTC, kendrahavens commented on docs/core/testing/unit-testing-with-nunit.md
> +## Creating the test project
Oh what text snippet do you recommend? Something like:
> This topic applies to: ✓ .NET Core SDK 2.1.4 and later versions

2018-08-29 00:09 UTC, mairaw commented on docs/core/testing/unit-testing-with-nunit.md
> +## Creating the test project
I'd call out the exact version. But this seemed to work with the 400 version I have installed.

2018-08-29 00:10 UTC, mairaw commented on docs/core/testing/unit-testing-with-nunit.md
It's best since we link to the full source by the end of the article. So it would be weird not to have that updated as well.

2018-08-29 00:16 UTC, mairaw commented
Just noticed we also have VB and F# versions of the same topic. So I'll apply all changes we make to those topics once we're done with the changes to the C# one.

2018-08-30 01:54 UTC, kendrahavens commented on docs/core/testing/unit-testing-with-nunit.md
> +## Creating the test project
Ah, you are correct. I found it in the [400 release notes](https://github.com/dotnet/core/blob/master/release-notes/2.1/2.1.400-SDK/2.1.400-sdk.md#notable-changes-in-sdk-21400). Thanks!

2018-08-30 02:00 UTC, kendrahavens commented
@mairaw That would be awesome! I was thinking of those, but wanted to make sure I had the right changes before I repeated them on the other docs. Sweet!

2018-08-31 16:57 UTC, kendrahavens commented
@mairaw Is there anything else I need to add for approval?

2018-08-31 19:58 UTC, mairaw commented
I've updated the date to reflect the change and I'll keep that issue open so I can mirror the same changes to the VB and F# versions.

2018-08-31 21:46 UTC, mairaw commented
I was going to create a separate PR for some improvements but decided it would be better to have it done here so the C# version is 100% complete. Some things bothered me as I was testing the whole topic before.

2018-08-31 22:41 UTC, mairaw approved these changes

2018-08-31 22:41 UTC, merged

2018-09-04 19:10 UTC, kendrahavens commented
You are awesome! Thank you!

2018-09-04 19:29 UTC, kendrahavens commented
F# and Visual Basic docs to follow.