Clean up words in F# install page
dotnet/docs pull request #7349
Opened 2018-08-28 21:51 UTC by cartermp

2018-08-28 22:38 UTC, rpetrusha requested changes
This looks good, @cartermp, except that the two links to the interactive install topic are broken.

2018-08-28 22:38 UTC, rpetrusha commented on docs/fsharp/get-started/install-fsharp.md
> +[Mono](http://www.mono-project.com) is used for [F# Interactive](../tutorials/fsharp-interactive.md) support. The easiest way to install Mono on macOS is via Homebrew. Simply type the following into
The link is broken: ../tutorials/fsharp-interactive/index.md

2018-08-28 22:38 UTC, rpetrusha commented on docs/fsharp/get-started/install-fsharp.md
> +[Mono](https://www.mono-project.com) is used for [F# Interactive](../tutorials/fsharp-interactive.md) support. If you're on Debian or Ubuntu, you can use the following:
The link is broken: ../tutorials/fsharp-interactive/index.md

2018-08-28 22:52 UTC, mairaw commented
My change should fix that.

2018-08-28 22:56 UTC, cartermp commented
Thanks @mairaw, sorry for the mess on my end

2018-08-29 17:00 UTC, rpetrusha approved these changes

2018-08-29 17:00 UTC, rpetrusha commented
This is ready to merge, @cartermp.

2018-08-29 17:15 UTC, merged