Change string to bool
dotnet/docs pull request #7486
Opened 2018-09-04 15:56 UTC by jahbenjah

Change string to bool because the string type is not a primitive type

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-09-04 18:07 UTC, mairaw commented
Build failed. Trying again.

2018-09-04 21:18 UTC, rpetrusha requested changes
Thanks for making this correction, @jahbenjah. One further change is needed, though, so that the link to the bool article can be resolved.

2018-09-04 21:18 UTC, rpetrusha commented on docs/core/about.md
> +- Primitive types, such as [bool][bool] and [int][int].
For the link to be resolved, line 36 has to be modified as well. It should be:
[bool]: https://docs.microsoft.com/en-us/dotnet/csharp/language-reference/keywords/bool

2018-09-05 16:46 UTC, rpetrusha approved these changes

2018-09-05 16:47 UTC, rpetrusha commented
Thanks, @jahbenjah, for making the additional change. We'll merge your PR once we've updated our live branch. Your changes should appear live on docs.microsoft.com in the next day or two.

2018-09-05 16:51 UTC, merged