Fixed code indentation
dotnet/docs pull request #7527
Opened 2018-09-06 09:58 UTC by Shah-Nisarg

2018-09-06 16:01 UTC, rpetrusha requested changes
Thanks for correcting the formatting, @Shah-Nisarg. The code fails to compile because the first `ProcessorCount` is undefined and should be `Environment.ProcessorCount`. This is unrelated to your PR, but would you mind fixing it?

2018-09-07 05:52 UTC, Shah-Nisarg commented
Thanks for reviewing @rpetrusha . I have updated the code.

2018-09-07 16:55 UTC, rpetrusha approved these changes

2018-09-07 16:55 UTC, rpetrusha commented
Thanks, @Shah-Nisarg, for making the additional changes. I'll merge your PR now. The updated examples should appear live on docs.microsoft.com in the next day or two.

2018-09-07 16:56 UTC, merged