C37856: Replacing single quotes syntax to avoid extra content in link
dotnet/docs pull request #7610
Opened 2018-09-10 17:25 UTC by v-maudel

Hello, @mairaw ,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.  
Description: Missing space after the URL is causing the entity to be linked. Please use the single quotation mark.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

2018-09-11 21:54 UTC, rpetrusha requested changes
Thanks for opening this PR, @v-maudel. A problem with this fix on line 11 and also with line 12 is that the URL renders as a link. That's not desirable -- it would be preferable to fence both URLs so they don't render as links. E.g., \`http://www.w3.org/XML/1998/namespace\`,

2018-09-17 16:03 UTC, v-maudel commented
Hi @rpetrusha , 
I've updated it!

2018-09-17 16:16 UTC, rpetrusha approved these changes

2018-09-17 16:16 UTC, merged

2018-09-17 16:47 UTC, v-maudel commented
Thanks @rpetrusha