Smallish Visual Studio updates to high page view topics
dotnet/docs pull request #7633
Opened 2018-09-11 18:15 UTC by gewarren

2018-09-11 20:09 UTC, rpetrusha requested changes
Thanks for making these changes, @gewarren. I've left a number of comments, many of them unrelated to your PR but that would be nice to address.

2018-09-11 20:09 UTC, rpetrusha commented on docs/framework/whats-new/index.md
unrelated to your PR: The ClickOnce link is not working. could you remove blank line 402?

2018-09-11 23:07 UTC, rpetrusha requested changes
This looks good, @gewarren. Just two comments to address.

2018-09-11 23:07 UTC, rpetrusha commented on docs/framework/whats-new/index.md
> +#### <a name="clickonce472" /> ClickOnce
The link still isn't working. I think it needs to be on two separate lines as it originally was:

\<a name="clickonce472" />
\#\#\#\# ClickOnce

2018-09-11 23:07 UTC, rpetrusha commented on docs/framework/whats-new/index.md
This is badly formatted -- the opening \*\*\` can be removed.

2018-09-12 03:16 UTC, gewarren commented
@rpetrusha Thanks so much for your reviews. The ClickOnce bookmarks are both working now and I think this is good to go.

2018-09-12 16:44 UTC, rpetrusha commented
Thanks for making the additional changes, @gewarren. This looks good, so I'll merge it now.

2018-09-12 16:44 UTC, rpetrusha approved these changes

2018-09-12 16:44 UTC, merged

2018-09-12 16:47 UTC, gewarren commented
@rpetrusha Thanks very much Ron!