WIP - Refresh multi-part WCF tutorial
dotnet/docs pull request #7688
Opened 2018-09-13 21:03 UTC by gewarren

2018-09-14 19:43 UTC, rpetrusha requested changes
You've substantially improved these topics, @gewarren. I've left a number of comments, many of them unrelated to your PR but that it would be nice to fix. Also, this is a substantial enough revision that you should update the ms.date field.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +// program.cs
Here again, it's useful to pare down the namespaces to the ones actually used (the same ones as in the VB example, along with System. And the filename can be removed.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +```vb
The filename can be removed, as can Imports System.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +1. Step 1 - Creates an instance of the Uri class to hold the base address of the service. Services are identified by a URL which contains a base address and an optional URI. The base address is forma
The use of a number and "Step x" seems redundant here.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +using System;
Pare down namespaces here.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +using System;
Pare down namespaces here.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +using System;
Similarly, here.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-host-and-run-a-basic-wcf-service.md
> +Imports System
Remove Imports System here and in the later VB code examples in this page.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-implement-a-wcf-contract.md
> +//Service1.cs
The same comments as previously apply to both the VB and C# code here.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-use-a-wcf-client.md
> +```csharp
The same comments as earlier apply to VB and C# code in this article.

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/how-to-use-a-wcf-client.md
> +Notice the using or imports statement that imports the GettingStartedClient.ServiceReference1. This imports the code generated by Add Service Reference in Visual Studio. The code instantiates the WCF
using, imports, and GettingStartedClientServiceReference1 can all be fenced.
Add Service Reference can be bolded.
comma after "closed the proxy"

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/wcf-service-publishing.md
> + You can find these service templates by choosing **File** -> **New Project** -> **Visual Basic** or **Visual C#** -> **WCF**. For other WCF templates in this location (including WCF Workflow Service
nit: comma before "you can publish"

2018-09-14 19:43 UTC, rpetrusha commented on docs/framework/wcf/wcf-service-publishing.md
> + If you choose to deploy your application to local IIS, you may encounter errors related to IIS setup. Please ensure that IIS is installed properly. You can type " HYPERLINK "http://localhost" http:/
" HYPERLINK "http://localhost" http://localhost" --> \`http://localhost\`

2018-09-14 21:15 UTC, gewarren commented
@rpetrusha Thanks for reviewing this!

2018-09-17 16:18 UTC, rpetrusha approved these changes

2018-09-17 16:19 UTC, rpetrusha commented
Thanks, @gewarren, for making the additional changes. You can merge whenever you're ready.

2018-09-17 16:28 UTC, gewarren commented
@rpetrusha Thank you!

2018-09-17 16:28 UTC, merged