Documented compat switches for ASP.NET apps
dotnet/docs pull request #7789
Opened 2018-09-19 19:15 UTC by rpetrusha

## Documented compat switches for ASP.NET apps

Fixes #6675 

@AlexGhiondea

2018-09-19 19:47 UTC, AlexGhiondea requested changes

2018-09-19 19:47 UTC, AlexGhiondea commented on docs/framework/configure-apps/file-schema/appsettings/add-element-for-appsettings.md
> +  <add key="Switch.System.,Globalization.NoAsyncCurrentCulture" value="true" />
This needs to be: 
key="AppContext.SetSwitch:Switch.System.Globalization.NoAsyncCurrentCulture" value="true" />

Same for the one below.

2018-09-19 19:47 UTC, AlexGhiondea commented on docs/framework/configure-apps/file-schema/runtime/appcontextswitchoverrides-element.md
> +  <add key="Switch.System.,Globalization.NoAsyncCurrentCulture" value="true" />
This needs to be as above.

2018-09-20 15:05 UTC, BillWagner approved these changes
These are good improvements @rpetrusha 

Once you address the PM comments, you can :shipit:

2018-09-20 17:14 UTC, AlexGhiondea approved these changes

2018-09-20 18:17 UTC, merged