Minor clarifications and formatting tweaks
dotnet/docs pull request #7791
Opened 2018-09-19 20:54 UTC by mlimber

## Minor clarifications and formatting tweaks

I applied some minor fixes such as:
* Clarify where the `<UICulture>` element goes in the .csproj file.
* Using "e.g." (for example) instead of "i.e." (that is).
* Removing extraneous spaces and punctuation such as the extra space and comma in this: "in the case of the LocBaml Tool, ( see Localize an Application),".
* Fix broken code formatting on the last code block in the article. (Did not convert to external file to provide minimum changeset.)

Fixes #7788 (reported by me before I realized I could edit directly).

2018-09-19 20:54 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=7791) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=7791) before we can accept your contribution.<br/><br/>:x: mlimber [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=7791)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=7791) it.</sub>

2018-09-19 22:06 UTC, mairaw requested changes
Thank you for contributing to our docs @mlimber. Changes look great but left a few comments for a couple of things that should be fixed before we could merge. Thanks!

2018-09-19 22:06 UTC, mairaw commented on docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md
> + On German [!INCLUDE[TLA#tla_mswin](../../../../includes/tlasharptla-mswin-md.md)], if this resources.dll is placed in a de-DE folder next to the main assembly, this resource will automatically load
we actually shouldn't use neither i.e. or e.g. in our docs and actually spell it out for example.
also, make sure that the other missing backtick is added.

2018-09-19 22:06 UTC, mairaw commented on docs/framework/wpf/advanced/wpf-globalization-and-localization-overview.md
> + If you specify a font that does not support a given codepoint range, [!INCLUDE[TLA2#tla_winclient](../../../../includes/tla2sharptla-winclient-md.md)] will automatically fallback to one that does by
should this one be for example as well?

2018-09-20 15:16 UTC, mlimber commented
I updated my PR. Let me know if you need anything else from me! Thanks.

2018-09-24 23:40 UTC, mairaw approved these changes
This looks great @mlimber. I've just fixed some of escaping of the asterisks before we can merge.

2018-09-24 23:54 UTC, merged