update link to asp.net core docs tutorials
dotnet/docs pull request #7953
Opened 2018-09-30 17:02 UTC by terry-mulvany

## Summary

Link no longer exists in gh and it seems like it was intended to go to primary doc site for asp.net core

2018-10-01 17:08 UTC, rpetrusha requested changes
Thanks for contributing to the dotnet/docs repo, @terry-mulvany. The format of the link is correct, as I indicated in my detailed comment, although actual link itself should go to the ASP.NET Core tutorials. Can you make that change before I approve your PR?

2018-10-01 17:08 UTC, rpetrusha commented on docs/core/tutorials/aspnet-core.md
> +For tutorials about developing ASP.NET Core web applications, we suggest you head over to [ASP.NET Core documentation](https://docs.microsoft.com/en-us/aspnet/core/tutorials).
Links such as `/aspnet/core...` are resolved by the publishing platform for docs.microsoft.com. So the /aspnet/core/ part of the link is correct. It should link to tutorials, though. So a better link is /aspnet/core/tutorials/. Would you mind changing it?

Also, and totally unrelated to your PR, "head over to" is a difficult phrase for localization. Would you mind changing it to "see"?

2018-10-02 01:37 UTC, terry-mulvany commented
@rpetrusha how's that

2018-10-02 02:19 UTC, mairaw commented on docs/core/tutorials/aspnet-core.md
> +For tutorials about developing ASP.NET Core web applications, tions, see [ASP.NET Core documentation](aspnet/core/tutorials).
remove ",tions,"

also change the link text to ASP.NET Core tutorials since you changed the destination

2018-10-04 18:11 UTC, rpetrusha approved these changes

2018-10-04 18:12 UTC, rpetrusha commented
This looks good, @terry-mulvany. Thanks for making the changes. We'll merge your PR now. Changes should appear live on docs.microsoft.com in the next day or two.

2018-10-04 18:12 UTC, merged