More examples of code and showing different ways to do things
dotnet/docs pull request #7982
Opened 2018-10-02 04:38 UTC by thalaeg

For the modify data in database: there was a "dim" missing and also I thought it would be good to show other fields updating.

For how to count, sum, or average data: I was giving more examples of LINQ calls that are easier to read

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-10-02 04:38 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=7982) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=7982) before we can accept your contribution.<br/><br/>:x: thalaeg [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=7982)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=7982) it.</sub>

2019-01-16 00:38 UTC, mairaw commented
Closing and reopening to get a new build. @rpetrusha @KathleenDollard can we get a review here?

2019-01-17 01:50 UTC, rpetrusha requested changes
Thank you for contributing to the dotnet/docs repo, @thalaeg, and for modifying these examples. I apologize that it's taken us such a ridiculously long amount of time to review your PR and respond to you. You changes look good except for the addition of the `Dim` statement; the call to the constructor was intended to initialize the `db` variable declared on line 64. Once you remove the Dim statement, we'll merge your PR.

2019-01-17 01:50 UTC, rpetrusha commented on docs/visual-basic/programming-guide/language-features/linq/how-to-modify-data-in-a-database-by-using-linq.md
> +      Dim db = New northwindDataContext()
The `Dim` here is incorrect; db is declared on line 64. Declaring it here causes it to not be in scope for the call in `RefreshData`.

2019-01-18 17:34 UTC, rpetrusha approved these changes

2019-01-18 17:34 UTC, merged