Improved document formatting and readability
dotnet/docs pull request #8035
Opened 2018-10-03 14:04 UTC by julianstopher

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-10-03 14:20 UTC, BillWagner requested changes
Thanks for spotting this and submitting a fix @julianstopher 

We appreciate it.  

I like the list, but want to keep the links. Can you update the PR with my suggested changes?

Thank you.

2018-10-03 14:20 UTC, BillWagner commented on docs/csharp/how-to/compare-strings.md
> +**System.String.CompareTo(String)**,
I really like that you have changed these to a list format.

However, I'd like to keep the link syntax. Can you replace this change with the following:

```md
- <xref:System.String.CompareTo%2A?displayProperty=nameWithType>
- <xref:System.String.Equals%2A?displayProperty=nameWithType>
- <xref:System.String.op_Equality%2A?displayProperty=nameWithType> 
```

2019-01-18 02:31 UTC, mairaw commented
I've resolved the merge conflicts but it seems @rpetrusha has changed the topic since. Do we still want to merge this @BillWagner?

2019-01-18 15:49 UTC, BillWagner commented
Thanks for the ping @mairaw 

I'll approve and merge now. I think that additional format does make it easier to spot the important information when scanning the article.

2019-01-18 15:49 UTC, BillWagner approved these changes

2019-01-18 15:49 UTC, merged