Add Nuget.exe as Prerequisites
dotnet/docs pull request #8049
Opened 2018-10-03 18:48 UTC by jahbenjah

You need the nuget.exe to create a custom template

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-10-22 23:40 UTC, mairaw commented
@KathleenDollard @dsplaisted @guardrex can you confirm that prereq for creating a custom template?

2018-10-22 23:49 UTC, guardrex commented
I don't think [dotnet pack](https://docs.microsoft.com/dotnet/core/tools/dotnet-pack) existed at the time we put this topic out. If `dotnet pack` hits the spot, then I'd resolve this by swapping the `dotnet pack` command into the topic.

2018-10-23 01:07 UTC, guardrex commented
mmmmm 🤔 .... *existed* ... let me rephrase to "*worked*".

> Currently, a custom template is packed on Windows with [nuget.exe](https://dist.nuget.org/win-x86-commandline/latest/nuget.exe) (not [dotnet pack](dotnet-pack.md)).

... **_"not dotnet pack"_** ... 

For example at the time ... https://github.com/dotnet/dotnet-template-samples/issues/16#issuecomment-310690785

The explicit "not dotnet pack" comment probably reflects a limitation of the `dotnet pack` command at the time.

I'm free next weekend. Would u like me to run it with `dotnet pack` and see what happens? :smile: or :cry:

2018-11-25 22:39 UTC, guardrex commented
@mairaw If you like, I'll be free over the 🎄 holiday break ⛄️ to work it or immediately after my contract ends on 12/31. Let me know.

2019-02-22 19:12 UTC, BillWagner commented
@KathleenDollard @rlander Who should look at this for the correct xplat workflow?

2019-03-12 19:34 UTC, seancpeters commented
Using dotnet pack should create the nupkg whether it's run on Windows or on Linux. Nupkgs themselves are platform agnostic, and so it should not matter on which platform the nupkg is created.

2019-03-12 20:51 UTC, dsplaisted commented
@seancpeters `dotnet pack` creates a .nupkg from a project file.  In this guide for creating templates, you need to create a .nupkg from a .nuspec, which isn't supported by `dotnet pack`, at least not without a special project file.

2019-04-10 23:21 UTC, Thraka requested changes
En-us should be removed from the URL.

2019-04-10 23:21 UTC, Thraka commented on docs/core/tutorials/create-custom-template.md
> +- Install the [nuget.exe CLI](https://docs.microsoft.com/en-us/nuget/install-nuget-client-tools#nugetexe-cli)
The link shouldn't have `en-us` in it.

```suggestion
- Install the [nuget.exe CLI](https://docs.microsoft.com/nuget/install-nuget-client-tools#nugetexe-cli)
```

2019-04-10 23:42 UTC, Thraka commented
The article is written for the .nuspec file. If that file isn't supported with `dotnet pack` and we need to showcase that scenario, the article needs to be rewritten. This PR though is valid as, according to the article, nuget.exe is used and it's not listed as a prerequisite. According to the nuget install article, you can use nuget.exe on linux by installing mono.

I think we should accept the PR. If we want the article rewritten with the faux csproj that replaces the nuspec and use dotnet pack, we should file a new issue for that.

2019-10-04 17:49 UTC, mairaw commented
@Thraka you completely rewrote these tutorials, no? should we close this?

2019-10-04 17:52 UTC, Thraka commented
Yes this should be closed. This file doesn't exist anymore.

2019-10-04 17:52 UTC, closed without merging