ML tutorials: reference overview of new ML.NET API
dotnet/docs pull request #8051
Opened 2018-10-03 19:53 UTC by pkulikov

As the [new API released with 0.6 version](https://github.com/dotnet/machinelearning/blob/master/docs/release-notes/0.6/release-0.6.md) and while tutorials are not updated, would be useful to give the links to the overview of new API.

/cc: @JRAlexander

2018-10-05 21:05 UTC, JRAlexander requested changes
@pkulikov - Looks good except for a few small changes. Thanks!

2018-10-05 21:05 UTC, JRAlexander commented on docs/machine-learning/tutorials/index.md
> +> The tutorials demonstrate how to use the ML.NET API introduced in ML.NET 0.1. For information about new API introduced in ML.NET 0.6, see [ML.NET high-level concepts](https://github.com/dotnet/mach
Please reference the current api as the LearningPipeline, and add "the" between about and new.
-> The tutorials demonstrate how to use the ML.NET `LearningPipeline` API introduced in ML.NET 0.1. For information about the new API introduced in ML.NET 0.6, see [ML.NET high-level concepts]

2018-10-05 22:40 UTC, pkulikov commented
@JRAlexander thank you for review; I've addressed your feedback.

2018-10-06 00:05 UTC, JRAlexander approved these changes

2018-10-06 00:06 UTC, JRAlexander commented
@pkulikov - Thanks for adding this. I'll merge it now.

2018-10-06 00:06 UTC, merged