Guidelines for working with Memory\<T> and Span\<T>
dotnet/docs pull request #8055
Opened 2018-10-03 22:59 UTC by rpetrusha

## Guidelines for working with Memory\<T> and Span\<T>

Fixes #4823 

@ahsonkhan @stephentoub @GrabYourPitchforks

2018-10-04 19:13 UTC, BillWagner requested changes
This is really good @rpetrusha It's a clear explanation of these types and when to choose each.

I had a few suggestions for topics to introduce earlier that would make it more clear.

Overall, a great addition.

2018-10-04 22:43 UTC, rpetrusha commented on docs/standard/memory-and-spans/memory-t-usage-guidelines.md
> +- **Consumption**. The consumer of a buffer instance is allowed to use the buffer instance by reading from it and possibly writing to it. Buffers can have one consumer at a time unless some external
Contractions don't seem to be my strong point, @BillWagner.

2018-10-04 23:14 UTC, rpetrusha commented on docs/standard/memory-and-spans/memory-t-usage-guidelines.md
> +## Memory\<T> and the owner/consumer model
Thanks, @BillWagner; this is a really helpful comment. I've addressed it and committed. I'll address your following comment either later this evening or tomorrow.

2018-11-14 16:13 UTC, BillWagner approved these changes

2018-11-14 16:14 UTC, BillWagner commented
I approved the changes, as I had no further issues @rpetrusha 

I'll let you work through with @mairaw and others if more needs to be done.

2018-11-15 17:01 UTC, merged