Added note to clarify globbing support
dotnet/docs pull request #8101
Opened 2018-10-05 08:18 UTC by Nyami

## Summary

#6293 confirms this behaviour so thought it valuable to add a clear note.

2018-10-08 16:26 UTC, rpetrusha requested changes
Thanks, @Nyami, for adding the note. I've proposed some changes for you to consider.

2018-10-08 16:40 UTC, pkulikov commented on docs/core/tools/dotnet-sln.md
> +> Globbing is not a CLI feature but rather a feature of the command shell, to sucessfully expand the files you must be using a shell that supports.
one more suggestion: 
- "you must be using" --> "use" or "you must use"

2018-10-09 16:01 UTC, Thraka reviewed
Would it be helpful to add a `For more information about globbing, see [Wikipedia](https://en.wikipedia.org/wiki/Glob_%28programming%29).` at the end of the note?

2018-10-10 16:32 UTC, rpetrusha commented
This looks good, @Nyami. Though I like the suggestion from @Thraka that we add a link to more information about globbing. Would you like to do that?

2018-10-11 07:52 UTC, Nyami commented
@rpetrusha I'm happy to add @Thraka suggestion to the note.

2018-10-11 15:39 UTC, rpetrusha approved these changes

2018-10-11 15:40 UTC, rpetrusha commented
Thanks, @Nyami, for the contribution and the additional changes. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

2018-10-11 15:40 UTC, merged