Replacing MSDN links with /docs relative ones or API xref
dotnet/docs pull request #8111
Opened 2018-10-05 20:26 UTC by nemrism

Contributes to #2037

2018-10-06 01:59 UTC, mairaw commented
Thanks @nemrism! Can you access the [build report](https://opbuildstorageprod.blob.core.windows.net/report/2018%5C10%5C5%5Ca3bda507-3390-de91-8f7f-26f90f4e5fc8%5CPullRequest%5C201810052026304220-8111%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=f6D%2Fgl5kbQjyFwSMOccw5aaCLfPc1ChjGZsiyF36kBs%3D&st=2018-10-05T20%3A26%3A48Z&se=2018-11-05T20%3A31%3A48Z&sp=r)? There are a few warnings showing up.

2018-10-06 06:30 UTC, nemrism commented
Yes, I can see it with the warnings details, @mairaw 
I'll correct them, and reactivate the PR then.

2018-10-06 21:03 UTC, mairaw commented
Try rebasing your branch with dotnet/docs master to not have these extra commits showing up @nemrism. Let me know if you have any questions!

2018-10-06 21:05 UTC, nemrism commented
I was currently doing it (the rebase). I've pushed the last version based on it right now.

2018-10-06 21:09 UTC, nemrism commented
Not sure  I've done it right... could you check @mairaw ?

2018-10-08 22:28 UTC, mairaw commented
I don't think so. Let me try to fix this @nemrism.

2018-10-08 22:32 UTC, mairaw commented
Ok, I think that looks good now. As for doing this work, I'd break down these PRs even further. Having a maximum of 20 or so of this kind in one PR really speeds up the process for us. But we do appreciate your contributions!

2018-10-08 23:11 UTC, nemrism commented
Thx a lot for your help @mairaw 
I'll try to break them in even smaller ones, but it is sometimes easier for me to replace some links in the overall repo. This might lead to bigger PR if it was used in multiple files

2018-10-08 23:20 UTC, mairaw requested changes
Reviewed a portion of this PR. Left comments for where I saw changes needed.
For non-trivial changes, that's why we ask you to break down the PR. It's easier for us to review and for you to address comments as well.

2018-10-08 23:29 UTC, nemrism commented on docs/csharp/walkthroughs.md
> + [Creating a Windows Runtime Component in C# or Visual Basic and Calling it from JavaScript](/windows/uwp/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic)
You right, I didn't find this one!
I assume it should be without the locale but with or without the domain?

2018-10-08 23:30 UTC, mairaw commented on docs/csharp/walkthroughs.md
> + [Creating a Windows Runtime Component in C# or Visual Basic and Calling it from JavaScript](/windows/uwp/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic)
without like you did here

2018-10-08 23:31 UTC, nemrism commented on docs/csharp/walkthroughs.md
> + [Creating a Windows Runtime Component in C# or Visual Basic and Calling it from JavaScript](/windows/uwp/winrt-components/creating-windows-runtime-components-in-csharp-and-visual-basic)
Found my answer in next file change review

2018-10-08 23:32 UTC, nemrism commented on docs/framework/configure-apps/file-schema/wcf/trackingprofile-of-wcf.md
> +|[\<participants>](../../../../../docs/framework/configure-apps/file-schema/windows-workflow-foundation/participants.md)|A configuration element that contains all queries for a specific workflow iden
Works with any xref with trailing * or just in this particular case?

2018-10-08 23:55 UTC, mairaw commented on docs/framework/configure-apps/file-schema/wcf/trackingprofile-of-wcf.md
> +|[\<participants>](../../../../../docs/framework/configure-apps/file-schema/windows-workflow-foundation/participants.md)|A configuration element that contains all queries for a specific workflow iden
The * means it will go to the "overload" page instead of a specific API. So it works with properties and methods but not classes for example.

2018-10-09 00:01 UTC, nemrism commented on docs/framework/configure-apps/file-schema/wcf/trackingprofile-of-wcf.md
> +|[\<participants>](../../../../../docs/framework/configure-apps/file-schema/windows-workflow-foundation/participants.md)|A configuration element that contains all queries for a specific workflow iden
Ok, nice to understand it better.
After all this ongoing work on links replacement I may suggest some additions to the "Links" chapter of the styleguide sometime 😁

2018-10-09 00:08 UTC, mairaw commented on docs/framework/configure-apps/file-schema/wcf/trackingprofile-of-wcf.md
> +|[\<participants>](../../../../../docs/framework/configure-apps/file-schema/windows-workflow-foundation/participants.md)|A configuration element that contains all queries for a specific workflow iden
Yes, we probably need to enhance that section 😄

2018-10-16 06:16 UTC, nemrism commented on docs/framework/data/adonet/secure-data-access.md
> +|[Advanced COM Interoperability](/previous-versions/dotnet/netframework-4.0/bd9cdfyx)|Contains advanced topics such as primary interop assemblies, threading and custom marshaling.|
It seems that a lot of /previous-versions links are currently without the domain...
Would it be relevant to open a separated issue or PR to fix them all?

2018-10-16 17:06 UTC, mairaw commented
I can do a bulk search and replace to add the domain after we merge this one @nemrism.

2018-10-16 17:09 UTC, nemrism commented
Thanks, ready for another round of review!

2018-10-16 17:09 UTC, nemrism commented on docs/framework/deployment/guide-for-administrators.md
>   **SQL Server 2008:**
I'll try to do this update right now... just forget to do it

2018-10-16 17:10 UTC, mairaw commented
Yep, doing that right now!

2018-10-16 17:18 UTC, nemrism commented
In the guide-for-administrators.md flle, I would also suggest to update the following section:

**System Center 2012 Configuration Manager (Management Point, Distribution Point):**  

With links pointing to either https://docs.microsoft.com/sccm/core/plan-design/get-ready or https://docs.microsoft.com/en-us/sccm/core/plan-design/hierarchy/design-a-hierarchy-of-sites

2018-10-16 17:23 UTC, mairaw approved these changes
Great job on this PR @nemrism. I made some small fixes and I'll merge this as soon as build finishes successfully.

2018-10-16 17:35 UTC, merged

2018-10-16 18:05 UTC, nemrism commented
I'll make a separated PR with updates on last sections of the guide-for-administrators.md file