Add missing assembly to 'Creating the Data Set'
dotnet/docs pull request #8136
Opened 2018-10-06 21:11 UTC by Marcos-Costa

## Summary

The Creating the Data Set section was missing two assembly that it needs in order to compile. If the the user tried to compile the code as the tutorial told him to do, he would see an error message, instead of what was prompted in the image used at the end of this section.

2018-10-08 17:00 UTC, rpetrusha requested changes
Thanks, @Marcos-Costa, for contributing to the dotnet/docs repo. This is a useful addition, though it would be a good idea to add `using System;` to the list of imported namespaces as well.

2018-10-08 17:57 UTC, Marcos-Costa commented on docs/csharp/tutorials/working-with-linq.md
> +using System.Collections.Generic;
Thanks for this addition. I agree with the fact that assumptions like that may bring some problems to newcomers.

2018-10-09 16:33 UTC, rpetrusha approved these changes

2018-10-09 16:34 UTC, rpetrusha commented
Thanks, @Marcos-Costa, for making the additional change. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

2018-10-09 16:34 UTC, merged