Explain what a static variable does.
dotnet/docs pull request #8139
Opened 2018-10-07 03:53 UTC by pavanagrawal123

The current tutorial just adds in a static variable without explaining what it really does...

2018-10-08 17:09 UTC, rpetrusha requested changes
Thanks for contributing to the dotnet/docs repo, @pavanagrawal123, and for defining `static`. I thought that your definition could be improved by making it clear that there is a separate value of a non-static variable for each instance.

2018-10-08 17:09 UTC, rpetrusha commented on docs/csharp/quick-starts/introduction-to-classes.md
> +This is a data member. It's `private`, which means it can only be accessed by code inside the `BankAccount` class. It's a way of separating the public responsibilities (like having an account number)
Non \`static\` variables are --> The value of a non-static variable is

2018-10-08 19:42 UTC, pavanagrawal123 commented
I've updated the change, let me know what you think.

2018-10-09 16:36 UTC, rpetrusha approved these changes

2018-10-09 16:37 UTC, rpetrusha commented
Your changes look good, @pavanagrawal123. I'll merge your PR now. The updated article will be live on docs.microsoft.com in the next day or two.

2018-10-09 16:37 UTC, merged