Point to specific parts of the specification
dotnet/docs pull request #8221
Opened 2018-10-10 11:08 UTC by Mackiovello

Fixes #7890

2018-10-10 14:02 UTC, BillWagner requested changes
Thanks for making these changes @Mackiovello We really appreciate it.

I also like that you've updated the one paragraph where the text taken from the spec has changed. That was great to spot.

I have one suggestion for a better link destination. Once you make that change, I'll :shipit:

Thanks again.

2018-10-10 14:02 UTC, BillWagner commented on docs/csharp/programming-guide/generics/index.md
> + For more information, see the [C# Language Specification](../../../csharp/language-reference/language-specification/classes.md).
I'd change this link to `../../../csharp/language-reference/language-specification/types#constructed-types`

That is where the spec references generic definitions and instantiations.

2018-10-11 12:53 UTC, BillWagner commented
@Mackiovello You're using the correct syntax, but there's some build magic going on underneath.

The C# (and VB) language specs are from a dependent repo (see [here](https://github.com/dotnet/docs/blob/master/docfx.json#L28).  That means the links need to point to the MD files from the source.  For example:

```markdown
../../../csharp/language-reference/language-specification/arrays.md#array-initializers
```

Should be:

```markdown
../../../../_csharplang/spec/arrays.md#array-initializers
```

Note the extra `..` in the path.

I'll open a PR in the style guide to make a note of it.

2018-10-11 14:22 UTC, Mackiovello commented
Thanks for the clear instructions. It seems to work.

2018-10-12 15:16 UTC, BillWagner approved these changes

2018-10-12 15:17 UTC, BillWagner commented
Thanks for making the additional changes @Mackiovello I'll :shipit: now.  

You should see these updates on the live site in the next day or two. 💯

2018-10-12 15:17 UTC, merged