Fixed typo in sentence
dotnet/docs pull request #8256
Opened 2018-10-11 07:02 UTC by ThePiranha

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2018-10-11 07:14 UTC, mairaw requested changes
Thanks @ThePiranha. The removal of the double which looks good but the second file was correct actually. Can you undo that change please?

2018-10-11 07:14 UTC, mairaw commented on docs/core/tools/csproj.md
> +Semicolon separated list of key-value pairs.
the key=value pairs is correct. This is the format used for this property.

2018-10-11 17:41 UTC, ThePiranha commented
@mairaw cleaned up the other commits. Now one commit for one file change.

2018-10-12 00:09 UTC, mairaw approved these changes
Didn't need to clean the commit but thank you! 💯

2018-10-12 00:09 UTC, merged