Add intro to functional programming
dotnet/docs pull request #8367
Opened 2018-10-15 18:05 UTC by cartermp

First in a series that will be written over time.

2018-10-16 01:56 UTC, BillWagner requested changes
Overall, this is well presented.  You've explained the concepts clearly, with great examples of F# syntax.

I had a few suggestions that would make the comparisons stronger if your intended audience is developers familiar with OO or procedural languages.

I'd also recommend running Acrolinx on these changes. I saw a few instances of passive voice and future tense. The tool is more efficient at finding those than I am.

2018-10-16 01:56 UTC, BillWagner commented on docs/fsharp/introduction-to-functional-programming/index.md
> +* Functions over objects
I like this list as a set of goals. You did a great job of explaining immutable values over variables. I didn't find any comparison of functions and objects, or declarative over imperative. I mentioned some suggestions to make the comparison of expressions and suggestions stronger.  

If your intended audience is developers familiar with OO or procedural languages, I'd make those comparisons more clear.

2018-10-16 23:32 UTC, cartermp commented on docs/fsharp/introduction-to-functional-programming/index.md
> +    let result =
I added more detail and an C# comparison.

2018-10-16 23:32 UTC, cartermp commented on docs/fsharp/introduction-to-functional-programming/index.md
> +### Pure functions
Good idea. I've done so here and in the referential transparency section.

2018-10-23 16:58 UTC, mairaw commented
@BillWagner this might be ready for a new review

2018-10-23 21:38 UTC, BillWagner approved these changes

2018-10-23 21:39 UTC, BillWagner commented
I really like this @cartermp 
You can :shipit: when ready.

2018-10-29 20:27 UTC, cartermp commented on docs/fsharp/introduction-to-functional-programming/index.md
> +This is in sharp contrast to imperative programming, where the equivalent `if` construct is a statement, and producing values is often done with mutating variables. For example, in C#, the code might
Added.

2018-10-29 20:35 UTC, svick approved these changes

2018-10-29 20:54 UTC, pkulikov commented on docs/fsharp/introduction-to-functional-programming/index.md
> +It's worth noting that C# and other C-style languages do suppor the ternary `?` expression, which allows for expression-based conditional programming.
typo: "do suppor" -> "do support"
nit: `?` -> `?:` (not to mix with the null-conditional `?.` operator) or even explicitly: `cond ? x : y`

2018-10-29 21:13 UTC, merged