Added links to NuGet package services
dotnet/docs pull request #8379
Opened 2018-10-15 21:02 UTC by pkulikov

2018-10-15 21:03 UTC, pkulikov commented on docs/standard/library-guidance/nuget.md
> +NuGet is a package manager for the .NET eco-system and is the primary way developers discover and acquire .NET open-source libraries. [NuGet.org](https://www.nuget.org/), a free service provided by M
Given the service has a name, should the link "Azure DevOps" be renamed to "Azure Artifacts"?

2018-10-15 22:55 UTC, rpetrusha requested changes
In addition to the change suggested by @pkulikov, there are also two other issues, though both are unrelated to your PR. 
- eco-system --> ecosystem
- comma before "but you can publish" 
I'd appreciate it if you could make those changes as well.

2018-10-16 06:11 UTC, pkulikov commented
@rpetrusha thanks for review; I've also addressed additional feedback.

2018-10-16 17:04 UTC, rpetrusha approved these changes

2018-10-16 17:04 UTC, rpetrusha commented
Thank you so much, @pkulikov, for making the additional, extraneous changes. I really appreciate it. I'll merge your PR now.

2018-10-16 17:04 UTC, merged