Library guidance: clarified intent of the section
dotnet/docs pull request #8436
Opened 2018-10-17 16:10 UTC by pkulikov

This PR makes the purpose of the following section clear:
https://docs.microsoft.com/en-us/dotnet/standard/library-guidance/#recommendations

This section is not for recommendations, but introduce the types of recommendations used throughout the guidance.

/cc: @JamesNK

2018-10-17 18:25 UTC, JamesNK reviewed
Good improvement. Couple of minor language queries

2018-10-17 18:34 UTC, pkulikov commented
@JamesNK thanks for review. Also it was a good test of the "suggestions" feature.

2018-10-17 18:40 UTC, JamesNK approved these changes
Looks good to me. Thanks. A docs review will double check the language before merge.

2018-10-17 20:02 UTC, rpetrusha requested changes
This is much clearer, @pkulikov. Thanks for doing it. I've left one suggestion for you to consider.

2018-10-17 20:02 UTC, rpetrusha commented on docs/standard/library-guidance/index.md
> +Articles in this guidance present recommendations of four types: **Do**, **Consider**, **Avoid**, and **Do not**. The type of recommendation indicates how strongly it should be followed.
"Each article presents four types of recommendations" is clearer.

2018-10-17 20:02 UTC, rpetrusha commented on docs/standard/library-guidance/index.md
> +**Avoid** recommendations mention things that are generally not a good idea, but breaking the rule sometimes makes sense:
Very good change!! I didn't like "are things" previously, but couldn't think of a better replacement.

2018-10-17 20:12 UTC, pkulikov commented
@rpetrusha thanks for review; I've addressed your feedback.

2018-10-18 00:02 UTC, rpetrusha approved these changes

2018-10-18 00:03 UTC, rpetrusha commented
Thanks, @pkulikov. This topic now looks really good. I'll merge your PR.

2018-10-18 00:03 UTC, merged