wrong base address fix.
dotnet/docs pull request #8493
Opened 2018-10-19 07:52 UTC by koviroli

## Summary

Base adress code of How To Create Wcf Client page, is not correct. Maybe the VB script also incorrect.

Fixes #Issue_Number (if available)

2018-10-22 17:18 UTC, Thraka requested changes
@koviroli Thank you for opening this PR. Could you fix the other two error spots?

2018-10-22 17:18 UTC, Thraka commented on docs/framework/wcf/how-to-create-a-wcf-client.md
> +    svcutil.exe /language:cs /out:generatedProxy.cs /config:app.config http://localhost:8000/GettingStarted/CalculatorService
The `svcutil` call above for VB should also use this fixed URL.

2018-10-22 17:18 UTC, Thraka commented on docs/framework/wcf/how-to-create-a-wcf-client.md
> +    svcutil.exe /language:cs /out:generatedProxy.cs /config:app.config http://localhost:8000/GettingStarted/CalculatorService
It would be great if you could fix the intro URL also. It should not use `GettingStartedClient`

2018-10-23 07:50 UTC, koviroli commented
Ok I fix it

2018-10-23 16:33 UTC, Thraka approved these changes

2018-10-23 16:33 UTC, Thraka commented
@koviroli thank you!!

2018-10-23 16:35 UTC, merged