Revised addition operator reference
dotnet/docs pull request #8539
Opened 2018-10-21 20:47 UTC by pkulikov

Revised addition operators (`+` and `+=`) docs:
- move snippets to the samples repo: dotnet/samples#404
- split the `+` topic in sections
- add references to the C# language spec

2018-10-22 20:41 UTC, pkulikov commented
As snippets PR is merged, let's close/reopen.

2018-10-22 20:59 UTC, rpetrusha commented
Build warnings show that merge of examples wasn't recognized. Closing and reopening to begin new build.

2018-10-22 23:35 UTC, rpetrusha requested changes
This looks good, @pkulikov. Thanks also for moving the code to the samples repo. I've left a couple of suggested changes.

2018-10-22 23:35 UTC, rpetrusha commented on docs/csharp/language-reference/operators/addition-assignment-operator.md
> +For numeric types, the [addition operator](addition-operator.md) `+` computes the sum of its operands. If one or both operands of type [string](../keywords/string.md), it concatenates the string repr
of type --> is of type

2018-10-22 23:35 UTC, rpetrusha commented on docs/csharp/language-reference/operators/addition-operator.md
> +User-defined types can [overload](../keywords/operator.md) either of unary or binary `+` operators. When a binary `+` operator is overloaded, the [addition assignment operator](addition-assignment-op
either of unary or binary --> the unary and binary

2018-10-22 23:35 UTC, rpetrusha commented on docs/csharp/language-reference/operators/addition-operator.md
> +Unary `+` operator returns the value of its operand. It's supported by all numeric types.
Unary --> The unary

2018-10-22 23:35 UTC, rpetrusha commented on docs/csharp/language-reference/operators/remainder-operator.md
> +For information about behavior of the `%` operator in case of non-finite operands, see the [Remainder operator](~/_csharplang/spec/expressions.md#remainder-operator) section of the [C# language speci
unrelated to your PR: 
- behavior --> the behavior
- in case of --> with

2018-10-23 06:01 UTC, pkulikov commented
@rpetrusha thanks for review; I've addressed your feedback.

2018-10-23 15:14 UTC, rpetrusha approved these changes

2018-10-23 15:14 UTC, rpetrusha commented
Thanks, @pkulikov, for the additional changes. I'll merge your PR now.

2018-10-23 15:14 UTC, merged