Add missing Async suffix to ProcessURL method
dotnet/docs pull request #8637
Opened 2018-10-25 08:49 UTC by KristianJakubik

## Summary

Renames `ProcessURL` to `ProcessURLAsync`.

Fixes #8602

2018-10-25 17:16 UTC, rpetrusha requested changes
Thank you, @KristianJakubik, for contributing to the dotnet/docs repo, as well as for opening and addressing issue #8602 with this PR. There are two additional occurrences of `ProcessURL` that should be changed to `ProcessURLAsync`. The first occurs on line 103, the second on line 135. Could you make those changes as well, please?

2018-10-25 21:01 UTC, KristianJakubik commented
@rpetrusha 
Ohh crap. I though, I renamed everyone, thanks for pointing it out.

2018-10-26 22:18 UTC, rpetrusha approved these changes

2018-10-26 22:19 UTC, rpetrusha commented
Thanks for making the additional changes, @KristianJakubik. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

2018-10-26 22:19 UTC, merged