Fixes #8150 out of date
dotnet/docs pull request #8667
Opened 2018-10-26 18:49 UTC by AlexejLiebenthal

## Summary

Updated Text and Dialog

Fixes #8150

2018-10-26 18:50 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=8667) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=8667) before we can accept your contribution.<br/><br/>:x: AlexejLiebenthal [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=8667)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=8667) it.</sub>

2018-10-26 20:22 UTC, mairaw requested changes
Thanks for jumping on this issue @AlexejLiebenthal! The changes look great, Can you also take care of the comments I've left regarding this change?

2018-10-26 21:00 UTC, AlexejLiebenthal commented on docs/framework/wpf/getting-started/walkthrough-my-first-wpf-desktop-application.md
Sure

2018-11-12 23:30 UTC, mairaw approved these changes
Thank you @AlexejLiebenthal for addresing my feedback and apologies on the delay since I was out on vacation. Your changes will be live within a day.

2018-11-12 23:31 UTC, merged