Replace some MSDN links
dotnet/docs pull request #8718
Opened 2018-10-29 05:15 UTC by nemrism

## Summary

Changing MSDN links with docs.microsoft.com relative ones

Contributes to #2037

2018-10-29 20:12 UTC, rpetrusha requested changes
This looks good, @nemrism; thanks for doing it. I've left one suggested replacement for an existing link.

2018-10-31 00:16 UTC, nemrism commented
Hi @rpetrusha
Did the replacement & ready for a new review

2018-10-31 17:43 UTC, rpetrusha approved these changes

2018-10-31 17:43 UTC, rpetrusha commented
Thanks for making the additional changes, @nemrism. I'll merge your PR now.

2018-10-31 17:43 UTC, merged