Add dotnet-svcutil.xmlserializer guide
dotnet/docs pull request #8734
Opened 2018-10-29 22:23 UTC by huanwu

Add dotnet-svcuitl.xmlserializer guide

@Lxiamail

2018-10-29 22:32 UTC, Lxiamail approved these changes

2018-10-30 02:22 UTC, rpetrusha requested changes
Thanks for documenting this tool, @huanwu. I've left a number of comments and suggestions for you to consider.

2018-11-01 15:39 UTC, rpetrusha approved these changes

2018-11-01 15:39 UTC, rpetrusha commented
Thanks, @huanwu. The changes look great. I'll merge your PR now.

2018-11-01 15:39 UTC, merged

2018-11-01 21:03 UTC, huanwu commented
@rpetrusha Thanks!