Update net-standard.md
dotnet/docs pull request #8752
Opened 2018-10-30 15:42 UTC by Soundug

2018-10-30 15:52 UTC, Soundug commented
Closes Soundug/standard#736

2018-11-05 23:38 UTC, rpetrusha requested changes
Thanks, @Soundug, for contributing to the dotnet/docs repo and clarifying this paragraph. I've suggested a few changes.

2018-11-05 23:38 UTC, rpetrusha commented on docs/standard/net-standard.md
> +3. The column header indicates the .NET Standard version that your target supports. You may also target any lower .NET Standard. Higher .NET Standard will also support your implementation.
lower .NET Standard --> lower .NET Standard version
Higher .NET Standard --> Higher .NET Standard versions

2018-11-21 18:10 UTC, rpetrusha approved these changes

2018-11-24 22:36 UTC, richlander commented on docs/standard/net-standard.md
> +3. The column header indicates the .NET Standard version that your target supports. You may also target any lower .NET Standard version. Higher .NET Standard versions will also support your implement
How about:

```
The column header indicates the .NET Standard version that your chosen .NET implementation version supports. You may also target lower .NET Standard versions.
```

This part is true: `Higher .NET Standard versions will support your implementation.` I think it is almost an orthogonal topic, for two different reasons: compatibility is primary a function of the .NET implementation and less the standard and what the future looks like is a policy issue that isn't represented by this table.

2018-12-17 21:01 UTC, merged