Update how-to-join-content-from-dissimilar-files-linq.md
dotnet/docs pull request #8886
Opened 2018-11-06 03:13 UTC by KathleenDollard

In response to https://github.com/dotnet/docs/issues/8841

## Summary

Per issue, changed code to not output the ID, as it is not in the displayed output 

Fixes #8841

2018-11-06 17:12 UTC, rpetrusha requested changes
Thanks for addressing this issue, @KathleenDollard. Your change, though, returns the student ID, which isn't included in the output.

2018-11-06 17:12 UTC, rpetrusha commented on docs/visual-basic/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md
> +                            Select n(0) & "," & n2(0) & "," & n2(1) & "," &
This is incorrect. It should be:
```
                            Select n(0) & "," & n2(1) & "," & n2(2) & "," &  
                              n2(3) & "," & n2(4)  
```

2018-11-06 18:03 UTC, rpetrusha commented
Also, @KathleenDollard see my comments on the path in #8888

2018-12-14 22:50 UTC, mairaw reviewed
Just put it @rpetrusha comments in the form of suggestions so you can easily batch them and commit.

2018-12-14 22:50 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md
> +                            Select n(0) & "," & n2(0) & "," & n2(1) & "," &
```suggestion
                            Select n(0) & "," & n2(1) & "," & n2(2) & "," &  
```

2018-12-14 22:50 UTC, mairaw commented on docs/visual-basic/programming-guide/concepts/linq/how-to-join-content-from-dissimilar-files-linq.md
>                                n2(2) & "," & n2(3)
```suggestion
                               n2(3) & "," & n2(4)  
```

2019-02-06 20:32 UTC, closed without merging