Update link text
dotnet/docs pull request #9146
Opened 2018-11-20 05:36 UTC by imba-tjd

MSDN --> Default Marshaling Behavior

2018-11-20 16:46 UTC, rpetrusha requested changes
Thanks for improving this paragraph, @imba-tjd. I think that it can be improved still more, so I left some suggestions.

2018-11-20 16:46 UTC, rpetrusha commented on docs/standard/native-interop.md
> +The reason marshalling is needed is because the types in the managed and unmanaged code are different. In managed code, for instance, you have a `String`, while in the unmanaged world strings can be
This is an improvement, but the sentence doesn't read very well. Some suggestions:
- Right Thing --> right thing
- based on the default behavior which you...plus link --> based on the \[default behavior](../../docs/framework/interop/default-marshaling-behavior.md).
- MarshalAs can be a link: \[MarshalAs](xref:System.Runtime.InteropServicxes.MarshalAs)

2018-11-21 00:18 UTC, imba-tjd commented
OK, please review~

2018-11-21 17:39 UTC, rpetrusha approved these changes

2018-11-21 17:40 UTC, rpetrusha commented
Thanks, @imba-tjd, for making the additional changes. I think that your changes have substantially improved this topic. I'll merge your PR now.

2018-11-21 17:40 UTC, merged