Containerized Docker Application Lifecycle - Article 01.1
dotnet/docs pull request #9306
Opened 2018-11-29 17:02 UTC by mvelosop

## Summary

### e-book <--> docs.microsoft.com synchronization
- Chapter 01 - article 1

2019-02-12 19:19 UTC, mairaw requested changes
Small nits to fix but looks good overall

2019-02-12 19:19 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/index.md
>  ms.date: 09/22/2017
change ms.date?

2019-02-12 19:19 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/index.md
> +# Introduction to Containers and Docker
Previous title was the correct capitalization

```suggestion
# Introduction to containers and Docker
```

2019-02-12 19:19 UTC, mairaw commented on docs/standard/containerized-lifecycle-architecture/index.md
>  ms.author: wiwagn
can we fix the description here for SEO?

2019-02-13 10:40 UTC, mvelosop commented
@mairaw, we had already fixed metadata in PR https://github.com/dotnet/docs/pull/9305, so I just cherry-picked this commit and applied to a fresh branch (and fixed the title casing)

2019-02-13 10:40 UTC, closed without merging