Fixed typos
dotnet/docs pull request #9328
Opened 2018-11-30 19:23 UTC by CalvinAllen

## Summary

Fixed the typos (slight variation of the proposed fix for the second example)

Fixes #8854

2018-12-01 20:29 UTC, rpetrusha requested changes
Thanks for submitting this PR, @CalvinAllen. I really like the first correction that you made. I thought that the second could be streamlined a bit, though.

2018-12-01 20:41 UTC, CalvinAllen commented
Completely agree, that sounds a lot better!

2018-12-04 14:37 UTC, CalvinAllen commented
Sorry, @rpetrusha , scheduling conflicts keeping me from resolving this - will get on as soon as I can.

2018-12-04 14:37 UTC, CalvinAllen commented on docs/csharp/programming-guide/classes-and-structs/restricting-accessor-accessibility.md
> + When you override a property or indexer, the overridden accessors must be accessible to the overriding code. Also, the accessibility level of both the property/indexer, and that of the accessors, mu
Yeah, that sounds a lot better!

(moving comment from general comments to review)

2018-12-04 22:22 UTC, rpetrusha commented
No worries, @CalvinAllen. Thanks for making the additional changes. I'll merge your PR now. Your changes should be live on docs.microsoft.com in the next day or two.

2018-12-04 22:22 UTC, rpetrusha approved these changes

2018-12-04 22:22 UTC, merged