Revised true and false operators (and literals)
dotnet/docs pull request #9356
Opened 2018-12-03 20:09 UTC by pkulikov

Fixes #8444

As I was around, I also went through the articles about `true`/`false` literals.

Supported by dotnet/samples#493 (thanks to @BillWagner for the example)

2018-12-04 16:01 UTC, BillWagner reviewed
This looks great @pkulikov 

I'll add the "Hold for related PR" label, and give it a final review after we've merged the associated samples.

Thanks again for contributing to docs!

2018-12-05 16:01 UTC, BillWagner commented
closing and reopening to start a new build

2018-12-05 16:28 UTC, BillWagner requested changes
This looks great @pkulikov 

We need to fix the links before I :shipit:.

I had one other thought for a (possible) later PR, but I'd like your thoughts first.

2018-12-05 16:40 UTC, pkulikov commented on docs/csharp/language-reference/keywords/true-operator.md
> +For the example that defines both `true` and `false` operators, see the [false operator](false-operator.md) article.
Completely agree with that! Yes, let's make it another PR. I will create one.

2018-12-05 16:44 UTC, pkulikov commented
@BillWagner thanks for review, I've addressed your feedback

2018-12-05 18:38 UTC, BillWagner approved these changes

2018-12-05 18:38 UTC, merged