Updated page for Compiler Error CS0116
dotnet/docs pull request #9397
Opened 2018-12-05 02:43 UTC by jmarkman

## Summary

I tackled these aspects of the page:

* Updated the code sample

Previously, the sample was extremely bare bones and only covered methods existing out of the scope of a class. I added some fields (three variables and an autoproperty), changed the methods to be more concrete concepts (latitude and longitude coordinates rather than Method and Method2), and included a struct. I also placed comments in the code samples pointing out what would make the compiler grumpy and what wouldn't. I also made everything public - while it isn't a Best Practice™, it'll allow those reading/learning to simply copy-paste the code into their editor without running into any accessibility issues.

As the issue actually requested, I added a version of the code sample that would compile. However, the previous sample didn't have a main method. Neither does this one. Both will trigger CS5001. I'm not sure if the snippet should have a main method, I'll leave that for the review of the PR.

* Expanded on the actual text on the page

Just lifted what @BillWagner said in his comment and applied it to the leading short paragraph. However, I also expanded on what would actually happen if the user pasted the compiler-triggering code example into their editor of choice (stuck with Visual Studio because hey, it's docs.***microsoft***.com, right?). I removed the bit about C/C++ programmers because there are plenty of other languages out there where the C# structure is a foreign concept. Scripting languages like Javascript and Python come to mind.

I also added an inline link to the [General Structure of a C# Program](../../../csharp/programming-guide/inside-a-program/general-structure-of-a-csharp-program.md) article even though it was listed in the **See Also** section.

Fixes #9204

2018-12-05 15:49 UTC, BillWagner requested changes
Overall, this is great @jmarkman 

Once you address these comments, it's ready to go.

Thanks for contributing to .NET docs.

2018-12-05 15:49 UTC, BillWagner commented on docs/csharp/language-reference/compiler-messages/cs0116.md
> +A namespace cannot directly contain members such as fields or methods. However, a namespace can contain other namespaces, structs, and classes. For more information, see the [namespace keyword](../ke
When you split these paragraphs, I'd remove "However" from the start of the next paragraph.

2018-12-05 15:49 UTC, BillWagner commented on docs/csharp/language-reference/compiler-messages/cs0116.md
> +    // Even if there's a properly defined class and method or a properly defined struct
I'd remove this comment. I think it distracts from the explanation.

2018-12-05 17:06 UTC, jmarkman commented on docs/csharp/language-reference/compiler-messages/cs0116.md
> +A namespace cannot directly contain members such as fields or methods. However, a namespace can contain other namespaces, structs, and classes. For more information, see the [namespace keyword](../ke
Got it, will fix.

2018-12-06 15:57 UTC, BillWagner approved these changes

2018-12-06 15:57 UTC, BillWagner commented
Thanks for making this changes @jmarkman I'll :shipit: now.

Thanks again for contributing to docs.

2018-12-06 15:58 UTC, BillWagner commented
Thanks for making this changes @jmarkman I'll :shipit: now.

Thanks again for contributing to docs.

2018-12-06 15:58 UTC, BillWagner commented
Thanks for making this changes @jmarkman I'll :shipit: now.

Thanks again for contributing to docs.

2018-12-06 15:59 UTC, BillWagner commented
Thanks for making this changes @jmarkman I'll :shipit: now.

Thanks again for contributing to docs.

2018-12-06 15:59 UTC, merged

2018-12-06 15:59 UTC, BillWagner commented
Thanks for making this changes @jmarkman I'll :shipit: now.

Thanks again for contributing to docs.