Added package option details to dotnet list
dotnet/docs pull request #9590
Opened 2018-12-13 19:16 UTC by anangaur

## Summary

Added `package` option with `dotnet list`

Fixes #Issue_Number (if available)

2018-12-13 19:42 UTC, zivkan reviewed
From memory, `dotnet list package` also supports the `.sln` file as an argument, then it will show package references from all projects in the sln.

Also, there are several list package specific arguments (transitive, outdated, others). Should these be documented?

2018-12-13 19:42 UTC, zivkan commented on docs/core/tools/dotnet-list-reference.md
> +  dotnet list package app/app.csproj reference
package goes after the csproj, and remove the reference that's already after it

2018-12-13 19:43 UTC, zivkan commented on docs/core/tools/dotnet-list-reference.md
> +  dotnet list package app/app.csproj reference
in other words, change the line to
`dotnet list app/app.csproj package`

2018-12-14 19:21 UTC, mairaw requested changes
Thanks for your contribution @anangaur. But this should be added as a new topic along with https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-add-package.

2019-01-26 02:43 UTC, anangaur commented
I didn’t get a chance to revisit this. When do you plan to make your changes?

2019-01-26 02:51 UTC, mairaw commented
Hopefully next week!

2019-01-26 04:50 UTC, anangaur commented
Then yes. Please do add this in your changes too 🙂

2019-01-30 09:07 UTC, mairaw commented
Closing since I've created #10227 with the new article. Please review.

2019-01-30 09:07 UTC, closed without merging