Spelling fix
dotnet/docs pull request #9626
Opened 2018-12-16 14:25 UTC by ThePiranha

## Summary

Fixed spelling and completed missing words in sentence.

2018-12-17 01:27 UTC, douglaslMS requested changes
@ThePiranha Thank you for catching these issues. In the 2nd of your 3 fixes, will you please change "users providing" to "users to provide" so it reads "...without requiring users to provide a user name or password." Thank you! Then I'll sign off to merge your fixes.

2018-12-17 03:12 UTC, mairaw commented on docs/framework/data/adonet/sql/authentication-in-sql-server.md
> + With Windows authentication, users are already logged onto Windows and do not have to log on separately to SQL Server. The following `SqlConnection.ConnectionString` specifies Windows authentication
```suggestion
 With Windows authentication, users are already logged onto Windows and do not have to log on separately to SQL Server. The following `SqlConnection.ConnectionString` specifies Windows authentication without requiring users to provide a user name or password.  
```

2018-12-17 03:13 UTC, mairaw commented
Left @douglaslMS comment in form of suggestion so it's easier to apply the feedback.

2018-12-17 21:54 UTC, douglaslMS approved these changes

2018-12-17 21:54 UTC, merged

2018-12-18 17:59 UTC, ThePiranha commented
![image](https://user-images.githubusercontent.com/9007981/50173124-c9251c00-0320-11e9-8335-2dfb5029f729.png)
for considering this PR.