Added mutually recursive records example to records documentation
dotnet/docs pull request #9664
Opened 2018-12-18 21:37 UTC by iwasdavid

## Added mutually recursive records example to records documentation

I have added a code example for creating mutually recursive record types as I couldn't find any information about them on the official documentation.

I noticed in the records.md file, some of the snippets were defined in the markdown file but most were in the samples repo. I have added the code inline but can move to the samples repo if desired.

2018-12-18 21:37 UTC, dnfclas commented
[![CLA assistant check](https://cla.dotnetfoundation.org/pull/badge/not_signed)](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=9664) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=9664) before we can accept your contribution.<br/><br/>:x: iwasdavid [sign now](https://cla.dotnetfoundation.org/dotnet/docs?pullRequest=9664)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/dotnet/docs?pullRequest=9664) it.</sub>

2018-12-19 00:29 UTC, cartermp requested changes
Thanks @iwasdavid! I love the addition. A few suggestions and then this should be good to go.

2018-12-19 02:34 UTC, iwasdavid commented on docs/fsharp/language-reference/records.md
> +```fsharp
Yeah I almost didn’t put that bit in! I’ll get rid of that when I get to a PC.

2018-12-19 06:54 UTC, cartermp approved these changes

2018-12-19 16:25 UTC, merged