Update regular-expression-language-quick-reference.md
dotnet/docs pull request #9708
Opened 2018-12-21 03:37 UTC by NextTurn

This label is not referenced anywhere else.

2018-12-21 20:00 UTC, mairaw requested changes
Thanks for your contribution @NextTurn! I think we can just remove that customized anchor.

2018-12-22 08:29 UTC, mairaw approved these changes
Thanks for making the change.

2018-12-22 08:29 UTC, merged

2018-12-22 10:09 UTC, NextTurn commented
I don't quite understand. Does it mean that other customized anchors should also be removed?

```
<a name="quantifiers"></a>   
## Quantifiers  
```

If not, why should I remove it?

2018-12-23 00:14 UTC, mairaw commented
We usually use customized ones when heading titles are too long or complicated. I think the other ones in this topic could also be reviewed to use the automated ones.