Refresh io task topics
dotnet/docs pull request #9776
Opened 2018-12-29 00:59 UTC by v-thepet

## Summary

Refresh 
how-to-copy-directories
how-to-enumerate-directories-and-files

Part of User Story
https://mseng.visualstudio.com/TechnicalContent/_workitems/edit/1374049

2019-01-07 18:30 UTC, v-thepet commented
@rpetrusha - Ready for your review per Task https://mseng.visualstudio.com/TechnicalContent/_queries/edit/1385009/?triage=true. Thanks.

2019-01-10 01:39 UTC, rpetrusha requested changes
Thanks, @v-thepet. Your changes look good. I've also suggested some additional changes, as well as some changes to modernize the code examples.

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +|File system entry information (<xref:System.IO.FileSystemInfo>)|<xref:System.IO.DirectoryInfo.EnumerateFileSystemInfos%2A?displayProperty=nameWithType>|
One item to add:
|Directory and file names | \<xref:System.IO.Directory.EnumerateFileSystemEntries%2A?displayProperty=nameWithType>|

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +[!code-csharp[System.IO.Directory.EnumerateFiles#1](../../../samples/snippets/csharp/VS_Snippets_CLR_System/system.io.directory.enumeratefiles/cs/program.cs#1)]
in the example:
- in the VB example, there should be a blank line between the last `Imports` statement and the Module statement.
- the exception names should use camel casing or just be `ex`
- the 2 Console.WriteLine statements with format strings should be replaced with interpolated strings..

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +[!code-csharp[System.IO.EnumDirs1#1](../../../samples/snippets/csharp/VS_Snippets_CLR_System/system.io.enumdirs1/cs/program.cs#1)]
in the example:
- delete `using System.Linq`;
- exception names should use camel casing. We generally just name an exception variable `ex`.
- we've been replaying format strings with interpolated strings; so:   
   - `$"{0}", dir.Substring(dir.LastIndexOf("\\") + 1)` --> `"{dir.Substring(dir.LastIndexOf("\\") + 1)}"`
   - "{0} directories found.",  dirs.Count --> $"{dirs.Count} directories found."

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +[!code-csharp[System.IO.DirectoryInfo.EnumDirs#1](../../../samples/snippets/csharp/VS_Snippets_CLR_System/system.io.directoryinfo.enumdirs/cs/program.cs)]
- In the C# example, only the first two `using` statements are needed.
- The VB example should have a full example that corresponds to the C# example, not just a fragment
- indentation in the C# example should be fixed.
- See if the Snippet1 tag is used elsewhere in the dotnet/docs or dotnet/dotnet-api-docs repos (search for "directoryinfo.enumdirs#1"). If it's not, delete it.

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +The following example uses the <xref:System.IO.DirectoryInfo.EnumerateDirectories%2A?displayProperty=nameWithType> method to list a collection of top-level directories whose DateTime DirectoryInfo ma
```suggestion
The following example uses the <xref:System.IO.DirectoryInfo.EnumerateDirectories%2A?displayProperty=nameWithType> method to list a collection of top-level directories whose <xref:System.IO.DirectoryInfo.CreationTimeUtc> is earlier than a certain <xref:System.DateTime> value.  

```

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +The following example uses the <xref:System.IO.DirectoryInfo.EnumerateFiles%2A?displayProperty=nameWithType> method to list all directories and all files whose Length FileInfo matches a certain patte
```suggestion
The following example uses the <xref:System.IO.DirectoryInfo.EnumerateFiles%2A?displayProperty=nameWithType> method to list all files whose <xref:System.IO.FileInfo.Length> exceeds 10MB. This example first enumerates the top-level directories to catch possible unauthorized access exceptions, and then enumerates the files.  
```

2019-01-10 01:39 UTC, rpetrusha commented on docs/standard/io/how-to-enumerate-directories-and-files.md
> +[!code-csharp[System.IO.DirectoryInfo.EnumerateDirectories#1](../../../samples/snippets/csharp/VS_Snippets_CLR_System/system.io.directoryinfo.enumeratedirectories/cs/program.cs#1)]
In the code examples:
- use interpolated strings except for the VB line that includes vbTab twice. That's best as a format string, with vbTab as one of the format items.
- in the VB example, delete `Imports System`
- exception variable names should be changed (camel cased or just `ex`)

2019-01-18 18:02 UTC, v-thepet commented
@rpetrusha - Changes are ready for review and in https://github.com/dotnet/samples/pull/574. Thanks.

2019-01-22 01:47 UTC, v-thepet commented
@rpetrusha - Code changes are made in dotnet/samples#574.

2019-01-22 17:16 UTC, rpetrusha commented
Closing and reopening to begin new build after dotnet/samples#574 was merged.

2019-01-22 17:30 UTC, v-thepet commented
@rpetrusha - Thanks for merging the code PR, this one should be ready for merge now. Thanks.

2019-01-22 18:53 UTC, rpetrusha approved these changes

2019-01-22 18:53 UTC, rpetrusha commented
This looks good, @v-thepet. I'll merge now.

2019-01-22 18:53 UTC, merged