C57279: Correcting bold format and escaping square brackets
dotnet/docs pull request #9829
Opened 2019-01-04 16:47 UTC by v-maudel

Hello, @rpetrusha , @drewnoakes,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version.
Description: There is problem with strings that are written for example like this one - "/a[ssembly]:". Based on the content in source it doesn't make sense to write it like this, because for example there is also string "/c[ompiler]:", which has brackets "[]" in bold as well. We suggest to keep it consistent and write all strings like the second one, so it works on localized languages too.

Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR then share your PR number so we can confirm and close this PR.
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-01-05 02:52 UTC, rpetrusha approved these changes
I've made some additional formatting changes, so I'll merge once the build completes, @v-maudel..

2019-01-05 03:23 UTC, mairaw requested changes
Please create a new PR targeting the master branch @v-maudel.

2019-01-07 14:45 UTC, v-maudel commented
Thanks @mairaw  for pointing out this was created in the Live Branch and sorryu for the inconveniences, I didn't notice it when I created the PR. 
I've created a new [PR](https://github.com/dotnet/docs/pull/9871) and also added the changes made by @rpetrusha.

regards.

2019-01-07 17:50 UTC, rpetrusha commented
Thanks for noticing that this targeted live, @mairaw. 
I'll close this PR now, since it's replaced by #9871.

2019-01-07 17:50 UTC, closed without merging