Minor update, clarification.
dotnet/docs pull request #9878
Opened 2019-01-07 23:50 UTC by CESARDELATORRE

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-01-08 00:47 UTC, mairaw requested changes
Looks good to me but left a few suggestions for improving those sentences

2019-01-08 00:47 UTC, mairaw commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md
> +The essence of those patterns, and the important point here, is that queries are idempotent: no matter how many times you query a system, the state of that system will not change. In other words, que
```suggestion
The essence of those patterns, and the important point here, is that queries are idempotent: no matter how many times you query a system, the state of that system won't change. In other words, queries are side-effect free.
```

2019-01-08 00:47 UTC, mairaw commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md
> +Therefore, you could use a different “reads” data model than the transactional logic “writes” domain model, although the ordering microservices is using the same database. Hence this is a simplified
```suggestion
Therefore, you could use a different “reads” data model than the transactional logic “writes” domain model, even though the ordering microservices are using the same database. Hence, this is a simplified CQRS approach.
```

2019-01-17 01:35 UTC, CESARDELATORRE commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md
> +The essence of those patterns, and the important point here, is that queries are idempotent: no matter how many times you query a system, the state of that system will not change. In other words, que
👍

2019-01-17 01:36 UTC, CESARDELATORRE commented on docs/standard/microservices-architecture/microservice-ddd-cqrs-patterns/eshoponcontainers-cqrs-ddd-microservice.md
> +Therefore, you could use a different “reads” data model than the transactional logic “writes” domain model, although the ordering microservices is using the same database. Hence this is a simplified
👍 Good to go!

2019-01-17 02:20 UTC, mairaw approved these changes
Thanks @CESARDELATORRE!

2019-01-17 02:20 UTC, merged