C54009: Asterisk issue
dotnet/docs pull request #9883
Opened 2019-01-08 11:06 UTC by v-makoud

Hello, @rpetrusha,
Localization team has reported source content issue that causes localized version to have broken/different format compared to en-us version. 
Please review and merge the proposed file change to fix to target versions. If you make related fix in another PR  then share your PR number so we can confirm and close this PR.
Many thanks in advance.

## Summary

Describe your changes here.

Fixes #Issue_Number (if available)

2019-01-08 17:13 UTC, mairaw requested changes
Looks good to me @v-makoud but I'm wondering if you also need to make the same change on the previous paragraph.

2019-01-08 17:13 UTC, mairaw commented on docs/standard/asynchronous-programming-patterns/blocking-application-execution-by-ending-an-async-operation.md
>  -   Use the <xref:System.IAsyncResult.AsyncWaitHandle%2A> property of the <xref:System.IAsyncResult> returned by the asynchronous operation's **Begin***OperationName* method. For an example that demo
I imagine you'd have the same issue here, no?

2019-01-11 08:38 UTC, v-makoud commented
thanks @mairaw, I think so, but let me just check with the bug fixing team to be sure

2019-01-11 13:04 UTC, v-makoud commented
they agree, i made the change

2019-01-16 22:43 UTC, mairaw approved these changes

2019-01-16 22:43 UTC, merged