Update examples
dotnet/docs pull request #9930
Opened 2019-01-10 16:02 UTC by NextTurn

Fixes #9875 
Fixes #9874 

Contributes to #9781 

Remove redundant references

2019-01-10 17:19 UTC, BillWagner requested changes
Overall, this is a great set of changes @NextTurn 

I'd like to keep the links to the keyword references for `async` and `await` (that way, these samples don't have to define those in detail).

If you make that update, I'll :shipit:

2019-01-10 17:19 UTC, BillWagner commented on docs/csharp/programming-guide/concepts/async/index.md
> - If you specify that a method is an async method by using the [async](../../../../csharp/language-reference/keywords/async.md) modifier, you enable the following two capabilities.
I'd like to keep the links to the keywords here.

2019-01-10 17:19 UTC, BillWagner commented on docs/csharp/programming-guide/concepts/async/index.md
> +-   The marked async method can use `await` to designate suspension points. The `await` operator tells the compiler that the async method can't continue past that point until the awaited asynchronous
Same comment: Let's preserve the links.

2019-01-15 02:56 UTC, NextTurn commented
I assume that the following references are redundant

https://github.com/dotnet/docs/blob/f46493f2c26510ebfdd4567eaf5e72613d8d56dc/docs/csharp/programming-guide/concepts/async/index.md#L158-L163

2019-01-25 13:20 UTC, NextTurn commented
Hi @BillWagner, don't forget this.

2019-01-28 14:33 UTC, NextTurn commented
I assume that the following references are redundant

https://github.com/dotnet/docs/blob/f46493f2c26510ebfdd4567eaf5e72613d8d56dc/docs/csharp/programming-guide/concepts/async/index.md#L158-L162

2019-02-05 02:09 UTC, NextTurn commented
@BillWagner

2019-02-05 02:10 UTC, NextTurn commented
Welcome back from London @BillWagner

2019-02-05 16:20 UTC, BillWagner approved these changes

2019-02-05 16:21 UTC, merged